### ISSUE TITLE
GetStorageItemAsync in DragEnter only works once

### ISSUE THREAD

**Issue by bjorn-malmo** [microsoft/microsoft-ui-xaml#8108] opened 2023-01-18 14:02 UTC
### Describe the bug

Enumerating DataView.GetStorageItemsAsync() in the DragEnter event handler works when dropping files for the first time in an application.
The next drag and drop operation will not be allowed.

### Steps to reproduce the bug

Create a page with an element having AllowDrop=True and subscribe to the DragEnter and Drop events.

In the DragEnter event handler, enumerate the files being dragged, i.e. to inspect ContentType

```
    async void Grid_DragEnter(object sender, DragEventArgs e)
    {
        var items = await e.DataView.GetStorageItemsAsync();

        e.AcceptedOperation = Windows.ApplicationModel.DataTransfer.DataPackageOperation.Copy;
    }
```

The first time, this will work as expected and a Copy operation will be indicated to the user. 
The next operation will indicate Drop not allowed, and the Drop event will not be fired.

Enumerating the files in the Drop event works every time.

### Expected behavior

I think it should be possible to inspect the files being dragged, to check the ContentType of the files and determine if a Drag-and-drop operation can be initiated

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 10 (21H2): Build 19044

**Comment by bpulliam** [comment] 2023-07-07 22:22
Given the work we have done on drag and drop issues, Please try this on a newer build and see if you still see the issue.

**Comment by JJBrychell** [comment] 2023-07-20 04:09
I believe that I have been able to repro this, but only in a managed application.  The issue seems to be not that you can't inspect the file(s) retrieved by GetStorageItemsAsync (getting items collection and checking counts returns the correct data), however, the issue is that the accepted option is (for some unexplained reason) not getting processed correctly and thus the icon does not change to indicate that the item(s) are copyable.  I have confirmed that Xaml appears to be setting it correctly (passing it through from the application to the DataTransfer object).  But we are somehow getting into a state where that is not getting processed correctly.

**Comment by JJBrychell** [comment] 2023-07-20 23:51
I have an idea about what is going on, but I also may have a workaround.  I have been able to get the storage items to work consistently by setting the AcceptedOperation BEFORE accessing the storage items.  Something seems to be corrupting the data transfer object and so the AcceptedOperation is not being correctly marshaled to DataExchangeHost if set after accessing the storage items.

**Comment by JJBrychell** [comment] 2023-07-25 19:07
As it turns out, this appears to be by design and the workaround I mentioned is the appropriate way to do this.

I am not overly familiar with c#, but I found this statement about the await operator in the documentation:

> The await operator doesn't block the thread that evaluates the async method. **When the await operator suspends the enclosing async method, the control returns to the caller of the method.**

So, what is happening is that when you await the GetStoarageItemAsync, the drag event itself is getting completed (we return from the event handler).  This causes the background drag/drop background process to immediately query the current state of the AcceptedOperation value (which has not been set yet) and so it assumes that the drop target does not want to handle a drop.  At some future point when the await operation completes, the accepted operation is updated, but that value is never queried again by the drag/drop background process and in reality, it has probably already moved on to the next drag event.

Since this is a timing issue between the application process and the background drag drop process (DataExchangeHost), it is not uncommon to see different behavior with the first invocation of the scenario.  In my case, I was seeing a load library occur which probably changes the scheduling of the time slices and makes it so that DataExchangeHost doesn't get notified of end of the event handler until the async part of the event is complete as well.

Further expanding the suggested way of doing this.  This would make it difficult to tailor your accepted operation to the data in the storage items (e.g. are they files of the correct type of the correct number).  However, you can get around this by querying in the enter event and storing this information and setting it in future over events.

Closing as by design.

**Closed by JJBrychell** 2023-07-25 19:07 UTC
Labels: bug, team-Rendering, by design
