### ISSUE TITLE
Discussion: Roadmap / What to expect for WinUI3 design in VS?

### ISSUE THREAD

**Issue by ivberg** [microsoft/microsoft-ui-xaml#5174] opened 2021-06-11 14:00 UTC
# Discussion: Roadmap / What to expect for WinUI3 design in VS?
I have seen very little that I could find on the roadmap discussing what to expect for UI design assistance in VS (for WinUI3). I sort of hoped that there would be better support/design assistance in Visual Studio with 16.10.1 but that doesn't seem to be the case.

What is the plan, timeline, or roadmap that details better support of UI design in VS with WinUI3?

For C# devs coming from WPF, this is a downgrade with regards to UI design in VS, and there seems to be little information when this will be corrected.

## Related Links
This is helpful but VS is conspicuously absent - https://github.com/microsoft/microsoft-ui-xaml/issues/1688

**Comment by mdtauk** [comment] 2021-06-11 16:15
I suspect there may be a push for everyone to move to writing Xaml by hand (with autocomplete) and using Hot Reload to do the design testing.  Much like HTML and CSS, with the browser for viewing.

Then there is the possibility of C# Markup also using Hot Reload.

I like the fact SwiftUI has a good designer surface and tooling, along with the preview functionality of Kotlin's Jetpack Compose.

I would love a really polished designer for all varieties of Xaml and WinForms.

![image](https://user-images.githubusercontent.com/7389110/121715765-2ad03680-cad7-11eb-90ee-ca6dd3cfd636.png)
![image](https://user-images.githubusercontent.com/7389110/121716481-fe68ea00-cad7-11eb-9932-e564a7c1ba5f.png)

**Comment by huoyaoyuan** [comment] 2021-06-12 19:25
Debug Tools like Live Visual Tree was already supported since 16.9 *Preview*, but intentionally not shipped with Release Channel.

**Comment by mdtauk** [comment] 2021-06-12 20:19
> Debug Tools like Live Visual Tree was already supported since 16.9 _Preview_, but intentionally not shipped with Release Channel.
>
Its the Designer view that is currently missing, and without a guaranteed future as part of the tooling.

**Comment by asklar** [comment] 2021-07-23 04:57
Duplicate of #4195

**Closed by asklar** 2021-07-23 04:57 UTC
Labels: area-Tooling, discussion, needs-triage, product-winui3, team-Markup

**Comment by sasakrsmanovic** [comment] 2024-11-20 04:27
There is no need to write XAML by hand. ... Hot Design from Uno Platform achieves this goal of being a Visual Dsigner for WinUI 3 (and other targets) in Visual Studio. 

https://github.com/unoplatform/uno/discussions/18833
.NET Conf 2024 Session on Hot design:
https://www.youtube.com/watch?v=sJPyieyt1Rc&list=PLdo4fOcmZ0oXeSG8BgCVru3zQtw_K4ANY&index=93
