### ISSUE TITLE
ItemsControl not get updated while dynamically adding or removing items in its itemsource collection.

### ISSUE THREAD

**Issue by VigneshRameshh** [microsoft/microsoft-ui-xaml#3517] opened 2020-10-29 09:52 UTC
**Describe the bug**
I have a simple ItemsControl and bind the string ObservableCollection to its ItemsSource. If I change the collection dynamically, then the ItemsControl not get refreshed/updated.

**Steps to reproduce the bug**
1.Run the sample [WinUITest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5457413/WinUITest.zip)
2.Click Add/Remove button
3.You can see, the ItemsControl not get updated.

**Expected behavior**
The ItemsControl should be updated, while dynamically adding or removing the items in collection.

**NuGet package version:**
3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| OS version : 1903 Build : 18363.1139            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
If I checked the same codes in UWP platform, it is working fine.

**Comment by syncsiva** [comment] 2020-11-09 04:39
Team: Any update on this?

**Comment by dotMorten** [comment] 2020-11-18 06:25
Same issue in Preview 3 when using UWP (Works in Win32)

**Comment by dpaulino** [comment] 2020-11-18 06:49
Big showstopper for me. I won't even bother trying the preview or any WinUI 3 production builds unless this is fixed for UWP. I hope this issue is addressed before WinUI 3 is released for UWP.

**Comment by dotMorten** [comment] 2020-11-18 07:08
I did find that if I implement `Microsoft.UI.Xaml.Interop.INotifyCollectionChanged` in a custom class, I can sort of make it work, but it's not a trivial interface to implement (mostly due to the EventRegistrationToken you need to manage) and [doc even tells you not to implement it from .NET](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Interop.INotifyCollectionChanged?view=winrt-19041#remarks).

Here's my very crude class that at least supports adding items. There's a LOT of TODOs though...

```cs

        public class INCCCollection<T> : ObservableCollection<T>, Microsoft.UI.Xaml.Interop.INotifyCollectionChanged
        {
            protected override void OnCollectionChanged(NotifyCollectionChangedEventArgs e)
            {
                base.OnCollectionChanged(e);
                var handler = _collectionChanged;
                if (handler != null) {
                    Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction action = Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction.Reset;
                    switch (e.Action)
                    {
                        case NotifyCollectionChangedAction.Add: action = Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction.Add; break;
                        case NotifyCollectionChangedAction.Remove: action = Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction.Remove; break;
                        case NotifyCollectionChangedAction.Reset: action = Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction.Reset; break;
                        case NotifyCollectionChangedAction.Move: action = Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction.Move; break;
                        case NotifyCollectionChangedAction.Replace: action = Microsoft.UI.Xaml.Interop.NotifyCollectionChangedAction.Replace; break;
                    }
                    handler?.Invoke(this, new Microsoft.UI.Xaml.Interop.NotifyCollectionChangedEventArgs(action, new Vector(e.NewItems), new Vector(e.OldItems), e.NewStartingIndex, e.OldStartingIndex));
                }
            }

            private event Microsoft.UI.Xaml.Interop.NotifyCollectionChangedEventHandler _collectionChanged;

            event Microsoft.UI.Xaml.Interop.NotifyCollectionChangedEventHandler
                Microsoft.UI.Xaml.Interop.INotifyCollectionChanged.CollectionChanged
            {
                add { _collectionChanged += value; return new EventRegistrationToken(/*TODO*/); }
                remove { /*TODO*/  }
            }

            private class Vector : Microsoft.UI.Xaml.Interop.IBindableVector
            {
                private System.Collections.IList _items;
                public Vector(System.Collections.IList items) { _items = items; }
                public object GetAt(uint index) => _items[(int)index];
                public bool IndexOf(object value, out uint index)
                {
                    int i = _items.IndexOf(value);
                    index = i < 0 ? 0 : (uint)i;
                    return i > -1;
                }
                public uint Size => (uint)_items.Count;
                public Microsoft.UI.Xaml.Interop.IBindableVectorView GetView() => throw new NotImplementedException("TODO");
                public void SetAt(uint index, object value) => throw new NotImplementedException("TODO");
                public void InsertAt(uint index, object value) => throw new NotImplementedException("TODO");
                public void RemoveAt(uint index) => throw new NotImplementedException("TODO");
                public void Append(object value) => throw new NotImplementedException("TODO");
                public void RemoveAtEnd() => throw new NotImplementedException("TODO");
                public void Clear() => throw new NotImplementedException("TODO");
                public Microsoft.UI.Xaml.Interop.IBindableIterator First() => throw new NotImplementedException("TODO");
            }
        }
```

**Comment by prashant-gupta-dev** [comment] 2020-11-18 15:17
This is a show stopper for me. .

**Comment by MikeHillberg** [comment] 2020-12-15 17:27
I think this is fixed now in cs/winrt: https://github.com/microsoft/CsWinRT/issues/286

**Comment by dotMorten** [comment] 2020-12-15 17:30
@MikeHillberg not for UWP which this issue is for

**Comment by BorzillaR** [comment] 2020-12-21 09:53
@dotMorten, did you try to use workaround as described [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#known-issues)?

[CollectionsInterop sample](https://github.com/microsoft/Xaml-Controls-Gallery/blob/winui3preview/XamlControlsGallery/CollectionsInterop.cs)

**Comment by anawishnoff** [comment] 2021-02-02 18:50
This bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by sheiksyedm** [comment] 2021-02-16 11:04
@anawishnoff  Fix is not moved to the WinUI 3 Preview 4 release. Can you confirm, which release fix is going to move?

**Comment by anawishnoff** [comment] 2021-02-16 15:10
@codendone Any more info here? Looks like this is still reproducing in Preview 4.

**Comment by codendone** [comment] 2021-02-18 03:28
@JesseCol?

**Comment by JesseCol** [comment] 2021-02-18 16:16
My apologies -- I tried this out on an Preview 4 candidate build and I wasn't able to repro.  I must have done something wrong, I'll take a closer look.

**Comment by ssaran046** [comment] 2021-05-12 09:24
This issue is reproduced on all the items control like ItemsRepeater, ListBox, ListView, GridView controls.

**Comment by ssaran046** [comment] 2021-06-16 12:21
Hi Team,

Any update on this?

**Comment by anawishnoff** [comment] 2021-06-16 14:11
@JesseCol were you ever able to repro this issue in a later version of WinUI 3?

**Closed** 2023-01-11 15:09 UTC
Labels: team-Controls, product-winui3, fixed-internally
