### ISSUE TITLE
SwipeControl (WUX/MUX) causes random crashes in ListView

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#2527] opened 2020-05-21 22:55 UTC
**Describe the bug**

Scrolling down a `ListView` with a large number of items, each having a `SwipeControl` in its template, randomly triggers a crash. By "randomly" I mean the crash happens when scrolling, at _some point_, which varies every time. The same crash happens with:

- A custom control which has the `SwipeControl` in its template
- The `Windows.UI.Xaml.Controls.SwipeControl`
- The `Microsoft.UI.Xaml.Controls.SwipeControl` (WinUI `2.4.2`)

**Steps to reproduce the bug**

1. Download the repro: [SwipeItemsCrashRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4691050/SwipeItemsCrashRepro.zip)
2. Build and run the app
3. Scroll to the bottom, and eventually back up

> **NOTE:** the repro uses the `MarkdownTextBlock` from the toolkit, which for some reason causes the crash to happen much more rapidly. Replacing it with just a `TextBlock` still causes the crash, but you then need to scroll up and down for quite a bit before observing the crash, for some reason.

I also prepared two crash dumps, one with the WUX control and one with the MUX one:
- [Crash dump with Windows.UI.Xaml.Controls.SwipeItems](https://1drv.ms/u/s!AjTEhZcuNvx2zewqSuUNzSUPXGK7EA?e=VnbXbc)
- [Crash dump with Microsoft.UI.Xaml.Controls.SwipeItems](https://1drv.ms/u/s!AjTEhZcuNvx2zewrfyL-eT-K4Tv3Sg?e=RLmZyy)

**Expected behavior**

Scrolling down the list should work as expected.

**Screenshots**

![XT7xwwFwJm](https://user-images.githubusercontent.com/10199417/82613468-a22de200-9bc5-11ea-9ec6-d3761eb0ca47.gif)

**Version Info**

NuGet package version: 
- Microsoft.UI.Xaml `2.4.0`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19041.264)              |  Yes   |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by ranjeshj** [comment] 2020-05-27 15:17
@Sergio0694 Thanks for reporting. If you have a standalone repro app that you can share, that would be helpful. Thanks!

**Comment by Sergio0694** [comment] 2020-05-27 18:51
Hey @ranjeshj, thank you for chiming in!
I've managed to create a minimal repro, I've added a link to the main post! 😊

**Comment by ranjeshj** [comment] 2020-05-28 14:39
Hmm.. I'm not seeing the crash with the repro app with mouse wheel scroll or touch scroll. Does it crash immediately or take a while of usage ?

**Comment by Sergio0694** [comment] 2020-05-28 14:46
Huh, that's weird. Yeah it's pretty much instantaneous for me, I can repro this 100% of the time both in my app and in the repro project I shared. You're on Windows 10 19041 too, correct?

![2u4ovqDuyY](https://user-images.githubusercontent.com/10199417/83156352-9af55f80-a102-11ea-950c-4632fd3b2220.gif)

@kikisaints Have you had a chance to try the repro to see if it crashes on your PC too?

**Comment by michael-hawker** [comment] 2020-05-28 19:16
This crashed for me right away as soon as I grabbed the scrollbar and dragged down on 19041.

**Comment by StephenLPeters** [comment] 2020-05-28 20:06
Removing needs-winui-3 because I suspect this is a swipe issue and could maybe be fixed before winui3

**Comment by Sergio0694** [comment] 2020-05-28 20:14
Hey @StephenLPeters - that's amazing!
So glad to hear that, thank you for looking into this! 😊

**Comment by Felix-Dev** [comment] 2020-05-28 20:19
Crash does not happen on 18363.836 with 18362 SDK.

**Comment by Sergio0694** [comment] 2020-05-28 20:25
Thanks @Felix-Dev!
It really looks like this crash is only happening starting from Windows 10 19041 🤔

**Comment by ranjeshj** [comment] 2020-06-03 03:04
@StephenLPeters @michael-hawker If you can repro this, can you share the native callstack for the crash ?

**Comment by Sergio0694** [comment] 2020-07-27 22:36
Pinging @michael-hawker in case he missed the previous notification 😄

Also @kikisaints I was wondering if the two crash dumps I shared were useful?
Can't recall if I also shared them with @ranjeshj, in case I haven't and you'd like me to forward them to you just let me know!

**Comment by Sergio0694** [comment] 2023-07-29 15:08
I mean I'm pretty sure the bug is still there 😅

**Comment by bkaankose** [comment] 2024-07-26 12:17
@Sergio0694 it is indeed. I am able to reproduce this still.

**Comment by llongley** [comment] 2024-09-10 06:23
This should be fixed in the next version of WindowsAppSDK.

**Closed by llongley** 2024-09-10 06:23 UTC
Labels: bug, area-Lists, area-SwipeControl, team-Controls
