### ISSUE TITLE
No LayoutTransformControl in WinUI

### ISSUE THREAD

**Issue by ejserna** [microsoft/microsoft-ui-xaml#3493] opened 2020-10-26 21:08 UTC
**Describe the bug**
For #3492, we need a ````LayoutTransformControl````, which WinUI doesn't have (yet).

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by mdtauk** [comment] 2020-10-26 21:10
The Windows Community Toolkit has one
https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/layouttransformcontrol

**Comment by ranjeshj** [comment] 2020-10-26 23:06
WPF supports LayoutTransform in the framework so this is a gap. Unfortunately render transform does not update the layout bounds of the element.

**Comment by mdtauk** [comment] 2020-10-26 23:18
> WPF supports LayoutTransform in the framework so this is a gap. Unfortunately render transform does not update the layout bounds of the element.
>

The need for it in WinUI is to enable the new Expander control to be able to expand to the Left or Right.

In time, this may also allow for Vertical Tabs which can be rotated and placed to the left or right.

**Comment by robloo** [comment] 2020-10-27 23:44
LayoutTransform really needs to be in the framework itself like RenderTransform. What was done in the WCT to create a separate control is only a work-around.

**Comment by michael-hawker** [comment] 2020-12-08 19:31
🦙 @chrisglein FYI, this is a duplicate of #546. I had added it early on specifically because of Expander and it's usefulness in other scenarios for the WPF gap.

**Comment by chrisglein** [comment] 2020-12-09 00:42
Duplicate of #546

**Closed by chrisglein** 2020-12-09 00:42 UTC
Labels: feature proposal, team-Framework, wpf-vs-winui-mismatch
