### ISSUE TITLE
TreeView - AccessViolationException on remove an item

### ISSUE THREAD

**Issue by DehghaniHootan** [microsoft/microsoft-ui-xaml#2405] opened 2020-05-07 15:25 UTC
**Describe the bug**

**System.AccessViolationException**
{"Attempted to read or write protected memory. This is often an indication that other memory is corrupt."}

**Steps to reproduce the bug**

I have a TreeView which its ItemSource binded to a Collection. When i remove an Element in that Collection i got this Exception before i can handle it.

**Expected behavior**
I had no crash on version 2.3

**Screenshots**
![winui_2 4](https://user-images.githubusercontent.com/39124067/81313103-a671df80-909c-11ea-9d23-cc17652407ea.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.0-prerelease.200506001

Windows 10 Version 1909 Build 18363.778

| Desktop                 | yes |

**Comment by ranjeshj** [comment] 2020-05-07 20:08
@DehghaniHootan can you please share a repro app ?

**Comment by DehghaniHootan** [comment] 2020-05-08 02:10
> 
> 
> @DehghaniHootan can you please share a repro app ?

[Sample_app](https://github.com/DehghaniHootan/TV_Remove)
I find out that when i tried to remove a selected node that exception happen. so first i have to change isSelected to false. (in the sample_app when i hit remove button 2 times i got this exception)

**Comment by ranjeshj** [comment] 2020-05-08 12:43
@DehghaniHootan I am unable to repro this. When I hit the remove button twice I get this error which seems to be an app issue since SampleItems seems to be empty.

![image](https://user-images.githubusercontent.com/28935693/81406594-b4e8e700-90ee-11ea-8798-142078ff4ae9.png)

**Comment by DehghaniHootan** [comment] 2020-05-08 13:36
@ranjeshj don't you have these 3 Companies when you run the app. If not, LoadDataAsync method in TreeViewViewModel.cs does not do its job.
![Companies](https://user-images.githubusercontent.com/39124067/81410307-c1ecf100-9155-11ea-80e0-fd6f598ed5e4.png)

**Comment by chingucoding** [comment] 2020-06-10 23:41
Update: I've been able to reproduce the AccessViolation sometimes (not very often). After updating to the latest WinUI 2.5 prerelease, I wasn't able to reproduce the crashes anymore. 

@ranjeshj Should we close this issue?

**Comment by ranjeshj** [comment] 2020-06-11 12:54
Thanks @chingucoding. @DehghaniHootan Please give 2.5 prerelease a try. If you still hit the crash, please reopen this issue. Thanks!

**Comment by Going-Gone** [comment] 2020-08-26 14:32
@ranjeshj this does appear to be happening with the navigation view as well. 

If you try to set the MenuItemSource to a different collection the same exception occurs. If you first set the selected item to null, it allows the items source to be modified.

**Comment by Felix-Dev** [comment] 2020-08-26 14:53
@Going-Gone I cannot reproduce this on the newest 2.5 preview:

![navview-itemssource-change](https://user-images.githubusercontent.com/1398851/91319299-82a5e700-e7bc-11ea-985f-6bf7818477eb.gif)

Are you doing anything else or could you upload a repro app?

**Comment by Going-Gone** [comment] 2020-08-26 15:23
> 
> 
> @Going-Gone I cannot reproduce this on the newest 2.5 preview:
> 
> ![navview-itemssource-change](https://user-images.githubusercontent.com/1398851/91319299-82a5e700-e7bc-11ea-985f-6bf7818477eb.gif)
> 
> ("Change ItemsSource" button assigns a new list to the MenuItemsSource.)
> 
> Are you doing anything else or could you upload a repro app?

It appears that with the Top Pane mode, the exception happens, but it doesn't happen with Left pane mode.

**Comment by Felix-Dev** [comment] 2020-08-26 15:29
> It appears that with the Top Pane mode, the exception happens, but it doesn't happen with Left pane mode.

@Going-Gone Thanks! I can repro it now. I can take a look at this issue.

**Comment by Going-Gone** [comment] 2020-08-26 15:31
> 
> 
> > It appears that with the Top Pane mode, the exception happens, but it doesn't happen with Left pane mode.
> 
> @Going-Gone Thanks! I can repro it now. I can take a look at this issue.

Awesome, thanks.

**Comment by ranjeshj** [comment] 2020-09-01 20:41
Thanks @Going-Gone  and @Felix-Dev. Reopening this issue since we do have a repro.

**Comment by Felix-Dev** [comment] 2020-09-01 20:54
@ranjeshj I couldn't repoduce this for the **TreeView** control. @Going-Gone and I above managed to repro an issue in the **NavigationView** control here which is tracked by issue https://github.com/microsoft/microsoft-ui-xaml/issues/3200. I think you can close this issue here again until someone manages to repro this specific TreeView on the newest WinUI bits again.

Sorry for the confusion.

**Closed** 2020-09-01 22:00 UTC
Labels: area-TreeView, help wanted, team-Controls
