### ISSUE TITLE
[Preview 4]Window.Current.SetTitleBar  is not yet implemented for UWP in WinUI 3

### ISSUE THREAD

**Issue by weixingyao** [microsoft/microsoft-ui-xaml#4173] opened 2021-02-12 04:59 UTC
**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|          Yes        |           No          | 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |             Yes          |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |            Yes        |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment] 2021-02-13 00:25
@Austin-Lamb and @pratikone FYI.  I think this is by design but others should correct me if I'm wrong, in UWP I think you have to use the ExtendViewIntoTitleBar property. here is some documentation: https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar

**Comment by weixingyao** [comment] 2021-02-13 03:01
> @Austin-Lamb and @pratikone FYI. I think this is by design but others should correct me if I'm wrong, in UWP I think you have to use the ExtendViewIntoTitleBar property. here is some documentation: https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar

We can not load Windows.UI.Xaml.dll  and Microsoft.UI.Xaml.dll together.This might be a bug or design. In UWP,ExtendViewIntoTitleBar has effects,but Window.Current.SetTitleBar is not. If we load Microsoft.UI.Xaml.dll then we can`t use Windows.UI.Xaml.dll.

**Comment by weixingyao** [comment] 2021-02-13 03:06
> @Austin-Lamb and @pratikone FYI. I think this is by design but others should correct me if I'm wrong, in UWP I think you have to use the ExtendViewIntoTitleBar property. here is some documentation: https://docs.microsoft.com/en-us/windows/uwp/design/shell/title-bar

Windows.UI.Xaml.Window.Current.SetTitleBar is different with Microsoft.UI.Xaml.Window.Current.SetTitleBar. Could any one tell me how to use these  two dll in UWP？

**Comment by MikeHillberg** [comment] 2021-02-13 21:58
You're right that you don't want to load both Windows.UI.Xaml (in Windows) and Microsoft.UI.Xaml (in WinUI3).

[The plan](https://github.com/microsoft/microsoft-ui-xaml-specs/pull/71/files) is that Window will have an ExtendsContentIntoTitleBar property and SetTitleBar method. ExtendsContentIntoTitleBar collapses away the system title bar, and then SetTitleBar identifies the element that can be used for window dragging etc. That's implemented in Preview4 for Desktop, but not UWP yet.

**Comment by krschau** [comment] 2022-06-22 16:37
We're closing this item because the WindowsAppSDK does not support UWP apps, details about which can be found in [this discussion](https://github.com/microsoft/WindowsAppSDK/discussions/1615). If you are still having trouble with SetTitleBar() in the latest WindowsAppSDK version, please open a new issue.

**Closed by krschau** 2022-06-22 16:37 UTC
Labels: team-Reach, product-winui3, version-winui3preview4, area-TitleBar
