### ISSUE TITLE
The TextBox component renders abnormally

### ISSUE THREAD

**Issue by Ling0925** [microsoft/microsoft-ui-xaml#9518] opened 2024-04-08 14:50 UTC
### Describe the bug

When the TextBox component renders multiple lines of content, only the first 178277 characters are rendered, and the subsequent content is displayed as blank

### Steps to reproduce the bug

1. Create TextBox in xaml
```XAML
 <TextBox 
     x:Name="SkusTextBox"
     x:Uid="SkusTextBox"
     AcceptsReturn="True" 
     TextWrapping="WrapWholeWords"
     Header="SKU列表,每行一个"
     MaxHeight="500"
     MinHeight="200"
     Visibility="Visible"
     ScrollViewer.VerticalScrollBarVisibility="Visible"/>
```

2. Set Content to TextBox
```CSharp
var skus = new StringBuilder();
SKUs.Distinct().ToList().ForEach(item =>
{
    skus.Append(item);
    skus.Append("\n");
});

SkusTextBox.Text = skus.ToString();
```

### Expected behavior

It should show all the content

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/67010066/27113649-f323-4687-8438-cbfd89881e29)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.1: 1.5.240311000

### Windows version

Windows Insider Build (xxxxx)

### Additional context

Edition	Windows 11 Pro
Version	24H2
Installed on	‎4/‎4/‎2024
OS build	26100.1
Experience	Windows Feature Experience Pack 1000.26100.1.0

**Comment by kmahone** [comment] 2024-05-07 22:34
This is a duplicate of : #1842

**Closed by kmahone** 2024-05-07 22:34 UTC
Labels: bug, area-TextBox, team-Controls
