### ISSUE TITLE
Proposal: Foreground for ComboBox.PlaceholderText should be same as TextBox.PlaceholderText 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2774] opened 2020-06-29 03:00 UTC
# Proposal: Foreground for ComboBox.PlaceholderText should be same as TextBox.PlaceholderText  

## Summary

The foreground colour for ComboBox's PlaceholderText should be same as TextBox's PlaceholderText, as it would allow it to be differentiated from the selected value in the combobox.

## Rationale

* Help align PlaceholderText foreground between controls
* Help differentiate the PlaceholderText from the selected value 

## Scope

| Capability | Priority |
| :---------- | :------- |
| Match the foreground colour to TextBox's PlaceholderText foreground | Must |
| Allow lightweight style | Should |

**Comment by Felix-Dev** [comment] 2020-06-29 11:02
Makes sense to me. We should also update the placeholder foreground color then when the ComboBox is not editable and in focus. A possible solution would be to introduce a new `ComboBoxPlaceHolderForegroundFocused` alongside the existing ComboBoxPlaceHolderForeground* theme resources and match the placeholder foreground color with the placeholder foreground color when in rest state (in other words, keep the placeholder foreground color the same when focused or not focused when in uneditable mode).

(I made some GIFs showcasing this but apparently there are some issues with Github right now preventing me from uploading them. I will try again later.)

**Comment by StephenLPeters** [comment] 2020-06-29 23:23
Should be pretty simple given that we have lifted the combo box template to WinUI 2 already. I agree the placeholder text foreground color should match textbox's. FYI @chigy

**Comment by Felix-Dev** [comment] 2020-06-29 23:28
I will create a PR tomorrow for the placeholder foreground.

**Comment by Felix-Dev** [comment] 2020-06-30 14:57
About ligthweight styling the placeholder foreground: This doesn't appear to work as intended and expected for now. Observe for example the following XAML:
```xml
<ComboBox PlaceholderText="Some placeholder">
    <ComboBox.Resources>
        <SolidColorBrush x:Key="ComboBoxPlaceHolderForeground" Color="Green" />
        <SolidColorBrush x:Key="ComboBoxPlaceHolderForegroundFocused" Color="Orange" />
        <SolidColorBrush x:Key="ComboBoxPlaceHolderForegroundFocusedPressed" Color="Red" />
    </ComboBox.Resources>
</ComboBox>
```

The expected result would be this:
![combobox-placeholder-foreground-focused-themeresources-issue-expected](https://user-images.githubusercontent.com/1398851/86141712-aae1d400-baf2-11ea-9d13-95c533d76cb4.gif)

but the actual result is this:
![combobox-placeholder-foreground-focused-themeresources-issue](https://user-images.githubusercontent.com/1398851/86136390-53d90080-baec-11ea-849f-5dd640884e43.gif)

These issues are located here, for example: https://github.com/microsoft/microsoft-ui-xaml/blob/6994eb90c8c7656f694d01253cfa643f29a0df9f/dev/ComboBox/ComboBox_themeresources.xaml#L620

What we are saying here and in the other visual states of Focused and FocusedPressed [here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ComboBox/ComboBox_themeresources.xaml#L475) and [here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/ComboBox/ComboBox_themeresources.xaml#L493) is that if the `ComboBox.PlaceholderForeground` API is set, it will take precendence over the specified theme resources. However, if the PlaceholderForeground API is *not* set, as in my example XAML above, these theme resources should be used. And in fact they are (TargetNullValue works correctly). Unfortunately for us though, the theme resources values applied here are the values defined in the *ComboBox_themeresources.xml* resource dictionary! The overriden resource values in my example XAML above are being ignored (probably not seen by the theme resource lookup algorithm in use here). @StephenLPeters I'm not sure how related this XAML resource lookup issue is with the issue we were seeing in https://github.com/microsoft/microsoft-ui-xaml/pull/2674#issuecomment-646236865 but I'm still pinging you here as a FYI at least.

This issue also effects the TextBox and its placeholder theme resources like *TextControlPlaceholderForeground* and *TextControlPlaceholderForegroundFocused* and as such is also an issue for the ComboBox when it is in an editable state (ComboBox.IsEditable = true): https://github.com/microsoft/microsoft-ui-xaml/blob/6994eb90c8c7656f694d01253cfa643f29a0df9f/dev/CommonStyles/TextBox_themeresources.xaml#L231

These lightweight styling issues above should presumably be tracked in a separate issue about the XAML resource lookup algorithm. Your thoughts, @StephenLPeters?

**Comment by chigy** [comment] 2020-06-30 15:30
@kikisaints FYI

**Comment by StephenLPeters** [comment] 2020-06-30 20:49
@Felix-Dev making sure I understand, this issue is still present after your PR correct?  If you put the theme resource in a parent resource dictionary does it work? what about the app.xaml resources? I wonder if the lookup initiated by the binding functions differently than a normal resource lookup, similar to how resource lookups from code behind don't match xaml resource lookups..

@MikeHillberg or @jevansaks maybe you already know about any intricacies to lookups from binding?

**Comment by Felix-Dev** [comment] 2020-06-30 21:05
@StephenLPeters Yes, the issue would still be present even with my PR merged. In other words, using lightweight styling to set the **Placeholder** foreground for the TextBox/ComboBox/... would still not work (see my example XAML markup in the post above).

It also does not matter if I override these resources on the control level, the page level or the app level. Same effect - my overriden placeholder foreground theme resources will be ignored.

And yes, "the lookup initiated by the binding functions" seems like a good candidate for being the culprit here. Observe that this only happens for the Placeholder which is the only one using `Binding` in ComboBox visual states. If I change the following XAML code in the visual state from
```xml
    <DiscreteObjectKeyFrame KeyTime="0" Value="{Binding PlaceholderForeground, RelativeSource={RelativeSource TemplatedParent}, TargetNullValue={ThemeResource ComboBoxPlaceHolderForegroundFocused}}" />
</ObjectAnimationUsingKeyFrames>
```
to:
```xml
<ObjectAnimationUsingKeyFrames Storyboard.TargetName="PlaceholderTextBlock" Storyboard.TargetProperty="Foreground">
    <DiscreteObjectKeyFrame KeyTime="0" Value="{ThemeResource ComboBoxPlaceHolderForegroundFocused}" />
```

my theme resource overrides for `ComboBoxPlaceHolderForegroundFocused` will be applied just as expected.

**Closed** 2020-07-31 21:29 UTC
Labels: area-ComboBox, area-Styling, feature proposal, help wanted, team-Controls, working on it
