### ISSUE TITLE
Focused moved to first control contained inside scroll viewer when clicking on empty space in application

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4364] opened 2021-02-26 14:18 UTC
**Describe the bug**
Focused moved to first control contained inside scroll viewer when clicking on empty space in application.

**Steps to reproduce the bug**
1. Run the application.
2. Focus Second TextBox contained inside stackpanel.
3. Now, click on empty space in application.
4. Note, Focused moved to first TextBox control when clicking on empty space in an application.

**Expected behavior**
Focused should not moved to first TextBox control when clicking on empty space in an application. 

**Note:**
If StackPanel not placed inside scrollviewer, then it works fine.

**Version Info**
[Microsoft.WinUI 3.0.0-preview4.210210.4]

**Sample:**
[WinUITest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6050122/WinUITest.zip)

**Comment by StephenLPeters** [comment] 2021-03-03 01:18
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4380 except this is in Winui3preview.

**Comment by bpulliam** [comment] 2023-07-07 12:40
Closing as duplicate.  #597 has more traction.

**Closed by bpulliam** 2023-07-07 12:40 UTC
Labels: duplicate, area-Scrolling, team-Controls, product-winui3
