### ISSUE TITLE
The TextBlock text is not centered in Windows 11.

### ISSUE THREAD

**Issue by KarthikRajaKalaimani** [microsoft/microsoft-ui-xaml#10256] opened 2024-12-24 11:04 UTC
### Describe the bug

When adding a TextBlock with both HorizontalAlignment and VerticalAlignment set to "Center" within a Grid, the text appears correctly centered in Windows 10 but is misaligned in Windows 11. Please refer to the screenshot below for comparison.

Windows 11 : 
![Image](https://github.com/user-attachments/assets/7ddd6d7a-ffa1-41ba-99c0-c2e0a8a7aa74)

Windows 10: 
![Image](https://github.com/user-attachments/assets/9d1d5907-cd4d-4436-a503-02f17b8836a8)

### Steps to reproduce the bug

1. Run the below code in MainWindow.xaml

```
 <Grid Height="40" Width="164" Background="LightGray">
     <Grid Background="Orange" Height="20" HorizontalAlignment="Center" VerticalAlignment="Center">
     <TextBlock Text="Stop responding" x:Name="label" 
            Height="20"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
             />
     </Grid>
 </Grid> 
```

### Expected behavior

The text should be horizontally and vertically centered.

### NuGet package version

WinUI 3 - Windows App SDK 1.6.3: 1.6.241114003

### Windows version

Windows 11 (23H2): Build 22631

**Comment by karkarl** [comment] 2024-12-26 16:17
This is due to the Segoe UI fontset's layout. This is by design, so closing.

**Closed by karkarl** 2024-12-26 16:17 UTC
Labels: bug, needs-triage

**Comment by KarthikRajaKalaimani** [comment] 2024-12-27 04:57
is there any workaround to make it centre on windows 11 ?

**Comment by mqudsi** [comment] 2025-05-12 17:12
This is a huge regression that causes apps to require manual vertical alignment with padding/margin offsets (which then breaks how they appear on Windows 10). If Segoe UI is broken on Windows 11, then a different font should be used by WinUI or a patched version should be bundled with it.

I don't understand how this is closed as "by design" when you can no longer align text with an adjacent icon.

**Comment by mqudsi** [comment] 2025-05-22 15:35
This can be worked around by using the specific font family you need instead of relying on WinUI to pick the right variant. e.g. instead of the default font and `FontWeight = Medium`, remove `FontWeight` and add `FontFamily="Segoe UI Medium"`.

It seems only the default font is bugged and specific variants ttf/otf files are fine.
