### ISSUE TITLE
CalendarView: Bad rendering for first-day-of-month buttons

### ISSUE THREAD

**Issue by RBrid** [microsoft/microsoft-ui-xaml#1199] opened 2019-08-22 21:57 UTC
CalendarView shows first-day-of-month buttons with overlapping month and day captions.

1. Run the MUXControlsTestApp
2. Click its CalendarView button

Result:
![CalendarViewScreenshot](https://user-images.githubusercontent.com/36547063/63552561-c6507b80-c4ec-11e9-946e-954def9b1e59.png)

Expected:
Month and day captions should not overlap.

Seen on 19H1 Desktop.

The additional month captions come from the setting IsGroupLabelVisible="True" in the page's XAML markup.

**Comment by jevansaks** [comment] 2019-08-23 18:13
@kikisaints This has been the rendering for a while now, are there comps for how it should look where the text isn't overlapping?

**Comment by mdtauk** [comment] 2019-08-23 18:22
I agree it looks bad, but it seems to be by design...

@jevansaks @kikisaints 

![image](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls/images/calendarmonthelements.png)

**Comment by kikisaints** [comment] 2019-08-23 21:09
@mdtauk I think so some degree it is by design, but it should be addressed. Legibility is important and this definitely rides the line.

I spoke to our design team a while ago about this and we ran into... issues that prevented us from finalizing it at the time.

Here were some of the solutions we cam up with at the time:

## Label on the side
![image](https://user-images.githubusercontent.com/6964369/63623496-99649d00-c5ae-11e9-8491-9281298c60e7.png)

Pros:
- Clean
- Large text, so easier to read

Cons:
- Insets first item, but not the rest, could be difficult to do as a quick fix

## Label in corner
![image](https://user-images.githubusercontent.com/6964369/63623553-b7ca9880-c5ae-11e9-9df3-3f5191770143.png)

Pros:
- Clean
- All items are homogeneous, making it easier to quick fix

Cons:
- If the developer enabled this, all day items would go from center aligned to offset suddenly, could be an undesired effect in some situations

Thoughts?

**Comment by mdtauk** [comment] 2019-08-23 21:16
I am glad the team is willing to address this.  I think this other feature needs to be tested with these control changes.

![image](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls/images/calendarview_density_bars.png)

**Comment by kikisaints** [comment] 2019-08-23 21:29
Good point! They do need to work well with the density colors. I feel that kind of rules out the side label option.

**Comment by mdtauk** [comment] 2019-08-23 21:37
Personally I think the Item backgrounds do a good enough job highlighting the current Month scope, but the feature is there, and should be designed well.  On the plus side, only boxes with a Number 1 will display the date, so there is room to work with.  I wonder if smaller text in a lighter colour would look good?

![image](https://user-images.githubusercontent.com/7389110/63625110-84abf780-c5f6-11e9-9ef6-9e25a238be37.png)

**Comment by adrientetar** [comment] 2019-08-23 22:35
Why is the label even needed, since the month is displayed at the top?

**Comment by kikisaints** [comment] 2019-08-23 22:46
@adrientetar The month label at the top shows the current month, the labels in the days show which month is starting when a different month is in scope.

@mdtauk I like your designs, but a sticking point was offsetting the "1" on only one CalendarViewDayItem. All the items are created at once, homogeneously. So offsetting one would mean offsetting all the others.

I like the grayed out look, but it would need to meet the accessibility contrast ratio bar when over gray, which I don't think it would in the out of scope scenario you have above.

Sideways is interesting, but when we explored that a while ago we agreed it was a bit too difficult to read. Although cool looking.

**Comment by mdtauk** [comment] 2019-08-23 23:07
@kikisaints  Couldn't a Template Selector be employed to isolate the 1st day box?

There are resources for 20% Base colour, and 40% - the latter being a bit too strong, where 30% may work better.

![image](https://user-images.githubusercontent.com/7389110/63628211-19b4ed80-c603-11e9-97c7-eb50d59d691a.png)


I decided to try the text Sideways not to look cool, but solve the problem.  The Month text, in All Caps, is shorter than it is wide.  Having it to the side of the narrow number 1 digit, gives more space, so the box feels less cramped.

----

Offsetting was done before, on Windows Phone.
![image](https://user-images.githubusercontent.com/7389110/63628047-56341980-c602-11e9-8bef-191e19777858.png)

**Comment by shaheedmalik** [comment] 2019-08-24 07:16
> Personally I think the Item backgrounds do a good enough job highlighting the current Month scope, but the feature is there, and should be designed well. On the plus side, only boxes with a Number 1 will display the month, so there is room to work with. I wonder if smaller text in a lighter colour would look good?
>
> Or something like this:
> ![image](https://user-images.githubusercontent.com/7389110/63626705-4580a500-c5fc-11e9-8266-23611352b7df.png)

This one looks the best to me. It's very legible. I would just not make that single digit offset.

Like this:
![image](https://user-images.githubusercontent.com/51347950/63633895-8f2db780-c61d-11e9-9f45-2af2bd29d3c8.png)

**Comment by mdtauk** [comment] 2019-08-28 16:23
How often are these control designs audited and re-evaluate?  Also how would a control handle the deprecation of a property or feature, if it no longer feels appropriate.

I am not saying this "First Day of the Month" feature should go, as it can be made to work.  But if making that change needs a re-think in how the control works.  The whole thing about not being able to target the first day control separate from the others - that could be re-engineered with the right resources.

But if the Office Team needed new things from an existing control, to avoid them going their own way with a custom control, how would their needs be folded into existing controls?

**Comment by kikisaints** [comment] 2019-09-13 23:13
@mdtauk - designs are re-evaluated by PMs, but less often by the design team unless we find an error with the original design, or it becomes broken. Like this case.

As far as us ensuring we can fold in new  requests into controls (like the Office team example you've given) it actually had more to do with our turnaround time rather than our iteration on the feature/control itself. This is one of the many reasons we chose to go open source - easier and faster for internal and external partners to consume our changes.

**Comment by mdtauk** [comment] 2019-09-14 00:38
> @mdtauk - designs are re-evaluated by PMs, but less often by the design team unless we find an error with the original design, or it becomes broken. Like this case.
> 
> As far as us ensuring we can fold in new requests into controls (like the Office team example you've given) it actually had more to do with our turnaround time rather than our iteration on the feature/control itself. This is one of the many reasons we chose to go open source - easier and faster for internal and external partners to consume our changes.

Ok so making a change to the way the control's template works, to allow the changes you want to make, _can_ be done?

**Closed** 2023-08-04 11:59 UTC
Labels: bug, spec issue, area-DateTimePickers, team-Controls, no-issue-activity
