### ISSUE TITLE
Proposal: Click on cascading menu items to instantly open the cascading menu

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#939] opened 2019-06-25 11:05 UTC
# Proposal: We should be able to click on cascading menu items to instantly open the cascading menu

## Summary

We should be able to click on cascading menu items to instantly open the cascading menu.
## Rationale

* Consistency with win32 menus
* It makes things faster and feel faster

## Scope

| Capability | Priority |
| :---------- | :------- |
| Users can click on an item in a MenuFlyout that reveals another menu instantly| Must |

## Important Notes

The animation makes menus feel slow. This is something to consider but is worth its own issue.

**Comment by YuliKl** [comment] 2019-06-25 22:56
@Poopooracoocoo, I don't think I'm understanding the proposal. Can you point me to a specific example of an app whose experience will be improved by making this change?

**Comment by jevansaks** [comment] 2019-06-26 04:55
There's a small (but noticeable) delay between when you hover over a parent menu item. In Win32 menus if you click the menu would open immediately, in XAML it doesn't. 

I agree we should do this for consistency. Should be a pretty straightforward change once we're able to make changes in WinUI 3.0.

**Comment by Poopooracoocoo** [comment] 2019-06-26 10:16
@YuliKl Sorry again for submitting this as a bug. It's very hard to determine what is a bug and what is a proposal. I considered this to be a bug. It's something that was overlooked however.

**Comment by Poopooracoocoo** [comment] 2019-06-26 10:21
@YuliKl I remembered you telling me that something similar was more of a feature request so I filed this as a feature request instead of a bug even though I thought of it as something that was overlooked and therefore a bug.

**Comment by jevansaks** [comment] 2019-06-26 16:51
> I filed this as a feature request instead of a bug even though I thought of it as something that was overlooked and therefore a bug.

No worries! It's borderline for me too, but since there's very strong prior art in this area I think it's easy to follow suit.

**Comment by Poopooracoocoo** [comment] 2021-08-07 02:07
@karenbtlai any updates on this? been over two years.

**Comment by Poopooracoocoo** [comment] 2023-07-29 07:17
Don't close this

**Comment by fredemmott** [comment] 2023-12-01 22:11
This feels beyond 'slow' in Windows App SDK v1.4.2, including in the WinUI3 gallery; it is taking 2-3 *seconds* of hover to open with no visual feedback, so I thought cascading menus were completely broken.

Can be reproduced with the 'cascading menus' example on the menu flyouts page of WinUI3 gallery.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/360927/7383cac5-d04c-416f-a687-b61198a7dd40)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/360927/570ab804-ba6d-4eb5-9447-466916415a3d)

**Comment by kmgallahan** [comment] 2023-12-02 03:43
@fredemmott I see no 2-3 second delay. In fact, the menu opens so quickly on hover that I don't think I can even click before the animation has finished.

Do you have another machine to test on?

**Comment by fredemmott** [comment] 2023-12-02 11:39
> @fredemmott I see no 2-3 second delay. In fact, the menu opens so quickly on hover that I don't think I can even click before the animation has finished.
> 
> Do you have another machine to test on?

I'm seeing this on two machines with Windows 10, z790, 13900k, and RTX4090
I am not seeing it (the flyout opens quickly) on a machine with the same version of windows 10, z370, 8700k, and RTX4070

All 3 machines are running Win 10 22H2 1904.3693 with all windows updates, and the 546.17 nvidia driver

**Comment by kmgallahan** [comment] 2023-12-02 12:50
I think this might be related to:

https://github.com/microsoft/terminal/issues/14756

https://github.com/microsoft/terminal/issues/15545

@ranjeshj become I don't know who else to mention regarding how to further investigate this.

**Comment by fredemmott** [comment] 2023-12-02 12:56
From reading those comments, I tried turning "Show Animations in Windows" off in the windows control panel (screenshot) - interestingly, this reliably makes things *worse*: 5-6 seconds. Turning it back on gets me back to 2-3 seconds.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/360927/c50d8ae2-4077-41c2-8441-dcc5f841a2e6)

**Comment by kmgallahan** [comment] 2023-12-02 13:21
Unless/until someone from Microsoft recommends a better way, my typical approach to diagnosing different behaviors on different machines is to try to find differences and eliminate them one at a time. Painful, but sometimes gets it done.

Maybe check monitor setup including resolution, display scaling, text scaling. Kill all 3rd party programs, in particular anything that uses drivers or monitors other running software (antivirus, work activity monitoring, Grammarly, etc.).

**Comment by fredemmott** [comment] 2023-12-02 13:31
This appears to be a problem with high refresh rates:

slow machines:
- 100% scaling, 1080p 240hz gsync on, windows Variable Refresh Rate off
  - disabling g-sync: no change
  - enabling windows VRR: no change
  - reducing from 240hz to 60hz: **FIXED**, regardless of if gsync is on or off
- 150% scaling, 5120x1440 240hz gsync on, windows VRR off
  - disabling g-sync: no change
  - enabling windows VRR: no change
  - reducing from 240hz to 60hz: **FIXED**, regardless of if gsync is on or off

Fast machine:
- 150% scaling, 3x 4K 60hz fixed

All:
- Hardware assisted GPU scheduling off
- No third-party software or AV, no monitoring, no third-party background services other than essential drivers and 1password

**Comment by jeremy-visionaid** [comment] 2024-02-29 09:11
@fredemmott Nice catch with the refresh rate. I agree with the other comments here - it's so laggy at 2-3 seconds that you think it's broken. Setting my screen refresh rate to 60 Hz makes the pop up much faster.

**Comment by gegao18** [comment] 2024-03-22 22:32
@fredemmott Nice find! Yes, there is an issue with variable refresh rate displays and how WinUI 3 keeps track of time that causes multi-second delays in DispatcherTimers firing. This is tracked by #9371, and we have a fix coming in 1.5.2. This issue (and #8921) tracks the slight delay in opening nested menus with a mouse click, and this delay exists regardless of the type of device running the app.

**Comment by fredemmott** [comment] 2024-03-22 22:39
@gegao18 to be clear, this is at *high* refresh rates - enabling/disabling variable refresh rate does no difference

**Comment by bkudiess** [comment] 2024-08-20 18:49
This was fixed internally and will be available in WASDK 1.7

**Closed by bkudiess** 2024-08-20 18:49 UTC
Labels: bug, area-Menus, needs-winui-3, team-Controls
