### ISSUE TITLE
Question: System.ArgumentException: 'Value does not fall within the expected range.' on Content Dialog

### ISSUE THREAD

**Issue by ServidorInformatica** [microsoft/microsoft-ui-xaml#5227] opened 2021-06-21 10:31 UTC
I'm triyng to make a login system in my UWP (WinUI3) app and when I try to lauch de Login Content Dialog it crashes throwing this error:

> System.ArgumentException: 'Value does not fall within the expected range.'

on `await messageDialog.ShowAsync();`

Code on app.xaml.cs:

```
protected override async void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
        {  

            m_window = new MainWindow();
            m_window.Activate();

            Login();
             
        }

        protected async void Login()
        {
            var messageDialog = new ContentDialogs.LoginDialog();
            await messageDialog.ShowAsync();

            if (App.Aplicacao.Utilizador == null)
            {
                m_window.Close();
                return;
            }
        }
```
Content Dialog XAML:

```
<ContentDialog
    x:Class="xizSoft.ContentDialogs.LoginDialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:xizSoft.ContentDialogs"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource SystemControlAcrylicWindowBrush}">

    <Grid>
    </Grid>
</ContentDialog>
```
Code-behind:

```
 public LoginDialog()
        {
            this.InitializeComponent();
        }
```

**Comment by StephenLPeters** [comment] 2021-06-21 23:32
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4251

ContentDialogs need to have a XamlRoot specified on them. This happens automatically if you define your content dialog in markup, but when you do it from code behind you need to specify which XamlRoot the Dialog is assigned to.

**Closed** 2021-06-21 23:32 UTC
Labels: area-Dialogs, question, team-Controls, winui3preview
