### ISSUE TITLE
Content Resize Slower Than Window Resize

### ISSUE THREAD

**Issue by krixano** [microsoft/microsoft-ui-xaml#5446] opened 2021-07-12 16:49 UTC
**Describe the bug**
Resizing the window - the content lags enough so that there's a visual "artifact" of a gray border on the right or bottom where the content hasn't been filled into yet.

I am aware that lots of programs have this problem, even Firefox, Discord, and even programs on other Operating Systems, so it's a common problem with GUI frameworks in general.  I don't know if it's like Windows, the GUI frameworks being used, the resize events being too slow, etc. But it's a pretty common problem, even on other platforms like Linux.

In regards to Windows, it seems like the old Windows 10 (and prior) apps, like Windows Calculator, File explorer, Feedback Hub, etc., don't have this problem, while the new Windows 11 apps *do* have this problem, including the new Microsoft Store for Windows 11, the Windows 11 Settings App, etc. Windows Terminal (version 1.8.1521.0) also has this problem.

Fixing this would polish up people's systems in general, and make things more enjoyable to use, so I definitely think it's something all programs should work towards fixing.

**Steps to reproduce the bug**

1.) Resize Window

**Expected behavior**
The content resizing smoothly along with the window resize.

**Screenshots**

https://user-images.githubusercontent.com/4098042/125325803-fa163380-e306-11eb-9406-136b47c7b4bb.mp4

**Version Info**
I'm on latest Windows 11 Insider build (22000.65).

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.65)              | yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I had made an issue on the Windows Terminal repo also, here: https://github.com/microsoft/terminal/issues/10635

**Comment by krixano** [comment] 2023-08-02 18:24
It's still an issue.

**Comment by castorix** [comment] 2023-08-03 08:35
It is the same issue as https://github.com/microsoft/microsoft-ui-xaml/issues/5148

**Comment by JJBrychell** [comment] 2023-08-30 03:30
We are closing this issue as a duplicate of [(#5148) ](https://github.com/microsoft/microsoft-ui-xaml/issues/5148). There you will find an extremely extensive discussion about the challenges, possible workaround and potential fixes on this issue.

**Closed by JJBrychell** 2023-08-30 03:30 UTC
Labels: team-Rendering, area-Performance

**Comment by krixano** [comment] 2023-09-08 07:37
Good. As long as it gets fixed sometime in this lifetime, lmao. Y'all are too slow on this crap, seriously.
