### ISSUE TITLE
Can't bind array to ItemsSource when using C++/WinRT

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#4119] opened 2021-02-06 09:19 UTC
**Describe the bug**

When using C++/WinRT, binding to ItemSource using x:Bind doesn't work as it generates a C# style array which won't work in C++, instead use winrt::array_view<T>.

**Steps to reproduce the bug**

1. Define an array in IDL
2. Bind it to a XAML control 
3. See error

**Expected behavior**
x:Bind should work with an array

**Screenshots**

![திரைப்பிடிப்பு (247)](https://user-images.githubusercontent.com/45227503/107114241-5b366880-688a-11eb-9110-de321925194a.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment] 2021-02-09 00:24
@kennykerr FYI, Is this a cppwinrt issue or a xaml compiler issue?

**Comment by StephenLPeters** [comment] 2021-02-09 00:25
@RealTommyKlein and @fabiant3 FYI

**Comment by kennykerr** [comment] 2021-02-09 01:15
That code is not generated by cppwinrt.

**Comment by RealTommyKlein** [comment] 2021-02-09 01:16
@StephenLPeters it's an issue in the Xaml compiler's generated code

**Comment by JeanRoca** [comment] 2021-04-14 22:12
No further information provided, closing for now. Feel free to reopen if there is more info.

**Comment by Jaiganeshkumaran** [comment] 2021-05-22 02:59
> No further information provided, closing for now. Feel free to reopen if there is more info.

Yes this seems to happen in a desktop project as well however only when you use C++. Works fine with C#.

**Comment by Jaiganeshkumaran** [comment] 2021-11-24 14:47
Can this issue be reopened? The issue still exists.

**Closed** 2023-08-04 12:02 UTC
Labels: bug, area-Binding, team-Markup, area-C++/WinRT, no-issue-activity

**Comment by JaiganeshKumaran** [comment] 2024-02-07 15:23
> @JaiganeshKumaran does this issue occur in a Desktop project as well?

Yes, it very much does; please fix it soon.

**Comment by bpulliam** [comment] 2024-02-29 17:07
You mentioned that you would like this reopened, so I'm just getting some background. You also mentioned this is a duplicate of #7929, but that issue is closed. Is this not a duplicate, or is that issue closed incorrectly?

**Comment by JaiganeshKumaran** [comment] 2024-02-29 17:25
@bpulliam That issue is in fact a duplicate, but the author closed it because this issue was open at that time.
