### ISSUE TITLE
Cannot locate xaml Resource file

### ISSUE THREAD

**Issue by GMudide** [microsoft/microsoft-ui-xaml#8691] opened 2023-07-28 17:36 UTC
### Describe the bug

I'm working on c++ WinUI3  application

'Cannot locate resource from 'ms-appx:///Sample.xaml'.'. 
Actually, by default xaml files are placed under TestWRC folder during build process under CoreApp x64 directory but when xaml cpp code is generated, file is referring root location ('ms-appx:///Sample.xaml'.') instead of  ('ms-appx:///SampleWRC/Sample.xaml'.').

I felt it has to do with configuration/property settings of xaml file but nothing found on project settings. Am I missing anything small here?

### Steps to reproduce the bug

1. create Balnk App, Packaged (WinUI 3 in Desktop)  C++ with same name (CoreApp) for solution and project name. Uncheck the option to put the Project in the Solution folder.
2. create Windows Runtime component (WinUI 3) C++ project with TestWRC as name, then add Sample.xaml file.
3. make navigation from CoreApp to WRC project.
4. Build application and Run
5. click Button which throws 'Cannot locate resource from 'ms-appx:///Sample.xaml'. ERROR

==========NUGET Packages=======
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.Windows.CppWinRT" version="2.0.220929.3" targetFramework="native" />
  <package id="Microsoft.Windows.ImplementationLibrary" version="1.0.220914.1" targetFramework="native" />
  <package id="Microsoft.Windows.SDK.BuildTools" version="10.0.22621.755" targetFramework="native" />
  <package id="Microsoft.WindowsAppSDK" version="1.3.230502000" targetFramework="native" />
</packages>
```

======================

==============System configuration=================
Windows version: Windows 10 Enterprise 22H2 version
Visual Studio: Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Microsoft Visual Studio Enterprise 2022
Version 17.6.4
VisualStudio.17.Release/17.6.4+33815.320
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA457
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.6.326.62524
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.6.326.62524
Azure App Service Tools v3.0.0

C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23087.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.23087.1
Profiling support for Python projects.

Python - VC Project Support   17.0.23055.1
Provides support for launching C++ projects with Python debugging enabled.

Python with Pylance   17.0.23087.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.6.0.2327201+a6a61fdfa748eaa65aab53dab583276e26af4a3e
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.6.13.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.20329.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Microsoft Visual F# Tools

Microsoft Visual Studio Enterprise 2022
Version 17.6.4
VisualStudio.17.Release/17.6.4+33815.320
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Enterprise

Visual C++ 2022   00476-80000-00000-AA457
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.6.326.62524
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.6.326.62524
Azure App Service Tools v3.0.0

C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.23087.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Python - Profiling support   17.0.23087.1
Profiling support for Python projects.

Python - VC Project Support   17.0.23055.1
Provides support for launching C++ projects with Python debugging enabled.

Python with Pylance   17.0.23087.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.6.0.2327201+a6a61fdfa748eaa65aab53dab583276e26af4a3e
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.6.13.0
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.20329.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.
========================

### Expected behavior

App should Navigate to Sample.xaml UI

### NuGet package version

None

**Comment by DarranRowe** [comment] 2023-07-29 01:38
What version of the Windows App SDK are you working with?
I do remember seeing things like this happening with older versions, such as 1.1 and I think 1.2. But I don't remember seeing this happen with 1.3.
One thing to try, which did fix things in the past, is modify the component's project file. The following is an extract from a Windows Runtime Component .vcxproj file.
```
  <PropertyGroup Label="Globals">
    <CppWinRTOptimized>true</CppWinRTOptimized>
    <CppWinRTRootNamespaceAutoMerge>true</CppWinRTRootNamespaceAutoMerge>
    <MinimalCoreWin>true</MinimalCoreWin>
    <ProjectGuid>{56227b93-b492-435e-b8fe-302e11381664}</ProjectGuid>
    <ProjectName>TestComponent</ProjectName>
    <RootNamespace>TestComponent</RootNamespace>
    <DefaultLanguage>en-GB</DefaultLanguage>
    <MinimumVisualStudioVersion>16.0</MinimumVisualStudioVersion>
    <!--The following property, AppContainerApplication, should be set to false-->
    <AppContainerApplication>true</AppContainerApplication>
    <ApplicationType>Windows Store</ApplicationType>
    <ApplicationTypeRevision>10.0</ApplicationTypeRevision>
    <WindowsTargetPlatformVersion Condition=" '$(WindowsTargetPlatformVersion)' == '' ">10.0.22621.0</WindowsTargetPlatformVersion>
    <WindowsTargetPlatformMinVersion>10.0.17763.0</WindowsTargetPlatformMinVersion>
    <DesktopCompatible>true</DesktopCompatible>
    <UseWinUI>true</UseWinUI>
  </PropertyGroup>
```
Try setting the AppContainerApplication property to false. You should know if this has been set properly since the component should have (Desktop) after the project name instead of (Universal Windows).

**Comment by GMudide** [comment] 2023-07-30 15:56
Worked! Thank You!

Windows SDK version 1.3.230502000
<package id="Microsoft.WindowsAppSDK" version="1.3.230502000" targetFramework="native" />

I believe the suggestion is a workaround but not a solution because 
- the component name changes from (Universal Windows) to (Desktop) and 
- Already In the current VS solution there are existing projects as (Universal Windows) which had no issues. for the newly added projects, I see this issue.

**Comment by DarranRowe** [comment] 2023-07-30 23:21
The issue depends totally on what the component is doing.
The problem is in the code that comes from the Xaml compiler. In your project's case, it is in GuidePage.xaml.g.hpp.
```
    template <typename D, typename ... I>
    void GuidePageT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///GuidePage.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Nested);
        }
    }
```
This is looking for the page in the application's directory, however the project system places GuidePage.xaml/GuidePage.xbf in the CoreWRC subdirectory. If you set AppContainerApplication to false, then the Xaml compiler will then add the subdirectory to the path that it looks for the .xaml/.xbf file.
```
    template <typename D, typename ... I>
    void TestPageT<D, I...>::InitializeComponent()
    {
        if (!_contentLoaded)
        {
            _contentLoaded = true;
            ::winrt::Windows::Foundation::Uri resourceLocator{ L"ms-appx:///TestComponent/TestPage.xaml" };
            ::winrt::Microsoft::UI::Xaml::Application::LoadComponent(*this, resourceLocator, ComponentResourceLocation::Nested);
        }
    }
```
If the component is only providing a runtime class then it will not try to load a .xaml file in this way.
I honestly haven't dug into the diagnostic project output to see if there are any differences between the Xaml compiler input, or even tried to figure out if this difference seems to be deliberate. All I know is that AppContainerApplication is what causes the difference.

**Comment by GMudide** [comment] 2023-08-01 06:15
Thanks for your comments! 

can anyone from **microsoft-ui-xaml** team confirm on the behavior?

**Comment by DarranRowe** [comment] 2023-08-01 20:18
Unfortunately, in this case you would be in the better position to investigate this.
I would have to have access to a project which places the .xaml/.xbf files in the subdirectory while still having AppContainerApplication set to true to be able to investigate, and I don't.

**Comment by sotanakamura** [comment] 2023-08-05 23:41
Did you solve this issue? If so, please close this issue.

**Comment by GMudide** [comment] 2023-08-06 09:04
Not yet

**Comment by GMudide** [comment] 2023-08-08 10:37
finally got the answer. It's a known issue.

https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#:~:text=Known%20issues%20for%20both%20packaged%20and%20unpackaged%20WinUI%20applications%3A


`<Target Name="GetPriIndexName">
<PropertyGroup>
    
    <PriIndexName Condition="'$(RootNamespace)' != ''">$(RootNamespace)</PriIndexName>
    
    <PriIndexName Condition="$(PriIndexName) == ''">$(TargetName)</PriIndexName>
</PropertyGroup>
</Target>`

**Comment by evelynwu-msft** [comment] 2024-01-27 08:12
Duplicate of https://github.com/microsoft/WindowsAppSDK/issues/1769

**Closed by evelynwu-msft** 2024-01-27 08:12 UTC
Labels: bug, area-Resources, team-Markup
