### ISSUE TITLE
Cleared UIElement child objects, but still its holding in performance profiler memory 

### ISSUE THREAD

**Issue by Ganeshamoorthy10** [microsoft/microsoft-ui-xaml#4580] opened 2021-03-19 13:50 UTC
**Describe the bug**

Cleared UIElement child objects while closing the window but still it holds in performance profiler memory. 

In my sample i added 42 CustomCell in row and column manner, when the window is closed i cleared all the child CustomCell from the stack panel, but when i check in performance profiler, CustomCell objects still holds in memory.

**Steps to reproduce the bug**

- Run the sample and click "cells page".
- Close the window by clicking "Go to home page" button.
- Open performance profiler, follow step 1 and step 2.
- Check the memory, it holds CustomCell 42 objetcs.

**Expected behavior**

All the objects should be cleared.

**Screenshots**

![Screenshot (27)](https://user-images.githubusercontent.com/39787321/111789921-ac089a80-88e7-11eb-87f9-012f643658cc.png)

**Sample:** 
[WinUIDesktopCellsDemo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6171507/WinUIDesktopCellsDemo.zip)

**Version Info**

WinUI NuGet package version = 3.0.0-preview4.210210.4

OS version = Windows 10 Pro

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-03-19 22:55
Is it just the case that garbage collection hasn't run yet? You can force garbage collection to happen by calling GC.Collect. https://docs.microsoft.com/en-us/dotnet/api/system.gc.collect?view=net-5.0  If you do that do you still see your objects being kept alive?

**Comment by Ganeshamoorthy10** [comment] 2021-03-22 04:41
Hi @StephenLPeters, i have checked by calling GC.Collect, still objects are not cleared.

**Comment by StephenLPeters** [comment] 2021-03-23 00:47
@Ganeshamoorthy10 probably the same root cause as https://github.com/microsoft/microsoft-ui-xaml/issues/4610?

@Scottj1s FYI

**Comment by StephenLPeters** [comment] 2021-03-23 00:48
Closing as dupe, if you think its not, let me know :)

**Closed by StephenLPeters** 2021-03-23 00:48 UTC
Labels: duplicate
