### ISSUE TITLE
TextBlock text in AppBarButton.Flyout cannot be selected

### ISSUE THREAD

**Issue by hez2010** [microsoft/microsoft-ui-xaml#3189] opened 2020-08-24 09:16 UTC
**Describe the bug**
TextBlock text in AppBarButton.Flyout cannot be selected

**Steps to reproduce the bug**
```xaml
<AppBarButton Content="Click me">
    <AppBarButton.Flyout>
        <Flyout>
            <TextBlock Text="The text cannot be selected" IsTextSelectionEnabled="True" />
        </Flyout>
    </AppBarButton.Flyout>
</AppBarButton>
```

**Expected behavior**
With IsTextSelectionEnabled="True", the text in textblock should be able to be selected.

**Version Info**
WinUI: 2.4

NuGet package version: Microsoft.UI.Xaml 2.4.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Not tested |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20197)              | Yes   |
| May 2020 Update (19041)            | Not tested  |
| November 2019 Update (18363)       |  Not tested   |
| May 2019 Update (18362)            |  Not tested   |
| October 2018 Update (17763)        |  Not tested   |
| April 2018 Update (17134)          |  Not tested   |
| Fall Creators Update (16299)       |  Not tested   |
| Creators Update (15063)            |  Not tested   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  Not tested |
| Surface Hub        |  Not tested |
| IoT                |  Not tested |

**Additional context**

**Comment by YuliKl** [comment] 2020-08-25 17:46
@hez2010 can you try setting the AppBarButton's [AllowFocusOnInteraction](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.frameworkelement.allowfocusoninteraction?view=winrt-19041#Windows_UI_Xaml_FrameworkElement_AllowFocusOnInteraction) property to True?

**Comment by hez2010** [comment] 2020-08-26 11:59
@YuliKl I've verified and it works. Thanks!

**Comment by YuliKl** [comment] 2020-08-26 17:08
Sounds like the issue is resolved. Closing.

**Closed by YuliKl** 2020-08-26 17:08 UTC
Labels: area-Commanding, needs-triage, team-Controls
