### ISSUE TITLE
TabView: "Element is already the child of another element" thrown when a TabViewItem is switched to

### ISSUE THREAD

**Issue by duke7553** [microsoft/microsoft-ui-xaml#1262] opened 2019-09-02 18:04 UTC
**Describe the bug**
I migrated my project over to the WinUI version of TabView, but noticed that clicking a different TabViewItem will crash the app with the error: Element is already the child of another element. This bug occurs only when running with a debugger in Visual Studio.

**Steps to reproduce the bug**

1. Create a project with a WinUI TabView
2. Run Project with debugger
3. Add Multiple TabViewItems to the control
4. Click one of the unselected items

**Expected behavior**
Clicking an item should simply display its content. The crash and error is unexpected because it only occurs when running the app with a debugger.

**Screenshots**

![image](https://user-images.githubusercontent.com/20365014/64129235-09caa580-cd89-11e9-9c81-f8a6baf1864c.png)
![image](https://user-images.githubusercontent.com/20365014/64129250-1d760c00-cd89-11e9-9046-88a6a7c996dd.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362.10015)              | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
The problematic lines of code may be related to **line 222 of TabView.cpp**

**Comment by jevansaks** [comment] 2019-09-02 20:12
Thanks for reporting! Do you have a repro app you can share?

**Comment by duke7553** [comment] 2019-09-02 23:13
@jevansaks Unfortunately, I can't reproduce this weird bug in another project. Confusing!

**Comment by eugenegff** [comment] 2019-09-03 09:23
Seems that it is duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/1245

**Comment by duke7553** [comment] 2019-09-03 10:51
@eugenegff Agreed.

**Comment by jevansaks** [comment] 2019-09-03 18:22
Thanks! I'll close it and we can use #1245 to track.

**Closed by jevansaks** 2019-09-03 18:22 UTC
Labels: area-TreeView, bug, duplicate, needs: follow-up
