### ISSUE TITLE
ListViewItem selected state looks broken

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#5304] opened 2021-06-28 18:29 UTC
**Describe the bug**

ListViewItem selected pointer over state looks quite broken on WinUI 2.6, on 21H1.

**Steps to reproduce the bug**

1. Select a ListViewItem.
2. Move the mouse in and out of it.

**Screenshots**

https://user-images.githubusercontent.com/8152849/123685729-49605c80-d84f-11eb-9ff5-a3c6f5bad04b.mp4

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.6.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment] 2021-06-28 23:11
@ranjeshj this is close to maybe wanting to cherry pick into 2.6 thoughts?

@marksfoster do you know the intended behavior? is the selected rest state supposed to be accent color or the selected pointer over state supposed to be a grey?

**Comment by lhak** [comment] 2021-07-01 07:23
Please also change the way selected items (without pointer over) are presented. The selected state is barely visible (low contrast).

**Comment by ranjeshj** [comment] 2021-07-16 22:17
@beervoley closing this since the change is merged.

**Closed by ranjeshj** 2021-07-16 22:17 UTC
Labels: area-Lists, needs-cherrypicktorelease, team-Controls

**Comment by lmadhavan** [comment] 2021-07-19 04:24
Will this be hotfixed to 2.6?

**Comment by StephenLPeters** [comment] 2021-07-28 23:59
Yes.
