### ISSUE TITLE
Bug Report for 'NavigationView'(Top PaneDisplayMode) in 'Microsoft.UI.Xaml.Controls' from UWP

### ISSUE THREAD

**Issue by plane5** [microsoft/microsoft-ui-xaml#4934] opened 2021-04-30 03:35 UTC
Summary : 
application freezes 
when NavigationView's 'More button'(kebab button, button with three dots icon) is clicked
and no exceptions occurred.

Conditions
- UWP application
- PaneDisplayMode = "Top"
- MenuItemSources = List that contains its Type of Lists(tree-like structure)
- Shrunk window(it creates 'More button' as there is not enough space for MenuItem's content)

Version
- Microsoft.Toolkit.Uwp.UI.Controls v7.0.1 (NuGet)
- Microsoft.NETCore.UniversalWindowsPlatform v6.2.11

ETC
- I'm not sure If My test code is the problem but I assume not as I referred to MS Docs and only modified 'PaneDisplayMode' Property.
- reffered page : (https://docs.microsoft.com/ko-kr/windows/uwp/design/controls-and-patterns/navigationview)
- If you think there is another problem, please tell me so that I can apply it to my test code.

**Comment by chingucoding** [comment] 2021-04-30 07:05
Could this be a possible duplicate of #138? Both cases, opening the More dropdown breaks NavigationView and app get's unresponsive.

**Comment by StephenLPeters** [comment] 2021-04-30 23:22
Definitely possible. @ranjeshj fyi

**Comment by ranjeshj** [comment] 2021-05-21 14:52
If this crash is a layout cycle, [this fix](https://github.com/microsoft/microsoft-ui-xaml/commit/1cf9f1cc7ff56e701c91d1d3767d8ba551ff7896) would likely address it.

**Closed** 2023-08-03 22:43 UTC
Labels: area-NavigationView, team-Controls, product-winui2, no-issue-activity
