### ISSUE TITLE
SVG not longer rendering

### ISSUE THREAD

**Issue by galois77** [microsoft/microsoft-ui-xaml#9415] opened 2024-03-08 13:25 UTC
### Describe the bug

Since the last update, the google font icons are not rendered in our WinUI 3 app
![accueil](https://github.com/microsoft/microsoft-ui-xaml/assets/162712663/1e9711d5-a8f7-4bd2-8e0c-171b2cd333f1)

### Steps to reproduce the bug

                            <ImageIcon Source="/Resources/Icones/accueil.svg" Width="Auto" Height="Auto"/>

### NuGet package version

WinUI 3 - Windows App SDK 1.5.0: 1.5.240227000

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ranjeshj** [comment] 2024-04-09 22:47
SVG needs to have a native size. Does the svg file have the size in it?

**Comment by gegao18** [comment] 2024-04-11 22:07
Thanks for reporting this. I repro this regression, and it's caused by SVG scaling changes in WinUI 3 in 1.5.

The SVG file itself defines a negative viewbox (viewBox="0 -960 960 960") that's messing up scaling. One workaround is to change this to a positive viewBox (viewBox="0 0 960 960") and update the path to compensate.

I'll work on a fix for the 1.6 timeframe.

**Comment by gegao18** [comment] 2024-04-24 02:11
Fix checked in for WASDK 1.6.

**Closed by gegao18** 2024-04-24 02:11 UTC
Labels: bug, area-Images, team-Rendering

**Comment by codendone** [comment] 2024-06-12 00:24
The fix is now also in [Version 1.5.4 (1.5.240607001)](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-154-15240607001).
