### ISSUE TITLE
Proposal: Ability to control visibility of NavigationView Header

### ISSUE THREAD

**Issue by hez2010** [microsoft/microsoft-ui-xaml#834] opened 2019-06-10 16:00 UTC
# Proposal: Ability to control visibility of NavigationView Header

## Summary
Add a 'HeaderVisibility' property to make user able to control the visibility of NavigationView Header.

## Rationale
NavigationView currently has 'AlwaysShowHeader', but what we need more is to totally control the behavior of its Header. 

## Implementation
```xaml
<ContentControl x:Name="HeaderContent" ContentTemplate="{TemplateBinding HeaderTemplate}" Content="{TemplateBinding Header}" HorizontalContentAlignment="Stretch" IsTabStop="False" MinHeight="{StaticResource PaneToggleButtonHeight}" Grid.Row="1" Style="{StaticResource NavigationViewTitleHeaderContentControlTextStyle}" VerticalContentAlignment="Stretch" Visibility="{TemplateBinding HeaderVisibility}"/>
```
```csharp
public Visibility HeaderVisibility { get; set; }
public static readonly DependencyProperty HeaderVisibilityProperty = DependencyProperty.Register(nameof(HeaderVisibility), typeof(Visibility), typeof(NavigationView), new PropertyMetadata(Visibility.Visible));

```

**Comment by jevansaks** [comment] 2019-06-10 17:14
@hez2010 when are you seeing that AlwaysShowHeader isn't working? We have another issue #757 relating to AlwaysShowHeader not controlling the header in "Top" mode, but in left it should essentially work like IsVisible.

**Comment by hez2010** [comment] 2019-06-11 14:06
`AlwaysShowHeader` only makes decision for us about when to hide Header, however, with `HeaderVisibility` we can do what `AlwaysShowHeader` can do as well as making it more customizable.

**Comment by YuliKl** [comment] 2019-06-11 14:39
@hez2010, I'm sorry, I still don't understand. Maybe you can explain your scenario of what you're trying to achieve and how `AlwaysShowHeader` isn't letting you accomplish this?

**Comment by hez2010** [comment] 2019-06-11 14:44
For example, in the below scenario the header will show in the red rectangle, however, the blue rectangle I marked up has already shown the header, which will lead to duplicated headers and make the whole page ugly.
![home](https://user-images.githubusercontent.com/14960345/59281771-69d61200-8c9a-11e9-85d8-b64369a067db.png)

**Comment by YuliKl** [comment] 2019-06-11 16:51
I *think* what you're reporting is a duplicate of #757

**Closed** 2019-06-11 16:52 UTC
Labels: area-NavigationView, duplicate, feature request
