### ISSUE TITLE
Programmatically setting AutomationId on WebView2 is not preserved

### ISSUE THREAD

**Issue by jfkm69** [microsoft/microsoft-ui-xaml#8278] opened 2023-03-14 01:03 UTC
### Describe the bug

When carrying out testing for a WinRT application hosting the XAML WebView2 component I realized that setting the AutomationID programmatically does not result in the property being propagated to the rendered component and it is therefore not visible to automation testing tools such as Appium. 

```
auto testID = propertyValue.AsString();
// Attempt 1(https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.dependencyobject.setvalue?view=winrt-22621)
view.SetValue(AutomationProperties::AutomationIdProperty(), box_value(winrt::to_hstring(testID)));
// Attempt 2 (https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.automation.automationproperties.automationid?view=winrt-22621)
AutomationProperties::SetAutomationId(view, to_hstring(testID));
```

### Steps to reproduce the bug

1. Load the application hosting the WebView 2 application
2. Launch [Appium Server GUI](https://github.com/appium/appium-desktop/releases)
3. Start the Appium server
4. Launch the [Appium Desktop Inspector](https://github.com/appium/appium-inspector/releases/tag/v2023.2.1)
5. Observe XAML components like Button and View have their automationId set but the WebView2 component remains blank

### Expected behavior

Setting the AutomationID programatically should allow it to propagate to the rendered component in the application and those properties should be available for inspection by automation testing tools.

### Screenshots

![Screenshot 2023-03-13 180002](https://user-images.githubusercontent.com/17795430/224865478-8e7c8955-60a1-478e-9fbb-32907174bbc4.png)

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

### Windows version

Windows 10 (21H1): Build 19043

**Comment by DmitriyKomin** [comment] 2024-02-24 00:48
Hey @jfkm69, thank you for reporting this issue. I tried this out in a C# app (both WinUI2 and WinapSDK) and do not repro the problem - at least not with C# - AutomationID is correctly propagated for WebView2 with the code (verified in Inspect):
```
        private void SetAutomationIDButton_Click(object sender, RoutedEventArgs e)
        {
            myWV2.SetValue(AutomationProperties.AutomationIdProperty, "wv2_automation_id_set_from_code");
        }
```

In 2023, there was an Edge bug impacting WinAppSDK that caused _AutomationProperties.Name_ to disappear once the underlying CoreWebView2 got initialized - I wonder if this is the root cause of the behavior you were seeing? The bug got fixed in Edge ~119.0.2106.0 per notes [here](https://learn.microsoft.com/en-us/microsoft-edge/webview2/release-notes?tabs=dotnetcsharp#102106-prerelease).

Closing not repro on the assumption of fix in Edge. Please comment here and include repro app / video if you are still seeing the problem on latest WinAppSDK.

**Closed** 2024-02-24 00:49 UTC
Labels: bug, area-WebView, team-Rendering, product-winui2
