### ISSUE TITLE
Bug: TreeView - using IObservableVector.ReplaceAll to update ItemsSource does not work

### ISSUE THREAD

**Issue by the-om** [microsoft/microsoft-ui-xaml#1379] opened 2019-09-25 12:04 UTC
**Describe the bug**
When binding an IObservableVector (like winrt::single_threaded_observable_vector) to the ItemsSource property of a TreeView, updating the vector with ReplaceAll causes the corresponding tree node to drop all children instead of creating/updating its children according to the new items in the vector.

The change notification triggered by ReplaceAll ends up here:
https://github.com/microsoft/microsoft-ui-xaml/blob/803f4797a19ae03a428c8781bef85190e8855f1e/dev/TreeView/TreeViewNode.cpp#L195-L202
which just removes the nodes' children.

**Steps to reproduce the bug**
1. Bind an IObservableVector to the ItemsSource property of a TreeView
2. Update the vector using the ReplaceAll method

**Expected behavior**
The tree node should update its children according to the new contents of the vector.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment] 2019-09-25 15:57
@kaiguo sounds like a possible regression from the data source changes?

**Comment by kaiguo** [comment] 2019-09-26 18:58
@jevansaks I was able to repro this in CX app. ReplaceAll did end up in `Reset` as @the-om mentioned. Shouldn't it go to `Replace` instead? Is this a bug in IObservableVector?
https://github.com/microsoft/microsoft-ui-xaml/blob/803f4797a19ae03a428c8781bef85190e8855f1e/dev/TreeView/TreeViewNode.cpp#L195-L209

**Comment by jevansaks** [comment] 2019-09-26 19:05
Not necessarily. Reset means "lots of stuff changed". Sometimes it's convenient (or desired) to not have to notify specifically what changed. I see that the [.NET docs say that Reset means it was cleared](https://docs.microsoft.com/en-us/dotnet/api/system.collections.specialized.notifycollectionchangedaction?view=netframework-4.8#fields), but I think the docs are inaccurate.

The [UWP docs description](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.interop.notifycollectionchangedaction) is correct: "The content of the collection changed dramatically."

**Comment by chingucoding** [comment] 2019-09-26 22:30
What would be the best way to fix this? Are we accepting the fact that collections might still contain elements if they end up in `Reset`? If so, I think, we just need to add a check if there are any items in the collection and if so, re-add them.

**Comment by jevansaks** [comment] 2019-09-26 22:42
> What would be the best way to fix this? Are we accepting the fact that collections might still contain elements if they end up in `Reset`? If so, I think, we just need to add a check if there are any items in the collection and if so, re-add them.

Yup, I think that's the right fix. I think Kai was going to look into this but if you want to pick it up I imagine he wouldn't complain. :) Kai was observing that we have this problem in a bunch of controls so the fix might be broader than just TreeView.

**Comment by kaiguo** [comment] 2019-09-26 22:53
Yeah [NavigationView](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/TopNavigationViewDataProvider.cpp#L283-L287) and [Repeater](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/SelectionNode.cpp#L485-L490) both need to be fixed (and there's probably more). 

@chingucoding I haven't started yet so feel free to take it if you have time. Just let us know when you started so we don't step onto each other : )

**Comment by chingucoding** [comment] 2019-09-26 23:06
> Yeah [NavigationView](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/TopNavigationViewDataProvider.cpp#L283-L287) and [Repeater](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/SelectionNode.cpp#L485-L490) both need to be fixed (and there's probably more).
> 
> @chingucoding I haven't started yet so feel free to take it if you have time. Just let us know when you started so we don't step onto each other : )

Ah okay, yes I would look into this tomorrow if that is fine with everyone.

Should we rename the issue? Since TreeView is not the only control not dealing correctly with `Reset`.

Regarding all controls that need fixing, so far I have found:
* [NavigationView](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/NavigationView/TopNavigationViewDataProvider.cpp#L283-L287)
* [Repeater](https://github.com/microsoft/microsoft-ui-xaml/blob/master/dev/Repeater/SelectionNode.cpp#L485-L490)
* [TreeView](https://github.com/microsoft/microsoft-ui-xaml/blob/803f4797a19ae03a428c8781bef85190e8855f1e/dev/TreeView/TreeViewNode.cpp#L195-L209)
* [AnimationManager](https://github.com/chingucoding/microsoft-ui-xaml/blob/9b6490bdc3ac4ae602fcd234adeef2f74908b3cf/dev/Repeater/AnimationManager.cpp#L55)
* [SelectionNode](https://github.com/chingucoding/microsoft-ui-xaml/blob/9b6490bdc3ac4ae602fcd234adeef2f74908b3cf/dev/Repeater/SelectionNode.cpp#L485)
* [UniformGridLayout](https://github.com/chingucoding/microsoft-ui-xaml/blob/9b6490bdc3ac4ae602fcd234adeef2f74908b3cf/dev/Repeater/UniformGridLayoutState.cpp#L170)
* [ViewManager](https://github.com/chingucoding/microsoft-ui-xaml/blob/9b6490bdc3ac4ae602fcd234adeef2f74908b3cf/dev/Repeater/ViewManager.cpp#L434)
* [ElementManager](https://github.com/chingucoding/microsoft-ui-xaml/blob/9b6490bdc3ac4ae602fcd234adeef2f74908b3cf/dev/Repeater/ElementManager.cpp#L312)

Are there any missing? 😅 

Just to be sure, reset should clear all items and then add all items from the collection that raised the `Reset` state, right?

**Comment by jevansaks** [comment] 2019-09-26 23:07
> Just to be sure, reset should clear all items and then add all items from the collection that raised the `Reset` state, right?

That's my expectation. @ranjeshj any concerns?

**Comment by kaiguo** [comment] 2019-09-26 23:30
@chingucoding I didn't do any actual fix yet but I created a test page to repro the issue, it's in [user/kaiguo/treeview-fix](https://github.com/microsoft/microsoft-ui-xaml/commit/4c11b5d8e4203710d618899527ddf1fb8ecb068b), hopefully this can save you some time. I think this is a CX only problem since ReplaceAll only exists on CX side.

**Comment by chingucoding** [comment] 2019-09-26 23:41
> @chingucoding I didn't do any actual fix yet but I created a test page to repro the issue, it's in [user/kaiguo/treeview-fix](https://github.com/microsoft/microsoft-ui-xaml/commit/4c11b5d8e4203710d618899527ddf1fb8ecb068b), hopefully this can save you some time. I think this is a CX only problem since ReplaceAll only exists on CX side.

Yes that will definitely save me some time, thanks for pointing that out! 

If this is a CX problem only, I think we should create a testpage for every control that is affected by that. What do you think @jevansaks , @kaiguo ?

**Comment by kaiguo** [comment] 2019-09-27 00:23
Yeah I think we should add tests for the affected controls, considering adding them [here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/test/MUXControlsReleaseTest/MUXControls.ReleaseTest/NugetTestsCX.cs) and [here](https://github.com/microsoft/microsoft-ui-xaml/blob/master/test/MUXControlsReleaseTest/NugetPackageTestAppCX/MainPage.xaml), those tests run in every CI build. But I want to make sure this is CX only issue first since adding C# tests are easier...

@jevansaks is there any entrance on C# side that can get us to NotifyCollectionChangedAction::Reset? I didn't find anything in [OberservableCollection](https://docs.microsoft.com/en-us/dotnet/api/system.collections.objectmodel.observablecollection-1?view=netframework-4.8).

**Comment by jevansaks** [comment] 2019-09-27 04:32
[Looking at the source](https://github.com/dotnet/corefx/blob/master/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs) I don't think it does it normally. It comes up for custom data sources though, you could maybe just derive from it and mimic this problem?

**Comment by chingucoding** [comment] 2019-09-27 08:36
> [Looking at the source](https://github.com/dotnet/corefx/blob/master/src/System.ObjectModel/src/System/Collections/ObjectModel/ObservableCollection.cs) I don't think it does it normally. It comes up for custom data sources though, you could maybe just derive from it and mimic this problem?

I think, indeed, we could recreate this in C# when using a custom data source. The easiest would be to derive from ObservableCollection and e.g. add a replace all function which raises the corresponding event.

**Comment by chingucoding** [comment] 2019-09-27 11:27
So I found a fix for this problem:

```c++
    case winrt::NotifyCollectionChangedAction::Reset:
    {
        int count = m_itemsDataSource.Count();
        int childrenCount = Children().Size();

        if (count > 0) {
            // Reset was raised as part of massive collection changes!
            // Add all items to the children
            AddToChildrenNodes(0, count);
        }
        RemoveFromChildrenNodes(count, childrenCount);
        break;
    }
```

The problem is, we can't really use `Clear()` since calling `Children.Clear` will modify `ItemsSource` depending on the binding. So replacing https://github.com/microsoft/microsoft-ui-xaml/blob/803f4797a19ae03a428c8781bef85190e8855f1e/dev/TreeView/TreeViewNode.cpp#L195-L202 with the snippet, will solve the problem in question.

See [this branch](https://github.com/chingucoding/microsoft-ui-xaml/tree/observablecollection-replaceall-fix), where the fix is applied.

**Comment by kaiguo** [comment] 2019-09-27 18:14
@chingucoding with custom data source you can probably just add API tests for the changes, which sounds easier than adding c++ nuget tests.

Also, Clear actually has a parameter for ItemsSource updates, the code below won't update ItemsSource.
``` c++
winrt::get_self<TreeViewNodeVector>(Children())->Clear(/*updateItemsSource=*/ false);
```

I saw we had a sync function, I *think* you can just call SyncChildrenNodesWithItemsSource() to reset in this TreeView case.

**Comment by chingucoding** [comment] 2019-09-27 21:18
> @chingucoding with custom data source you can probably just add API tests for the changes, which sounds easier than adding c++ nuget tests.
> 
> Also, Clear actually has a parameter for ItemsSource updates, the code below won't update ItemsSource.
> 
> ```c++
> winrt::get_self<TreeViewNodeVector>(Children())->Clear(/*updateItemsSource=*/ false);
> ```
> 
> I saw we had a sync function, I _think_ you can just call SyncChildrenNodesWithItemsSource() to reset in this TreeView case.

Yes SyncChildrenNodesWithItemsSource() does fix this problem, brilliant idea!

Yes I think adding api test(s) would be easier. My idea would be to create a subclass of ObservableCollection in MuxControlsTestApp.Shared that would trigger that behaviour, since this will probably be useful in multiple tests. @kaiguo Would this be a good idea?

What would you (@jevansaks and @kaiguo) suggest moving forward? Should I first create a PR fixing this issue and over the next days create a PR fixing the other controls that have the same problem?

**Comment by kaiguo** [comment] 2019-09-27 21:42
Yeah I think it's fine to add the shared subclass to MuxControlsTestApp.Shared. And creating separate PRs sounds to me, we can loop in other area owners this way and make sure we don't break their stuff 😅

**Closed** 2019-10-01 01:05 UTC
Labels: area-TreeView, bug, working on it
