### ISSUE TITLE
Vertical alignments of text is off

### ISSUE THREAD

**Issue by eric-vogt-pacesetter** [microsoft/microsoft-ui-xaml#10177] opened 2024-11-18 21:56 UTC
### Describe the bug

Vertical alignment of text in a button is higher than it used to be:

![Image](https://github.com/user-attachments/assets/4bf1b0ec-2145-4f90-a7c1-ebba2772f509)

Purple background is Microsoft.WindowsAppSDK Version="1.6.240923002"
Blue background is Microsoft.WindowsAppSDK Version="1.5.240802000"

I've had the same issue with TextBlock and Button

XAML for button:
```xaml
<Button
    VerticalContentAlignment="Center"
    BorderThickness="0"
    CornerRadius="90"
    FontSize="15"
    Background="#bb2d1c"
    FontWeight="Bold"
    Foreground="White">
E
</Button>
```

### Steps to reproduce the bug

See description

### Expected behavior

See description

### Screenshots

See description

### NuGet package version

None

### Additional context

Windows 10 Build 19045

**Comment by Balkoth** [comment] 2024-11-19 19:37
Its a known problem to the devs that this is broken since v1.6.0 on Windows 10.

**Comment by karkarl** [comment] 2024-12-26 17:01
Resolving as dupe of #10014

**Closed by karkarl** 2024-12-26 17:01 UTC
Labels: bug, needs-triage
