### ISSUE TITLE
Icon Reversed

### ISSUE THREAD

**Issue by EmployeePortalBug** [microsoft/microsoft-ui-xaml#7371] opened 2022-07-14 07:46 UTC
### Describe the bug

Stock up and Stock Down Icons are reversed, can you please check

### Steps to reproduce the bug

NA

### Screenshots

![image](https://user-images.githubusercontent.com/109273697/178929815-507c28c2-5a18-4711-b45a-4f36820aa189.png)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by krschau** [comment] 2022-07-14 15:59
This is a known issue that will be fixed in the next font refresh. In the meantime, you can opt to switch the icons in your app.

**Comment by krschau** [comment] 2022-07-14 15:59
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/7332

**Closed by krschau** 2022-07-14 15:59 UTC
Labels: duplicate, area-External
