### ISSUE TITLE
Unable to create unit tests for a project that sets `XamlControlsResources`

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#230] opened 2019-01-28 14:43 UTC
**Describe the bug**
Setting `XamlControlsResources` as a resource in an app means the app can't be tested with a `Unit Test App (Windows Universal)` app.

**Steps to reproduce the bug**

1. Create a new, blank UWP app 
![image](https://user-images.githubusercontent.com/189547/51842344-90f1ff80-2308-11e9-94ef-c032a6088ecc.png)
2. Set the target framework to be 1809
![image](https://user-images.githubusercontent.com/189547/51842396-aff09180-2308-11e9-8746-b6ac1a741849.png)
3. Add a `Unit Test App (Windows Universal)` app to the solution and set the same target/min framework versions as the app.
![image](https://user-images.githubusercontent.com/189547/51843401-c7c91500-230a-11e9-9095-753ecded17e6.png)
4. Add a reference in the test app that points to the blank app.
5. Run the default test "TestMethod1". It will pass.
![image](https://user-images.githubusercontent.com/189547/51842671-5b014b00-2309-11e9-88f7-dd8aa81f8d81.png)
6. In both apps, add a reference to `Micrsoft.UI.XAML` (version 2.0.181018003.1). The test project will raise a warning if it doesn't have the reference but will still work without it.
7. Run the unit test again. It will still pass.
8. In `App.xaml` in the blank project, add the required reference to `XamlControlsResources`.
```
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
    </Application.Resources>
```
9. Run the unit test again.

**Expected behavior**
Expect the test to pass.

**Actual behavior** 
The test doesn't even run. The status bar states "Unexpected error detected."

 From the test output pane:
```
[1/28/2019 2:35:31 PM Informational] ------ Run test started ------
[1/28/2019 2:35:44 PM Error] Failed to initialize client proxy: could not connect to test process.
[1/28/2019 2:35:44 PM Error] Failed to initialize client proxy: could not connect to test process.
[1/28/2019 2:35:44 PM Informational] ========== Run test finished: 0 run (0:00:12.429535) ==========
```

**Version Info**

Windows 10, Version 1803 (17134.523)
VS 2017 15.9.6

NuGet package version: 
Microsoft.UI.Xaml 2.0.181018003.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   |   |
| April 2018 Update (17134)        |  Yes   |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by crutkas** [comment] 2019-01-28 18:16
For more context, this is blocking Windows Template Studio from shipping Unit Test projects.

**Comment by kmahone** [comment] 2019-01-28 21:33
I took a look at this issue.

The problem is that the Unit Test project does not generate an IXamlMetadateProvider, so when the runtime tries to get the Xaml metadata for XamlControlsResources, it fails.

It is possible to workaround this issue by forcing the Unit Test project to generate an IXMP, e.g. by adding a reference to a dummy custom type into UnitTestApp.xaml
`<Style TargetType="local:MyButton" />`

`public class MyButton : Windows.UI.Xaml.Controls.Button { }`

I need to figure out why the Unit Test Project is not generating IXMP.

**Comment by mrlacey** [comment] 2019-01-29 09:21
@kmahone As a workaround this is great. Thank you for such a quick triage.
It would still be good to address the underlying issue with the Unit Test Project.

**Comment by kmahone** [comment] 2019-02-01 20:31
I've filed an [internal issue](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/784279) to track this.

**Comment by jevansaks** [comment] 2019-02-27 18:14
Tracked as dotnet/test-templates#56, closing this issue.

**Comment by tonuv** [comment] 2019-04-09 17:21
I tried the workaround suggested - did not fix the issue

**Comment by llongley** [comment] 2019-04-12 22:54
@mayankbansal018 - I've uploaded a repro app here: [Issue230ReproApp.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3075386/Issue230ReproApp.zip)

If you remove the reference to App2 in UnitTestProject and instead add an explicit reference to Microsoft.UI.Xaml, the issue no longer repros.

**Comment by jevansaks** [comment] 2019-04-30 17:10
@mayankbansal018 when do you expect to be able to look into this?

**Comment by mayankbansal018** [comment] 2019-05-01 05:49
I apologise for the delay here, unfortunately I'm busy with some high priority tasks this week, will definitely look into this early next week.

**Comment by mayankbansal018** [comment] 2019-05-29 09:33
@llongley, apologies for delay on this, I just checked your csproj for Unit Test project, & turns out it doesn't have reference to `Microsoft.UI.XAML` nuget, once I added it things worked fine.

Can you please try the same?

Just an update, seems like the fixes I made have not flown in VS2019 update 1 yet, will ping the teams internally to see why is it so.

**Comment by jevansaks** [comment] 2019-07-03 17:00
@mrlacey not sure if you're still seeing this, but if you add the MUX dependency to the test project does that resolve it?

I'm not sure if this should be required or if that's what the new "buildTransitive" folder would help with...

**Closed by jevansaks** 2019-07-03 17:00 UTC
Labels: needs: follow-up

**Comment by mgollubske** [comment] 2019-11-06 21:03
I get  the error " System.TypeLoadException: 'Could not find Windows Runtime type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'.' in my UWP.  It has me very confused as it works fine in the Debug Configuration.  However, the project also has a configuration called Test that I will get that error for?  Is there something with the nuget library and different configurations that it has issues with?

**Comment by llongley** [comment] 2019-11-06 21:06
I think you're hitting a regression that was introduced recently.  [This pull request](https://github.com/microsoft/microsoft-ui-xaml/pull/1560) should fix the issue you describe.

**Comment by mgollubske** [comment] 2019-11-06 21:24
Do you have an estimate of when that fix may be available via nuget?

**Comment by llongley** [comment] 2019-11-06 21:29
Once it's checked in, which should happen as soon as PR checks pass, it should be available in prerelease after the CI build picks up that commit.  That generally happens about an hour after checking in.

**Comment by llongley** [comment] 2019-11-07 00:03
Actually, sorry, I misremembered - our CI build publishes to a private feed to test nuget restore; that doesn't go to nuget.org.  We publish to nuget.org on a monthly basis, so the regression I mentioned shouldn't have been published yet.

**Comment by hernandik** [comment] 2020-11-18 13:16
> I took a look at this issue.
> 
> The problem is that the Unit Test project does not generate an IXamlMetadateProvider, so when the runtime tries to get the Xaml metadata for XamlControlsResources, it fails.
> 
> It is possible to workaround this issue by forcing the Unit Test project to generate an IXMP, e.g. by adding a reference to a dummy custom type into UnitTestApp.xaml
> `<Style TargetType="local:MyButton" />`
> 
> `public class MyButton : Windows.UI.Xaml.Controls.Button { }`
> 
> I need to figure out why the Unit Test Project is not generating IXMP.

Hello. Sorry, but that is not clear how to put this in the file UnitTestApp.zaml, since it has only resource dictionarie entries.
Could someone please supply a more 'complete' version of the xaml containing this fix?

**Comment by michael-hawker** [comment] 2025-12-02 05:38
Had an old project which I was trying to test some MUXC namespace stuff to, needed to update it to match new template. Linking to that PR to make it a bit clearer for the workaround: https://github.com/dotnet/test-templates/pull/56

However, that doesn't seem to be working for me still. I am using XamlReader.Load, but haven't seen issue with this doing the same thing in other projects, so I'm a bit confused on what I may be missing still. Switched it over to a Page within the project itself to remove the dynamic load and was the same issue.
