### ISSUE TITLE
Visual Studio does not want that CornerRadius of a edit Button template will crash on older Windows updates

### ISSUE THREAD

**Issue by ArchieCoder** [microsoft/microsoft-ui-xaml#1285] opened 2019-09-06 00:22 UTC
**Describe the bug**
Editing a button template will generate the ContentPresenter with the attribute CornerRadius, but Visual Studio does not warn that the attribute is not supported on 17134 or older builds. However, Visual Studio warns for the BackgroundSizing attribute.

**Steps to reproduce the bug**
1. Edit a template of a Button and use the button template in MainPage.xaml
2. Deploy on 17134 -> Crash

**Expected behavior**
No crash and for the benefits to everyone, the XAML engine at runtime should be smart and ignore invalid/not-supported attributes.

**Screenshots**
See screenshot

**Version Info**
Create the button with 17763 and deploy with 17134

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | No  |
| October 2018 Update (17763)        | No  |
| April 2018 Update (17134)          | Yes  |
| Fall Creators Update (16299)       | Yes   |
| Creators Update (15063)            |  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

![CornerRadius](https://user-images.githubusercontent.com/1608424/64392298-10238080-d01a-11e9-88d0-5b339e5befdd.jpg)

**Comment by jevansaks** [comment] 2019-09-09 19:41
Dupe of #1288?

**Closed by jevansaks** 2019-09-09 19:41 UTC
Labels: duplicate

**Comment by ArchieCoder** [comment] 2019-09-09 20:24
1288 was an invalid value.
This one is an invalid attribute.

I can be a duplicate based on the fact that VS just takes a snapshot of the General xaml file.
