### ISSUE TITLE
Shadows on Flyout flicker upon opening

### ISSUE THREAD

**Issue by Aurumaker72** [microsoft/microsoft-ui-xaml#7630] opened 2022-08-21 18:41 UTC
### Describe the bug

When a MenuFlyout's MenuFlyoutItem finishes animating after clicking on it, its shadow shortly flickers before reappearing.

This phenomenon is best visible against a high-contrast background.

### High-Contrast scenario
1. Define your controls in an empty Window the following way:
```xml
<Grid Background="Red">
        <MenuBar Background="Transparent">
            <MenuBarItem Title="File">
                <MenuFlyoutItem Text="Open"/>
            </MenuBarItem>
        </MenuBar>
</Grid>
```

### General scenario
1. Define your controls in an empty Window the following way:
```xml
<Grid>
        <MenuBar>
            <MenuBarItem Title="File">
                <MenuFlyoutItem Text="Open"/>
            </MenuBarItem>
        </MenuBar>
</Grid>
```

2. Run the application
3. Click the `MenuBarItem` and observe the shadow flickering

### Expected behavior

The shadow is expected to remain visible throughout all stages of its animation.

### Screenshots

https://user-images.githubusercontent.com/48759429/185805788-ceee788a-08c1-4603-bbe1-81cb6af8d4db.mp4

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

This issue is less noticeable in low-contrast situations, but persists nevertheless.

**Comment by cyberrex5** [comment] 2022-08-24 20:12
much more visible and annoying in light mode
![Desktop 2022 08 24 - 22 58 06 02_1](https://user-images.githubusercontent.com/67976161/186514061-3a2f18ef-4c28-4537-9048-99499d7e3b6a.gif)

**Comment by contextfree** [comment] 2022-08-25 19:10
These kinds of issues have been rampant for me in WinUI2/UWP and WinUI3 ever since drop shadows were introduced. Just as a user I find them really annoying, makes me subconsciously dread opening flyouts.

**Comment by bogdan-patraucean** [comment] 2023-01-08 19:48
Any update on this? it's still happening

**Comment by cyberrex5** [comment] 2023-04-13 12:54
seems to be fixed now

**Comment by Aurumaker72** [comment] 2023-04-13 15:08
Sounds good to me

**Comment by bogdan-patraucean** [comment] 2023-04-24 22:29
The issue is still reproducing for MenuFlyoutSubItem, it should be reopened.

**Comment by Aurumaker72** [comment] 2023-05-14 07:09
> The issue is still reproducing for MenuFlyoutSubItem, it should be reopened.

I can't reproduce this on `1.3.230502000`.


https://github.com/microsoft/microsoft-ui-xaml/assets/48759429/174c8fbb-6d7e-4aa3-beba-cdf03671c941

**Closed** 2023-06-11 08:36 UTC
Labels: bug, team-Rendering, needs-review 👀
