### ISSUE TITLE
When closing tabviewitem ( webview2 does not dispose )

### ISSUE THREAD

**Issue by jarno9981** [microsoft/microsoft-ui-xaml#7526] opened 2022-07-25 11:08 UTC
### Describe the bug

I have multible tabs open where there are user controls in them with webview2 when i close a tab is say this.usercontrols.items.dispose

To destroy the items en turn them of 

But webview2 thread keeps living in eco mode 

### Steps to reproduce the bug

1. Make a uwp app with tabview
2. Make a costum usercontrol with latest webview2
3. Open a second tab
4. Close the tab 
5. Look in taskmgr you see the second tab thread still exist for webview2

### Expected behavior

That the webview2 thread stops en gets killed so no extra threads exist in the app

### NuGet package version

Microsoft.UI.Xaml 2.8.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by krschau** [comment] 2022-07-25 17:27
Possible dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/5622

**Closed** 2023-08-03 22:52 UTC
Labels: bug, area-WebView, team-Rendering, product-winui2, no-issue-activity
