### ISSUE TITLE
Type parameter using x:TypeArguments in Xaml does not compile in derived Page Control 

### ISSUE THREAD

**Issue by David-Buyer** [microsoft/microsoft-ui-xaml#7746] opened 2022-09-20 07:11 UTC
### Describe the bug

I suppose this refers to #931

I'm attempting to create a derived Page class inherits from a Page class control, using a generic type parameter in class declaration. In the related Xaml i attempted to use this derived Page as root element passing the type parameter with x:TypeArguments attribute syntax but in the generated **_code.g.cs_** type parameter is not used and compilation fails as it's required obviously. 

### Steps to reproduce the bug

Base class;

```
namespace FunzionarioItinerante3UI.ContentViews.Base
{
    public class ModelPageBase<T> : Page where T : class, new()
    {
     
    / * ..... */
     
    }

}
```

Derived Class:

```
namespace FunzionarioItinerante3UI.ContentViews
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class PassaportoOrdinario : ModelPageBase<PassaportoOrdinarioModel>, IStatefulPage
    {
  
      /* .... */

    }
}

```

Xaml:

```
<local:ModelPageBase
    x:TypeArguments="models:PassaportoOrdinarioModel"
    x:Class="FunzionarioItinerante3UI.ContentViews.PassaportoOrdinario"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:FunzionarioItinerante3UI.ContentViews.Base"
    xmlns:models="using:FunzionarioItinerante3UI.Models"
    xmlns:controls="using:FunzionarioItinerante3UI.Controls.Input"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="Transparent">
    <Grid Padding="15" x:Name="GridPanelContainer">
        <Grid.RowDefinitions>
            <RowDefinition Height="auto" />
            <RowDefinition Height="auto" />
            <RowDefinition Height="auto" />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="0.5*" />
            <ColumnDefinition Width="0.5*" />
        </Grid.ColumnDefinitions>
        <TextBlock Margin="0 10 10 20" Style="{StaticResource TitleLabel}" Text="Dati Generali" />
    </Grid>
</local:ModelPageBase>
```

Result ( error -> ModelPageBase requires a 1 type parameter ):

```
namespace FunzionarioItinerante3UI.ContentViews
{
    partial class PassaportoOrdinario : global::FunzionarioItinerante3UI.ContentViews.Base.ModelPageBase
    {

    /* .... */    

    }
}
```
Compilation fails.

### Expected behavior

The type parameter should be passed to .g.cs file to compile as:

```
namespace FunzionarioItinerante3UI.ContentViews
{
    partial class PassaportoOrdinario : global::FunzionarioItinerante3UI.ContentViews.Base.ModelPageBase<PassaportoOrdinarioModel>
    {

    /* .... */    

    }
}
```
It would be good to know if there are any progresses about supporting this feature.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by evelynwu-msft** [comment] 2022-11-29 03:26
Support for `x:TypeArguments` would fall under #7037. I'm going to close this as it is a duplicate of the broader feature request.

**Closed by evelynwu-msft** 2022-11-29 03:26 UTC
Labels: bug, feature proposal, area-XamlCompiler, area-Parser, team-Markup, product-winui3
