### ISSUE TITLE
Double-clicking the title to maximise still works after setting AppWindow.Presenter.IsMaximizable to false

### ISSUE THREAD

**Issue by JaiganeshKumaran** [microsoft/microsoft-ui-xaml#8897] opened 2023-09-19 12:42 UTC
Even after setting AppWindow.Presenter.IsMaximizable to false, it seems to be possible to maximise the window by double-clicking the title bar. Also I notice that in this case, the maximised window also covers the taskbar.

**Comment by bpulliam** [comment] 2023-09-21 19:06
Duplicate of #8666

**Closed by bpulliam** 2023-09-21 19:06 UTC
Labels: area-AppWindow, team-CompInput
