### ISSUE TITLE
[WinUI3.0 Desktop(App and ClassLibrary)] A UserControl in a ClassLibrary can't be dynamically loaded by a custom AssemblyLoadContext class

### ISSUE THREAD

**Issue by SunnyWang1012** [microsoft/microsoft-ui-xaml#3888] opened 2021-01-05 03:04 UTC
I create several projects and the relations are as following:
![structure](https://user-images.githubusercontent.com/7006770/103599885-1e045100-4f41-11eb-9f38-2bfdd6a8e3f3.jpg)

In short, I want to use WinUI 3.0 Desktop **App** to dynamically load a ClassLibrary named **HelloPlugin.dll**. 

- Both **App** and **HelloPlugin.dll** add reference to an interface "ICommand" in **PluginBase.dll**
- **HelloPlugin.dll** implements the "ICommand" interface which includes a field of UserControl.
-  **HelloPlugin.dll** add reference to another ClassLibrary named **DataProvider.dll**
- I implement a custom **AssemblyLoadContext** in **App** to dynamically load **HelloPlugin.dll** and code snippets is as following 
   ![code](https://user-images.githubusercontent.com/7006770/103601617-fb743700-4f44-11eb-8bb7-6557c9234564.jpg)

[Bug]
I can successfully load **HelloPlugin.dll** in **App** and activate as **ICommand** and some fields leveraging **DataProvider.dll** are also loaded successfully. 
However, when I invoke to get that UserControl field, it crashes at UserControl's constructor show as followings
![error1](https://user-images.githubusercontent.com/7006770/103601165-07132e00-4f44-11eb-8705-2a42d678de40.jpg)
![error2](https://user-images.githubusercontent.com/7006770/103601182-0f6b6900-4f44-11eb-82b7-bc4e8dd7ed1a.jpg)

Can you help to see if I miss anything in order to load resource of UserControl?

**Comment by ranjeshj** [comment] 2021-01-06 00:10
@jevansaks @MikeHillberg any thoughts ?

**Comment by jevansaks** [comment] 2021-01-06 04:19
The error message in the output is "NamedResource Not found", coming from MRM.dll. That sounds like there's a path to an asset or something that's being requested which can't be resolved by MRT.

@SunnyWang1012 look closer at the HelloUserControl.xaml (or share more of the project for us to take a look at) to see where there might be a problem with an ms-appx or ms-resource URI in that file.

**Comment by SunnyWang1012** [comment] 2021-01-06 07:43
@jevansaks The following screenshots shows the details of HelloUserControl.xaml, it actually doesn't have any content yet. I create that WinUI 3.0 UserControl by "Add New Item" to HelloPlugin project. Do you know if there is any setting I need to do in order to let **App** load this UserControl correctly?

**Comment by ValerCheck** [comment] 2021-01-06 09:29
@SunnyWang1012 possibly I have addressed similar [issue](https://github.com/dotnet/runtime/issues/46487) for dotnet/wpf repository. I may be wrong, but I had resource not found exception when was trying to load views from different plugins. Issue was closed and the answer was that it should be fixed in the scope of dotnet/wpf but not dotnet/runtime. The issue was found for views shared between multiple plugins.

**Comment by SunnyWang1012** [comment] 2021-01-07 03:04
Thanks @ValerCheck 
I disabled "JustMyCode" setting and found the exception occurs inside "this.InitializeComponent()" of HelloUserControl.xaml.cs. The following is the screenshot:
![error](https://user-images.githubusercontent.com/7006770/103845799-c2200080-50d7-11eb-90c0-26687e594d09.jpg)

I try to add **HelloPlugin** as reference project to **App** project, then it will be no problem. It seems that when dynamically loading plugins, I miss some "operation" in order to load the related resource as well...

**Comment by jevansaks** [comment] 2021-01-07 03:10
That makes sense ... but without a repro project we can't help too much. In general assets should get carried through `<ProjectReference .../>` in csproj/vcxproj but there may be some more knobs you need to set.

**Comment by SunnyWang1012** [comment] 2021-01-07 14:09
@jevansaks  
I have uploaded my projects. For your reference. thanks.
https://github.com/SunnyWang1012/WinUILoadPlugin/blob/main/README.md

**Comment by SunnyWang1012** [comment] 2021-01-12 02:59
@MikeHillberg @jevansaks  Any thought?

**Comment by SunnyWang1012** [comment] 2021-01-18 08:33
Some updates...

- I add **HelloPlugin** as a reference for **WinUILoadApp**, then the UserControl can be loaded successfully.
- I do another POC named WpfLoadDll project to implement the same way in .NET framework. It can successfully load the UserControl

**Comment by MikeHillberg** [comment] 2021-01-20 19:14
@stevenbrix, could this be an issue that when dynamically loading the DLL we're not finding the user control's XBF?

**Comment by stevenbrix** [comment] 2021-01-20 20:45
@SunnyWang1012 if you disable mixed mode debugging, does this error still persist? I'm wondering if this is the same issue as #3893

**Comment by stevenbrix** [comment] 2021-01-20 20:45
@alwu for FYI

**Comment by SunnyWang1012** [comment] 2021-01-21 10:37
@stevenbrix  After reading the issue #3893, I try to disable **winrt::hresult_error** and the UI control can be loaded successfully. Thank you so much :)

**Comment by stevenbrix** [comment] 2021-01-26 15:54
Awesome, I'm glad to hear you are unblocked! I'll close this as a dupe of #3893 then :)

**Closed by stevenbrix** 2021-01-26 15:54 UTC
Labels: winui3preview
