### ISSUE TITLE
Discussion: Tabview control in winui version 2.4  not renderd properly with  Bindng x:bind in  windows 10 OS 17134.

### ISSUE THREAD

**Issue by mraju2** [microsoft/microsoft-ui-xaml#3623] opened 2020-11-17 17:15 UTC
I have used winui 2.4(Microsoft-UI-XAML) tab view control to display data.
But in Windows OS version  17134  tab control not displaying the data , in the next versions 17763,18363 able to see the data in a tab view. I suspect is it problem with tabcontrol along with binding(x:bind).  tab headers are bind with `data`

wrong display os version 17134
![image](https://user-images.githubusercontent.com/8207926/99422472-99745980-2925-11eb-94e6-9d999b4d01fc.png)

correct display os version 18363
![image](https://user-images.githubusercontent.com/8207926/99422762-e22c1280-2925-11eb-91df-6a7d044e8061.png)

```<xmlc:TabView x:Name="TaskTabsControl" Background="Transparent" Grid.Row="0" HorizontalAlignment="Stretch" VerticalAlignment="Stretch" TabWidthMode="SizeToContent"  CanReorderTabs="false" CanDragTabs="false" CanDrag="false"
                                  IsAddTabButtonVisible="False"
                                      Margin="0" TabItemsSource="{x:Bind TaskTabData,Mode=TwoWay}" >
            <xmlc:TabView.TabStripHeader>
                <Grid x:Name="ShellTitlebarInset" Background="Transparent" Height="30" />
            </xmlc:TabView.TabStripHeader>
            <xmlc:TabView.TabItemTemplate>
                <DataTemplate>
                    <xmlc:TabViewItem x:Name="tabHeader"  Background="Transparent"  Header="{Binding TaskHeader}"  Margin="0,0,0,0"
                                     IsEnabled="{Binding IsEnabled}" IsClosable="false" >
                        <ItemsControl Grid.Row="1" x:Name="itemsControlTask" ItemsSource="{Binding Tasks}">
                            <ItemsControl.ItemsPanel>
                                <ItemsPanelTemplate>
                                    <controls:UniformGrid Margin="0,3,0,0" Rows="6" Columns="5" RowSpacing="4" ColumnSpacing="4"/>
                                </ItemsPanelTemplate>
                            </ItemsControl.ItemsPanel>
                            <ItemsControl.ItemTemplate>
                                <DataTemplate>
                                            <ToggleButton x:Name="TaskButton" IsEnabled="{Binding IsActive,Mode=TwoWay}"
                                                      IsChecked="{Binding IsChecked, Mode=TwoWay}"
                                                      HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
                                                <TextBlock x:Name="taskText" MaxLines="2"   
                                            TextWrapping="Wrap" TextTrimming="CharacterEllipsis"    Text="{Binding TaskName}"
                                            ></TextBlock>

                                            </ToggleButton>
                                </DataTemplate>
                            </ItemsControl.ItemTemplate>
                        </ItemsControl>
                    </xmlc:TabViewItem>
                </DataTemplate>
            </xmlc:TabView.TabItemTemplate>
        </xmlc:TabView>```

How to fix the issue in os 17134 , should I need to install any sdk component.

**Comment by Felix-Dev** [comment] 2020-11-17 17:36
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/2427.

**Comment by ranjeshj** [comment] 2020-11-18 00:10
@mraju2 can you try this with latest winui 2.5 prerelease bits ?

**Comment by mraju2** [comment] 2020-11-18 08:34
@ranjeshj I have tried with 2.5 prerelease bits but still facing the issue

**Closed** 2023-08-03 22:39 UTC
Labels: question, no-issue-activity
