### ISSUE TITLE
Winui Print API

### ISSUE THREAD

**Issue by Redp87** [microsoft/microsoft-ui-xaml#7234] opened 2022-06-14 06:18 UTC
Hi, please add the Print API as fast as you can. I'm stuck with no solution after months of development with Winui.
The Print API is a must.
Thank you.

**Comment by castorix** [comment] 2022-06-14 06:28
> I'm stuck with no solution after months of development with Winui. 

There are several ways to print, like PrintDocument from 
System.Drawing.Printing (I had posted a basic sample), Win32 Print APIs (GDI), ...

**Comment by Redp87** [comment] 2022-06-14 06:38
I'm doing that in WPF. I actually ported my app to WinUI to use native modern APIs.

**Comment by ghost1372** [comment] 2022-06-15 14:57
if you mean, print api for WinUI 3, Microsoft released it today
https://github.com/marb2000/PrintSample

But I think we have to wait for the new Nuget package

**Comment by Redp87** [comment] 2022-06-15 16:27
Did someone test this? I'll test it as soon as possible and give feedback. Thanks.

**Comment by marb2000** [comment] 2022-06-15 20:54
Hi there! 

You can safely use these Printing APIs within the bits of WinAppSDK 1.1 and 1.0. Just use the PrintManagerInterop API to set the Window handle that will host the Printing UI.
```CS

var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
PrintManager printMan = PrintManagerInterop.GetForWindow(hWnd);

```

**Comment by Redp87** [comment] 2022-06-15 21:55
> Hi there!
> 
> You can safely use these Printing APIs within the bits of WinAppSDK 1.1 and 1.0. Just use the PrintManagerInterop API to set the Window handle that will host the Printing UI.
> 
> ```cs
> var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
> PrintManager printMan = PrintManagerInterop.GetForWindow(hWnd);
> ```

Thank you.

**Comment by krschau** [comment] 2022-06-15 22:51
Closing as dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/4419

**Closed by krschau** 2022-06-15 22:51 UTC
Labels: duplicate, needs-triage

**Comment by Redp87** [comment] 2022-06-16 14:53
Just posted there.
