### ISSUE TITLE
"A cycle occurred while laying out the GUI." Exception occurred while adding the Inlines to the TextBlock in WINUI_Desktop

### ISSUE THREAD

**Issue by SathiyathanamSathish** [microsoft/microsoft-ui-xaml#6637] opened 2022-01-26 10:27 UTC
### Describe the bug

**"A cycle occurred while laying out the GUI." exception occurred while adding the Inlines to the TextBlock in WINUI**

### Steps to reproduce the bug

1. Run the attached Sample.
2. Note the "A cycle occurred while laying out the GUI." exception occurred.

You can find the sample in the bottom of the query.

### Expected behavior

The "A cycle occurred while laying out the GUI." exception should not occur and TextBlock should update based on the Inlines.

### Screenshots

![image](https://user-images.githubusercontent.com/89458634/151144264-21d9746a-e9dd-4a74-9a73-1d60ca5eeb25.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

We have a custom button that has the content as ContentPresenter. By using this custom button we have tried to change the TextBlcok foreground based on its content by using the [Run](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.documents.run?view=winui-3.0#properties) and [TextBlock.Inlines](https://docs.microsoft.com/en-us/dotnet/api/system.windows.controls.textblock.inlines?view=windowsdesktop-6.0). Please refer to the below image which we have tried 

![image](https://user-images.githubusercontent.com/89458634/151145356-b1d14d60-23d5-4333-ad9a-5bbd1966612f.png)

![image](https://user-images.githubusercontent.com/89458634/151145492-dc682efc-9ae0-418a-b43a-cd78756c5cf0.png)

And in the Custom Button ArrangeOverride method, I have changed the custom button contentpresenter ie. TextBlcok inline based on its content. While I am doing this, the button ArrangeOverride is called multiple times so that only this exception occurred. **We need to know why the Button ArrangeOverried is called multiple times when we change textblock inlines.**

### Sample Location

**WINUI Sample** - [TextBlock_Inline_WINUI.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7940871/TextBlock_Inline.zip)

And i have added the same codes in **UWP** platform. In **UWP** also the same **"Layout cycle detected."** exception occurred.

**UWP Sample** - [TextBlock_Inline_UWP.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7942557/TextBlock_Inline.zip)

But the same codes does not occurs any issues in **WPF** sample and ArrangeOverride is also called only one time:

**WPF Sample** - [TextBlock_Inline_WPF.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7942567/TextBlock_Inline_WPF.zip)

**Comment by gabbybilka** [comment] 2022-02-08 08:07
Duplicate of #6642

**Closed by gabbybilka** 2022-02-08 08:07 UTC
Labels: needs-triage
