### ISSUE TITLE
Question: Why I can't see the XAML designer?

### ISSUE THREAD

**Issue by JunaidQadirB** [microsoft/microsoft-ui-xaml#2428] opened 2020-05-11 12:26 UTC
I'm using WinUI 3.0.0.alpha.200210.0 and I'm using Visual Studio 2019 Community Edition.
I created a new Blank App (WinUI UWP) project and restored the dependencies.

App compiles and runs fine but the problem is I cannot see the XAML designer. it just displays the XML markup only.

XAML designer works fine with WPF apps.

How do I enable XAML designer?

**Comment by MikeCodesDotNET** [comment] 2020-05-14 20:57
I’m experiencing the same issue. Is this intended behaviour?

**Comment by venklar** [comment] 2020-06-27 21:26
As far as I know there's no visual designer available at the moment and I can't see it anywhere in the roadmap. I really hope that will be done at some point as for me it's the top missing feature.

**Comment by venklar** [comment] 2020-08-10 19:08
This issue is listed under Preview 2's known issues and limitations ("No visual designer"). Can anyone advise on current status?

**Comment by asklar** [comment] 2021-07-23 04:57
Duplicate of #4195

**Closed by asklar** 2021-07-23 04:57 UTC
Labels: product-winui3, question, team-Markup, version-winui3α
