### ISSUE TITLE
ComboBox dropdown arrow cropped and size reduced  while customising the height using Style property

### ISSUE THREAD

**Issue by mageshsankar** [microsoft/microsoft-ui-xaml#4396] opened 2021-03-02 12:42 UTC
**Describe the bug**

While customising the height of ComboBox using `Style` property , the dropdown arrow cropped. If we use direct `Height` properties, then it working fine.

Note: It will occurred while we setting small value to `Height` property.

Sample:

[ComboBox_DropDownCropped.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6068629/ComboBox_DropDownCropped.zip)

**Steps to reproduce the bug**

1. Extract the sample.
2. Run the sample.
3. Compare the first and second ComboBox dropdown arrow.
4. Note, the second ComboBox dropdown arrow cropped and Arrow size looks small.

**Expected behavior**

The second ComboBox dropdown arrow should be displayed properly with same size as like as first ComboBox .

**Screenshots**

![image](https://user-images.githubusercontent.com/55440472/109648975-46937a80-7b81-11eb-9747-05ceedd05f22.png)

**Version Info**

NuGet package version: 

[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes  |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-03-03 00:13
@mageshsankar do you know if this is also an issue in System Xaml? (Winui2)

**Comment by StephenLPeters** [comment] 2021-03-03 00:17
Looking at the template I see that the chevron textblock has its min height set to the theme resource ComboBoxMinHeight which has a value of 32. You can try overriding that resource and see if that allows your chevron to scale to a smaller size and not get clipped.

**Comment by jschwizer99** [comment] 2021-03-04 18:07
@StephenLPeters, Hi Stephen I suffer from the same issue as I would like to use the compact mode `Microsoft.UI.Xaml/DensityStyles/Compact.xaml` and would expect that the `ComboBox` has the same height as normal input elements. Just forcing the control height leads to the clamped glyph as described above.

When I modify the Margin="0,10,10,10" by removing the top and bottom margin I get the expected results. IMHO, the margin doesn't belong there as it prevents a proper scaling with FontSize of the element. It is enough to center the Glyph and give it a proper FontSize.

```
<FontIcon x:Name="DropDownGlyph"
                            Grid.Row="1"
                            Grid.Column="2"
                            IsHitTestVisible="False"
                            Margin="0,10,10,10"
                            Foreground="{ThemeResource ComboBoxDropDownGlyphForeground}"
                            FontFamily="{ThemeResource SymbolThemeFontFamily}"
                            FontSize="12"
                            Glyph="&#xE0E5;"
                            HorizontalAlignment="Right"
                            VerticalAlignment="Center"
                            AutomationProperties.AccessibilityView="Raw" />
```
There are several other UI controls that suffer from similar scaling issues (`ToggleSplitButton`, `NumberBox`). Is there a good way to overwrite such styles in the application resources? This way we could patch these layout issues ourselves. Many thanks in advance.

**Comment by StephenLPeters** [comment] 2021-03-04 18:46
The margin does seem strange here, at first glance it seems like the top and bottom values it wouldn't do anything helpful given the VerticalAlignment is center.  Unfortunately the only way for a developer to change this value would be to retemplate the control because this value is hard coded in the template.  If we changed it to something like

`Margin="{StaticResource ComboBoxDropDownGlyphMargin}"`

and then define that resource in Combobox_themeresources then it would be customizable by resources.  

This change seems like goodness to me, any chance you'd want to make a PR? We should also consider making the default margin value 0,0,10,0 since the top and bottom seems useless. :)

**Comment by jschwizer99** [comment] 2021-03-05 10:48
@StephenLPeters Hi Stephen, both mine and @mageshsankar reported observation relate to WinUI 3.0 Preview4. So the issue should be flagged with [preview4]. I've checked and built the master of WinUI 2.6x. There the margin is as expected `Margin="0,0,14,0"` and the compact mode behaves correctly. It was changed from `Margin="0,0,10,0"` by [#3938](https://github.com/microsoft/microsoft-ui-xaml/commit/6109cfac0e88e14e9006503ca223d3eaef4f0469).
But WinUI 3.0 Preview4 settings date back to code prior [#361](https://github.com/microsoft/microsoft-ui-xaml/commit/d2f7c91501329615ad2a2c36b5bd2b3f02fdd1a3). As I do not have access to the Preview4 code base how should I do a PR?

**Comment by jschwizer99** [comment] 2021-03-31 09:16
@StephenLPeters This issue was closed by the ms bot without any final conclusion on what the solution is. In WinUI Reunion 0.5 we still have the problematic styles visible that do not match the repo of WinUI 2.6x. Is there any help/information from my side that I could supply? Sorry that I'm insisting here, but there are other layout issues related to font size scaling. If there is soon an overhaul I will wait with reporting the other issues and wait for that release. 
![image](https://user-images.githubusercontent.com/7672712/113120730-2dc6c500-9212-11eb-8599-6783af350edc.png)
![image](https://user-images.githubusercontent.com/7672712/113120907-5e0e6380-9212-11eb-97bd-c78c9eb276c2.png)

**Comment by StephenLPeters** [comment] 2021-03-31 23:39
Sorry! our bot rules closed this when it probably should not have been.

**Comment by StephenLPeters** [comment] 2021-03-31 23:49
@jschwizer99 looking closer, the style in winui2 which contains the corrected margin is included in winui3. However we still require that you include the XamlControlsResources in your app.xaml in order to get those styles.:
```
    <Application.Resources>
        <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
    </Application.Resources>
```

Is it possible you are missing that?

**Comment by jschwizer99** [comment] 2021-04-01 16:45
@StephenLPeters, I'm using  `xmlns="using:Microsoft.UI.Xaml.Controls"` together with the compact mode `ms-appx:///Microsoft.UI.Xaml/DensityStyles/Compact.xaml`. The following resource is a minimal version to demonstrate all the weird behaviors. The following XAML code was causing the cropped glyphs as I required the height setting to correct for the non-compact height of the ComboBox.

```XML
<Application.Resources>
  <ResourceDictionary>
    <Style TargetType="TextBox">
      <Setter Property="VerticalAlignment" Value="Center"/>
      <Setter Property="Margin" Value="2"/>
      <Setter Property="BorderThickness" Value="1"/>
    </Style>
    <Style TargetType="ComboBox">
      <Setter Property="VerticalAlignment" Value="Center"/>
      <!--Setter Property="Height" Value="24.6667"/-->
      <Setter Property="Margin" Value="2"/>
      <Setter Property="Padding" Value="1.5,1.5"/> <!-- Border + 0.5 (???) = 1.5 -->
      <Setter Property="BorderThickness" Value="1"/>
    </Style>
    <Style TargetType="NumberBox">
      <Setter Property="VerticalAlignment" Value="Center"/>
      <Setter Property="Padding" Value="4,0"/>
      <Setter Property="Margin" Value="2"/>
      <Setter Property="BorderThickness" Value="1"/>
    </Style>
    <ResourceDictionary.MergedDictionaries>
      <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
      <ResourceDictionary Source="ms-appx:///Microsoft.UI.Xaml/DensityStyles/Compact.xaml" />
      <ResourceDictionary>
        <ResourceDictionary.ThemeDictionaries>
          <!-- Theme Resources -->
        </ResourceDictionary.ThemeDictionaries>
      </ResourceDictionary>
    </ResourceDictionary.MergedDictionaries>
  </ResourceDictionary>
</Application.Resources>
```
![image](https://user-images.githubusercontent.com/7672712/113325151-4faa6f80-9318-11eb-9e37-eedb200e178e.png)

Based on your questions above I experimented with changes. First I noted that removing the ComboBox style fully indeed shows the expected behavior.
![image](https://user-images.githubusercontent.com/7672712/113325321-8f715700-9318-11eb-83c7-877278d6cfd4.png)

But I need some stylings for the ComboBox, so this is not an option. The property editor indicated that as soon as `<Stlye TargetType="ComboBox"></Style>` is present it takes different default values.

A [stackoverflow entry](https://stackoverflow.com/questions/62755030/winui-uwp-how-to-create-a-custom-style-that-inherits-from-it) proposed `<Style TargetType="ComboBox" BasedOn="{StaticResource DefaultComboBoxStyle}">` which indeed solves the initial problem. Now, additional combobox styling can be used and we get the compact size without glyphs issues.
![image](https://user-images.githubusercontent.com/7672712/113325583-f131c100-9318-11eb-8cf4-1e6a207b93e7.png)

But the height does not correctly match. Increasing the border thickness indicates that the border of the ComboBox is calculated in the wrong direction. For the ComboBox it points inwards, for the other UI-elements outwards.
![image](https://user-images.githubusercontent.com/7672712/113325804-2d652180-9319-11eb-9a48-54cac9d5c856.png)

As a workaround, padding of border thickness + 0.5 (???) can be added for the ComboBox.
![image](https://user-images.githubusercontent.com/7672712/113326034-774e0780-9319-11eb-8fcf-85c0f2284693.png)

With all the above changes and workarounds, the ComboBox finally has a correct scaling behavior with font size. The corner radius is different but can be easily fixed by style.

I expect that adding the `BasedOn="{StaticResource DefaultComboBoxStyle}"` code equivalent should solve the issue for @mageshsankar as well.

Question:
- Why do we need `DefaultComboBoxStyle` just for the ComboBox to get a proper default style?
- Do we need a separate ticket for the margin issue?

For the NumberBox things are worse. As soon as I use `SpinButtonPlacementMode="Inline"` style for the up-/down glyphs the layout is broken. I couldn't find a similar `BasedOn` default style as for ComBox.
![image](https://user-images.githubusercontent.com/7672712/113326490-065b1f80-931a-11eb-9185-089c9aa926e2.png)

With some experiments, I found out that the problem is the `VerticalAlignment` and `Margin` settings of the `TextBox` style. When I remove BOTH the NumberBox looks better. But there is still a height difference for a NumberBox with `SpinButtonPlacementMode="Inline"` and `SpinButtonPlacementMode="Hidden"`.
![image](https://user-images.githubusercontent.com/7672712/113326618-34406400-931a-11eb-9832-902d5a971113.png)

**Comment by StephenLPeters** [comment] 2021-04-01 17:28
Ah, okay this makes sense. Winui2 provided new styles for the system xaml controls (like combo box). I does that by publishing an unnamed style that is based on a named style that is included in XamlControlsResources.  The names styles have the name Default[Foo]Style however they are, confusingly, not the controls [metadata definded] default style, those can only be published in the same dll as the control, so the [metadata defined] default style is the one in Generic.xaml, which has the wrong margin.  So... When you define your own style that doesn't define a template, the system merges your style with the default style, resulting in what you are seeing. So for all controls authored in system xaml, we recomend that your style be based on Default[Foo]Style.

For controls authored in Winui2 the story is a little different. Because the winmd defition and style are in the same dll we were able to make them the [metadata defined] default style. This means for numberbox you don't need to do based on because the system will merge your style with ours auto matically.  We currently don't expose the default style as a named style, but we are currently having some internal talks about doing that.

In a future release of Winui3 we plan to flatten the hierarchy so that the winui2 styles become the actual default styles, however right now they are actually still separate dlls, which is why this is still an issue when using winui3.

The numberbox issue you are describing seems like a bug, I suspect it is present in winui2 as well. Can you help me narrow down the exact repro steps?

**Comment by StephenLPeters** [comment] 2021-04-01 17:30
The difference in behavior for the border thickness is super strange... @ranjeshj and @MikeHillberg

**Comment by jschwizer99** [comment] 2021-04-01 17:46
```XAML
            <Style TargetType="TextBox">
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="Margin" Value="2"/>
                <Setter Property="BorderThickness" Value="1"/>
            </Style>
            <Style TargetType="NumberBox" x:Key="UpDown">
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="BorderThickness" Value="1"/>
            </Style>
```
Results in
![image](https://user-images.githubusercontent.com/7672712/113332850-06f7b400-9322-11eb-8d8b-3455e9ef8bf3.png)

```XAML
            <Style TargetType="TextBox">
                <Setter Property="BorderThickness" Value="1"/>
            </Style>
            <Style TargetType="NumberBox" x:Key="UpDown">
                <Setter Property="VerticalAlignment" Value="Center"/>
                <Setter Property="BorderThickness" Value="1"/>
            </Style>
```
Results in
![image](https://user-images.githubusercontent.com/7672712/113333270-82596580-9322-11eb-8004-8eb344897b4f.png)

for
```XAML
                <NumberBox
                    Value="45"
                    SpinButtonPlacementMode="Inline"
                    Style="{StaticResource UpDown}"/>
```

Without Inline:
![image](https://user-images.githubusercontent.com/7672712/113333537-d5cbb380-9322-11eb-83ea-9f98d637de94.png)

**Comment by jschwizer99** [comment] 2021-04-01 17:57
@StephenLPeters, how can I find out which control is in system, and which one in WinUI2?

**Comment by MikeHillberg** [comment] 2021-04-06 14:21
About the border going in vs going out ... In layout calculations, if a parent gives a child more space than it needs, the child can set its [FrameworkElement.HorizontalAlignment](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.FrameworkElement.HorizontalAlignment) and/or [FrameworkElement.VerticalAlignment](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.FrameworkElement.VerticalAlignment) to `Stretch`, meaning that the child will grow to fill the space. But if the alignment is set to something other than `Stretch` the child will take up only the space it needs (the `DesiredSize`). For example setting `VerticalAlignment` to `Center` the child will take up only the height that it needs.

So I suspect the difference in the TextBox isn't that the border is going inwards, it's that the text box is centered by the VerticalAlignment, and no longer stretching to fill the space. The up/down buttons though are stretching.

**Comment by jschwizer99** [comment] 2021-04-06 21:29
@MikeHillberg, @StephenLPeters 
On top level, all UI elements use the `VerticalAlignment="center"` setting. As a framework user, I do not expect that some UI elements behave differently for identical style settings. I did a quick test with `VerticalAlignment="stretch"` and I didn't really see a change in behavior.
At least for the ComboBox the source looks to be something different:
![image](https://user-images.githubusercontent.com/7672712/113779622-48c39880-972e-11eb-9d38-8ac3208374ff.png)
The ComboBox uses a grid (LayoutRoot) with `BorderThickness="0"` inside a border (Background). I manually changed the color of the border to blue and the grid to red brush color and `BorderThickness="5"`, `CornerRadius="3"`. It looks as if we see in the original the inside border with gray color. As this is inside the grid (of the ComboBox element) it has to be smaller as the size calculation of the ComboBox is controlled on the grid.
The effect on the width change can be understood as well.
Here for comparison a TextBox with identical styling:
![image](https://user-images.githubusercontent.com/7672712/113780357-62b1ab00-972f-11eb-9859-ce820c15aee3.png)
I would conclude that the visible border should be the grid border and not the inner border, in order to get a correct layout behavior.

**Comment by jschwizer99** [comment] 2021-04-06 21:57
The above red border is on both top and bottom 1px too large. This is caused by an unfortunate `MinHeight="24"` value of the `DropDownGlyph` below. When correcting this as well the red border matches the expected layout behavior.

Where does the `MinHeight` come from? Why is it needed at all?

**Comment by jschwizer99** [comment] 2021-04-19 09:40
@StephenLPeters Will https://github.com/microsoft/microsoft-ui-xaml/pull/4469 fix this issue with the borders as well?

**Comment by StephenLPeters** [comment] 2021-04-19 16:56
I don't think so.. @chingucoding thoughts?

**Comment by jschwizer99** [comment] 2021-04-19 18:58
Many thanks for the confirmation. Will offer to test it if it finally makes it into a release.

**Closed** 2023-08-03 22:41 UTC
Labels: area-ComboBox, area-Styling, team-Controls, no-issue-activity
