### ISSUE TITLE
ProgressRing Indeterminate Doesn't Play Automatically 

### ISSUE THREAD

**Issue by karenbtlai** [microsoft/microsoft-ui-xaml#2151] opened 2020-03-23 22:30 UTC
**Describe the bug**

ProgressRing Indeterminate Lottie Animation doesn't play automatically when `IsIndeterminate` is set to `true` initially. 

It only plays after toggling from `IsIndeterminate="False"` back to `IsIndeterminate="True"` 

**Steps to reproduce the bug**

1. Create test app and with the following Xaml
```
<muxc:ProgressRing
        Height="40"
        Width="40"
         Margin="0,48,0,0"
         IsIndeterminate="True" />
```
2. Build Project

**Expected behavior**

Indeterminate ProgressRing Lottie animation is supposed to start automatically, but doesn't.

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.4.0-prerelease.200322001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment] 2020-03-23 22:36
I am not sure if the following issue over at the XAML Controls Gallery is also caused by this or related to this issue:
https://github.com/microsoft/Xaml-Controls-Gallery/issues/365

**Comment by ranjeshj** [comment] 2020-03-23 23:08
Looks like a related issue. @karenbtlai can you take a look at both controls ?

**Comment by karenbtlai** [comment] 2020-03-24 18:56
> I am not sure if the following issue over at the XAML Controls Gallery is also caused by this or related to this issue:
> [microsoft/Xaml-Controls-Gallery#365](https://github.com/microsoft/Xaml-Controls-Gallery/issues/365)

ProgressBar is running fine with Indeterminate as default onLoad on the most recent build. It seems to be a separate issue so I will look into it separately.

**Comment by chingucoding** [comment] 2020-03-24 19:18
Since it seems that the issue in the XCG seems to be fixed now, I don't know if there is anything to investigate now 😅

**Comment by chingucoding** [comment] 2020-06-26 17:09
Should this issue be closed since with WinUI 2.4 the `IsDeterminate` property was removed and hence this issue doesn't exist anymore?

**Comment by ranjeshj** [comment] 2020-06-30 05:27
Its coming back with [this PR](https://github.com/microsoft/microsoft-ui-xaml/pull/2584). @karenbtlai can take care of this one as part of that PR.

**Comment by chingucoding** [comment] 2020-08-04 19:05
Since the `IsDeterminate` property was reintroduced with #2584, and the behavior is correct now, I think we can close this issue.

**Comment by chingucoding** [comment] 2020-08-23 19:51
@StephenLPeters @ranjeshj FYI

**Closed** 2020-09-01 18:51 UTC
Labels: area-Progress, team-Controls
