### ISSUE TITLE
v1.3.230331000: COMException caused by App.Window.Content in Unloaded on window close

### ISSUE THREAD

**Issue by kunig30** [microsoft/microsoft-ui-xaml#8417] opened 2023-04-14 09:28 UTC
### Describe the bug

If I use `SystemBackdrop` the following exception occurs in a user controls Unloaded event when closing the main window:
```
System.Runtime.InteropServices.COMException (0x800710DD): The operation identifier is not valid. (0x800710DD)  
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)  
   at ABI.Microsoft.UI.Xaml.IWindowMethods.get_Content(IObjectReference _obj)   
   ...
```

### Steps to reproduce the bug

In the main window constructor:
```csharp
this.SystemBackdrop = new MicaBackdrop();
```

In the Unloaded event of the user control:
```csharp
private void UserControl_Unloaded(object sender, RoutedEventArgs e)
{
    if (App.Window == null) return;
    App.Window.Content.KeyUp -= WindowOnKeyUp;
}
```
This works fine if the event was invoked by navigating to another page but throws the exception when the main window was closed.  

The exception in my app is caused by accessing `App.Window.Content`.  
When I try to view the properties of `Window` in the debugger the access to `Window.SystemBackdrop` throws an exception:
```
The target process exited with code -1073741819 (0xC0000005) while evaluating the function 'Microsoft.UI.Xaml.Window.SystemBackdrop.get'.
```

### NuGet package version

1.3.230331000

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ranjeshj** [comment] 2023-07-18 22:41
@kunig30  this should be fixed in WASDK 1.4. Can you please try out 1.4 preview 1 to see if it repro's there?

**Comment by kunig30** [comment] 2023-07-19 09:20
With 1.4 preview 1, the code of my initial post still throws the same exception.
The workaround (checking AppWindow for null) still works.

**Comment by JJBrychell** [comment] 2023-08-30 03:43
This behavior is by design. You cannot access a window property once the window has started its shutdown process. When the window is closed one of the things it does is to set the window content to null, which in turn causes the unloading event on all elements to fire. But, the window is already in its closed state, so any attempt to access properties will throw a failure. It is advised that if you wish to access the a content element via the window during unload that you  wrap it in a try/catch to prevent failure.

**Closed by JJBrychell** 2023-08-30 03:42 UTC
Labels: bug, team-Rendering, product-winui3
