### ISSUE TITLE
WinUI properties and tools missing.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#2974] opened 2020-07-22 20:01 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/1117214/winui-properties-and-tools-missing.html)._

---
<p>[regression] [worked-in:16.7.0 preview 4.0]<br>
I’ve installed a fresh copy of Preview 3, upgraded it to 4, installed both x64 and x86 versions of Windows UI Preview 2 and also installed the VSIX package (all as described on the Overview and release notes page). I can create a new C# Packaged WinUI Desktop project and run it, but if I place the cursor over any of the controls in my XAML the properties page is completely empty:</p><p><a href="https://developercommunity.visualstudio.com/storage/attachments/146930-1609451.png"> Image:146930-1609451.png</a></p>
<p>Intellisense appears while I’m editing the XAML, but the displayed fields are only those that apply to all elements (#region etc). the “Text” field, for example, doesn’t show in the dropdown when I’m editing a TextBlock, nor do any of the other TextBlock-specific properties.</p>
<p>On a related note, my toolbox is also empty when editing the XAML, and displays the “There are no useable controls in this group” message. Enabling “Show All” shows the tools for other app types, but of course they’re all greyed out.</p>
<p>Everything works fine with other apps (WPF etc), it’s only WinUI that I’m seeing this on. Tools I can live without, but properties and Intellisense are pretty important. Is this normal for this version of the preview? Like I said, it’s a completely fresh install, and I’ve followed the install instructions verbatim, so I’m at a bit of a loss now as to what to do next.</p>

---
#### Feedback Bot on 7/19/2020, 07:12 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

#### Tommy Klein [MSFT] on 7/22/2020, 04:53 AM: 

<p>Hi Dylan,</p><p>The WinUI 3 Previews are missing some tooling features that we expect to be resolved by its next release in September, WinUI 3 Preview 3.  This includes XAML Intellisense when editing .xaml markup files, XAML Hot Reload, and the XAML Live Visual Tree and Live Property Editor windows.  However, the Toolbox and Properties windows support appear to be connected to the XAML Designer, which we won't support in the near future.  I've asked some folks on the Visual Studio side to determine whether the Designer is required for Toolbox/Properties window support.</p><p>Thanks,</p><p>Tommy</p>

---
### Original Solutions
(no solutions)

**Comment by Myndale** [comment] 2020-07-24 01:48
Thanks for the explanation Tommy. I do find it strange though that "the Toolbox and Properties windows support appear to be connected to the XAML Designer", given that in other app types (WPF et al) those features also work with XAML and thus don't appear to be tied exclusively to the designer, at least not from the user's perspective?

**Comment by asklar** [comment] 2021-07-23 04:59
Duplicate of #4195

**Closed by asklar** 2021-07-23 04:59 UTC
Labels: product-winui3, team-Markup
