### ISSUE TITLE
Bug: Rounded corners are removed form the Button when you set the Style to null

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#6187] opened 2021-10-28 12:07 UTC
### Describe the bug

The rounded corners of a Button are removed when a `Button` has a `Style` (for example the `AccentButtonStyle`) and you remove it by setting the `Style` property to `null'. 

This issue is also in WinUI 2.7, see https://github.com/microsoft/microsoft-ui-xaml/issues/6156

### Steps to reproduce the bug

Create a new UWP project and add Microsoft.UI.Xaml NuGet package.

Add the following code to the MainPage.xaml

```xml
    <StackPanel HorizontalAlignment="Center"
                VerticalAlignment="Center"
                Spacing="12">
        <Button Click="Button1_Click"
                Content="Button 1" />
        <Button x:Name="button2"
                Content="Button 2"
                Style="{StaticResource AccentButtonStyle}" />
    </StackPanel>
```

```cs
public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
    }

    private void Button1_Click(object sender, RoutedEventArgs e) {
        button2.Style = null;
    }
}
```

Run the app and click `Button 1`

### Expected behavior

The `Button 2` should have rounded corners

### Screenshots

The app starts like this.

![image](https://user-images.githubusercontent.com/9335559/138712019-d29d6070-0c37-4938-a03f-7d7423fdcdcd.png)

If you click `Button 1` the rounded corners are removed from `Button 2`.

![image](https://user-images.githubusercontent.com/9335559/138712126-31547b52-11dd-4e56-931d-75a9d265e59c.png)

### NuGet package version

Microsoft.WindowsAppSDK  Version 1.0.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by kmahone** [comment] 2023-08-08 20:06
Dupe of: WinUI2.7 Rounded corners are removed form the Button when you set the Style to null #6156

**Closed by kmahone** 2023-08-08 20:06 UTC
Labels: area-Styling, area-Resources, team-Controls, product-winui3
