### ISSUE TITLE
ContentDialog has no show animation in 1.6-exp1

### ISSUE THREAD

**Issue by lolametro** [microsoft/microsoft-ui-xaml#9712] opened 2024-06-08 10:49 UTC
### Describe the bug

The `ContentDialog` has no longer a show/"fly in" animation when calling `ShowAsync` in Windows App SDK 1.6-experimental-1. This is a regression from 1.5, where there is an animation.

### Steps to reproduce the bug

1. Create new Windows App SDK 1.6-experimental-1 WinUI app with the default VS template
2. Update a button click handler with this code: 
```
private async void myButton_Click(object sender, RoutedEventArgs e)
{
    myButton.Content = "Clicked";

    var contentDialog = new ContentDialog();
    contentDialog.XamlRoot = Content.XamlRoot;
    contentDialog.Title = "Save your work?";
    contentDialog.PrimaryButtonText = "Save";
    contentDialog.SecondaryButtonText = "Don't Save";
    contentDialog.CloseButtonText = "Cancel";
    contentDialog.DefaultButton = ContentDialogButton.Primary;

    await contentDialog.ShowAsync();
}
```
3. Start the app
4. Click on the button
5. See the ContentDialog appear without any animation

### Expected behavior

See the ContentDialog appear with an animation

### Screenshots

![contentdialog-no-animation](https://github.com/microsoft/microsoft-ui-xaml/assets/13728127/2c498fa6-aa6a-42f8-9994-c3cd26b5509e)

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 1: 1.6.240531000-experimental1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Note: the exit animation still works.

**Comment by lolametro** [comment] 2024-06-08 10:54
The "workaround" mentioned in #8476 does not work either (`contentDialog.Style = Application.Current.Resources["DefaultContentDialogStyle"] as Style;`). But it was also not necessary in Windows App SDK 1.5.

**Comment by codendone** [comment] 2024-06-17 22:04
Closing as duplicate of #8476.

**Closed by codendone** 2024-06-17 22:04 UTC
Labels: bug, area-Dialogs, team-Controls
