### ISSUE TITLE
Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.BackgroundSource'

### ISSUE THREAD

**Issue by yingcai169** [microsoft/microsoft-ui-xaml#5814] opened 2021-09-01 03:02 UTC
**Describe the bug**
An error occurred after updating to WinUI2.6.x (including 2.6.0, 2.6.1 and 2.6.2) :
Message = "Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.BackgroundSource'. [Line: 978 Position: 73]"

Bug if use Microsoft.UI.Xaml prerelease version(Tried 2.6.0-prerelease.210405001, 2.6.1-prerelease.210709001 and  2.7.0-prerelease.210816001), app can startup successfully.

**Steps to reproduce the bug**
1. Upgrade Microsoft.UI.Xaml package from 2.1.190606001 to 2.6.x (also tried 2.6.0, 2.6.1 and 2.6.2).
2. Click 'Start debugging' button in VisualStudio2019 to start app.

**Expected behavior**
App can startup successfully.

**Screenshots**
![123](https://user-images.githubusercontent.com/89888869/131603516-baf05ee7-40b7-4d17-a312-95968d13776e.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]
[Microsoft.UI.Xaml 2.6.1]
[Microsoft.UI.Xaml 2.6.2]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |Yes   |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by jevansaks** [comment] 2021-09-07 22:22
Sorry, this isn't familiar to me.

**Comment by StephenLPeters** [comment] 2021-09-13 23:55
@yingcai169 just to double check, this is a UWP application right? not a XamlIslands application?

**Comment by yingcai169** [comment] 2021-09-14 00:40
> @yingcai169 just to double check, this is a UWP application right? not a XamlIslands application?

Yes, this is a UWP application.

**Comment by TheWebartist** [comment] 2023-03-02 15:08
Hi.
For some precisions, I can reproduce the issue from upgrade from 2.5.X to 2.8.2.
The issue is only reproduced on Xbox, not on Windows 11.
`Failed to assign to property 'Microsoft.UI.Xaml.Media.AcrylicBrush.BackgroundSource'. [Line: 1133 Position: 50]`

You can see my SDK declarations below :
- Min target SDK : 1903 (10.0.18362)
- Target SDK : 2004 (10.0.19041).

Have you any update on this issue ?

**Closed** 2023-10-20 07:09 UTC
Labels: area-Materials, area-NugetPackage, team-Controls, closed-Won'tFix

**Comment by DmitriyKomin** [comment] 2023-10-26 03:45
Just wanted to add context for closure - unfortunately we are unable to investigate most WinUI2-only issues due to the current focus on WinUI3 (more on the policy [here](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/contribution_handling.md#winui-2)).
