### ISSUE TITLE
Winui3 packaged app not available for assigned access (kiosk mode)

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9828] opened 2024-07-17 17:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Winui3-packaged-app-not-available-for-as/10632665)._

---
[severity:I'm unable to use this version]
With Microsoft’s constant recommendation to upgrade from UWP to WinUI3 this is a huge oversight. What is the official path forward here? It is not an option to unpackage for shell launcher. 

I need to be able to set a packaged WinUI 3 app as the app for assigned access. 

---
#### Feedback Bot on 4/6/2024, 10:18 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by codendone** [comment] 2024-07-18 16:47
Closing as duplicate of microsoft/WindowsAppSDK#3642.

**Closed by codendone** 2024-07-18 16:47 UTC
Labels: needs-triage
