### ISSUE TITLE
Font color not reverting after hover over button from 2.6.0 onwards (UWP)

### ISSUE THREAD

**Issue by matthewyoungias** [microsoft/microsoft-ui-xaml#6375] opened 2021-11-24 10:29 UTC
When using a button with a dark background and a white font colour, hovering inverts the font colour to black (and the background to grey). From 2.6.0 onwards, the background colour reverts when hover ceases, but the font colour does not (it stays black).

Button:

x:Name="Administration"
HeightRequest="60"
WidthRequest="300"
CornerRadius="30"
Grid.Row="7"
Text="Administration"
VerticalOptions="Center"
                HorizontalOptions="Center"
                FontSize="Medium"
                TextColor="White"
                Clicked="AdministrationClicked">
                Button.Background
                LinearGradientBrush EndPoint="0,1">
                    GradientStop Color="#90278E" Offset="0.1" />
                    GradientStop Color="#353254" Offset="1.0" />
                LinearGradientBrush>
                Button.Background>
            Button>
Before hover:
![before hover](https://user-images.githubusercontent.com/35612135/143221426-8010e456-8c1e-43e7-834a-0c80357b3cc4.PNG)

During hover:
![during hover](https://user-images.githubusercontent.com/35612135/143221422-00678040-2f22-42cb-9f99-7b505c818d14.PNG)

After hover:
![after hover](https://user-images.githubusercontent.com/35612135/143221425-6a86f0d2-e5d3-4dac-aa26-62787be24552.PNG)

**Comment by kmgallahan** [comment] 2021-11-24 15:09
Likely dupe of #5717

**Closed** 2022-02-16 22:42 UTC
Labels: duplicate

**Comment by matthewyoungias** [comment] 2022-06-09 13:12
Hi - is there a timeline on when a fix for this is likely to be available please?
