### ISSUE TITLE
`ListView` is blinking when moving items up or down

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#7923] opened 2022-11-14 15:01 UTC
### Describe the bug

`ListView` is blinking when moving items up or down in its source collection.

### Steps to reproduce the bug

1. Add a `ListView` control to the app
2. Bind it to an `ObservableCollection<string>` filled with some random strings
3. Add a button to call `ObservableCollection<T>.Move(int oldIndex, int newIndex)` on the source collection
4. Run the app and press the button.

`ListView` is blinking when moving the items from the source `ObservableCollection<string>`.

### Expected behavior

`ListView` is not blinking and displaying the expected move animation(s).

### Screenshots

![list view blinking](https://user-images.githubusercontent.com/20152272/201692210-b9ab8199-e09a-4136-bc12-2a2dc59e6e5c.gif)

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

### Additional context
Adding, inserting or removing items is working fine.

One way to work around the issue is to replace the calls to `ObservableCollection.Move()` by `ObservableCollection.RemoveAt()` + `ObservableCollection.Insert()` which is not very convenient.

Repro app: [MoveUpDown.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10004140/MoveUpDown.zip)

**Comment by kmgallahan** [comment] 2022-11-14 15:33
Dupe of #1503

**Closed** 2023-08-04 12:06 UTC
Labels: bug, area-Lists, area-Binding, no-issue-activity
