### ISSUE TITLE
Navigation view top padding when extending view into titlebar

### ISSUE THREAD

**Issue by knightmeister** [microsoft/microsoft-ui-xaml#1003] opened 2019-07-07 01:21 UTC
**Describe the bug**
The bug is present in the nuget package Microsoft.UI.Xaml 2.1.190606001 but not in the 1903 navigation view.

Using the nuget NavigationView there is a top padding (the height of the titlebar, approx 32px) added to the top of the navigation view.

**Steps to reproduce the bug**
See https://github.com/knightmeister/NavigationViewPaddingIssue for a reproduction. You can quickly switch this back to 1903 behaviour by changing mux:Navigation* to Navigation*.

The view must be extended into the titlebar using 

            var coreTitlebar = CoreApplication.GetCurrentView().TitleBar;
            coreTitlebar.ExtendViewIntoTitleBar = true;

**Expected behavior**
Expected the same behaviour as seen in stock 1903. See the following screenshot:
![image](https://user-images.githubusercontent.com/1528425/60762649-cd403d80-a0a8-11e9-9cac-9210d31173ef.png)

**Screenshots**
Observed behaviour:
![image](https://user-images.githubusercontent.com/1528425/60762651-d6310f00-a0a8-11e9-9664-62b1f1857f7f.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001

**Version & form factor**
Desktop 1903

**Comment by YuliKl** [comment] 2019-07-08 20:12
This is a duplicate of #47

**Closed by YuliKl** 2019-07-08 20:12 UTC
Labels: area-NavigationView, duplicate

**Comment by knightmeister** [comment] 2019-07-09 03:33
> This is a duplicate of #47

I'm not sure that it is, which is why I raised it. I am seeing the top padding in the NavigationView pane in 1903 (without using MUX) and the grid titlebar aligns properly. Switching to MUX the padding remains in the pane but also extends into the titlebar area.

You guys are the experts though so I'm happy to be wrong :)
