### ISSUE TITLE
Regression: App crash when upgrading from 1.0.3 to 1.1.3

### ISSUE THREAD

**Issue by DierkDroth** [microsoft/microsoft-ui-xaml#7529] opened 2022-07-22 09:34 UTC
### Describe the bug

Please see attached repo - which is a cut down version of my 'real world' app (you may need to apply the password 'unusual' when deploying from the temporary certificate):
- click and 'grab' the (very simplistic) grid splitter in the middle of the window
- drag it to the left -> you'll get a crash

Note: 
- you won't get the crash if you reduced the # of items on the listview so the scrollbar would not show
- please inspect the Unusual.Windows.csproj file and search for '!!!': replacing 'Microsoft.WindowsAppSdk 1.1.3' by '1.0.3' fixes the issue
- this is Windows 11 and VS 2022 with latest updates

[Unusual.zip](https://github.com/microsoft/WindowsAppSDK/files/9166551/Unusual.zip)

### Steps to reproduce the bug

Above

### NuGet package version

1.1.3

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

**Comment by DierkDroth** [comment] 2022-08-06 09:51
@btueffers, to who it may concern

I reported this issue > 2 weeks back. I would believe that a clear regression which results in an app crash would be of interest to the stakeholders of WindowsAppSdk/XAML. Unfortunately, the issue did not even make it through triage yet.

I would appreciate getting feedback on how Microsoft liked to handle this issue as it impacts the reliability of products based on WindowsAppSdk/XAML.

Thanks in advance

**Comment by gabbybilka** [comment] 2022-08-08 21:44
Thanks for the comment and @btueffers for bumping it. This looks like a dupe of #7230 and others, the fix will be in an upcoming servicing release for 1.1.

**Comment by DierkDroth** [comment] 2022-08-09 03:26
@gabbybilka @btueffers 

Excellent! Thanks for taking care. Much appreciated.

**Comment by MrDeej** [comment] 2022-08-11 09:00
@gabbybilka maybe this issue is related to this: https://github.com/microsoft/microsoft-ui-xaml/issues/7564
?

Please solve this, the app crash is a bad user experience, it should at least be able to catch the exceptions.

And also, can you please make it so that unhandled exception in async voids does not crash the app? It is so much clutter in our code now because we have to try catch everything. Please make the App.UnhandledException also include async void

**Comment by DierkDroth** [comment] 2022-08-16 17:06
@gabbybilka excellent! Thanks for letting us know...

**Comment by krschau** [comment] 2022-08-17 13:09
@DierkDroth and others... we're still investigating this, and it looks like more than was fixed in 1.1.4. The crash is coming from the garbage collector not handling the Page correctly. We'll update when we have a fix.

**Comment by DierkDroth** [comment] 2022-08-17 13:17
@krschau thanks for letting us know. Odd, that there still are issues ... :-(

Looking forward the final fix.

**Closed** 2023-08-03 22:52 UTC
Labels: bug, area-Lists, team-Rendering, product-winui3, needs-review 👀, v1.1.0, transfer-repo, Crash, no-issue-activity
