### ISSUE TITLE
ProgressRing does not jump backward to a lower value when progress decreases

### ISSUE THREAD

**Issue by MarissaMatt** [microsoft/microsoft-ui-xaml#3562] opened 2020-11-05 22:19 UTC
**Describe the bug**
When the ProgressRing needs to reduce the amount of progress made, the ring does not move backwards it only moves forwards. 

**Steps to reproduce the bug**

1. Set ProgressRing to a value of 60. 
2. Set the value to 50. 
3. ProgressRing completely fills in and animates forward to the value of 50. 

**Expected behavior**
ProgressRing will jump back to the value of 50. 

**Version Info**
WinUI 2.5

NuGet package version: 
Microsoft.UI.Xaml v2.5.0-prerelease.201027002

**Comment by chingucoding** [comment] 2020-11-05 22:21
I think this is a duplicate of #3173, @MarissaMatt can you confirm?

**Comment by MarissaMatt** [comment] 2020-11-05 22:25
You're correct! @ranjeshj could we assign someone to the issue that @chingucoding mentioned above? I'll close this one after the other bug is assigned. Good catch @chingucoding!

**Comment by StephenLPeters** [comment] 2020-11-06 00:06
@chingucoding I saw you said you would like to look into the duplicate issue. Did you run into an issue with AVP that prevented the negative playback rate from working?

**Comment by chingucoding** [comment] 2020-11-06 08:09
@StephenLPeters The issue is that the animation does in fact not play in reverse. When setting the playback rate to -1, instead of animating to that value, the progressring immediately jumped to that value. It would probably require some digging into the animation to figure out why a negative playback rate does not work as expected.

**Comment by ranjeshj** [comment] 2020-11-06 18:47
> @StephenLPeters The issue is that the animation does in fact not play in reverse. When setting the playback rate to -1, instead of animating to that value, the progressring immediately jumped to that value. It would probably require some digging into the animation to figure out why a negative playback rate does not work as expected.
> 
> Edit: Created a PR to fix the behavior as best as we/I can. Animating backwards doesn't work, it jumps to the value, however that is far better than the current behavior.

Jump when going backwards is what the spec calls for.

**Comment by chingucoding** [comment] 2020-11-06 18:53
> Jump when going backwards is what the spec calls for.

Oh I did not know that. In that case, I updated the PR description to close both this and #3173, I am sorry about the confusion and delay caused.

**Closed** 2020-11-09 16:20 UTC
Labels: area-Progress, duplicate, needs-author-feedback, team-Controls, working on it
