### ISSUE TITLE
OverlappedPresenter.IsMaximizable should disable extended title bar double clicking

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/microsoft-ui-xaml#8846] opened 2023-09-03 03:51 UTC
### Describe the bug

Currently, `OverlappedPresenter.IsMaximizable` would disable the maximize button, but it doesn't disable extended title bar (`AppWindowTitleBar.ExtendsContentIntoTitleBar`) double-clicking to maximize, which would result in the window hiding the taskbar.

### Steps to reproduce the bug

Add this code, double click the window title bar and observe the window being maximized, hiding the taskbar.
```cs
// Initialize _appWindow.

// Enable extended title bar.
_appWindow.TitleBar.ExtendsContentIntoTitleBar = true;

// Set maximizable to false
OverlappedPresenter presenter = _appWindow.Presenter as OverlappedPresenter;
presenter.IsMaximizable = false;
```

### Expected behavior

The window shouldn't maximize when the user double clicks the title bar and `IsMaximizable` is `false`.

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Unpackaged

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022-preview

**Comment by bpulliam** [comment] 2023-09-21 19:07
Duplicate of #8666

**Closed by bpulliam** 2023-09-21 19:07 UTC
Labels: area-AppWindow, team-CompInput
