### ISSUE TITLE
Faulting Module : Microsoft.UI.Xaml.DLL - Win32 WinUI 3 App not loading

### ISSUE THREAD

**Issue by OceanCyanTech** [microsoft/microsoft-ui-xaml#7163] opened 2022-05-29 13:25 UTC
### Describe the bug

When I'm trying to run my WinUI 3 app, I get this error in Event Viewer:

Log Name: Application
Source: Application Error
Date: 29-05-2022 17:30:40
Event ID: 1000
Task Category: Application Crashing Events
Level: Error
Keywords:
User:
Computer:
Description:
Faulting application name: CompInfo.exe, version: 1.0.0.0, time stamp: 0x62571150
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2204, time stamp: 0xe15d9c14
Exception code: 0xc000027b
Fault offset: 0x0023bac9
Faulting process id: 0x0x59D8
Faulting application start time: 0x0x1D87353B61B4DB3
Faulting application path: C:\Program Files (x86)\CompInfo\CompInfo.exe
Faulting module path: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1-preview3_1000.485.2229.0_x86_8wekyb3d8bbwe\Microsoft.ui.xaml.dll
Report Id: 0f4e4cd6-ed23-4b81-bf6d-7aaade61fcda
Faulting package full name:
Faulting package-relative application ID:
Event Xml:
<Event xmlns="[http://schemas.microsoft.com/win/2004/08/events/event">](http://schemas.microsoft.com/win/2004/08/events/event);
<System>
<Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" />
<EventID>1000</EventID>
<Version>0</Version>
<Level>2</Level>
<Task>100</Task>
<Opcode>0</Opcode>
<Keywords>0x8000000000000000</Keywords>
<TimeCreated SystemTime="2022-05-29T12:00:40.7854474Z" />
<EventRecordID>6885</EventRecordID>
<Correlation />
<Execution ProcessID="19768" ThreadID="24048" />
<Channel>Application</Channel>
<Computer>Lenovo_laptop</Computer>
<Security UserID="S-1-5-21-371826321-386045141-2969802394-1001" />
</System>
<EventData>
<Data Name="AppName">CompInfo.exe</Data>
<Data Name="AppVersion">1.0.0.0</Data>
<Data Name="AppTimeStamp">62571150</Data>
<Data Name="ModuleName">Microsoft.ui.xaml.dll</Data>
<Data Name="ModuleVersion">3.0.0.2204</Data>
<Data Name="ModuleTimeStamp">e15d9c14</Data>
<Data Name="ExceptionCode">c000027b</Data>
<Data Name="FaultingOffset">0023bac9</Data>
<Data Name="ProcessId">0x59d8</Data>
<Data Name="ProcessCreationTime">0x1d87353b61b4db3</Data>
<Data Name="AppPath">C:\Program Files (x86)\CompInfo\CompInfo.exe</Data>
<Data Name="ModulePath">C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.1-preview3_1000.485.2229.0_x86_8wekyb3d8bbwe\Microsoft.ui.xaml.dll</Data>
<Data Name="IntegratorReportId">0f4e4cd6-ed23-4b81-bf6d-7aaade61fcda</Data>
<Data Name="PackageFullName">
</Data>
<Data Name="PackageRelativeAppId">
</Data>
</EventData>
</Event>

### Steps to reproduce the bug

1. Create a WinUI 3 app with Windows App SDK Runtime 1.0.3
2. Build it as Non-Packaged
3. Use Inno Setup to create a setup.exe
4. Run it on a computer which has Windows App SDK Runtime 1.0.3 installed
5. App doesn't open
6. Open Event Viewer and find issue under Windows Logs> Application

### Expected behavior

App runs smoothly

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

**Comment by marb2000** [comment] 2022-06-20 18:29
Did you install the Windows App SDK runtime on your machine? When your app is unpackaged you need it:

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/deploy-unpackaged-apps#deploy-windows-app-sdk-runtime

**Comment by lukedukeus** [comment] 2022-07-14 02:40
Im experiencing this too, @OceanCyanTech did you ever get it working?
```
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2206, time stamp: 0xfec042e2
Exception code: 0xc000027b
Fault offset: 0x000000000033f2d8
```

**Comment by dannyr-git** [comment] 2023-03-13 20:32
I am having this same problem.   My unpackaged app only runs on my machine.  I've tested it with friends' Windows 10 machines and my wife's Windows 11 machine.  All errors look like this :

```
Faulting application name: wingman.exe, version: 1.0.0.0, time stamp: 0x63c9df9f
Faulting module name: Microsoft.ui.xaml.dll, version: 3.0.0.2302, time stamp: 0x93c3ada5
Exception code: 0xc000027b
Fault offset: 0x00000000007cd8bc
Faulting process id: 0x0x38C
Faulting application start time: 0x0x1D955C8A6F93000
Faulting application path: d:\Store\net7.0-windows10.0.19041.0\wingman.exe
Faulting module path: d:\Store\net7.0-windows10.0.19041.0\Microsoft.ui.xaml.dll
Report Id: a9acd5cd-c47b-4fbc-a63c-5b51f02d421e
Faulting package full name: 
Faulting package-relative application ID: 
```

I am compiling with this :
```
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <WindowsPackageType>None</WindowsPackageType>
```
    
I've personally overseen that every machine installs :
```
.Net7 (obviously)
VCRedist
and 
https://aka.ms/windowsappsdk/1.2/1.2.230217.4/windowsappruntimeinstall-x64.exe
https://aka.ms/windowsappsdk/1.2/1.2.230217.4/windowsappruntimeinstall-x86.exe


I have no idea how to triage what is going on here.  I did notice when you install the WindowsAppRuntime, you get a Microsoft.UI.Xaml.DLL that shows :
v2.8.2207.29001 , that is 6MB 

But when I compile with <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>, the same dll in the folder is 
v3.0.0.2302 (3.0.0-zmain.2302) and is 14.1MB
```

**Comment by bogdan-patraucean** [comment] 2023-07-05 20:47
This issue is happening for a packaged app installed from the Store as well.

**Comment by jhert0** [comment] 2023-10-27 21:44
I have a user who has experienced this error multiple times. Our app is packaged.

**Comment by AkazaRenn** [comment] 2023-11-18 20:48
Acknowledged but never fixed, I see why people don't develop for Microsoft anymore.

**Comment by CodeFontana** [comment] 2024-02-25 07:14
I'm new to WinUI3, just trying to get off the ground.  I have prior WPF experience, so it's not like I'm totally lost.

I'm attempting to build a traditional desktop application, having nothing to do with the Windows Store.  I've eliminated the launch profile for the 'packaged' version of the app, along with the 'Assets' folder, and the Package.appxmanifest, which appeared related only to the Packaged/Store version.

Additionally, I've added these three setting to my .csproj file:
<EnableMsixTooling>false</EnableMsixTooling>
<WindowsPackageType>None</WindowsPackageType>
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>

Running in Visual Studio 2022 works without an issue.
Publishing to a folder has landed me on this thread with a crash:

Faulting application name: WinUIDesktop.exe, version: 1.0.0.0, time stamp: 0x65ab0000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.4.0, time stamp: 0x343afd70
Exception code: 0xc000027b
Fault offset: 0x00000000003b9584
Faulting process id: 0x0x2514

Seems if I switch EnableMsixTooling back to 'true', everything works.

I didn't want to look into MAUI, as I don't need cross-platform.
Was looking into WinUI 3 due to the component gallery, would save me a lot of time vs plain old WPF.

With leaving EnableMsixTooling set to true, I'm continuing, but this already feels 'fragile' out of the box.  I would highly recommend a project template for starting an 'Unpackaged' application, in addition to it not crashing with the published version.  You might also consider rebranding 'unpackaged' as 'Traditional Desktop' and maybe 'Packaged' as 'Windows Store', if that's appropriate.

**Comment by CodeFontana** [comment] 2024-02-25 07:35
Coincidentally, 20 mins later, while browsing the WinUI 3 Gallery app, it also crashed on the same Microsoft.ui.xaml.dll:

```
Faulting application name: WinUIGallery.exe, version: 2.2.0.0, time stamp: 0x655e0000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.4.0, time stamp: 0xd8e270fd
Exception code: 0xc000027b
Fault offset: 0x00000000003ba2f4
```

I was searching icons at the time.

**Comment by CodeFontana** [comment] 2024-02-28 06:21
> > Seems if I switch EnableMsixTooling back to 'true', everything works.
> 
> Thanks @CodeFontana! I also got this in the event log after publishing the non package project generated by the "Blank App, Packaged with Windows Application Packaging Project" template.
> 
> This is supposed to work without that right?

I'm in the same boat-- I would believe you should be able to create a WinUI 3 app independently from MSIX and the Windows Store, but I can't say this for sure, as I'm new to this project type myself.

Seems WinUI project templates and settings need an overhaul.  Disappointing it's so confusing/buggy out of the box!

**Comment by sigmarsson** [comment] 2024-03-15 18:03
<img width="623" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/43340959/0e54929a-952b-4120-9930-1f957b455c67">

**Comment by ENGiDEERS** [comment] 2024-04-08 18:26
I have the same problem. I tried the same thing and couldn't find a solution.  I hope this will be solved soon.

**Comment by sigmarsson** [comment] 2024-04-08 18:43
@ENGiDEERS https://stackoverflow.com/questions/78180962/faulting-module-name-microsoft-ui-xaml-dll

**Comment by book1625** [comment] 2024-05-23 07:13
Any update ??

**Comment by arthur28197** [comment] 2024-05-24 08:40
Hi,
I have build a packaged self-contain WinUI3 with the following setting added into the csproj file following instruction from https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps and https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-packaging-dot-net. 

`    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    ...
 <Target Name="_RemoveFrameworkReferences" BeforeTargets="_ConvertItems;_CalculateInputsForGenerateCurrentProjectAppxManifest">
<ItemGroup>
<FrameworkSdkReference Remove="@(FrameworkSdkReference)" Condition="$([System.String]::Copy('%(FrameworkSdkReference.SDKName)').StartsWith('Microsoft.WindowsAppRuntime.'))" />
</ItemGroup>
</Target>
`

The application can run in VS with no problems. However, the published MSIX package application can not run and throw the following error in event reviewer. Thanks.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/155520918/256af029-94c0-4719-9526-7a59fbe25eb2)

**Comment by RobertK66** [comment] 2024-06-03 13:04
Pls. all be careful to state 'I have the same problem here' with this "c000027b" Exception!

FYI:  https://learn.microsoft.com/en-us/shows/inside/c000027b

IMHO this error is happening deep in the guts of Win UI XAML code. Unfortunately it is not much of a help when it happens:

> ... If the exception is not handled by the caller, the stowed exception is thrown fatally. Because the throwing is deferred, the current context of the associated dump has little value. ...


My own instance of this problem was simply caused by my 'stupidly misusing' of a Component in my XAML while I did not fully understand this component at that time. My symptoms where as described here 

> the application can run in VS with no problems. However, the published MSIX package application can not run and throw the following error in event reviewer ....

[see here for details](https://github.com/CommunityToolkit/Windows/issues/191#issuecomment-1698616253) Providing a corrected version of my own XAML solved it.

That said, I am hoping that future versions of WinUI3 do improve the developer experience in this area.

**Comment by Strypper** [comment] 2024-06-05 04:12
> ere as describe

Unfortunately I stepped into these 2 error 
1. Windows 10 : Faulting application name: mauisland.exe, version: 1.0.0.0, time stamp: 0x65a80000
Faulting module name: KERNELBASE.dll, version: 10.0.19041.4355, time stamp: 0xd7762934
2. Windows 11 :Faulting application name: mauisland.exe, version: 2.0.0.0, time stamp: 0x661f0000
Faulting module name: Microsoft.ui.xaml.dll, version: 3.1.5.0, time stamp: 0x7fd76c03

My problem is the project launch in release mode just fine both Debug and Release run the like charm, but when deployed to MSIX it crash on start which make me really frustrated to located where the issue really is

**Comment by malciin** [comment] 2024-07-10 07:29
I have the same issue with the same exception code.

It's easily reproducible on my machine when I build the MSIX package with both `/p:PublishSelfContained=true` `/p:WindowsAppSDKSelfContained=true`. Our crucial requirement is for the app to run self-contained on an offline machine - only setting `/p:PublishSelfContained=true` wont allow us to install & run app on offline machine because of:

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/23403545/d3475ac3-2cc9-4df3-bf53-41e7ac90617c)

**Comment by naoki-yamamoto-ymh** [comment] 2024-08-27 01:37
I have the same problem. Unfortunately, this problem only occurs in some environments. Is this issue still active?

**Comment by SanskaarPatni** [comment] 2024-09-19 11:30
I am facing the same issue. I created a blank app, packaged (winui 3 in Desktop)
![image](https://github.com/user-attachments/assets/751c4203-6076-4e75-a412-0403de109d3c)

The "Debug" configuration deploys fine, and app does not crash on launching.

Whereas the "Release" configuration deploys and the app crashes when launched from Start menu.

![image](https://github.com/user-attachments/assets/1f3d9d30-9feb-4351-abe3-389bf2938991)

**Comment by jansapp** [comment] 2024-09-23 07:36
same he
![Unbenannt](https://github.com/user-attachments/assets/e86b0678-5c82-4919-b544-907a3d4030f5)

**Comment by pratikone** [comment] 2024-09-25 23:57
Thank you all for sharing your experiences with these failures. Your input is incredibly valuable in identifying and resolving these issues. After investigating multiple issues discussed in this thread, I’ve compiled a list of potential causes and solutions for the mux.dll crash failures. It addresses some of concerns. We need more data for better root cause analysis of crashes. 
 
 Investigation Results 
 1. Publishing Self-Contained Unpackaged App to a Folder Results in a Crash 
 Issue: The “Trim unused code” option is enabled by default in publish settings, leading to certain WinRT parts being incorrectly trimmed out. This causes a crash when running the build. 
 Solution: A fix is underway. More details can be found here. In the meantime, you can disable the “Trim unused code” option to prevent the crash. 
 
 
 2. EnableMSIXTooling=false Results in a Crash in Self-Contained Unpackaged App’s Launch 
 Issue: The EnableMsixTooling property must be set to true even for self-contained unpackaged apps, as it includes essential resource loading logic. 
 Solution: We are working on improving the default settings and providing clearer indications of required build properties. 
 
 
 3. Publishing Packaged App to a Folder Results and launching the published binary results in a Crash 
 Issue: Publishing a packaged app to a folder is not a valid configuration. This option is only applicable to unpackaged apps and can cause crashes. 
 Solution: Use Project -> Publish -> Create App Packages to create an MSIX package for packaged apps. We are working on disabling the folder publish option for packaged apps. 
 
 4. Published Self-Contained MSIX Installs Correctly but Crashes on Launch on Different Machines 
 Issue: This issue is challenging to reproduce. The crash stack is not helpful without symbols, and the likely cause is missing runtimes on the target machines. 
 Solution: Ensure all necessary dependencies (e.g., Universal CRT, .NET runtime) are installed. 

  

 

Debugging Crashes 
 With WinUI 3 being source available and symbols available, you can get meaningful stack traces from crashes. 
 First ensure you have the right setup for debugging. 

  

WinDBG: Add the Microsoft symbol server to the default symbol path. Launch the app and let it crash to fetch symbols and display a meaningful stack trace. 
 Symbol Path Setup 
 Visual Studio: Add the Microsoft symbol server in Options -> Debugging -> Symbols. Launch the app from Visual Studio, ensuring the debugging mode is set to Native, Mixed, or Auto. 
 Mixed Mode Debugging 
 Once you have a detailed stack trace, please create a new issue in the microsoft-ui-xaml repo and share your configuration and stack trace. This will help us address these problems more efficiently. 

  

Few debugging techniques :  
 1. Investigating contents of stowed exception. This resource can be useful. https://learn.microsoft.com/en-us/shows/inside/c000027b.Windbg provides a useful !pde.dse command. 

  

2.  Set breakpoint on Microsoft.UI.Xaml!OnFailureEncountered. 

  

3. Subscribing to Application.UnhandledException Event https://learn.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.application.unhandledexception?view=windows-app-sdk-1.6 

  

4. See crash debugging hands by Scott Jones here : https://www.youtube.com/watch?v=uFgGhNGlPm4&t=1015s 

  

 

If you encounter a new failure, please create a new thread instead of adding to this one. This will help us track and communicate more effectively. I will be closing this issue now. 
 
 Thank you for your cooperation and understanding! 

@michael-hawker for reference.

**Closed by pratikone** 2024-09-25 23:57 UTC
Labels: bug, team-Markup, product-winui3, Crash

**Comment by CodeFontana** [comment] 2024-09-26 05:12
By closing this issue, I'm assuming you're saying WinUI is not a viable project type for traditional desktop needs.  To be honest, my team abandoned the idea of using WinUI3 for our needs, based on the idea it was broken out of the box.  This is feedback you need to hear when arbitrarily closing an issue based on a summary, and no concrete solutions.  I'd rather you retire the technology than lie to us.

**Comment by freemstr** [comment] 2024-09-26 14:54
I can repro this issue in .NET 8 MAUI project as well with publish trimmed turned off, just FYI

**Comment by Scottj1s** [comment] 2024-09-26 19:27
@CodeFontana our intent is not to ignore anyone, but to actively manage our backlog.  This issue dates back a couple years to Windows App SDK 1.0.3, and many variations of crashes in Microsoft.UI.Xaml.DLL have been added to it.  We've resolved a few of these, and are tracking others separately.  We welcome new issues opened against the latest version of Windows App SDK, with clear repro steps.

**Comment by Scottj1s** [comment] 2024-09-26 19:27
@freemstr please enter a new issue for your MAUI-related crash.

**Comment by CodeFontana** [comment] 2024-09-27 04:23
> @CodeFontana our intent is not to ignore anyone, but to actively manage our backlog. This issue dates back a couple years to Windows App SDK 1.0.3, and many variations of crashes in Microsoft.UI.Xaml.DLL have been added to it. We've resolved a few of these, and are tracking others separately. We welcome new issues opened against the latest version of Windows App SDK, with clear repro steps.

Yeah, you're right.  It's just frustrating because it takes so long to address what I would call "getting started" issues.  Unfortunately, my team is not using this technology, and now it would be an uphill battle to try and suggest again.  There's a basic expectation this stuff should work gracefully out of the box-- I mean we really didn't have to go far to immediately bump into problems.  And I still feel there should be more obvious templating for "Traditional Desktop" vs "Windows Store" applications.  Sorry if my feedback was bit rough, might just be passion and disappointment.  We want you guys to hit every mark, so us folks in the trenches can confidently and consistently recommend cohesive Microsoft tech stacks.

**Comment by mirec75** [comment] 2024-12-15 23:29
The problem with **Microsoft.UI.Xaml.dll** is not limited just to developing a new app.
See my **problem after I updated my Win11** home  office notebook **to 24H2**
and see the solution here:
[https://answers.microsoft.com/en-us/windows/forum/windows_11-wintop_update/cannot-open-explorer-after-update-to-24h2-crashes/e149b7b0-2d67-445c-807b-e25d6b87d656](https://answers.microsoft.com/en-us/windows/forum/windows_11-wintop_update/cannot-open-explorer-after-update-to-24h2-crashes/e149b7b0-2d67-445c-807b-e25d6b87d656)

**Comment by fullstackdevsalmoh** [comment] 2025-09-02 09:37
same here, ,, test small MAUI app works fine, but real app not working,, very disappointed
