### ISSUE TITLE
New Expander control causes LayoutCycle exception in winui 2.6 preview

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#4255] opened 2021-02-19 08:49 UTC
**Describe the bug**

Testing the new Expander control and it causes LayoutCycle exceptions if a ListView is added to it.

**Steps to reproduce the bug**

1. Use the repro project
2. Scroll up and down with a touchpad
3. After a few second it will crash with a LayoutCycle exception.

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml.2.6.0-prerelease.210217002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

[ExpanderLayoutCycle.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6008674/ExpanderLayoutCycle.zip)

**Comment by StephenLPeters** [comment] 2021-02-20 00:11
@ranjeshj FYI

**Comment by ranjeshj** [comment] 2021-02-20 00:36
@lhak I don't have a touch pad to test out right now, but it didn't repro with mouse. Few questions to help isolate the issue. Does it repo with keyboard/mouse or is it only when using touch pad ? Does removing the expander and just having the listview alone make it repro/not repro ? Expander is quite simple when it comes to layout, so I'm wondering if the issue is in ListView.

**Comment by lhak** [comment] 2021-02-22 17:46
@ranjeshj I have updated the sample so that it also triggers when the expander is opened and closed very quickly with a mouse click. Two observations I have made:

- I can only reproduce it with display scaling set to 125%
- I cannot reproduce it if I set the UseLayoutRounding property of the expander content to false

[ExpanderLayoutCycle2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6023981/ExpanderLayoutCycle2.zip)

**Comment by StephenLPeters** [comment] 2021-02-23 00:50
@gegao18 FYI

**Comment by StephenLPeters** [comment] 2021-02-23 00:51
Moving to rendering because of the display scaling component

**Comment by robloo** [comment] 2021-03-02 05:49
I just reproduced this in the MUXControlsTestApp with https://github.com/microsoft/microsoft-ui-xaml/pull/4394 applied. 

Expanders are now within a ScrollViewer on the test page since there are too many expanders to show at once. When some controls are expanded, and then the mouse scroll wheel is used, layout cycle crash occurs.

![gifexample](https://user-images.githubusercontent.com/17993847/109604198-1b614a80-7af1-11eb-8dee-2bc0828a0f36.gif)

This is definitely a show stopper.

**Closed** 2021-03-13 00:13 UTC
Labels: area-Expander, team-Controls, working on it
