### ISSUE TITLE
Unable to set environment for CoreWebView2 on WinUI3 WebView2 component

### ISSUE THREAD

**Issue by mlynch** [microsoft/microsoft-ui-xaml#7074] opened 2022-05-08 21:20 UTC
### Describe the bug

An API is missing for WinUI3's WebView2 control, making it impossible to specify additional environment options for the Web View. Specifically, `WebView.EnsureCoreWebView2Async()` takes no arguments compared to the APIs documented here: https://docs.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2environment.createasync?view=webview2-dotnet-1.0.1185.39#microsoft-web-webview2-core-corewebview2environment-createasync(system-string-system-string-microsoft-web-webview2-core-corewebview2environmentoptions)

One major side effect of this is it seems impossible to set the user data path for the web view environment which, as far as I can tell, makes WinUI3 + WebView2 impossible to use for unpackaged apps. When running unpackaged, the WebView2 does not use the default packaged application data directory the user has write access to. Instead, the path of the exe is used which, very likely, the user does not have write access to.

Under the [instructions for specifying the user data folder](https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32), this paragraph says:

> **Why you should use a custom UDF location on this platform:**
> 
> If you don't specify a custom UDF location, the default location can produce a run-time failure, if using installer technologies, because installer technologies put the app and thus the UDF in a protected area of the filesystem, where WebView2 isn't able to create the UDF, and thus UDF creation will usually fail. WebView2 will throw an error to let your host app know that the UDF can't be created at that location.
> 
> If the host app is running from a location that the user doesn't have Write access to, WebView2 isn't able to create the UDF, and you will receive a runtime error during WebView2 startup.

### Steps to reproduce the bug

Create an unpackaged app using Windows App SDK 1.03 and WinUI 3. Add a WebView2 to your app. Notice the APIs available in differ from those required to configure the user data folder as shown here: https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/user-data-folder?tabs=win32

### Expected behavior

APIs should match and enable customizing the `Environment` used to initialize the `CoreWebView2` instance in WinUI3's `WebView2` control

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by asklar** [comment] 2022-05-11 07:10
Duplicate of #6150

**Comment by asklar** [comment] 2022-05-11 07:10
@krschau @codendone fyi

**Closed by asklar** 2022-05-11 07:10 UTC
Labels: bug, needs-triage
