### ISSUE TITLE
TextBox and AutoSuggest use deprecated icon codes

### ISSUE THREAD

**Issue by Jay-o-Way** [microsoft/microsoft-ui-xaml#7850] opened 2022-10-05 12:47 UTC
### Description

_Coming from issues in PowerToys; see https://github.com/microsoft/PowerToys/issues/18055#issuecomment-1268074593_

We have issues coming from people with Chinese UI. We used a few deprecated [1] icon codes that would display fine in western languages, but show as "garbled charaters" in Chinese. After updating the Unicode points, these were fixed in our UI. But then there are two more left-overs: the Search icon inside of an \<AutoSuggestBox> and the [X] inside of a \<TextBox>. In the first case we set `QueryIcon="Find"` and in the second case we set no icon. So my conclusion is this is a XAML/WinUI3 issue.

[1] see message at https://learn.microsoft.com/windows/apps/design/style/segoe-fluent-icons-font#icon-list

### Screenshots

**AutoSuggest:**
![Image AutoSuggest](https://user-images.githubusercontent.com/68262945/194009493-931b6420-bf41-488e-b270-a33483387ef6.png)
source: https://github.com/microsoft/PowerToys/blob/32f3e6bf70c501e4228c14763848cede2bafe956/src/settings-ui/Settings.UI/Views/PowerLauncherPage.xaml#L257-L260

**TextBox:**
![Image TextBox](https://user-images.githubusercontent.com/68262945/182609355-8a366c93-edf6-4523-8a63-a926fce1ebed.png)
source: https://github.com/microsoft/PowerToys/blob/32f3e6bf70c501e4228c14763848cede2bafe956/src/settings-ui/Settings.UI/Views/ImageResizerPage.xaml#L89-L93

### Windows version

November 2021 Update/21H2 (19044)

**Comment by bpulliam** [comment] 2022-10-19 14:47
Specifically which glyphs are you looking at?  I see 0xE11A for QueryIcon=Find and xE10A for AutoSuggest. Which values should each of these be? Moving all glyphs to the new range is a large, potentially breaking task, but if these 2 glyphs are broken, that can be a more tactical fix. There is also the possibility that the issue is in the translation of those glyphs, and the fix is in the font itself.  Thanks for pushing on this! :)

**Comment by Jay-o-Way** [comment] 2022-10-19 16:55
Hi @bpulliam. Yes, you also confirm my conclusion. These seem to have been deprecated for a while now. The site for the [Fluent Icons Font](https://learn.microsoft.com/windows/apps/design/style/segoe-fluent-icons-font#:~:text=Glyphs%20with%20prefixes%20ranging%20from%20E0%2D%20to%20E5%2D%20(e.g.%20E001%2C%20E5B1)%20are%20currently%20marked%20as%20legacy%20and%20are%20therefore%20deprecated.) shows the message I earlier referred to and also shows a list of ("safe"?) icons and their unicode and description. If you Ctrl+F for "Search" you'll find `e721` and "Cancel" gives `e711`. (or should it be "CancelMedium"? i don't know)

> Moving all glyphs to the new range is a large, potentially breaking task

Nah, it is not potentially breaking if the correct code is used. It is something that should be done, regardless of the size of the task.

> **Note**
> I also remember somebody showed that this even happens in **Windows File Explorer**, in the search box in the top right corner.

**Comment by Jay-o-Way** [comment] 2022-10-19 17:12
FYI @niels9001

**Comment by Jay-o-Way** [comment] 2022-12-02 07:09
Hi. Any update? 🙂

**Comment by Jay-o-Way** [comment] 2022-12-06 19:06
Looks like there are still different icons in different occasions that are affected. Including Windows Explorer and WinUI3 Gallery. How can Microsoft make these mistakes? Unbelievable...

Please tell me this will be fixed in a broad spectrum in a fashionable time.

**Comment by Jay-o-Way** [comment] 2023-02-28 15:46
Is this still an issue?

**Comment by Jay-o-Way** [comment] 2023-06-22 19:35
Superseded by #8375 and (should be) fixed with #8379

**Comment by kmahone** [comment] 2023-08-08 20:59
> Superseded by #8375 and (should be) fixed with #8379

Thanks. I'll close this issue.

**Closed by kmahone** 2023-08-08 20:59 UTC
Labels: team-Controls, area-Icon
