### ISSUE TITLE
WinUI 3 should include a DataGrid or TableView control

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6408] opened 2021-11-30 03:23 UTC
This is a topic that comes up pretty much every community call : )
There is a need for a platform-provided table / datagrid control. The existing WCT one is not sufficient or appropriate since that is realistically only consumable by .NET apps. C++ apps are not able to consume it, or unwilling to pay the perf hit of loading a whole CLR just for one control. See CommunityToolkit/WindowsCommunityToolkit#4391 and many other issues filed here.
The platform should include this control rather than rely on developers to roll their own.

**Comment by michael-hawker** [comment] 2021-11-30 20:45
Duplicate of #1500

**Comment by asklar** [comment] 2021-11-30 21:49
@michael-hawker please don't close. Thanks :)

**Comment by michael-hawker** [comment] 2022-02-17 20:39
@asklar @StephenLPeters @RBrid there's already an issue tracking this, why do we need to keep this one open as a duplicate?

**Closed** 2023-08-05 11:19 UTC
Labels: duplicate, team-Controls, area-DataGrid, product-winui3, no-issue-activity
