### ISSUE TITLE
Designer won't render WinUI/ProjectReunion forms

### ISSUE THREAD

**Issue by GuildOfCalamity** [microsoft/microsoft-ui-xaml#5538] opened 2021-07-20 22:32 UTC
**Describe the bug**
I have installed the WinUI/ProjectReunion/WindowsAppSDK extensions in VS2019 and followed all the steps in the tutorials but I cannot get the form to paint in the IDE. I have checked all of the settings in the options menus and my other XAML projects render the form just fine. NOTE: The app will run and compile without issue, but will not render in the IDE.

I'm using VS2019 Version 16.10.3 on Windows 10 Pro, build 19042.1110

**Steps to reproduce the bug**

1. Create blank app WinUI project.

![error1](https://user-images.githubusercontent.com/81915293/126403778-db3d2c19-5fae-4862-9c3b-2805a08df7cc.png)
![error4](https://user-images.githubusercontent.com/81915293/126403783-6d708106-5e11-49fb-a7c8-0f0fca97e0a2.png)
![error2](https://user-images.githubusercontent.com/81915293/126403790-f844f17b-ec96-4ccf-96c0-b3162b081e87.png)
![error3](https://user-images.githubusercontent.com/81915293/126403801-a6214f09-4628-4422-81ad-acdcc4eb46b1.png)

Using NuGet just makes the problem worse...
![UAP_error](https://user-images.githubusercontent.com/81915293/126404094-8a18bba4-f025-4f69-b159-20570660fdf2.png)

**Comment by StephenLPeters** [comment] 2021-07-22 23:31
@sylveon is correct, Winui3 does not currently support the VS Designer.

**Comment by asklar** [comment] 2021-07-23 04:56
Duplicate of #4195

**Closed by asklar** 2021-07-23 04:56 UTC
Labels: area-Tooling, product-winui3, team-Markup
