### ISSUE TITLE
Bug: TreeViewItem bind data

### ISSUE THREAD

**Issue by doghappy** [microsoft/microsoft-ui-xaml#337] opened 2019-02-22 14:34 UTC
**Describe the bug**

When data has child nodes, the binding value is not expected

**Steps to reproduce the bug**

```cs
public sealed partial class TestPage : Page
{
    public TestPage()
    {
        InitializeComponent();
        SampleDatas = new List<SampleData>
        {
            new SampleData { Name = "Google", IsChecked = true },
            new SampleData {
                Name = "Microsoft",
                IsChecked = true,
                Chidren = new List<SampleData>
                {
                    new SampleData { Name = ".Net", IsChecked = true },
                    new SampleData { Name = "Office", IsChecked = false },
                    new SampleData { Name = "Windows", IsChecked = true }
                }
            },
            new SampleData { Name = "Apple", IsChecked = true }
        };
    }

    List<SampleData> SampleDatas { get; }
}

class SampleData
{
    public string Name { get; set; }
    public bool IsChecked { get; set; }
    public List<SampleData> Chidren { get; set; }
}
```

```xaml
<winui:TreeView ItemsSource="{x:Bind SampleDatas}" SelectionMode="Multiple">
    <winui:TreeView.ItemTemplate>
        <DataTemplate x:DataType="local:SampleData">
            <winui:TreeViewItem ItemsSource="{x:Bind Chidren}"
                                Content="{x:Bind Name}"
                                IsExpanded="True"
                                IsSelected="{x:Bind IsChecked}"/>
        </DataTemplate>
    </winui:TreeView.ItemTemplate>
</winui:TreeView>
```

![image](https://user-images.githubusercontent.com/20038914/53249038-0a0b2980-36f2-11e9-8432-2c5b232fe193.png)

**Comment by jevansaks** [comment] 2019-02-22 17:37
@doghappy to clarify, is the issue that IsChecked is not taking effect for the treeview sub-items?

@kaiguo want to take a look?

**Comment by kaiguo** [comment] 2019-02-22 19:05
@jevansaks I believe that's the known "IsSelected" issue. TreeViewItem is inherited from ListViewItem, the underneath ListView is set to non-select mode when TreeView operates in multi-select mode, which creates some conflicts. I'll take a look.

**Comment by doghappy** [comment] 2019-02-23 12:56
> @doghappy to clarify, is the issue that IsChecked is not taking effect for the treeview sub-items?

yeah, the issue you pointed out is only one of them.

I didn't click on any node, only the last worked

**Comment by jevansaks** [comment] 2019-02-25 17:59
> I'll take a look.

Thanks, assign to yourself when you start the investigation.

**Comment by kaiguo** [comment] 2019-09-30 18:20
This has the same root cause as #125, closing as dupe.

**Closed by kaiguo** 2019-09-30 18:20 UTC
Labels: area-TreeView, bug, duplicate
