### ISSUE TITLE
SwipeControl doesn`t work in XAML Controls Gallery

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#5762] opened 2021-08-25 04:07 UTC
**Describe the bug**
In XAML Controls Gallery version 1.2.20.0 SwipeControl Example doesn`t work.
I'm trying to swipe using touchscreen. swiping in mail app working well

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | ? |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2021 Update (19043)            |   Yes   |

**Comment by Psykobal** [comment] 2021-09-08 14:17
I have the same bug in my application.
I think you can rename your issue, SwipeControl doesn't work from 2.6.0 to 2.7.0-prerelease.210827001 (not only in XAML Controls Gallery)

**Comment by StephenLPeters** [comment] 2021-09-13 22:50
Closing as duplicate of #5855

**Closed** 2021-09-13 22:50 UTC
Labels: duplicate, area-SwipeControl, needs-triage, team-Controls
