### ISSUE TITLE
PrintManager doesn't work on XAML islands

### ISSUE THREAD

**Issue by solocle** [microsoft/microsoft-ui-xaml#7150] opened 2022-05-26 10:46 UTC
### Describe the bug

Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll - Value does not fall within the expected range.

### Steps to reproduce the bug

Use the WPF_XAMLIslands_v1 sample application.

Modify WelcomePage.xaml and the code behind in the UWPApplication project:
<StackPanel HorizontalAlignment="Center" Spacing="10" Padding="20" VerticalAlignment="Center">
        <TextBlock x:Uid="WelcomeHeader" x:Name="HeaderTB" HorizontalAlignment="Center" TextWrapping="Wrap" Text="" FontSize="30" />
        <TextBlock HorizontalAlignment="Center" Margin="15" TextWrapping="Wrap" Text="😍❤💋🌹🎉😎�🐱‍👤" FontSize="16" />
        <TextBlock x:Name="WelcomeDescriptionTB" HorizontalAlignment="Center" TextWrapping="WrapWholeWords" Margin="10" Text="" FontSize="16" />
        <Button x:Name="PrintButton" Click="PrintButton_Click" Content="Kill me" />
    </StackPanel>

private PrintManager printMan = null;
        private PrintDocument printDocSource = null;

        private async void PrintButton_Click(object sender, RoutedEventArgs e)
        {
            printDocSource = new PrintDocument();
            if (printMan == null)
            {
                printMan = PrintManager.GetForCurrentView();
                printMan.PrintTaskRequested += PrintMan_PrintTaskRequested;
            }
            await PrintManager.ShowPrintUIAsync();
        }

        private void PrintMan_PrintTaskRequested(PrintManager sender, PrintTaskRequestedEventArgs args)
        {
            args.Request.CreatePrintTask("Print", PrintTaskSourceRequested);
        }

        private void PrintTaskSourceRequested(PrintTaskSourceRequestedArgs args)
        {
            args.SetSource(printDocSource.DocumentSource);
        }

### Expected behavior

Display the UWP print dialog with preview.
![image](https://user-images.githubusercontent.com/8686370/170473142-f7d34237-8960-4e65-bdc4-28718c0a2869.png)

### Screenshots

![image](https://user-images.githubusercontent.com/8686370/170472944-b0cf8bab-274f-4820-88c8-3ed3bbda3e21.png)

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H1): Build 19043

**Comment by krschau** [comment] 2022-06-15 16:58
Closing as dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/4419
Please see solution and continue any conversation over there.

**Closed by krschau** 2022-06-15 16:58 UTC
Labels: bug, duplicate
