### ISSUE TITLE
Bug: await CoreDispatcher.RunAsync does not continue.

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/microsoft-ui-xaml#3874] opened 2021-01-02 01:48 UTC
This item was identified in the discussion thread #2609. 

WinUI documentation says that the CoreDispatcher can be obtained from any UI element (https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.dependencyobject.dispatcher?view=winui-3.0-preview).

However, in a test of RunAsync the continuation did not execute. 

Steps to reproduce: Install Visual Studio Version 16.9.0 Preview 2.0 with WinUI 3 Project Templates [Preview] version 3.0.0.2011130. Download and compile the Xaml Controls Gallery branch for WinUI 3 - Desktop (i.e. with the MSIX package). In ButtonPage.xaml.cs, add the following lines to the Button_Click method after the first line (and make the method async):

        System.Diagnostics.Debug.WriteLine("Dispatching....");
        await b.Dispatcher.RunAsync( Windows.UI.Core.CoreDispatcherPriority.Normal, () => { System.Diagnostics.Debug.WriteLine("Dispatched!"); }).AsTask();
        System.Diagnostics.Debug.WriteLine("Awaited.");

Expected: when you click the button it should print "Dispatching..." and "Dispatched" and "Awaited.". 
Actual: When you click the button it prints "Dispatching..." and "Dispatched!" but not "Awaited". The continuation of the method after the "await" is not executed. Noting that the UI remains responsive, i.e. this does not seem to be a deadlock situation.

**Comment by sjb-sjb** [comment] 2021-01-03 18:22
I tested this on the master branch of the Xaml Controls Gallery, which is a UWP app, and it does give the expected behavior i.e. the output includes "Awaited.". Consequently this is not a problem with the VS 16.9 preview compiler or environment, nor is there some kind of logic error. This increases the confidence that this is a WinUI 3 bug.

**Comment by huoyaoyuan** [comment] 2021-01-04 06:55
Can you confirm this with WinUI3 UWP and desktop? This looks like a CsWinRT issue, which shouldn't repro for WinUI3 UWP.

**Comment by sjb-sjb** [comment] 2021-01-04 22:40
I have run the following variants of Xaml Controls Gallery 

(a) The WinUI 3 desktop branch with the XamlControlsGallery.Desktop.sln solution. This is WinUI 3 in a packaged desktop app. The test failed, the continuation didn't run (as indicated by "Awaited." not being printed). 

(b) The WinUI 3 desktop branch with the XamlControlsGallery.sln solution. This is a WinUI 3 UWP app. The test succeeded, the continuation ran and "Awaited." was printed. 

(c) The master branch with the XamlControlsGallery.sln solution. This is a UWP app without WinUI 3; it uses Microsoft.UI.Xaml v 2.5.0. The test succeeded, the continuation ran and "Awaited." was printed. 

This bug is hanging up my project, how can I get a fix for it ? 

Steve

P.S.  for both (b) and (c) I encountered a NuGet problem which I fixed using the method described in https://franckgaspoz.fr/en/how-to-solve-a-failure-of-nuget-restore-impossible-to-access-a-deleted-object-from-the-package-manager-of-visual-studio-2019/

**Comment by StephenLPeters** [comment] 2021-01-05 00:19
@Scottj1s and @stevenbrix another cswinrt issue?

**Comment by stevenbrix** [comment] 2021-01-05 23:46
No, this is a difference between Desktop and UWP. In Desktop apps, `CoreDispatcher` doesn't work, and you instead need to use the `DependencyObject.DispatcherQueue` property. In fact, `DependencyObject.DispatcherQueue` will work in both UWP and Desktop, so it's recommended to use that always if you can

**Comment by sjb-sjb** [comment] 2021-01-06 00:23
@stevenbrix, thanks, what you say here is consistent with @MikeHillberg’s comments in #2609.

In that case the CoreDispatcher documentation in the WinUI documentation set (linked above) is wrong and should be deleted or modified.

Can you explain how to implement an equivalent of RunAsync using the DispatcherQueue only? The equivalence is not clear to me, because CoreDispatcher.RunAsync waits for the delegate to begin executing, while DispatcherQueue.TryEnqueue returns immediately. Is it as simple as adding in a TaskCompletionSource that is completed at the start of the delegate execution, or are there some tricks or subtleties involved?

**Comment by sjb-sjb** [comment] 2021-01-06 00:57
Also, any thoughts on how to get an event similar to CoreDispatcher.AcceleratorKeyActivated, in the WinUI environment ?

**Comment by MikeHillberg** [comment] 2021-01-08 01:19
@sjb-sjb, could you explain that last part? You're expecting to get a KeyUp while the key is still down?

**Comment by sjb-sjb** [comment] 2021-01-15 03:17
No, what I meant was this: the accelerator key activated event occurs when the ALT key is pressed and then released, i.e. it occurs when the key is released. If you try to simulate this by trapping KeyDown and KeyUp, you will not succeed because if the ALT key is held down for a while then when it is released the KeyUp will not be generated. You will not be able to generate the simulated AcceleratorKeyActivated when the ALT key is released. Caveat, I am telling you this from memory of an experiment I did quite a while ago.

**Comment by marb2000** [comment] 2021-02-10 07:01
@sjb-sjb There is not plan yet for introducing an event similar to CoreDispatcher.AcceleratorKeyActivated (ideally, there should be a DispatcherQueue.AcceleratorKeyActivated). 

About this: 

> if the ALT key is held down for a while then when it is released the KeyUp will not be generated. 
I tested this and it worked as expected. When pressing the ALT key, the KeyDown event was fired, and after pressing it for several seconds, I released the button, and the KeyUp event was fired.  Was this your scenario?

**Comment by sjb-sjb** [comment] 2021-02-11 00:29
I believe that the sequence was: ALT key down, alphabetic key down, alphabetic key up, then ALT up. One of the two key-ups was not generated when there was a pause in the sequence (either after the ALT down or after the alphabetic down). It was on UWP.

**Comment by marb2000** [comment] 2021-02-20 06:51
I do recommend to you to open a feature proposal for AcceleratorKeyActivated. 

About your issue to implement ALT, perhpas you can do something like this:
```CS
myGrid.KeyDown += (sender, e) => {
     bool altDown = KeyboardInput.GetKeyStateForCurrentThread(VirtualKey.Menu).HasFlag(CoreVirtualKeyStates.Down);
     if (e.Key == VirtualKey.F4 && altDown)
    {
              // Do something
    }
};
```

**Comment by bpulliam** [comment] 2022-10-30 02:03
Closing this issue as By Design.

**Closed by bpulliam** 2022-10-30 02:03 UTC
Labels: product-winui3, appModel-win32
