### ISSUE TITLE
TextBox in a Flyout does not take focus

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/microsoft-ui-xaml#8614] opened 2023-07-07 03:59 UTC
### Describe the bug

If you add a Textbox inside a Flyout control, when the flyout opens up, the textbox will never take focus making it look like its read-only. No matter how many time you click on the textbox, you won't be able to type in it.

A workaround is to make the textbox take focus in the code-behind file, for example:
`MyTextBox.Focus(FocusState.Programmatic);`

A permanent internal fix is highly requested.

### Steps to reproduce the bug

`<CommandBar IsOpen="True">`
`	<AppBarButton Icon="Find" Label="Find">`
`		<AppBarButton.Flyout>`
`			<Flyout>`
`				<StackPanel Spacing="8">`
`					<TextBox Width="250" Header="Enter your query below" />`
`					<Button Content="Click to search" />`
`				</StackPanel>`
`			</Flyout>`
`		</AppBarButton.Flyout>`
`	</AppBarButton>`
`</CommandBar>`

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/77593544/8d8faf02-4523-48bf-9e57-2f48011b27eb)

### Expected behavior

When the flyout gets opened, the textbox should automatically take focus so it can be clicked and typed into.

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by jp-weber** [comment] 2023-07-11 19:15
Same issue in #6924 and #8094.

**Comment by ShankarBUS** [comment] 2023-11-19 06:42
Any updates on this issue?
I'm facing the same issue [here](https://github.com/ShankarBUS/WinUIAppBarButtonFlyoutRepro)

Not just TextBox but also all input controls. You can only click them. ComboBox can be clicked but elements couldn't be selected.
The flyout doesn't get focus. Tab navigation also doesn't work.

**Comment by JJBrychell** [comment] 2024-01-12 21:52
Am resolving this by design.

By default flyouts are not allowed to take focus when interacted with using a pointer device because the core use case is that the flyout is being used to take action on the element that generated the flyout, i.e. the one with focus.  If the flyout were to take focus, then context would be lost. And in many cases (such as the flyouts used for editing in a text block), when the element loses focus, it will dismiss the UI that just got focus.

You can see this in action in another bug I am working on where when the edit bar pops up after selecting text in a trich text box, if you attempt to tap the more menu button, the UI dismisses and doesn't bring up the secondary menu.  This is because the 'more' button is taking focus, the rich edit bock is losing focus and so it dismisses the editing UI.

The good news, is that you can override this behavior by adding AllowFocusOnInteraction="True" to your textbox.  This will allow the textbox to take focus and if the element that has the focus does not dismiss the UI, you can type in it.

**Closed by JJBrychell** 2024-01-12 21:52 UTC
Labels: bug, team-Controls
