### ISSUE TITLE
Teaching Tip doesn't move with the target

### ISSUE THREAD

**Issue by KodWhat** [microsoft/microsoft-ui-xaml#3050] opened 2020-08-05 18:44 UTC
**Describe the bug**
When the control targeted with a Teaching Tip moves or changes, the Teaching Tip does not follow.

To note: A window resize will replace the Teaching Tip in the right place.

This might be related to #1609, where the Teaching Tip was repositioned on window resize but not on control move.

**Steps to reproduce the bug**
Here are three ways to reproduce :
1. Have a Teaching Tip attached to a button and shown. Change the width of the button. The teaching tip will not move, overlapping with the button.

2. Have another control show/hide while the teaching tip is opened as such that it moves the targeted control. The teaching tip will not move.

3. Have a teaching tip opened at application start. Have ExtendViewIntoTitleBar set to true on the view. The teaching tip will not adapt and overlap the targeted control.

**Expected behavior**
Either the Teaching Tip should reposition itself when its targets gets transformed (position, size, ...) or the RepositionPopup method should be made public to allow for manual refresh.

**Screenshots**
![Screenshot 2020-08-05 203806](https://user-images.githubusercontent.com/1282471/89450897-9cbf4d00-d75b-11ea-9125-88c1b96db21c.jpg)
On this screenshot, the picture sidebar get shown after the teaching tip was opened, and ExtendViewIntoTitleBar is set to true.
Teaching Tip is attached to the Settings AppBarButton

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20180)              | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment] 2020-08-05 23:21
It was a conscious decision to not have the teaching tip move with a target, primarily because we didn't have a good story for what to do with the teaching tip when the target was scrolled out of the view port. In that case it was causing the tip to look as if it were pointing at a different object.  Our designers also found that a moving teaching tip was very distracting and thus the guidance is to not have tips which target components which you expect to move, or when they do to close the tip.  

Your idea of exposing a method which the consumer could use to reposition the tip is interesting.  @SavoySchuler do you have thoughts on this?

**Comment by KodWhat** [comment] 2020-08-05 23:45
Thank you for your answer.
To add more details about my use case : 
I develop a weather app where the side picture is shown when there is a forecast available (Connected to internet and City selected).
When these conditions are not met or if the window is too small, that picture is hidden.
I use the Teaching Tip as a way to indicate what's new in an update (at least for now), so I show it as soon as the app is launched.

For the method to reposition the tip, I saw that there is a RepositionPopup that is used when the window gets resized, and if that method is safe to use and exposed, that would be a good solution, and won't cause any issue with scrolling (or at least, it will be the consumer's responsibility)

**Comment by StephenLPeters** [comment] 2020-08-05 23:53
@KodWhat Could I trouble you to open a Feature Request issue?  I think the feature request and the details in this issue are different enough that we shouldn't repurpose this.

**Comment by chingucoding** [comment] 2020-08-11 21:11
Given that there is #3062, is there any benefit in keeping this issue open or can we close it?

**Comment by StephenLPeters** [comment] 2020-08-12 17:29
I think that the two are slightly different.  But I think that we could potentially close this as 'By Design'. @ranjeshj are you okay with that?

**Comment by ranjeshj** [comment] 2020-08-12 18:03
Looks like both are talking about similar issues. Lets dup this and add more details to #3062 if necessary. Thanks!

**Closed by ranjeshj** 2020-08-12 18:03 UTC
Labels: area-TeachingTip, team-Controls
