### ISSUE TITLE
Proposal: Bring native NavigationView experience to XBox

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#3455] opened 2020-10-21 06:29 UTC
Currently, XBox's `NavigationView` control has the same behaviors as the desktop. Like all the other controls, we have to customize their appearance to adapt to Xbox. Most of them are simple, but `NavigationView` is a special case.

Many behaviors and appearance of `NavigationView` seems perfect on desktop, but performs terribly on the Xbox platform. I tried to modify some of the xaml resource and behavior, but still not perfect, comparing to Android TV's hamburger menu.

For example:
1. Android TV's menu has the focus style, better than Xbox's rectangle border focus.
![image](https://user-images.githubusercontent.com/14960168/96684669-87e37480-13ae-11eb-815f-0c3de85fa9a5.png)

2. Android TV support navigates right to enter the selected page on the menu item. When the focus on the page, navigate left to open the menu.
![image](https://user-images.githubusercontent.com/14960168/96685076-312a6a80-13af-11eb-8c69-331fed47b4f8.png)

2. Android TV's menu support sub menu, like
Item A
  -- Item A1
  -- Item A2
Item B
Item C
When open the menu, it shows like above. When closed, it shows below.
Item A
Item B
Item C

**A UI/UX video on Xbox.👇👇👇**

[![NavigationView on Xbox](https://res.cloudinary.com/marcomontalbano/image/upload/v1603261903/video_to_markdown/images/youtube--aiB8vpIWjHs-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://www.youtube.com/watch?v=aiB8vpIWjHs&feature=youtu.be "NavigationView on Xbox")

**A UI/UX video on Android TV👇👇👇**
[![Navigation on Android TV](https://res.cloudinary.com/marcomontalbano/image/upload/v1603263096/video_to_markdown/images/youtube--xu7ihPv1ZEo-c05b58ac6eb4c4700831b2b3070cd403.jpg)](https://youtu.be/xu7ihPv1ZEo "Navigation on Android TV")

**Comment by maxkatz6** [comment] 2020-10-21 06:44
It's not clear enough for me, what exactly wrong on this video and what can be improved.

**Comment by hupo376787** [comment] 2020-10-21 06:59
@maxkatz6 I have updated the comment, thx.

**Comment by mdtauk** [comment] 2020-10-21 08:24
Once WinUI 3.0 is out, I hope every control will get a ControlTemplate with all the typographic and metric changes needed so when running on Xbox, the controls will look and behave correctly.

I suspect Microsoft will push more towards ReactNative for Xbox, as the new Store uses it to render the native controls, and WinUI 3.0 wont be supported at launch on Xbox, or non Desktop/Tablet form factors.

#698

**Comment by hupo376787** [comment] 2020-10-21 08:33
I have also noticed the new app store, seems better.

**Comment by ad1Dima** [comment] 2020-10-22 17:27
>3. Android TV's menu support sub menu, like
And NavigationView too 
![image](https://user-images.githubusercontent.com/3244664/96907860-0252e800-14c6-11eb-8e87-09bd31140ae6.png)

> A UI/UX video on Android TV
try `PaneDisplayMode="Left"` and `SelectionFollowsFocus="Enabled"`

**Comment by ad1Dima** [comment] 2020-10-22 17:28
> Android TV support navigates right to enter the selected page on the menu item. When the focus on the page, navigate left to open the menu.

this is interesting

**Comment by ad1Dima** [comment] 2020-10-22 17:35
> 1. Android TV's menu has the focus style, better than Xbox's rectangle border focus.

ListView had same reveal focus style.
![image](https://user-images.githubusercontent.com/3244664/96908786-50b4b680-14c7-11eb-8515-e6a55e8e5763.png)

I believe NavigationViewItem shold have same reveal focus style. Since it has moved on `ItemsRepeater` it lost it.

**Comment by hupo376787** [comment] 2020-10-23 01:58
@ad1Dima I also noticed `SelectionFollowsFocus`, but when set PaneDisplayMode="LeftCompact", there is a bug when opening `NavigationView` using `NavigationView.IsPaneOpen=true`. It closes immediately after opening.

**Comment by Felix-Dev** [comment] 2020-10-24 10:27
>  but when set PaneDisplayMode="LeftCompact", there is a bug when opening NavigationView using NavigationView.IsPaneOpen=true. It closes immediately after opening.

@hupo376787 This is by design. See the discussion starting [here](https://github.com/microsoft/microsoft-ui-xaml/issues/2391#issuecomment-666708683). Feel free to voice your concerns in that issue (and perhaps include pinging YuliKI from the WinUI team) if you disagree with that design thought.

We also still need to add that info to the NavigationView IsPaneOpen documentation (if kept) and I plan to create a commit soon.

**Closed** 2021-04-12 02:14 UTC
Labels: area-NavigationView, feature proposal, team-Controls
