### ISSUE TITLE
NumberBox spin buttons doesn't disappear upon scrolling

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#4605] opened 2021-03-22 01:05 UTC
**Describe the bug**

**Steps to reproduce the bug**

1. Open page with numberbox within a scrollviewer and lots of content
2. Click on spin button box
3. scroll down until selected numberbox is out of view
4. Spin buttons are still shown above all other content

**Expected behavior**
The spin buttons should be dismissed upon scrolling or should not be shown above other content.

**Screenshots**
![image](https://user-images.githubusercontent.com/59544401/111927812-3fb8a300-8a6f-11eb-9dc5-ddab7b1e6d58.png)

**Version Info**
Microsoft.Ui.Xaml 2.6.0-prerelease.210315002

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21337.1010)              | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-03-23 00:00
What a great issue.  Looking closer at this, the issue is that the flyout is acting as if it is light dismiss while not being a light dismiss popup. It does this by closing the popup when the control looses focus, however actual light dismiss popups do more than this, they also, for instance, block scroll wheel input from reaching things outside of the popup, effectively preventing scrolling. We don't use light dismiss in this case because we need to be able to continue to interact with the numberbox via keyboard and mouse while leaving the popup open.  This is actually an issue in other places as well, you can repro the same thing with autosuggest box.

It's unclear to me how we should be fixing this...

**Comment by StephenLPeters** [comment] 2021-03-23 00:02
@ranjeshj @jevansaks and @MikeHillberg this seems like an architecural question. It seems like we would want to think whollistically about what we want to do with parented popups when their parent scrolls off screen.

**Comment by jevansaks** [comment] 2021-03-23 20:32
> @ranjeshj @jevansaks and @MikeHillberg this seems like an architecural question. It seems like we would want to think whollistically about what we want to do with parented popups when their parent scrolls off screen.

I'm not familiar with how this feature is built, but why is it using popups instead of just putting elements in the tree?

**Comment by MikeHillberg** [comment] 2021-03-31 05:25
Yes, popups are in a separate layer so not subject to any clipping going on in the main layer. The transform is copied over though. So the buttons stay with the box as it scrolls, but don't get clipped when scrolled out of the viewport. (A ScrollViewer is a translate transform + a clip.)

This shows up in Xaml Controls Gallery too.

The motivation to use a popup is to break out of the bounding box of the text element, and not get obscured by any higher z-order element nearby.

![image](https://user-images.githubusercontent.com/18429489/113094148-0b975d80-91a6-11eb-8bbb-6428c7e35a25.png)

We've talked about having WPF's [AdornerLayer](https://docs.microsoft.com/dotnet/api/System.Windows.Documents.AdornerLayer) or something like it, this looks like a motivation for that.

**Comment by jevansaks** [comment] 2021-03-31 14:38
> The motivation to use a popup is to break out of the bounding box of the text element, and not get obscured by any higher z-order element nearby.

Hmmm ... these two goals seem at odds. I don't understand why these can't just be in the NumberBox outside of anything else it draws and then with Canvas.ZIndex = bignumber. Drawing on top of neighbors that the NumberBox control isn't already drawing on top of seems dubious.

If we had adorner support, how would that help?

**Comment by jevansaks** [comment] 2021-03-31 21:04
But you can draw and receive input out of the bounds of your layout slot with negative margins or canvas positioning or tricks like that.

**Comment by Jay-o-Way** [comment] 2021-11-27 08:01
Any news yet?

**Comment by StephenLPeters** [comment] 2021-11-29 19:57
@MikeHillberg @jevansaks and @ranjeshj can we just attach to the effective viewport changed event on numberbox and close the spin button popup when it's effective viewport is of 0 size?

**Closed** 2023-08-05 11:18 UTC
Labels: area-Flyouts, area-NumberBox, team-Controls, no-issue-activity
