### ISSUE TITLE
Caption Buttons do not work on certain platforms when content extended into titlebar

### ISSUE THREAD

**Issue by NPadrutt** [microsoft/microsoft-ui-xaml#6895] opened 2022-03-28 18:14 UTC
### Describe the bug

I have a WInUI 3 application that I migrated from UWP over that extends the content into the titlebar. When I add a margin to the div in the title on certain platforms the caption buttons do no longer work as if they are covered by the div.

I orignally made a StackOverflow post that you can find here: https://stackoverflow.com/questions/71563972/caption-buttons-do-not-work-when-content-is-extended-into-titlebar?noredirect=1#comment126617134_71563972

So far we found out that Windows 10 and some Win11 pc's it does work, but on others it doesn't. Also the buttons do react to the click in changing colors, but the action (minimize, maximize or close) is not executed as it seems.

### Steps to reproduce the bug

I have a repor sample here: https://1drv.ms/u/s!Ang3D30bKDOhqfQVfrORlAVxleTVeA?e=IqqMyv

The XAML code looks like this:

```
<Window
    x:Class="MoneyFox.Win.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="34" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <Grid x:Name="AppTitleBar" Margin="0,0,120,0" Background="{ThemeResource TitleBarBrush}">
            <TextBlock x:Name="AppTitleTextBlock" Text="Money Fox"
                       Style="{StaticResource CaptionTextBlockStyle}"
                       Margin="12,0,0,0" VerticalAlignment="Center" />
        </Grid>

        <Frame Grid.Row="1" x:Name="ShellFrame" />
    </Grid>
</Window>
```

With the example it works, when I remove ` Margin="0,0,120,0"`.  Funny enough when I change it to ` Margin="0,0,60,0" half of the buttons do work. 

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by ojhad** [comment] 2022-03-29 23:22
@pratikone Do you know what's going on here?

**Comment by akbayt** [comment] 2022-03-30 07:34
Hi, we have a live and active game on the store and the buttons stopped working for our game as well. As @NPadrutt mentioned removing margin fixes the issue. Now the solution looks simple: just removing the margin. However, if this is a bug with one of the windows update: 

- after removing the margin, the buttons will stop working for the users who don't have the latest windows update 
- when the Microsoft team fixes the issue, we need to revert the margin fix
- also it sounds like, it might behave differently on 10 and 11

so this should be addressed properly.

Any suggestion?

**Comment by sakurai-5317** [comment] 2022-03-30 16:25
I've encountered this on Windows 10 and 11 with both Windows App SDK 1.0.0 and 1.0.1.

**Comment by pratikone** [comment] 2022-03-31 17:03
Hi, thanks for reporting this. We are working to update the documentation to not use the margins. The titlebar uses coordinates of uielement to create an invisible glass window on top for doing the dragging operations. With right margin assigned to the uielement, the glass window shifts to left side, leaving caption buttons exposed and not working. The docs will be updated soon to remove margins and recommending people not to use it for titlebar uielement.

**Comment by pratikone** [comment] 2022-03-31 17:10
@akbayt  even in the older release, the titlebar element should work without the margin. the only issue was that you would have to account layout space for caption buttons.   
There should be a difference in windows 10 and 11 versions. Using margins was a workaround for the issue of app content covering up the titlebar area. With new titlebar implementation, it is no longer needed. We are also working to see if we can ignore margin values at all if it is applied to the titlebar element

**Comment by pratikone** [comment] 2022-03-31 17:22
This is intentional. The way custom titlebar works, there is a glass window on top of titlebar area which takes up all the input and does the processing. So in case of smoke layer, clicking on smoke layer which is at titlebar area won't dismiss it. so we have decided to shift the smoke layer down. this is consistent with how it will appear with system titlebar too. The smoke layer doesn't cover that area up.

**Closed by pratikone** 2022-03-31 17:22 UTC
Labels: needs-triage, team-Reach, area-TitleBar

**Comment by harvinders** [comment] 2022-04-01 14:04
@pratikone You have used words like `glass layer` and `smoke layer`. Would you please care to explain the difference? Or are you using these terms interchangeably? 

Also, one would expect that if they are extending the content into titlebar, the content and titlebar becomes indistinguishable, hence I fail to understand why should there be a `smoke layer` over the titlebar region.

**Comment by NPadrutt** [comment] 2022-04-01 18:59
@pratikone Thanks for the explanation. Unfortunately, I don't really understand it - which might be totally due to a lack of know how on my part. But when it is the intended way this works, could you point out how to fix problem? Since as it seems the official documentation does it in an unintended way then, since my example is based on the [documentation](https://docs.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=winui3#title-bar-components)?

Also I have to say I'm pretty surprised that this kind of change is included in a patch update. I didn't expect breaking changes in one of those.

**Comment by pratikone** [comment] 2022-07-12 19:17
With new updates, titlebar will ignore any margin applied UIElement set as titlebar, except for left margin.  This should fix some of the issues. 

Smoke layer is the semi transparent white background when content dialog is open. 

Glass window is inner detail of how a custom titlebar is implemented. Basically, over the whole UIElement as well as min max close buttons, there is a transparent HWND, whose job is to capture all input which occurs in that region and forward it to window below. This is what enables dragging in the custom titlebar. This transparent window is called glass window

**Comment by krschau** [comment] 2022-07-13 15:48
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6859
