### ISSUE TITLE
Exception thrown when new item is added to ObservableCollection ItemsSource of TreeView

### ISSUE THREAD

**Issue by dpaulino** [microsoft/microsoft-ui-xaml#631] opened 2019-04-30 03:05 UTC
**Describe the bug**
`System.Exception. The operation attempted to access data outside the valid range` error is thrown when adding item to ObservableCollection ItemsSource of TreeView. This error only occurs after the existing items in the TreeView have been reordered in a specific way.

**Steps to reproduce the bug**

1. Download this sample UWP solution: https://github.com/dpaulino/treeviewtest
2. Run in Local Machine. The TreeView will be populated by two items named `first` and `second`.
3. Drag and drop `second` into `first`
4. Press the "Add" button above the TreeView control.
5. Exception thrown.

**Expected behavior**
No exception thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/7649589/56938788-09f42500-6ab9-11e9-9cad-5c56d31d887a.png)

**Version Info**

NuGet package version: 
Microsoft.Ui.Xaml 2.1.190405004.2 and 2.2.190425001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| April 2019 Update (18362)   | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment] 2019-04-30 17:09
This sounds like a dupe of #556. Without that fix the drag&drop operation is leaving the TreeView internal list out of sync with the data source, so then moving items in the data source will cause further inconsistencies.

Can you try one of the latest CI builds as Kai was showing in #556?

**Comment by dpaulino** [comment] 2019-04-30 22:49
I performed the same repro steps as I detailed above but with `2.2.190425001-prerelease` and the same error occurs.
![image](https://user-images.githubusercontent.com/7649589/56998256-85a8ad00-6b5f-11e9-94a3-a2b90e491efa.png)

**Comment by jevansaks** [comment] 2019-05-01 21:17
Thanks. @rbrid can you take a look?

**Comment by dpaulino** [comment] 2019-05-01 21:34
Thanks @jevansaks. 

@RBrid Let me know if there's anything else I can help with.

**Comment by dpaulino** [comment] 2019-05-17 06:45
Hi all, just checking in about this exception. Any updates? Thanks in advance!

**Comment by dpaulino** [comment] 2019-06-12 16:14
Hi all, checking in again. Is there a workaround I could do on my end? This bug is blocking one of my features in my application, and my customers are complaining

**Closed** 2019-06-14 18:04 UTC
Labels: area-TreeView, bug, working on it
