### ISSUE TITLE
Question: How to use menuflyout in CommandBarFlyout with touch screen

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#2040] opened 2020-02-28 15:33 UTC
If the mouse pointer is placed on MenuFlyout in a mouse environment, it will automatically open and work fine. However, in a touch screen environment, it must be clicked to expand MenuFlyout, but CommandBarFlyout will automatically close at this time, so MenuFlyout cannot be expanded in a touch screen environment. I want to know if there is any way to make the touch screen work properly?

Here is mouse:
![image](https://user-images.githubusercontent.com/42038175/75561028-426de200-5a81-11ea-9b4a-5b98ac805d17.png)

Here is touch screen:
<img width="262" alt="无标题" src="https://user-images.githubusercontent.com/42038175/75561445-fe2f1180-5a81-11ea-888c-e00f19d0f41d.png">

Here is my example code:

        <CommandBarFlyout x:Name="FileFlyout"
                          Placement="RightEdgeAlignedTop">
                <AppBarButton Label="Open with..."
                              Name="OtherOpenMethod"
                              x:Uid="OtherOpenMethod"
                              Icon="AllApps">
                    <AppBarButton.Flyout>
                        <MenuFlyout x:Name="FileOpenMethodFlyout">
                            <MenuFlyoutItem />
                            <MenuFlyoutItem />
                        </MenuFlyout>
                    </AppBarButton.Flyout>
                </AppBarButton>
         </CommandBarFlyout>

**Comment by shaheedmalik** [comment] 2020-02-28 20:17
That's a bug.

**Comment by YuliKl** [comment] 2020-02-29 05:26
This definitely feels like a bug. Seems that CommandBarFlyout is a bit too aggressive in closing when it loses focus. I tried changing its ShowMode and also tried setting the button's AllowFocusOnInteraction property to False but neither helped.

@zhuxb711 one thing to try is replacing your AppBarButton with attached Flyout with:

```xaml
<AppBarElementContainer>
    <MenuFlyoutSubItem Text="Open with..." Icon="AllApps">
        <MenuFlyoutItem />
        <MenuFlyoutItem />
    </MenuFlyoutSubItem>
</AppBarElementContainer>
```

I saw two problems with this approach but am curious if this might work for your scenario.
1. The icon didn't render. I believe this is by design because the MenuFlyoutSubItem isn't in a MenuFlyout. Seems that we have not documented this limitation but I recall discussing this decision  in the past.
2. The content of the MenuFlyoutSubItem is rendering behind the CommandBarFlyout in z order. I think that's a bug although there may be technical limitations this behavior stems from.

Please give this a try and we may need to open some follow-up issues to track all this.

**Comment by zhuxb711** [comment] 2020-02-29 07:54
@YuliKl 

I tried it according to your method, but there are some problems, including: the icon does not render correctly, it is shorter than the entire CommandBarFlyout.

In addition, although it works correctly under the touch screen, it cannot be closed once it is expanded

like this:

<img width="294" alt="无标题" src="https://user-images.githubusercontent.com/42038175/75603674-9a512b00-5b0b-11ea-9037-069fcce8bb42.png">


![image](https://user-images.githubusercontent.com/42038175/75603671-91605980-5b0b-11ea-9d62-cc0672858642.png)

**Comment by zhuxb711** [comment] 2020-04-04 03:26
@YuliKl Is there any progress on the fix for this issue?

**Comment by ranjeshj** [comment] 2020-04-15 12:01
@llongley any thoughts on a fix for this issue ?

**Comment by zhuxb711** [comment] 2020-05-30 06:11
@YuliKl
@ranjeshj
Regarding this issue, is there any solution available?

**Comment by zhuxb711** [comment] 2020-08-01 05:35
Is there any progress now? When will this be fixed?

**Comment by StephenLPeters** [comment] 2020-08-05 20:49
@zhuxb711 I got some time and looked into this issue today.  The bug in CommandBarFlyout is caused by this [line](https://github.com/microsoft/microsoft-ui-xaml/blob/83b95302a4f0715be1f3ebcc8744b2cb2cc09dc1/dev/CommandBarFlyout/CommandBarFlyout.cpp#L274). Normally when we attach the close function to the secondary item's click events we ignore the buttons which have flyout to prevent the closing behavior you are seeing. However it looks like we forgot to include that in this particular case.  I will send out a PR to fix this soon, but if you need a work around to use before we publish a new Winui 2 prerelease/release let me know.  You could probably work around the bug by inserting your menu items with flyouts into the collection after the fact so that they are treated by the vector changed code path which has the bug fix.

**Comment by StephenLPeters** [comment] 2020-08-05 21:11
There is an additional issue where invoking a button from a flyout of a secondary command (with any input) doesn't close the CommandBar.  Fixing this will be a little bit trickier,  I've opened issue #3052 to track

**Closed** 2020-08-06 21:12 UTC
Labels: area-Commanding, question, team-Controls, working on it

**Comment by zhuxb711** [comment] 2020-09-26 09:28
Clicking a button with flyout will still cause the commandbarflyout to close in 2.5.0-prerelease.200923002
@StephenLPeters

**Comment by zhuxb711** [comment] 2020-09-30 04:14
Sorry, now I can confirm that the problem has been properly resolved
