### ISSUE TITLE
Error APPX3217: SDK folder containing 'UAP.props' for 'UAP 10.0.18362.0' cannot be located.

### ISSUE THREAD

**Issue by abhi-msft** [microsoft/microsoft-ui-xaml#3805] opened 2020-12-14 18:36 UTC
I have a WINUI desktop app project building fine in VS but when tried from cmd giving the error:
**C:\Program Files\dotnet\sdk\5.0.100-preview.5.20279.10\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(1063,5): error APPX3217: SDK folder containing 'UAP.props' for 'UAP 10.0.18362.0' cannot be located.**

I am trying to create a CI/CD pipeline from Azure DevOps hosted build agent which started giving me this error.
I logged into the machine and confirmed it has SDK 10.0.18362.0 installed along with newer one and running fine when opened from VS. It is complaining when run in cmd and is blocking CI/CD.

**Version Info**
dot net - 5.0.100-preview.5.20279.10
Win UI - 3.0.0-preview2.200713.0
Win 10 - May 2020 Update (19041)
Desktop - Yes

**Comment by StephenLPeters** [comment] 2020-12-15 00:06
@abhi-msft can you confirm that the issue is present when using preview3?

@stevenbrix FYI

**Comment by huoyaoyuan** [comment] 2020-12-15 19:50
Preview 2 is only compatible with VS 16.7. This looks like the issue reported when using Preview 2 with VS 16.8.
The only solution should be updating to Preview 3.

**Comment by abhi-msft** [comment] 2020-12-15 19:54
@huoyaoyuan I am using VS 16.7

**Comment by abhi-msft** [comment] 2020-12-15 19:56
I uninstalled SDKs that came with VS and installed them using exes and then used msbuild which made it work. Earlier was using dotnet build which I believe is not using full capabilities of msbuild.

**Comment by huoyaoyuan** [comment] 2020-12-15 19:58
AFAIK winui isn't compatible with `dotnet build` for now. Make sure you launch the correct version of msbuild shipped with VS.

**Comment by abhi-msft** [comment] 2020-12-15 20:00
Yeah got to know after some searching, thank you @huoyaoyuan

**Comment by stevenbrix** [comment] 2021-01-09 01:09
Sorry that you came across this issue @abhi-msft. I'm going to close this since it no longer repros.

Thanks @huoyaoyuan for helping @abhi-msft, you're a rockstar!

**Closed by stevenbrix** 2021-01-09 01:09 UTC
Labels: area-NugetPackage, winui3preview
