### ISSUE TITLE
ContentDialog fails to display WinUI 3 Preview 1 and .NET 5 Desktop

### ISSUE THREAD

**Issue by darenm** [microsoft/microsoft-ui-xaml#2504] opened 2020-05-20 21:30 UTC
**Describe the bug**
While trying out WinUI3 and .NET 5 desktop app, I tried to display a ContentDialog both in code and via a XAML definition. In both circumstances I received the the following exception:

```csharp
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IContentDialog.ShowAsync()
   at Microsoft.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at N5UI3Test.MainWindow.<myButton_Click>d__1.MoveNext() in D:\D-Repos\N5UI3Test\N5UI3Test\N5UI3Test\MainWindow.xaml.cs:line 42
```

**Steps to reproduce the bug**

1. Create new **Blank App, Packaged (WinUI in Desktop)** app
2. Open **MainWindow.xaml.cs**.
3. Update the **myButton_Click** method to the following:

   ```csharp
   private async void myButton_Click(object sender, RoutedEventArgs e)
   {
       myButton.Content = "Clicked";
       var cd = new ContentDialog
       {
           Title = "Button Clicker!",
           Content = "You clicked the button!",
           CloseButtonText = "Ok"
       };
       var result = await cd.ShowAsync();
   }
   ```
4. Run the app
5. Click the **Click Me** button and observe the exception.

**Expected behavior**

I expect to see the ContentDialog displayed.

**Screenshots**

![image](https://user-images.githubusercontent.com/1674843/82498534-669ff480-9aad-11ea-95bb-01cd185b332b.png)

**Version Info**

Windows 10 Version 1909 (18363.836)
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.7.0 Preview 1.0
Desktop PC 2x 4K monitors
Microsoft.NETCore.App 5.0.0-preview.4.20251.6

NuGet package version: 
Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by JesseCol** [comment] 2020-05-21 21:08
I expect the fix here is that for desktop apps the app needs to set ContentDialog.XamlRoot before showing the dialog.  But we really need a better error message.

**Comment by darenm** [comment] 2020-05-21 21:20
Confirmed the above.

I updated the **myButton_Click** method to:

```csharp
private async void myButton_Click(object sender, RoutedEventArgs e)
{
    myButton.Content = "Clicked";
    var cd = new ContentDialog
    {
        Title = "Button Clicker!",
        Content = "You clicked the button!",
        CloseButtonText = "Ok"
    };

    cd.XamlRoot = this.Content.XamlRoot;
    var result = await cd.ShowAsync();

    //var cd = new ContentDialogExample();
    //await cd.ShowAsync();
}
```

**Comment by JesseCol** [comment] 2020-05-21 21:34
Great, thanks for the quick validation!  Let's still leave this open to track improving the error message.

**Comment by jtbrower** [comment] 2020-07-04 21:05
I stumbled into this one moments ago, thank you @darenm for reporting this so I could quickly apply the fix suggested above. 

It seems that documentation and samples might need explicit updates.  I am new to both UWP/WinUI coming from about 13 years in WPF.  When digging for samples I came across the following resources, but I don't know which ones will need updated and which ones are specific to legacy UWP and should remain the same.  For that reason I didn't suggest changes at any of these locations, but will if the powers-to-be want me to.

- [UWP Dialogs](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/dialogs)
- [UWP Dialog API](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.contentdialog?view=winrt-19041)
- [XAML Controls Gallery Content Dialog](https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/ControlPages/ContentDialogPage.xaml.cs)

**Comment by marb2000** [comment] 2020-07-06 23:48
Thanks @jtbrower for the feedback. Let's ping @anawishnoff who driving the new WinUI documentation.

**Comment by MikeHillberg** [comment] 2020-07-06 23:54
Shouldn't ContentDialog in a Desktop app create a modeal top-level window (and so not need the XamlRoot to be set)?

**Comment by marb2000** [comment] 2020-07-07 00:14
Good point Mike. 

Adding some context to other readers. Today, the ContentDialog is just XAML content placed on the top of the Visual Tree. In WPF, ContentDialog is like a MessageBox, which is a modal top-level Window. You are opening a discussion about whether we should pivot the current ContentDialog design towards a modal top-level Window. Am I right?

I have several thoughts about it:
1. Agree with ContentDilalog won't need XamlRoot anymore.
2. What parent Window will host the ContentDialog child Window. There can be multiple window objects in the same thread. So, do we need new APIs? For example:

    ```  contentdialog.ShowAsync(mywindow); ```

3. How will the new top-level child ContentDIalog work with the RequestedTheme feature?
4. Will this work in XAML Islands scenarios?

**Comment by anawishnoff** [comment] 2020-07-07 18:14
Thanks for the suggestions @jtbrower! We are definitely looking into creating more samples and docs for WinUI3 as it matures. I know that the scenario of coming from WPF -> WinUI is going to be a common one, so I'll definitely be pushing for docs that highlight key feature differences and/or a getting started guide coming from WPF.

We'll be continuing to add new and useful documentation about WinUI 3 throughout the year, and new docs will not necessarily have to be tied to releases.

**Comment by jtbrower** [comment] 2020-07-07 21:05
@anawishnoff I agree that there could be a big wave of developers evaluating WinUI as a UI stack replacement for WPF.  Since WPF is the goto framework for MVVM backed desktop applications, I imagine that there are a lot of developers out there who never migrated to UWP because of the vast differences in security restrictions as well as the Windowing model.  Now that the WinUI team is focusing on Desktop applications, it finally gives us WPF centric developers _some_ of the tools we need to move to a more performant version of XAML.  It may even convince some of the larger WinForms application developers to finally take the plunge and move over to XAML.

I will continue to document my journey and share it back with the team to help improve the transition for other WPF developers.

**Comment by tuggernuts** [comment] 2020-09-30 14:25
Hi, @anawishnoff  I'd like to agree with and add to @jtbrower's comment.

I went from WPF, to UWP, and now evaluating WinUI for Desktop for similar reasons. The UWP -> WinUI jump will be common, and not simple, I am finding.

For those of us 'evaluating,' there is a paucity of working samples and even less documentation. It's practically impossible to evaluate anything, beyond the most simple 'Hello World' app. So I'd respectfully ask that any docs and samples that exist, in whatever state, that they be put somewhere where developers can find and use them. Right now, I'm just picking through the issues here and screengrabs from whatever videos (i,e, ignite) I can find.

**Comment by marb2000** [comment] 2020-10-01 20:23
Thanks for your feedback @tuggernuts, I know @anawishnoff is working in a plan to improve the documentation, but it won't be landed soon. I hope the Preview 3 (Nov 2020) allows us to update the samples and create even more docs specific for WinUI 3. I will make public the sample I show at Ignite as well with the Preview 3 release too.

**Comment by HebuSan** [comment] 2021-08-04 20:48
Hi,
Just in case, this issue still exists with WinUi 3 (Windows App SDK 0.81) in desktop mode. 
This post is the only place where I could find a workaround. Thx @darenm.
I can confirm the exception thrown is not really clear.

Also, I tried using ContentDialog because I faced weird issues while trying to use a MessageDialog in my code.
Using MessageDialog leads to the following exception:
"system.runtime.interopservices.comexception the handle is invalid"

On this [link](https://docs.microsoft.com/en-us/uwp/api/windows.ui.popups.messagedialog?view=winrt-20348) it is said
_"You should use MessageDialog only when you are upgrading a Universal Windows 8 app that uses MessageDialog, and need to minimize changes. For new apps in Windows 10, we recommend using the ContentDialog control instead."_

But maybe this should be fixed as well, if we can still refer to the MessageDialog Class.

**Comment by dedaap72** [comment] 2021-11-26 00:39
This issue still exists in WinUI3, with the same vague error message. And agreeing with what others have written, documentation for WinUI is sparse. Also, with the different frameworks now it's hard to find the right way for the framework you're using. Coming from WPF but not having used UWP before, it's sometimes unclear where to look: WinUI? WinRT? UWP? Some things from WPF work in WinUI but others don't, so what's the alternative?

**Comment by Gabboxl** [comment] 2022-02-11 23:01
> This issue still exists in WinUI3, with the same vague error message. And agreeing with what others have written, documentation for WinUI is sparse. Also, with the different frameworks now it's hard to find the right way for the framework you're using. Coming from WPF but not having used UWP before, it's sometimes unclear where to look: WinUI? WinRT? UWP? Some things from WPF work in WinUI but others don't, so what's the alternative?

I completely agree. Just got into WinUI 3 and everything is so confusing, especially the documentation even for basic things like that. Hope things will be clearer in the future.

**Comment by AtosNicoS** [comment] 2022-05-25 08:48
Is [the solution by @darenm](https://github.com/microsoft/microsoft-ui-xaml/issues/2504#issuecomment-632352279) supposted to be the common way to handle ContentDialogs or is this just a workaround for a bug that must be fixed in the framework? I am currently confused on what to use for WinUI3, as it is so buggy.

**Comment by kmgallahan** [comment] 2022-05-25 17:17
@marb2000 

The [WinUI 3 docs for ContentDialog](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.contentdialog?view=winui-3.0) mention setting xamlroot, however as the text was copied from the UWP / WinUI 2 docs it erroneously hints that it isn't always required when using WinUI 3 / Microsoft.UI.Xaml, which is not the case.

In my opinion WinUI 2 should not be referenced while browsing WinUI 3 / Microsoft.UI.Xaml docs as seen in the ContentDialog "Tip" bubble. 

Further, old code samples like the ones shown before xamlroot is mentioned should be updated to reflect the current state of working with ContentDialog.

Although it would take a fair amount of time, not cleaning out old legacy UWP / WinUI 2 code, links, and references from the WinUI 3 docs is going to perpetually confuse newcomers.

**Closed** 2023-08-03 22:36 UTC
Labels: area-Dialogs, team-Controls, product-winui3, no-issue-activity
