### ISSUE TITLE
Question: Launching multiple windows

### ISSUE THREAD

**Issue by Grinch** [microsoft/microsoft-ui-xaml#4709] opened 2021-04-01 04:54 UTC
I am attempting to activate another window instance but was greeted with the following error.

```
Exception thrown at 0x00007FFC4FAA67AC (KernelBase.dll) in UI.exe: WinRT originate error - 0x80004005 : 'WinUI: Error creating second Desktop Window on the current process. No more than one Desktop Window is allowed per process.'.
Unhandled exception at 0x00007FFBAAE94BA8 (Microsoft.ui.xaml.dll) in UI.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x000001E4DDF05A10, 0x0000000000000005).
```

There error is clear... but I am not able to find *how* to properly open a new window with WinUI 3 Desktop. If someone could provide me with the proper approach I would appreciate it.

**Comment by StephenLPeters** [comment] 2021-04-01 23:24
@pratikone and @Austin-Lamb FYI

**Comment by Zidane** [comment] 2021-04-02 16:01
Hitting this as well. Any idea from anyone in the community on the proper way to open a Window?

**Comment by aqibbanday** [comment] 2021-04-05 14:42
Unhandled exception at 0x7A937E30 (Microsoft.ui.xaml.dll) in *.exe: 0xC000027B: An application-internal exception has occurred (parameters: 0x1799EA10, 0x00000001).

Window window = new Window();
window.Content = new TextBlock(){ Text = "Hello" };
window.Activate();

**Comment by Zidane** [comment] 2021-04-06 22:58
@pratikone @Austin-Lamb @StephenLPeters 

Any update on this?

**Comment by codendone** [comment] 2021-04-07 05:22
The release of Project Reunion 0.5 does not support more than one Window in the process, and will throw this error on any attempt to create a second window. Obviously this is an unfortunate limitation right now, but there is a lot of remaining work to ensure multiple windows are release quality, which is why the limitation is enforced.

Preview builds, including the Project Reunion 0.5 preview from a few weeks ago and the upcoming Project Reunion 0.8 preview, can be used for multi-window development, with the caveat that you might hit known and unknown issues.

**Comment by aqibbanday** [comment] 2021-04-07 08:49
Window window = new Window();
window.Content = new TextBlock(){ Text = "Hello" };
window.Activate();
The above code sample is from documentation of Project Reunion 0.5.

In preview is it possible to show window as a dialog like we do in WPF with window.ShowDialog(); method.

**Comment by codendone** [comment] 2021-04-08 03:07
@aqibbanday Yes, that code works in preview builds.

**Comment by Grinch** [comment] 2021-04-09 04:37
@codendone How does one work with preview builds specifically? I'm not seeing anything specific to using those off-hand.

**Comment by aqibbanday** [comment] 2021-04-09 05:59
@Grinch I think you need to install preview WinUI 3 project templates.

**Comment by marb2000** [comment] 2021-04-09 18:32
Closing the issue given it's a temporary limitation of the platform that will be solved, hopefully, for Reunion v1.

**Closed by marb2000** 2021-04-09 18:32 UTC
Labels: area-Desktop, needs-triage, question, team-Reach, winui3preview

**Comment by Bonobomagno** [comment] 2022-01-25 11:07
now v1 is out, but It is not working, so open it again please

**Comment by aqibbanday** [comment] 2022-01-25 11:14
Check the road map

**Comment by Bonobomagno** [comment] 2022-01-25 11:47
1.1, but in v1 preview 3 the issue is still there

**Comment by Reza-Noei** [comment] 2023-11-03 17:47
Any update on this ?

**Comment by wherewhere** [comment] 2025-06-30 09:28
Find a discussion https://github.com/microsoft/WindowsAppSDK/discussions/3666
It does not need to use `DesktopWindowXamlSource` now.
