### ISSUE TITLE
The default style doesn't apply to the inheritor of the component

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#6606] opened 2022-01-14 13:03 UTC
### Describe the bug

Hi, the default style doesn't apply to the inheritor of the CalendarView. Take a look at the attached screenshot and code

### Steps to reproduce the bug

```csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
        }
    }
    public class MyCalendar : CalendarView { }
```
```xaml
    <StackPanel VerticalAlignment="Center" Spacing="30" Orientation="Horizontal">
        <local:MyCalendar/>
        <local:MyCalendar Style="{StaticResource DefaultCalendarViewStyle}"/>
    </StackPanel>
```

### Screenshots

![image](https://user-images.githubusercontent.com/47348109/149519362-ce3d6aa5-c31e-40e3-84a3-6ca570bba4d6.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by StephenLPeters** [comment] 2022-03-02 18:31
I believe this is a known behavior where Styles with TargetType=Foo do not get automatically applied to FooDerived. The system does its walk looking for a style and doesn't commit to the style that targets the parent type because it would prefer to find one that targets its type.  But when it doesn't find one it then defaults to the meta-data defined default style which for calendar view is the one defined in System xaml.  Specifying the style as you have is the recommendation.

All that being said I'm surprised to see this behavior in Winui3.  My understanding was that the styles from Winui2 are replacing the styles defined in Generic.xaml in winui3 so the outdated calendarview style shouldn't even exist... @llongley @codendone @MikeHillberg can you explain why this isn't the case?

**Comment by michael-hawker** [comment] 2022-09-29 16:31
Is there any workaround for this, like there was for https://github.com/microsoft/microsoft-ui-xaml/issues/3502?

**Comment by michael-hawker** [comment] 2023-07-13 21:20
Bumping, based on https://github.com/microsoft/microsoft-ui-xaml/discussions/8638

**Comment by DmitriyKomin** [comment] 2023-11-29 23:22
Duplicate of #8869

**Closed** 2023-11-29 23:22 UTC
Labels: bug, area-Styling, team-Controls, product-winui3, wct

**Comment by michael-hawker** [comment] 2023-11-30 21:11
@DmitriyKomin should this be the other way around? Generally, the older issue is left as the open one.
