### ISSUE TITLE
WinUI for Desktop

### ISSUE THREAD

**Issue by Fernand-Delavy** [microsoft/microsoft-ui-xaml#4375] opened 2021-02-28 14:46 UTC
i use Visual Studio 16.9.0.Preview 5.0

App can't print because crash:
PrintManager manager;
manager = PrintManager.GetForCurrentView(); // System.Runtime.InteropServices.COMException: 'Interface non enregistrée (0x80040155)'
The print capability is important

Can't change Windows title from 'WinUI Desktop' to app name

MessageDialog crash work arond use ContentDialog ?

**Comment by sigmarsson** [comment] 2021-03-01 19:59
Yes ContentDialog.

**Comment by StephenLPeters** [comment] 2021-03-03 01:00
@Austin-Lamb FYI. @Fernand-Delavy I haven't seen PrintManager before, but the api's that have *ForCurrentView() generally use the core window, which isn't supported in Winui3 preview 4.  I don't know if this has another way to do it or not.

**Comment by dedaap72** [comment] 2021-11-28 00:59
I'm running into the same problem in WinUI3. How do I get printing to work? All examples I Google use UWP.

**Comment by Fernand-Delavy** [comment] 2021-11-28 15:08
Sorry for my bad englich

I think here is a "Wirte Only" forum. All developper write but the Microsoft Staff (GitHub)  never reply !
My post is 9 month old and no solution !

**Comment by StephenLPeters** [comment] 2021-11-29 19:49
@MikeHillberg and @codendone FYI

**Comment by EliDotNet** [comment] 2022-04-13 20:00
so no solution?

**Comment by krschau** [comment] 2022-06-15 16:42
Please try the solution in the [sample app](https://github.com/marb2000/PrintSample) linked in https://github.com/microsoft/microsoft-ui-xaml/issues/7234.

Essentially, as mentioned above, *ForCurrentView() methods don't work in WinUI 3 desktop apps, which don't have a core window. But you can work around it with an hwnd and the interop method:

```
var hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
printMan = PrintManagerInterop.GetForWindow(hWnd);
```

I'm closing this as a dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/4419, and any more conversation can happen over there.

**Closed by krschau** 2022-06-15 16:42 UTC
Labels: duplicate, needs-triage
