### ISSUE TITLE
Clipping issue in RadioButtons items

### ISSUE THREAD

**Issue by mayankkrjain** [microsoft/microsoft-ui-xaml#1666] opened 2019-11-23 15:03 UTC
**It seems the first item in RadioButtons is defining the max-width for all the remaining items. If an item with index>0 is having size more than the size of the first item (and greater than min-width) it will get clipped. This issue can also be seen in the test app where the last disabled item is clipped.**

**Steps to reproduce the bug**

1. Go to RadioButtons Sample page to see the issue.
2. Alternatively you can try out this sample.
`
    <controls:RadioButtons
    x:Name="RadioButtons">         
   <x:String>UnCheckedDisabl</x:String>
   <x:String>UnCheckedDisabled</x:String>
    </controls:RadioButtons>
`

**Expected behavior**
Text should not get clipped.

**Screenshots**

![RadioClip](https://user-images.githubusercontent.com/2456240/69480761-4c53c980-0e30-11ea-835d-92548824d191.png)

**Version Info**
This issue is reproducible in latest master.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |

**Comment by Felix-Dev** [comment] 2019-11-23 15:59
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/705 which has just been fixed in commit https://github.com/microsoft/microsoft-ui-xaml/pull/1623.

**Comment by mayankkrjain** [comment] 2019-11-23 16:43
@Felix-Dev - Yes. I am able to see the fix in the latest master. Thanks!
 However it seems the Focus navigation behavior is changed now. Earlier the selected item in the group used to get the focus. Not it's the first item in the focus direction which gets focused (and selection). Is this expected?

**Comment by jevansaks** [comment] 2019-11-23 17:00
I don't think that's expected. @kikisaints @stephenlpeters can you comment?

**Comment by jevansaks** [comment] 2019-11-23 18:25
Yeah I see the bug too. It seems to be when going from one RadioButtons control to another (if the previously focused control was not a RadioButtons then it seems to behave correctly). I wonder if some state is being shared. We'll need to trace through the GettingFocus logic.

**Closed** 2019-11-25 15:56 UTC
Labels: needs-triage, working on it
