### ISSUE TITLE
Textbox content is not visible properly when we focused the textbox. (WinUI_Desktop)

### ISSUE THREAD

**Issue by SathiyathanamSathish** [microsoft/microsoft-ui-xaml#6323] opened 2021-11-16 15:59 UTC
### Describe the bug

Textbox content is not visible properly when we focused the textbox. We suspect this issue happens because we have set the Height and Width Manually to the textbox.

### Steps to reproduce the bug

1. Run the sample.
2. Try to focus the TextBox.

**Observed Behaviour:**

You can see the textbox content ie. text is hidden.

**Please refer to the code snippets from below:**

![image](https://user-images.githubusercontent.com/89458634/142020139-309ad5e1-6ed8-48d9-8f51-cb115434b0a1.png)

### Expected behavior

Textbox content ie. text is should be shown.

### Screenshots

https://user-images.githubusercontent.com/89458634/142017887-6968ab36-3acd-4a84-8864-f1be0ef1d887.mp4

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Please refer to the below screenshots for the system information.

![image](https://user-images.githubusercontent.com/89458634/142018816-8e5c3fc6-9cb8-416e-990c-6befed3544b4.png)

**Comment by MikeHillberg** [comment] 2021-12-02 20:36
Looks like what's happening is that when there's more than one line of height, the clear-text button is overtaking the text area. So yes, it's setting that height triggers it.

Is the purpose of setting the height to allow multi-line and/or wrapping? If so you should set [TextBox.AcceptsReturn](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.Controls.TextBox.AcceptsReturn) and/or [TextBox.TextWrapping](https://docs.microsoft.com/uwp/api/Microsoft.UI.Xaml.Controls.TextBox.TextWrapping) (to Wrap or WrapWholeWords), and that will remove the clear button.

**Comment by JJBrychell** [comment] 2023-03-01 20:37
Closing this issue as by design.

By design, the delete button is square and sized to the height of the textbox.   Hence, if you create 300px high text box the delete button will be 300px wide and in a 300px textbox will not allow any space for valid text.  

Since the textbox only shows the delete button if it does not wrap, and there is no known scenario where it would be sufficiently advantageous to set a textbox to dimensions that would cause this error  (e.g. for a textbox to need this height its font would have the extremely large and as such a smaller delete button would provide no significant improvement in user experience), we will consider this by design.

If these assumptions are in correct and there does exist such a scenario, feel free to reactive this issue or submit a feature request to support these types of dimensions.

**Closed by JJBrychell** 2023-03-01 20:37 UTC
Labels: team-Rendering
