### ISSUE TITLE
WinUI 3 ContentDialog declaration in xaml as Flyout does

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#9707] opened 2024-06-07 18:26 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-3-ContentDialog-declaration-in-xam/10674154)._

---
**WinUI 3 ContentDialog declaration in xaml as Flyout does.**

My suggestion is that the developer can create a Customize ContentDialog in the XAML code as Flyout does. So it will enhance the way a developer can use a ContentDialog in a MVVM context as Flyout does. The properties(dependency properties) in the ContentDialog would be bind to ViewModel properties. The result of the dialog (ContentDialogResult) can be bind to another ViewModel property. 

My goal is to have the simplicity of the Flyout that can be declared and use from XAML code but in the ContenteDialog context. As I know the ContentDialog needs to create a new control and figure out how to give the XamlRoot. I think that kind of steps can be assign automatically from a XAML declaration. 

Or another way would be that the Flyout can have a modal dialog behavior that the user cannot go to another control before the modal dialog would be closed. Right now, as I know the Flyout is a lightweight contextual popup window that will be close for any common action outside the flyout.

---
#### Feedback Bot on 6/3/2024, 07:59 PM: 

(private comment, text removed)

**Comment by chrisglein** [comment] 2024-07-11 16:57
Duplicate of #4439

**Closed by chrisglein** 2024-07-11 16:57 UTC
Labels: feature proposal, area-Dialogs, needs-triage
