### ISSUE TITLE
Window Title property is not working

### ISSUE THREAD

**Issue by saravanan-2112** [microsoft/microsoft-ui-xaml#6882] opened 2022-03-24 07:35 UTC
### Describe the bug

I have created a simple sample and set "Title" to the window. Then if I build the sample, then it shows the below error.

The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found	App1	D:\syncfusion\winui\samples\App1\MainWindow.xaml	9	

**Sample:** [App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/8339317/App1.zip)

### Steps to reproduce the bug

1. Build the attached sample
2. It shows compilation error

### Expected behavior

The application should run with provided window title.

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by asklar** [comment] 2022-03-25 20:30
Duplicate of #3689

**Closed by asklar** 2022-03-25 20:30 UTC
Labels: needs-triage, team-Reach, product-winui3
