### ISSUE TITLE
WebView2 for UWP html pages has <Input  type="file"> can't browse to files to select file 

### ISSUE THREAD

**Issue by ZakaryaAtef** [microsoft/microsoft-ui-xaml#7278] opened 2022-06-25 14:14 UTC
I'm currently using webview2 version 1.0.1248-prerelease 
while trying to select file from browse button on any website it does nothing 
I tried it for uwp it doesn't work 
but for windows forms it works fine

**Comment by ZakaryaAtef** [comment] 2022-06-26 12:51
I added duplicate issue under bugs section

**Comment by krschau** [comment] 2022-06-27 18:21
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/7280

**Comment by krschau** [comment] 2022-06-27 18:22
Please see https://github.com/microsoft/microsoft-ui-xaml/issues/7280 for more information.

**Closed by krschau** 2022-06-27 18:21 UTC
Labels: needs-triage

**Comment by dineshgaikwad09** [comment] 2022-12-02 15:19
Is there any solution?
