### ISSUE TITLE
Can't remove padding of custom ContentDialog

### ISSUE THREAD

**Issue by tipa** [microsoft/microsoft-ui-xaml#5688] opened 2021-08-14 08:16 UTC
**Describe the bug**
I want to remove the padding of a subclassed ContentDialog.
Setting `ContentDialogPadding` to 0 is not working.

**Steps to reproduce the bug**
```
<ContentDialog
    x:Class="Namespace.AuthDialog"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Style="{StaticResource DefaultContentDialogStyle}"
    mc:Ignorable="d">

    <ContentDialog.Resources>
        <Thickness x:Key="ContentDialogPadding">0</Thickness>
    </ContentDialog.Resources>

...

</ContentDialog>
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/2863198/129439745-b81d39bc-7080-4eeb-bd1e-1d83b6df1c8c.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/2863198/129439733-de85d94e-6cc0-499c-aade-91284d696b90.png)

NuGet package version: 
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| YES |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
|  Build 19043.1165              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes|
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by llongley** [comment] 2021-08-17 01:42
That location for the resource may be too late, in that it may have already loaded the `DefaultContentDialogStyle` resource before picking up that override.  Does it work if you add it to the app resources instead in App.xaml, like this?

```
        <controls:XamlControlsResources ControlsResourcesVersion="Version2">
            <controls:XamlControlsResources.MergedDictionaries>
                <ResourceDictionary>
                    <Thickness x:Key="ContentDialogPadding">0</Thickness>
                </ResourceDictionary>
            </controls:XamlControlsResources.MergedDictionaries>
        </controls:XamlControlsResources>
```

**Comment by tipa** [comment] 2021-08-17 08:41
> Does it work if you add it to the app resources instead in App.xaml, like this?

No, the padding is still present.
Besides that, I don't want to remove the padding globally for all `ContentDialogs`, only for that particular `ContentDialog` subclass

**Comment by michael-hawker** [comment] 2021-08-18 17:38
This seems like a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4247?

**Comment by tipa** [comment] 2021-08-19 10:54
Looks like it.
Too bad it doesn't seem to have any priority to be fixed, even after all those months after it has been reported.

**Comment by michael-hawker** [comment] 2021-08-19 18:52
I plan to submit a fix for #424 on a future dev stream of mine and try and investigate #4247 too. I was able to build the WinUI repo locally and run their test app. Just trying to get our Toolkit release together and working on our last feature there, so don't know timing yet.

You can copy the style and test the suggested fix in #4247 and see if that works, knowing that would be helpful.

**Comment by tipa** [comment] 2021-08-19 19:00
@michael-hawker thanks!
Yes, using the adjusted template in my custom ControlDialog seems to work

**Comment by StephenLPeters** [comment] 2021-08-20 00:38
@tipa If you were able to make a PR with the fix now that you validated it that would be awesome!

**Comment by tipa** [comment] 2021-08-20 07:32
@StephenLPeters  Would it make sense to convert all these parameters to `ThemeResources`?
Currently they are all being used as `StaticResources`
https://github.com/microsoft/microsoft-ui-xaml/blob/92dcdc0c6bd97dca35d248f13a930aec02e0d105/dev/ContentDialog/ContentDialog_themeresources.xaml#L36-L42

**Comment by tipa** [comment] 2021-09-04 08:40
@StephenLPeters submitted a pull request.

**Closed** 2021-09-08 21:31 UTC
Labels: duplicate, area-Dialogs, team-Controls

**Comment by AtosNicoS** [comment] 2022-08-04 09:07
It seems that this issue is still not fixed in winui3, but the issue was closed, as it was references by the PR. Could you please reopen it?

Is there a workaround for this in the meantime?

**Comment by ojhad** [comment] 2022-08-14 16:43
@AtosNicoS Please open a separate issue for winui3 tracking.

@llongley are you aware of a workaround?
