### ISSUE TITLE
NavigationView Settings Icon Doesn't Update Position Fast Enough When Resizing

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1336] opened 2019-09-16 00:33 UTC
**Describe the bug**
The settings icon doesn't update it's position fast enough when resizing the window in top mode. Please see the giff below.

**Steps to reproduce the bug**
Can be reproduced with the simple code below:

```xaml
<Page
    x:Class="App3.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:mux="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <mux:NavigationView
        PaneDisplayMode="Top"
        IsBackButtonVisible="Collapsed"
        ItemInvoked="NavigationView_ItemInvoked">
        <mux:NavigationView.MenuItems>
            <mux:NavigationViewItem
                Content="File"
                x:Name="A" />
            <mux:NavigationViewItemSeparator />
            <mux:NavigationViewItem
                x:Name="B">
                <mux:NavigationViewItem.Icon>
                    <FontIcon
                        FontFamily="Segoe MDL2 Assets"
                        Glyph="&#xE80F;" />
                </mux:NavigationViewItem.Icon>
                <mux:NavigationViewItem.Content>
                    <TextBlock
                        Text="Home" />
                </mux:NavigationViewItem.Content>
            </mux:NavigationViewItem>
            <mux:NavigationViewItem
                Content="Item Title 1"
                x:Name="C" />
            <mux:NavigationViewItem
                Content="Item Title 2"
                x:Name="D" />
            <mux:NavigationViewItem
                Content="Item Title 3" />
            <mux:NavigationViewItem
                Content="Item Title 4" />
        </mux:NavigationView.MenuItems>
        <Border Background="Red"/>
    </mux:NavigationView>
</Page>
```

**Expected behavior**
The settings icon should never render overtop navigation view items.

**Screenshots**

![Issue](https://user-images.githubusercontent.com/17993847/64929743-e6c3db00-d7f7-11e9-9b56-b2d7114d4d2e.gif)

**Version Info**

Windows: Windows 10 Home 1903 build 18362.239
NuGet package version: Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | N/A   |
| April 2018 Update (17134)          | N/A   |
| Fall Creators Update (16299)       | N/A   |
| Creators Update (15063)            | N/A   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   | N/A   |
| Xbox                      | N/A   |
| Surface Hub          | N/A    |
| IoT                         | N/A    |

**Comment by Felix-Dev** [comment] 2019-09-16 10:02
@robloo Seems like duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/591.

**Comment by robloo** [comment] 2019-09-16 15:24
@Felix-Dev Yes, you are right this is a duplicate. I'll have to search more carefully next time!

**Comment by jevansaks** [comment] 2019-09-16 17:06
@robloo don't sweat it. :) Thanks for confirming the duplicate.

**Closed by jevansaks** 2019-09-16 17:06 UTC
