### ISSUE TITLE
The ShouldConstrainToRootBounds property of the Popup doesn't work

### ISSUE THREAD

**Issue by alexdi220** [microsoft/microsoft-ui-xaml#5958] opened 2021-09-24 11:30 UTC
**Describe the bug**
How can I show a popup out of the window's bounds? The `ShouldConstrainToRootBounds` looks pretty good ([doc](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.popup.shouldconstraintorootbounds?view=winui-3.0#remarks)) but doesn't work and the `IsConstrainedToRootBounds` property always returns `true`

**Steps to reproduce the bug**
```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button Content="Click" Click="Button_Click"/>
        <Popup x:Name="popup" ShouldConstrainToRootBounds="False">
            <Border Width="100" Height="500" Background="Red" BorderThickness="3" BorderBrush="Black"/>
        </Popup>
    </StackPanel>
```
```csharp
    public sealed partial class MainWindow : Window {
        public MainWindow() {
            this.InitializeComponent();
        }
        void Button_Click(object sender, RoutedEventArgs e) {
            popup.IsOpen = !popup.IsOpen;
        }
    }
```

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47348109/134667281-19e55099-46fe-4623-8560-4ff1953b834c.png)

![image](https://user-images.githubusercontent.com/47348109/134667137-beed3db6-ff19-4bf3-9950-e7bf35c08d13.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |  Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by codendone** [comment] 2021-09-28 05:12
`ShouldConstrainToRootBounds="False"` is not yet supported in WinUI 3.

**Comment by alexdi220** [comment] 2021-09-28 06:17
Thanks, @codendone . Could you add a note\remark in the documentation about that?

**Comment by krschau** [comment] 2021-10-01 18:49
@gabbybilka Can we update the doc above to reflect that False is not yet supported? Thanks!

**Comment by gabbybilka** [comment] 2021-10-01 18:51
@krschau, yes!

**Comment by Samuel12321** [comment] 2021-10-29 21:30
@krschau why was this closed when it hasn't been fixed yet? 
`ShouldConstrainToRootBounds="False"` Still doesn't work in winui 3.

**Comment by krschau** [comment] 2021-10-29 22:20
@Samuel12321 We should be enabling this soon, although it won't be quite soon enough for the WinAppSDK 1.0 release. As I mentioned when I closed it, I think that since it's now appropriately documented, this particular issue can be closed. This doesn't mean that we aren't working on enabling the feature. 

I see pros and cons in closing or leaving issues open issues in situations like this, and we'll adjust if we see that the way we're doing it isn't helpful as we go forward.

**Comment by asklar** [comment] 2021-11-24 19:37
Tracked internally by https://task.ms/36484033

**Comment by Samuel12321** [comment] 2022-02-28 02:26
Will a fix for this be included for 1.1?

**Comment by codendone** [comment] 2022-03-01 03:00
@Samuel12321 Additional feature work was necessary to properly support ShouldConstrainToRootBounds=False. That work is in progress, but it looks like it won't be complete in time for 1.1.

**Comment by Samuel12321** [comment] 2022-04-26 06:51
@codendone is there any update as to when this issue will be fixed. Its currently blocking my team from using WINUI 3.

**Comment by codendone** [comment] 2022-04-28 23:43
@Samuel12321 Nothing new here from my previous comment: This unfortunately won't be enabled in 1.1. I'm hoping it will be in 1.2, but can't say for sure at this time.

**Comment by Samuel12321** [comment] 2022-06-23 06:59
@codendone is there any chance this will make it to one of the 1.1 servicing releases?
Sorry to bug, but this is a hugely problematic issue for my team and a few other projects I'm aware of.

**Comment by krschau** [comment] 2022-06-23 16:35
@Samuel12321 I expect this wouldn't be appropriate for 1.1 servicing, because behind the scenes this is a pretty substantial change. We understand it's a pretty huge pain point, though, and are actively working on it.

**Comment by HannesHold** [comment] 2022-07-08 19:42
Looking forward have such a functionality available for WinUI3 apps :)

**Comment by Samuel12321** [comment] 2022-08-20 12:19
@krschau Will this be part of 1.2?

**Comment by Samuel12321** [comment] 2022-09-21 00:13
@codendone @krschau will this be part of 1.2?

**Comment by codendone** [comment] 2022-09-21 02:25
@Samuel12321 Unfortunately this will not be in 1.2. Most of the implementation is complete, but there are a few critical issues which still need to be addressed.

**Comment by AlexanderBlackman** [comment] 2022-10-05 08:19
I really hope this'll come sooner rather than later.  It's probably the only feature I'd even use an experimental build for.

**Comment by AestheticalZ** [comment] 2023-01-23 05:06
Been almost 2 years since this issue was opened and it still hasn't been solved, even though apps like Files would benefit GREATLY from it. Is there any ETA or will there continue to be silence until someone else comes and complains about it?

**Comment by sylveon** [comment] 2023-01-25 06:41
I also agree. I am currently stuck on XAML Islands primarily because WinUI 3 doesn't implement this.

**Comment by yaira2** [comment] 2023-02-14 05:46
@gabbybilka are there any updates on this issue? It's one of the main issues we're having since migrating to WinAppSdk.

**Comment by TheXamlGuy** [comment] 2023-02-22 22:50
Will this ever be fixed?

**Comment by HannesHold** [comment] 2023-04-03 20:57
No Assignees, No Projects and No Milestones yet. - Quite a good time period passed and it's getting frustrating and it feels like writing into a void. - Is there someone out there who actually can help out about this?

**Comment by codendone** [comment] 2023-04-04 02:20
This continues to be a work in progress. It still isn't ready to be part of the upcoming 1.3 release, but the goal is to complete it for 1.4.

**Comment by yaira2** [comment] 2023-04-04 02:29
@codendone thank you for the transparency on the timeline. We've been waiting for a long time for this to be fixed and 1.4 is too far away, it's not the only issue we've had but most of the time we're able to work around them. This issue, however, doesn't have any known workarounds and it's one of the top frustrations for our user base.

I hope you can take this feedback into consideration and see if there is any way to increase the priority for getting this into a servicing release so that we don't have to wait for 1.4.

**Comment by andrezzzini** [comment] 2023-04-14 15:17
this feature is really missed.

**Comment by zhuxb711** [comment] 2023-04-14 16:05
1.3 fixed nothing important, most bugs reported to WinUI team is being ignored.

It's too inefficient and I hope .Net team could hand over the repo one day as they are very efficient and never delay their due date. For WinUI team: Oh it's too hard and let's arrange it to next release (Repeat it); For .Net team: Oh it's too hard let's gathering around to solve it!

Sorry for the complaints and that's what I thought to WinUI team with very disappointment.

**Comment by sylveon** [comment] 2023-04-14 21:07
WinUI is a C++ library not a .NET one.

**Comment by AlexanderBlackman** [comment] 2023-06-14 21:33
> This issue, however, doesn't have any known workarounds and it's one of the top frustrations for our user base.
Exactly.
The closest hypothetical workaround I've thought of is creating a new temporary window with just the menu options, but even that would be more trouble than it is worth. This has been an issue for years.

**Comment by Gaoyifei1011** [comment] 2023-07-08 07:07
> **Describe the bug** How can I show a popup out of the window's bounds? The `ShouldConstrainToRootBounds` looks pretty good ([doc](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.popup.shouldconstraintorootbounds?view=winui-3.0#remarks)) but doesn't work and the `IsConstrainedToRootBounds` property always returns `true`
> 
> **Steps to reproduce the bug**
> 
> ```
>     <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
>         <Button Content="Click" Click="Button_Click"/>
>         <Popup x:Name="popup" ShouldConstrainToRootBounds="False">
>             <Border Width="100" Height="500" Background="Red" BorderThickness="3" BorderBrush="Black"/>
>         </Popup>
>     </StackPanel>
> ```
> 
> ```cs
>     public sealed partial class MainWindow : Window {
>         public MainWindow() {
>             this.InitializeComponent();
>         }
>         void Button_Click(object sender, RoutedEventArgs e) {
>             popup.IsOpen = !popup.IsOpen;
>         }
>     }
> ```
> 
> **Expected behavior**
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/47348109/134667281-19e55099-46fe-4623-8560-4ff1953b834c.png)
> 
> ![image](https://user-images.githubusercontent.com/47348109/134667137-beed3db6-ff19-4bf3-9950-e7bf35c08d13.png)
> 
> **Version Info**
> 
> NuGet package version:
> 
> Windows app type:
> 
> UWP	Win32
> Yes
> Windows version	Saw the problem?
> Insider Build (xxxxx)	
> May 2021 Update (19043)	
> October 2020 Update (19042)	
> May 2020 Update (19041)	Yes
> November 2019 Update (18363)	
> May 2019 Update (18362)	
> October 2018 Update (17763)	
> April 2018 Update (17134)	
> Fall Creators Update (16299)	
> Creators Update (15063)	
> Device form factor	Saw the problem?
> Desktop	Yes
> Xbox	
> Surface Hub	
> IoT	
> **Additional context**

in windows app sdk 1.4-experimental 1 it is successfully work

**Comment by Samuel12321** [comment] 2023-07-08 09:35
Can we get some confirmation on whether this has been addressed in 1.4 experimental 1 from the wasdk dev team.

**Comment by Pietro228** [comment] 2023-07-08 11:53
Now it does work!

**Comment by ramjke** [comment] 2023-07-19 07:14
> In 1.4-experimental 1 it does work!

Confirmed. But there's a new problem. Now backdrop is also disabled when ShouldConstrainToRootBounds = False.

https://github.com/microsoft/microsoft-ui-xaml/issues/8657

**Comment by khoabui1412** [comment] 2023-08-04 03:48
MenuFlyoutItem doesn't have ShouldConstrainToRootBounds property, how to deal with that?

**Comment by sylveon** [comment] 2023-08-04 04:13
The property is on MenuFlyout itself

**Comment by khoabui1412** [comment] 2023-08-04 04:19
@sylveon, I tested but it doesn't work for MenuFlyoutItem though set ShouldConstrainToRootBounds=false in MenuFlyout

**Comment by khoabui1412** [comment] 2023-08-04 06:08
I clean the bin/obj, close vs and re-open, it's ok now.
sorry for make confused

**Comment by codendone** [comment] 2023-09-20 19:50
Closing as fixed in 1.4.

**Closed by codendone** 2023-09-20 19:50 UTC
Labels: team-Rendering, product-winui3, area-Popup
