### ISSUE TITLE
Inheriting from WinUI 2 Control in C++/WinRT results in compile issues

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#3485] opened 2020-10-25 20:34 UTC
**Describe the bug**

When inheriting from a MUXC control in MIDL, the compilation fails with errors like this:

```
Severity	Code	Description	File	Project	Line	Suppression State
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_VerticalCacheLength' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_VerticalCacheLength' ( Procedure 'put_VerticalCacheLength' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_Layout' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_Layout' ( Procedure 'put_Layout' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_ItemTemplate' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_ItemTemplate' ( Procedure 'put_ItemTemplate' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_ItemsSource' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_ItemsSource' ( Procedure 'put_ItemsSource' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_HorizontalCacheLength' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_HorizontalCacheLength' ( Procedure 'put_HorizontalCacheLength' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_Animator' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'put_Animator' ( Procedure 'put_Animator' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_VerticalCacheLength' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_VerticalCacheLength' ( Procedure 'get_VerticalCacheLength' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_Layout' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_Layout' ( Procedure 'get_Layout' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_ItemTemplate' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_ItemTemplate' ( Procedure 'get_ItemTemplate' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_ItemsSource' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_ItemsSource' ( Procedure 'get_ItemsSource' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_HorizontalCacheLength' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_HorizontalCacheLength' ( Procedure 'get_HorizontalCacheLength' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_Animator' ( RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL5015	[msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ Procedure 'get_Animator' ( Procedure 'get_Animator' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL2072	[msg]inapplicable attribute [context]: Windows.Foundation.Metadata.ExperimentalAttribute [ RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ( RuntimeClass 'RepeaterCompileCrash.BlankUserControl' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
Error	MIDL2072	[msg]inapplicable attribute [context]: Windows.Foundation.Metadata.ExperimentalAttribute [ RuntimeClass 'Microsoft.UI.Xaml.Controls.ItemsRepeater' ( RuntimeClass 'RepeaterCompileCrash.BlankUserControl' ) ]	D:\Projects\RepeaterCompileCrash\BlankUserControl.idl	RepeaterCompileCrash	5	
```

[RepeaterCompileCrash.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5435895/RepeaterCompileCrash.zip)

**Steps to reproduce the bug**

1. Create new C++/WinRT project
2. Add WinUI package and update pch.h
3. Create new control, inherit from a MUXC control in IDL
4. Compile project

**Expected behavior**

Project should compile just fine.

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml.2.5.0-prerelease.200923002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20241)              | Yes |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Issue found by @sylveon

**Comment by ranjeshj** [comment] 2020-10-26 23:17
@jevansaks any ideas ?

**Comment by jevansaks** [comment] 2020-10-27 01:29
This sounds like a MIDL bug that was already fixed but I don't remember the details. @BenJKuhn @DefaultRyan can you take a look? The IDL is simple:

```idl
namespace RepeaterCompileCrash
{
    [default_interface]
    runtimeclass BlankUserControl : Microsoft.UI.Xaml.Controls.ItemsRepeater
    {
        BlankUserControl();
    }
}
```

Was this one of the issues where it's a bug with /reference imports but not import statements with idls directly?

**Comment by robloo** [comment] 2020-10-27 19:57
The inheriting issue might be a broader problem. I discovered a bug over the weekend and it really doesn't work at all. Will file an issue right now.

**Comment by robloo** [comment] 2020-10-27 20:39
Also see #3499

**Comment by DHowett** [comment] 2020-11-13 18:44
Terminal just hit this attempting to _add a MUX type as a member_ to an idl.

```
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

namespace Microsoft.Terminal.Settings.Editor
{
    [default_interface] runtimeclass MainPage : Windows.UI.Xaml.Controls.Page//, Windows.UI.Xaml.Data.INotifyPropertyChanged
    {
        MainPage(Microsoft.Terminal.Settings.Model.CascadiaSettings settings);
        event Windows.Foundation.TypedEventHandler<Object, Microsoft.Terminal.Settings.Model.SettingsTarget> OpenJson;

        IInspectable CurrentPageName;
        Microsoft.UI.Xaml.Controls.NavigationView SettingsNav(); ////// <<<< line 13
    }
}
```

```
1>D:\Terminal\src\cascadia\TerminalSettingsEditor\MainPage.idl(13): error MIDL5015: [msg]the custom attribute argument contains a boolean value that is not valid [context]: enable [ RuntimeClass 'Microsoft.UI.Xaml.Controls.NavigationView' ( Parameter 'result' ) ]
```


(/cc @carlos-zamora)

**Comment by rectified95** [comment] 2021-06-21 22:49
@jevansaks Have there been any updates on that? We might be hitting this in RNW - trying to use the WinUI 2.6 Expander in a custom module.

**Comment by sylveon** [comment] 2021-06-21 22:54
I see a repeating pattern popping up: I find a bug in WinUI or the XAML compiler's C++ support, I file an issue, it stays basically unresponded for months, then several months later Windows Terminal or React Native also hits the same bug, and the bug never sees any activity or fix again.

Hopefully I can just go and fix them all myself once WinUI 3 goes open source 😭

**Comment by asklar** [comment] 2021-06-21 23:58
@rectified95 @DHowett 
- is the bug limited to inheriting from xaml types? sounds like it shouldn't be which seems...bad. 
- is this a recent regression? does it repro with the 18362 / 17763 SDK? or only 19041+? I remember seeing one other issue with custom attributes that only started to show up in 19041.
- if we suspect a bug in MIDL let's please file an internal bug to track since MIDL team won't necessarily track github issues.

**Comment by asklar** [comment] 2021-06-22 00:02
Filed https://task.ms/33886151

**Comment by DefaultRyan** [comment] 2021-06-22 18:34
Note, this is almost certainly MidlRT, not Midl. There has been a steady trickle of fixes to MidlRT since 19041 (which released in first half of 2020), but I'm not sure exactly if this would be affected by one of them. I suppose since @asklar is asking for checking older SDKs, I shouldn't get my hopes up that somebody has checked this against the latest preview SDK?

**Comment by DefaultRyan** [comment] 2021-06-22 18:52
I just re-read the original report and noticed it referred to Insider build 20241. There was a fix to MidlRT that might affect this that is available in 21348, I *think*. I don't suppose anybody has tried that?

**Comment by jevansaks** [comment] 2021-06-22 19:00
> I just re-read the original report and noticed it referred to Insider build 20241. There was a fix to MidlRT that might affect this that is available in 21348, I _think_. I don't suppose anybody has tried that?

@asklar if you're able to repro can you try that? 20344 is the newest insider SDK in the public right now so only internal folks can check this.

**Comment by asklar** [comment] 2021-06-22 23:57
@rectified95 and @amdingler just mentioned at standup that they are hitting this with 18362. 

I tried @chingucoding's app with 18362 and 19041 and was able to repro the midl error.
Then installed the private SDK from 22128 and it works!

We do have inheritance from WUX types with no problems, so this seems like a problem that might be specific to how MUX types are set up? Are there any workarounds folks could use until we ship a new SDK @DefaultRyan ?

**Comment by DefaultRyan** [comment] 2021-06-23 15:11
The issue is that MidlRT wasn't processing `[experimental]` attributes properly when reading winmd references. It processes them fine when reading a `import filename.idl` directive in IDL files. I'm guessing that WUX types don't present this problem because they don't have the `[experimental]` attribute in their winmds.

@JesseCol brought the issue to my attention originally, so he's more familiar with how to work around it.

**Comment by asklar** [comment] 2021-06-24 02:10
I think we want to ensure that MUX can be used with any SDK, not just the new unreleased one  :) So I think MUX needs to take a change here, maybe remove the experimental APIs from the public package until we figure out a way to fix this for everyone?

@jevansaks @ranjeshj

**Comment by jevansaks** [comment] 2021-06-24 02:23
We've had `[experimental]` types in every prerelease package since the beginning though -- what changed? Or what's special about these types?

**Comment by asklar** [comment] 2021-06-24 02:34
I suspect something changed in mux since this repros with older SDKs?

**Comment by jevansaks** [comment] 2021-06-24 02:36
@DefaultRyan can you grab the metadata out of older nuget packages (like 2.5 prerelease) and see what is new that is tripping up midlrt here? https://www.nuget.org/packages/Microsoft.UI.Xaml

**Comment by DefaultRyan** [comment] 2021-06-24 22:50
@jevansaks I downloaded the repro zip in the first message of this thread, and it references Microsoft.UI.Xaml v2.5.0-prerelease.200923002. There are two things tripping up MidlRT, both of which have been fixed internally:
- Importing winmds with `[experimental]` attributes, present in the prelease Xaml Nuget. As mentioned above, this fix was somewhat more recent, and should be present as of 21348, which isn't available yet. However, the `[experimental]` attributes are only present in the prerelease Nuget, and this issue goes away if you move to a stable Nuget, e.g. 2.5.0.
- Importing winmds with custom attributes with boolean fields. In this case, it's `Microsoft.UI.Xaml.CustomAttributes.MUXPropertyChangedCallbackAttribute`. MidlRT was fixed for this issue last year and was available as of build 20196. Targeting the publicly available preview SDK fixes this issue. If you wanted to workaround this issue in Xaml for all versions of MidlRT, you should be able to do so by changing that attribute field from a boolean to an integer.

So, as of today, customers can successfully build the repro project by using the public preview Windows SDK (currently 20344) and using a non-prerelease Xaml Nuget (e.g. 2.5.0 or 2.6.0). Also, I'm fairly confident both of these bugs only affect winmd importing - the legacy `import` IDL syntax should be unaffected.

**Comment by sylveon** [comment] 2021-07-08 06:53
Fixed in the 22000 SDK for me - this issue can be closed.

**Closed** 2021-07-08 07:01 UTC
Labels: team-Controls

**Comment by estebanm321** [comment] 2021-08-10 19:31
Are there any plans to add these fixes in for Windows 10/previous versions of the Windows SDK and Windows Universal Runtime?

**Comment by sylveon** [comment] 2021-08-10 19:35
The 22000 SDK can be used to target Windows 10 (and even Windows 7, provided you avoid any API that was introduced since then). Since it's purely a compile-time issue, there is no update required to the OS itself.

**Comment by estebanm321** [comment] 2021-08-10 19:59
I was able to get it to compile correctly on Windows 10 w/ the 22000 SDK, but when I try a deploy, I get an error telling me to update my OS, since the 'Windows Universal Runtime' also needs to be updated. Is it only possible to update that by going to Windows 11?

**Comment by sylveon** [comment] 2021-08-10 23:02
You need to keep the min target to something below 22000.

**Comment by estebanm321** [comment] 2021-08-10 23:37
Ah thanks, that worked!
