### ISSUE TITLE
Element binding not working in interactivity behavior of WinUI desktop project

### ISSUE THREAD

**Issue by KarthikRajaAKR** [microsoft/microsoft-ui-xaml#4057] opened 2021-01-29 08:31 UTC
**Describe the bug**
I'm trying to use ChangePropertyAction trigger using [Microsoft.Xaml.Behaviors.WinUI.Managed](Microsoft.Xaml.Behaviors.WinUI.Managed) package, but trigger not working.

So I have checked the issue by porting [XamlBehavior](https://github.com/microsoft/XamlBehaviors/tree/master/src/BehaviorsSDKManaged) code into my testing project and found that element binding value not updated to trigger.

**Steps to reproduce the bug**
Sample: [WinUIDesktopTestProject.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5891772/WinUIDesktopTestProject.zip)

1. Run the attached sample and change the first slider value
2. First Rectangle background should get updated but it's not. ( Slider value >= 50 => Green, else Transparent)
3. Change slider value of second slider, note second rectangle fill not updated.

Note: 
1. For first rectangle, Interactivity package behavior used
2. For second rectangle, locally integrated interactivity code used.

**Expected behavior**
Behaiors should trigger value based on condition.

**Screenshots**
NA

**Version Info**

NuGet package version: 
Microsoft.WinUI 3.0.0-preview3.201113.0
Microsoft.Xaml.Behaviors.WinUI.Managed - 2.0.3-rc4

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        |   |
| April 2018 Update (17134)          |   |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment] 2021-02-02 00:15
@michael-hawker Is this a Winui3 issue, a toolkit issue or perhaps the authors usage issue?

**Comment by michael-hawker** [comment] 2021-02-02 02:41
@StephenLPeters nothing to do with the Toolkit, the [XAML Behaviors are a different thing](https://github.com/Microsoft/XAMLBehaviors/). So, it's either an issue in WinUI 3 OR it's an issue with the WinUI 3 port of the Behaviors package (FYI @DVaughan @azchohfi). I just copied the code snippet from the provided sample into XAML Studio and was able to see the proper behavior, so the original UWP logic seems sound.

```xml
    ...
    xmlns:interactionCore="using:Microsoft.Xaml.Interactions.Core" 
    xmlns:interaction="using:Microsoft.Xaml.Interactivity">

        
        <Rectangle x:Name="DataTriggerRectangle" Grid.Row="1" Fill="Violet">
            <interaction:Interaction.Behaviors>
                <interactionCore:DataTriggerBehavior Binding="{Binding Path=Value, ElementName=slider}" ComparisonCondition="GreaterThan" Value="50">
                    <interactionCore:ChangePropertyAction TargetObject="{Binding ElementName=DataTriggerRectangle}" PropertyName="Fill" Value="Green"/>
                </interactionCore:DataTriggerBehavior>

                <interactionCore:DataTriggerBehavior Binding="{Binding Path=Value, ElementName=slider}" ComparisonCondition="LessThanOrEqual" Value="50">
                    <interactionCore:ChangePropertyAction TargetObject="{Binding ElementName=DataTriggerRectangle}" PropertyName="Fill" Value="Transparent"/>
                </interactionCore:DataTriggerBehavior>
            </interaction:Interaction.Behaviors>
        </Rectangle>
        <Slider x:Name="slider" Grid.Row="2" Value="1"/>
```

We do use the behaviors as well in the Toolkit, but not sure how extensively we've tested things using them yet. We leverage it more in our upcoming 7.0 release which is still being worked on.

@KarthikRajaAKR what changes did you make when you copied the code? Did you grab from their main branch or the branch they had setup for WinUI already?

**Comment by KarthikRajaAKR** [comment] 2021-02-02 05:56
Hi @michael-hawker,
I just copied code from the main branch and modified namespaces for WinUI from UWP.

**Comment by StephenLPeters** [comment] 2021-02-04 00:25
@michael-hawker I'm not sure I understand this issue, could you help me direct it to people who could answer better?  @MikeHillberg or @Austin-Lamb .

**Comment by michael-hawker** [comment] 2021-02-04 00:47
@StephenLPeters so if the only code change is the fact that something that works in UWP now doesn't in WinUI 3 this sounds like it's exposed an issue in the WinUI 3 preview. I think this may be is related [to this DevOps issue](https://microsoft.visualstudio.com/OS/_workitems/edit/31582150)? @alwu-msft looks like the same root cause? 

@azchohfi was your report sparked from this issue/discussion here? This'll effect our Animation story in the Toolkit as well, as we do similar patterns with attached behaviors and binding in our Sample App examples for XamlReader.

**Comment by azchohfi** [comment] 2021-02-04 02:18
I believe it is the Binding. @KarthikRajaAKR, could you try using x:Bind, and see if the issue persists?

I've reported this issue already, and apparently its a WinUI3 issue, and no @michael-hawker I didn't see this issue until now, but they seem like the same.

**Comment by KarthikRajaAKR** [comment] 2021-02-04 06:00
@azchohfi, thanks for the suggestion but **x:bind** also not working.

**Comment by chrisglein** [comment] 2021-02-16 23:32
It's hard to evaluate this as there's a stack of various previews involved (both WinUI and XamlBehaviors). @KarthikRajaAKR have you attempted to reduce the binding problem in question _without_ XamlBehaviors so we can verify if this is a WinUI3 issue or a WinUI3+XamlBehaviors issue?

There's been a fair number of bug fixes between preview3 and preview4. @DVaughan have we had a compatibility check between XamlBehaviors and preview4?

**Comment by michael-hawker** [comment] 2021-02-24 10:15
> @azchohfi, thanks for the suggestion but **x:bind** also not working.

FYI @alwu-msft thought this may have been the same issue as the DevOps one I linked to tracking, but in that one you said x:Bind should work which here it appears not to?

**Comment by alwu-msft** [comment] 2021-02-24 19:30
@michael-hawker If replacing `{Binding}` with `{x:Bind}` fails as well, then it's unlikely to be the same root cause as the DevOps issue since `x:Bind` doesn't rely on `FrameworkElement.FindName` (the moral equivalent of what an ElementName Binding does).

**Comment by Noemata** [comment] 2021-02-25 20:01
@michael-hawker , given this: https://github.com/microsoft/XamlBehaviors/issues/213

It doesn't look like XAML Behaviors has had much testing against WinUI 3.  I consider the EventTriggerBehavior/InvokeCommandAction essential and a must have in order to be able to port even trivial UWP applications to WinUI.

**Comment by Noemata** [comment] 2021-02-25 20:07
While I'm here, could we please add this to XAML Behaviors: https://github.com/Noemata/SimpleMVVM/blob/master/SimpleMVVM/SimpleMVVM/Behaviors/EventToCommandBehavior.cs

I've seen other Microsoft devs use this within their UWP App store projects, so it's only fair to include this in XAML Behaviors for everyone to benefit.

**Comment by michael-hawker** [comment] 2021-02-26 09:38
@Noemata you should open new issues for requests about adding a specific Behavior on the Behavior repo itself and not on a different bug thread in the WinUI repo.

@chrisglein the sample provided @KarthikRajaAKR contains a copy of the behaviors code within the project itself, so you can test just on top of WinUI itself.

@KarthikRajaAKR it wasn't clear from me in the report (and I can't seem to build the project at the moment) about if both scenarios failed or the local copy somehow worked? Can you clarify some of the details on the two scenarios, expected results, and screenshots in your bug report? Thanks!

**Comment by KarthikRajaAKR** [comment] 2021-02-26 11:05
Hi @michael-hawker,
Both scenarios are not working, I integrated the code just to check the issue. In both scenarios, I suspect that binding is the issue.

**Comment by Noemata** [comment] 2021-02-26 17:20
```
    <StackPanel x:Name="Stack" Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <i:Interaction.Behaviors>
            <ic:EventTriggerBehavior EventName="Loaded">
                <ic:InvokeCommandAction Command="{x:Bind StackPanelLoadedCommand}" CommandParameter="{Binding ElementName=Stack}"/>
            </ic:EventTriggerBehavior>
        </i:Interaction.Behaviors>
        
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
```

I traced through the XAML behaviors code with a WinUI project.  Here's a screenshot of the problematic code:

![image](https://user-images.githubusercontent.com/6632315/109332675-6dbe1500-782c-11eb-9566-341afafd58e7.png)

@michael-hawker , it's quite disappointing to see this sort of flaw slip through on WinUI 3 Preview 4.  This should be caught by automated testing before it gets out the door!

**Comment by Noemata** [comment] 2021-02-26 17:36
Looks like the binding expression -> CommandParameter="{Binding ElementName=Stack}" is broken in WinUI 3 Preview 4.

**Comment by Noemata** [comment] 2021-02-26 17:48
See the following for specific details: https://github.com/microsoft/microsoft-ui-xaml/issues/4057

**Comment by Noemata** [comment] 2021-02-26 18:17
x:Bind works -> CommandParameter="{x:Bind Stack}

**Comment by alwu-msft** [comment] 2021-03-08 20:09
This will be fixed in an upcoming preview of WinUI 3.

**Comment by Noemata** [comment] 2021-03-09 22:38
I did have a couple other binding expressions fail when running through a series of XAML Behaviors tests.  I didn't bother running those against the XAML Behaviors source code since it looked like there may have also been a XAML compiler problem, like here:

https://github.com/microsoft/microsoft-ui-xaml/issues/4092

Running against the XAML Behaviors unit tests should reveal any remaining issues, I hope ...

**Closed** 2023-08-04 12:01 UTC
Labels: area-Binding, team-Framework, product-winui3, no-issue-activity
