### ISSUE TITLE
TitleBar doesn't show Subtitle/Header/Content/Footer

### ISSUE THREAD

**Issue by Poker-sang** [microsoft/microsoft-ui-xaml#9694] opened 2024-06-05 09:29 UTC
### Describe the bug

TitleBar doesn't show the Header/Content/Footer. However when I set it in XAML Hot Reload it appears.

### Steps to reproduce the bug

```xml
<Window x:Class="App.MainWindow" ...>
    <Grid RowDefinitions="auto,*">
        <TitleBar
            x:Name="TitleBar"
            Title="312"
            Grid.Row="0">
            123
        </TitleBar>
    </Grid>
</Window>
```

```cs
public MainWindow()
{
    InitializeComponent();
    ExtendsContentIntoTitleBar = true;
    SetTitleBar(TitleBar);
}
```

### Expected behavior

Show the Header/Content/Footer

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/62325494/9b5cb416-4451-44ce-aba3-9614531ed93a)

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx)

### Additional context

WASDK 1.6

**Comment by ghost1372** [comment] 2024-06-05 10:19
Subtitle also does not shown, changing focus will display it.

**Comment by dotMorten** [comment] 2024-06-05 19:33
I'm seeing this behavior too:

https://github.com/microsoft/microsoft-ui-xaml/assets/1378165/b3c78f13-5771-4c22-9e95-c09de8b22d81

Looks like it's only functional with hotreload.

**Comment by riverar** [comment] 2024-06-05 19:37
I'm curious about how bugs like this make it into the experimental release. Can we review the process to see if there are any areas for improvement?

**Comment by ghost1372** [comment] 2024-06-05 20:29
> I'm curious about how bugs like this make it into the experimental release. Can we review the process to see if there are any areas for improvement?

It seems they used a different version in ms build And we're using an early version. As you can see [here](https://youtu.be/WR4T24lLoVo?si=_lxZw-OQ14U7MPgJ&t=827), the title bar works well in ms build.

**Comment by ranjeshj** [comment] 2024-06-06 01:43
A perf fix to delay load left the initial load broken. There is a workaround documented in the release notes. The issue is already fixed and will make it into the next release.
https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#new-titlebar-control

**Comment by riverar** [comment] 2024-06-06 01:51
A bit frustrating that Microsoft slipped this into the docs 5 hours ago and none of the involved parties thought to close the loop here. Thank you @ranjeshj for the heads up! https://github.com/MicrosoftDocs/windows-dev-docs/commit/465e1e155fe595c3d0093d850176cebdfa73809e

**Comment by ranjeshj** [comment] 2024-06-21 18:25
The fix is checked in, should be available in the next release.

**Closed by ranjeshj** 2024-06-21 18:25 UTC
Labels: bug, team-Controls, area-TitleBar
