### ISSUE TITLE
Runtime error: can't find Microsoft.UI.Xaml.Controls.XamlControlsResources

### ISSUE THREAD

**Issue by DRAirey1** [microsoft/microsoft-ui-xaml#1632] opened 2019-11-18 13:30 UTC
[old-merlin.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3865451/old-merlin.zip)
Runtime error:
System.TypeLoadException: Could not find Windows Runtime type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'.
   at ThetaRex.Merlin.UWP.App.OnLaunched(LaunchActivatedEventArgs launchActivatedEventArgs)

**Steps to reproduce the bug**
I had a working project on Friday.  On Sunday, I took several updated NuGet packages, but I couldn't tell you exactly which ones I took.

**Expected behavior**
It ran just fine before taking the new packages.

NuGet package version: 
Microsoft.UI.Xaml 2.2.190917002

**Additional context**
The error went away when I forced the pre-release, but I don't do pre-releases, so please fix the problem.

**Comment by DRAirey1** [comment] 2019-11-18 14:28
The problem definitely developed on the upgrade to Xamarin.Forms 4.3.0.991211

**Comment by jevansaks** [comment] 2019-11-19 18:30
@DRAirey1 Thanks for filing and narrowing down to the addition of XF. Can you share a solution project (either GitHub repo link or .zip attached to the issue description or comment) for us to repro locally and investigate?

**Comment by DRAirey1** [comment] 2019-11-19 18:34
I attached the project.  If you unzip it and upgrade to the latest Xamarin.Forms, then compile and run, you should see the error.

**Comment by jevansaks** [comment] 2019-11-19 18:35
Thanks!

**Comment by DRAirey1** [comment] 2019-11-20 23:15
This is a bigger problem that just me.  Open Visual Studio, create a new Mobile application with UWP.  Update the packages to latest.  Run.
It crashes with this error.  It's effecting new projects created from templates.

**Comment by kmahone** [comment] 2019-11-20 23:47
Ok, I think there are two issues here.

1. The app is not directly using Microsoft.UI.Xaml. It is directly using Xamarin.Forms. The older version of Xamarin.Forms (4.2.0.848062) does not depend on Microsoft.UI.Xaml, but the new one (4.3.0.991211) declares a dependency on M.U.X. (2.1.190606001). We previously had an issue in our nuget package where we were not handling these "transitive dependencies" where M.U.X. is indirectly required by the app. This was fixed by #1203, but this fix is not yet in 2.1. It will be in 2.3.

This issue would normally be fixed by adding the M.U.X. 2.1 nuget package directly to the app. However this fix is not resolving the issue for this particular app. I think there is a further issue:

2. The .props file included in the M.U.X. nuget package adds a \<AppxPackageRegistration\> for the different configurations. See [MUXControls-Nuget-FrameworkPackage.props](https://github.com/microsoft/microsoft-ui-xaml/blob/3fc68ffe48a5df30ba650811d1e94f145228421c/build/NuSpecs/MUXControls-Nuget-FrameworkPackage.props). It assumes that the app will be using these same set of configurations (Configuration=Release/Debug). However, the Merlin app is using a different set of values here. It is using Configuration=Local/Development.

It is possible to work-around issue 2 here by adding the AppxPackageRegistration directly to the app's proj file. I added this:

```
  <ItemGroup>
    <AppxPackageRegistration Include="$(NuGetPackageRoot)\microsoft.ui.xaml\$(MicrosoftUIXamlAppxVersion)\tools\AppX\x64\Release\Microsoft.UI.Xaml.2.1.appx">
      <Configuration>Development</Configuration>
      <Architecture>x64</Architecture>
      <Version>$(MicrosoftUIXamlAppxVersion)</Version>
      <Publisher>'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US'</Publisher>
    </AppxPackageRegistration>
  </ItemGroup>
```

This successfully worked around the issue. @DRAirey1, if you make these two changes to your app's proj file you should be able to avoid this problem. Once caveat is that it is important to make sure that the version of M.U.X. that your app references must match the version that Xamarin.Forms is depending on.

The first of these issues is already fixed in master. Once that is published (as M.U.X. 2.3) and once Xamarin.Forms updates to use 2.3, this problem will not longer be hit. 

For the second of these, I think we can probably resolve the problem by just removing the "Configuration" node from the <AppXPackageRegistration> from our props file. We don't do anything different between Release and Debug, so there is no reason to switch based on them.

**Comment by kmahone** [comment] 2019-11-21 01:42
I am trying out a fix for the second part of the issue by removing the \<Configuration\> element from the \<AppxPackageRegistration\>.

**Comment by DRAirey1** [comment] 2019-11-21 15:11
Perhaps I didn't explain the second problem: this bug occurs with a virgin Mobile project.  Just create a Mobile application and update the NuGet packages.  You can't expect everyone who want's to make a simple mobile app to have to debug this issue and monkey with the generated files.

**Comment by kmahone** [comment] 2019-11-21 17:27
@DRAirey1, I was not able to reproduce the problem with the new project. I used Visual Studio 2019 to create a new "Mobile App (Xamarin Forms)" and included UWP support. After upgrading all the nuget packages, the app continued to work. Could you share a zip of your project that demonstrates this problem so I can compare it with mine to see what is different?

>You can't expect everyone who want's to make a simple mobile app to have to debug this issue and monkey with the generated files.

I agree. The workaround that I shared was just a way to get unblocked. I am investigating to determine what the real fix to the shipped package needs to be so that the workaround is unneeded.

**Comment by DRAirey1** [comment] 2019-12-02 02:09
I can confirm that the problem is related to the configuration names.  If I take a virgin project and create a configuration called 'Local', it breaks with the message in the original post.

**Comment by kmahone** [comment] 2019-12-02 17:29
Thanks for the confirmation DRAirey1. I have made the fix for the Configuration problem in #1657 and the issue will be resolved in the next release of WinUI (2.3). Since Xamarin is currently using WinUI 2.1, this fix will not resolve the issue that you are seeing until Xamarin picks up the 2.3 release. You may want to create an issue on Xamarin's github that outlines your problem so that they pick up the 2.3 release once it is available.

In the meantime, you should be able to unblock your development using the workaround that I shared above. 

Thanks for reporting this issue.

**Closed by kmahone** 2019-12-02 17:29 UTC
Labels: area-NugetPackage, needs-assignee-attention, team-Controls

**Comment by DRAirey1** [comment] 2019-12-02 17:32
I can also confirm that screwing with the .csproj file fixes this problem, but you need an entry for every configuration (in my experience, it's not uncommon to find "Production", and "Development" configurations as well).

**Comment by kmahone** [comment] 2019-12-02 17:33
If you actually get rid of the Configuration tag entirely, you should be able to get away with only one entry per Architecture.
