### ISSUE TITLE
Editable combo box sets bound value to null when itemsource changes

### ISSUE THREAD

**Issue by SoggyBottomBoy** [microsoft/microsoft-ui-xaml#9573] opened 2024-04-23 01:53 UTC
### Describe the bug

I have an editable combo box which allows the user to select predefined items or set another item by typing in its name. The combox box ItemsSource is bound to a list of strings which is changed when action is taken by the user which changes the list of predefined strings. When the ItemsSources changes it appears that the SelectedItem is set to null. I am unable to re-type the same value, and clicking the drop down repopulates the value.

I'm pretty confused about what is going on...

### Steps to reproduce the bug

Create 2 editable combo boxes.
Have one 1 combo box ItemsSource rely on the value of the other.
Enter a value like "1" in the combo box.
Change the value of the other combo box to trigger a changes of the items source
The value in the editable combo box is replaced with null and "1" can not be entered.

### Expected behavior

For an editable combo box change the items source should not re-trigger the value bound to selected item or text to change.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmahone** [comment] 2024-05-09 22:24
I am having a hard time understanding the repro steps. Could you share some code and xaml that demonstrates the issue?

**Comment by SoggyBottomBoy** [comment] 2024-05-10 07:49
https://github.com/SoggyBottomBoy/EditableComboBoxBug
The second combox (bottom) is editable so enter in a value in the box, then change the section of the first box (top)

**Comment by kmahone** [comment] 2024-05-10 17:20
Thanks. I can reproduce the issue.

As you said, there are two issues here:
1. When the ItemsSource changes, it resets the selection of the ComboBox. This usually makes sense, but in the case of an editable combobox, it probably should not happen.
2. The inner TextBox of the ComboBox retains its old value. Normally when a user enters a value into the TextBox, the ComboBox will use that for the selection. But, it relies on the TextBox's TextChanging to trigger that. In this case, if the text does not actually change, it won't trigger that logic. So in order to select the old value, the user has to intentionally change it to something else and then change it back.

**Comment by SoggyBottomBoy** [comment] 2024-05-11 03:28
Yep but I think item 2 is somewhat solved by item 1. I would say an editable combox should be expected to retain the value if the ItemsSource is changed, if the developer does not want this behaviour then it should be an explicit opt in by handling ItemsSourceChanged or similar.

**Comment by karkarl** [comment] 2024-12-26 16:30
Resolving as dupe of #10232

**Closed by karkarl** 2024-12-26 16:30 UTC
Labels: bug, area-ComboBox, team-Controls
