### ISSUE TITLE
Setting SystemBackdrop without a content throws an exception

### ISSUE THREAD

**Issue by sotanakamura** [microsoft/microsoft-ui-xaml#8449] opened 2023-05-03 07:34 UTC
### Describe the bug

Setting `SystemBackdrop` before calling `InitializeComponent` throws an exception. `MicaBackdrop` is not instantiated.
If it is a specification, we need to document it.

### Steps to reproduce the bug

1. Create a WinUI 3 app project with a template
2. Set `SystemBackdrop` before `InitializeComponent` like the following code;

```cpp
    MainWindow::MainWindow()
    {
	SystemBackdrop(Microsoft::UI::Xaml::Media::MicaBackdrop());
        InitializeComponent();
    }
```

### NuGet package version

WinUI 3 - Windows App SDK 1.3.0: 1.3.230331000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by sotanakamura** [comment] 2023-05-03 08:31
#8139

**Comment by bpulliam** [comment] 2023-05-09 22:58
This is a duplicate of #8416 and that issue has been fixed in 1.3.1 (now available).

**Closed by bpulliam** 2023-05-09 22:58 UTC
Labels: bug

**Comment by bpulliam** [comment] 2023-05-10 00:47
1.3.1 = 1.3.230502000 (built May 2, 2023)

**Comment by sotanakamura** [comment] 2023-05-10 00:49
I checked it worked. Thanks!
