### ISSUE TITLE
WinUI3: NavigationView.IsPaneVisible is throwing error at specific instance.

### ISSUE THREAD

**Issue by mayurpaghdal** [microsoft/microsoft-ui-xaml#6715] opened 2022-02-14 13:11 UTC
### Describe the bug

So, I'm developing a WinUI3 app which requires client to Login to access the features.

To Accomplish the authorization, i have to hide the navigation pane of NavigationView.

But the app breaks when I set `NavigationView.IsPaneVisible = **false**`

### Steps to reproduce the bug

1. Login (NavigationPane Visible = **false**) 
2. MainPage (NavigationPane Visible = **true**) 
3. Access Features (Optional, not required)
4. Pane -> Go to Settings
5. Hit Logout (NavigationPane Visible = **false**)

**Step 1:**
So when i login and hit Logout (in settings page), it throws `ArgumentException`. I temporarily suppressed the exception to get my app POC running without issue. 

**Step 2:**
But here i found weird behavior of Navigation View, If I login again and goes to the same flow as described earlier -> it won't throw any exception when i logout again and would hide the navigation pane.

**Step 3:**
If I then do login again and goes to the same flow, this time it will again throw the exception.

Conclusively, it breaks on alternate IsPaneVisible = false.

### Expected behavior

No matter what number of times i switch the visibility of the Navigation pane. It must process it smoothly.

### Screenshots

![image](https://user-images.githubusercontent.com/23274856/153866119-cd82d483-251a-41ca-a827-f43ed6153165.png)
![image](https://user-images.githubusercontent.com/23274856/153866203-9df181c5-1b43-4469-90e5-7486fdf27689.png)
![image](https://user-images.githubusercontent.com/23274856/153869494-67ce8bcd-21ea-4692-b1b0-762d1197c5ea.png)
![image](https://user-images.githubusercontent.com/23274856/153870169-31970927-e7ff-4eb0-b73d-20b557cb4025.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Additional context

Windows version is: Win 11 (22000.493)

**Comment by kmgallahan** [comment] 2022-02-14 21:33
Looks like a dupe of #5971, which was supposedly fixed but I'm unsure which releases have the fix. @karenbtlai

**Comment by mayurpaghdal** [comment] 2022-02-15 06:43
@kmgallahan agree.. It's reported before already and seems it got fixed too. 

But still it;s causing the exception. I hop[e the details provided here could help.

**Comment by karenbtlai** [comment] 2022-02-15 18:20
Does the workaround provided solve the issue temporarily?

Also, it seems the fix is not included in any releases or pre-releases. @ranjeshj as FYI.

**Comment by mayurpaghdal** [comment] 2022-02-16 07:21
@karenbtlai 
For now, I've moved with an alternate option in the required app flow.Therefore, couldn't say exactly if the workaround works or not.

**Comment by StephenLPeters** [comment] 2022-03-04 22:15
@karenbtlai can you link the PR that fixes this?

**Comment by ismaelestalayo** [comment] 2022-04-18 13:01
Is there an update on this issue?
It is happening to me as well, but as the original issue #5971 said, it only happens in Debug mode, so while it's not a critical issue, it complicates debuggin some functionality of my app.

**Comment by MarkBrainfire** [comment] 2022-05-28 18:07
I'm experiencing an error when I attempt to set the IsPaneVisible property to false.
Work Around: If the desire is to take a page fullscreen, you can always assign the content of the parent window to the desired page.  This will require you to reassign the NavigationView to the content when exiting the fullscreen page view.

Here is the stack trace from the error message:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.INavigationView2.global::Microsoft.UI.Xaml.Controls.INavigationView2.set_IsPaneVisible(Boolean value)
   at Microsoft.UI.Xaml.Controls.NavigationView.set_IsPaneVisible(Boolean value)
   at RLE.NavigationSvc.NavigateTo(String displayedName, String toolTip) in C:\Users\Mark\BF\RLESolution\RLE\NavigationSvc.cs:line 76
   at RLE.NavigationSvc.NavigateTo(Object selectedItem) in C:\Users\Mark\BF\RLESolution\RLE\NavigationSvc.cs:line 60
   at RLE.NavigationSvc.SelectionChanged(NavigationView sender, NavigationViewSelectionChangedEventArgs e) in C:\Users\Mark\BF\RLESolution\RLE\NavigationSvc.cs:line 125
   at RLE.MainWindow.MainWindow_obj1_Bindings.<Connect>b__15_1(NavigationView p0, NavigationViewSelectionChangedEventArgs p1) in C:\Users\Mark\BF\RLESolution\RLE\obj\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\MainWindow.g.cs:line 121
   at WinRT._EventSource_global__Windows_Foundation_TypedEventHandler_global__Microsoft_UI_Xaml_Controls_NavigationView__global__Microsoft_UI_Xaml_Controls_NavigationViewSelectionChangedEventArgs_.EventState.<GetEventInvoke>b__1_0(NavigationView sender, NavigationViewSelectionChangedEventArgs args)
   at ABI.Windows.Foundation.TypedEventHandler`2.Do_Abi_Invoke[TSenderAbi,TResultAbi](Void* thisPtr, TSenderAbi sender, TResultAbi args)

**Comment by MarkBrainfire** [comment] 2022-05-28 18:46
Another workaround for hiding the NavigationView Panel is the following:

```
private void HidePanel()
{
    Nv.PaneTitle = string.Empty;
    Nv.AlwaysShowHeader = false;
    Nv.IsPaneToggleButtonVisible = false;
    Nv.OpenPaneLength = 0;
}
```

**Closed** 2023-08-05 11:19 UTC
Labels: area-NavigationView, team-Controls, no-issue-activity
