### ISSUE TITLE
Crashing when binding to control resources

### ISSUE THREAD

**Issue by takatsuka2022** [microsoft/microsoft-ui-xaml#9693] opened 2024-06-05 01:42 UTC
### Describe the bug

I want to dynamically change the color style of a control, so I bound a method that retrieves the color style to the control's resources. However, it crashes with a memory access violation.
 
Is this a bug? Or is there any workaround?
 
Please let me know. Thank you.

### Steps to reproduce the bug

[PageResourceTest1 1.zip](https://github.com/user-attachments/files/15572053/PageResourceTest1.1.zip)

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/100827114/6c2f979b-aad3-4b33-b7c0-b0a481f78dba)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment] 2024-06-13 16:50
What is the crash? Is it crashing in the generated code for the x:Bind? What step is it crashing on?

**Comment by takatsuka2022** [comment] 2024-06-14 00:44
Does the application crash when you run the attached test project? The app seems to crash because the binding target for Color is
nullptr.
<img width="890" alt="Error1" src="https://github.com/microsoft/microsoft-ui-xaml/assets/100827114/7c6481ed-ca86-4d6d-9226-f09d7a7cb51e">
<img width="1208" alt="Error2" src="https://github.com/microsoft/microsoft-ui-xaml/assets/100827114/392801ad-4136-4496-964b-730f868cc031">

**Comment by evelynwu-msft** [comment] 2024-06-18 01:39
@takatsuka2022 This is a duplicate of #5786. You can work around it by using `x:Name` instead of `x:Key` to declare the resource key.

**Closed by evelynwu-msft** 2024-06-18 01:39 UTC
Labels: bug, area-Binding, team-Markup
