### ISSUE TITLE
Unable to set XAML properties through x:Uid in WinUI 3 preview 1 (desktop)

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2657] opened 2020-06-14 06:22 UTC
**Describe the bug**

Defining a resource in resw as below
```
SettingsPage_General.Content	General	
```
and referencing it in the XAML is not working
```
            <NavigationViewItem x:Uid="SettingsPage_General" Icon="MusicInfo" />
```

**Steps to reproduce the bug**

1. See above

**Expected behavior**

Text in NavigationViewItem should be set from the resw file

**Screenshots**

**Version Info**
WinUI 3 preview 1

**Comment by huoyaoyuan** [comment] 2020-06-14 06:50
Duplicate of #2602

**Closed** 2020-06-14 07:02 UTC
Labels: needs-triage
