### ISSUE TITLE
WinUI Community Call: June 30, 2021 👨‍💻☎

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#5281] opened 2021-06-25 15:02 UTC
### Update (7/15/2021): The July WinUI Community Call has been cancelled - we'll see you in August, and feel free to [open up separate issues for your questions on this repo](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) or leave your comment in the [issue for the August call](https://github.com/microsoft/microsoft-ui-xaml/issues/5482) in the meantime. 

----

### https://youtu.be/9EOKxjFyY68

# Details
Date: Wednesday June 30, 2021
Time: 16:00-17:00 UTC (9:00-10:00am Pacific)

Anyone and everyone is welcome - no pre-registration is required.
This will be an informal interactive live stream directly with members of our engineering team.

# Format
The community call is a call among the WinUI team that is live-streamed onto YouTube. We present on new updates, share information, welcome guests, and answer your questions. In this month's call, we'll be doing a deep dive into the new WinUI 2.6 release and discussing roadmap plans for WinUI 3. 

### **Agenda (Tentative)**
- Intro 
- WinUI 2.6 deep-dive
- WinUI 3: roadmap updates, release channels, and developer experience
- Q & A
  - **Questions and topic requests can be pre-submitted by commenting them on this GitHub issue**
  - **Questions can be asked live in the YouTube livestream's comment section**

### **Q&A Code of Conduct**
- To help ensure Q&A remains beneficial for the majority of the call's developer audience, please consider whether your question could be framed so that it might be more broadly relevant to our larger developer audience by ensuring it is reasonably concise, broadly beneficial, well-suited for the fast-paced live Q&A format, or able to spark open ended discussion.  
- Please understand some questions are not well-suited for the fast-paced liacve Q&A format and should be filed as standalone [Discussion](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=discussion&template=discussion.md&title=Discussion%3A+%5Byour+discussion+title%5D) or [Question](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=question&template=question.md&title=Question%3A+%5Byour+question+here%5D) issues where they can be most appropriately handled. Excluding presentation topic requests, this generally includes requests for dedicated follow-ups or technically complex questions that require investigative time or expertise not included in this month's guest list.

### Leave us your questions in the comments on this issue or live in the YouTube chat during the stream!

**Comment by AathifMahir** [comment] 2021-06-25 15:51
Will the Windows App SDK and WinUI 3 support Mica or else it's part of the OS itself?

**Comment by mdtauk** [comment] 2021-06-25 17:32
**Widgets...**
- What are they?
- How can devs make them?
- What tech do they use? Web/HTML (like MSN News and Interests) and or Xaml (like GameBar Widgets)
- Do they have to be bundled with apps like with GameBar Widgets?
- Will Secondary and Live Tiles used in existing apps, become widgets on Windows 11 with the same XML or Image payloads?

**Comment by Tropix126** [comment] 2021-06-26 01:59
In what scenarios will Mica be practically utilized in XAML applications? Is it a replacement for background acrylic, or simply a suppliment? Additionally, it seems to be missing from xaml-controls-gallery. Is there an estimate on when it will be added?

**Comment by Tropix126** [comment] 2021-06-26 02:05
- To what extent will the new changes be backported to Windows 10? I know that they're at least functional, but many controls appear to be shaped around 11's new shell, most notably the rounded window surfaces. This can be seen in certain components like the `NavigationView` sidebar panel, which can look rather strange when viewing it from an installation of Windows 10.

**Comment by Tropix126** [comment] 2021-06-26 02:10
- Might not be a question suited for here, but with these new extensive changes to controls, are there plans to work with or attempt to recreate these styles on https://github.com/microsoft/fluentui? I am currently working on a component library for svelte which utilizes the new control styles, however the gap between XAML fluent and web fluent seems massive, almost to the point where they could be considered different design languages alltogether.

**Comment by jschwizer99** [comment] 2021-06-26 12:21
### Question for the Call
As a WinUI application developer with an external view, I currently see a growing issue backlog of open bugs. Within all these open tickets there are serious stability issues that strongly affect applications developed with the WinUI framework. A lot of these tickets are now open for many preview prelease cycles and get hardly any progress reported.

- Can you explain how the MS WinUI team prioritizes these bugs so that we users understand better how we can support the team?
- How do you plan to address the challenge of the growth in this backlog of open bugs? More resources? How can we application developers support you that we get these issues addressed in time?
- How to deal with tickets that report serious bugs but do not get any progress indication over several releases? An example is for e.g. the drag and drop issue https://github.com/microsoft/microsoft-ui-xaml/issues/4574#issuecomment-868716493. In this example, we got finally an outlook.

As a WinUI WinRT C++ application developer, I appreciate your efforts and I'm willing to spend time to support you to accelerate the progress. Many thanks!

**Comment by harvinders** [comment] 2021-06-26 23:01
It seems that the new style would only be available in WinUI 3 with windows app SDK 1.0. This seems too late. Are there any plans to bring it to WinUI earlier, so we can try it with our apps?

**Comment by Marv51** [comment] 2021-06-29 13:59
@harvinders I believe they have promised a preview of 1.0 (presumably with the latest changes from 2.6) in the coming weeks.

**Comment by Marv51** [comment] 2021-06-29 14:11
Can you speak about CsWinRT again? It seems responsible for a large number of the really critical bugs. The team seems super small and future of WinUI seems to depend on getting CsWinRT right. Is the feeling of the team that the backlog of major bugs is decreasing?

**Comment by artkat** [comment] 2021-06-30 02:28
**AppCenter support for WinUI 3?**
AppCenter plays crucial part in the development of our product. It allows us to track events, exceptions and crashes.
At the moment, AppCenter does not support WinUI 3.
With some creativity, like referencing System.Windows.Forms, you can get it to work partly.
App Crash info collection is something I cannot get to work (might be related to issue: https://github.com/microsoft/microsoft-ui-xaml/issues/5221).

**Comment by wbokkers** [comment] 2021-06-30 07:54
Please fix all crashes that cannot be handled ourselves. There are still too many of them. Out internal testers frequently complain about silent crashes. There is no way for me to analyze these crashes properly.

Also, please answer questions of @jschwizer99 and @Marv51 about this. 

We really need a stable product.

**Comment by wbokkers** [comment] 2021-06-30 07:56
@artkat I can get AppCenter to work with WinUI3 (Desktop) for events and exceptions, but it never reports crashes.

**Comment by Noemata** [comment] 2021-06-30 13:19
The Windows App SDK roadmap seems to be morphing relative to where the Project Reunion version was previously.  Mention of WinUI cross device support (HoloLens, XBox, Surface Hub, etc.) is getting harder to find?  There is more outward posturing that implies Winforms, WPF and MAUI are somehow part of the Windows App SDK story.  This is very confusing when WinUI is brought into the picture.  OS API level integration is one thing, UI integration thus far is only available via XAML Islands which is also getting less mention.  The UWP UI side of things appears to be getting more suppressed?  Bottom line, it is harder to tell what Microsoft will be spending its development dollars on.  It's great to see WPF get more attention.  Not so great to see UWP disappearing.  The sandboxed execution model had a lot of benefits.  Please state clearly if this is going away along with UWP.

**Comment by pjmlp** [comment] 2021-06-30 17:39
XBox kept being used as example during the call, yet the release of [Microsoft Game Development Kit (GDK)](https://github.com/microsoft/GDK), states otherwise.

Taking some content from their readme,

> Using Win32 + GDK is the primary, supported app model to build games for Xbox console, Xbox Game Pass (both Xbox and PC), and Xbox Game Streaming**.
...
>For developers building Xbox One games today, Win32 + GDK is a direct replacement for the WinRT-based Exclusive Resource Application (ERA) app model using the XDK, introduced on Xbox One; Xbox 360 developers similarly migrated to ERA in 2013.
...
> UWP apps and games are community-supported only; partners inside Xbox managed programs (Xbox, Xbox Game Pass, Xbox Game Streaming) should use Microsoft Win32 + GDK.

So when all pieces of the puzzle get put together it appears that UWP on the XBox is on the same extinction path as it happened with XNA on the XBox 360, so it would be nice that WinUI and XBox teams would talk with each other, and provide a clarification on the next community call.

**Comment by groovykool** [comment] 2021-07-02 16:51
UWP is on life support and then?

https://github.com/microsoft/microsoft-ui-xaml/issues/3639#issuecomment-872568286

**Comment by shaheedmalik** [comment] 2021-07-02 17:31
The fact they want to make a WinUI 2.7 instead of adding UWP to WinUI 3.1 means UWP is dead in the water.

**Comment by pjmlp** [comment] 2021-07-02 17:57
Anyone that was gone through VB6, Silverlight, Managed DirectX, XNA, C++/CX, Forms, knows quite well how to recognize the ramp down signs.

**Comment by mdtauk** [comment] 2021-07-02 18:04
UWP is not for making Windows or Xbox Games.

GDK is not for making Windows or Xbox Apps.

**Comment by robloo** [comment] 2021-07-02 18:12
@anawishnoff 

Are additional controls still going to be open sourced and added here to the WinUI library? i.e. Grid source code, CommandBar source code, etc. Or are all controls not already here going to remain in WinUI3-only indefinitely.

Is there still a plan to open source WinUI3? I kind-of expect that promise to be revoked at this point. All the warning signs are there.

**Comment by pjmlp** [comment] 2021-07-02 18:23
> UWP is not for making Windows or Xbox Games.

New around here?

https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-getting-started

**Comment by mdtauk** [comment] 2021-07-02 18:31
> > UWP is not for making Windows or Xbox Games.
> 
> @mdtauk New around here?
> 
> https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-getting-started

Of course it can be used to make games, only that it probably shouldn't be used for it.

WinForms could probably be used for making games, but would you _really_ want to?

**Comment by pjmlp** [comment] 2021-07-02 18:47
> > > UWP is not for making Windows or Xbox Games.
> > 
> > 
> > @mdtauk New around here?
> > https://docs.microsoft.com/en-us/windows/uwp/gaming/directx-getting-started
> 
> Of course it can be used to make games, only that it probably shouldn't be used for it.
> 
> WinForms could probably be used for making games, but would you _really_ want to?

Ah! So Microsoft has been playing with us after all!

https://www.pcgamer.com/microsoft-explains-how-windows-10-game-mode-will-improve-performance-in-uwp-and-win32-games/

**Comment by Shomnipotence** [comment] 2021-07-12 02:23
So at the end of this year or early next year, only WinUI 2.7 will be released, but WinUI 3 1.0, which was originally expected to be released in October, will be delayed to an uncertain time in the future?

**Comment by mrlacey** [comment] 2021-07-15 12:37
Is the data for the July call confirmed yet?
Is there an issue for then July2021 call that can be used to log questions? and should it be pinned in place of this?

**Comment by Lorymi** [comment] 2021-07-15 13:53
[.Net 6 + WinUI 3 + UWP](https://github.com/microsoft/WindowsAppSDK/discussions/1055)

**Comment by mrlacey** [comment] 2021-07-15 15:10
> Is the data for the July call confirmed yet?
> Is there an issue for then July2021 call that can be used to log questions? and should it be pinned in place of this?

As [the July call is canceled](https://twitter.com/WindowsUI/status/1415687731569733639), please can we have a pinned placeholder issue for the August meeting?

**Comment by anawishnoff** [comment] 2021-07-15 15:37
@mrlacey - Sure, just went ahead and created that here: #5482. I'll update this post with a link to it as well.

**Closed** 2021-11-23 19:55 UTC
Labels: discussion
