### ISSUE TITLE
In Install Shield License agreement hyperlink is not working

### ISSUE THREAD

**Issue by Mohan-Babblu** [microsoft/microsoft-ui-xaml#8189] opened 2023-02-16 05:52 UTC
Hey there, 

So i am using the Install Wizard for my application and i am trying to add my own licence agreement the content i can see , but the thing is like inside the content i have a link , whenever i try to click the link it is not working.

To Place the Content , I have added customized  Eula.rtf file.

When i try to add my own File:

![IMHpyerlink](https://user-images.githubusercontent.com/88727251/219279271-77d78a6d-b25f-4f09-a3f4-6e3a903afffb.PNG)

How can i fix this?
Thanks

**Comment by bpulliam** [comment] 2023-07-07 22:40
I'm not sure how this is a Xaml issue, but it may be a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6513

**Closed by bpulliam** 2023-07-07 22:40 UTC
Labels: needs-triage
