### ISSUE TITLE
Command Bar control text scaling issue

### ISSUE THREAD

**Issue by tashatitova** [microsoft/microsoft-ui-xaml#2879] opened 2020-07-10 19:45 UTC
Regression: Control Center footer add/remove buttons in edit mode look bad with text scaling
See item below:
https://microsoft.visualstudio.com/OS/_workitems/edit/26126908?src=WorkItemMention&src-action=artifact_link

**Comment by YuliKl** [comment] 2020-07-20 18:06
Closing because this is by design behavior.

**Closed by YuliKl** 2020-07-20 18:06 UTC
Labels: area-Commanding, team-Controls
