### ISSUE TITLE
StackPanel ActualWidth reports Wrong value

### ISSUE THREAD

**Issue by Jellomoldbrain** [microsoft/microsoft-ui-xaml#8270] opened 2023-03-10 08:51 UTC
### Describe the bug

ActualWidth reports window client width not width of Stack Panel
ActualHeight reports the same value, independed for window client size

### Steps to reproduce the bug

Create a Stack panel with a fixed width.  
Report ActualWidth of stackpanel in you favorite way. I used a text box and button to fill it with the stackpanel.ActualWidth.
Change the window size to less and more then size of stack panel width and observe the ActualWidth property.
the output is the window client width if under the fixed size of the stack panel.  If the window size is larger then the stack panel then the value is the fixed size.

The actualheight property is always the stack panel height, no matter the window size.

### Expected behavior

The ActualWidth and ActualHeight should be the size of the stack panel.

### Screenshots

![image](https://user-images.githubusercontent.com/17345045/224267338-8fc21f43-8a9a-425a-8ff5-10781bebae53.png)
![image](https://user-images.githubusercontent.com/17345045/224267590-8f327076-82b4-43d5-994d-81010f572efe.png)
![image](https://user-images.githubusercontent.com/17345045/224268339-19ac1fdd-90da-4598-b851-32def2e7e2f0.png)
![image](https://user-images.githubusercontent.com/17345045/224268470-cc63106e-fe42-4239-8a60-2c63109baa3f.png)

### NuGet package version

None

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Microsoft Visual Studio Community 2022
Version 17.5.0
VisualStudio.17.Release/17.5.0+33414.496
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

Visual C++ 2022   00482-90000-00000-AA781
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.5.317.37931
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.5.317.37931
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.5.317.37931
Azure Functions and Web Jobs Tools

C# Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22336.2
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.4.3 (main@2a4517a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

Linux Core Dump Debugging   1.0.9.33414
Enables debugging of Linux core dumps.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.5.9 (11975e6)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.0.33303.00
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.22336.2
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22336.2
Profiling support for Python projects.

Python with Pylance   17.0.22336.2
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.5.2.2307502+8b3141d86b738daf2ca3ed9c15b12513071fc676
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.2.40118.0
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   17.0.20105.2003
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.5.0-6.23109.5+6a5a63bbc9f4449d9bd1e95a8f9624939c3ccdc3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Cross Platform Mobile Development (Android)   17.0.33312.129
Visual C++ for Cross Platform Mobile Development (Android)

Visual C++ for Linux Development   1.0.9.33414
Visual C++ for Linux Development

Visual F# Tools   17.5.0-beta.23053.5+794b7c259d9646a7eb685dad865aa27da7940a21
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.5.0.173 (d17-5@33e727c)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.5.3.46 (remotes/origin/d17-5@e4dd80b2bb)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin.Android SDK   13.2.0.0 (d17-5/797e2e1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/main@149d70fe
    SQLite: xamarin/sqlite/3.40.0@fdc1e34
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@9f02d77

**Comment by sotanakamura** [comment] 2023-03-10 15:55
I cannot reproduce the bug.
```xaml
<StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center" Width="100">
    <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
</StackPanel>
```
```cpp
void MainWindow::myButton_Click(IInspectable const&, RoutedEventArgs const&)
{
    auto actualwidth = Content().as<Controls::StackPanel>().ActualWidth();
    myButton().Content(box_value(actualwidth));
}
```

**Comment by Jellomoldbrain** [comment] 2023-03-11 01:11
Do you shrink the width of the bounding app window to less then the size of the stack panel?
Ex..  the outer window width is appWindow.ClientSize().Width
      and I am reading the stack panel width with spMain().ActualWidth()

I create a larger stack panel which is about 600 pixels wide.
	<StackPanel
		x:Name="spMain"
		Width="Auto"
		Height="Auto"
		Margin="0,0,0,0"
		Padding="0,0,0,0"
		HorizontalAlignment="Left"
		VerticalAlignment="Top"
		Background="Gray"
		BorderThickness="0"
		Orientation="Vertical"
		RequestedTheme="Default"
		SizeChanged="spMainSizeChanged">

And I read it with...
        windowWidth = int(spMain().ActualWidth());

**Comment by sotanakamura** [comment] 2023-03-11 01:31
Please try my code and tell me what you expect.

**Comment by sotanakamura** [comment] 2023-03-12 00:59
If you ensure my code works well, please close the issue.

**Comment by Jellomoldbrain** [comment] 2023-03-12 22:21
Why dont you try my code.  I dont want to use the button as the size.  This bug is about the actual size of the STACKPANEL not producing the correct size output, NOT THE BUTTON.

**Comment by sotanakamura** [comment] 2023-03-12 23:21
> Why dont you try my code. 

I don't know how to try your code. Please share a minimal reproducible example shown in the following article.
[How to create a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)

Your code is not complete. The following code has a compile error and the width of StackPanel is not fixed, it dosen't follow the steps to reproduce the bug.

```xaml
	<StackPanel
		x:Name="spMain"
		Width="Auto"
		Height="Auto"
		Margin="0,0,0,0"
		Padding="0,0,0,0"
		HorizontalAlignment="Left"
		VerticalAlignment="Top"
		Background="Gray"
		BorderThickness="0"
		Orientation="Vertical"
		RequestedTheme="Default"
		SizeChanged="spMainSizeChanged">
```

A minimal reproducible example is like this;

```xaml
<StackPanel Width="600"/>
```

In this sample, ActualWidth of the StackPanel always returns 600.

>  I dont want to use the button as the size. This bug is about the actual size of the STACKPANEL not producing the correct size output, NOT THE BUTTON.

I used the button to display the StackPanel ActualWidth, not the Button ActulaWidth. I followed the steps to reproduce the bug.

1. Create a Stack panel with a fixed width. I set 100 as the width.
2. Report ActualWidth of stackpanel in you favorite way. I used button to display the StackPanel ActualWidth.
3. Change the window size to less and more then size of stack panel width and observe the ActualWidth property. The ActualWidth property returns always 100.

**Comment by sotanakamura** [comment] 2023-03-13 00:24
Based on your code snippet, the StackPanel has its width set to "Auto", which means its width will be determined by its content. This can cause the ActualWidth property to be unreliable, as it can change dynamically based on the content of the StackPanel.

To get an accurate value for the ActualWidth property, you may want to set the Width property of the StackPanel to a fixed value instead of "Auto". For example, you could try setting it to "600" to match the width of your StackPanel.

**Comment by Jellomoldbrain** [comment] 2023-03-13 03:55
ActualHeight works the way I expected.   It reports the height independent of whether the outside window is smaller and it is set to Auto. 
Have you tried my code?  Make a default project with a 500 x500 fixed size stack panel and test it.  Your code doesnt access the stack panel width and height values.   If you dont want to check it pass the bug on to someone that cares.

**Comment by sotanakamura** [comment] 2023-03-13 13:03
> Have you tried my code? 

I tried your code. It had a compile error. I added 2 lines at the bottom. This reproduces the bug. The StackPanel size is not fixed, but the content size is fixed.
```xaml
    <StackPanel
        x:Name="spMain"
        Width="Auto"
        Height="Auto"
        Margin="0,0,0,0"
        Padding="0,0,0,0"
        HorizontalAlignment="Left"
        VerticalAlignment="Top"
        Background="Gray"
        BorderThickness="0"
        Orientation="Vertical"
        RequestedTheme="Default"
        SizeChanged="spMainSizeChanged">
        <Rectangle Width="600" Height="600" Fill="Red"/>
    </StackPanel>
```
Someone can help you.

**Comment by sotanakamura** [comment] 2023-03-13 13:49
@Jellomoldbrain I believe this is a specification. To avoid this behavior, please set the Width property of the StackPanel to a constant value.

**Comment by JJBrychell** [comment] 2024-02-13 04:26
There appear to be two difference scenarios here, both of which are functioning as intended.

Scenario 1: StackPanel's explicit width exceeds the available space (e.g. wider than window).

`<Window>`
`    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center" Width="100">`
`        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>`
`    </StackPanel>`
`</Window>`

In this case, if the window is smaller than the 100 pixel width, the stack panel will continue to report an actual width of 100 pixels because, that is how big you told it to be.  Even though the stack panel was told there wasn't enough space during layout for all 100 pixels it still honors the requested width because it doesn't know what its parent is going to do with it.  In this case it will clip it, but it also could offset it some way (such as the way a scroll viewer would) to show different parts of it.

Senario 2: StackPanel width is not specified but its contents exceed the available space (e.g. wider than the window).

`<Window>`
`    <StackPanel>`
`        <Rectangle Width="600" Height="600" Fill="Red"/>`
`    </StackPanel>`
`</Window>`

Here if the window is smaller than the 600 pixel width, the stack panel will report the actual width of the window because that is how wide it is.  It was told during layout that there were less than 600 pixels available and since there are no specific instructions to override that (such as a width or a minwidth property), it will honor that and take up only as much space as it was told it could have.  The behavior of a stackpanel is to clip its children if needed.  So the children being 600 pixels wide is fine, the stack panel will be the size of the window and clip the excess parts of the children.

I have validated that both these scenarios are working as expected.

**Comment by DmitriyKomin** [comment] 2024-02-24 01:00
Closing per @JJBrychell's comments above.

**Closed by DmitriyKomin** 2024-02-24 01:00 UTC
Labels: bug, team-Controls
