### ISSUE TITLE
[WinUI][.NET 8] Class Library build failed with a warning NETSDK1206

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#8599] opened 2023-07-03 08:07 UTC
### Describe the bug

There is a warning after build Class Library (WinUI 3 in Desktop) project successfully with .NET 8.0.100-preview.6.23330.14.

Warning NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): win10-arm64, win10-x64, win10-x86. Affected libraries: Microsoft.WindowsAppSDK. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.

### Steps to reproduce the bug

**Environment:**
OS Version: Win11x64 & Win11-ARM64
VS Build: 17.7.0 Preview 3.0 [33901.74.d17.7]
.NET Version: .NET 8.0.100-preview.6.23330.14

**More info:**
This issue does not reproduce on .NET 6.

**Repro Steps:**
1. Make sure .NET SDK(Preview) and .NET 8.0 Runtime are installed from installer.
2. Add dotnet 8 feed: https://pkgs.dev.azure.com/dnceng/public/_packaging/8.0.100-preview.6.23330.14-shipping/nuget/v3/index.json
3. Create a Class Library (WinUI 3 in Desktop) project.
4. Update the TargetFramework to `<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>`
5. Save and Build

**Expected Result:**
Build successfully without error.

**Actual Result:**
There is a warning: NETSDK1206
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/adceea96-a252-409d-aa21-66ec10471f19)

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 11 (22H2): Build 22621

**Comment by michael-hawker** [comment] 2023-10-03 21:32
Is #8801 related?

**Comment by Scottj1s** [comment] 2024-01-03 17:48
Windows App SDK 1.4.4 will be released shortly and includes support for portable RIDs, so the UseRidGraph workaround will no longer be necessary.

**Comment by XamlTest** [comment] 2024-03-21 08:52
We tried on the latest VS(17.10 Preview 3) and latest Windows App SDK(1.5.240311000), the issue still repro with below steps:
1. Create Class Library (WinUI 3 in Desktop).
2. Build.

**Actual:** There is a Warning NETSDK1206.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/5d633894-6a3d-4b49-8b2b-ff6565667ecc)

**Comment by molesmoke** [comment] 2024-05-21 01:45
Still seeing this in v1.5.240428000

**Comment by jeremy-visionaid** [comment] 2024-06-12 02:01
Still present in v1.5.240607001

**Comment by dotMorten** [comment] 2024-08-08 17:31
The problem is that WinUI _requires_ you to set the runtime identifiers, even if you're building an AnyCPU class library.
We should _not_ be setting runtime identifiers in an anycpu class library, and the warning tells us about this. However the way that the Windows App SDK has been authored it incorrectly requires this.

**Comment by cheapw** [comment] 2024-08-26 09:12
Still present in v1.5.240802000

**Comment by codendone** [comment] 2024-09-30 20:07
I'm told this is fixed in WinAppSDK 1.6 (likely via the fix for microsoft/WindowsAppSDK#4597).

**Closed by codendone** 2024-09-30 20:07 UTC
Labels: bug, team-Markup, closed-Fixed, fix-released
