### ISSUE TITLE
Discussion: Memory leak in NavigationView even though I cleared the child page element while unloading.

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#5978] opened 2021-09-27 10:07 UTC
# Discussion: Why memory leak occurs while displaying a custom code snippets view in a NavigationView's child page.

## Describe the bug

While using the `NavigationView` control to navigate child pages, the child page's elements were cleared in its own unloading methods. But, the child pages retaining their memory after closing them.

### Steps to reproduce the bug

1. Open and build the sample [App8.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7235641/App8.zip) with x86 or x64 architecture.
2. To take a memory leak report, click the `Debug` menu item and select the `Performance Profiler` in Visual studio.
3. Select the` Memory Usage` check box and click `Start` button
4. Visual studio will start the diagnostic session and launching the application
5.  Click the `TakeScreenshot` button in the Visual Studio diagnostic session.
6.  Click on the `DemoList` Navigation Menu Item in the application.
7. Click on the `Code Snippets1` grid view item and its opens a code snippets page
8. Click on the `Back` app bar button
9. Repeat steps 7 and 8 for `CodeSnippets 2`and`CodeSnippets 3`
10. Click the `Empty Page` Navigation Menu Item.
11. Wait for 2 min and click the `Force GC` in the Visual Studio diagnostic session.
11. Click the `TakeScreenshot` button in the Visual Studio diagnostic session.
12. Then, click the `Stop Collection`

![ezgif com-gif-maker (9)](https://user-images.githubusercontent.com/57438309/134888697-2cac5e2b-95ad-4a41-b8b4-ed6917497a43.gif)

## Memory leak report:

![image](https://user-images.githubusercontent.com/57438309/134876824-66c651d0-168b-4d3b-bcc6-4a09d9f8927b.png)

![image](https://user-images.githubusercontent.com/57438309/134901063-63f50b59-4e2e-44ba-8d3f-9932ec67c9d4.png)

## Expected behavior

Memory should be the same or low as the initial screenshot.

### Version Info

NuGet package version: [WinUI 3 - Windows App SDK 0.8: 0.8.1]

### Windows app type

WinRT

### Windows version

October 2020 Update (19042)

**Comment by dylech30th** [comment] 2021-09-29 00:15
My case with this issue is more severe that what's inside the `GridView` is tons of `Image` each of which is bearing a `BitmapImage` as its source. And I found that the memory usage stays high even if I have cleared the item source of that `GridView` and confirmed multiple times that there are no other references to prevent the items from begin collected. I run both managed and native profiling several times and, initially, I thought this was a WinRT issue that the `BitmapImage` can't free up its resource correctly since the issue is immediately resolved once we changed the `BitmapImage` to `SoftwareBitmap` and handled the disposal of it manually.

**Comment by prabakaran-sangameswaran** [comment] 2021-11-12 15:16
Hi Team,

Any update on this?

**Comment by bogdan-patraucean** [comment] 2022-02-20 13:49
I have the same problem with .NET 6 and Windows App SDK 1.0. The memory is not released after I leave a page, and when I come back it's increasing with the amount needed for the page. If the memory needed for that page is 50 MBs, each time I navigate back and forth, it keeps increasing with 50 MBs. The page constructor is never hit.

Tried NavigationCacheMode=Disabled and IsNagivationStackEnabled=False, same problem
Tried to implement IDisposable, but not even that is hit when I leave the page, same problem
Tried Bindinds.StopTracking() on Page Unload event, same problem

**Comment by bogdan-patraucean** [comment] 2022-02-20 13:50
I have the same problem with .NET 6 and Windows App SDK 1.0. The memory is not released after I leave a page, and when I come back it's increasing with the amount needed for the page. If the memory needed for that page is 50 MBs, each time I navigate back and forth, it keeps increasing with 50 MBs. The page constructor is never hit. 
- Tried `NavigationCacheMode=Disabled` and `IsNagivationStackEnabled=False`, same problem
- Tried to implement `IDisposable`, but not even that is hit when I leave the page, same problem
- Tried `Bindinds.StopTracking()` on Page Unload event, same problem

**Comment by wbokkers** [comment] 2022-02-22 12:25
Even when NavigatioView is used with controls (and not with a Page), the memory used by these controls will not be released after closing the NavigationView.  I tested with the NavigationView in its own UserControl. On 'navigation', I set the Visibility of UI elements in a <Grid> to Visible and Collapsed. So no actual navigation occurs.
When I unload the NavigationView, the memory is not released.
I see users getting an out of memory exception quite often now that I use NavigationView in our app.

**Comment by Dimigergo** [comment] 2022-09-05 14:20
Any update?

**Comment by bogdan-patraucean** [comment] 2022-12-15 23:17
It should be fixed in the [latest ](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-12) WindowsAppSDK version. I tested navigating back & forth and it's indeed increasing the memory but for my app it stops at around 500 MB of RAM. As far as I know there is a cache limit until which no memory will be released, so probably that's why it's still increasing.

**Comment by l619534951** [comment] 2023-03-19 05:36
Is this issue not a high priority? "WinUI 3 Gallery" and "PowerToys" also has this problem(WinAppSDK: 1.2).

**Comment by vfib** [comment] 2023-04-24 22:36
Any news on this? Otherwise, where can I look to get updates for this? Created a WinUI 3 app with the template studio under win 11 and memory is increasing after each menu change. 
@bogdan-patraucean I might not be up to date in C# and .NET, but 500 MB full of items not needed sounds kind of unpleasent for me. Where are the times youd want a app that uses as little memory as possible?

**Comment by l619534951** [comment] 2023-04-25 00:39
@vfib memory usage still increase when more than 500 MB, but the growth will slow down. if you continue navigation, your app will crash. (tested with WinAppSDK 1.3)

**Comment by vfib** [comment] 2023-04-25 10:33
Yeah, there seem to be some problems with navigation right now. Offtopic, but setting a ThemeResource to create a card like stackpanel in settings page causes my app to crash after third navigation back and forth. But thanks for that workaround

**Comment by AdriaanLarcai** [comment] 2023-06-07 17:39
Years later this is still an issue from UWP days... Is this something that can actually be solved? Or should we rather undertake the massive effort to move our years-in-the-making application to a different platform?

**Comment by ranjeshj** [comment] 2023-10-09 22:43
We've made leak fixes in the recent 1.4 WASDK release. Please give the latest build a try and let us know if this is still an issue. Memory growth is expected until GC kicks in. If you see unbounded growth or leak in a native app, please let us know.

**Closed by ranjeshj** 2023-10-09 22:43 UTC
Labels: area-NavigationView, team-Controls, area-Performance, product-winui3, v0.8

**Comment by marwalsch** [comment] 2023-10-26 08:19
@ranjeshj 
I have updated to 1.4.231008000 and don't see any difference whatsoever. The GC barely cleans up anything at all. 
Memory build-up diminishes when approaching the 500 MB mark but it will inevitably overflow. This is still a huge issue and should be re-opened

**Comment by sude22** [comment] 2023-11-16 15:35
It really is a great misfortune that such a central function as navigation still does not work without errors. It is not possible to develop professional applications with the WinAppSdk in its current state. The memory leak in the navigation in combination with the use of the WebView2 control (a new instance is created with every page change) causes every application to crash after a few days of use.
I hate to think back to the day over a year ago when our team made the decision to build a new LOB application based on WinUI3.

**Comment by Sahil12524** [comment] 2024-03-07 09:35
> @vfib memory usage still increase when more than 500 MB, but the growth will slow down. if you continue navigation, your app will crash. (tested with WinAppSDK 1.3)
> 
> Powertoys can be used for testing, navigated to difference page many times, Powertoys will crash.
> 
> Temporary solutions is:
> 
> ```cs
> private void ContentFrame_Navigated(object sender, NavigationEventArgs e)
> {
>     System.GC.Collect();
> }
> ```

The official clock app 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42999635/26a1fcd5-26b4-47c5-97d8-d7282694de22)
is also crashing when navigating different pages. The memory never releases and getting increased again and again.
even settings of windows 11 is having memory leak 
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/42999635/0fededf1-c687-4d58-85be-75eece2b32dc)
the memory never gets freed!

**Comment by jeffintc** [comment] 2024-03-11 22:26
Is there any news on this? It still seems to be occurring with WinApp 1.5 (and .NET 8) with a sample app I created.

**Comment by LucaCris** [comment] 2024-05-22 13:32
Confirmed also with VS 17.10

**Comment by Tiktack** [comment] 2024-08-24 18:59
Still reproducible with latest WinUI3 Gallery. Spawning additional windows from "Multiple Windows" menu and closing them not releases memory to initial state. 3 years and issue still not addressed....
