### ISSUE TITLE
[NavigationView] FooterMenuItems show unwanted scrollbar

### ISSUE THREAD

**Issue by tipa** [microsoft/microsoft-ui-xaml#3771] opened 2020-12-04 21:21 UTC
**Describe the bug**
NavigationView FooterMenuItems show unwanted scrollbar

**Steps to reproduce the bug**
1. Add a `NavigationView `and add some `NavigationViewItem`s
2. Hover with the mouse over the right area of the FooterMenuItems area

**Expected behavior**
No Scrollbar when there's enough space

**Screenshots**
![image](https://user-images.githubusercontent.com/2863198/101215745-a19afb80-367e-11eb-8aa9-1d3bb735c7df.png)

NuGet package version: 
Microsoft.UI.Xaml 2.5.0

**Additional context**
Might have been introduced here: https://github.com/microsoft/microsoft-ui-xaml/issues/3447

**Comment by gabors** [comment] 2020-12-04 21:24
Just ran into the same thing :(

**Comment by Felix-Dev** [comment] 2020-12-04 21:45
Looks like we are missing
```xml
VerticalScrollBarVisibility="Auto"
```
here: https://github.com/microsoft/microsoft-ui-xaml/blob/624ee5a70b183e08523208f47519a4516560e8f0/dev/NavigationView/NavigationView.xaml#L493

**Comment by gabors** [comment] 2020-12-04 21:48
I did try this, but it has no effect, as soon as you hover around the right edge of the navigation view, the scrollbar shows up, only for footer menu items though.

```       <muxc:NavigationView 
            Grid.Row="1"
            x:Name="navigationView"
            PaneDisplayMode="Left"
            IsBackEnabled="False"
            IsPaneOpen="False"
            IsSettingsVisible="true"
            ScrollViewer.VerticalScrollBarVisibility="Hidden"
            ScrollViewer.VerticalScrollMode="Disabled"
            OpenPaneLength="224"
            Loaded="navigationView_Loaded" 
            ItemInvoked="navigationView_ItemInvoked"
            BackRequested="navigationView_BackRequested"
            >```

**Comment by Felix-Dev** [comment] 2020-12-04 21:54
@gabors We have to set the VerticalScrollBarVisibility mode on the *internal* scrollviewer used by the NavigationView for the footer menu items (you can see the internal scrollviewer in question linked above). 

As a "hotfix" (until a WinUI version has been released with this fix) you can walk the visual tree and obtain the linked internal ScrollViewer (named "FooterItemsScrollViewer") and set the `VerticalScrollBarVisibility` directly on the obtained scrollviewer instance. (Or you copy/paste the template into your project and set it in markup,)

**Comment by gabors** [comment] 2020-12-04 21:56
@Felix-Dev Appreciate your help, I'll walk the tree for now, hopefully this is fixed soon :)

**Comment by mdtauk** [comment] 2020-12-04 22:01
Is there a need for a
**<muxc:NavigationView BottomScrollViewer />**

as well as the 
<muxc:NavigationView ScrollViewer />

**Comment by StephenLPeters** [comment] 2020-12-05 00:14
Thanks for reporting this! I think we can probably get a patch for the release for this.

**Comment by Noemata** [comment] 2020-12-11 02:46
Looking at the source:

For the main section we have:

```
                                            <local:ItemsRepeaterScrollHost
                                                HorizontalAlignment="Stretch"
                                                VerticalAlignment="Stretch">
                                                <ScrollViewer x:Name="MenuItemsScrollViewer"
                                                    TabNavigation="Local"
                                                    VerticalScrollBarVisibility="Auto">
                                                    <!-- Left nav ItemsRepeater -->
                                                    <local:ItemsRepeater
                                                        x:Name="MenuItemsHost"
                                                        AutomationProperties.Name="{TemplateBinding AutomationProperties.Name}"
                                                        AutomationProperties.AccessibilityView = "Content"/>
                                                </ScrollViewer>
                                            </local:ItemsRepeaterScrollHost>
```

And for the footer it is:

```
                                            <!-- FooterItems -->
                                            <local:ItemsRepeaterScrollHost Grid.Row="3">
                                                <ScrollViewer x:Name="FooterItemsScrollViewer"
                                                        contract7Present:VerticalAnchorRatio="1">
                                                    <local:ItemsRepeater
                                                        x:Name="FooterMenuItemsHost"
                                                        AutomationProperties.AccessibilityView = "Content"/>
                                                </ScrollViewer>
                                            </local:ItemsRepeaterScrollHost>
````

There's no VerticalScrollBarVisibility="Auto" for the footer part.

I'm also miffed that this markup is now broken:

```
            <ui:NavigationView.PaneFooter>
                <StackPanel Margin="0,0,0,-30" >
                    <Rectangle Height="1" HorizontalAlignment="Stretch" Fill="Gray" Margin="0,0,1,0" />

                    <StackPanel Orientation="Horizontal" Margin="0,0,0,0">
                        <ToggleButton Style="{StaticResource ToggleButtonStyle}" cm:Message.Attach="[Event Click] = [Action ShowSetup()]" >
                            <FontIcon Glyph="&#xE115;"/>
                        </ToggleButton>
                        <TextBlock Text="Setup" VerticalAlignment="Center" Margin="8,0,0,0" />
                    </StackPanel>
                </StackPanel>
            </ui:NavigationView.PaneFooter>
```

I was using this to fix the floaty Settings button issue, but also to implement an alternate strategy for using Settings that allowed me to have a separate Setting view for each menu button.  You've now taken the option away. Given it used to work, it's an incorrect regression.

With 2.5, my custom footer is now occluded from input.  Please fix this ASAP!  Also have more exhaustive use cases for your tests.  What's in the sources is rather meek for the more complex controls such as this one.

**Comment by Alkanores** [comment] 2020-12-11 13:06
@Felix-Dev @gabors  can you show example how to fix this in C#/XAML?

**Comment by Noemata** [comment] 2020-12-11 13:47
Here are the desired behaviors:

On load ->
![image](https://user-images.githubusercontent.com/6632315/101910065-6f146580-3b8c-11eb-99ee-b329932c3df8.png)

Settings button selected ->
![image](https://user-images.githubusercontent.com/6632315/101910125-82273580-3b8c-11eb-985a-0fe05b28061a.png)

Notice how I disable the menu buttons, for certain scenarios this is more desirable.  Also, use of toggle Settings button makes it possible to have a different Settings pane for each menu item.

Full menu mode ->
![image](https://user-images.githubusercontent.com/6632315/101910392-df22eb80-3b8c-11eb-9ec2-5ad7a5f5d0f6.png)

Full menu setup deselected ->
![image](https://user-images.githubusercontent.com/6632315/101910488-fd88e700-3b8c-11eb-8e9e-30fe21da673b.png)

And here's the nonsense workaround due to the Footer bug

```
            <ui:NavigationView.PaneFooter>

                <StackPanel Orientation="Vertical" Margin="0,6,0,-48">
                    <Rectangle Height="1" HorizontalAlignment="Stretch" Fill="Gray" />
                    <Grid Margin="48,-2,0,0">
                        <TextBlock Text="Setup" Height="30" Margin="0,12,0,0" />
                    </Grid>
                </StackPanel>
            </ui:NavigationView.PaneFooter>

... further down to get past the occlusion bug

        <Grid VerticalAlignment="Bottom">
            <ToggleButton Style="{StaticResource ToggleButtonStyle}" cm:Message.Attach="[Event Click] = [Action ShowSetup()]" >
                <FontIcon Glyph="&#xE115;"/>
            </ToggleButton>
        </Grid>
```

Note, the above painful workaround should not be required if the NavigationView footer worked properly.

**Comment by Noemata** [comment] 2020-12-11 14:23
To be clear, I should be able to get my desired behavior with something like this:

```
            <ui:NavigationView.PaneFooter>

                <StackPanel Orientation="Vertical">
                    <Rectangle Height="1" HorizontalAlignment="Stretch" Fill="Gray" Margin="0,0,1,0"/>
                    <StackPanel Orientation="Horizontal">
                        <ToggleButton Style="{StaticResource ToggleButtonStyle}" cm:Message.Attach="[Event Click] = [Action ShowSetup()]" >
                            <FontIcon Glyph="&#xE115;"/>
                        </ToggleButton>
                        <TextBlock Text="Setup" VerticalAlignment="Center" Margin="8,0,0,0" />
                    </StackPanel>
                </StackPanel>

            </ui:NavigationView.PaneFooter>
```

**Comment by mfeingol** [comment] 2021-02-13 20:57
Is someone working on fixing this so we don't have to apply awkward workarounds that don't quite work?

**Comment by gabors** [comment] 2021-02-14 00:10
I would also like to know please when this is getting fixed.

**Comment by myokeeh** [comment] 2021-03-29 22:21
I'm also seeing this on the WinUI Controls Gallery app. This is version 1.2.27.0

![image](https://user-images.githubusercontent.com/3663297/112907220-5a5bcf00-90a2-11eb-8a9d-e2e10c8fefc1.png)

**Comment by HavenDV** [comment] 2021-05-19 06:48
Still exists in NuGet package Microsoft.UI.Xaml 2.6.0-prerelease.210430001.

**Comment by StephenLPeters** [comment] 2021-05-21 23:17
@beervoley and @chingucoding did we regress this again?

**Comment by chingucoding** [comment] 2021-05-21 23:18
Looking into this.

**Comment by gabors** [comment] 2021-05-21 23:42
Fwiw I tried all versions of this nuget as it was updated and it never worked right. That scrollbar always appeared.

**Closed** 2021-05-25 19:30 UTC
Labels: area-NavigationView, help wanted, needs-cherrypicktorelease, team-Controls, working on it
