### ISSUE TITLE
BackdropMaterial is not compatible with AppWindow

### ISSUE THREAD

**Issue by FrozenAssassine** [microsoft/microsoft-ui-xaml#6553] opened 2022-01-06 07:53 UTC
### Describe the bug

I've tried to create a multiwindow application with BackdropMaterial applied to all pages. When creating the second window using AppWindow appWindow = await AppWindow.TryCreateAsync(); the background of the window shows just the SystemAccentColor, but not the BackdropMaterial as expected.

### Steps to reproduce the bug

Create an AppWindow on button click with BackdropMaterial applied to MainPage.xaml:
```
AppWindow appWindow = await AppWindow.TryCreateAsync();
Frame appWindowContentFrame = new Frame();
appWindowContentFrame.Navigate(typeof(MainPage));
ElementCompositionPreview.SetAppWindowContent(appWindow, appWindowContentFrame);

await appWindow.TryShowAsync();
``` 

### Expected behavior

Both Windows should have the BackdropMaterial applied

### Screenshots

![PWOuA](https://user-images.githubusercontent.com/72889252/148347929-8694f233-e5bd-4719-a82c-8dd10ece061c.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by Link1J** [comment] 2022-01-10 18:27
Duplicate of #5370

**Closed** 2022-03-02 17:36 UTC
Labels: duplicate, area-AppWindow, needs-triage, team-Reach
