### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN crash on Application::Start with inappropriate SUBSYSTEM 

### ISSUE THREAD

**Issue by bdbai** [microsoft/microsoft-ui-xaml#2632] opened 2020-06-09 16:51 UTC
**Describe the bug**
STATUS_STACK_BUFFER_OVERRUN crash on Application::Start with inappropriate linker option `SUBSYSTEM`.

**Steps to reproduce the bug**

1. Create a Windows Console Application (C++/WinRT)
2. Write the following code in `main.cpp`
```c++
#include "pch.h"
#include <windows.h>
#include <winrt/Windows.UI.Xaml.h>

using namespace winrt;
using namespace Windows::Foundation;
using namespace Windows::UI::Xaml;

int main() {
	winrt::init_apartment();
	Application::Start([](auto&&) {});
	return 0;
}
```
3. Build and run the program
4. The exit code is `-1073740791`, which is `0xc0000409, STATUS_STACK_BUFFER_OVERRUN`
5. Go to project property, linker, system, set `subsystem` to `/SUBSYSTEM:WINDOWS`
6. Write the following code in `main.cpp`
```c++
#include "pch.h"
#include <windows.h>
#include <winrt/Windows.UI.Xaml.h>

using namespace winrt;
using namespace Windows::Foundation;
using namespace Windows::UI::Xaml;

int __stdcall wWinMain(HINSTANCE, HINSTANCE, PWSTR, int)
{
	winrt::init_apartment();
	Application::Start([](auto&&) {});
	return 0;
}
```
7. Build and run the program
8.  The exit code is no more `-1073740791`

**Expected behavior**
Throw a user-friendly error like `APPMODEL_ERROR_NO_PACKAGE`.

**Screenshots**
![image](https://user-images.githubusercontent.com/5270106/84175928-3bf4fa80-aab3-11ea-94ed-3fbb1c3f24d3.png)

**Version Info**
OS version: 1903 (build 18362.836)

NuGet package version: 
Microsoft.Windows.CppWinRT 2.0.200602.3
(Also reproducible with winrt-rs 0.7)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I understand this is a rare scenario that nobody would do, but STATUS_STACK_BUFFER_OVERRUN does not make sense anyway.

**Comment by kennykerr** [comment] 2020-06-09 17:04
This was first reported here: https://github.com/microsoft/winrt-rs/issues/214

The issue is that Xaml must report the invalid use of its API as a WinRT error so that languages with strong safety guarantees (like Rust) can make use of Xaml APIs.

Here is a minimal repro. The following C++/WinRT code should not crash but instead report some error message:

```C++
#include "winrt/Windows.UI.Xaml.h"

int main()
{
    try
    {
        winrt::Windows::UI::Xaml::Application::Start([](auto&&) {});
    }
    catch (winrt::hresult_error const& e)
    {
        printf("error: %ls\n", e.message().c_str());
    }
}
```

Instead, this code causes a failfast:

```
Windows.UI.Xaml.dll!00007FFF52667FC0: (caller: 00007FF759BC2F69) FailFast(1) tid(46fc) 8000FFFF Catastrophic failure
Unhandled exception at 0x00007FFF52667FC0 (Windows.UI.Xaml.dll) in scratch.exe: Fatal program exit requested.
```

**Comment by bdbai** [comment] 2020-06-09 17:40
`8000FFFF Catastrophic failure` was also observed when the debugger was attached.

**Comment by kennykerr** [comment] 2020-06-09 20:29
I had a closer look and it turns out that the failure in Xaml is as a result of a fail-fast operation, which is guaranteed to avoid unwinding and immediately terminate the process in a safe way. I spoke with @rylev and we have concluded that this does not violate Rust's safety principles. There may well still be a usability issue here in that the developer experience isn't all that great, but that's a matter for the Xaml team to consider.

**Comment by Austin-Lamb** [comment] 2021-01-05 18:17
It's expected that one needs /SUBSYSTEM:WINDOWS to use a GUI app (or you need to specify [w]WinMain() instead of main() so the linker detects that subsystem by default).

I don't think there's anything that needs to be done here, so I'm closing this issue.

**Comment by kennykerr** [comment] 2021-01-05 18:28
You don't ever expect a console app to use UI? That's pretty common. As an example, the official git client does that today (for authentication). All of the command line Sysinternals tools do as well (for licensing).

**Comment by Austin-Lamb** [comment] 2021-01-05 18:35
I hadn't thought of that scenario, it's an interesting one.  I usually think of GUI and console apps as two separate universes.

Thanks for bringing that one up, I'll reactivate this issue and leave it on the backlog, but it's low-priority at this time.

**Comment by sigmarsson** [comment] 2022-04-23 16:37
I witness this too. Is it related to `<WindowsPackageType>None</WindowsPackageType>` ?

`The program '[22112] Weather.History.Windows.Desktop.exe' has exited with code 3221226505 (0xc0000409).`

**Comment by n-mam** [comment] 2022-12-01 11:15
I am getting the same crash (Security check failure or stack buffer overrun - code c0000409 ) on starting a react native windows app directly by invoking it from the command line. The nested(actual) reason seems to be fast fail on non-supported launch as the below callstack suggests. From inside VS it launches fine. Why is an explicit exe launch "non-supported" method ? I just want to launch the app from inside windbg...

![image](https://user-images.githubusercontent.com/17683324/205038201-9fe56299-e6b7-414e-8f23-119651e8b31e.png)

**Comment by bdbai** [comment] 2023-07-29 17:04
not stale

**Comment by GuildOfCalamity** [comment] 2023-09-08 15:46
_[In the context of WinUI3 Apps]_
I ran into this recently while updating the **WindowsAppSDK** to **1.3.x**
I found that the fail-fast issue stops if I use these two in combination...
```
 <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.1" />
 <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.3.230502000" />
```
There definitely seems to be an issue once you take the SDK above 1.2.x

In the `App()` ctor I also experimented with `App.Current.DebugSettings.FailFastOnErrors = false;`, but I have no idea if this actually does anything.

**Comment by JesseCol** [comment] 2023-12-09 00:26
Hi, I see a few different things going on here.

For the OP -- thanks for filing this bug!  Unfortunately, we're making very few changes to System Xaml (Windows.UI.Xaml) right now so we can focus on WinAppSDK / WinUI3.  

For those asking about WinAppSDK / WinUI3, I tried this locally with WinAppSDK 1.4 and it appears to be working fine in a console app (with no failfast).  Note that to use WinAppSDK correctly, you'll either need to use the WinAppSDK [bootstrapper](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/tutorial-unpackaged-deployment?tabs=cpp) or use [self-contained deployment](https://learn.microsoft.com/en-us/windows/apps/package-and-deploy/self-contained-deploy/deploy-self-contained-apps).

Regarding the FailFastOnErrors property: it defaults to false, so I don't think setting it to false will have any effect.

I'm closing this one out, but feel free to add comments if I've missed something or you have questions.  Thanks!

**Closed by JesseCol** 2023-12-09 00:26 UTC
Labels: bug, needs-winui-3, team-Reach, Crash
