### ISSUE TITLE
[Winui package]Auto-Append suggestion not works correctly for data containing space in ComboBox

### ISSUE THREAD

**Issue by jeyakasipandi** [microsoft/microsoft-ui-xaml#8263] opened 2023-03-08 14:38 UTC
### Describe the bug

Auto append text does not work correctly in ComboBox.
For example, 
If type 'f' letter and give the datasource  in combobox with space in prefix like below
  this.SocialMedias.Add(" Facebook"); 
It appends Facebook with the whole selection and again types the 'a' letter the selection text gets removed.
Output:
It appends the text as like below image
![image](https://user-images.githubusercontent.com/92785406/223739034-a561d0a2-35cc-4f6b-94fd-ea1b3c9c79db.png)

### Steps to reproduce the bug

1. Run the below sample
**Replication sample**:[SuggestionSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10921531/SuggestionSample.zip)
2. Type 'f' letter in Combobox
3. It appends the 'facebook' text from the data source and selection applied to the whole text.

### NuGet package version

None

**Comment by sotanakamura** [comment] 2023-03-11 02:22
Why do you need prefix space? Please remove the space.

**Comment by jeya-kasipandi** [comment] 2023-03-13 10:05
The data comes from a web service over which we have no control. This is a list of strings. Any readable ASCII character, including space, might be included in this list.

**Comment by jeyakasipandi** [comment] 2023-03-13 10:10
The data comes from a web service over which we have no control. This is a list of strings. Any readable ASCII character, including space, might be included in this list.

**Comment by sotanakamura** [comment] 2023-03-13 10:21
I see. Can you remove the leading spaces before adding the string to controls using trim? https://learn.microsoft.com/ja-jp/dotnet/api/system.string.trimstart?view=net-7.0#system-string-trimstart

**Comment by DmitriyKomin** [comment] 2024-02-12 23:45
@jeyakasipandi, this looks like a dupe of #8516. We ended up looking at that one first and it now has additional context from @JJBrychell 's initial investigation, so will close this one.

**Closed** 2024-02-12 23:46 UTC
Labels: bug, area-ComboBox, team-Controls
