### ISSUE TITLE
How can I get HWND of the window in a C++ WinUI3 Application ?

### ISSUE THREAD

**Issue by Extrimis** [microsoft/microsoft-ui-xaml#5151] opened 2021-06-07 03:57 UTC
How can i get hwnd of the window in a C++ WinUI3 Application ?
In WinUI C# version i used this code :

```
[ComImport]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
[Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
internal interface IWindowNative
{
      IntPtr WindowHandle { get; }
}
```

and obtained hwnd using 

` var hwnd = this.As<IWindowNative>().WindowHandle;`

but how can i port it for WinUI3 C++ Application

_**Note: The handle should be obtained in MainWindow,xaml.cpp file and not in app.cpp file**_

**Comment by SelastinGeorge** [comment] 2021-06-07 04:00
I Got the answer from other issues:

#include <Microsoft.UI.Xaml.Window.h>

```
HWND GetHWNDFromWindow(winrt::Microsoft::UI::Xaml::Window const& window)
{
    HWND nativeWindow{ nullptr };
    winrt::check_hresult(window.as<IWindowNative>()->get_WindowHandle(&nativeWindow));
    return nativeWindow;
}
```

This solved my problem

**Comment by Extrimis** [comment] 2021-06-21 16:23
I am reopening this issue, i was able to get handle to a window, but if i need to get the handle of MainWindow in C++ WinUI3 what can i do?

**Comment by StephenLPeters** [comment] 2021-06-21 23:51
duplicate of #5230

**Closed by StephenLPeters** 2021-06-21 23:51 UTC
Labels: needs-triage, question
