### ISSUE TITLE
WinUI 3 apps keep running after closing window if swap chain is rendering

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#7153] opened 2022-05-27 00:34 UTC
### Describe the bug

I have a WinUI 3 app rendering frames onto a swap chain through a DX12 compute shader. The same exact code (as in, literally the same) works just fine in a UWP app with no issues ([full sample here](https://github.com/Sergio0694/ComputeSharp/tree/main/samples/ComputeSharp.SwapChain.Uwp)). When in a WinUI 3 app though, closing the window causes the app to keep running. After some investigation, it seems what's causing the app to keep running is the render thread in the swap chain, which isn't stopped because the `Unloaded` event for the panel is never raised when the window is closed, so it can't know it needs to stop rendering. Regardless though, this is the same on UWP, but the app still closes just fine there. On WinUI 3 instead, it just keeps running. Is this an issue with WinUI 3 or by design? I don't understand _what_ exactly is keeping the app alive. Is there a way to properly handle this, or is this just an issue that should be resolved on WinUI 3? I want to stress that this is not an issue on UWP at all, so for folks migrating, this is just a regression.

### Steps to reproduce the bug

1. Clone this minimal repro: https://github.com/Sergio0694/SwapChainWinUI3Repro
2. Launch the app
3. Close the window

The app will keep running.

To verify it's the swap chain rendering causing this, go into `App.xaml.cs` and uncomment line 15 with that `m_window.Closed` handler. That will cause the render loop to stop when the window is closed. Launch the app again, close the window.

### Expected behavior

The app should stop running when the window is closed.

**This works just fine with the same exact code on UWP, so it's a regression.**

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

Also tried with WinAppSDK 1.1.0-Preview3, same exact issue.

**Comment by dotMorten** [comment] 2022-05-27 00:41
What we really need for this scenario is this: https://github.com/microsoft/microsoft-ui-xaml/issues/674

**Comment by Sergio0694** [comment] 2022-05-27 00:50
That would be nice, but even without considering that, the fact this is not an issue at all on UWP is what annoys me.
If I close the window, I want my app to close, not to just keep running silently. This just seems like a WinUI issue to me.

**Comment by dotMorten** [comment] 2022-05-27 01:12
Win32 apps don’t require a window to run though. Or it could have multiple windows and your control might be in one that closes while another is still open - win32 doesn’t have the main window concept uwp has. IMHO the issue here is we can’t tell we need to shut down running threads based on unload, and not not whether a closing window kills your entire thread.

**Comment by pratikone** [comment] 2022-12-15 01:16
since this is duplicate of #7193 , i am closing this as duplicate and following further discussions there

**Closed** 2022-12-15 01:17 UTC
Labels: bug, needs-triage, team-Reach, area-Lifetime, product-winui3
