### ISSUE TITLE
CalendarDatePicker -> I can't to select a month after several attempts choosing new date

### ISSUE THREAD

**Issue by autour89** [microsoft/microsoft-ui-xaml#712] opened 2019-05-15 14:07 UTC
**Describe the bug**
I created a very simple UWP app with CalendarDatePicker control in xaml and faced with such behaviour as can't to choose month on Year display mode.
This thing randomly reproducible and somehow is relevant with hiding of Flyout after choosing new date which is implemented around CalendarView here.

**Steps to reproduce the bug**
1) open calendar date picker and switch to Year display mode
2) select new date on month display mode
3) make several attempts of this circle
In result : cannot choose month but I can with Tab press and focus on month by keyboard only.

Not found this issue running test proj on windows 10 version 1803 build 17134.706

**Expected behavior**
I want be able to select month as many I need it.

**Version Info**
Windows 10 version 1809 build 17763.437

NuGet package version: 
Microsoft.NETCore.UniversalWindowsPlatform 6.2.8

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |    |
| October 2018 Update (17763)   | Yes    |
| April 2018 Update (17134)        |  No    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes    |
| Mobile                   |   |
| Xbox                      |   |
| Surface Hub          |   |
| IoT                         |   |

**Additional context**
[TestApps.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3182822/TestApps.zip)

**Comment by chrisglein** [comment] 2019-05-16 17:55
Thanks for providing your sample code!

What's the scenario you're trying to accomplish? It looks like you have a CalendarDatePicker that is driving the visibility of another CalendarView in a Flyout... except that CalendarDatePicker already contains a CalendarView in a Flyout so I'm not sure what the purpose is of this second one. Can you give some more detail on your scenario?

**Comment by Alexandrapril** [comment] 2019-05-17 03:12
In second one I was looking for workaround this issue and wanted 
to demonstrate that not only CalendarDatePicker affected but also when you try to wrap CalendarView around TextBlock's atached flyout and control it's visibility, I'm able to reproduce it.

**Comment by jevansaks** [comment] 2019-09-25 17:31
Sorry for dropping the ball on this one. I tried the repro and I observe the problem. When this happens I also see that reveal hover stops working, implying that the element stopped getting pointer events. I suspect that the flyout isn't getting input routed to it correctly anymore. @gegao18 can you take a look?

**Comment by gegao18** [comment] 2019-09-25 19:14
I got the repro in a time travel trace. When the CalendarView is in a bad state, its XxxViewScrollViewer elements is marked with IsHitTestVisible="false", so we're skipping that entire subtree. The hit ends up landing on the BackgroundLayer grid.

0:000> !o 0x000001ed9cbcd5e0
DumpObject 0x000001ed`9cbcd5e0 Windows_UI_Xaml!CScrollViewer
  +0x018 m_strName                       : "DecadeViewScrollViewer"
  +0x08c m_fHitTestVisible               : 0 = False

@jevansaks can you have someone on the controls side take a look next? Was there a view transition animation that got interrupted, which left the current view marked as not hit test visible?

**Comment by jevansaks** [comment] 2019-09-25 22:28
Thanks @gegao18! Yeah we can take a look. I wouldn't have expected our code to be changing IsHitTestVisible at all though...

**Comment by humhei** [comment] 2019-11-24 09:02
can repro on xaml controls gallery

**Comment by Going-Gone** [comment] 2020-11-30 16:15
This is still occurring.

**Comment by stevoat8** [comment] 2022-06-15 11:03
Bug can still easily be reproduced in version 2.7.1. Will this ever be fixed? The bug makes this control pretty useless.

**Closed** 2023-08-04 11:59 UTC
Labels: bug, area-DateTimePickers, needs-winui-3, team-Controls, product-winui2, no-issue-activity
