### ISSUE TITLE
Add width, height, minimum height and minimum width property in the Window class

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/microsoft-ui-xaml#4781] opened 2021-04-10 09:42 UTC
Add properties to change the width, height, minimum height and minimum width of a WinUI 3 desktop or UWP app window.

**Comment by StephenLPeters** [comment] 2021-04-12 23:50
@marb2000 FYI

**Comment by marb2000** [comment] 2021-04-13 00:25
Thanks for opening this proposal @Jaiganeshkumaran, It's something that we want to add to the Window class when we finish first with the top blocker issues. Honestly, per the current engineering plan, I don't believe this will happen for Reunion 1.0 in Fall 2021. However, I have created this [sample](https://github.com/marb2000/DesktopWindow) that implements these behaviors.

**Comment by marb2000** [comment] 2021-04-13 00:27
Also, this is a dupe of #2731, so closing this request,

**Closed by marb2000** 2021-04-13 00:27 UTC
Labels: area-AppWindow, area-XamlWindow, duplicate, feature proposal, team-Reach, winui3preview
