### ISSUE TITLE
XamlControlsGallery "Editable Combobox" scenario crashes with invalid size

### ISSUE THREAD

**Issue by Scottj1s** [microsoft/microsoft-ui-xaml#4717] opened 2021-04-01 22:52 UTC
Repro steps:
Launch the "Editable Combobox" scenario 
Type a size directly into the combobox that doesn't exist in the dropdown list, eg: "13"
The app crashes

**Comment by Scottj1s** [comment] 2021-04-01 22:52
Call stack:

>	microsoft.ui.xaml.dll!CReentrancyGuard::CheckReentrancy(int bTerminateOnReentrancy) Line 54	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::OnReentrancyProtectedWindowMessage(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 774	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam, long * plRet, unsigned int * pbDoDefault) Line 706	C++
 	microsoft.ui.xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned int wParam, long lParam) Line 664	C++
 	user32.dll!AddClipboardFormatListener() + 82 bytes	Unknown
 	user32.dll![Frames below may be incorrect and/or missing, no symbols loaded for user32.dll]	Unknown
 	user32.dll!CallWindowProcW() + 5194 bytes	Unknown
 	user32.dll!CallWindowProcW() + 2898 bytes	Unknown
 	user32.dll!SetWindowsHookExAW() + 268 bytes	Unknown
 	user32.dll!SendMessageW() + 70 bytes	Unknown
 	microsoft.ui.xaml.dll!CXcpDispatcher::SendMessageW(unsigned int uMsg, unsigned int wParam, long lParam) Line 638	C++
 	microsoft.ui.xaml.dll!CXcpBrowserHost::SyncScriptCallbackRequest(void * pVoidBH, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *) pHandler) Line 732	C++
 	microsoft.ui.xaml.dll!CEventManager::RaiseHelper(xvector<REQUEST *> * pRegisteredRequests, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int bRefire, HRESULT(__stdcall*)(void *, CDependencyObject *, EventHandle, CDependencyObject *, CEventArgs *, int, IScriptObject *, HRESULT(__stdcall*)(CDependencyObject *, CEventArgs *)) pfnScriptCallback, unsigned int & bFired, CDependencyObject * pSenderOverride) Line 1061	C++
 	microsoft.ui.xaml.dll!CEventManager::Raise(EventHandle hEvent, int bRefire, CDependencyObject * pSender, CEventArgs * pArgs, bool fRaiseSync, bool fInputEvent, bool bAllowErrorFallback, CDependencyObject * pSenderOverride) Line 895	C++
 	microsoft.ui.xaml.dll!DirectUI::ComboBox::RaiseTextSubmittedEvent(Microsoft::WRL::Wrappers::HString & text) Line 4253	C++
 	microsoft.ui.xaml.dll!DirectUI::ComboBox::CommitRevertEditableSearch(bool restoreValue) Line 2454	C++
 	microsoft.ui.xaml.dll!DirectUI::ComboBox::OnPropertyChanged2(const PropertyChangedParams & args) Line 1331	C++
 	microsoft.ui.xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2240	C++
 	microsoft.ui.xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(CDependencyObject * pDO, const PropertyChangedParams & args) Line 2659	C++
 	microsoft.ui.xaml.dll!CFxCallbacks::DependencyObject_NotifyPropertyChanged(CDependencyObject * pDO, const PropertyChangedParams & args) Line 590	C++
 	microsoft.ui.xaml.dll!CDependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2795	C++
 	microsoft.ui.xaml.dll!CDependencyObject::SetEffectiveValue(const CDependencyObject::EffectiveValueParams & args) Line 1636	C++
 	microsoft.ui.xaml.dll!CDependencyObject::UpdateEffectiveValue(const CDependencyObject::UpdateEffectiveValueParams & args) Line 1902	C++
 	microsoft.ui.xaml.dll!CDependencyObject::SetValue(const SetValueParams & args) Line 1668	C++
 	microsoft.ui.xaml.dll!CUIElement::SetValue(const SetValueParams & args) Line 703	C++
 	microsoft.ui.xaml.dll!CFrameworkElement::SetValue(const SetValueParams & args) Line 232	C++
 	microsoft.ui.xaml.dll!CControl::SetValue(const SetValueParams & args) Line 106	C++
 	microsoft.ui.xaml.dll!CItemsControl::SetValue(const SetValueParams & args) Line 125	C++
 	microsoft.ui.xaml.dll!DependencyObject_SetValue(CDependencyObject * pObject, const SetValueParams & args) Line 2217	C++
 	microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueCore(const SetValueParams & args, bool fSetEffectiveValueOnly) Line 1034	C++
 	microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty * dp, IInspectable * value, bool setEffectiveValueOnly, BaseValueSource baseValueSource) Line 1372	C++
 	microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty * pDP, IInspectable * pValue) Line 248	C++
 	microsoft.ui.xaml.dll!DirectUI::DependencyObject::SetValueByKnownIndex(KnownPropertyIndex nPropertyIndex, IInspectable * pValue) Line 1107	C++
 	microsoft.ui.xaml.dll!DirectUI::SelectorGenerated::put_SelectedItem(IInspectable * pValue) Line 84	C++
 	[Managed to Native Transition]	
 	Microsoft.WinUI.dll!ABI.Microsoft.UI.Xaml.Controls.Primitives.ISelector.Microsoft.UI.Xaml.Controls.Primitives.ISelector.SelectedItem.set(object value) Line 39682	C#
 	Microsoft.WinUI.dll!Microsoft.UI.Xaml.Controls.Primitives.Selector.SelectedItem.set(object value) Line 9746	C#
 	XamlControlsGallery.dll!AppUIBasics.ControlPages.ComboBoxPage.Combo3_TextSubmitted(Microsoft.UI.Xaml.Controls.ComboBox sender, Microsoft.UI.Xaml.Controls.ComboBoxTextSubmittedEventArgs args)	Unknown
 	[Lightweight Function]	
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	System.Private.CoreLib.dll!System.Delegate.DynamicInvokeImpl(object[] args) Line 89	C#
 	Microsoft.Windows.SDK.NET.dll!ABI.Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.ComboBox, Microsoft.UI.Xaml.Controls.ComboBoxTextSubmittedEventArgs>.Do_Abi_Invoke.AnonymousMethod__0(System.Delegate invoke)	Unknown
 	WinRT.Runtime.dll!WinRT.ComWrappersSupport.MarshalDelegateInvoke<System.Delegate>(System.IntPtr thisPtr, System.Action<System.Delegate> invoke) Line 54	C#
 	Microsoft.Windows.SDK.NET.dll!ABI.Windows.Foundation.TypedEventHandler<Microsoft.UI.Xaml.Controls.ComboBox, Microsoft.UI.Xaml.Controls.ComboBoxTextSubmittedEventArgs>.Do_Abi_Invoke<System.IntPtr, System.IntPtr>(void* thisPtr, System.IntPtr sender, System.IntPtr args)	Unknown
 	[Native to Managed Transition]

**Comment by StephenLPeters** [comment] 2021-04-01 23:03
@Scottj1s any other info about the winui version or app model used?  @stmoy there was a XCG bug that was similar to this.  Could this be a dupe of that?

**Comment by gabbybilka** [comment] 2023-02-14 00:20
Closing as per status of task.ms/32337676

**Closed by gabbybilka** 2023-02-14 00:20 UTC
Labels: area-ComboBox, team-Controls, product-winui3
