### ISSUE TITLE
ItemsRepeater throws AccessViolationException when DataTemplate is empty

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#776] opened 2019-05-30 05:18 UTC
**Describe the bug**
I got AccessViolationException when return `new DataTemplate()` from `DataTemplateSelector`. `ListView` and `GridView` deals well with it by just rendering nothing, but ItemsRepeater throws Exception.

**Steps to reproduce the bug**
this code
```
<muxc:ItemsRepeater ItemsSource="{Binding SomeItems}">
    <muxc:ItemsRepeater.ItemTemplate>
        <DataTemplate/>
    </muxc:ItemsRepeater.ItemTemplate>
</muxc:ItemsRepeater>
```
throws AccessViolationException.

**Expected behavior**
Do not throw Exception, just don't render this item.

**Additional context**
My guess is that AccessViolation [appears here](https://github.com/microsoft/microsoft-ui-xaml/blob/40201afdcaa7bdc177d211e2b41ba103371aaa1d/dev/Repeater/ItemTemplateWrapper.cpp#L59) as selectedTemplate.LoadContent() returns null.

**Comment by micahl** [comment] 2019-05-30 05:28
Good find, thanks!

**Comment by chingucoding** [comment] 2019-09-18 11:03
I was unable to reproduce the issue with WinUI version 2.2.190830001. With the code provided in this issue, the ItemsRepeater just renders nothing just as expected.
I think this issue can be closed if we can not reproduce the bug.

**Comment by jevansaks** [comment] 2019-09-18 16:24
Thanks for trying the repro on latest bits, @chingucoding. @ad1Dima let me know if you still see this and we can reactivate.

**Comment by ad1Dima** [comment] 2019-09-19 08:23
It's stiil there. With provided sample...
Nothing [changed there ](https://github.com/microsoft/microsoft-ui-xaml/blob/40201afdcaa7bdc177d211e2b41ba103371aaa1d/dev/Repeater/ItemTemplateWrapper.cpp#L59)

**Comment by ad1Dima** [comment] 2019-09-19 08:25
> I was unable to reproduce the issue with WinUI version 2.2.190830001. With the code provided in this issue, the ItemsRepeater just renders nothing just as expected.

May be you had no items in your items source?

**Comment by ad1Dima** [comment] 2019-09-19 08:30
Please, try this solution: [ItemsRepeaterTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3630190/ItemsRepeaterTest.zip)

**Comment by chingucoding** [comment] 2019-09-19 08:35
> > I was unable to reproduce the issue with WinUI version 2.2.190830001. With the code provided in this issue, the ItemsRepeater just renders nothing just as expected.
> 
> May be you had no items in your items source?

My test, which resulted in no exception, was the following:
```xaml
    <muxc:ItemsRepeater ItemsSource="{Binding SomeItems}" x:Name="myItemRepeater">
        <muxc:ItemsRepeater.ItemTemplate>
            <DataTemplate/>
        </muxc:ItemsRepeater.ItemTemplate>
    </muxc:ItemsRepeater>
```
```c#
        public ObservableCollection<String> SomeItems;
        public MainPage()
        {
            this.InitializeComponent();
            SomeItems =  new ObservableCollection<string>();
            SomeItems.Add("some awesome string");
            SomeItems.Add("some awesome string");
            SomeItems.Add("some awesome string");
            SomeItems.Add("some awesome string");

            //myItemRepeater.ItemsSource = SomeItems;
        }
```
However when setting the ItemsSource again (though I already specified that in the XAML) the app crashes. My expectation was that since I used an ObersableCollection, the ItemsRepeater would notice that there are elements but apparentlyit does not. 🤔 

Thank you for your follow up on this issue. Since the issue is not fixed you can reopen it again. I will try to find a fix for this issue.

@jevansaks Is it expected that adding items to an ObservableCollection does not trigger that behaviour?

**Comment by ad1Dima** [comment] 2019-09-19 08:51
> Is it expected that adding items to an ObservableCollection does not trigger that behaviour?
ObservableCollection triggers only changes within collctions, not changes of SomeItems. So binding didn't know SomeItems was changed

**Comment by ad1Dima** [comment] 2019-09-19 08:52
I guess this code would work as you expect:

```
public MainPage()
{
    SomeItems =  new ObservableCollection<string>();
    this.InitializeComponent();
    SomeItems.Add("some awesome string");
    SomeItems.Add("some awesome string");
    SomeItems.Add("some awesome string");
    SomeItems.Add("some awesome string");
}
```

**Comment by chingucoding** [comment] 2019-09-19 08:58
> I guess this code would work as you expect:
> 
> ```cs
> public MainPage()
> {
>     SomeItems =  new ObservableCollection<string>();
>     this.InitializeComponent();
>     SomeItems.Add("some awesome string");
>     SomeItems.Add("some awesome string");
>     SomeItems.Add("some awesome string");
>     SomeItems.Add("some awesome string");
> }
> ```

Weirdly, this does not crash the application either.

**Comment by chingucoding** [comment] 2019-09-19 09:00
And neither does this:
```c#
        public MainPage()
        {
            SomeItems =  new ObservableCollection<string>();
            this.InitializeComponent();
            SomeItems.Add("some awesome string");
            SomeItems.Add("some awesome string");
            SomeItems.Add("some awesome string");
            SomeItems.Add("some awesome string");
            SomeItems[1] = "Text";
            Console.WriteLine(SomeItems[1]); // Prints "Text"
        }
```

**Comment by jevansaks** [comment] 2019-09-19 16:10
Re-opening to investigate further.

**Closed** 2019-09-24 15:55 UTC
Labels: area-ItemsRepeater, bug, working on it

**Comment by ad1Dima** [comment] 2019-09-25 06:52
There is another case, more useful: you can provide DataTemplateSelector that return empty DataTemplate for some datatype. PR #1358 doesn't consider that.

Should I open new issue?

**Comment by chingucoding** [comment] 2019-09-25 07:11
I think that would be better.

**Comment by ad1Dima** [comment] 2019-09-25 08:30
Hmm... Description of this bug already contains this case. I just made sample code simpler...

**Comment by ranjeshj** [comment] 2019-09-25 15:43
Is there a valid scenario with DataTemplateSelector ? What if one of the templates is empty and the other is not ? Should the empty template just insert items that take up no space ? If we do that then, we could end up de-virtualizing the entire list trying to fill the viewport.  I would like to understand the scenario with DataTemplateSelector and the expected behavior in different cases. Yes, opening a separate bug to discuss that would be best. I merged these changes in since the two fixes are independent. Thanks!

**Comment by ad1Dima** [comment] 2019-09-27 17:51
> What if one of the templates is empty and the other is not ? 
This IS The case. 
>Should the empty template just insert items that take up no space ?
ListView do this
>If we do that then, we could end up de-virtualizing the entire list trying to fill the viewport.
I guess this is aceptable
> Yes, opening a separate bug to discuss that would be best
Ok
