### ISSUE TITLE
The ContextFlyout.Opening event hooking of one TextBox was triggered for all TextBoxes in the application.

### ISSUE THREAD

**Issue by prabakaran-sangameswaran** [microsoft/microsoft-ui-xaml#5636] opened 2021-08-08 11:21 UTC
**Describe the bug**

If we hook the TextBox 's ContextFlyout.Opening event and do some contextflyout customization for that particular textbox , it was triggered for all TextBoxes in the application.

**Steps to reproduce the bug**

1. Run the [NumberBox-ContextMenu.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6950602/NumberBox-ContextMenu.zip) Sample 
2. Right-click on the `TextBox 2` or `TextBox 2` to open context flyout
3. `Select All` menu item not shown for the `TextBox 2` and  `TextBox 3` contextflyout
Note:  [We have removed the `Select All` option only for `TextBox 1` in its ContextFlyout.Opening event, but it also affects other textboxes too]

**Expected behavior**

ContextFlyout.Opening event should not triggered for `TextBox 2` and `TextBox 3`.

**Screenshots**

Expected output:
![image](https://user-images.githubusercontent.com/57438309/128630052-b33d964a-5988-4b5f-a073-0df316238791.png)

Current output:
![image](https://user-images.githubusercontent.com/57438309/128630023-862fcedd-2866-4773-b4e5-cef2dfb1342b.png)

**Version Info**

NuGet package version: 

[WinUI 3 - Windows App SDK 0.8: 0.8.0] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-08-10 23:30
It is by design that text box's all share the same ContextFlyout by default.  You have attached to that shared objects Opening Event. To get the bahavior you are looking for you can either look at the target of the ContextFlyout during the opening event and see if it is opening for the textbox you want to be special, or you can try attaching to the UIElement.ContextRequested event.  I think TextBox might mark this event as handled, so you may have to attach using AddHandler so that you can pass true to the parameter that lets you respond to handled events as well.

**Comment by StephenLPeters** [comment] 2021-08-10 23:30
Closing the issue, if this didn't answer your questions feel free to post back here.

**Closed by StephenLPeters** 2021-08-10 23:30 UTC
Labels: area-TextBox, team-Controls
