### ISSUE TITLE
Add Multiple Inline Items to Paragraph element crash app

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#7286] opened 2022-06-22 12:57 UTC
### Describe the bug

i want to add multiple inline items to Paragraph element, but i get error

```
Paragraph currentParagraph = new Paragraph();
            var listviewItems = quranListView.Items;
            foreach (var item in listviewItems)
            {
                var container = quranListView.ContainerFromItem(item) as ListViewItem;
                var richTextBlock = container.ContentTemplateRoot as RichTextBlock;
                var paragraph = (Paragraph) richTextBlock.Blocks?.FirstOrDefault();
                foreach (var inlineItem in paragraph.Inlines)
                {
                    currentParagraph.Inlines.Add(inlineItem);
                }
            }

```

but if use 
![image](https://user-images.githubusercontent.com/9213496/175033922-f8b0d784-a316-4e77-bbaa-da39cdbe769d.png)

### Steps to reproduce the bug

1.Create a new WinUI 3 app
2.create a listview with datatemplate
3. put richtextblock with paragraph and inline items
4. get listview items and find paragraph from datatemplate
5. try to add inline items to a new paragraph element

### NuGet package version

1.1.1

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by ghost1372** [comment] 2023-07-14 18:06
Just prevent closure

**Comment by JJBrychell** [comment] 2023-10-20 02:07
This is expected behavior.  The error being raised is actually AG_E_MANAGED_ELEMENT_ASSOCIATED which means that the element you are attempting to add to a parent, is already parented to a different element.  In this example, an Inline element is being retrieved from one paragraph and then an attempt is to add it into another.

There are two ways you might get around this.

The first is to remove the item from first paragraph before trying to add it to the new paragraph:
```
         while (paragraph.Inlines().Size())
         {
             auto inlineItem = paragraph.Inlines().GetAt(0);
             paragraph.Inlines().RemoveAt(0);
             currentParagraph.Inlines().Append(inlineItem);
         }
```
And the second is to duplicate the item:
```
         foreach(var inlineItem in paragraph.Inlines)
         {
            auto run = inlineItem.as<Run>();
            Run newRun;
            newRun.Text(run.Text());
            currentParagraph.Inlines.Add(newRun);
         }
```
It is regrettable that we don't have a better error message for this, but we already have several work items related to making that better.  So closing this as by design.

**Closed by JJBrychell** 2023-10-20 02:07 UTC
Labels: area-TextBlocks, team-Rendering, product-winui3, Crash, closed-ByDesign
