### ISSUE TITLE
Synchronous prompt on CustomScriptDialogOpening WebView2Bug

### ISSUE THREAD

**Issue by OMendozaG** [microsoft/microsoft-ui-xaml#8411] opened 2023-04-20 15:00 UTC
I'm developing a MAUI application in C# that implements a WebView2 and I need to change the style of the alert, prompt, and confirm dialogs. In WinUI applications everything is very modern, avoiding synchrony, but apparently only when it suits Microsoft, let me explain: If I do:

```
webView.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;
webView.CoreWebView2.ScriptDialogOpening += CustomScriptDialogOpening;
```

I can intercept the default JavaScript dialogs, but even if the CustomScriptDialogOpening function is async, the WebView doesn't await it.

So,

How the heck can I make a prompt if I can't await it, And there's no way to launch the user prompt window synchronously, and if I launch it asynchronously, WebView2 doesn't await it?

I don't know if this has a solution... Thank you!

### Steps to reproduce the bug

Create MAUI project with windows support.
Add webview.
Set AreDefaultScriptDialogsEnabled = false
add Event on ScriptDialogOpening 

### Expected behavior

EventHandler has to await their added handler events.

### NuGet package version

None

### Windows version

Windows Insider Build (xxxxx), Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

**Comment by OMendozaG** [comment] 2023-04-20 17:55
An example may not make much sense as it is a very simple problem, but I will try to explain it better:

In JavaScript, when you launch a prompt, it runs synchronously, stopping the JavaScript execution thread and returning the user's entered response. This is also applicable to confirm and alert.

If we access this PlatformView and use its "wb.CoreWebView2.ScriptDialogOpening" property, we can add an event listener that returns these prompt, confirm, and alert calls to C# code.

NOTE: To make it work and have the calls returned, you need to disable the default dialog execution with the "wb.CoreWebView2.Settings.AreDefaultScriptDialogsEnabled = false;" property.

Then, if you add a method to handle the events, you will see that we can do (I will give the example of prompt()):

```
wb.CoreWebView2.ScriptDialogOpening += async (CoreWebView2 sender, CoreWebView2ScriptDialogOpeningEventArgs e) => {
	if (e.Kind == CoreWebView2ScriptDialogKind.Prompt) {
		e.ResultText = await DisplayPromptAsync("title", "Question", "Cancel", "OK", "");
		e.Accept();
	}
}};
```

But the method, despite being async, is not awaited by the function that launches it.
If I don't make it async, I can't launch a Prompt to the user because the main thread is busy waiting for the prompt response in the WebView, so it is never processed.

This makes it practically impossible to display a custom Prompt to the user.
If you need more information, I can provide it.

**Comment by DmitriyKomin** [comment] 2023-11-06 23:48
The description suggests the issue is Edge/CoreWebView2 and should be moved to [WebView2Feedback](https://github.com/MicrosoftEdge/WebView2Feedback). @champnic can you take a look?

**Comment by champnic** [comment] 2023-11-07 00:59
Hey @OMendozaG - To block the script execution until you are ready with a response, please use the Deferral mechanism of the event args, `CoreWebView2Deferral deferral = e.GetDeferral();`:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2.scriptdialogopening?view=webview2-dotnet-1.0.2151.40#remarks
https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.core.corewebview2scriptdialogopeningeventargs.getdeferral?view=webview2-dotnet-1.0.2151.40#microsoft-web-webview2-core-corewebview2scriptdialogopeningeventargs-getdeferral

And then continue the script execution by completing the deferral, `deferral.Complete();`.

**Comment by DmitriyKomin** [comment] 2024-02-08 01:58
Closing as the behavior is expected as per @champnic's comment above.

**Closed by DmitriyKomin** 2024-02-08 01:58 UTC
Labels: bug, area-WebView, team-Rendering
