### ISSUE TITLE
The content dialog box cannot be overridden to the title bar

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#7284] opened 2022-06-27 08:34 UTC
### Describe the bug

When Winui3 uses the Windows Chrome style, the content dialog cannot be overridden to the title bar

![image](https://user-images.githubusercontent.com/49179966/175896444-c250035a-7080-40a7-a4eb-624e92bcd6f2.png)

### Steps to reproduce the bug

Clicking on any one of the contents dialog boxes will appear

### Expected behavior

Like Winui2, the title bar can be extended when using the Windows Chrome style
![image](https://user-images.githubusercontent.com/49179966/175895919-5b5a2ba7-a142-4360-b828-944c6087261f.png)

### Screenshots

![image](https://user-images.githubusercontent.com/49179966/175896444-c250035a-7080-40a7-a4eb-624e92bcd6f2.png)

### NuGet package version

1.1.1

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Insider Build (xxxxx)

### IDE

Visual Studio 2022

### Additional context

Hope to fix the bug in next version

**Comment by krschau** [comment] 2022-06-29 20:40
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6534

**Closed** 2022-06-29 20:41 UTC
Labels: team-Reach, product-winui3, area-TitleBar
