### ISSUE TITLE
Publishing WinUI 3 in Desktop package fails

### ISSUE THREAD

**Issue by noffett** [microsoft/microsoft-ui-xaml#5340] opened 2021-07-01 14:08 UTC
**Describe the bug**

Not able to publish an app installation package when creating a project from the _Blank App, Packaged (WinUI 3 in Desktop)_ template.

**Steps to reproduce the bug**

1. Create a new project using the _Blank App, Packaged (WinUI 3 in Desktop)_ template
2. Right click the Package project and select Publish -> Create App Packages
3. Choose Sideloading, uncheck Enable automatic updates, click Next
4. Select certificate, click Next
5. Select build config, click Create

**Expected behavior**

App installation package should be created

**Screenshots**

![image](https://user-images.githubusercontent.com/26929135/124131587-3f717000-da80-11eb-9332-7abee101330b.png)

A suggested solution to the problem gives me the following:
![image](https://user-images.githubusercontent.com/26929135/124131866-80698480-da80-11eb-8d26-c092a59c9dc7.png)

**Version Info**

NuGet: Microsoft.ProjectReunion 0.8.0
OS: 10.0.19041

NuGet package version: 

Microsoft.ProjectReunion 0.8.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-07-01 23:19
This should be supported.. @alwu-msft do  you see what is wrong?

**Comment by alwu-msft** [comment] 2021-07-01 23:25
Duplicate of #5248.

**Closed by alwu-msft** 2021-07-01 23:25 UTC
Labels: ProjectReunion 0.8, area-Tooling, needs-triage, team-Markup, winui3preview
