### ISSUE TITLE
ContentDialog does not respect ContentDialogMaxWidth

### ISSUE THREAD

**Issue by XamlBrewer** [microsoft/microsoft-ui-xaml#1686] opened 2019-11-27 18:23 UTC
**Describe the bug**
From WinUI v2.3pre on, it looks like ContentDialog does not respect ContentDialogMaxWidth setting anymore. It stays a lot smaller than in v2.2.

**Steps to reproduce the bug**
Download an run the XamlFlix sample from https://github.com/XamlBrewer/UWP-ItemsRepeater-Sample.

Click on a movie and press any of the commands button to start the trailer. It looks like this:
![ContentDialogv22](https://user-images.githubusercontent.com/9828352/69749155-2be68080-114a-11ea-9a9e-f15bea2ae0ca.png)
The dialog is large, because of the ContentDialogMaxWidth setting in app.xaml.

Now upgrade the WinUI NuGet package to v2.2prerelease and run the app again. The ContentDialog suddenly looks like this:
![ContentDialogv23Pre](https://user-images.githubusercontent.com/9828352/69749226-51738a00-114a-11ea-9bea-8dfdc53fcf48.png)

It looks like it's ignoring the ContentDialogMaxWidth setting now. It has taken the new v2.3 styles however (rounded corners everywhere).

**Expected behavior**
I would expect the dialogs to keep the same size after an upgrade.

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment] 2019-11-27 19:00
Thanks for reporting @XamlBrewer! @kaiguo said he could take a look.

**Comment by kaiguo** [comment] 2019-11-27 19:34
We had issues with app level resource overriding earlier, this might be related to #1486, which also assigned to me. This probably won't be a quick simple fix, I'll do some more investigation and update the thread when I have new findings.

**Comment by kaiguo** [comment] 2020-01-28 19:50
This is caused by a broader issue/limitation in our framework, app level resource overriding doesn't work as expected. I'll close this issue and use #1486 to track, which is assigned to framework team.

**Closed by kaiguo** 2020-01-28 19:50 UTC
Labels: area-UIDesign, bug, team-Controls
