### ISSUE TITLE
Bug: XAML Controls Gallery: Accessibility: The Info badge number on Inbox Tab is not appearing when 'Left compact' mode is selected in Infobadge navigation view

### ISSUE THREAD

**Issue by v-amnat** [microsoft/microsoft-ui-xaml#5882] opened 2021-09-14 14:27 UTC
**Tags**
A11yFeature, FeatureIssue, XAML Controls Gallery (Debug), Win32, Wipro

**Steps to reproduce the bug**

1. Launch the XAML Controls Gallery (Debug) App
2. Go to search bar and type Info Badge and hit enter key.
3. Now in display mode, select 'Left expanded' menu item, then select 'Left compact' menu item and observe the info badge on inbox is not shown.
4. If user click anywhere on the page then only the symbol is shown.

**Actual behavior**
The info badge on inbox symbol is not seen immediately when user selects 'Left compact' menu item after selecting the 'Left expanded' menu item.

Note: This issue is not observed in the navigation view card at same UI.

**Expected behavior**
When user selects left compact view then immediately the view should be shown along with the info badge symbols on respective tab items..

Version Info
Microsoft OS: 22449.1000
App: XAML Controls Gallery (Debug) (Version 1.2.16.0)

Attachment
left compact view feature.png
![left compact view feature](https://user-images.githubusercontent.com/74585893/133276301-937500b1-defe-4b7f-a96e-7a2862183eb8.png)

**Comment by StephenLPeters** [comment] 2021-09-14 21:07
duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5881, if you dismiss the popup once then the control works as expected.

**Closed** 2021-09-14 21:07 UTC
Labels: duplicate, needs-triage
