### ISSUE TITLE
OverlappedPresenter.IsMaximizable Does Not Work As Expected With ExtendsContentIntoTitleBar

### ISSUE THREAD

**Issue by DJRM2021** [microsoft/microsoft-ui-xaml#8783] opened 2023-08-22 15:26 UTC
### Describe the bug

When using OverlappedPresenter.IsMaximizable = false, the app window's maximize button "looks" disabled, but still clickable and will make the window to maximize.

### Steps to reproduce the bug

1. Create a new WinUI 3 Packaged Project in VS 2022.
![image](https://github.com/microsoft/WindowsAppSDK/assets/77593544/97e260b9-aef3-4a6c-905e-de52eeb65dca)
2. In the MainWindow.xaml.cs file, go to public MainWindow() constructor.
3. Insert the following code after the this.initializeComponent():
`public MainWindow()`
`{`
`    this.InitializeComponent();`
`    WindowTitleBar = AppWindow.TitleBar;`
`    WindowTitleBar.ExtendsContentIntoTitleBar = true;`
`    WindowTitleBar.PreferredHeightOption = TitleBarHeightOption.Standard;`
`    OverlappedPresenter windowPresenter;`
`    windowPresenter = (OverlappedPresenter)AppWindow.Presenter;`
`    windowPresenter.IsMaximizable = false;`
`    windowPresenter.IsMinimizable = true;`
`    windowPresenter.IsResizable = false;`
`}`

### Expected behavior

The maximize button should be completely disabled and the window should not be maximizable.

### NuGet package version

Windows App SDK 1.4 Preview 2: 1.4.230811000-preview2

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by eduardobragaxz** [comment] 2023-08-25 17:02
Duplicate of [#8666](https://github.com/microsoft/microsoft-ui-xaml/issues/8666)

**Closed** 2023-09-21 19:08 UTC
Labels: team-CompInput, area-Windowing
