### ISSUE TITLE
Severity Code Description Project File Line Suppression State Error Payload file 'C:\Users\admin\.nuget\packages\microsoft.winui\3.0.0-alpha.200210.0\runtimes\win10-x64\native\Microsoft.UI.Xaml\DensityStyles\CompactDatePickerTimePickerFlyout.xaml' does not exist. XamlControlsGallery

### ISSUE THREAD

**Issue by tejaat1995** [microsoft/microsoft-ui-xaml#2372] opened 2020-05-02 04:13 UTC
**Severity Code Description Project File Line Suppression State Error Payload file 'C:\Users\admin\.nuget\packages\microsoft.winui\3.0.0-alpha.200210.0\runtimes\win10-x64\native\Microsoft.UI.Xaml\DensityStyles\CompactDatePickerTimePickerFlyout.xaml' does not exist. XamlControlsGallery			
**

**Steps to reproduce the bug**

1. Clone  'git clone --single-branch --branch winui3alpha https://github.com/microsoft/Xaml-Controls-Gallery.git'
2. Try to lunch.

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | No   |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            | No   |
| October 2018 Update (17763)        | No   |
| April 2018 Update (17134)          | No   |
| Fall Creators Update (16299)       | No   |
| Creators Update (15063)            | No   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   | No  |
| Xbox                      | No  |
| Surface Hub          | No  |
| IoT                         | No  |

**Comment by ranjeshj** [comment] 2020-05-04 14:06
Did the nuget restore succeed without any errors ? you can force it by right clicking on the solution file and clicking on restore all nuget packages  and then looking in the output window for any errors.

**Comment by tejaat1995** [comment] 2020-05-07 23:55
> Did the nuget restore succeed without any errors ? you can force it by right clicking on the solution file and clicking on restore all nuget packages and then looking in the output window for any errors.

Thanks for the reply ranjeshj. I Tried that and NuGet packages are successfully configured but i dont have a CompactDatePickerTimePickerFlyout.xaml file in C:\Users\admin\.nuget\packages\microsoft.winui\3.0.0-alpha.200210.0\runtimes\win10-x64\native\Microsoft.UI.Xaml\DensityStyles\

**Comment by icnocop** [comment] 2020-08-26 05:34
This is happening when building in Release mode and the Microsoft.WinUI NuGet package 3.0.0-preview2.200713.0.
```
CheckForUnsupportedScenarios:
  The specified XPath query did not capture any nodes.
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\DensityStyles\Compact.xaml' does not exist. [D:\a\MyApp\MyApp\src\MyApp (Package)\MyApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\DensityStyles\CompactDatePickerTimePickerFlyout.xaml' does not exist. [D:\a\MyApp\MyApp\src\MyApp (Package)\MyApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\compact_themeresources.xaml' does not exist. [D:\a\MyApp\MyApp\src\MyApp (Package)\MyApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\generic.xaml' does not exist. [D:\a\MyApp\MyApp\src\MyApp (Package)\MyApp (Package).wapproj]
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(3035,5): error APPX0702: Payload file 'C:\Users\runneradmin\.nuget\packages\microsoft.winui\3.0.0-preview2.200713.0\runtimes\win10-x86\native\Microsoft.UI.Xaml\Themes\themeresources.xaml' does not exist. [D:\a\MyApp\MyApp\src\MyApp (Package)\MyApp (Package).wapproj]
```

**Comment by krschau** [comment] 2021-07-19 17:03
I believe this is a dupe of #3315, which was fixed in Preview 3. If you are still seeing the problem, please reopen this issue.

**Closed by krschau** 2021-07-19 17:03 UTC
Labels: product-winui3, version-winui3α
