### ISSUE TITLE
Windows App SDK (WinUI) projects lost designer and xaml properties

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6695] opened 2022-02-09 16:17 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Windows-App-SDK-WinUI-projects-lost-de/1640436)._

---
[severity:It's more difficult to complete my work]
don't know exactly when, if it was an update or not.
But new WinUI projects lost xaml designer capability and xaml properties panel doesn't work.

as you can see from the screenshot. in the xaml editor the context menu doesn't show "View Designer", those tabs which showed in one corner that allowed you to switch between xaml and designer is also gone, and when i select an object on xaml, the properties panel shows nothing.

I repaired VS2022 but same result.

---
#### Feedback Bot on 1/19/2022, 00:04 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by WelterDevelopment** [comment] 2022-02-16 11:51
Duplicate of #5917.

**Comment by asklar** [comment] 2022-02-19 09:40
Duplicate of #5917

**Closed by asklar** 2022-02-19 09:40 UTC
Labels: needs-triage

**Comment by CAKCy** [comment] 2023-09-19 02:39
Please read and act accordingly!

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7456966/7f950b63-7462-413d-9611-734eee4c48fc)

The link again:
https://developercommunity.visualstudio.com/t/Feature-request-Visual-designer-for-Wi/1608476?q=WinUI+Designer

Oh! And SPREAD THE WORD! 
PLEASE!
