### ISSUE TITLE
TeachingTips not display properly

### ISSUE THREAD

**Issue by quangaming2929** [microsoft/microsoft-ui-xaml#1763] opened 2019-12-15 08:27 UTC
**Describe the bug**
TeachingTip with IsLigthDismissEnabled open the first time by using TeachingTip.IsOpen = true work fine but after it has been close, next time the TeachingTip open using the same property, some of the element in the TeachingTip will be croped

**Steps to reproduce the bug**
I've using this code as an example inside a NavigationView
``` XAML
<Page
    x:Class="TestUWPApp.TestPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:controls="using:Microsoft.UI.Xaml.Controls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:TestUWPApp"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:models="using:TestUWPApp.Models"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">

    <Grid>
        <Button Click="Button_Click" Content="Ligth Dismiss Button" />
        <controls:TeachingTip
            x:Name="ttLigthDismiss"
            Title="Hello"
            Content="Random Content here .............."
            IsLightDismissEnabled="True"
            PreferredPlacement="TopRight" />
    </Grid>
</Page>
```
```C#
    public sealed partial class TestPage : Page
    {
        public TestPage()
        {
            this.InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            ttLigthDismiss.IsOpen = true;
        }
    }
```
In App.xaml:
``` XAML
<Application
    x:Class="TestUWPApp.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:TestUWPApp">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <!--  Other merged dictionaries here  -->
            </ResourceDictionary.MergedDictionaries>
            <!--  Other app resources here  -->
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

1. Click the button with the content "Ligth Dismiss Button"
2. Click anywhere on the page except the button and TeachingTip
3. Click the button with the content "Ligth Dismiss Button" again

**Expected behavior**
The element inside TeachingTip display normally

**Screenshots**
[Video showcasing the bug](https://video.fhan2-4.fna.fbcdn.net/v/t42.3356-2/80728026_2617045828382253_7311033868652062037_n.mp4/video-1576397185.mp4?_nc_cat=100&_nc_ohc=VzLGfy-BSFoAQmW5Am3oN860T1QUb0D3H6XvMR5ranghv5mK5uI1rUejg&vabr=271166&_nc_ht=video.fhan2-4.fna&oh=784a198aab1170f5ca0a0d1c8468582b&oe=5DF796FA&dl=1)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml version 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmgallahan** [comment] 2019-12-15 12:26
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/1372

**Closed** 2019-12-16 19:22 UTC
Labels: area-TeachingTip, duplicate, team-Controls
