### ISSUE TITLE
SVG image does not support styling via class

### ISSUE THREAD

**Issue by zed220** [microsoft/microsoft-ui-xaml#3941] opened 2021-01-13 13:11 UTC
I have created a sample WinUI on UWP project. 
SVG image does not support styling via class

**Steps to reproduce the bug**
[App22.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5808750/App22.zip)
1. Open attached project.
2. Run

**Expected behavior**
The circle should be green.

**Screenshots**
![image](https://user-images.githubusercontent.com/7091626/104456210-682ca880-55b9-11eb-8b7c-12fbe89e5b9a.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

**Comment by codendone** [comment] 2021-01-14 04:20
Yes, the current SVG support does not support styles. See #625 for more info.

**Comment by BorzillaR** [comment] 2021-01-14 22:01
btw, is any way to bind some svg colors to the system brushes? I want to use the svg icons in the toolbar items and cant find a way to change theirs colors depending on the current theme (Light, Dark)

**Comment by codendone** [comment] 2021-02-03 03:33
The only way I can think of to map to system colors would be to load the svg file into a buffer, lookup the color RGB values you need, search and replace them in the svg buffer, and then load that. Of course, you'll need to listen for theme changes and repeat this process when that happens.

**Comment by codendone** [comment] 2021-02-18 23:10
Closing this as a duplicate of a feature proposal asking for styling: #507.

**Closed by codendone** 2021-02-18 23:10 UTC
Labels: area-Images, needs-triage, team-Rendering, winui3preview
