### ISSUE TITLE
[UWP] ThemeResources specified in the code do not respond to RequestedTheme changes

### ISSUE THREAD

**Issue by steam3d** [microsoft/microsoft-ui-xaml#8873] opened 2023-09-16 17:56 UTC
### Describe the bug

If I set theme resource from code:
`Border.Background = Application.Current.Resources["CardBackgroundFillColorDefaultBrush"]`

It will not update the color when I change RequestedTheme, but if I set using xaml:
 `<Border Background="{ThemeResource CardBackgroundFillColorDefaultBrush}"/>`

It will update the color when I change RequestedTheme

https://github.com/microsoft/microsoft-ui-xaml/assets/30986874/5f30334d-55cd-43d3-953d-f9e03b9ddb31

Here is repo: [RequestedThemeIssue](https://github.com/steam3d/RequestedThemeIssue)

### Steps to reproduce the bug

1. Build  [RequestedThemeIssue](https://github.com/steam3d/RequestedThemeIssue)
2. Switch between theme

### NuGet package version

WinUI 2 - Microsoft.UI.Xaml 2.8.2

**Comment by mdtauk** [comment] 2023-09-16 18:28
Could it be because you are assigning the value, and not establishing a binding to the value, which would pick up changes?

**Comment by steam3d** [comment] 2023-09-16 18:41
> Could it be because you are assigning the value, and not establishing a binding to the value, which would pick up changes?
But how I can binding theme resource from code?

**Comment by steam3d** [comment] 2023-09-16 19:16
I also tired create a ThemeDictionaries and it still have the same behavior.
```
<ResourceDictionary.ThemeDictionaries>
  <ResourceDictionary
	  x:Key="Light">
	  <SolidColorBrush
		  x:Key="myBrush"
		  Color="Red" />
  </ResourceDictionary>
  <ResourceDictionary
	  x:Key="Dark">
	  <SolidColorBrush
		  x:Key="myBrush"
		  Color="Green" />
  </ResourceDictionary>
  <ResourceDictionary
	  x:Key="HighContrast">
	  <SolidColorBrush
		  x:Key="myBrush"
		  Color="Yellow" />
  </ResourceDictionary>
</ResourceDictionary.ThemeDictionaries>
```

**Comment by steam3d** [comment] 2023-09-16 19:24
Resources inside Application.Current.Resources never updates. Does not matter which theme you request.  Access to Application.Current.Resources will always return the same values.

**Comment by asklar** [comment] 2023-10-26 05:56
Dupe of #4443

**Closed** 2023-11-13 23:29 UTC
Labels: bug, team-Controls, product-winui2
