### ISSUE TITLE
Problem in the X button to close windows on the top right of screen

### ISSUE THREAD

**Issue by Saransh719** [microsoft/microsoft-ui-xaml#9060] opened 2023-11-09 16:15 UTC
### Describe the bug

While using Files app which uses this service, when I move the mouse over to the top left of the screen even when files is maximised, it focuses on resizing the window(which it is unable to do because window is maximised) instead of focusing on the X button as shown in screenshot below.

### Steps to reproduce the bug

Maximise files window and move mouse to top right

### Expected behavior

Mouse focuses on the X buttom

### Screenshots

![000065](https://github.com/microsoft/microsoft-ui-xaml/assets/115471237/38d768c9-ec1f-4995-9644-42e0543d1e23)
What is happening

![000066](https://github.com/microsoft/microsoft-ui-xaml/assets/115471237/99141766-1ffc-45e9-9230-38053f7bd8b7)
Expected(as in other software)
(See top right)

### NuGet package version

None

**Comment by bpulliam** [comment] 2023-11-09 17:31
Duplicate of #8805

**Closed by bpulliam** 2023-11-09 17:31 UTC
Labels: bug
