### ISSUE TITLE
Autosuggestbox border is blurry with a shadow effect

### ISSUE THREAD

**Issue by AtosNicoS** [microsoft/microsoft-ui-xaml#4552] opened 2021-03-17 12:43 UTC
**Describe the bug**
Have a close look at the Autosuggestbox:
![grafik](https://user-images.githubusercontent.com/37442184/111468933-694b9480-8726-11eb-8085-0998bee1bedd.png)

**Steps to reproduce the bug**
```xml
<AutoSuggestBox PlaceholderText="Search" QueryIcon="Find">
    <AutoSuggestBox.Resources>
        <SolidColorBrush x:Key="TextControlBorderBrush" Color="Red" />  
    </AutoSuggestBox.Resources>
</AutoSuggestBox>
```

**Expected behavior**
Why is there a shadow? I've also tried setting the border to 1px, but that does not help.

**Version Info**
WinUI 2.4 for UWP
I've also installed the nuget package for winui 2.5, but it seems Autosuggestbox is not available in this package (why?)

https://github.com/microsoft/microsoft-ui-xaml/blob/release/2.4/dev/AutoSuggestBox/AutoSuggestBox_themeresources.xaml

**Comment by codendone** [comment] 2021-03-18 02:40
The problem is that the rounded border gets blurred. This is tracked by #4021. Closing as a dup of that issue.

Note: this issue has been fixed for a future version of Windows, and will also be fixed in WinUI 3.

**Closed by codendone** 2021-03-18 02:40 UTC
Labels: needs-triage
