### ISSUE TITLE
WPF App using ,Net Core 3 preview cannot load Microsoft.Ui.XAML nuget package

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#1143] opened 2019-08-08 17:40 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/681541/wpf-app-using-net-core-3-preview-cannot-load-micro.html)._

---
Just updated VS 2019 Enterprise to latest 16.2.1. Have latest .Net Core 3.0 preview.
Tried to add the Microsoft.UI.XAML nuget package but got an error displayed just above the Manage Packages dialog reading:
The project 'JwContacts.WPF' ran into a problem during the last operation. The expression &quot;[System.Version]:Parse(&quot;)&quot; cannot be evaluated. Version string portion was too short or too long C:\Users\david\nuget\packages\microsoft.ui.xaml\2.1.190606001\build\Microsoft.UI.Xaml.props. You may need to reload the solution after fixing the problem.

The path and file indicated do exist.

Once the project.cs file is reverted and the solution closed, the project will not load until the project bin and obj folders are first deleted.

Repearted entire process after first deleting the package in my nuget store. Same result.

---
#### Visual Studio Feedback System on 8/7/2019, 06:36 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by jevansaks** [comment] 2019-08-09 18:19
Dupe of #295 .

**Closed** 2019-08-09 18:19 UTC
Labels: duplicate

**Comment by jevansaks** [comment] 2019-09-25 18:47
Duplicate of #295
