### ISSUE TITLE
Visual Artifacts and Behavior Discrepancies with Radial Progress Bar

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#3832] opened 2020-12-18 22:17 UTC
Was just playing with the updated XAML Controls Gallery, noticed some issues with the new determinate Progress Ring:

- [ ] Value of 50 isn't half of the circle:
![image](https://user-images.githubusercontent.com/24302614/101382506-e4222b00-386c-11eb-9b58-6706e4610ca1.png)

- [ ] Values aren't determinate. Setting a value doesn't result in the same behavior all the time:
![image](https://user-images.githubusercontent.com/24302614/101382758-2ea3a780-386d-11eb-9aef-2ce844df9ca1.png)
![image](https://user-images.githubusercontent.com/24302614/101382782-36634c00-386d-11eb-8a39-1563c8494e0e.png)

- [ ] The above means that in many cases there is no visual increment when incrementing between numbers (every value should show a discrete amount of the arc when the control is large enough on screen):
![image](https://user-images.githubusercontent.com/24302614/101382729-264b6c80-386d-11eb-97a9-e84ccc017aec.png)
![image](https://user-images.githubusercontent.com/24302614/101382748-2cd9e400-386d-11eb-80a9-02b524b683d0.png)

(I saw it go for 3-4 steps without moving, and then this seemed to cause a large jump between 99 and 100 at times.)

- [ ] The ring isn't completely filled at 100 (you can still see the end caps of the segment):
![image](https://user-images.githubusercontent.com/24302614/101382863-4a0eb280-386d-11eb-8735-60d4987997a4.png)

_Originally posted by @michael-hawker in https://github.com/microsoft/microsoft-ui-xaml/issues/3767#issuecomment-740059870_

FYI @MarissaMatt

**Comment by chingucoding** [comment] 2020-12-18 22:19
I think that's a dupe of #3787.

**Comment by YuliKl** [comment] 2020-12-19 00:07
Indeed, thank you @chingucoding. Closing this issue as a dupe.

**Closed by YuliKl** 2020-12-19 00:07 UTC
Labels: area-Progress, duplicate, team-Controls

**Comment by michael-hawker** [comment] 2020-12-19 02:25
Ah, sorry I didn't see that one had already been filed based on my comment! 🤦‍♂️
