### ISSUE TITLE
Crash in VisualStateManager.GoToState when animations are disabled in Windows

### ISSUE THREAD

**Issue by BaZzz01010101** [microsoft/microsoft-ui-xaml#8742] opened 2023-07-21 17:14 UTC
### Describe the bug

When animations are disabled in Windows settings the call to `VisualStateManager.GoToState` crashes in certain conditions.

The minimal repro solution:
https://github.com/BaZzz01010101/ReproAnimationCrash

### Steps to reproduce the bug

1. Disable animations in Windows Settings >> Ease of Access >> Display >> Simplify and personalize Windows >> Show animations in Windows
2. Checkout the minimal repro solution from https://github.com/BaZzz01010101/ReproAnimationCrash
3. Build and run the solution in debug mode
4. Click the checkbox in the app 3 times to switch visual states

### Expected behavior

The red circle in center should appear, disappear and then appear again according to visual states transitions programmed in the app but without animation according to Windows settings.

Instead the application is crashing on the 3rd switch of the checkbox.

When animations are enabled in Windows the application is not crashing but the animation is not started on the 1st state switch as expected. The circle just appeared without fade-in-out animation. On the 3rd state switch it start animating.

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/11557955/7388c5e3-6cdb-479e-89bf-09590070f459)

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Edition: Windows 10 Pro
Version: 22H2
OS Build: 19045.3208

**Comment by bpulliam** [comment] 2023-08-21 00:48
duplicate of #8675

**Closed by bpulliam** 2023-08-21 00:48 UTC
Labels: team-Controls, area-Animations
