### ISSUE TITLE
Windows deadlock when copying text in Entry

### ISSUE THREAD

**Issue by mattleibow** [microsoft/microsoft-ui-xaml#8088] opened 2023-01-04 19:35 UTC
---
**Issue moved from dotnet/maui#12369**
- Please respond to @daltzctr.

---

_From @daltzctr on Saturday, December 31, 2022 7:56:30 PM_

### Description

This issue occurs in Xamarin.Forms & MAUI. I've profiled this application using the Visual Studio profiler.

The highlighted section is where the "deadlock" occurs. It fixes itself after an unknown amount of time, which seems to scale based on the time dragging around the control.

![image](https://user-images.githubusercontent.com/105223895/210154407-2be88419-c6a1-459a-b5bc-069e51225e48.png)

### Steps to Reproduce

1. Create new MAUI application based on default template in VS 2022
2. Add the following text to `MainPage`

```
            <Entry Text="Test text" />
```
3. Run application, click into textbox and click and drag rapidly **outside** the boundaries of the text box.
4. Observe deadlock

Attached is a video demonstrating the freeze. You can see the time "clicking & dragging" around the control. After the deadlock occurs, I attempt to click on the "Click" button and it does not update until the freeze has ended.

https://user-images.githubusercontent.com/105223895/210154476-98d93c4e-9a63-4f08-8b2e-a313fb91a6a2.mp4

### Link to public reproduction project repository

MAUI: https://github.com/daltzctr/MauiDeadlock
WinUI 3: https://github.com/daltzctr/WinUITest

### Version with bug

7.0 (current)

### Last version that worked well

Unknown/Other

### Affected platforms

Windows

### Affected platform versions

Windows 11 22621.963

### Did you find any workaround?

No. Seems to be a bug in WinRT.

**Comment by JJBrychell** [comment] 2023-08-30 03:41
It appears that on some systems (and exacerbated by Maui) that the system can get overwhelmed attempting to process these pointer move messages. It isn't a copy that is occurring, but a selection (It doesn't appear that we support drag our of text boxes). So, when you mouse down over the text, even though a selection already exists, it starts a new one and then each move of the pointer attempts to alter the selected text in the text box and then requests asynchronously for Xaml to ensure that that selection is in the visible area. What appears to be happening is that in some scenarios, these requests are not processed fast enough and end up getting backed up, which in turn cause each subsequent request to take just a bit longer. Eventually the system gets so overwhelmed attempting to manage and process these requests that it appears to lock up.

However, in all of our testing it appears that once the pointer input is stopped, eventually, the system will catch up and get all these requests drained and will start performing as expected. Given this, and given that the scenario itself is an uncommon one (attempting to drag the selection for a significant period of time as shown in the video), this does not meet the threshold of something that we would address as a bug and therefore we are closing this issue.

**Closed by JJBrychell** 2023-08-30 03:41 UTC
Labels: bug, area-TextBox, team-Rendering, product-winui3, maui-7.x

**Comment by daltzctr** [comment] 2023-08-30 18:10
This is kinda funny. I respect the response, but I disagree with the flagging of not a bug.

- Occurs after ~3 seconds of selection. This isn't that uncommon. If you classify every uncommon behavior as not a bug, we'd have like 90% less bugs (maybe that's what MS is going for here :P)
- Occurs in a non-MAUI app
- Does NOT occur in a Win32 application, meaning this is a regression in behavior.

**Comment by JJBrychell** [comment] 2023-08-30 19:20
While technically not a bug (it is working as designed, just not well an unepected scenario) i agree that the result is buggy behavior and so yea, we treat it as a bug.  I have been able to repro it regularly in a Maui app, but only a couple of times in a WinUI3 desktop app (could have something to do with relative power of my machine).  If a Win32 application implemented a textblock in the same way, I would guess that it too would suffer from the same symptom.  It probably doesn't and we can agree that the current implementation is not handling this particular scenario very well.

That being said, the reason we closed this is that this doesn't seem to be a valid (or at least common) scenario.  For what purpose does one attempt to select text is in a text box (or even drag text) by pressing the left mouse button down and then rapidly and randomly dragging the mouse for three seconds?

Given a finite set of resources, it does not seem that redesigning this implementation to handle this scenario gives us enough benefit.  

If there is a more common or critical scenario where this occurs then feel free to make that case and if sufficient benefit can be derived from addressing this, we would certainly reconsider.

**Comment by hartez** [comment] 2023-08-30 20:07
> For what purpose does one attempt to select text is in a text box (or even drag text) by pressing the left mouse button down and then rapidly and randomly dragging the mouse for three seconds?

It's not necessarily happening for a purpose; folks with movement disorders might easily run into this issue.
