### ISSUE TITLE
Generated code for x:Bind in a Window doesn't correctly support converters

### ISSUE THREAD

**Issue by smaillet** [microsoft/microsoft-ui-xaml#5902] opened 2021-09-17 15:22 UTC
**Describe the bug**
Window class, which is the default setup for the project templates, doesn't support converters via x:Bind. 
The generated code for `GetBindingConnector(int, object)` fails to compile. (Works correctly with {Bind} however. 

**Steps to reproduce the bug**
Createa a WinUI 3 project from the template
In the MainWindow.xaml add a converter for some property of the the type
Add an instance of the converter to the Grid.resources. (Because Window doesn't have resources like other forms of XAML [Sigh....])
Compile.

`error CS1503: Argument 1: cannot convert from 'WinUIv3App.MainWindow' to 'Microsoft.UI.Xaml.FrameworkElement'`

This triggers for the call to `bindings.SetConverterLookupRoot(this)` Since Window is apparently NOT a FrameworkEelement, that can't work. Looking into the generated code for this it seems the lookup needs the "this" to find the converter in the resources, assuming they are in the resources of the top level element in the XAML (e.g. can't be in a global resource?).

**Expected behavior**
Expected the generated code to actually compile to allow using a converter in bindings of properties for elements in a window.
Ideally Window **IS** a FrameworkElement like it is with other XAML based frameworks. Barring that then the generated code needs to know that and instead of using "this" as the parmeter to SetConverterLookupRoot() it should use the first child of the Window which will be FrameworkElement.

**Screenshots**

**Version Info**
NuGet package version: 
0.8.3

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | <Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by michael-hawker** [comment] 2021-09-17 17:41
Duplicate of #4966

**Comment by StephenLPeters** [comment] 2021-09-23 00:08
@RealTommyKlein FYI

**Closed** 2023-08-03 22:46 UTC
Labels: team-Markup, product-winui3, v0.8, no-issue-activity
