### ISSUE TITLE
Simultaneous Mouse and multi-touch input Crash

### ISSUE THREAD

**Issue by techjogger** [microsoft/microsoft-ui-xaml#8022] opened 2022-12-16 13:54 UTC
### Describe the bug

Simultaneous Mouse and multi-touch input causes an ...... Unhandled exception at 0x00007FF8408A26DB (Microsoft.InputStateManager.dll) in ***.exe: Fatal program exit requested.

### Steps to reproduce the bug

Run a Windows App SDK 1.2.2 App
Simultaneously use the Mouse and two figures .
App crashes...

### Expected behavior

App does not crash!!!

### Screenshots

![crash](https://user-images.githubusercontent.com/13125455/208113360-610dd97e-5c1b-4367-ac98-29d40265d540.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by gabbybilka** [comment] 2023-01-06 17:54
Closing as dupe of https://github.com/microsoft/WindowsAppSDK/issues/3257

**Closed by gabbybilka** 2023-01-06 17:54 UTC
Labels: bug, needs-triage

**Comment by codendone** [comment] 2024-06-22 01:55
Correction: This is a dup of #7622.
