### ISSUE TITLE
NavigationView missing shadow when opening the panel in LeftMinimal mode

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#3117] opened 2020-08-13 03:45 UTC
**Describe the bug**

**Steps to reproduce the bug**

1. Open XAML Control gallary
2. Reduce the width of the application to make NavigationView go into `LeftMinimal` mode
3. Click on the hamburger menu to open the NavigationView panel
4. The panel shows the shadow, but it disappears after the panel is fully open

**Expected behavior**

Shadow to remain when the panel is fully open

**Screenshots**

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.0]
[Microsoft.UI.Xaml.2.4.0-prerelease.200506001]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by chingucoding** [comment] 2020-08-13 12:02
I think the issue is that the shadow is exactly the same width as the pane, thus the shadow is hidden behind the pane:
Pane shortly before fully opened:
![image](https://user-images.githubusercontent.com/16122379/90132126-8887db00-dd6d-11ea-8bf9-daf0098d24b0.png)

Pane completely opened:
![image](https://user-images.githubusercontent.com/16122379/90132141-90477f80-dd6d-11ea-9049-8d1b85d680b3.png)

**Comment by chingucoding** [comment] 2020-08-13 12:07
Also it seems that this is a regression (again): #1394 was filed in october last year and was fixed with #1398 .

**Comment by chingucoding** [comment] 2020-08-14 13:38
I would like to work on this issue.

**Closed** 2020-09-03 21:27 UTC
Labels: area-NavigationView, help wanted, team-Controls, working on it
