### ISSUE TITLE
Compilation error whilst declaring Converter as a resource in WinUI 3 preview 1

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2667] opened 2020-06-15 02:44 UTC
**Describe the bug**

I get `XamlCompiler error WMC0001: Unknown type 'EnumToBooleanConverter' in XML namespace 'clr-namespace:App1.Helpers;assembly=App1, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'` when I declare a Converter as a resource in the `Page.Resources`.

**Steps to reproduce the bug**

1. Create a Converter in namespace `App1.Helpers`
```
using System;

using Microsoft.UI.Xaml.Data;

namespace App1.Helpers
{
    public class EnumToBooleanConverter : IValueConverter
    {
        public Type EnumType { get; set; }

        public object Convert(object value, Type targetType, object parameter, string language)
        {
            if (parameter is string enumString)
            {
                if (!Enum.IsDefined(EnumType, value))
                {
                    throw new ArgumentException("ExceptionEnumToBooleanConverterValueMustBeAnEnum"/*.GetLocalized()*/);
                }

                var enumValue = Enum.Parse(EnumType, enumString);

                return enumValue.Equals(value);
            }

            throw new ArgumentException("ExceptionEnumToBooleanConverterParameterMustBeAnEnumName"/*.GetLocalized()*/);
        }

        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            if (parameter is string enumString)
            {
                return Enum.Parse(EnumType, enumString);
            }

            throw new ArgumentException("ExceptionEnumToBooleanConverterParameterMustBeAnEnumName"/*.GetLocalized()*/);
        }
    }
}
```
2. Refer it in the page resource as 
```
<Page
  x:Class="App1.View.SystemPage"
  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
  xmlns:xaml="using:Microsoft.UI.Xaml"
  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
  xmlns:helpers="clr-namespace:App1.Helpers"
  mc:Ignorable="d"
  Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
    <Page.Resources>
        <helpers:EnumToBooleanConverter x:Key="EnumToBooleanConverter" EnumType="ElementTheme" />
    </Page.Resources>
```

**Expected behavior**

No compilation errors

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.WinUI 3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |  Yes|
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by harvinders** [comment] 2020-06-15 03:09
Changing the declaration from `xmlns:helpers="clr-namespace:App1.Helpers"`  to `  xmlns:helpers="using:App1.Helpers"` helped compile the application.

However, still can't figure out how to set the `EnumType` property on the converter. I get runtime error with `EnumType="ElementTheme"`  or `EnumType="xaml:ElementTheme"`

**Comment by StephenLPeters** [comment] 2020-06-15 20:27
@RealTommyKlein @alwu-msft FYI

**Comment by RealTommyKlein** [comment] 2020-06-15 22:03
This looks like a duplicate of  #2551, which will be fixed in Preview 2.  Verified I hit the runtime crash using Preview 1 but the EnumType was correctly assigned to a System.Type of Microsoft.UI.Xaml.ElementTheme with 2551's fix.  Just the `EnumType="ElementTheme"` assignment is necessary, no need to qualify it as `xaml:ElementTheme`.

Similar to Windows.UI.Xaml, we use the `using` token instead of `clr-namespace` token to specify code namespaces in WinUI 3, so I wouldn't expect `clr-namespace` to work.  See [here](https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-namespaces-and-namespace-mapping#mapping-custom-types-to-xaml-namespaces-and-prefixes) for more details.

**Closed by RealTommyKlein** 2020-06-15 22:03 UTC
Labels: needs-triage, team-Markup, winui3preview
