### ISSUE TITLE
Payload contains two or more files with the same destination path Compact.xbf

### ISSUE THREAD

**Issue by tpdickson** [Microsoft/microsoft-ui-xaml#599] opened 2019-04-22 19:17 UTC
**Describe the bug**
UWP and UWP Xunit test project in same solution, both referencing Microsoft.UI.Xaml >= 2.1.190405004, causes error "Payload contains two or more files with the same destination path 'Microsoft.UI.Xaml\DensityStyles\Compact.xbf" (in each project's \bin\x86\Debug\ folder).

If I downgrade both project's Microsoft.UI.Xaml to 2.0.181018004 the error goes away.

**Steps to reproduce the bug**
I was trying Windows Template Studio for VS 2019 so these might differ slightly:

1. Add a Universal Windows C# project to your solution.
2. Add a Universal Windows C# xUnit test project to your solution.
3. Check NuGet Package Manager and make sure Microsoft.UI.Xaml is using version 2.1.x on both projects.
4. Build the solution.

**Expected behavior**
The project should build with no errors.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Fall Creators Update (16299)     | yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes   |

**Additional context**
Visual Studio 2019 16.0.2
Solution generated with Windows Template Studio.
Target Windows version: 1809 (17763)
Min Windows version: Fall Creators Update (16299)

**Comment by jevansaks** [comment] 2019-04-22 20:02
@licanhua I think we might need to package this file up into a .pri file -- that's how it works for the prerelease packages and we haven't run into issues that way yet.

**Comment by licanhua** [comment] 2019-04-22 20:46
It's interesting that I didn't repro it with VS 2017. By default, we supports the usage like         <ResourceDictionary Source="ms-appx://Microsoft.UI.Xaml.2.1/Microsoft.UI.Xaml/DensityStyles/Compact.xaml"/>
and it's been packaged to .pri.
Do you mean I just rollback the change which packing Compact.xaml into framework package?

**Comment by jevansaks** [comment] 2019-04-22 20:53
> Do you mean I just rollback the change which packing Compact.xaml into framework package?

No, I don't think so -- since if you do that then we would lose the Compact scenario that we've documented as working with 2.1.

@tpdickson can you share a repro project? 

@licanhua note that the customer is reporting this in VS2019. And I believe @micahl hit the same error with a VS2019 install.

**Comment by tpdickson** [comment] 2019-04-22 21:15
@jevansaks solution attached. I'd like to note again that this was generated with Windows Template Studio 2019 plugin, if that helps narrow it down for some bizarre reason.

[WTSTest1.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3104898/WTSTest1.zip)

**Comment by micahl** [comment] 2019-04-22 23:35
Yes, I hit the same error with a VS2019 install (not using Windows Template Studio).

**Comment by licanhua** [comment] 2019-04-23 02:51
I can repro the problem with the attached project.
The first repro step missed a important information: C# xUnit project references the C# project.
To support compact, I injected a <Page> to the project for framework package. It introduced problem in _ComputeAppxPackagePayload if more than two projects are references the microsoft.ui.xaml and the two projects have reference relationship too.
In this example:
C# xUnit project reference MUX nuget, it copied Compact.xaml to obj and compiled it.
C# project reference MUX nuget, it copied Compact.xaml again.
C# xUnit project reference C# project.
When compile C# xUnit project, _ComputeAppxPackagePayload aggregate Compact.xaml from both project in target _ComputeAppxPackagePayload, and task RemoveDuplicates detects this conflicts. 
I don't know how to fix it yet.

**Comment by jevansaks** [comment] 2019-04-23 02:53
Take a look at how the -prerelease nuget package is laid out. There is a .pri file that the Nuget msbuild targets merge in to the app's .pri. Since I haven't heard of problems with this on prerelease packages, I assume that shifting to that structure would work here. You can just invoke makepri.exe during MakeFrameworkPackage.ps1 or build-nupkg.ps1 for the framework package path.

**Comment by sibille** [comment] 2019-04-23 09:24
@jevansaks, I can repro this in VS2017 without using WTS. 
[BlankApp.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3106832/BlankApp.zip)

**Comment by licanhua** [comment] 2019-04-24 02:16
You may workaround the problem by adding below target to you project before the fix is in official release.
 ```
 <Target Name="FixXamlCompactXbfPackaging" BeforeTargets="_ComputeAppxPackagePayload">
    <ItemGroup>
      <XamlCompactXbfPackagingOutput Include="@(PackagingOutputs)" Condition="'%(PackagingOutputs.TargetPath)' == 'Microsoft.UI.Xaml\DensityStyles\Compact.xbf' and '%(PackagingOutputs.ProjectName)' != '$(MSBuildProjectName)'" />
    </ItemGroup>
    <ItemGroup Condition="'@(XamlCompactXbfPackagingOutput)' != ''">
      <PackagingOutputs Remove="@(XamlCompactXbfPackagingOutput)" />
    </ItemGroup>
  </Target>
```

**Comment by sibille** [comment] 2019-04-24 06:14
Thanks @licanhua, by when can we expect the fix to be in the official release?

**Comment by jevansaks** [comment] 2019-04-25 18:31
Re-opening as @licanhua said there's still an issue with the nuget package with his fix. He'll continue to investigate.

**Closed** 2019-04-26 20:04 UTC
Labels: area-Density, bug, needs-cherrypicktorelease

**Comment by JulienTheron** [comment] 2020-07-28 17:58
Hi,

It doesn't seem the issue is fixed. I've got "PRI277: 0xdef00532 - Conflicting values for resource 'Files/Microsoft.UI.Xaml/DensityStyles/Compact.xbf'" with the following project dependencies:
- MyApp:
    - Microsoft.UI.Xaml 2.4.2
    - MyControlLibrary:
        - Microsoft.UI.Xaml 2.4.0

As far as NuGet versioning works, I would expect the App to use the contents of the 2.4.2 package, but right now build is failing.
Build succeeds if the versions are the same, but the MyControlLibrary project will be used by other apps, and I don't want to block them from using 2.5.0 or later.

**Comment by licanhua** [comment] 2020-07-28 20:01
2.4.x should have the new implementation #1603, so I expect the workaround doesn't work any more.
Because you are using two MUX versions, so two microsoft.ui.xaml.pri from different nuget are used. Look like compiler can't resolve the conflicts by itself, and it's possible for you to remove one of the microsoft.ui.xaml.pri during compilation.

**Comment by JulienTheron** [comment] 2020-07-29 12:20
If it's possible to remove one, how so? Also, should I open a new issue for that? Seems like it breaks the whole semantic versioning principles.

**Comment by licanhua** [comment] 2020-07-29 17:54
Please open new issue. also please note down which language MyApp and MyControlLibrary you are using: C#, C++/Cx or CppWinRT.
It will be great if you can provide a simple repro project.
