### ISSUE TITLE
Increasing the FontSize of AutoSuggestBox should not increases the size of the Cancel icon as well

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#3968] opened 2021-01-17 04:08 UTC
**Describe the bug**
Increasing the font size of AutoSuggestBox increases the size of the Cancel (X) icon, however the QueryIcon size is not changed.

**Steps to reproduce the bug**
```
<AutoSuggestBox FontSize="32" QueryIcon="Find"/>
```
**Expected behavior**
QueryIcon should also scale up

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by mdtauk** [comment] 2021-01-17 10:20
I think by design the system does not automatically scale icons in line with text sizes.

So adjusting the font sizes in system settings doesn't make all icons bigger.

You may need to adjust the lightweight style for the Glyph to match the font size you are changing

**Comment by chingucoding** [comment] 2021-01-17 10:32
@mdtauk is correct, icons are usually not scaled with text scale changes but rather stay the same size (e.g. TabView or NavigationView exhibit the same behavior).

**Comment by StephenLPeters** [comment] 2021-01-20 00:38
It is correct that by design icon's do not scale. So I think the issue here is that the x button scales with font size not that the search button doesn't.

**Comment by harvinders** [comment] 2021-01-20 10:23
@StephenLPeters Bit of a context, I am developing application for kids and hence I would like to increase the font size. In my use case I would like the icon size to increase as it helps kids click the find button with ease. 

If I take my use case for other controls like navigation button, I think for kids the icon size should increase. I think, it is more of accessibility issue, if you consider for kids and elderlies. I don't fully understand the reasoning behind not scaling the icons, yes the behaviour is consistent across the controls but in my opinion it is not the right call. For the elderlies and kids, for worst there should be a workaround and at best icons should scale up.

> You may need to adjust the lightweight style for the Glyph to match the font size you are changing
@mdtauk Could you send me a link so that I can explore it.

Reducing the cross button is worse result considering my use case, because today I can opt to not show the icon and place a button with icon next to it (or try @mdtauk's suggestion) to achieve my objectives.

**Comment by mdtauk** [comment] 2021-01-20 12:59
There are light weight styles you can override if you wish to increase the sizes of these things.

I don't believe the TextBox currently uses light weight style values for it's glyphs, which is probably an oversight that should be fixed @StephenLPeters 

Would there be any issues with putting the UI you wish to resize in a ViewBox and scaling/zooming?

**Comment by StephenLPeters** [comment] 2021-01-21 19:46
@harvinders I understand your concern, the issue that we frequently run into when Icon's do scale up is that Icon's are usually placed in locations with limited space.  There is a windows setting to increase font scaling across the system that frequently causes our font icon's to scale but past their bounding box size and get clipped (when we forget to disable text scaling on the font icon).  We do want to allow these things to be customizable though which is why we tie their size to a resource.  For your scenario here you can override the [AutoSuggestBoxIconFontSize](https://github.com/microsoft/microsoft-ui-xaml/blob/67149eb41b582cb5a2572262a12789399381e68b/dev/AutoSuggestBox/AutoSuggestBox_themeresources_v2.5.xaml#L16) resource (at a page or more local scope) to adjust the query icon size.

I think that this template [part](https://github.com/microsoft/microsoft-ui-xaml/blob/67149eb41b582cb5a2572262a12789399381e68b/dev/AutoSuggestBox/AutoSuggestBox_themeresources_v2.5.xaml#L110) should get its font size property set to a light weight style for consistency. @chingucoding interested in trying this out?

**Comment by harvinders** [comment] 2021-01-22 02:19
@StephenLPeters Thanks, that was helpful

**Comment by chingucoding** [comment] 2021-01-22 10:46
> I think that this template part should get its font size property set to a light weight style for consistency. @chingucoding interested in trying this out?

Sure thing, PR's out.

**Closed** 2021-01-25 20:59 UTC
Labels: area-AutoSuggestBox, team-Controls, working on it
