### ISSUE TITLE
ListView, TreeView crashes while scrolling using scrollbar thumb when there are many items

### ISSUE THREAD

**Issue by bongvisu** [microsoft/microsoft-ui-xaml#7573] opened 2022-08-07 12:49 UTC
### Describe the bug

When a ListView has many(over 1000) items,
and do scrolling using the scrollbar thumb,
an exception occurs.

### Steps to reproduce the bug

1. Add many items(over 5000) to a ListView
2. Do scrolling using the scrollbar thumb

### Screenshots

![Callstack](https://user-images.githubusercontent.com/26132826/183291265-b767e762-7a17-4ef3-8b2d-8d94ce6888e2.png)

**Comment by gabbybilka** [comment] 2022-08-08 21:43
Yep, looks like a dupe of #7230 and others, the fix will be in an upcoming servicing release for 1.1.

**Comment by gabbybilka** [comment] 2022-08-16 16:37
:tada:`Microsoft.UI.Xaml v1.1.4` has been released which fixes this issue.

Handy links:
* [Release Notes](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-114)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.1.4)

**Closed by gabbybilka** 2022-08-16 16:37 UTC
Labels: bug, area-Lists, team-Rendering, fixed-internally, v1.1.0, transfer-repo
