### ISSUE TITLE
Upper part of the application window is cut off when snapped 

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#1624] opened 2019-11-16 14:23 UTC
**Describe the bug**

When a UWP/WinUI application is snapped to one side (in desktop or tablet mode), the upper part of its window is cut off.

**Steps to reproduce the bug**

1. Open a UWP app (e.g. the store)
2. Snap it to the left side (e.g. via keyboard short)
3. Oberserve that the upper part of the window is cut off.

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

This template needs to be updated to include the most recent released Windows version...

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2019 Update (18363)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmgallahan** [comment] 2019-11-16 15:59
Can't be reproduced. 

You'd need to provide screenshots and detailed information about your display hardware/settings/configuration to get anywhere with this.

**Comment by lhak** [comment] 2019-11-16 18:50
Screenshot of Microsoft Edge when maximized:

![image](https://user-images.githubusercontent.com/38145893/68997716-a9d49d00-08a9-11ea-933e-cf92de538757.png)

Window snapped to the left with Win+Left shortcut:

![image](https://user-images.githubusercontent.com/38145893/68997746-f4eeb000-08a9-11ea-92cb-bd8d07006d66.png)

I can see this issue on a Surface Go (1820x1200 Resolution, 150% scaling) and on a Desktop PC (4k resolution, 200% scaling), both running Windows 1909.

**Comment by kmgallahan** [comment] 2019-11-16 19:19
There must be some edge-case, non-standard setting or software on both systems. Otherwise it'd be easy to repro and heavily reported by now. Try logging into Safe Mode or a different user account to see how it appears there.

The Windows Sandbox shows it working fine:

![Annotation 2019-11-16 141535](https://user-images.githubusercontent.com/5379488/68998093-c954d100-087b-11ea-94e5-7f32410ef917.png)

**Comment by shaheedmalik** [comment] 2019-11-18 14:52
> Can't be reproduced.
> 
> You'd need to provide screenshots and detailed information about your display hardware/settings/configuration to get anywhere with this.

Easy to reproduce.

![image](https://user-images.githubusercontent.com/51347950/69062503-07233800-09e9-11ea-8037-65fe4c41f84d.png)

**Comment by kmgallahan** [comment] 2019-11-18 15:46
@shaheedmalik

The OP clearly stated:

> When a UWP/WinUI application is snapped to one side (in desktop or tablet mode)

It is not reproducible in desktop mode on any of my devices.

If it only repros in tablet mode then that is an important detail and the issue should be corrected, including the title.

**Comment by lhak** [comment] 2019-11-18 15:51
I tested it again on another machine (with a completely unrelated non-microsoft user account) and see the same issue. All machines are on build 18363.476 and I can reproduce it in desktop and tablet mode.

**Comment by kmgallahan** [comment] 2019-11-18 16:05
If anyone outside of @lhak can repro this in a normal Windows desktop environment, then please let us know.

Until then this is the difference between an issue impacting:

- 800+ million desktop users
- ~1 million tablet mode users
- ? users in desktop or tablet mode under very specific, yet unknown circumstances

**Comment by shaheedmalik** [comment] 2019-11-18 16:41
It's easily reproducible in both modes.

![image](https://user-images.githubusercontent.com/51347950/69071562-22e20a80-09f8-11ea-810b-fd14e9d35e4c.png)

Open window in desktop mode. Win+Up, Win+Left

![image](https://user-images.githubusercontent.com/51347950/69071680-4efd8b80-09f8-11ea-8bed-b6f7901b5232.png)

**Comment by kmgallahan** [comment] 2019-11-18 17:33
So if you specifically:

1. First hit the Win+Up to maximize a window
2. Hit Win+Left/Right to snap the window

then the issue can be repro'd (goes away if you his Win+L/R again). 

**However**, this happens to all windows, not just UWP/WinUI ones. So this is a Windows 10 issue that belongs in the Feedback Hub, rather than something that should be addressed here.

**Comment by shaheedmalik** [comment] 2019-11-18 18:04
> So if you specifically:
> 
> 1. First maximize a window
> 2. Then hit Win+Left/Right to snap the window
> 
> Then the issue can be repro'd (and goes away if you hit Win+L/R again). Maximizing first wasn't part of the original steps.
> 
> **However**, this happens to all windows, not just UWP/WinUI ones. So this is a Windows 10 issue that belongs in the Feedback Hub, rather than something that should be addressed here. @lhak
> 
> @shaheedmalik Thanks for the double downvotes btw!

You're welcome!

The issue also occurs when you snap a window at the the top of the screen (via mouse) to maximize it.
![image](https://user-images.githubusercontent.com/51347950/69077548-dac8e500-0a03-11ea-987e-ecb01919004b.png)

**Comment by YuliKl** [comment] 2019-11-18 19:50
@lhak thank you for opening this issue. As @kmgallahan pointed out, the problem isn't limited to UWP apps and won't be fixed in WinUI. Feedback Hub is definitely the best place for these types of issues, so please feel free to upvote the [feedback](https://aka.ms/AA6lruh) I opened based on the information that was provided here.

**Closed by YuliKl** 2019-11-18 19:50 UTC
Labels: needs-triage

**Comment by jasonwurzel** [comment] 2019-11-19 07:32
Sorry to bump up this closed issue, but I can't seem to open your link for the feedback issue @YuliKl is there a Issue ID or smth I can search for? I'd like to vote for it because apparrently I'm one of the 800million users affected by this. Though I wouldn't have noticed without this issue.

**Comment by jevansaks** [comment] 2019-11-19 18:43
Yulia's issue is internal and I don't know how to make it public. @jasonwurzel (or anyone) can you file a Feedback Hub item? I'll link it to the one Yulia created.
