### ISSUE TITLE
[WinUI] Border not rendering properly if we set corner radius for particular edges

### ISSUE THREAD

**Issue by VigneshRameshh** [microsoft/microsoft-ui-xaml#6419] opened 2021-11-30 15:56 UTC
### Describe the bug

Border not rendering properly if we set corner radius for particular edges

### Steps to reproduce the bug

1. Run the attached sample [WindowAppSDKUpgrade.zip](https://github.com/microsoft/WindowsAppSDK/files/7627034/WindowAppSDKUpgrade.zip)
2. Check the bord

### Expected behavior

The border should render properly, even if we set a corner radius for particular edges.

### Screenshots

![image](https://user-images.githubusercontent.com/43605205/144081109-c504094d-2525-4a02-af8c-8cddf88800c3.png)

### NuGet package version

1.0.0

### Windows version

October 2020 Update (19042)

### IDE

Visual Studio 2022-preview

**Comment by kmgallahan** [comment] 2021-11-30 22:39
Dupe of #6194

**Closed** 2022-02-17 18:39 UTC
Labels: duplicate, needs-triage, team-Rendering, product-winui3
