### ISSUE TITLE
Navigation Pane Issue when Theme is opposite to System Theme

### ISSUE THREAD

**Issue by cderi** [microsoft/microsoft-ui-xaml#2177] opened 2020-03-26 22:11 UTC
Hi

Navigation pane is changing briefly to the opposite them during various transitions / mouse over when a Acrylic Background is used.

To reproduce, create a new simple project with a navigation pane and a setting page.
Include the Acrylic tint in app.xaml :
```xaml
               <ResourceDictionary>
                   <ResourceDictionary.ThemeDictionaries>
                        <ResourceDictionary x:Key="Default">
                            <AcrylicBrush x:Key="NavigationViewExpandedPaneBackground"
                                BackgroundSource="HostBackdrop" TintColor="{ThemeResource SystemChromeMediumColor}" TintOpacity=".7"/>
                        </ResourceDictionary>
                        <ResourceDictionary x:Key="HighContrast">
                        </ResourceDictionary>
                    </ResourceDictionary.ThemeDictionaries>
                </ResourceDictionary>
```
![Pane Issue](https://user-images.githubusercontent.com/52795294/77701631-0b72e980-6fb7-11ea-8384-79051af25b64.png)

Run, select the Theme opposite to the system theme, and navigate. See screen shot.

Destop Windows 10 version: 1903 and 1909

Thanks

Charles

**Comment by ranjeshj** [comment] 2020-03-26 22:55
@cderi  Does this repro only on the latest pre-release build of WinUI ? Does it work in the pre-release build from December (or any of the stable builds) ? 

@ojhad as FYI

**Comment by YuliKl** [comment] 2020-03-26 22:57
@cderi, I wonder if this is caused by the tint color being a theme rather than a static resource... Does the issue still repro if you try changing to `TintColor="{StaticResource SystemChromeMediumColor}"` ?

**Comment by mdtauk** [comment] 2020-03-26 23:26
ThemeResources should change as the theme changes.  It is the StaticResources which do not change as the theme changes.

**Comment by YuliKl** [comment] 2020-03-26 23:31
> ThemeResources should change as the theme changes. It is the StaticResources which do not change as the theme changes.

True, but this theme resource is inside a theme dictionary. I wonder if there's a bit of inception happening, causing NavigationViewExpandedPaneBackground to go into the Default/Dark theme, and its TintColor to look for the system (Light) theme.

This is all just a hunch, something to try 🙂

**Comment by mdtauk** [comment] 2020-03-26 23:38
> > ThemeResources should change as the theme changes. It is the StaticResources which do not change as the theme changes.
> 
> True, but this theme resource is inside a theme dictionary. I wonder if there's a bit of inception happening, causing NavigationViewExpandedPaneBackground to go into the Default/Dark theme, and its TintColor to look for the system (Light) theme.
> 
> This is all just a hunch, something to try 🙂

Default, Light, and the High Contrast theme dictionaries should get an appropriate StaticResource

**Comment by cderi** [comment] 2020-03-27 07:31
@YuliKl The artefact does not appear if you use a StaticResource instead of the ThemeResource, but of course your pane stays on the wrong tint when you change theme.

**Comment by cderi** [comment] 2020-03-27 07:35
I closed the issue by mistake, sorry.

**Comment by StephenLPeters** [comment] 2020-03-27 21:12
I think the issue here is that the custom override of this resource does not have a override for dark theme as well.  The system is recording this dictionary as the location of this resource and when the theme is changed it looks at this dictionary for the dark theme version of this resource but it does not exist.  If this dictionary was merged into the NavigationViewThemeResources dictionary then I think you would see it correctly updated. Alternatively if you copy the dark theme resource into this dictionary I think that would also resolve the issue.

**Comment by cderi** [comment] 2020-04-01 20:48
Thank you Stephen. I have included the Light theme version in the dictionary as well and that works now. Thank you for the work around!

**Comment by cderi** [comment] 2020-04-02 07:28
Now there is still an issue on the navigation pane when the application is in background.
When the navigation pane background is Acrylic, it goes to white (in light mode) or black (in ark mode) when the application is in background (or when transparency is disabled). So the control become "invisible".

![Background Acrylic](https://user-images.githubusercontent.com/52795294/78221423-a1c97280-74c3-11ea-90c5-f4a0c891090b.jpg)

Hereunder is the expected color (as seen when the pane background is not Acrylic) 

![Background Solid](https://user-images.githubusercontent.com/52795294/78221607-f4a32a00-74c3-11ea-98bb-ee588728140d.jpg)

**Comment by chingucoding** [comment] 2020-04-02 10:28
Is this a bug? If we don't specify a themeresource for a specific theme, there isn't really a way to "guess" the correct resource and we have to use a resource from a different theme. Not specifying a resource for a certain theme, and switching to that theme is something I would expect to be resulting "undefined" behavior.

**Comment by StephenLPeters** [comment] 2020-04-02 17:11
yeah.. its unclear to me that is actually an issue.  @kikisaints is the fix I suggested earlier how we expect people to do this?

**Comment by mdtauk** [comment] 2020-04-02 18:55
> Is this a bug? If we don't specify a themeresource for a specific theme, there isn't really a way to "guess" the correct resource and we have to use a resource from a different theme. Not specifying a resource for a certain theme, and switching to that theme is something I would expect to be resulting "undefined" behavior.

I thought this was why there is a **default** when it comes to the ThemeDictionaries?

```
For custom controls, if you don't support "Light" and "Dark" themes and only support one theme as well as at least one "HighContrast" theme, you can change your main dictionary's x:Key attribute to "Default". "Default" is the ResourceDictionary that will be used if a ResourceDictionary in the specified theme (such as "Dark") cannot be found.

**Comment by cderi** [comment] 2020-04-03 07:23
What was bugging me was the "unstable" behavior. The Navigation pane color is fllashing when you move around, so I thought some links were broken somewhere.  I am happy to close the issue if there is nothing to track here.

**Closed** 2023-08-04 12:00 UTC
Labels: area-NavigationView, area-Styling, team-Controls, no-issue-activity
