### ISSUE TITLE
MediaPlayerElement will crash when playing opus format audio

### ISSUE THREAD

**Issue by tingjiangcao** [microsoft/microsoft-ui-xaml#9506] opened 2024-04-01 11:26 UTC
### Describe the bug

opus format audio (test file from YouTube)

It plays normally and fakes a death in about 20 seconds or so
The same file can be played normally with potplayer.
Play m4a and mp3 format without problem.

### Steps to reproduce the bug

..

### NuGet package version

None

**Comment by tingjiangcao** [comment] 2024-04-01 14:51
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/51285674/eb67ea60-ee7a-4aeb-9b86-eee77e300687)

**Comment by codendone** [comment] 2024-04-12 04:21
Likely the same underlying issue as microsoft/WindowsAppSDK#3305.

**Comment by patnels** [comment] 2024-04-14 15:06
Yes, this is the same issue.

**Comment by codendone** [comment] 2024-04-14 22:15
Closing as duplicate of microsoft/WindowsAppSDK#3305.

**Closed by codendone** 2024-04-14 22:15 UTC
Labels: bug, area-MediaPlayerElement, area-External
