### ISSUE TITLE
Using mouse back button on NavigationViewItem is triggering both forward and a backward navigation

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#6630] opened 2022-01-20 09:53 UTC
### Describe the bug

Clicking on a `NavigationViewItem`  using the mouse "back" button is triggering both a navigation to the associated page and a back navigation.

### Steps to reproduce the bug

1. Open XAML controls gallery app
2. Left click on one `NavigationViewItem` to have something in the navigation history
3. Click using the mouse "back" button on another `NavigationViewItem`

### Actual behavior
We are still seeing the "first/previous" page. We can see the selection pill being going to the new clicked items and going back to the previous page.

### Expected behavior

Mouse "back" button should not trigger a navigation. `NavigationViewItem` should ignore those click events.

### Screenshots

![winUIback button issue](https://user-images.githubusercontent.com/20152272/150315309-136887c3-c889-47ad-a59c-ba81e4db7251.gif)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

**Comment by jp-weber** [comment] 2022-01-23 09:38
Same issue as #2308.

**Comment by StephenLPeters** [comment] 2022-03-03 19:11
@ojhad FYI

**Comment by jp-weber** [comment] 2023-07-31 17:58
It would be nice if you could limit the input keys that trigger an activation. The problem is just as relevant for Win32. 

Perhaps it would be easiest to determine the input key in the ItemInvoked event.

**Comment by kmahone** [comment] 2023-08-08 20:28
Dupe of: NavigationView: Side buttons of the mouse are interpreted as input #2308

**Closed by kmahone** 2023-08-08 20:28 UTC
Labels: area-NavigationView, team-Controls
