### ISSUE TITLE
Proposal: Enable generics support in XAML

### ISSUE THREAD

**Issue by hez2010** [microsoft/microsoft-ui-xaml#5241] opened 2021-06-22 14:39 UTC
# Proposal: Enable generics support in XAML

## Summary
XAML doesn't support generics currently, it would be great to support consuming generics in XAML (eg. `x:DataType`, `x:Bind`).

## Rationale
Generics support in XAML enables us more use scenarios, such as using `List<T>` directly as `DataContext` without any wrappers. Also, since UWP supports function calls in `x:Bind`, without generic support we cannot call generic methods directly in XAML.

## Scope
| Capability | Priority |
| :---------- | :------- |
| XAML supports consuming instantiated generic types | Must |
| XAML supports consuming open generic types | Could |

## Important Notes
Usage:

```csharp
public string GetString<T, U>(T value1, U value2)
{
    return value1.ToString() + value2.ToString();
}
```

```xml
<TextBlock Text="{x:Bind GetString`2[sys:Single, sys:Int32](1.2, 4)}" />
```

**Comment by asklar** [comment] 2021-06-23 05:25
FWIW XAML features must be available to all consuming languages (not just C# :) ), so this should be implementable at the WinRT layer by the parser (and convert it to something reasonable in code-behind).

**Comment by driver1998** [comment] 2021-06-25 02:48
> FWIW XAML features must be available to all consuming languages (not just C# :) ), so this should be implementable at the WinRT layer by the parser (and convert it to something reasonable in code-behind).

We do have generic classes in WinRT, so I don't think that is too much of a problem?

**Comment by michael-hawker** [comment] 2021-07-06 21:12
🦙 Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/931

**Comment by sylveon** [comment] 2021-07-08 07:02
> We do have generic classes in WinRT, so I don't think that is too much of a problem?

It's not possible for somebody to write their own generic WinRT class, only the predefined system types may be generic.

**Comment by krschau** [comment] 2022-06-22 18:30
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/931

**Closed by krschau** 2022-06-22 18:30 UTC
Labels: duplicate, feature proposal, needs-triage, team-Markup
