### ISSUE TITLE
With WinAppSDK 1.4 instantiating Multiple Windows crashes the application

### ISSUE THREAD

**Issue by CaseNewmark** [microsoft/microsoft-ui-xaml#8893] opened 2023-09-20 13:08 UTC
### Describe the bug

After updating to WinAppSDK 1.4, when instantiating multiple windows in OnLaunched of the Application class, the app crashes.

### Steps to reproduce the bug

1. In Visual Studio create a new blank WinUI3 C# app
2. Open the package manager and update both BuildTools (10.0.22621.756) and WindowsAppSDK (1.4.230913002) to those versions
3. In the OnLaunched event add an additional `var window = new MainWindow()`
4. When running it crashes on that line.

It doesn't matter if you try to store the instance in a member variable or if you instantiate a completely different Window.

### Expected behavior

On Start the application opens two windows.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

I actually use AppSDK version 1.4.230913002 and windows version 22H2 19045, but the GitHub issue doesn't show those as selections.

**Comment by kmgallahan** [comment] 2023-09-21 02:29
Probably dupe of #8806

**Comment by bpulliam** [comment] 2023-09-21 16:06
Closing as Dup of #8806

**Closed by bpulliam** 2023-09-21 16:06 UTC
Labels: bug
