### ISSUE TITLE
Proposal:Python is supported！

### ISSUE THREAD

**Issue by xiaoshuaiyo** [microsoft/microsoft-ui-xaml#9851] opened 2024-07-25 08:29 UTC
# Proposal: [Please ask Microsoft to speed up the adaptation of Python] 

## Rationale

* Python is one of the most popular programming languages in the world - by some measures, more popular than [JavaScript, C# and C++](https://www.tiobe.com/tiobe-index/).
* "Developing a native GUI app" is one of the most fundamental use cases for any programming language. However, there are no Microsoft supported paths at present for build Windows GUIs using Python. [Pythonnet](https://github.com/pythonnet/pythonnet) is a third-party tool that can be used, but it doesn't produce UWP-compatible apps.
* Python is widely used in education as an introductory language for new developers. Giving students the ability to build GUIs is an essential part of a modern developer experience.
* Python is widely used in scientific circles to support research. These researchers currently use Jupyter to provide visualisations of their data analysis; however, there Jupyter cannot be used to develop standalone applications for visualization or data gathering. A native GUI API would enable scientists to develop these apps.
* Microsoft already has an established interest in Python as a language. Microsoft has a dedicated Python language team (employing multiple members of the Python core team); VSCode has established Python language support; and Microsoft sponsors multiple major Python conferences.

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

## Important Notes
This is the software I made using Win32more.
![image](https://github.com/user-attachments/assets/7337b740-ab81-4508-9ef9-85bd3c688b56)
But he doesn't seem to be able to customize the title bar.
Win32more: https://github.com/ynkdir/py-win32more

**Comment by codendone** [comment] 2024-08-07 23:17
Closing as duplicate of #3364.

**Closed by codendone** 2024-08-07 23:17 UTC
Labels: feature proposal, needs-triage
