### ISSUE TITLE
TextBox control Language property is not working

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#5412] opened 2021-07-08 13:09 UTC
**Describe the bug**

TextBox control Language property is not working.

**Steps to reproduce the bug**

1. Create a simple sample with TextBox
2. Set Langauge as "ar-SA"

**Expected behavior**

Arabic language should be applied.

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by ssaran046** [comment] 2021-07-09 12:48
duplicate,

https://github.com/microsoft/WindowsAppSDK/issues/1043

**Comment by andrewleader** [comment] 2021-07-09 15:14
@ssaran046 This is the primary bug we're tracking since it's a WinUI bug (we transferred this bug to the WinUI repo).

**Comment by chrisglein** [comment] 2021-08-16 22:55
@ssaran046 With this issue having moved repos it's missing a bit of the environment/setup info we'd expect for a WinUI bug. Can you fill in the table above with what version you're seeing this with? And when you say "is not working", do you mean it follows the wrong language? Or something more (for example there are linked bugs here that indicate text not showing up)?

**Comment by ssaran046** [comment] 2021-08-17 06:41
@chrisglein I have seen this issue on ProjectReunion 0.8.1 and I saw the problem on May 2020 Update (19041).

"is not working" - what I mean is, there will be no effect when changing the Language property.

**Comment by chrisglein** [comment] 2021-08-17 22:50
> @chrisglein Chris Glein FTE I have seen this issue on ProjectReunion 0.8.1 and I saw the problem on May 2020 Update (19041).

Thanks for that clarification. That means this looks like a regression from UWP to WinUI3.

**Closed** 2023-08-03 22:44 UTC
Labels: area-TextBox, team-Framework, product-winui3, group-language, no-issue-activity
