### ISSUE TITLE
Text block behaves improperly in Right to Left flow direction with a signed integer.

### ISSUE THREAD

**Issue by sethuramkumar** [microsoft/microsoft-ui-xaml#7646] opened 2022-08-25 10:19 UTC
### Describe the bug

In winui, when a text block has a signed integer, and setting the flow direction as Right To Left,
Position of the negative ("-") sign is modified.
Position of the text remains same, only position of the negative sign is modified.

```
  <StackPanel Grid.Row="18" Orientation="Vertical">
          <TextBlock Text="-123" x:Name="textBlock"   />
          <TextBlock Text="1234" x:Name="textBlock1"  />
 </StackPanel>
 ```

### Steps to reproduce the bug

1.Declare a text block with a signed integer.
2.Set the flow direction as Right To Left.
3.Note the position of the negative sign is moved to the end of the text which makes text unmeaningful.

### Expected behavior

1.Negative sign's position should not be modified in Right To Left flow direction.

### Screenshots

Flow Direction : Left To Right
![image](https://user-images.githubusercontent.com/92511047/186637461-db4138f5-255d-4671-a6ab-bc309586ce50.png)

Flow Direction : Right To Left
![image](https://user-images.githubusercontent.com/92511047/186638762-8fdd3e2a-08d3-4f2b-8288-739e96a3c90c.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by sethuramkumar** [comment] 2023-07-31 01:36
Any updates on this?

**Comment by JJBrychell** [comment] 2023-08-31 20:56
This is operating as designed.

Setting FlowLayout is a, well, a layout feature.  It basically determines whether the coordinate system starts 0,0 in the upper left and move right and down, or 0,0 i in the upper right and move left and down.  The real world effect of this is that elements are laid out right to left and what would typically be left aligned, becomes right aligned (and visa versa).

One other effect of this that when text layout can't determine the language being used, it will look at the coordinate.system to and make an assumption that if the coordinate system is RTL then the language is probably RTL as well.  In this case because you cannot determine the language direction based just upon the "-123" is display appropriates for an RTL language as "123-".  The digits and the symbol are treated as individual components and then (because we are assuming RTL due to layout) get switched.

If the text processor has some context to the number, it then does the correct thing:

<img width="267" alt="image" src="https://github.com/microsoft/microsoft-ui-xaml/assets/1727282/fa2cb832-2945-4c91-b9a0-0f26e4e67207">

I can see two possible approaches to achieving the desired output for your examples.

Unicode provides several unicode characters to help with this: https://sites.psu.edu/symbolcodes/web/rtl/

In this case using a text block of 

```
<TextBlock Text="&#x202D;-123" />
```
Will produce the result of -123 in the output since the string is being forced into LTR using the override character. However, be warned, these override characters effect the whole text and results might not be desirable.  For example:

```
<TextBlock Text="&#x202E;-123" />
```

Will produce 321- because the RTL override character will cause the entire text to reverse without the benefit of text processing taking into account context and attempting to do the right thing.

The other option would be to override it on the text block level:

```
        <TextBlock Text="-123" HorizontalAlignment="Left" FlowDirection="LeftToRight"/>
```

The HorizontalAlignment of left will cause the text block to be right aligned in an RTL layout, but changing the flow direction back to LTR will cause the contents to show as -123.

Of course, using either one of these "overrides" will not play well with any of the frameworks default internationalization capabilities.

Closing this issue as by design.

**Closed by JJBrychell** 2023-08-31 20:56 UTC
Labels: bug, team-Rendering, product-winui3, closed-ByDesign
