### ISSUE TITLE
Long text not displayed correctly in TextBox over 12k lines

### ISSUE THREAD

**Issue by JMLCelec** [microsoft/microsoft-ui-xaml#9870] opened 2024-08-02 08:10 UTC
### Describe the bug

After 12108 lines in a TextBox, the text is not visible but seems to be taken into account in selection.

### Steps to reproduce the bug

Put a long text in TextBox with more than 12110 lines.

### Screenshots

![353503191-e932fb66-f62c-4bc2-9017-81c70fdb0865](https://github.com/user-attachments/assets/e6bdc1de-3ca4-415c-881a-7eece4d0b0b9)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.5: 1.5.240627000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment] 2024-08-07 22:40
This is a duplicate of #1842.

**Closed by codendone** 2024-08-07 22:40 UTC
Labels: bug, needs-triage
