### ISSUE TITLE
Question: WinUI 3 designer?

### ISSUE THREAD

**Issue by ward-horsfall** [microsoft/microsoft-ui-xaml#7257] opened 2022-06-17 18:38 UTC
Hi

Is there a designer coming like in WPF for WinUI. As I heard there is some retooling enhancements happening in Visual Studio.

Also to head this one off at the pass - as I am sure I will get responses on this about hot reload etc. And please take this with great respect - it does not work for me.

let me express this in different terms that I don’t think has been expressed not everyone has the ability to translate easily and hold a visual map in there mind (remember) to be efficient. A term might be working memory. Just like some people have learning styles that are visual some auditory etc.

Now I do have a disability that gives me trouble and I have poor special skills yet I can code.

Now consider the WPF designer ok I know some gives the best for people who just like xaml and for me who really likes the clear visual representation it gives.

To use a much used expression a picture tells a thousand words.

Also Microsoft great success given there own history was to bring programming to the masses was with Visual Basic. What made it so popular not just the language but the designer.

Now consider this I know Microsoft put in a lot of work trying to make the language better which I applaud them for but they are missing the boat a bit with this.

Now as well I know diversity is important to people and Microsoft do consider that how you approach this problem as well. At the moment you are constraining people in a way you were not before.

The other Microsoft should won’t to do is to bring as many people to the .net platform as well by lowering the bar. If you lower the bar and make it easier “visually” in the way I am suggesting people can make the leap more easily to get over the first hurdle.

Now I say this knowing that I have no doubt from Microsoft’s side this would be a volume of work to do. But if anyone has the resources to do it they have. However if they did they would get the payoff in take up and adoption rate to justify the effort.

Now please nobody take offence here Microsoft or others not my intention.

if it is in the roadmap please tell me I really do want to make that jump but it makes me a bit sad you can’t accommodate me. 

However I do feel strongly enough to post this.

Of course if I am incorrect and it is coming even better.

So Microsoft please reconsider- you have a great fan here.

Thanks

Ward

**Comment by castorix** [comment] 2022-06-18 00:56
There was a discussion about this : [#5917](https://github.com/microsoft/microsoft-ui-xaml/issues/5917)

**Comment by krschau** [comment] 2022-06-20 14:19
@castorix linked to a good discussion of this issue, and I'll specifically refer you to @marb2000's [comment](https://github.com/microsoft/microsoft-ui-xaml/issues/5917#issuecomment-1028626378) where he went into more detail about the challenges in bringing the designer into WinUI 3 and where it fits into our current priorities.

I am sorry that the current state of things doesn't work great for you. Thanks for bringing it up -- hearing about people's pain points does help us prioritize going forward.

I am going to close this issue as a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5917, just to keep the conversation going in the place with the most context and details.

**Closed by krschau** 2022-06-20 14:19 UTC
Labels: question, area-Tooling, area-Designer
