### ISSUE TITLE
MapControl in release not working without a call to InitializeMap

### ISSUE THREAD

**Issue by nickrandolph** [microsoft/microsoft-ui-xaml#9324] opened 2024-02-06 03:14 UTC
### Describe the bug

Is the MapControl in the [experimental release](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/experimental-channel#version-15-experimental-150-experimental2) supposed to be working? All I'm seeing is a blue screen

![image](https://github.com/microsoft/WindowsAppSDK/assets/1614057/46d37ea6-7b45-40c8-84e3-89e199ea80dd)

### Steps to reproduce the bug

New WinUI application
Update to experimental release
Use following XAML in MainWindow

```
<Window
    x:Class="MapSample.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:MapSample"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <Grid>
        <MapControl MapServiceToken="XXXXX" />
    </Grid>
</Window>
```

### Expected behavior

Shows a map, or at least throws a meaningful error as why it's not showing anything

### Screenshots

![image](https://github.com/microsoft/WindowsAppSDK/assets/1614057/46d37ea6-7b45-40c8-84e3-89e199ea80dd)

### NuGet package version

1.5.240124002-experimental2

### Packaging type

Tried both Packaged and Unpackaged

### Windows version

Windows 11

### IDE

VS 2022 (Version 17.9.0 Preview 4.0)

**Comment by bkudiess** [comment] 2024-02-09 18:05
I tested with preview 1 and it works fine, please reopen the issue with a repro app if you can still repro. Here is the code I used:     ``<MapControl x:Name="myMap" 
                    Width="800" 
                    Height="600" 
                    InteractiveControlsVisible="True"
                    MapServiceToken = "foobar"
        />``
This is the link to get a MapServiceToken: https://learn.microsoft.com/en-us/azure/azure-maps/quick-demo-map-app#get-the-subscription-key-for-your-account

**Comment by dotMorten** [comment] 2024-02-09 20:57
I'm not seeing Preview1 work any better either without my workaround. both x86 and x64 tested, with and without debugger attached. I think this issue should be reopened.

**Comment by ranjeshj** [comment] 2024-02-09 21:33
@dotMorten can you share the repro project you have?

**Comment by dotMorten** [comment] 2024-02-10 01:53
Here you go:
[MapLoadRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/14227461/MapLoadRepro.zip)

**Comment by dotMorten** [comment] 2024-02-21 03:47
@bkudiess I've tried on 4 different systems, and they all exhibit the same behavior, including on a Surface Laptop Studio 2 and Surface Laptop 5, both with latest Windows 11, and two desktop PCs (both Win11). I don't think this is hardware/OS specific.

**Comment by dotMorten** [comment] 2024-02-28 04:11
Can you fix your bot? 🙄

**Comment by dotMorten** [comment] 2024-03-01 01:30
Still broken in the final v1.5 release. I've seen this issue referred to in other discussions as well. Surprised this made it to release

**Comment by ranjeshj** [comment] 2024-03-01 14:43
> Still broken in the final v1.5 release. I've seen this issue referred to in other discussions as well. Surprised this made it to release. My workaround above does still seem to do the trick, but it's by no means ideal.

@dotMorten we are still working on getting a repro. Will service a fix to 1.5 once the issue is understood and we have a fix.

**Comment by dotMorten** [comment] 2024-03-01 14:46
Since my workaround essentially does what your code does but ensures it delays until webview is ready I’m guessing there’s race conditions at play. But then again I’ve never seen it work, and I don’t know of anyone outside Microsoft who has

**Comment by ranjeshj** [comment] 2024-03-01 15:06
Agreed that this needs to be addressed. Does sound like a race condition. Just tried out a simple example

```
 <Grid>
     <MapControl MapServiceToken=..  />
 </Grid>
``` 
and that worked out of the box for me on 1.5 stable. Will ask a few more folks in the team to give it a try to see if someone can repro.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/28935693/82cdec82-1b84-41e8-ac23-d24f10ff463b)

If there is some pattern where it works vs where it does not work, that would be helpful.

**Comment by dotMorten** [comment] 2024-03-01 18:04
Yes this isn't a keys issue. The blue background is caused by this: https://github.com/microsoft/microsoft-ui-xaml/issues/9377 I'm guessing someone forgot to remove some early debugging style?
It would be nice if there was a better error if there was a keys issue, like a callback or message on the map area that the key is invalid or the very least a message in the output window.

**Comment by riverar** [comment] 2024-03-01 22:13
I can reproduce this.

The root cause is this check for an alpha-numeric token. There should be no such check and instead rely on error propagation from the server side. (My token has a hyphen in it.)

https://github.com/microsoft/microsoft-ui-xaml/blob/c8bd154c015b914e171a326481fef6532bc943de/controls/dev/MapControl/MapControl.cpp#L131-L133

**Comment by dotMorten** [comment] 2024-03-01 22:15
LOLOLOL. I looked at that but didn't think too much of it. I have an underscore in mine.

**Comment by riverar** [comment] 2024-03-01 22:19
Workaround: Ask users to recycle their keys until an alpha-numeric-only variant appears. This is of course unacceptable from a security perspective, so hopefully the team is _now_ paying attention to this issue and will service this ASAP.

**Comment by gegao18** [comment] 2024-03-05 21:33
Thank you for reporting this issue (and huge thanks to @riverar for debugging this). We've checked in a fix for our first 1.5 servicing release.

IsValidMapServiceToken is still needed since the token is passed into ExecuteScriptAsync in a string literal. We've updated it to just check for a double quote instead:

```
bool MapControl::IsValidMapServiceToken()
{
    // This token is passed as a JavaScript param in double quotes. Make sure the token itself doesn't contain any.
    return !MapServiceToken().empty()
        && std::all_of(MapServiceToken().begin(), MapServiceToken().end(), [](wchar_t i){return i != '"';});
}
```

**Closed by gegao18** 2024-03-05 21:33 UTC
Labels: team-Controls

**Comment by riverar** [comment] 2024-03-05 22:53
@gegao18 This change will fail on `"`, which could be another valid token character (now or in the future). It also misses characters such as `\`. I would instead consider encoding the input token and skip the testing altogether.

Something like...

```diff
- auto token = IsValidMapServiceToken() ? MapServiceToken() : L"";
- auto parameters =  std::format(L"{},\"{}\"", pos, token);
+ auto token = JsonValue::CreateStringValue(MapServiceToken());
+ auto script = std::format(L"initializeMap({},'{}');", pos, token.Stringify().c_str());

  if (auto webView = m_webView.get())
  {
      auto core = webView.CoreWebView2();
      // Initializing Azure Maps on WebView
      // params: longitude, latitude, mapServiceToken
      returnedValue = co_await core.ExecuteScriptAsync(L"initializeMap(" + parameters + L");");

      for (uint32_t i = 0; i < Layers().Size(); i++)
      {
          winrt::MapElementsLayer layer = Layers().GetAt(i).as<winrt::MapElementsLayer>();
          OnLayerAdded(layer);
      }
  }
```

**Comment by riverar** [comment] 2024-03-26 05:26
@gegao18 Ping

**Comment by gegao18** [comment] 2024-03-26 23:36
Thanks for pinging. For 1.5.1 we made the quick fix that accepts all but ". For 1.6 we have the full fix that passes an encoded token into the map.

**Comment by riverar** [comment] 2024-03-27 01:58
@gegao18 Perfect, thanks again.
