### ISSUE TITLE
Proposal:bootsrap grid

### ISSUE THREAD

**Issue by khoshroomahdi** [microsoft/microsoft-ui-xaml#1522] opened 2019-10-31 17:18 UTC
# Proposal: bootstrap grid

## Summary

Use classes like bootstrap instead of visual State to make app responsive.look at the gridextra on github
https://github.com/sourcechord/GridExtra
# Rationale

* I think it's easir and familiar and needs less code to make app responsive.

**Comment by jevansaks** [comment] 2019-10-31 17:24
Duplicate of #1466 .

**Closed by jevansaks** 2019-10-31 17:24 UTC
Labels: duplicate, feature proposal
