### ISSUE TITLE
WinUI 3 SelectorBar Rendering Bug After Adding CommunityToolkit.WinUI.Controls.SettingsControls Package

### ISSUE THREAD

**Issue by Zakariathr22** [microsoft/microsoft-ui-xaml#9589] opened 2024-04-26 14:36 UTC
### Describe the bug

In a WinUI 3 app, adding the `CommunityToolkit.WinUI.Controls.SettingsControls` NuGet package breaks the rendering of a `SelectorBar` control. The `SelectorBar` visually malfunctions after the package is installed, despite functioning correctly before.

### Steps to reproduce the bug

1. Start with a blank window and add a straightforward `SelectorBar` as shown below:
```
<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="App.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <SelectorBar>
            <SelectorBarItem x:Name="SelectorBarItemRecent" Text="Recent" Icon="Clock" />
            <SelectorBarItem x:Name="SelectorBarItemShared" Text="Shared" Icon="Share" />
            <SelectorBarItem x:Name="SelectorBarItemFavorites" Text="Favorites" Icon="Favorite" />
        </SelectorBar>
    </StackPanel>
</Window>
```
At this point, everything functions as expected when you run the app.

2. Navigate to the `NuGet Package Manager`, search for `CommunityToolkit.WinUI.Controls.SettingsControls`, and install the most recent stable version (in my case, it’s 8.0.240109). This package comes with four transitive packages:
- `CommunityToolkit.Common` (version 8.2.1 in my case)
- `CommunityToolkit.WinUI.Extensions` (version 8.0.240109 in my case)
- `CommunityToolkit.WinUI.Helpers` (version 8.0.240109 in my case)
- `CommunityToolkit.WinUI.Triggers` (version 8.0.240109 in my case)

3. Run the app again. At this point, the issue manifests:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/101801384/997332e1-6354-44a2-9fe3-69928e1458a0)
- Call Stack:
```
>	App.dll!App.App.InitializeComponent.AnonymousMethod__4_2(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e) Line 74	C#
``` 

### Expected behavior

After adding the `CommunityToolkit.WinUI.Controls.SettingsControls` package to the WinUI3 application, the `SelectorBar` should function as intended without blocking or causing the application to break. The application should run smoothly without throwing any unhandled exceptions, regardless of the addition of the `SettingsControls` package. The `SelectorBar` should be responsive and interactive, allowing for the proper selection of items.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/101801384/997332e1-6354-44a2-9fe3-69928e1458a0)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

**Comment by Zakariathr22** [comment] 2024-04-26 14:54
These issues, while all related to Windows UI development, seem like separate problems. They affect different features, WinUI versions, and underlying technologies compared to the bug I had explained with the SelectorBar and the CommunityToolkit.WinUI.Controls.SettingsControls NuGet package.

**Comment by Jay-o-Way** [comment] 2024-04-30 13:18
@niels9001 any insight?

**Comment by niels9001** [comment] 2024-04-30 16:18
Duplicate of https://github.com/CommunityToolkit/Windows/issues/408.

WCT 8.1 should resolve this issue, for now you can use our preview packages to try and see if that solves things. See instructions in the issue on the WCT repo

**Comment by Zakariathr22** [comment] 2024-05-01 23:55
### Potential Solution Identified, Although Temporary:
There's no requirement to install the Prerelease of `CommunityToolkit.WinUI.Controls.SettingsControls` for the `SelectorBar` to function as expected. Simply installing the most recent version of `CommunityToolkit.WinUI.Controls.Segmented` should suffice.

### Rationale:
I observed that all controls operate smoothly when `CommunityToolkit.WinUI.Controls.SettingsControls` is present, with the exception of `SelectorBar`. This control was not available in earlier versions of `Windows App SDK` and only appeared in version 1.5. Upon examining the details of [the stable channel release notes](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel) for the `Windows App SDK`, I discovered that this control was formerly known as "SegmentedControl" on the 1.5 roadmap, which is identical to the control exists in WCT.
![from the stable channel release notes](https://github.com/CommunityToolkit/Windows/assets/101801384/b18a2b9b-ed06-4051-8d44-fc4735a3b205)

I also noticed that the [WinUI3 Gallery App](https://apps.microsoft.com/detail/9p3jfpwwdzrc?hl=en-US&gl=US) employs the `Settings Controls` with `SelectorBar` without any issues. When I inspected [the source code](https://github.com/microsoft/WinUI-Gallery/blob/main/WinUIGallery/WinUIGallery.csproj), I noticed that `CommunityToolkit.WinUI.Controls.Segmented` was installed in the project, but it wasn't being used at all!!??
![image](https://github.com/CommunityToolkit/Windows/assets/101801384/8c6a56c0-c12a-477f-843d-3278d7465e9d)

When I attempted the same approach (merely adding `CommunityToolkit.WinUI.Controls.Segmented` without utilizing it), I was finally able to use `SelectorBar` without any issues. As a result, I suspect that the issue lies not with `CommunityToolkit.WinUI.Controls.SettingsControls`, but rather with `Windows App SDK 1.5`, which provided us with the same control found in `CommunityToolkit.WinUI.Controls.Segmented`, albeit under a different name. (Furthermore, it only functions in the presence of `CommunityToolkit.WinUI.Controls.Segmented` if you use other WCT packages.)

### Code
This is a XAML code for a Windows application interface that includes a `SelectorBar` with three items, a `Segmented` control with four items, and a `SettingsCard` with a dropdown menu containing three options.
```
<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="NewApp.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:NewApp"
    xmlns:controls="using:CommunityToolkit.WinUI.Controls"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel>

        <SelectorBar>
            <SelectorBarItem Text="Recent" Icon="Clock" />
            <SelectorBarItem Text="Shared" Icon="Share" />
            <SelectorBarItem Text="Favorites" Icon="Favorite" />
        </SelectorBar>

        <controls:Segmented>
            <controls:SegmentedItem >Item 1</controls:SegmentedItem>
            <controls:SegmentedItem >Item 2</controls:SegmentedItem>
            <controls:SegmentedItem >Item with long label</controls:SegmentedItem>
            <controls:SegmentedItem >Item 4</controls:SegmentedItem>
        </controls:Segmented>

        <controls:SettingsCard Description="This is a default card, with the Header, Description and Content set."
                               Header="This is the Header">
            <ComboBox SelectedIndex="0">
                <ComboBoxItem>Option 1</ComboBoxItem>
                <ComboBoxItem>Option 2</ComboBoxItem>
                <ComboBoxItem>Option 3</ComboBoxItem>
            </ComboBox>
        </controls:SettingsCard>

    </StackPanel>
</Window>
```
### Screenshots
![image](https://github.com/CommunityToolkit/Windows/assets/101801384/68700b15-1718-4af7-8b4d-0cbc82bf8992)
![image](https://github.com/CommunityToolkit/Windows/assets/101801384/82dc57c6-c221-4b16-b65a-9339ec63df74)

**Comment by kmahone** [comment] 2024-05-09 23:02
This is a dupe of #8810. 

See that Issue and Issue #9424 for a work around.

I am currently working on a fix for this issue.

**Closed by kmahone** 2024-05-09 23:02 UTC
Labels: bug, team-Controls, area-SelectionModel
