### ISSUE TITLE
(WinUI 3) Color banding in Navigation View content when in dark mode

### ISSUE THREAD

**Issue by dongle-the-gadget** [microsoft/microsoft-ui-xaml#6809] opened 2022-03-10 11:15 UTC
### Describe the bug

There's a color banding in Navigation View when the application is in dark mode.

### Steps to reproduce the bug

XAML code:
```
<Grid>
  <NavigationView>
    <Grid>
      <Frame x:Name="contentFrame">
        <Grid>
          <TextBlock Padding="56,16,0,0">Page content!</TextBlock>
        </Grid>
      </Frame>
    </Grid>
  </NavigationView>
</Grid>
```

### Expected behavior

There shouldn't be any color banding.

### Screenshots

![Color banding present in Navigation View](https://user-images.githubusercontent.com/29563098/157650776-1e78d02d-09ca-4575-9a7f-a71961020ee8.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (22572)

**Comment by kmgallahan** [comment] 2022-03-10 15:27
This is probably yet another consequence of this bug: #6194, with these dupes: #6207 #6419 #6475, that has been open for over 4 months.

¯\\_(ツ)\_/¯

@StephenLPeters

**Comment by kmgallahan** [comment] 2022-03-10 15:30
Top left of the main pane has a rounded corner, the other 3 aren't rounded.

**Comment by dongle-the-gadget** [comment] 2022-03-10 15:31
> Top left of the main pane has a rounded corner, the other 3 aren't rounded.

Yeah but are those related to setting different corner radiuses for the 4 corners?

**Comment by dongle-the-gadget** [comment] 2022-03-10 15:35
Idk why they are applying gradients for some reason, I just used ApplicationPageBackgroundThemeBrush (or sth i don't remember the exact name)

**Comment by dongle-the-gadget** [comment] 2022-03-10 15:37
It looks fine in light mode
![image](https://user-images.githubusercontent.com/29563098/157697022-389d1610-e9c4-4a4d-8dae-2f559a64ef9a.png)

**Comment by StephenLPeters** [comment] 2022-03-11 00:00
Another duplicate of this same issue which is actively being looked into.

**Comment by StephenLPeters** [comment] 2022-03-11 00:01
@codendone and @gegao18 FYI

**Comment by codendone** [comment] 2022-03-11 03:31
I agree the cause is the same as #6194. Please track progress via that issue.

**Closed by codendone** 2022-03-11 03:31 UTC
Labels: duplicate, needs-triage, team-Rendering, product-winui3
