### ISSUE TITLE
Application crash on WinUITap.dll

### ISSUE THREAD

**Issue by NandishNR** [microsoft/microsoft-ui-xaml#8354] opened 2023-04-03 12:03 UTC
### Describe the bug

Faulting application name: JioMeet.exe, version: 4.23.2.12, time stamp: 0x63558578
Faulting module name: Microsoft.VisualStudio.DesignTools.WinUITap.dll, version: 17.0.33006.217, time stamp: 0x633f5715
Exception code: 0xc0000005
Fault offset: 0x0000000000069631
Faulting process id: 0x63c8
Faulting application start time: 0x01d96623b481d77d
Faulting application path: C:\Users\nandish.nr\source\repos\Jio-WinUI3\src\JMB\JMB\bin\x64\Debug\net6.0-windows10.0.19041.0\win10-x64\JioMeet.exe
Faulting module path: c:\program files\microsoft visual studio\2022\community\common7\ide\commonextensions\microsoft\xamldiagnostics\x64\WinUI3\Microsoft.VisualStudio.DesignTools.WinUITap.dll
Report Id: 93777858-7dfd-481c-b544-7e2af14559a1
Faulting package full name: 
Faulting package-relative application ID: 

### Steps to reproduce the bug

Launch application and navigate between screen, application will go to busy state and crash

### NuGet package version

None

**Comment by kondareddy** [comment] 2023-04-04 05:13
![image](https://user-images.githubusercontent.com/1445374/229692697-6ecbd89f-2dc8-4920-9bb8-911bee0fc917.png)

![image](https://user-images.githubusercontent.com/1445374/229692756-241806b9-fad8-4b73-8fc4-50f3c8b9929f.png)

in .NET we can always get stack trace of the exception so that we can fix easily but in WinUI +.NET 6 - generic details are seen in event viewer and crash dump analysis as well.

are we missing something here?

**Comment by bpulliam** [comment] 2024-01-20 00:13
Duplicate of #8806

**Closed by bpulliam** 2024-01-20 00:13 UTC
Labels: bug, team-Markup

**Comment by JochemPalmsens** [comment] 2024-02-02 15:44
@bpulliam but that issue has also been closed and it's not clear what's the referring issue now.

**Comment by codendone** [comment] 2024-02-03 02:49
Clarity on the fix has been added in that other issue.

**Comment by JochemPalmsens** [comment] 2024-02-19 10:08
@codendone it's not fixed. Please reopen either this or the other issue. See our experiences in that other issue.

**Comment by codendone** [comment] 2024-02-21 20:54
@JochemPalmsens Thanks for the ping. Investigation has resumed for #8806. Let's use that issue for tracking.
