### ISSUE TITLE
TabView: the tooltip for every item is `Ctrl+F4`.

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/microsoft-ui-xaml#1133] opened 2019-08-06 01:23 UTC
**Describe the bug**
Regardless of whether I'm hovering over the `[x]`, the tooltip for each tabview item i've put in my tabview is `Ctrl+F4`.

**Expected behavior**
The tooltip would only show above the `[x]`

**Screenshots**
![image](https://user-images.githubusercontent.com/14316954/62504555-efaf9e80-b7ad-11e9-9ab2-72625d8f8df1.png)

**Version Info**
`2.2.190731001-prerelease`

**Comment by jevansaks** [comment] 2019-08-08 17:11
@kmahone can you take a look at this?

**Comment by adrientetar** [comment] 2019-08-08 18:14
In Edge & Chrome, the main shortcut to close tabs is Ctrl+W so why not make that one the default? Also, the tooltip when hovering the close button should really say "Close Tab (Ctrl+W)" but maybe we want to wait for #389 for that.

**Comment by kmahone** [comment] 2019-08-12 17:51
@DHowett-MSFT I am not able to reproduce this issue. I don't get any Ctrl+F4 tooltips on the tabs. Is this something that you added?

The expected behavior is that the tooltip of the tab is set to the Header string. This was not implemented in 2.2.190731001-prerelease, but it is available in recent CI builds.

@adrientetar since this issue is specifically tracking a tooltip issue, please file a separate issue to track the request of adding Ctrl+W as a shortcut. It seems Edge and Chrome both support both Ctrl+W and Ctrl+F4.

**Comment by DHowett-MSFT** [comment] 2019-08-12 19:13
If you’re asking whether we are explicitly setting the tab Header or tooltip to the string `Ctrl+F4`, I’m gonna have to say “that’s not it” :smile:

If the Header being used as the tooltip wasn’t implemented until after the version I reported, that lack is probably the cause of this issue.

**Comment by kmahone** [comment] 2019-08-12 19:25
@DHowett-MSFT even with 2.2.190731001-prerelease, I cannot reproduce the issue. Can you share a xaml snippet that reproduces the issue? I can't get a 'Ctrl+f4' tooltip to show up at all.

**Comment by kmahone** [comment] 2019-08-15 21:30
I am closing this bug, since I cannot reproduce it. If you are still hitting this issue, please share steps to reproduce the problem and I will reactivate the bug.

**Closed by kmahone** 2019-08-15 21:30 UTC
Labels: area-TabView, bug

**Comment by anandgithub21** [comment] 2025-02-02 02:29
> **Describe the bug** Regardless of whether I'm hovering over the `[x]`, the tooltip for each tabview item i've put in my tabview is `Ctrl+F4`.
> 
> **Expected behavior** The tooltip would only show above the `[x]`
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/14316954/62504555-efaf9e80-b7ad-11e9-9ab2-72625d8f8df1.png)
> 
> **Version Info** `2.2.190731001-prerelease`

Feb 2025 had the same issue. Seems this only appears if the TabView is created thru code behind. Thru xaml no no issue.
