### ISSUE TITLE
TeachingTip throws error "System.AccessViolationException"

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#832] opened 2019-06-10 06:34 UTC
**Describe the bug**

TeachingTip throws error "System.AccessViolationException" when creating in .cs code.

**Steps to reproduce the bug**

`<Button x:Name="SaveButton" Content="Save" Tapped="Button_Tapped"/>`

```
        private void Button_Tapped(object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
        {
            MUXC.TeachingTip tip = new MUXC.TeachingTip();
            tip.Title = "Error";
            tip.Subtitle = "It seems you are not connected to the Internet :(";
            tip.CloseButtonContent = "OK";
            tip.IsLightDismissEnabled = true;
            tip.IsOpen = true;
        }
```

`Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |  Yes   |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by jevansaks** [comment] 2019-06-10 17:09
Duplicate of #349 , fix should go out in the prerelease this week. Sorry for the delay!

**Closed by jevansaks** 2019-06-10 17:09 UTC

**Comment by hupo376787** [comment] 2019-06-11 01:36
Got it. Thanks, @jevansaks
