### ISSUE TITLE
Can't set x:Bind.Converter to StaticResource in a Window

### ISSUE THREAD

**Issue by MikeHillberg** [microsoft/microsoft-ui-xaml#6369] opened 2021-11-23 17:40 UTC
### Describe the bug

Window doesn't have a Resources property, so you set resources typically in the root of the Window content. If you try to use that in an x:Bind Converter using a {StaticResource}, it fails in the generated x:Bind code on the `SetConverterLookupRoot` call with the error:

Argument 1: cannot convert from 'App5.MainWindow' to 'Microsoft.UI.Xaml.FrameworkElement'

```cs
public global::Microsoft.UI.Xaml.Markup.IComponentConnector GetBindingConnector(int connectionId, object target)
{
    global::Microsoft.UI.Xaml.Markup.IComponentConnector returnValue = null;
    switch(connectionId)
    {
    case 1: // MainWindow.xaml line 1
        {                    
            global::Microsoft.UI.Xaml.Window element1 = (global::Microsoft.UI.Xaml.Window)target;
            MainWindow_obj1_Bindings bindings = new MainWindow_obj1_Bindings();
            returnValue = bindings;
            bindings.SetDataRoot(this);
            bindings.SetConverterLookupRoot(this); // <=== Error
            this.Bindings = bindings;
            element1.Activated += bindings.Activated;
        }
        break;
    }
    return returnValue;
}
```

See also #3442, where were it not for this compiler error, the scenario still wouldn't work for a different issue.

### Steps to reproduce the bug

```xml
<Window
    x:Class="App5.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App5">
    
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <StackPanel.Resources>
            <local:MyConverter x:Key="myConverter"/>
        </StackPanel.Resources>
        
        <TextBlock Text="{x:Bind TestProp, Converter={StaticResource myConverter}}"/>
    </StackPanel>
    
</Window>
```

```cs
public class MyConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, string language)
    {
        return "World";
    }

    public object ConvertBack(object value, Type targetType, object parameter, string language)
    {
        throw new NotImplementedException();
    }
}
```

### Windows app type

- [ ] UWP
- [ ] Win32

**Comment by hawkerm** [comment] 2022-02-14 09:02
Duplicate of #4966?

**Comment by StephenLPeters** [comment] 2022-02-16 22:46
Looks like it to me. @RealTommyKlein if you agree can you close this.

**Comment by krschau** [comment] 2022-06-22 19:13
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4966

**Closed by krschau** 2022-06-22 19:13 UTC
Labels: duplicate, needs-triage, area-Binding, team-Markup
