### ISSUE TITLE
The WinUI3 popup element can not exceed the parent window area！

### ISSUE THREAD

**Issue by wuyang26** [microsoft/microsoft-ui-xaml#7933] opened 2022-11-17 00:49 UTC
### Describe the bug

The WinUI3 popup element can not exceed the parent window area,but the WinUI2 can ,and the Windows App can also,for example the media player.

### Steps to reproduce the bug

1.Run the WinUI3 Gallery,select the ComboBox sample
2. Resize the window height to smaller
3. Popup the Font Size ComboBox. look the picture file.

### Screenshots

![WinUI3](https://user-images.githubusercontent.com/30990704/202326103-297f75bc-f68a-4695-94ca-d42169ebfd53.png)
![WinUI2](https://user-images.githubusercontent.com/30990704/202326121-f5aa2e43-c629-43e2-a6ca-3e42224165ca.png)
![WinApp](https://user-images.githubusercontent.com/30990704/202326129-ad54041a-d2b3-43ad-8b7c-0fbd404b132a.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.0

### Windows version

Windows 11 (22H2): Build 22621

**Comment by gabbybilka** [comment] 2022-11-17 17:24
Thanks for filing, this is known behavior for WInUI 3, closing as dupe of #5958

**Closed by gabbybilka** 2022-11-17 17:24 UTC
Labels: bug, team-Rendering, product-winui3
