### ISSUE TITLE
Discussion: Code sharing and INPC & INCC

### ISSUE THREAD

**Issue by hshristov** [microsoft/microsoft-ui-xaml#2978] opened 2020-07-23 13:33 UTC
We are using the same code in both **WinUI for UWP** and **WinUI for Win32**.
For the moment the **UWP** version should target **INotifyPropertyChanged** and **INotifyCollectionChanged** interfaces from **Microsoft.UI.Xaml.Data / Microsoft.UI.Xaml.Interop** while the **Win32** assembly should target those from **System.ComponentModel / System.Collections.Specialized**

Is this going to stay the same for the official release or are there going to be changes? Having to use preprocessor directives is not such a big deal but a single interface (even from newer namespace) would be easier to use to maintain.

As a side note some of the classes are in **Microsoft** namespace while other are in **Windows**. For example **Windows.UI.Color** and **Microsoft.UI.Colors**. There is no **Color** class in **Microsoft** namespace so you have to use the fully qualified name or there will be collisions from types in both namespaces.

**Comment by dotMorten** [comment] 2020-07-23 15:35
@hshristov It was my understanding this was addressed in Preview 2. Are you saying it wasn't?

**Comment by StephenLPeters** [comment] 2020-07-23 23:16
I think that the issues were only addressed for Desktop, not for UWP @MikeHillberg to confirm.

**Comment by dotMorten** [comment] 2020-07-23 23:17
Ugh that would be quite unfortunate if that's the case. Glad I didn't get starting on moving our UWP app over to WinUI P2 just yet. It's what was holding me back at P1

**Comment by azchohfi** [comment] 2020-07-24 19:12
@dotMorten I'm having the same issue updating the toolkit:
```cs
#if WINDOWS_UWP
using Microsoft.UI.Xaml.Data;
#else
using System.ComponentModel;
#endif
```
And similars... Preview2 fixed it for Win32 apps, not UWP.

**Comment by dotMorten** [comment] 2020-07-24 19:53
@azchohfi Ugh! That sucks. Preview 3 it is then :(

**Comment by stevenbrix** [comment] 2020-07-24 20:14
@dotMorten it sucks indeed, but as long as UWP stays on .NET Native, this is how it will be.

/cc @pag3 @stmoy

**Comment by dotMorten** [comment] 2020-07-24 20:24
Why is that though? It works in uwp for non-WinUI apps. It makes it really hard for us to move our existing uwp apps over to WinUI, as it would require significant rewrites and work often spans all the way into third party libraries. It's one thing to move to WinUI but it's an entirely different level of work also moving existing apps over to Win32.

**Comment by stevenbrix** [comment] 2020-07-24 22:08
Because the projections are hardcoded to `Windows.UI.Xaml`, and now that we've changed the namespace, they are broken. 

As per https://github.com/microsoft/ProjectReunion/issues/105, it is possible to have UWP apps that run on .NET5. As [Paul mentioned in his comment](https://github.com/microsoft/ProjectReunion/issues/105#issuecomment-658504970), there are other, simpler, ways to turn a .NET5 Win32 WinUI app into a .NET5 UWP WinUI app that also have some level of VS integration. We'll be sharing more on this soon.

Assuming you have a `using System.ComponentModel` at the top of your .cs file, and you only refer to `INotifyPropertyChanged` by the short name, would adding what @azchohfi showed above to every file be sufficient? Or are there cases where that doesn't work?

**Comment by azchohfi** [comment] 2020-07-24 22:23
INPC is the easy one.
The problem is much, much worse for INCC:
https://github.com/windows-toolkit/WindowsCommunityToolkit/commit/314d4a748c7f2890241b681fb542cf15dad265e0#diff-9484082d3b316abeae0d18b46f96ad52
And this is an old commit that I did that completely changed it from one to the other. What I'm investigating now is multi-targeting, which will make this code unreadable. Its unlikely that we'll ship this.

**Comment by hshristov** [comment] 2020-07-28 13:11
My point is that it is not that hard to go and sprinke preprocessor directives which I already did. But 3rd party libraries should have two different versions - one for UWP and one for Win32 which sounds like a lot of work.

**Comment by stevenbrix** [comment] 2020-08-18 16:41
@hshristov are you using a .NET Standard MVVM library in your app?

**Comment by hshristov** [comment] 2020-08-20 17:02
@stevenbrix Nope, I'm working on 3rd party controls library.

**Closed** 2023-08-03 22:37 UTC
Labels: area-NugetPackage, discussion, team-Markup, product-winui3, no-issue-activity
