### ISSUE TITLE
XAML Compiler doesn't support composed classes for UserControls

### ISSUE THREAD

**Issue by marb2000** [microsoft/microsoft-ui-xaml#4691] opened 2021-03-29 23:32 UTC
**Describe the bug**

When creating a composed UserControl like this in C++/WinRT:
```C
  struct BlankUserControl : BlankUserControlT<BlankUserControl, IEmptyInterface>
  {
  ...
  }
```
 I got the exception:
>winrt\base.h(7829,43): error C2440: 'static_cast': cannot convert from 'const winrt::implements<D,winrt::RuntimeComponent1::BlankUserControl,winrt::composing,winrt::Windows::UI::Xaml::Controls::IControlOverrides,winrt::Windows::UI::Xaml::Controls::IControlOverrides6,winrt::Windows::UI::Xaml::IFrameworkElementOverrides,winrt::Windows::UI::Xaml::IFrameworkElementOverrides2,winrt::Windows::UI::Xaml::IUIElementOverrides,winrt::Windows::UI::Xaml::IUIElementOverrides7,winrt::Windows::UI::Xaml::IUIElementOverrides8,winrt::Windows::UI::Xaml::IUIElementOverrides9,winrt::Windows::UI::Xaml::Markup::IComponentConnector,winrt::Windows::UI::Xaml::Markup::IComponentConnector2> *' to 'const D *'

**Investigation:**
After some conversations with the WinUI team, the problem is the way that UserControl has generated code from XamlCompiler. It doesn’t know that you have another interface you want to implement. C++/WinRT passes any variadic types to the intermediate template but XAML neglects to pass it on to the base.

WinUI is also tracking this internally: ADO **20976604**

**NuGet package version:** 
Reunion 0.5.0

**Windows app type:**
| UWP              | Win32            |
| :--------------- | :--------------- |
|  ?  | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by sylveon** [comment] 2021-04-25 02:04
Duplicate of #3331 :)

**Closed** 2021-05-04 06:21 UTC
Labels: area-XamlCompiler, bug, duplicate, needs-triage, team-Markup
