### ISSUE TITLE
Proposal: Remove Button Tilt

### ISSUE THREAD

**Issue by kikisaints** [microsoft/microsoft-ui-xaml#242] opened 2019-01-29 18:37 UTC
# Proposal: Remove Button Tilt

## Summary

Remove the Button tilt animation in the control's default template.

## Rationale

Internal analysis of first party and third party apps have shown that the majority of re-templates for button are made simply to remove the button tilt behavior. In a large study of our internal apps - which consisted of: calculator, alarms, camera, settings, messaging, photos, voice recorder - 65% of them had re-templated buttons and all had removed the tilt - even on buttons that were not altered in any other way besides the animation removal.
The utility apps in many ways are an example of default design system at work, however these apps are opting out of the tilt animation as they don't feel it add anything to their apps' overall experience.

Re-templating can incur a lot of extra overhead for a developer when they have to take ownership of a control that they largely do not wish to maintain outside of this one animation change. Not to mention the fact that re-templated controls add-up in terms of performance on load.

**Comment by mrlacey** [comment] 2019-01-29 20:04
Is there any knowledge of why the tilt is being removed? Is it just a developer preference?
Is there any similarity between the apps that remove it and those that don't? Is it just one designer/team who prefers to see it removed?
Why was the tilt originally added to the default template? 


> "notable study of internal apps"
???

Has there been any analysis of apps in the store? 

Just because 46% of a small sample do something isn't reason on its own to change the default. Is it?

**Comment by kikisaints** [comment] 2019-01-29 21:32
> Is there any knowledge of why the tilt is being removed? Is it just a developer preference?

As far as the knowledge to why tilt is being removed - it's mostly because of both a developer and a designer preference. In many cases these design choices are made to imitate their web versions. Of which many buttons are more "flat" and don't involve animations.

> Is there any similarity between the apps that remove it and those that don't? Is it just one designer/team who prefers to see it removed?

Apps that do not remove tilt tend to have a less branded experience. 

> Why was the tilt originally added to the default template?

It was originally added as a cosmetic statement for our design system at the time.

> Has there been any analysis of apps in the store?
> 
> Just because 46% of a small sample do something isn't reason on its own to change the default. Is it?

The analysis was done on apps in the store. I pulled out a small example for the sake of keeping the rational section concise. However the study included our "utility" apps - which consist of: calculator, alarms, camera, settings, messaging, photos, voice recorder - of which 65% of them had re-templated buttons and all removed the tilt to some capacity within. Aside from that, the only additional changes made to the template were color alterations. However, this study was done before the introduction of Lightweight styling so availability to more easily customize colors was limited.

I have also personally conducted sit-downs with our internal teams about the reasoning to why they removed tilt and most responded with either it did not fit their brand, or design did not want it.

That being said, it could be that our internal reviews do not reflect what the community and our general developer base wants. Hence the desire to proposal a removal to everyone for debate.

**Comment by mdtauk** [comment] 2019-01-30 01:34
Tilt first appeared in the Windows Phone UI, and came about because of the IRIS UI they used in that, which was in 3D space, so tilt and tile flipping all worked with a scene camera.

There were tutorials at the time for devs to implement the same tilting in their XAML silverlight apps.

I guess it was some time in Windows 8 or early Windows 10 that they introduced theme animations to WinRT.

Rather than remove the effect, you could always add a property to override the effect on Pressed state

**Comment by JustinXinLiu** [comment] 2019-01-30 06:01
I have been a big fan of the tilt effect since the Windows Phone days. When done right (e.g. [dribbble](https://dribbble.com/shots/3683800-Marvel) & [Timeline design](https://youtu.be/6DnZcVsUz-c?t=4)), it just feels so alive and futuristic.

However, I no longer use it on buttons in any of my new projects. Here's why:

1. The current tilt animation feels sluggish and disconnected. The text within the button even gets blurry during the animation. The overall experience just isn't great.

2. Tilt doesn't make much sense on circular icon buttons, and I want all my buttons to have a consistent interaction effect (e.g. I use _scale_ most of the time).

3. Given that controls are more compact than ever, tilt simply doesn't give me the 2.5D feel when the button is small.

Having said this, I think it's probably much safer to disable it by default, but offer an option to enable it. After all, just like the ripple effect in Material Design, it does remind people that this design comes from Windows, which to me is a good thing.

**Comment by jevansaks** [comment] 2019-01-30 06:07
Is the proposal to just remove tilt?

I was under the impression design wanted to refresh the animation -- do away with tilt but still have some kind of press effect? We've talked about removing tilt for a while but we never did it because there wasn't a proposal to replace it with and it feels worse to remove it and have nothing (even though it feels dated as other commenters mentioned).

**Comment by mdtauk** [comment] 2019-01-30 10:52
If Buttons are going to be given depth and a shadow - the tilt effect would ruin that illusion.  I guess Microsoft Design internally have plans which are not discussed publically.

**Comment by kikisaints** [comment] 2019-01-30 15:10
>Is the proposal to just remove tilt?

>I was under the impression design wanted to refresh the animation -- do away with tilt but still have >some kind of press effect? We've talked about removing tilt for a while but we never did it because >there wasn't a proposal to replace it with and it feels worse to remove it and have nothing (even >though it feels dated as other commenters mentioned).

Yes the proposal is to simply remove it. Last we spoke to design they had some plans around a different animation, but nothing concrete. They did agree that it needed to be removed altogether because of the outdated-ness of it's appearance. Since there was no better solution proposed since, we've let the animation sit.

Another way/alternate soltuion we could do, is to allow disabling it without completely getting rid of it. We could template bind that animation so an app-developer can toggle it outside of the template:

```xaml
<VisualState x:Name="Normal">
     <Storyboard>
        <PointerUpThemeAnimation Storyboard.TargetName="RootGrid" IsEnabled="{TemplateBinding TiltOnPress}" />
     </Storyboard>
</VisualState>
```

A result to the effect of what @mdtauk was referring to.

**Comment by mrlacey** [comment] 2019-01-30 17:44
Ha, reminds me of early WP7 days when I spent ages adding the tilt effect to controls because it didn't get added by default.

**Comment by chigy** [comment] 2019-01-30 22:00
@kikisaints - I have not received official request to remove the tilt from the design team. As far as I understand, some button retemplate was due to the lack of flexibility to turn off tilt without retemplate and some buttons like title bar buttons did not make sense to have tilt. Today, tilt is used as a press state equivalent on Xbox where the button depresses so we cannot just remove it without considering what the removal means to the press and hover state on all the platforms we support.

**Comment by bschoepke** [comment] 2019-01-31 16:52
I'd suggest making it easy to opt-out of tilt via "lightweight styling"

https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/xaml-styles#lightweight-styling

the more we can do to prevent re-templating the better. I'd also maybe take the opportunity to allow devs to use lightweight styling to supply custom theme animations.

**Comment by stmoy** [comment] 2019-01-31 17:53
@kikisaints - the tilt animation is provided as a visual affordance that is specified by PointerDownThemeAnimation. I agree with @chigy that we'll need some sort of press feedback by default, so we could consider modifying the animation provided by PointerDownThemeAnimation.

**Comment by kikisaints** [comment] 2019-02-01 17:22
@stmoy and @chigy - I'm somewhere in the middle. I don't believe we should replace the animation with another, unchangeable/un-customizable animation. That feels odd.

@bschoepke - I like this line of thinking, my only worry is that lightweight styling relies heavily on your knowledge of resource keys and names. Which can become cumbersome and explodes generic.xaml considerably.

My reason for complete removal is that if the majority do not use tilt, maybe it's causing more issues than it's solving.

That being said, perhaps the crux of the issue here isn't the tilt itself, but how we've structured our styling system all-up...

**Comment by JustinXinLiu** [comment] 2019-02-01 19:16
I think we still need a _signature_ visual feedback on pressed state for most our interactive controls (e.g. `Button`, `AppBarToggleButton`, `ComboBoxItem`, `ListViewItem`, etc.) that could instantly differentiate themselves from other design languages.

It's like whenever I click a button and see the ripple, I know it's from Material.

Currently, we have reveal and tilt, however the former is not turned on by default and only works well with dark background. The tilt just doesn't look good anymore.

I am just concerned that if we removed it completely without a replacement, the controls could lose their Fluent design identity. I did [some experiment](https://twitter.com/justinxinliu/status/904257290189996033) in the past and would love to see if our design team can come up with something that embraces Fluent features like light, depth, material and motion. ;)

**Comment by JustinXinLiu** [comment] 2019-02-01 19:31
@mrlacey there will still be some color changes on the background, foreground and border, but I don't think they are enough...

**Comment by JohnnyWestlake** [comment] 2019-02-05 10:02
I'm going to chip in and say I don't see a need for removing it, but an easy TemplateBinding or even global toggle for it for those who want it wouldn't go amiss. One thing I will say when I've done client projects is they generally preferred it if the animation only affected the content of the button and not the border / background, so I usually ended up retemplating for it to affect the ContentPresenter instead. Still obvious depression, but a little nice.

Depression is also quite nice when using physical keys (like keyboard, media remotes, gamepads).

Or, even if it is removed, as long as PointerDownThemeAnimation still exists at least I can still put it back in easily - so in that case I'd like to chuck in a vote for *not* changing the default PointerDown/UpThemeAnimation but replacing it with a new one?

**Comment by mdtauk** [comment] 2019-02-05 11:47
Whether you keep the tilt or remove it/replace it

I think there is something to be said for adding a ThemeAnimation property, which is changable in XAML or codebehind - without a need for re-templating - would suffice until the Fluent Team know exactly what they want to do for button pressed animations across all MUX controls.

**Comment by kikisaints** [comment] 2019-02-05 18:23
@JohnnyWestlake interesting that there is a desire to have tilt on the presenter but not the border, it would seem that even if we had a toggle for the animation (either through lightweight styling or a property) it wouldn't really solve your scenario where you need to alter *what* the animation affects, not whether or not it's there... thanks for the insight!

**Comment by lukasf** [comment] 2019-02-13 13:31
@kikisaints This could be solved by having an enum TiltMode: { Disabled, Control, Content } ;) Not sure if it is a relevant scenario though.

**Comment by mdtauk** [comment] 2019-05-15 15:58
If all the tilting is in the State Transition - simply replacing that with an empty transition would turn off the effect.

That means the ButtonBase could have a Transition property for each state, allowing easy ways to override them?

Probably not until WinUI 3.0, when the source code for the Button and ButtonBase primitives are in the repository.

**Comment by Poopooracoocoo** [comment] 2019-11-05 02:56
I really dislike the tilt effect in menus but I'm fine with it on buttons

**Comment by sylveon** [comment] 2020-05-09 05:48
With the advent of XAML Islands, I am now in a state where I need to implement a close button in XAML for my XAML Island windows. The tilt animation is the last remaining thing before I get consistent with the normal system controls, so adding the possibility to opt-out via a single property would be nice, instead of having to retemplate the whole control (which I'd really like to avoid)

![image](https://user-images.githubusercontent.com/6440374/81465309-23817f80-9197-11ea-89c6-a0b7877da2f9.png)

**Comment by Felix-Dev** [comment] 2020-11-03 09:49
@kikisaints @chigy Experimental work https://github.com/microsoft/microsoft-ui-xaml/pull/3514 removed the button tilt effet for now without a replacement. Can we expect more design evaluations about the tilt effect (i.e. replacing it with a different animation, making it opt-in,....) or should we expect only foreground/background button color changes from now when pressing a button?

The new XAML re-design stresses that it wants to keep the new UI familiar to Windows users and [reading through some of the comments here](https://github.com/microsoft/microsoft-ui-xaml/issues/242#issuecomment-458822817), the tilt effect seems have become part of the Windows UI DNA since its introduction. This sounds like a case to *modify* the tilt effec instead of just outright removing it.

**Comment by chigy** [comment] 2020-11-03 18:23
@Felix-Dev , we are not currently looking at replacing tilt with another effect, but it doesn't mean we might not introduce something in the future. New design is not built to rely on tilt, so adding additional effect later will only strengthen, but not weaken it, IMO.

Tilt effect was a carry over of Metro design but it does not have a place in the current design language. It has issues such as the text scaling made things look fuzzy, over tilting, etc. and does not fit in our cleaner UI model.

If anyone is very sad to see tilt gone, it would be some of us who worked on phone to introduce it in the first place including myself. :) But we all understand why our design is better without it.

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 02:44
@chigy Please don't remove this. It may not have a place in the current design language however combining with reveal makes it better so it could be an optional thing. Also, the issues that you mention can be fixed like text scaling instead. Please don't do this because the web and other platforms don't have it. I'm worried that Fluent is becoming more material day by day. You first removed Acrylic from NavigationView, then broke reveal in the button control and now you have the dumb flat old look. Please don't say that makes it consistent with other platforms. macOS has acrylic everywhere but you removed it from NavigationView.

**Comment by Poopooracoocoo** [comment] 2020-11-04 03:21
>Tilt effect was a carry over of Metro design

The square/tile aesthetic is still unique as both Google and Apple have very round elements. There are some elements in some new designs that have a pill/stadium shape and it makes me think about unique elements in Microsoft's design. The tilt isn't one of them anymore. Office's new logo still has the angle that was consistent with the button tilt and the animation for opening apps in Windows 8. Windows 8 and Windows 10 did quite a bit to remove rounded corners, so if MS decides to implement them (like window borders), it'll be quite the task.

I honestly never liked the reveal effect and I expected that to get the chop first. The button tilt's text issues got on my nerves but those were bugs where the effect got stuck. As I said a year ago, I really dislike the effect in menu items. Holy cow, where has the time gone? A whole year. darn 😢

**Comment by Jaiganeshkumaran** [comment] 2020-11-04 08:46
The tilt effect provides visual feedback, especially on touch devices. Please don't remove it.

**Comment by dragonDScript** [comment] 2020-11-04 18:23
I think exactly the same @Jaiganeshkumaran 
The tilt effect provides visual feedback, which improves user experience. And as @Jaiganeshkumaran, especially on touch screens where you don't have a mouse and don't feel that.

**Comment by chigy** [comment] 2020-11-04 21:02
@Jaiganeshkumaran , @dragonDScript , @Poopooracoocoo , @Felix-Dev ,
Thank you for your comments. As someone who was part of the team that introduced tilt back in phone days as well as brought it to Windows, tilt removal is somewhat personal so I understand your feeling. So I can assure you that this decision was not made in a vacuum. That said, tilt as in today's form no longer fits within our design language and rather than trying to reuse what is no longer working (let alone it has many issues that makes this animation not super desirable), we decided to snap to a clean design that we can improve on top of.

**Comment by Jaiganeshkumaran** [comment] 2020-11-05 02:42
@chigy Why? Because the Windows team is increasingly going towards using web components in their OS. Since web frameworks don't have such effects, if they remove it they can have a consistent UI with the new web stuff and they don't need to update their framework.

**Comment by mdtauk** [comment] 2020-11-05 03:01
> @chigy Why? Because the Windows team is increasingly going towards using web components in their OS. Since web frameworks don't have such effects, if they remove it they can have a consistent UI with the new web stuff and they don't need to update their framework.

With CSS Perspective and Perspective-Origin - the tilt effect could be replicated on the web, but its not about replicating, an effect the design team no longer wishes to use.  Also web technologies have been built into windows since Windows 98.  Those rich folder views and control panel UI was done with HTML code built into the File Explorer code.

The blending/merging/melding of WinUI Xaml control designs and web, is a recognition that many more apps will choose to create apps on different frameworks.

One of the major complaints about Windows apps, is a lack of design consistency.

So, with a set of controls which look as identical as possible, use Fluent Designs, and a set of FluentUI components that are cross platform - this is how you begin to fix an inconsistent UI.

All windows native frameworks should eventually use a unified design IMO [Project Reunion Proposal](https://github.com/microsoft/ProjectReunion/issues/272) 

And then the new frameworks like Flutter which is web based, should have a FluentUI theme available, and ReactNative uses WinUI to render XAML UIs - so widening the amount of frameworks devs can pick for making Windows Apps

**Comment by Jaiganeshkumaran** [comment] 2020-11-05 03:24
@mdtauk Those web stuff ran in IE which was really lightweight. Although Chromium is better, loading it in every process multiple times like Electron causes huge performance issues.

**Comment by mdtauk** [comment] 2020-11-05 03:59
> @mdtauk Those web stuff ran in IE which was really lightweight. Although Chromium is better, loading it in every process multiple times like Electron causes huge performance issues. Also, Fluent UI should be styled to add WinUI styles like Reveal etc... and not the other way around. Tilt effect can go away but they should consider making Fluent UI more like WinUI as well. Fluent UI is just a rebrand of Office UI Fabric that they are calling Fluent. If designers want to remove this effect, let them remove it but overall WinUI is just becoming like Fluent UI and not the other way around.
>

>... Fluent UI should be styled to add WinUI styles like Reveal etc...
Acrylic within the browser window is being experimented with I believe.

Reveal may well be changing, so possibly in a way that can work on the web too, but @chigy would know more about that.  I made my thoughts clear in the discussion thread #1126 _Proposal: Improve reveal visual_

>... loading it in every process multiple times like Electron causes huge performance issues ...
>
Electron is not a great experience, hopefully Microsoft can transition away from it to PWAs and even better React Native for their web based apps

>... they should consider making Fluent UI more like WinUI ...
>
I very much agree with this.  FluentUI 8.0 is looking to add Design Tokens, and so is WinUI - so hopefully the designs for both will match.

>... Fluent UI is just a rebrand of Office UI Fabric ...
When the name changed, the controls all received a design refresh to adopt more Fluent Design looks and styles.  It started as an opt in, and became the default.

https://github.com/microsoft/fluentui/issues/8038

**Comment by Jaiganeshkumaran** [comment] 2021-01-07 05:41
Asking for the last time, please don't remove this. Although it's not nice plainly with reveal effect it is really good and would like to see it more on the web and mobile. Don't remove this from Windows.

**Comment by dragonDScript** [comment] 2021-01-07 19:03
They are not removing this feature

**Comment by mdtauk** [comment] 2021-01-07 19:07
The intent is to remove the tilt effect when pressing these controls, because it was a Windows Phone and Windows 8 metro effect, and they are moving to a new Fluent Design across Web, Windows, and Mobile Cross-Platform.

**Comment by mdtauk** [comment] 2021-01-07 19:11
I assume the Tilt effect will remain in the WinUI repo, but you would have to retemplate to re-add it to the controls.  Maybe @chingucoding, @chigy, or @anawishnoff will be able to clarify that.

**Comment by chingucoding** [comment] 2021-01-07 19:17
Yes you would need to retemplate controls to add the tilt effect to controls as you need to have the [PointerUpThemeAnimation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.animation.pointerupthemeanimation?view=winrt-19041) and [PointerDownThemeAnimation](https://docs.microsoft.com/en-us/uwp/api/Windows.UI.Xaml.Media.Animation.PointerDownThemeAnimation?redirectedfrom=MSDN&view=winrt-19041). The steps necessary to remove the effect are outlined [here](https://docs.microsoft.com/en-us/previous-versions/windows/apps/jj649432(v=win.10)) and also requires retemplating so adding the effect back will need retemplating too.

**Comment by sylveon** [comment] 2021-01-07 21:56
Retemplating to add/remove this effect is way too much code.

**Comment by chingucoding** [comment] 2021-01-07 22:28
Unfortunately, because how XAML works, beside adding a new API on the button itself to toggle this, there is no other option. With styling concepts like CSS this would be a lot easier, but the animations are part of the VSM and can't be changed without retemplating unfortunately.

**Comment by mdtauk** [comment] 2021-01-07 22:58
@chingucoding  You may want to keep a mental note of that.  It should not be that hard to alter any of the default Theme Transitions for controls - it may be worth trying to add these as lightweight overridable values.

ButtonPointerDownThemeAnimation
ButtonPointerUpThemeAnimation

Both of these can be set to a blank Animation by default, but you can assign a bundled Fluent Animation, or a custom animation to these states.

**Comment by chingucoding** [comment] 2021-01-07 23:26
The issue is that there doesn't seem to be a way to make this a lightweight styling resource. StoryBoard doesn't expose anything that we could bind to a resource, you have to set it's children in XAML. Either you set the children or you don't, however you can'T have an animation resource and use that in there from what I can tell. I'm afraid VSM needs to expose more properties for this to work.

**Comment by mdtauk** [comment] 2021-01-07 23:32
> The issue is that there doesn't seem to be a way to make this a lightweight styling resource. StoryBoard doesn't expose anything that we could bind to a resource, you have to set it's children in XAML. Either you set the children or you don't, however you can'T have an animation resource and use that in there from what I can tell. I'm afraid VSM needs to expose more properties for this to work.

So, it looks like WinUI 3.X will need to create a new API to allow for re-usable Animation or Storyboards - which can be applied to a control's VisualStates

**Comment by chingucoding** [comment] 2021-01-07 23:36
Yes, this needs changes in VSM and Storyboards so will need to wait until WinUI 3.X.

**Comment by mrlacey** [comment] 2021-01-07 23:41
If this is removed but lots of people want it, it should be simple enough to add a `TiltButton` to the community toolkit to make this behavior available to those who want it.

**Comment by mdtauk** [comment] 2021-01-07 23:45
> If this is removed but lots of people want it, it should be simple enough to add a `TiltButton` to the community toolkit to make this behavior available to those who want it.

Very nostalgic, as there was a Windows Phone custom control released to simulate the 3D camera perspective tilts that the DirectUI internal APIs supported in the Windows Phone UX - And later the concept of Theme Animations added to the Windows 8 controls by default.

**Comment by chingucoding** [comment] 2021-01-07 23:45
> If this is removed but lots of people want it, it should be simple enough to add a `TiltButton` to the community toolkit to make this behavior available to those who want it.

Agreed, though you would need a `TiltButton`, `TiltAccentButton` and `TiltRevealButton` to have a consistent experience.

**Comment by mdtauk** [comment] 2021-01-07 23:47
> > If this is removed but lots of people want it, it should be simple enough to add a `TiltButton` to the community toolkit to make this behavior available to those who want it.
> 
> Agreed, though you would need a `TiltButton`, `TiltAccentButton` and `TiltRevealButton` to have a consistent experience.

The tilt effect is also used for the List and Grid Views, which I believe is also going to be removed when they update.

**Comment by sylveon** [comment] 2021-01-08 00:47
> If this is removed but lots of people want it, it should be simple enough to add a `TiltButton` to the community toolkit to make this behavior available to those who want it.

@mrlacey The community toolkit is in C# and therefore I can't use it (my program is in C++). I feel like this might be better suited as a built-in WinUI style

**Comment by Jaiganeshkumaran** [comment] 2021-01-08 09:51
Please don't remove this

**Comment by Jaiganeshkumaran** [comment] 2021-01-08 09:53
> The intent is to remove the tilt effect when pressing these controls, because it was a Windows Phone and Windows 8 metro effect, and they are moving to a new Fluent Design across Web, Windows, and Mobile Cross-Platform.

Why can't they make it part of Fluent? I checked Windows 8 and tilt was present only on the tiles and Windows 10 did add tilt to other controls like buttons while Windows Phone already had it. This is an excuse not a real reason. And if you add reveal to tilt it does look good

**Comment by Jaiganeshkumaran** [comment] 2021-01-08 09:54
Why can't they change or improve this? If not tilt at least provide a Z index based effect for visual feedback

**Comment by mdtauk** [comment] 2021-01-08 10:01
> > The intent is to remove the tilt effect when pressing these controls, because it was a Windows Phone and Windows 8 metro effect, and they are moving to a new Fluent Design across Web, Windows, and Mobile Cross-Platform.
> 
> Why can't they make it part of Fluent? I checked Windows 8 and tilt was present only on the tiles and Windows 10 did add tilt to other controls like buttons while Windows Phone already had it. This is an excuse not a real reason. And if you add reveal to tilt it does look good
>

There are some concerns about how the text rendering gets distorted as the control tilts.  It is an effect that would mess up the ThemeShadow if it was based on the Z-index.  Like the indeterminate Progress Bar and Ring, moving away from the dots to a different animation - it is a Metro and MDL2 (Microsoft Design Language 2) feature, and it is not a feature they wish to continue using, or bring over to their FluentUI and Fast frameworks.

The ThemeAnimations will still be there if individual developers wish to continue using them.

>Why can't they change or improve this? If not tilt at least provide a replacement Z index-based effect for visual feedback
>

If you wish to "improve" or change the Pressed state for Buttons, you could make a clear proposal - but the Tilt effect does seem to be going, so just asking for it to remain will not be very persuasive.

You also have to remember, there has been vocal complaint about this effect, and developers have been asking for ways to remove it.  Making it an option for devs, rather than "forcing" it on them, may be a welcome change.

**Comment by Jaiganeshkumaran** [comment] 2021-01-08 10:06
@mdtauk What's the point of open source if MS doesn't listen to feedback? I'm not telling I don't like design refreshes but this is something unnecessary to remove

**Comment by Jaiganeshkumaran** [comment] 2021-01-08 10:15
Tilt can go away but there needs a click effect for touch feedback. Google has ripple for this but doesn't work well on a mouse

**Comment by mdtauk** [comment] 2021-01-08 11:53
> @mdtauk What's the point of open source if MS doesn't listen to feedback? I'm not telling I don't like design refreshes but this is something unnecessary to remove

I'm suggesting that there may be more feedback asking for it to be removed, than there is asking for it to stay

**Comment by mdtauk** [comment] 2021-01-08 11:54
> Tilt can go away but there needs a click effect for touch feedback. Google has ripple for this but doesn't feel that well on a mouse. I'm not an expert but a plain color change on the pressed state but does not do much

There is a pressed state, s change in colour.  You are suggesting it may not be enough or strong enough a change.  I think I may agree, but that would need to be a new proposal.

**Comment by Tropix126** [comment] 2021-01-09 17:42
I really view tilt as part of what makes fluent unique and would hate it if went.

**Comment by robloo** [comment] 2021-08-17 01:26
This can likely be closed. Fluent v2 Removes the Tilt effect.

**Comment by kmgallahan** [comment] 2023-08-05 19:27
@bpulliam This can be closed, yes?

**Closed** 2023-08-05 20:19 UTC
Labels: feature proposal, team-Controls
