### ISSUE TITLE
NavigationView's Settings button overwrites any custom tooltip set in code

### ISSUE THREAD

**Issue by simop-msft** [microsoft/microsoft-ui-xaml#1731] opened 2019-12-06 14:18 UTC
### Description
If the Settings button's tooltip is customized in code and the NavigationView is in Left mode, it will eventually be overwritten when the pane is open and closed.

### Repro steps
Create a page with the following code, similar to [the sample for access keys in navigation view](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.navigationview?view=winui-2.3#access-keys-for-built-in-elements):

**xaml**
```xml
<mux:NavigationView
	IsSettingsVisible="True"
	Loaded="OnNavigationBarLoaded"
	PaneDisplayMode="Left" >
</mux:NavigationView>
```

**xaml.cs**
```csharp
private void OnNavigationBarLoaded(object sender, RoutedEventArgs e)
{
	var navView = sender as Mux.Controls.NavigationView;
	var rootGrid = VisualTreeHelper.GetChild(navView, 0) as Grid;
	var grid = VisualTreeHelper.GetChild(rootGrid, 1) as Grid;
	var rootSplitView = VisualTreeHelper.GetChild(grid, 1) as SplitView;
	var grid2 = VisualTreeHelper.GetChild(rootSplitView, 0) as Grid;
	var paneRoot = VisualTreeHelper.GetChild(grid2, 0) as Grid;
	var border = VisualTreeHelper.GetChild(paneRoot, 0) as Border;
	var paneContentGrid = VisualTreeHelper.GetChild(border, 0) as Grid;
	var settingsNavPaneItem = VisualTreeHelper.GetChild(paneContentGrid, 6) as Mux.Controls.NavigationViewItem;

	ToolTipService.SetToolTip(settingsNavPaneItem, "Settings tooltip");
}
```

Launch the application.

### Behavior
Initially, the Settings button has the custom tooltip; when collapsing the pane, this tooltip becomes "Settings", the Mux provided one; when opening the pane again, the button has no tooltip at all.

### Expected
The control should keep the code-defined tooltip for all its lifetime.

### Version information

NuGet package version: 2.2.190917002
OS build: 19039
Form factor: Desktop

### Suggestions
It appears that this tooltip's value is changed when opening and closing the pane. I guess this behavior was put in place because a tooltip displaying "Settings" next to the button showing the same text was found unhelpful, so it is removed when the pane is opened.

The problem then is that customizing the tooltip in code doesn't work because it is overwritten when the pane is closed/open.

I suggest not changing the value of the tooltip when opening and closing, and live with a useless tooltip.

An increment other this would be to have the tooltip display the name of the button, and then its first keyboard accelerator in parentheses: "Settings (Ctl + G)"; this behavior is frequent across the platform, although it is not consistent on all controls. That way the tooltip would be useful in all situations.

**Comment by YuliKl** [comment] 2019-12-09 19:00
@simop-msft Thank you for reporting this. I think the best solution here would be to provide a SettingsTooltip property on NavigationView. The current code snippet is a hack, we don't really want to force users to walk the visual tree.

Not showing any tooltip when the pane is open is indeed the intended behavior. Our goal is to avoid unnecessary tooltips, and showing the same text that's already on screen is quite redundant and a poor user experience.

I'm going to close this bug but I'm hoping you can open a new feature request instead to make Settings item's tooltip easier to customize.

**Closed by YuliKl** 2019-12-09 19:00 UTC
Labels: needs-assignee-attention
