### ISSUE TITLE
WebView in ContentDialog does not work.

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#6427] opened 2021-12-02 07:55 UTC
### Describe the bug

links buttons in webview are not clickable.

### Steps to reproduce the bug

1, run the demo in release mode.
2, click links in webview (not clickable).
3, after remove `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />`, it works.

[BUG.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7640027/BUG.zip)

### Screenshots

![image](https://user-images.githubusercontent.com/12285582/144380479-24846009-eb01-4d71-b024-a733f35dc77f.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by Link1J** [comment] 2022-01-10 19:00
Reporting two unrelated thing as one bug.

I can't replicate the WebView bug mentioned in the title on Windows 11. In seems to be behaving correctly and opening the links in the browser. It is possible that you have uninstalled Edge, which could create problems like the one you are seeing.

The `ContentDialog` not changing size is not a bug with WinUI2 or the System XAML. In fact it is working as you asked. Maybe don't set the `MaxWidth` of the `ContentDialog`.

**Comment by HppZ** [comment] 2022-01-27 12:33
after maximized:
![image](https://user-images.githubusercontent.com/12285582/151359584-76f427c1-136c-4f9b-99a3-cebce3d60e16.png)

**Comment by HppZ** [comment] 2022-01-27 12:37
@chingucoding HELP PLEASE.

**Comment by chingucoding** [comment] 2022-01-27 20:36
So it seems that the corner radius being set with the WinUI styles is causing this issue. If you add the following to your `ButtonBase_OnClick` function before opening the content dialog, it works (note that you need to use the API contract since CornerRadius is not available on every Windows 10 version):

```c#
if(ApiInformation.IsApiContractPresent("Windows.Foundation.FoundationContract", 7))
{
    _verificationDialog.CornerRadius = new CornerRadius(0);
}
```
![Screenshot of WebView working inside a ContentDialog](https://user-images.githubusercontent.com/16122379/151439529-c07c6914-43e6-476c-87ab-734a42bcf0a8.png)

**Comment by HppZ** [comment] 2022-02-14 03:30
> So it seems that the corner radius being set with the WinUI styles is causing this issue. If you add the following to your `ButtonBase_OnClick` function before opening the content dialog, it works (note that you need to use the API contract since CornerRadius is not available on every Windows 10 version):
> 
> ```cs
> if(ApiInformation.IsApiContractPresent("Windows.Foundation.FoundationContract", 7))
> {
>     _verificationDialog.CornerRadius = new CornerRadius(0);
> }
> ```
> 
> ![Screenshot of WebView working inside a ContentDialog](https://user-images.githubusercontent.com/16122379/151439529-c07c6914-43e6-476c-87ab-734a42bcf0a8.png)

when will you fix it please?

**Comment by chingucoding** [comment] 2022-02-14 17:58
@HppZ I am not working for Microsoft so I can't tell you when this will be fixed. The problem is that the issue probably somewhere in WebView which means there isn't much one can do here beside using the workaround.

**Comment by HppZ** [comment] 2022-02-15 03:28
> @HppZ I am not working for Microsoft so I can't tell you when this will be fixed. The problem is that the issue probably somewhere in WebView which means there isn't much one can do here beside using the workaround.

@chingucoding Thank you.

**Comment by StephenLPeters** [comment] 2022-02-24 21:52
This is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5299  The issue is in system xaml and has been fixed for later versions of windows however is still present for some Win10 versions. Resolving this issue is challenging and Chingucoding's suggestion of removing the corner radius is the best work around we have.

**Closed by StephenLPeters** 2022-02-24 21:52 UTC
Labels: needs-triage
