### ISSUE TITLE
Microsoft.UI.Xaml.Markup.XamlParseException: 'XAML parsing failed.' is useless and more descriptive error is needed

### ISSUE THREAD

**Issue by ivanicin** [microsoft/microsoft-ui-xaml#7939] opened 2022-11-20 10:21 UTC
I am trying to port the UWP app to WinUI 3, but with current support it is next to impossible.

I have thousands of code lines in XAML in UWP app, the longest file is 800 lines. Unfortunately in multiple cases all I get is a runtime error:

> 
> Exception thrown: 'Microsoft.UI.Xaml.Markup.XamlParseException' in WinRT.Runtime.dll
> WinRT information: Element not found.
> 
> An exception of type 'Microsoft.UI.Xaml.Markup.XamlParseException' occurred in WinRT.Runtime.dll but was not handled in user code
> WinRT information: Element not found.

This causes the crash.

As this isn't descriptive it is extremely hard to find the error. I had success in one file by disabling and enabling parts of the code and see when it runs and when it crashes. But if there are multiple errors this becomes very hard. On top of that I need to disable and enable code in .cs file which takes immense time. 

I am aware that this error can happen because some resources are not included, but I have gone through that and App.xaml now has exactly the same resource like before and there aren't other XAML resources referenced in files.

**Comment by bpulliam** [comment] 2022-12-07 23:53
Closing as duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/7033.

**Closed by bpulliam** 2022-12-07 23:53 UTC
Labels: needs-triage

**Comment by ivanicin** [comment] 2022-12-08 09:54
@bpulliam that bug is already closed. This issue exists, you can see that also by the fact that two people have opened it again since it was closed. 

So please reopen this issue.
