### ISSUE TITLE
Changing target .NET from 6.0 to 5.0 and change back corrupts the project

### ISSUE THREAD

**Issue by hatsune-miku** [microsoft/microsoft-ui-xaml#8117] opened 2023-01-20 05:21 UTC
### Describe the bug

In a new WinUI3 project, changing the "Target framework" property from 6.0 to 5.0 and changing back to 6.0 immediately seems to corrupt the project making it unable to compile & run.

### Steps to reproduce the bug

1. Open VS, create new "Blank App, Packaged (WinUI 3 in Desktop)" project, named "test".
2. Press F5 to start debugging and the project builds and runs successfully as expected. The example "Click Me" button works as expected.
3. Right click the project in "solution explorer" and select "Properties".
4. Change "Target framework" from 6.0 to 5.0. An error saying "A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "" instead of a number, in condition "'$(TargetPlatformVersion)' < '10.0.18362.0'".  C:\Users\<username>\.nuget\packages\microsoft.windowsappsdk\1.2.221109.1\buildTransitive\Microsoft.InteractiveExperiences.Common.targets" appeared immediately.
![e1](https://user-images.githubusercontent.com/20541974/213621682-8fdae828-8808-412c-8b54-85cd86b0f7bc.png)

5. Change "Target framework" back to 6.0.
6. Now, building the project will always fail without errors.

```
Rebuild started...
1>------ Rebuild All started: Project: test, Configuration: Debug x86 ------
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========
========== Elapsed 00:00.118 ==========
Restored C:\Users\<username>\source\repos\test\test.csproj (in 18 ms).
```
7. Close solution and reopen it.
8. Solution explorer shows the project as "(unloaded)" and project files are not listed. Building still fails.
![image](https://user-images.githubusercontent.com/20541974/213621846-3028758c-bf06-45ff-9696-f70a0b588e14.png)

### Expected behavior

After changing target .NET version back to 6.0, the project should be the same as before, and be able to build and run correctly.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (21H1): Build 19043

### Additional context

Tried on two devices and both reproduced the problem.

**Comment by manodasanW** [comment] 2023-01-20 21:54
The issue is using the VS UI to change the TFM drops the Windows Version information in the TFM and you need to set those fields again.  See [here](https://developercommunity.visualstudio.com/t/Using-C-project-properties-to-change-Ta/10220321?ref=native&refTime=1670006497287&refUserId=3ecae279-b085-41e5-8176-afdfb2972795).

**Comment by DarranRowe** [comment] 2023-01-21 16:00
As a work around, you could manually edit the project file itself.
If you open the raw xml view of the cs project file and find the TargetFramework tag, you should find something along the lines of:
```
<TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
```
This is a combination of the target .Net framework version and the target Windows version. Changing this to net5.0 will target .Net 5.0, changing this to net7.0 will target .Net 7.0.
As an aside, this can be used to recover a project that you corrupted the settings in. If you manually edit the project and set the full target framework value (netx.0-windows10.0.xxxxx.0), obviously setting the x's to the versions that you want to target, then the project will start working correctly again.
But yes, this is a work around.

**Comment by hatsune-miku** [comment] 2023-01-21 16:12
> As a work around, you could manually edit the project file itself. If you open the raw xml view of the cs project file and find the TargetFramework tag, you should find something along the lines of:
> 
> ```
> <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
> ```
> 
> This is a combination of the target .Net framework version and the target Windows version. Changing this to net5.0 will target .Net 5.0, changing this to net7.0 will target .Net 7.0. As an aside, this can be used to recover a project that you corrupted the settings in. If you manually edit the project and set the full target framework value (netx.0-windows10.0.xxxxx.0), obviously setting the x's to the versions that you want to target, then the project will start working correctly again. But yes, this is a work around.



> The issue is using the VS UI to change the TFM drops the Windows Version information in the TFM and you need to set those fields again. See [here](https://developercommunity.visualstudio.com/t/Using-C-project-properties-to-change-Ta/10220321?ref=native&refTime=1670006497287&refUserId=3ecae279-b085-41e5-8176-afdfb2972795).

Thanks a lot! these are really helpful

**Comment by DJRM2021** [comment] 2023-01-22 21:59
For the record, this issue also happens when you change target framework from .Net 6 to 7.

**Comment by JesseCol** [comment] 2024-01-17 21:47
This should be fixed now in Visual Studio, thanks!

**Closed by JesseCol** 2024-01-17 21:47 UTC
Labels: bug, team-Markup
