### ISSUE TITLE
Xaml Islands, ms-settings with WPF app as admin mode won't launch

### ISSUE THREAD

**Issue by crutkas** [microsoft/microsoft-ui-xaml#3591] opened 2020-11-10 18:02 UTC
**Describe the bug**

**Steps to reproduce the bug**

1. Create an application with a XAML island v1
2. Have a Hyperlink to ms-settings:colors
3. launch application under admin

**Expected behavior**

Colors launches, with a pure WPF implementation, this works as expected

**Screenshots**

![image](https://user-images.githubusercontent.com/1462282/98712735-84069a80-233b-11eb-8b00-23137c556700.png)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml.2.5.0-prerelease.200923002]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

https://github.com/microsoft/PowerToys/issues/7819 for finding issue

**Comment by ranjeshj** [comment] 2020-11-11 00:12
@chrisglein @MikeHillberg  I remember there was some issue with launching from hyperlink inside a XAML island, but fail to recollect it.

**Comment by chrisglein** [comment] 2020-11-11 23:17
Believe that the launch APIs may have assumptions about package identity, so Hyperlink may have issues outside of that context?
We have an existing issue report on this.
Duplicate of #2357.

**Closed by chrisglein** 2020-11-11 23:17 UTC
Labels: Area-HyperlinkButton, area-Islands, needs-triage, team-Controls, team-Framework
