### ISSUE TITLE
AppWindow size and position doesn't persist in next launch

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/microsoft-ui-xaml#2744] opened 2020-06-24 12:35 UTC
**Describe the bug**

If application is programmatically closed by `Application.Current.Exit()`, the next time the app starts it doesn't start on the same position it was closed before. Also, the size isn't the same as before.

**Steps to reproduce the bug**

1. Create a simple app implementing a button which tries to exit the app programmatically with `Application.Current.Exit()`.
2. Launch the app.
3. Resize the app window and move it to another place.
4. Click on the implemented button to exit the app.
5. Launch the app again.

**Expected behavior**
The app should start in the same position and size as it was closed before just like the close button behaves.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Currently the only way to exit the app is by `ApplicationView.TryConsolidateAsync()` which isn't great to use for multi-window setup.

**Comment by ranjeshj** [comment] 2020-06-24 23:18
@Austin-Lamb @marb2000 Is this a known issue ?

**Comment by jschwizer99** [comment] 2021-03-24 09:59
I face a related issue. It seems that with `Close();` or `Application::Current().Exit();` myWin32 WinUI Reunion 0.5 application does not exit gracefully. In order to get a proper clean-up, the deconstructors should be called. This is essential if there is a lot of C++ business code behind it. In debug mode, this relates to a long list of memory leak reporting.
As `TryConsolidateAsync()` cannot be used anymore on Preview 3 / Reunion 0.5 due to the missing `GetForCurrentView()` access do to know a method to close the WinUI App gracefully.

@marb2000 Can you advise which approach should be used to close a WinUI Reunion 0.5 app gracefully? The method should correctly remember the Windows position and all resources should be correctly destroyed (no hard exit). Many thanks in advance.

**Comment by agnauck** [comment] 2021-04-06 17:20
When I execute
`Application.Current.Exit();`

on a simple test app I get the following exception;

`Exception thrown at 0x0975383D (Microsoft.ui.xaml.dll) in WinUi3Test.exe: 0xC0000005: Access violation reading location 0x0000016C.`

**Comment by marb2000** [comment] 2021-04-06 17:53
@soumyamahunt AppWindow is not supported in Desktop WinUI 3.  So I'm assuming that you refer to a window object that derives from Microsoft.UI.Xaml.Window. If so, this is a dupe of #2680. Restore Window's size and position is a feature not implemented yet. 

@agnauck About closing the App. I didn't get any exceptions when I do Application.Current.Exit() in Desktop. Are you using Reunion 0.5? If so, and you still have the issue, can you open a separate bug with the repro, please?


Closing this ug as dupe and waiting for @agnauck to open a bug if needed.

**Closed by marb2000** 2021-04-06 17:53 UTC
Labels: needs-winui-3, team-Reach

**Comment by agnauck** [comment] 2021-04-07 08:18
@marb2000 I can confirm that Application.Current.Exit() works fine in a new blank App for Desktop and Reunion 0.5

It looks like some 3rd party library or my own code is causing it. Just hard to find without proper error messages 😉

**Comment by agnauck** [comment] 2021-04-07 08:55
The exceptions happens when a **_NavigationView_** is present in the UI.
Using this XAML I can reproduce in App for Desktop and Reunion 0.5

XAML
```
<Window
    x:Class="WinUi3Test2.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinUi3Test2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition />
        </Grid.RowDefinitions>

        <MenuBar Grid.Row="0">
            <MenuBar.Items>
                <MenuBarItem Title="File">
                    <MenuBarItem.Items>
                        <MenuFlyoutItem Click="MenuFlyoutItem_Click" Text="Exit" />
                    </MenuBarItem.Items>
                </MenuBarItem>
            </MenuBar.Items>

        </MenuBar>
        <NavigationView Grid.Row="1">
            <NavigationView.MenuItems>
                <NavigationViewItem
                    Content="Menu Item1"
                    Icon="Play"
                    Tag="SamplePage1" />
                <NavigationViewItem
                    Content="Menu Item2"
                    Icon="Save"
                    Tag="SamplePage2" />
                <NavigationViewItem
                    Content="Menu Item3"
                    Icon="Refresh"
                    Tag="SamplePage3" />
                <NavigationViewItem
                    Content="Menu Item4"
                    Icon="Download"
                    Tag="SamplePage4" />
            </NavigationView.MenuItems>
            <Frame>
                <Button>Click Me</Button>
            </Frame>
        </NavigationView>
    </Grid>
</Window>
```

code behind
```
public sealed partial class MainWindow : Window
{
    public MainWindow()
    {
        this.InitializeComponent();
    }

    private void MenuFlyoutItem_Click(object sender, RoutedEventArgs e)
    {
        Application.Current.Exit();
    }
}
```
