### ISSUE TITLE
Proposal: Bringing WebView2 to WinUI 2

### ISSUE THREAD

**Issue by predavid** [microsoft/microsoft-ui-xaml#5610] opened 2021-08-02 20:44 UTC
# Proposal: Bringing WebView2 to WinUI 2

## Summary
Our team has built a prototype that brings the WebView2 control from WinUI 3 into WinUI 2, with the same API and behavior found in the [WinUI 3 version](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fmicrosoft-ui-xaml-specs%2Fblob%2Fmaster%2Factive%2FWebView2%2FWebView2_spec.md&data=04%7C01%7Cpredavid%40microsoft.com%7Cbb0ee108727f46dbabb308d9512dae3e%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637630078904161153%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DMW5U%2B%2F7sX3XX1vOIZ4UHuzZeGYfnTnAatjxWnIyHq4%3D&reserved=0)
## Rationale
Many of you in the community have requested that we make WebView2 available in UWP apps for your PC-based scenarios. We believe we can have this control worked into WinUI 2 builds very soon, with a debut in WinUI 2.7 previews.  

## Scope
As discussed earlier in the [WinUI3 version of the spec ](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fmicrosoft-ui-xaml-specs%2Fblob%2Fmaster%2Factive%2FWebView2%2FWebView2_spec.md&data=04%7C01%7Cpredavid%40microsoft.com%7Cbb0ee108727f46dbabb308d9512dae3e%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637630078904171149%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XgYcaFam5%2F5HV3g2ov%2FUL3DOg5WppuV%2FlG28UwYQrNc%3D&reserved=0)this version of WebView 2 would only work on PC-class devices, offering the full range of capability found in the WinUI 3 variant. Xbox, HoloLens and XAML Island support require quite a bit of additional work. So those devices/scenarios may be considered at a future point in time, but not for a sooner offering of WebView2 in WinUI2. 

WinUI community: Please share your thoughts about adopting WebView2 via WinUI2

**Comment by Poopooracoocoo** [comment] 2021-08-03 16:38
:/ no xbox??? idk what happened to the whole "universal" thing

**Comment by ayamadori** [comment] 2021-08-04 04:14
Microsoft Edge WebView2 roadmap
https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap

> The WebView2 team is planning the following major efforts for future updates.
> 
> - UWP Preview
> - MacOS Preview
> - Xbox Preview
> - HoloLens Preview

**Comment by predavid** [comment] 2021-08-04 16:30
Yes, @ayamadori  and @Poopooracoocoo - Xbox and other non-PC device support require quite a bit of additional work. So those devices/scenarios are in consideration for a future point in time (as called out in the [Edge roadmap](https://docs.microsoft.com/en-us/microsoft-edge/webview2/roadmap)) , just not for a sooner preview offering of WebView2 in WinUI2 that supports UWP apps for PC-based scenarios

**Comment by Pinox** [comment] 2021-08-04 16:54
I'll take what I can get, thanks for throwing UWP a lifeline, !!  If we could only get .net standard 2.1 support in UWP that will be a major game changer ;))

**Comment by robloo** [comment] 2021-08-05 01:29
Bringing WebView2 over shouldn't be a question. It's almost mandatory and needed for a wide number of things.

For example: There is a fundamental issue with WebView that prevents it from handling redirect URLs and custom schemes without showing a confirmation dialog every single time. That is a massive usability problem and affects all sorts of authentication flows.

This issue hopefully is fixed in WebView2. It has been a long-standing plan to migrate to WinUI3; however, that is essentially dropped at this point with the removal of UWP from the WinUI3 roadmap. Bringing over WebView2 would give some life to UWP apps and help with the state of limbo.

**Comment by BreeceW** [comment] 2021-08-05 08:20
My app relies on a web view that loads a page outside of my control. It’s almost certainly a matter of time before it breaks in EdgeHTML, so being able to switch to WebView2 on PCs would help me future-proof my app, as I am far from ready to move to WinUI 3 from UWP XAML.
I would really appreciate WebView2 in WinUI 2.

**Comment by sylveon** [comment] 2021-08-05 08:33
I would really appreciate if WebView 2 supported XAML islands, as it is still mostly the same kind of API as PC UWP (I believe most of the work would be replacing assumptions of 1 CoreWindow by thread and instead use the XamlRoot class and property) and would give XAML islands based apps a similar lifeline before making the big jump to WinUI 3 once it comes to feature parity with system XAML islands.

Also, nit: it's mentioned that WebView 2 would only work on PC-class devices, and XAML islands is listed along unsupported platforms, but is a PC-only API to host UWP controls, not a different platform. Maybe mention the lack of XAML Islands support separately from unsupported platforms?

**Comment by ayamadori** [comment] 2021-08-05 12:32
I love to hear this proposal.
Because apps are mostly used on PC, I can understand the priority.

Also, nit: Are there the plan to support Windows 10 Team?
https://docs.microsoft.com/en-us/surface-hub/surface-hub-2020-update-whats-new

**Comment by EzraWard** [comment] 2021-08-05 13:09
This would be a much-needed addition for UWP apps. My team uses the current WebView and being able to migrate those to WebView2 without needing to migrate our entire app to WinUI3 would be very valuable.

**Comment by Arlodotexe** [comment] 2021-08-05 15:00
Definitely need this -- I have an application with core functionality that relies on a service which is only provided via Web, but the company behind the service does not keep it working on Edge Legacy. They seem to break and fix it every other day and it's very frustrating. They full support Chromium, so WebView2 in UWP would be a lifesaver!

**Comment by michael-hawker** [comment] 2021-08-05 15:54
We've seen a lot of web developers abandoning support on their pages for Edge Legacy as the official support for the browser has lapsed, and it's not clear in any of that documentation that the engine should still be supported as part of the OS. This makes it difficult for folks using WebView to continue to do so.

I know this would help immensely with the Monaco editor component as Monaco has moved on from Edge Legacy as well.

**Comment by shaheedmalik** [comment] 2021-08-06 13:07
I rather UWP be supported by WinUI 3

**Comment by HumbertoML** [comment] 2021-08-07 21:12
webview 1 crashes on some websites, webview 2 is more optimized, the problem is that I am in a uwp app

**Comment by EP012014** [comment] 2021-08-15 03:27
Hope it brings a seamless scrolling experience.
My solution is to use UWP Scrollviewer instead of the one that Edge brings as default.

**Comment by HppZ** [comment] 2021-08-18 14:13
GREAT!!!!!!!!!!

**Closed** 2021-08-22 20:01 UTC
Labels: feature proposal, working on it, react-native-windows, wct

**Comment by emanuelmartin** [comment] 2021-09-08 22:47
Any updates on this?

**Comment by michael-hawker** [comment] 2021-09-08 22:57
@emanuelmartin what updates are you looking for? The PR was merged and it is in the latest pre-release NuGet package.

**Comment by tipa** [comment] 2021-09-09 06:19
I personally am waiting for an update on when the WebUI2 will be ready to use in my production apps.
Currently I am unable to submit apps with the pre-release package to the Store as it fails with a submission error.
One of my apps main component is an embedded website which recently stopped working on the old WebView so now I am eagerly waiting to be able to switch to WebView2 (even though that also means I would lose ARM support as it stands now)

**Comment by jevansaks** [comment] 2021-09-09 17:23
> I personally am waiting for an update on when the WebUI2 will be ready to use in my production apps.
> Currently I am unable to submit apps with the pre-release package to the Store as it fails with a submission error.
> One of my apps main component is an embedded website which recently stopped working on the old WebView so now I am eagerly waiting to be able to switch to WebView2 (even though that also means I would lose ARM support as it stands now)

There are changes coming to the WebView2 nupkg in a couple of weeks that will resolve the WACK issues and will make compiling for Arm32 easier (but the WebView2 runtime doesn't have Arm32 support so it would only compile but you couldn't run that code on Arm32).

**Comment by tipa** [comment] 2021-09-09 17:28
Thanks for the clarification! If I removed ARM32 support for that app, would ARM32 devices (like the Surface Pro X) be able to install and run the x86 or x64 variant of my app?

**Comment by sylveon** [comment] 2021-09-09 18:06
The SPX is not an ARM32 device. It is an ARM64 device. There are no ARM32 devices running Windows 10.

**Comment by robloo** [comment] 2021-09-09 20:25
This is a **huge lifeline** and I appreciate the WinUI team bringing this control over to UWP.

We have been consistently backed into a corner with UWP and this provides the much needed time to smooth migration to WinUI3 (WinUI3 is still too unstable and missing too many features).

A major feature scheduled for the next release required online authentication flows that use redirect URLs (pretty standard). This was not supported at all in WebView1 because the NavigationStarting event was never invoked for redirect URLs so the app has to be registered as a handler of the link and receive it externally from the system. Several times redirects are missed or require the user to confirm in a dialog they want to receive a seemingly strange URL with their app (the redirect). To fix this, a year or so ago it was planned to switch to WinUI3 and WebView2 since this issue has existing in WebView1 since the very beginning of UWP (Nobody has ever been able to use redirects since the beginning... let that sink in). Then with the cancellation of UWP support in WinUI3 we were dead in the water. The only option seemed to be a time consuming rewrite into a framework that still isn't ready (WinUI3).  WebView2 now provides the much needed time for WinUI3 to stabilize and keep the app on track.

WebView2 has now been fully integrated into the mentioned app and tested to fully work. WebView2 properly invokes the NavigationStarting event on redirects. Again, I really appreciate the time the team spent on this!

**Comment by tipa** [comment] 2021-10-17 10:38
> The SPX is not an ARM32 device. It is an ARM64 device. Ignoring Windows 10 IoT, there are no ARM32 devices running officially supported Windows 10.

Is the WebView2 supposed to work on the SPX? I just updated my app with the WebView2 and a user reported that my app is now crashing on his SPX.

**Comment by pheidler** [comment] 2024-01-25 21:43
> > The SPX is not an ARM32 device. It is an ARM64 device. Ignoring Windows 10 IoT, there are no ARM32 devices running officially supported Windows 10.
> 
> Is the WebView2 supposed to work on the SPX? I just updated my app with the WebView2 and a user reported that my app is now crashing on his SPX.

It's been a while, but did you ever resolve this issue? I'm encountering the same problem.
