### ISSUE TITLE
Proposal: I suggest there should be a property to set the Header to left side in TabView

### ISSUE THREAD

**Issue by AlexZhangrj** [microsoft/microsoft-ui-xaml#3508] opened 2020-10-28 07:34 UTC
'm doing something using UWP TabView. I want to let the Headers be on the left side of the TabView Controller. I found there is a way to do this in WPF, while we can use TabStripPlacement="Left" and use LayoutTransform in DataTemplate.
That's a perfect way to show my design.
But there is no TabStripPlacement property in UWP.
So, I suggest we should add a property in TabView.

**Comment by Felix-Dev** [comment] 2020-10-28 09:40
@AlexZhangrj Does proposal https://github.com/microsoft/microsoft-ui-xaml/issues/2194 cover your suggestion (if not, it's probably better to add your suggestion there so we can use one issue to track these placement requests and close this one as a duplicate).

**Comment by stmoy** [comment] 2020-10-28 23:34
This is duplicate of #2194.

**Closed by stmoy** 2020-10-28 23:34 UTC
Labels: area-TabView, feature proposal, team-Controls
