### ISSUE TITLE
Unpackage App Drag and drop crash when run as administrator

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#7548] opened 2022-07-30 04:39 UTC
### Describe the bug

Unpackage App Drag and drop crash when run as administrator

![image](https://user-images.githubusercontent.com/16729017/181872532-f7db3d43-cb69-46b9-a69c-f3528208b608.png)

### Steps to reproduce the bug

1. run as administrator
2. drag item
3. crash
4.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621, Windows 11 (21H2): Build 22000

### Additional context

same as windows 10

**Comment by bpulliam** [comment] 2022-11-17 17:45
Closing as a duplicate of #7690.

**Closed by bpulliam** 2022-11-17 17:45 UTC
Labels: bug, needs-triage, team-Rendering, product-winui3, area-DragAndDrop, Crash
