### ISSUE TITLE
PopUp not open in the appwindow in UWP

### ISSUE THREAD

**Issue by sampathnarine** [microsoft/microsoft-ui-xaml#4676] opened 2021-03-29 11:03 UTC
**Describe the bug**

I have updated the uwp build version 19401 and I have a button in the window and by click i have opened new appwindow. Now i have another button in the AppWindow to open the popup. Here comes the issue.

PopUp opens in the primary window and it not shown on the secondary window. Please refer the below gif

**Note :**
This issue do not occurs when opened in the normal window. And this issue occurs only in the AppWindow

**Steps to reproduce the bug**

1. Run the sample
2. Click the OpenNewWindow Button
3. New window opens and click the button open the popup.

**Observed behavior**

Popup opens in the primary window.

**Expected behavior**

Popup Should open in the window where the button to show popup is clicked.

**Screenshots**

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/63052528/112823195-998c1f00-90a6-11eb-9952-bf0eada83482.gif)

**Version Info**

- **VS Version:** 

![image](https://user-images.githubusercontent.com/63052528/112824000-9cd3da80-90a7-11eb-94da-6412a4043e65.png)

OS Version

![image](https://user-images.githubusercontent.com/63052528/112827250-b414c700-90ab-11eb-868c-5de1deb81d49.png)

**Uwp Target Version**

![image](https://user-images.githubusercontent.com/63052528/112824149-cc82e280-90a7-11eb-9522-e619cc521356.png)

Windows app type:

This issue occurs in the UWP platforms.

Sample : 
[UwpAppWindowSample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6221244/UwpAppWindowSample.zip)

**Comment by StephenLPeters** [comment] 2021-03-29 23:08
@sampathnarine what version of winui are you using for this?

**Comment by sampathnarine** [comment] 2021-03-30 09:34
Hi @StephenLPeters ,

 This issue occurs in the normal uwp project and not in the win ui version. Please refer the below version of Uwp project.

![image](https://user-images.githubusercontent.com/63052528/112967787-3d3e0380-9169-11eb-86ae-6cdf2f3f9277.png)

**Comment by StephenLPeters** [comment] 2021-03-30 23:29
@codendone and @kmelmon fyi

**Comment by codendone** [comment] 2021-03-31 05:24
The Popup needs to know which XamlRoot it being shown for. Try adding this line before opening the popup:
```
   mypop.XamlRoot = this.XamlRoot;
```

**Comment by sampathnarine** [comment] 2021-04-01 05:17
Hi @codendone,

Thanks for the replay.

I have tried out your solution and it works fine for one case. But for another case it is not fixed. Please find case below.

I have created the custom Contentcontrol(PopupHostExt). I have customized the control by loading the popup. I have shown the PopupHostExt when the button is clicked. Now the same issue occurs. The popup shown in the primary window. I have tried out by setting xamlroot to the popup but it not works. Please find the below gif for the replication. I have also attached the sample here. Please help me to sort out this issue.

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/63052528/113246557-e0f8f200-92d6-11eb-94d8-2f846ddeb398.gif)

Sample : 
[Sample.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6241178/Sample.zip)


Regards,
Sampath Narayanan.S

**Comment by codendone** [comment] 2021-04-01 06:00
The problem is that the popup is being opened before it is added to the tree, so it can't lookup the right XamlRoot. This happens because while applying the style template the IsOpen binding already evaluates as True, so the popup immediately opens even though its remaining markup properties (IsLightDismissEnabled="True" in this sample) haven't yet been set and the popup hasn't been added to its parent element. We could consider delaying the IsOpen action, and there is another issue discussing that potential change for WinUI3.

The solution is to ensure the template is applied prior to having IsOpen bind to True. You could do that by having the template be there well in advance, or delay setting the binding until after the template has been applied, or just force creating the template:
```
    popUpHostExt.ApplyTemplate();
```

Note that the two-way binding to old PopUpHostExt objects in the sample makes the button only work once. Avoiding recreating at the start of the function is one possible solution, so this version combines both fixes to get a good result:
```
        private void Open_Click(object sender, RoutedEventArgs e)
        {
            if (this.PopUpPresenter.Child != null)
                return;

            popUpHostExt = new PopUpHostExt();
            this.PopUpPresenter.Child = popUpHostExt;
            Windows.UI.Xaml.Data.Binding binding = new Windows.UI.Xaml.Data.Binding
            {
                Source = OpenButton,
                Path = new PropertyPath("IsChecked"),
                Mode = BindingMode.TwoWay
            };
            popUpHostExt.ApplyTemplate();
            popUpHostExt.SetBinding(PopUpHostExt.IsOpenProperty, binding);
        }
```

**Comment by sampathnarine** [comment] 2021-04-08 06:12
Hi @codendone,

The provided solution works fine for me. Thanks for your update.

Regards,
Sampath Narayanan.S

**Comment by codendone** [comment] 2021-04-09 02:34
I'm glad that's working for you. I'm closing this issue since this has been solved.

**Closed by codendone** 2021-04-09 02:34 UTC
Labels: area-Flyouts, needs-triage, needs-winui-3, team-Rendering
