### ISSUE TITLE
Custom title bar drag works on packaged app but not unpackaged

### ISSUE THREAD

**Issue by chaseplumlee** [microsoft/microsoft-ui-xaml#6634] opened 2022-01-23 20:23 UTC
### Describe the bug

With all things equal except the csproj configured to  include `<WindowsPackageType>None</WindowsPackageType>` for an unpackaged app and the build set to unpackaged. I am unable to drag the window using a custom title bar.  As soon as I revert the csproj back to exclude `<WindowsPackageType>None</WindowsPackageType>` and change the build back to Package the drag functionality behaves as expected.

### Steps to reproduce the bug

1.) Using the WinUI 3 Blank App template, create a project. 

2.) Follow steps to configure for unpackaged app. 
[https://docs.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app?pivots=winui3-unpackaged-csharp](url)

3.) Follow title bar example [https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0](url)

### Expected behavior

Expected to be able to drag window with custom title bar and have the application unpackaged.

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Windows version

October 2020 Update (19042)

**Comment by kmgallahan** [comment] 2022-01-23 22:34
Dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/6185 with workaround in https://github.com/microsoft/WindowsAppSDK/issues/1815

**Closed** 2022-03-03 00:19 UTC
Labels: duplicate, needs-triage, team-Reach, area-TitleBar
