### ISSUE TITLE
Performance Issue, UI Thread ~30fps

### ISSUE THREAD

**Issue by KenionX** [microsoft/microsoft-ui-xaml#7290] opened 2022-06-28 18:59 UTC
### Describe the bug

Any UI interaction is limited to arround 30 frames per second.
I messured how often the mouse events are fired ~1000/s however calling any UI function will not execute beyond 30fps, in my case I use canvas SetLeft / SetTop

I recorded also the framerate of the Dispatcher which 1 to 1 reflects why everything is lagging

You can also reproduce it in the "Color Picker" on controlls gallery

![chrome_d4jl9mEYb9](https://user-images.githubusercontent.com/63214030/176261660-2e07fbd8-2c7c-4050-90f8-d6224a09c13b.gif)

### Steps to reproduce the bug

- Open WinUI3 Controlls Gallery
- Move the Colorpicker quick arround

- Empty project with a canvas and a mouse move event
- Put any type of UI element inside it
- Write some logic to move the element with the mouse

### Expected behavior

Atleast 60fps or screen refreshrate.

### Screenshots

![image](https://user-images.githubusercontent.com/63214030/176333254-d4bfcd7d-9b5f-406d-bc4e-8fc131da7068.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.1

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

The experience on a 144hz+ screen is incredible bad, everything feels laggy which makes the experience not enjoyable.
It almost feels like there is some hardcoded fps cap, using a swapchain from Win2D produces 2.000fps without issues.

Maybe there is a way to increase the frame rate on the UI thread? :)

**Comment by kmgallahan** [comment] 2022-06-29 00:37
UI thread isn't limited to 30 fps, rather you are interacting with the ColorPicker which has poor performance due to it updating the binding to the selected color per-pixel change.

Dupe of #2683

**Comment by KenionX** [comment] 2022-06-29 01:05
> UI thread isn't limited to 30 fps, rather you are interacting with the ColorPicker which has poor performance due to it updating the binding to the selected color per-pixel change.
> 
> Dupe of #2683

Are you sure? Scrolling, Dragging, Everything is slow and laggy (even on almost empty projects). On wpf / uwp apps its way better. You wont see the issue on a 60hz screen  👍 

Maybe I need better hardware, RTX3090 and Ryzen5950 might be to slow for a good expierence

**Comment by kmgallahan** [comment] 2022-06-29 01:12
@marb2000 I think I've seen you mention there is (or is no longer) a 30 fps lock?

**Comment by KenionX** [comment] 2022-06-29 01:46
> @marb2000 I think I've seen you mention there is no (or is no longer) a 30 fps lock?

Added added a screenshot, was running a dispatcher on a complete empty project avg. on 45fps which is exactly  the visual expierence I have.

**Comment by marb2000** [comment] 2022-06-29 05:48
Let me ask about and I will circle back.

**Comment by castorix** [comment] 2022-06-29 11:11
[CompositionTarget.Rendering](https://docs.microsoft.com/en-us/windows/windows-app-sdk/api/winrt/microsoft.ui.xaml.media.compositiontarget.rendering?view=windows-app-sdk-1.1) runs on the UI thread from the doc
I use it to render Swap Chains (Direct2D) and it is at 60 FPS on my old PC

**Comment by marb2000** [comment] 2022-07-01 17:58
The current design is the same as UWP. WinUI tries to render at the monitor refresh rate of the primary monitor. If the system has multiple monitors at different refresh rates, it still just be pinned to the primary monitor.
However, other pieces can affect this, like using DispatcherQueue timer instead of the CoreDispatcher's one (used by UWP). There could be differences in the implementation that affect the rendering. I bet that there will be others. 

Thank you for the awareness; our perf and rendering teams are now aware of it and added it to the pipeline of improvements. No ETA yet for this specific issue, but I will expect several perf improvements by 1.2 that will increase the overall rendering efficiency.

**Comment by molesmoke** [comment] 2022-07-15 05:00
I'm also see this behaviour with a trivial test app:

```
    public sealed partial class MainWindow : Window
    {
        Stopwatch stopwatch = Stopwatch.StartNew();
        int frameCount = 0;

        public MainWindow()
        {
            this.InitializeComponent();

            CompositionTarget.Rendering += CompositionTarget_Rendering;
        }

        private void myButton_Click(object sender, RoutedEventArgs e)
        {
            myButton.Content = "Clicked";
        }

        private void CompositionTarget_Rendering(object sender, object e)
        {
            frameCount++;
            if (stopwatch.Elapsed.TotalSeconds >= 1.0)
            {
                myButton.Content = $"Frame count {frameCount}";;
                stopwatch.Restart();
                frameCount = 0;
            }
        }
    }
```

@castorix Interestingly, if my main screen is set to 60 Hz then I get 60 FPS. If it's set higher though (120HZ or 144 HZ) then I get ~30 FPS. Tested on Ryzen 3700X with GTX1080

**Comment by castorix** [comment] 2022-07-15 06:45
> Interestingly, if my main screen is set to 60 Hz then I get 60 FPS. If it's set higher though (120 Hz or 144 Hz) then I get ~30 FPS. Tested on Ryzen 3700X with GTX1080 with Windows App SDK 1.1.2.

Ah yes, it is weird.
I also did other tests since with abnormal results too : if I use OpenGL instead of DirectX (Direct2D), although I get 60 FPS, the animation is a lot slower than in Winforms, with the exact same code (copy/paste, C# + P/Invoke)

**Comment by christosk92** [comment] 2022-07-25 08:46
I have the exact same problem. If my monitor is set to 144 Hz, the fps goes down to roughly 30 fps. Once I put it back to 60 Hz, it stays at 60 fps. UWP Doesn't have this issue.

**Comment by jeremy-visionaid** [comment] 2022-08-31 02:06
Looks like this is a duplicate of #6031, which means the rendering performance has been terrible for nearly a year now

**Comment by christosk92** [comment] 2022-08-31 11:59
I'm confused as to why there aren't more issues about this. Surely this isn't just a couple of cases? Or are people (including the dev team) OK with this performance?

**Comment by KenionX** [comment] 2022-08-31 15:35
@christosk92 thats pretty simple, most ppl. working in big companies still using 60hz screens everywhere. The Amount of ppl. who use 144hz+ and playing competive shooters ( so the brain detects even the smallest amount of frame jumps ) and using WinUI3 is relative small. 

Iam so used to 144hz screen for me even the mouse is not smooth when I look at a 60hz screen, so everything below 60 frames is a nighmare :(

**Comment by christosk92** [comment] 2022-09-01 01:20
@KenionX I totally agree, its super sluggish and slow...

**Comment by CanTalat-Yakan** [comment] 2022-09-06 23:42
I hope you guys find a fix as that bug is really bothering

**Comment by holance** [comment] 2022-11-13 07:08
I am also getting FPS around 30 on my 144hz monitor.

**Comment by zmyspc** [comment] 2023-01-07 07:49
> I am also getting FPS around 30 on my 144hz monitor. If I connect another monitor with 60Hz and set that 60Hz monitor as primary monitor, FPS jumps to 60.
Same here.
Just my quick test, winui2 and winui3 Gallery App on windows 11.
Winui3 looks very laggy at 144hz, 120hz is a bit better. Set displayer to 60hz behaves the same as winui2. winui3 working at 60hz even seemed smoother than 144hz, wtf
winui2 has always worked very well, even at 144hz
This definitely needs a fix, people don't keep using oldies

**Comment by YOYOyayaLaLaNiNi** [comment] 2023-02-18 12:28
This bug doesn't seem to be fixed in the latest version of the update.

WinUI3's max refresh rate is locked at 60fps. And once you set your monitor's refresh rate higher than 60hz, then your WinUI3 app will only get a max refresh rate of 30fps. This is the case in Win10 environment. Has anyone verified if this bug is also present in Win11?

**Comment by christosk92** [comment] 2023-02-18 18:33
I've been stuck on my 60Hz laptop for the past month so I wasn't able to check, but the rendering performance on 60 Hz is fine. 

I remember it sucking if it goes above 60 Hz (on win11). Sad to hear it isn't fixed yet.

**Comment by molesmoke** [comment] 2023-02-18 18:53
@YOYOyayaLaLaNiNi Yup, it's present on both Win 10 and 11

**Comment by christosk92** [comment] 2023-03-11 10:39
I'm seeing better performance in preview 1 for 1.3 when scrolling using the mouse wheel ! 

Manually grabbing the scrollbar and scrolling still has terrible performance though. 
Tested on Win11 Insider build 25309.1000

**Comment by jeremy-visionaid** [comment] 2023-03-12 20:30
@christosk92 I'm not seeing any change in rendering perf for this issue in 1.3.230228005-preview1

**Comment by christosk92** [comment] 2023-03-19 03:27
> @christosk92 I'm not seeing any change in rendering perf for this issue in 1.3.230228005-preview1

Ah yeh, it's only when using a ListView/GridView. 

ScrollViewers with ItemsRepeaters, transitions still look laggy. 

At least they acknowledged it in the latest WinUI Community call.

**Comment by Nevodev** [comment] 2023-04-02 15:52
This is still not fixed in the latest version.

**Comment by molesmoke** [comment] 2023-04-02 21:25
This is so disappointing, and really shows that projects like this really need to be open sourced.
A critical bug in the flagship UI framework that hasn't been fixed in nearly 2 years does not inspire great confidence in the platform.

**Comment by bpulliam** [comment] 2023-04-18 14:29
A fix for the core issue is included in the 1.3 release, released April 12th. If you are still seeing low framerates on high refresh monitors using 1.3, please log a new issue, as it is likely a different scenario and we should track it separately.

**Closed by bpulliam** 2023-04-18 14:29 UTC
Labels: bug, team-Rendering, area-Performance, product-winui3

**Comment by christosk92** [comment] 2023-04-19 13:07
Can confirm that performance, esp scrolling is much much better, although sometimes I do feel like its a BIT slower than UWP. but maybe thats just my imagination.

Thank you for your fix.

**Comment by YOYOyayaLaLaNiNi** [comment] 2023-06-21 16:20
Finally, this bug that has been with winui3 since its inception has been fixed after two years.
Even so, I still feel that the overall performance of winui3 is not as good as UWP.
