### ISSUE TITLE
keyboardaccelerator context variable

### ISSUE THREAD

**Issue by ghost** [microsoft/microsoft-ui-xaml#889] opened 2019-06-18 05:59 UTC
In UWP C#, I use a keyboardaccelerator in a appbar MenuFlyout. I have seen this strange behaviour: my app open the page with the mentioned appbar, set a variable to oldValue, close the page, open the page again, set the variable to newValue and call with the keybardaccelerator the menu which use the variable. The variable should be newValue BUT is oldValue.
IF I call the menu with the mouse I got newValue which is fine.
It looks like that the keyboardaccelerator uses the old context of the page. Very strange…

**Comment by YuliKl** [comment] 2019-06-18 17:10
@YvesPflieger, thank you for reporting this problem. Could you attach a repro project or point at a repo that demonstrates this issue? Seeing your code would make it easier for us to debug.

**Comment by YvesPflieger** [comment] 2019-06-18 17:20
Hello,

The problem is now resolved in my code. I have updated Nuget Microsoft.UI.Xaml and use now Command instead of click event and KeyboardAccelerators.

Here below is what works now:

            <AppBarButton x:Name="abAction"
                          x:Uid="AbActions"​
                          Label="Actions..."​
                          Icon="Repair"​
                          RequestedTheme="Dark"​
                          Click="AbAction_Click"​
                          Visibility="Collapsed">​
                <AppBarButton.Resources>​
                    <MenuFlyout x:Name="flyOutAction">​
                        ​
                          ​
                        ​
                                        ​
                        <MenuFlyoutItem x:Name="mnuSupprimer"​
                                        Text="Supprimer..."​
                                        x:Uid="Supprimer"​
                                        >​
                            ​
                        </MenuFlyoutItem>​
                    </MenuFlyout>​
                </AppBarButton.Resources>​
            </AppBarButton>


            var deleteCommand = new StandardUICommand(StandardUICommandKind.Delete);
            deleteCommand.ExecuteRequested += DeleteCommand_ExecuteRequested;​
            mnuSupprimer.Command = deleteCommand;


Yves Pflieger





________________________________
De : Yulia Klein <notifications@github.com>
Envoyé : mardi 18 juin 2019 19:10
À : microsoft/microsoft-ui-xaml
Cc : Yves PFLIEGER; Mention
Objet : Re: [microsoft/microsoft-ui-xaml] keyboardaccelerator context variable (#889)


@YvesPflieger<https://github.com/YvesPflieger>, thank you for reporting this problem. Could you attach a repro project or point at a repo that demonstrates this issue? Seeing your code would make it easier for us to debug.

**Comment by YvesPflieger** [comment] 2019-06-19 09:44
Yves PFLIEGER a partagé un fichier OneDrive avec vous. Pour l’afficher, cliquez sur le lien ci-dessous.
<https://1drv.ms/u/s!Aq49pQqt8EEvkflg6KyKTeZmOaqunA>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://1drv.ms/u/s!Aq49pQqt8EEvkflg6KyKTeZmOaqunA>
TestBugKeyboardAccelerator.zip<https://1drv.ms/u/s!Aq49pQqt8EEvkflg6KyKTeZmOaqunA>


Here attached is a repro project showing the bug.
Look a comment in MainPage.cs

Yves Pflieger




________________________________
De : Yulia Klein <notifications@github.com>
Envoyé : mardi 18 juin 2019 19:10
À : microsoft/microsoft-ui-xaml
Cc : Yves PFLIEGER; Mention
Objet : Re: [microsoft/microsoft-ui-xaml] keyboardaccelerator context variable (#889)


@YvesPflieger<https://github.com/YvesPflieger>, thank you for reporting this problem. Could you attach a repro project or point at a repo that demonstrates this issue? Seeing your code would make it easier for us to debug.

**Comment by Austin-Lamb** [comment] 2019-06-25 17:06
Thanks for filing this, @YvesPflieger - this is a bug with how Page.[Bottom|Top]AppBar interacts with keyboard accelerators.  I'm going to put this on our backlog - but for now you can work around this by not using the AppBar properties on Page.  Instead, you can just position the CommandBar in your Page's layout - to get the CommandBar rendered in the same place.

**Comment by shresthasource** [comment] 2020-12-26 15:25
I am seeing the same issue with keyboard accelerators assigned to a page inside a tab. 
* Load a page with different arguments inside different tab items. 
* The page has context menu items (and corresponding keyboard accelerators).
* Clicking a context menu item always executes command in the same page (inside currently selected tab). However, using keyboard accelerators assigned to the same context menu items execute the command from other pages.

**Closed** 2023-08-03 22:32 UTC
Labels: area-KeyboardAccelerators, needs-winui-3, team-Reach, no-issue-activity
