### ISSUE TITLE
SDK 17763: Issue with XamlRenderingBackgroundTask on builds 17763+

### ISSUE THREAD

**Issue by ChristopheLav** [Microsoft/microsoft-ui-xaml#99] opened 2018-12-17 02:01 UTC
**Describe the bug**

When I use the last SDK of Windows 10 (17763) to compile my application, I have an error with the background tasks that are using XamlRenderingBackgroundTask. Background tasks that are using IBackgroundTask work fine.

When the execution starts, the BackgroundTaskHost.exe process crash with this stacktrace (from the Windows Store):

[stackTrace - backgroundtask issue 17763.txt](https://github.com/Microsoft/microsoft-ui-xaml/files/2684211/stackTrace.-.backgroundtask.issue.17763.txt)

This issue is also visible in the statistics of a flight build (Preview) of my app in the Windows Store.
You can see the issue appears only on builds 17763 and beyond.
On the previous builds of Windows 10, the **same** version of the app work well (for example on my Lumia).

![image](https://user-images.githubusercontent.com/19799037/50062405-064cab00-0175-11e9-9c1b-30ea291f45a3.png)

**Steps to reproduce the bug**

This is a simple project to reproduce the issue:

[BackgroundTask17763Test.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2685758/BackgroundTask17763Test.zip)

I have implemented two background tasks:

- BackgroundTask1 that implement IBackgroundTask
- BackgroundTask2 that implement XamlRenderingBackgroundTask

If I put a breakpoint in the tasks and start the execution of the tasks, the BackgroundTask1 is working but the BackgroundTask2 throw an exception:

![image](https://user-images.githubusercontent.com/19799037/50062467-680d1500-0175-11e9-80c2-3c4232cc7604.png)

**Expected behavior**

All background tasks (IBackgroundTask and XamlRenderingBackgroundTask) needs to be work on builds 17763+ when the application use the SDK 17763.

Actually, if I use the SDK 17763 - my application is not working on the builds 17763+.
If I use the previous SDK, my app is working on the previous and builds 17763+.

Seems a regression of the 17763 SDK, or a Windows 10 bug or a undocumented change.

**Version Info**

The issue occurs on stable build 17763.XXX and 19H1 Preview builds of Windows 10.
The issue is not encounter on previous version of Windows 10.

NuGet package version: not applicable in this case.

Windows 10 version:
- [X] Insider Build (19H1)
- [X] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [X] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

Thanks,
Christophe

**Comment by kmelmon** [comment] 2018-12-17 07:09
Thanks for reporting this.  Can you please also include the MyBackgroundTasks sub-project which contains your background task code?   The zip only has the main solution which doesn't include this code, so I can't actually build your sample.

Thanks!

**Comment by ChristopheLav** [comment] 2018-12-17 11:19
Sorry for the mistake, ZIP is updated:

[BackgroundTask17763Test.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2685758/BackgroundTask17763Test.zip)

Thanks!

**Comment by kmelmon** [comment] 2018-12-17 20:47
Thanks for the update.  I build the sample and have reproduced the issue.  We're investigating...  At this point I don't see any work-around but we don't have a root cause yet.  Will update when we know more.

**Comment by jevansaks** [comment] 2018-12-17 21:05
Thanks for the report. Now tracked as an [internal issue](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/19958016).

**Comment by ChristopheLav** [comment] 2018-12-17 22:14
Thanks for the status.

**Comment by Stedy59** [comment] 2018-12-31 20:06
I reported this issue over 2 1/2 months ago and they closed it and told me to report it in the Windows Insider hub. It has been over 2 months since I reported it there.. still no one has acknowledged that this is an issue, but yet they continue to force new bug ridden versions of Windows on us while breaking APIs that are necessary for us to write software to support this buggy OS!!!! NICE JOB MS!!!!!!!

**Comment by kmelmon** [comment] 2018-12-31 20:40
@Stedy59 Can you share a link to where you reported the issue?  I will follow-up to understand why the issue was apparently closed instead of being forwarded to the dev team.

**Comment by ChristopheLav** [comment] 2018-12-31 20:44
@jevansaks, @kmelmon Have you new information about analysis of this bug?

**Comment by kmelmon** [comment] 2018-12-31 20:57
We have made some progress but don't have a root cause or a fix yet.  The bug has been routed to the appropriate area experts who should be back from vacation this week.

**Comment by ChristopheLav** [comment] 2018-12-31 21:12
Thanks for the info and your help :-)

**Comment by Stedy59** [comment] 2018-12-31 21:15
Here is the first post from October 17th, 2018…

https://developercommunity.visualstudio.com/content/problem/360388/uwp-target-version-17763-breaks-application-trigge.html

After not agreeing with the response, I decided that I needed to re-submit it, so here is the second posting from November 6th, 2018…

https://developercommunity.visualstudio.com/content/problem/376747/uwp-target-version-17763-breaks-application-trigge-1.html

Thank you for looking into this because I have to applications in the store that use these APIs…

Regards,
Ed

[cid:image001.png@01D4A123.276B0780]

Edward J. Boelzner,  Principal Software Architect

Stedy Software and Systems  l  64 Greeley Street, Manchester, NH 03102
v: 603.626.6034  l  c: 603.860.9077  l  e: edward.boelzner@stedysoft.com<mailto:edward.boelzner@stedysoft.com>


The information transmitted is intended only for the person or entity to which it is addressed and may contain confidential and/or privileged material. Any review, re-transmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and delete the material from any computer.

© 1992-2018 Stedy Software and Systems ® All rights reserved

**Comment by kmelmon** [comment] 2019-01-04 19:54
Update:  We're still working on finding a root cause.  In the mean-time, I wanted to suggest a potential work-around.  From playing around with background rendering tasks, it looks like you need to create a separate project for the background task.  If this project targets an SDK version < 17763 the crash is avoided.  The main app project should be able to continue to target the latest SDK.  

The limitation here would be that the background rendering project cannot access RS5+ features.  The hope is that this code doesn't actually need RS5+ features, since all it needs to do is produce a live tile.  Is that an acceptable workaround for you guys?

**Comment by ChristopheLav** [comment] 2019-01-06 02:06
Thanks for the update @kmelmon

I have done some tests with the workaround but it's not working for me. My tasks are in one project and this project is using some other librairies to share some logics between tasks and application. I have attempt to use the last SDK in all projects except the "Task" project without success. I have made a second attempt to use the last SDK only on the application project without success too.

At this point, the workaround is not working for me (or not in all cases).

**Comment by Stedy59** [comment] 2019-01-06 16:56
Thank you for the proposed workaround(s)… Here are my findings:

1) The only background task(s) that are failing are ones that implement "XamlRenderingBackgroundTask"
      - These are already separate projects as they are "Windows Runtime Components"

2) Setting the target SDK to < 17763 in the background task projects fails as before.
     - Leaving the target SDK @ 17763 in the background task project but setting the target SDK to < 17763 in the main project that registers and calls it... works!

3) This would indicate to me that the bug is in the attempt to register the "XamlRenderingBackgroundTask" task, as opposed to the actual implementation being executed.

Leaving the target SDK @ < 17763 at this point is not an issue because the API pertaining to XAML did not change much... but, in the future, moving to the "19H1" branch of Windows, the XAML / .NET Core landscape has a massive change.  "XAML islands", etc...

**Comment by kmelmon** [comment] 2019-01-25 19:15
Update:  The issue has been fixed for the next public release of XAML (codename 19H1).

**Closed** 2019-01-26 00:30 UTC

**Comment by ChristopheLav** [comment] 2019-01-27 19:04
Thank you so much for your help and your follow. Appreciated!

**Comment by tipa** [comment] 2019-07-25 13:48
I just built my app with the latest available toolings 1 week ago and I still see this crash happening on 17763 devices. Are there any ways to prevent/workaround this?

**Comment by tipa** [comment] 2019-07-25 21:09
Does this mean the XamlRenderingBackgroundTask will inevitably crash on 17763 or is there any workaround?
