### ISSUE TITLE
WinUI Live Visual Tree exception thrown

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4866] opened 2021-04-20 21:59 UTC
When using Live Visual Tree to debug the visual tree of a WinUI 3 for Desktop application an exception is thrown when clicking any item in the tree

> Exception thrown at 0x7BAB8221 (Microsoft.VisualStudio.DesignTools.WinUITap.dll) in CalendarExplorer.exe: 0xC0000005: Access violation reading location 0x0000001C.

![image](https://user-images.githubusercontent.com/17496741/115468984-3e170200-a20a-11eb-9007-578875bb7f28.png)

Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 2.0

Project Reunion 0.5.5 extension

**Comment by jschwizer99** [comment] 2021-04-20 22:16
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4854#issue-861074276.

**Comment by StephenLPeters** [comment] 2021-04-20 23:05
@RealTommyKlein FYI

**Comment by RealTommyKlein** [comment] 2021-04-20 23:14
Closing as a dupe of #4854 - this will be fixed in 16.10 Preview 3, and a workaround is available in [this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/4854#issuecomment-822852473).  Thanks!

**Closed by RealTommyKlein** 2021-04-20 23:14 UTC
Labels: ProjectReunion 0.5, area-Tooling, duplicate, needs-triage, team-Markup, winui3preview
