### ISSUE TITLE
Microsoft.UI.Xaml v2.6.0 causing App Submission to Store to Fail

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#5298] opened 2021-06-27 05:30 UTC
**Describe the bug**
v2.6.0 is causing Partner Center submissions to fail with "Attention needed" and submission entry page shows "A previous submission failed certification. After you submit the latest changes, the submission will go through the certification process again." without error code. Going back to v2.5.0 allows it to get certified as normal.

**Steps to reproduce the bug**
Update to v2.6.0 and submit app update to Store.

**Expected behavior**
An updated app should be accepted as it was with v2.5.0

NuGet package version: 
[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 19043           | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by asklar** [comment] 2021-06-27 22:34
@myokeeh are you able to reproduce this locally with [Windows app cert kit](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/)? can you share the WACK .xml report on what specifically failed? Which SDK version are you using?

**Comment by nickprotop** [comment] 2021-06-28 10:26
> @myokeeh are you able to reproduce this locally with [Windows app cert kit](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/)? can you share the WACK .xml report on what specifically failed? Which SDK version are you using?

Same problem here. The app passes locally the Windows app cert kit.

**Comment by IstvanKor** [comment] 2021-06-28 10:52
Same issue here. Validation with Windows app cert kit passed without warning. Windows app cert kit version: 10.0.19041.685

**Comment by myokeeh** [comment] 2021-06-28 15:03
@asklar app passes WACK just fine.

**Comment by StephenLPeters** [comment] 2021-06-28 23:25
@ranjeshj @llongley FYI

**Comment by asklar** [comment] 2021-06-29 00:44
Ok - gut feel is something changed in the latest SDK (which is what the Store would use). Any chance one of you can run this against the latest insider preview SDK 22000? https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewSDK

**Comment by myokeeh** [comment] 2021-06-29 04:46
@asklar. If you mean setting target to 22000, I just did and Partner Center gives me this: 

Package acceptance validation error: The package _______.msix uses an unsupported version of file MakePri.exe (10.0.22000.51). The following versions are allowed: < 10.0.10500.0; >= 10.0.10586.0 & < 10.0.11000.0; >= 10.0.14383.0 & < 10.0.14800.0; >= 10.0.15053.0 & < 10.0.15100.0; >= 10.0.16299.0 & < 10.0.16350.0; >= 10.0.17134.0 & < 10.0.17500.0; >= 10.0.17763.0 & < 10.0.18199.0; >= 10.0.18362.0 & < 10.0.18799.0; >= 10.0.19041.0 & < 10.0.19399.0; >= 10.0.20348.0 & < 10.0.21242.0. Please update your Visual Studio build tools and try again.

**Comment by myokeeh** [comment] 2021-06-29 05:06
@asklar WACK 10.0.22000 still passes by the way

**Comment by zhuxb711** [comment] 2021-06-29 06:24
WinUI has so many problems, 2.6 is nothing like a version that took 6 months to develop, full of errors and omissions.

**Comment by mikebattista** [comment] 2021-06-29 21:15
> Package acceptance validation error: The package _______.msix uses an unsupported version of file MakePri.exe (10.0.22000.51). The following versions are allowed: < 10.0.10500.0; >= 10.0.10586.0 & < 10.0.11000.0; >= 10.0.14383.0 & < 10.0.14800.0; >= 10.0.15053.0 & < 10.0.15100.0; >= 10.0.16299.0 & < 10.0.16350.0; >= 10.0.17134.0 & < 10.0.17500.0; >= 10.0.17763.0 & < 10.0.18199.0; >= 10.0.18362.0 & < 10.0.18799.0; >= 10.0.19041.0 & < 10.0.19399.0; >= 10.0.20348.0 & < 10.0.21242.0. Please update your Visual Studio build tools and try again.

You can't submit apps to the Store using Insider SDKs, so that error is expected and a distraction from the original issue.

**Comment by KevinLaMS** [comment] 2021-06-29 21:20
@myokeeh  can you share the **original** failure report you received from the store?  Or provide us with the app ID and we can see what the failure was?

**Comment by myokeeh** [comment] 2021-06-30 01:51
> @myokeeh  can you share the **original** failure report you received from the store?  Or provide us with the app ID and we can see what the failure was?

That's the thing. There's no failure report other than the error and text I detailed in the original post. This is not isolated to one app or account as I've tried it on several apps and two Partner Center accounts now.

**Comment by jevansaks** [comment] 2021-06-30 03:53
@myokeeh  can you provide the app ids that failed submission? I think the store folks can use that to follow up. If you don't want to post them here, feel free to email me (address is in my github profile).

**Comment by myokeeh** [comment] 2021-06-30 05:49
Another data point: Partner Center isn't choking on apps with 2.6.0-prerelease.210623001.

**Comment by MartinZikmund** [comment] 2021-06-30 12:34
I am facing the same issue for all my updated UWP apps. I have contacted the Store team regarding this and they mention the app is failing in the preprocessing compile step. They provided me with the following error output: 

> Calling ilc.exe with arguments:\r\nF:\\AppCompileSdk\\AppCompile\\2.2\\x86\\ilc\\ilc.exe /in:\"F:\\Data\\PkgProc\\O424fyB7L0mmewoUH5tE8g\\AppCompileSourceDirectory\" /out:\"F:\\Data\\PkgProc\\O424fyB7L0mmewoUH5tE8g\\ExtractedBundle\\Physics.DragMovement_1.4.1.70_x86\" /WindowsSdkApiXml:\"F:\\AppCompileSdk\\AppCompile\\SupportedAPIs-x86.xml\" /makePriPath:\"D:\\SvcFab\\_App\\PackageProcessingHostType_App44\\PackageProcessingHostPkg.Code.1.0.21153.1\\SDK\\MakePri.exe\" /rcPath:\"D:\\SvcFab\\_App\\PackageProcessingHostType_App44\\PackageProcessingHostPkg.Code.1.0.21153.1\\SDK\\Rc.exe\" /disableVSTel:true /AllowNoManagedCode /buildtype:ret /CscPath:F:\\AppCompileSdk\\AppCompile\\2.2\\csc\\csc.exe /disableGatekeeper /TargetPlatform:x86 /exeName:\"Physics.DragMovement.exe\" /pdbPath:\"F:\\Data\\PkgProc\\O424fyB7L0mmewoUH5tE8g\\AppCompileSymbolOut\" /RdXmlPath:\"F:\\AppCompileSdk\\AppCompile\\2.2\\LibraryXML\" /UseSharedAssemblies /InSharedAssemblyPath:\"F:\\AppCompileSdk\\AppCompile\\2.2\\SharedAssemblyArtifacts\\x86\" /targetplatformsdklibpath:\"F:\\AppCompileSdk\\AppCompileTargetPlatforms\\Vibranium\" /v:\"d\" /ExtraNutcArguments:\"/d2threads1\"\r\nOutput:\r\nThe command line argument /MakePriPath is not supported anymore, it will be ignored.\r\nBuild started 6/30/2021 6:47:12 AM.\r\n__________________________________________________\r\nProject \"Preparation\" (default targets):\r\n\r\nTarget CreateToolchainGeneratedAssembly:\r\nTarget ConstructPreMergeAssemblyClosure:\r\n  Task \"PreMergeAssemblyClosure\"\r\n  Done executing task \"PreMergeAssemblyClosure\".\r\nTarget PreResolveTransforms:\r\n  Task \"McgReferenceResolveFilePath\"\r\n  Done executing task \"McgReferenceResolveFilePath\".\r\nTarget ConstructILTransformAssemblyClosure:\r\n  Task \"ResolveToolchainRequiredAssemblyRoots\"\r\n  Done executing task \"ResolveToolchainRequiredAssemblyRoots\".\r\n  Task \"ILTransformAssemblyClosure\"\r\n  Done executing task \"ILTransformAssemblyClosure\".\r\n  Task \"ResolveToolchainRequiredAssemblyRoots\"\r\n  Done executing task \"ResolveToolchainRequiredAssemblyRoots\".\r\n  Task \"ReducedCopyAssemblyClosure\"\r\n    MSBUILD : error : ILT1307: Assemblies 'F:\\Data\\PkgProc\\O424fyB7L0mmewoUH5tE8g\\AppCompileSourceDirectory\\Microsoft.UI.Xaml.winmd' and 'F:\\Data\\PkgProc\\O424fyB7L0mmewoUH5tE8g\\AppCompileSourceDirectory\\WinMetadata\\Microsoft.UI.Xaml.winmd' have conflicting simple names.\r\n  Done executing task \"ReducedCopyAssemblyClosure\" -- FAILED.\r\nDone building target \"ConstructILTransformAssemblyClosure\" in file \"Preparation\" -- FAILED.\r\n\r\nDone building project \"Preparation\" -- FAILED.

**Comment by jevansaks** [comment] 2021-06-30 13:23
@ranjeshj @kmahone @llongley did anything change with the framework package or nupkg winmd configuration in this release? I do not understand this error message and I’ve never seen it before. Is there a new MinVersion requirement?

@MartinZikmund @myokeeh we were able to submit XamlControlsGallery -- is there anything you can see that's different between your project and that one? (https://github.com/microsoft/Xaml-Controls-Gallery/blob/master/XamlControlsGallery/XamlControlsGallery.csproj)

**Comment by MartinZikmund** [comment] 2021-06-30 13:54
@jevansaks I can give you access to our repo, but I don't see anything suspicious at first glance. Downgrading to the latest preview package from NuGet seems to work and the certification did not fail so far

**Comment by Panda-Sharp** [comment] 2021-06-30 15:09
I Just experienced the same issue, I tried to upload a new app update that included WinUI 2.6 and it failed:

![image](https://user-images.githubusercontent.com/7117301/123985528-d3cacc80-d9c5-11eb-9bc2-010d64de69e5.png)

What's even worst that this message it's a bit confusing and there is no way get any extra details

**Comment by llongley** [comment] 2021-06-30 18:47
> @ranjeshj @kmahone @llongley did anything change with the framework package or nupkg winmd configuration in this release? I do not understand this error message and I’ve never seen it before. Is there a new MinVersion requirement?

The only change we made was the location we place the WinMD to in order to fix a WACK certification issue for Lottie:

https://github.com/microsoft/microsoft-ui-xaml/pull/4820/files

I at least wouldn't think that would be responsible for this, though I similarly don't understand what the error message means, so I can't be certain of that.

**Comment by llongley** [comment] 2021-06-30 18:52
@jevansaks We did change the WinMD placement to fix a Lottie WACK certification issue, which might be leading to this:

https://github.com/microsoft/microsoft-ui-xaml/pull/4820/files

It looks like this is the actual error message, which suggests that that might be related:

```
MSBUILD : error : ILT1307: Assemblies 'F:\Data\PkgProc\O424fyB7L0mmewoUH5tE8g\AppCompileSourceDirectory\Microsoft.UI.Xaml.winmd' and 'F:\Data\PkgProc\O424fyB7L0mmewoUH5tE8g\AppCompileSourceDirectory\WinMetadata\Microsoft.UI.Xaml.winmd' have conflicting simple names.
```

I'll investigate - I was trying to look at it yesterday, but I was similarly completely unable to get an actual error message beyond just "failed certification".

**Comment by ranjeshj** [comment] 2021-06-30 22:05
Curious, What is different about Xaml Controls Gallery that caused it to go through without this problem?

**Comment by jevansaks** [comment] 2021-06-30 22:47
XamlControlsGallery has MinVersion 17134, I suspect .NET Native had a bug that was fixed in the newer version.

@martinzikmund @panda-sharp @myokeeh What min version are you using? Can you try MinVersion 17134 to see if that changes things for you? .NET Native changes their behavior based on your MinVersion and the RS2/3 version has had some other bugs.

That test will help us narrow this down at least.

Also it's possible the error message is referring to the "simple names" of the paths of the files? So simply having the winmd in the app package and the framework package is the problem?

@llongley your change moved the package into the AppX root, maybe you can put it into WinMetadata folder instead? I'm not entirely clear on what problem you were solving in that other PR.

**Comment by llongley** [comment] 2021-06-30 22:51
> @llongley your change moved the package into the AppX root, maybe you can put it into WinMetadata folder instead? I'm not entirely clear on what problem you were solving in that other PR.

It needs to be in the root to pass WACK certification when WinUI 2 is being referenced transitively.  For example, when Lottie references a Microsoft.UI.Xaml type in its WinMD, the WACK metadata test suite tries to resolve that reference and fails if the WinMD isn't in the root, since that seems to be the only place it's looking.

**Comment by jevansaks** [comment] 2021-06-30 23:00
BTW we are not the first to hit this error: [Here](https://github.com/dotnet/runtime/issues/24050), and [this one has a clue](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/31cd6165-e3f9-44f3-adff-954afe0d810b/rs3-1709-vs20174-16299sdk-microsoft-advertising-sdk-have-a-severe-issue-that-prevent-the) that maybe MinVersion 16299 fixed it.

**Comment by michalleptuch** [comment] 2021-07-01 13:24
Hi everyone,
I had similar problem in my XAML Islands app. I saw discussion about another bug and modify one of the proposed solutions: https://github.com/microsoft/microsoft-ui-xaml/issues/3554. First, I downgraded WinUI 2.6 to 2.6.0-prerelease.210430001 and then added this part of code to wapproj:
```
<Target Name="FixPayload" BeforeTargets="_GenerateAppxUploadPackageFile" Returns="@(AppxUploadPackagePayload)">
  <ItemGroup>
    <_FilteredAppxPackagePayload Include="@(AppxUploadPackagePayload)" Condition="'%(AppxUploadPackagePayload.TargetPath)'=='Microsoft.UI.Xaml\Assets\NoiseAsset_256X256_PNG.png'" />
    <_FilteredAppxPackagePayload Include="@(AppxUploadPackagePayload)" Condition="'%(AppxUploadPackagePayload.TargetPath)'=='Microsoft.UI.Xaml.winmd'" />
    <_AppxPackagePayloadToRemove Include="@(_FilteredAppxPackagePayload)" Condition="'%(_FilteredAppxPackagePayload.ProjectName)'==''" />
    <AppxUploadPackagePayload Remove="@(_AppxPackagePayloadToRemove)" />
  </ItemGroup>
</Target>
```
I don't know if it helps for UWP apps with official release of the WinUI 2.6 but my app passes certification yesterday. Target version of my app: 10.0.18362.

**Comment by ChristopheLav** [comment] 2021-07-01 15:06
Same issue here with my app. Can't push update to the Store with WinUI 2.6.0.

So, seem like a general issue.

**Comment by jevansaks** [comment] 2021-07-02 03:44
Just an update: we are actively trying to find out from the Store team what tools are running on the Store side so we can repro this locally. If anyone is able to repro this compilation failure locally that would be very helpful to know as well.

**Comment by nickprotop** [comment] 2021-07-03 05:08
Any new update about this issue?

**Comment by asklar** [comment] 2021-07-03 05:49
@nickprotop @ChristopheLav and others, if you have an app ID / submission ID or something to identify the failed store submission please provide it (you can dm me on twitter https://twitter.com/alexsklar

**Comment by nickprotop** [comment] 2021-07-03 06:25
> @nickprotop @ChristopheLav and others, if you have an app ID / submission ID or something to identify the failed store submission please provide it (you can dm me on twitter https://twitter.com/alexsklar

Provided.

**Comment by ChristopheLav** [comment] 2021-07-03 12:56
@asklar Provided. Thank you.

**Comment by songshizhao** [comment] 2021-07-05 13:14
some nuget part did not use native compilation ,maybe
that is the error link directed to...
https://docs.microsoft.com/en-us/windows/uwp/publish/resolve-submission-errors

**Comment by edandersen** [comment] 2021-07-05 13:55
If this helps anybody, I have managed to get my app in the store using the workaround provided by @michalleptuch (use the latest preview version of 2.6 and the csproj updates) and with Target version 19041 and Min version 17134.

**Comment by ChristopheLav** [comment] 2021-07-05 13:59
@edandersen I'm using the last 2.6-preview as well and the csproj updates are not required to submit to the Store with success (I have push some builds). The preview packages of WinUI are not build in the same manner as the release packages (see details [here](https://github.com/microsoft/microsoft-ui-xaml/pull/4820#issue-615703889)) and the issue only impact release packages.

**Comment by edandersen** [comment] 2021-07-05 14:03
> @edandersen I'm using the last 2.6-preview as well and the csproj updates are not required to submit to the Store with success (I have push some builds). The preview packages of WinUI are not build in the same manner as the release packages (see details [here](https://github.com/microsoft/microsoft-ui-xaml/pull/4820#issue-615703889)) and the issue only impact release packages.

Excellent. Thanks for the info.

**Comment by nickprotop** [comment] 2021-07-05 16:39
> @edandersen I'm using the last 2.6-preview as well and the csproj updates are not required to submit to the Store with success (I have push some builds). The preview packages of WinUI are not build in the same manner as the release packages (see details [here](https://github.com/microsoft/microsoft-ui-xaml/pull/4820#issue-615703889)) and the issue only impact release packages.

Confirmed. Just downgrade WinUI from 2.6 to latest prelease, without anything else, passes windows store submission. Thanks!!

**Comment by mfeingol** [comment] 2021-07-05 19:00
Unfortunately, the 2.6.0-prerelease.210623001 version of Microsoft.UI.Xaml appears to break uses of AcrylicBrush. This is fixed in 2.6.0 final. So for my uses, at least, the last pre-release is not viable.

**Comment by ChristopheLav** [comment] 2021-07-05 23:42
The last preview seems identical to the 2.6.0:

![image](https://user-images.githubusercontent.com/19799037/124524286-889b2a00-ddc8-11eb-9e5c-b56d36a16b86.png)

I also see some Acrylic issues (with last preview + stable). Related to this, there are some commits in the main branch after the release (ba55e86). Probably the fixes will be included in an incoming 2.6.1 ;)

**Comment by mfeingol** [comment] 2021-07-06 15:10
> The last preview seems identical to the 2.6.0

That's interesting. I can confirm that if I declare and configure an `AcrylicBrush` in `<Page.Resources>` and then use it for some background on a page, that has no effect in the pre-release, but works fine in the release version.

So maybe something to do with packaging? Not sure.

**Comment by llongley** [comment] 2021-07-06 22:42
FYI, I have a fix for this issue out for PR:

https://github.com/microsoft/microsoft-ui-xaml/pull/5379

Things were working prior to the stable release because the prerelease versions are released with the DLLs in the nupkg, whereas the stable release gets its WinMD implementation from a framework package from the store, so the packaging is different.  The WinMD in the WinMetadata folder was only being put there in the latter case, which is why this hadn't been seen before.

I had thought that putting the WinMD in the WinMetadata folder was needed in that case, but it looks like it isn't, so I've removed it to fix this issue.

**Closed** 2021-07-06 23:54 UTC
Labels: area-NugetPackage, needs-cherrypicktorelease, team-Controls, working on it

**Comment by mfeingol** [comment] 2021-07-07 03:53
Thanks, @llongley. Will we see a 2.6.1 release before too long?

**Comment by ranjeshj** [comment] 2021-07-07 14:32
Thanks for your patience everyone. We are working on a 2.6.1 patch right now with this fix. Will be publishing it as soon as validation is complete.

**Comment by ArchieCoder** [comment] 2021-07-07 14:40
> Thanks for your patience everyone. We are working on a 2.6.1 patch right now with this fix. Will be publishing it as soon as validation is complete.

@ranjeshj This morning, I sent to the MVP WinDev DL that the Partner Center could be a better citizen and warn the dev when there is a big blocker. Another MVP was not aware about this particular thread here. When an issue is more than 2-3 days, a banner could help a lot the dev in Partner Center. After 10 days, many devs can lose confidence imo.

**Comment by ranjeshj** [comment] 2021-07-07 21:56
We have 2.6.1 published now which includes this fix for store certification, flyout acrylic fix and a few others. Can you please give a try and let me know if it resolves this issue ?
https://www.nuget.org/packages/Microsoft.UI.Xaml/2.6.1

**Comment by ChristopheLav** [comment] 2021-07-07 22:01
I will try.

**Comment by mfeingol** [comment] 2021-07-08 04:56
Working. Thanks, everyone.

**Comment by myokeeh** [comment] 2021-07-08 06:35
Thank you

**Comment by WillemBos** [comment] 2021-07-08 11:04
Thank you

**Comment by ValeraFinebits** [comment] 2021-07-16 09:12
This problem is still reproduced for the following case:
ARM64 UWP package with Windows Application Packaging Project (DesktopBridge) and Capability 'runFullTrust'
When roll back the version to 2.5 the problem disappears.

**Comment by yaichenbaum** [comment] 2021-07-19 02:54
> This problem is still reproduced for the following case:
> ARM64 UWP package with Windows Application Packaging Project (DesktopBridge) and Capability 'runFullTrust'
> When roll back the version to 2.5 the problem disappears.

I had this issue as well, I ended up removing support for ARM64 with WinUI 2.6, but I hope to add it back at some point.

**Comment by ValeraFinebits** [comment] 2021-07-26 08:40
Hi @ranjeshj 
What do you think about re-opening this bug?

**Comment by crramirez** [comment] 2021-07-26 22:12
I cannot upgrade to 2.6 from 2.5 until the ARM64 problem in Store gets fixed because I have users with ARM64

**Comment by ranjeshj** [comment] 2021-08-02 18:20
Sorry, missed this thread. This sounds like a different problem with arm64. Can you please file a new issue ? @yaichenbaum  @ValeraFinebits can you share a standalone repro that would be really helpful. @llongley  and @StephenLPeters  as FYI

**Comment by zhuxb711** [comment] 2021-09-16 11:59
Drop ARM64 is not helpful to my project. Submit a package with X64 and ARM only will still lead to 1201 code. See #5768
