### ISSUE TITLE
Dark theme does not get applied to teaching tip content sometime

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6320] opened 2021-11-16 12:47 UTC
### Describe the bug

Sometime when setting the dark theme from within the application, it does not get applied properly to content of teaching tip

### Steps to reproduce the bug

1. Create a teaching tip and add some content in it
2. Start the application and change the theme to dark (My app was developed using WTS, WTS setting has options to set dark theme)

### Expected behavior

![image](https://user-images.githubusercontent.com/8557046/141987282-20907d36-aa86-4279-a380-51dc4faa4385.png)

### Screenshots

![image](https://user-images.githubusercontent.com/8557046/141987163-6d4b23d3-0997-4d06-bf73-83736f1fe2f1.png)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

WinAppSDK 1.0.0-preview 3

**Comment by StephenLPeters** [comment] 2022-02-10 23:30
duplicate of known issue with popups getting improper theme

**Closed** 2023-08-03 22:47 UTC
Labels: area-TeachingTip, area-Resources, team-Controls, product-winui3, no-issue-activity
