### ISSUE TITLE
NumberBox has a top padding which breaks alignment

### ISSUE THREAD

**Issue by ccornici** [microsoft/microsoft-ui-xaml#2265] opened 2020-04-10 14:15 UTC
**Describe the bug**
`NumberBox` has a top padding which breaks alignment.

**Steps to reproduce the bug**
1. Add this XAML (I removed the data bindings since not relevant)
```
<Grid>
    <Grid.RowDefinitions>
        <RowDefinition/>
    </Grid.RowDefinitions>
    <Grid.ColumnDefinitions>
        <ColumnDefinition Width="250"/>
        <ColumnDefinition Width="70"/>
        <ColumnDefinition Width="100"/>
        <ColumnDefinition Width="50"/>
    </Grid.ColumnDefinitions>

    <TimePicker Grid.Row="0" Grid.Column="0" VerticalAlignment="Center"/>
    <winUI:NumberBox Grid.Row="0" Grid.Column="1" VerticalAlignment="Center" HorizontalContentAlignment="Center" HorizontalAlignment="Center" Padding="0,0,0,0" Margin="0,0,0,0"/>
    <TextBlock Grid.Row="0" Grid.Column="2" VerticalAlignment="Center" Margin="10,0,10,0" />
    <Button Grid.Row="0" Grid.Column="3" />
</Grid>
```
2. Observe

**Expected behavior**
NumberBox has all padding 0 and doesn't break Center alignment

**Screenshots**
Everyone is aligned, besides that smart-guy...
![problem1](https://user-images.githubusercontent.com/15718751/78996877-ce296280-7b45-11ea-80a6-751a5689f854.png)

Space at the top, both with default margin / padding and with margin/padding set to 0
![problem2](https://user-images.githubusercontent.com/15718751/78996903-dbdee800-7b45-11ea-8444-08a4b959cff4.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.3.200213001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   | Very funny  |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment] 2020-04-10 14:20
Can you please check if you can repro this with the latest pre release? I think we already merged a PR for this which is available in latest preview.

**Comment by ccornici** [comment] 2020-04-10 15:37
> Can you please check if you can repro this with the latest pre release? I think we already merged a PR for this which is available in latest preview.

I've read the MS page on the requirements/steps to get the 3.0 Alpha and I'm sorry to say that I'm not willing to do all that. It's OK, either way I'll sadly have to redesign that part of the UI until the (potential) fix is out of Alpha...

**Comment by chingucoding** [comment] 2020-04-10 15:38
Oh haha, no I meant the 2.4 preview. That should also include the fix. Sorry about the confusion.

**Comment by ccornici** [comment] 2020-04-10 15:52
> Oh haha, no I meant the 2.4 prerelease. That should also include the fix. Sorry about the confusion, mixed up the words there.

OK, I tried the 2.4.0-prerelease.200322001 as I see this is the latest one.
It looks like it's fixed in this package version

![fix1](https://user-images.githubusercontent.com/15718751/79003682-5feb9c80-7b53-11ea-9a16-33499a5ce082.png)

![fix2](https://user-images.githubusercontent.com/15718751/79003691-6417ba00-7b53-11ea-95f0-7d305b124542.png)


Can you please give me an estimate of when this is going to be out of preview?

**Comment by chingucoding** [comment] 2020-04-10 16:29
As to when 2.4 is being released, I can't give you an definite answer, I suspect maybe in the next 1-3 months, but @ranjeshj definitely knows it better then me.

Usually the pre releases also include features that are still under preview and might change later. As long as you don't rely on them I think it's fine to use them (note that I am not a Microsoft employee and this is just my opinion here).

If you don't want to use the pre releases, you can also set the `TextBoxTopHeaderMargin` to 0 since this is the root cause of this margin.

**Comment by ranjeshj** [comment] 2020-04-10 16:41
@ccornici You can use the pre-release builds as @chingucoding mentioned above. We do the stable release builds about once a quarter and we are trying to get 2.4 stable out by the end of this month (Thank you for your patience). All the features that will be in the next stable release are already in the pre-release so you can give that a try. We are working on a handful of stability fixes now.

**Closed** 2020-04-10 22:19 UTC
Labels: needs-triage
