### ISSUE TITLE
WinUI 3 NavigationViewItem IsSelected=true not work

### ISSUE THREAD

**Issue by ghost1372** [microsoft/microsoft-ui-xaml#5543] opened 2021-07-23 09:39 UTC
**Describe the bug**
NavigationViewItem Default Item cant be selected

**Steps to reproduce the bug**

```
<NavigationView.MenuItems>
            <NavigationViewItem Content="Home" Icon="Home" IsExpanded="True">
                <NavigationViewItem.MenuItems>
                    <NavigationViewItem IsSelected="True" Content="Subscene" Icon="ShowResults"/>
                    <NavigationViewItem Content="ESubtitle" Icon="Caption"/>
                </NavigationViewItem.MenuItems>
            </NavigationViewItem>
        </NavigationView.MenuItems>
```

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

WinUI 3 - Windows App SDK 0.8: 0.8.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-07-28 01:25
@ghost1372 can you try setting the IsSellected property from code behind during the Loaded event? I suspect this is a timing issue.  This issue isn't present in Winui2 correct?

**Comment by ghost1372** [comment] 2021-07-28 02:53
@StephenLPeters  WinUI 2.6.1 and WinUI 3.0 both do not work but i used a button to select default item and worked
```
private void Button_Click(object sender, RoutedEventArgs e)
        {
            myItem.IsSelected = true;
        }
```
I want to select one of the submenus by default

**Comment by StephenLPeters** [comment] 2021-07-28 18:59
So is this a duplicate of this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/3149

**Comment by ghost1372** [comment] 2021-07-28 19:05
yes, so we can close this issue?

**Closed** 2021-07-28 22:14 UTC
Labels: area-NavigationView, duplicate, product-winui3, team-Controls, version-ProjectReunion 0.8
