### ISSUE TITLE
Proposal: Ribbon Control Availability in WinUI Controls

### ISSUE THREAD

**Issue by hassaanmasood** [microsoft/microsoft-ui-xaml#6811] opened 2022-03-10 14:02 UTC
It would be great if a full featured Ribbon Control can be made available as part of WinUI Library. Like the one designed in new Windows 11 MS Paint App but with Tabs ( like in Windows 10 MS Paint). I am aware that a few third party controls are available for UWP. But why not have it as a first party control available both for UWP and WinUI3 featuring Win11 style control. 

## Rationale
* Ribbons are a very good ways to organize controls in the app. 
* It has been a while since Ribbons are popular, but Microsoft did never provide a good first party control that is easy to integrate in apps. Third party controls were buggy or not efficient in terms of performance. I think it is time that WinUI library has a first party, fully optimized, well performing control.

![image](https://user-images.githubusercontent.com/58418307/157677437-5a5574f2-6055-4864-8fa6-7a911371de41.png)

**Comment by kmgallahan** [comment] 2022-03-10 15:20
Dupe of #168 and proposal is essentially dead.

**Comment by hassaanmasood** [comment] 2022-03-10 16:33
Also, I strongly believe that Win UI 3 should emerge as a preferred framework for UI development on Windows. Winform & WPF, even UWP should be discarded and best of all these feature should be merged into WinUI 3. So that in future Windows and apps could have consistent UI\UX. And in case the control design changes in Win UI 3 they can be easily reflected with just a library update. Since the introduction of Windows 8, UI\UX experience across both first party and third party apps has not been very consistent. Its time to fix it and I believe Microsoft is finally headed in the right direction.

**Comment by hassaanmasood** [comment] 2022-03-10 16:36
The point is developer should have full confidence in WinUI and they should not be choosing WinForm or WPF for new apps at least. And this would be only possible if WinUI library has a wide range of controls and features.

**Comment by kmgallahan** [comment] 2022-03-10 16:36
I'm simply stating that an MS employee closed the issue that represented a ribbon control proposal in this repo, and this issue is a dupe of that one, so the purpose of this issue isn't clear.

If you want a standing open issue proposing a ribbon control then you should propose that #168 be reopened, instead of just creating a new issue with much less detail #168.

@StephenLPeters @adambarlow

**Comment by hassaanmasood** [comment] 2022-03-10 16:39
@kmgallahan I got your point. I just wrote my view on this. Also #168 is a bit different control than what I am talking about here. That is a minimized or single row version of the ribbon. I am talking about a full size ribbon like in the MS Office or new MS Paint.

**Comment by kmgallahan** [comment] 2022-03-10 16:44
Functional Requirement 9 states:

> Ability to host arbitrary XAML (developer would not get styling for free)

Which means it would support any height.

**Comment by meirumeiru** [comment] 2022-03-10 21:16
What is this? [Windows Ribbon Framework](https://docs.microsoft.com/en-us/windows/win32/windowsribbon/-uiplat-windowsribbon-entry) ... can we use this together with WinUI 3? And... when it already exists. Why can it not become a part of WinUI 3?

**Comment by kmgallahan** [comment] 2022-03-10 21:29
@meirumeiru 

> What is this?

It was/is used by the old Win32 UI framework. 

> can we use this together with WinUI 3?

Only if you use [XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api), of which I'm unsure how production ready it is.

>  Why can it not become a part of WinUI 3?

For the same reason all other Win32 & WPF controls aren't a part of WinUI, they are separate UI frameworks.

**Comment by meirumeiru** [comment] 2022-03-10 21:51
> Only if you use [XAML Islands](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/using-the-xaml-hosting-api), of which I'm unsure how production ready it is.

I didn't want to ask this in this thread, but since you mentioned it... I'm confused about this article. It's talking about "WinRT XAML" ... what's that?  WinUI 3? WinUI 2? I'm asking this, because later down it explains "WindowsXamlManager" "This class represents the UWP XAML framework..." ??? So... didn't Microsoft say, that WinUI 3 isn't available for UWP? So then... is this article not relevant for WinUI 3?

**Comment by kmgallahan** [comment] 2022-03-10 22:06
Disclaimer: I don't care about XAML islands and have never used them so I don't know much about them or their state.

The [WinUI 3 section of the WinUI roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md#winui-3) mentions:

> Enabling you to extend existing Win32 (WPF, WinForms, MFC...) apps with modern Windows UI at your own pace using the upcoming release of [Xaml Islands](https://docs.microsoft.com/windows/apps/desktop/modernize/xaml-islands).

And down in the feature matrix it is listed as experimental at the moment.

> It's talking about "WinRT XAML" ... what's that? WinUI 3? WinUI 2?

Not sure if they refer to both UWP / WinUI 2 XAML & WinUI 3 XAML as "WinRT XAML". @gabbybilka

**Comment by StephenLPeters** [comment] 2022-03-10 23:55
Closing as a duplicate

**Closed** 2022-03-10 23:55 UTC
Labels: duplicate, feature proposal, team-Controls, product-winui3

**Comment by ClearSeve** [comment] 2023-03-01 06:38
So how is paint implemented?

**Comment by castorix** [comment] 2023-03-01 08:17
> So how is paint implemented?

With MFC

**Comment by mdtauk** [comment] 2023-03-02 01:20
> > So how is paint implemented?
> 
> With MFC

Is the updated version of Paint using MFC for it's ribbon still, or is it now a XAML Island component?
