### ISSUE TITLE
AppBarButton with MenuFlyout Flyout is broken in the 1809

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#1825] opened 2020-01-09 23:38 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/872025/appbarbutton-with-menuflyout-flyout-is-broken-in-t.html)._

---
I am targeting Windows 10 version 1809 and that is also my OS version. If I have an AppBarButton inside a CommandBar and set the Flyout of the AppBarButton to a MenuFlyout.  It opens ok but then the only way to hide it is to click one of the options or click the more button, followed by a menu item or the more button again.  While the Flyout menu is visible it should collapse when the user clicks anywhere off the menu.

Steps to reproduce:
Open new UWP project.
Paste the following XML on the Main Page Grid and create the Click events

```
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <CommandBar>
            <AppBarButton Icon="NewFolder" Content="Charts" Label="Charts" Click="AppBarButton_Click" />
            <AppBarButton  Icon="Page2"  Label="test1 menu">
                <AppBarButton.Flyout>
                    <MenuFlyout >
                        <MenuFlyoutItem Text="Manage Styles" Click="MenuFlyoutItem_Click" Tag="Manage"/>
                    </MenuFlyout>
                </AppBarButton.Flyout>
            </AppBarButton>
        </CommandBar>
        <TextBox Grid.Row="1" VerticalAlignment="Top"/>

```

A similar issue was reported here
https://social.msdn.microsoft.com/Forums/vstudio/en-US/f6290df6-b640-476c-a006-68c587fcecd7/uwp-rs51809appbarbutton-with-menuflyout-flyout-is-broken-in-the-1809-update?forum=wpdevelop

It seems to be acknowledged as a bug but no action is taken.

Is there any work around suggested?

---
#### Visual Studio Feedback System on 1/2/2020, 07:01 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by YuliKl** [comment] 2020-01-10 21:53
I'm not able to repro the problem in a sample app with target and min versions set to 1809. My OS build is a newer Windows Insider build.

**Comment by YuliKl** [comment] 2020-01-10 22:02
Similar, I can't repro in the [XamlCommanding](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/XamlCommanding) sample when run on an insider build.

Closing this issue because it appears that the problem is fixed in newer OS versions.

**Closed by YuliKl** 2020-01-10 22:03 UTC
Labels: area-Commanding, area-Flyouts, team-Controls

**Comment by radev8** [comment] 2020-01-26 07:58
I can repro the problem on my machine with the XamlCommanding sample app.  Can you confirm you can reproduce the issue on an OS build 1809.  I am not able to update my laptop to the insider build as I am part of an organization which controls the release of OS upgrades.  Can you confirm if the 1903 build fixes this issue?

**Comment by radev8** [comment] 2020-01-26 08:29
Found a machine with 1909 and deployed the same app to it and it does behave correctly and the problem is resolved on 1909.

**Comment by ranjeshj** [comment] 2020-01-26 16:03
@radev8 Thanks for the confirmation.
