### ISSUE TITLE
Inconsistent NavigationView selection indicator animation

### ISSUE THREAD

**Issue by xezrunner** [microsoft/microsoft-ui-xaml#5332] opened 2021-06-30 21:53 UTC
**Describe the bug**
The NavigationView selection indicator used to stretch to its target item then compress back into its actual size.
In build 22000.51 / WinUI 2.6, the animation now jumps to place instead of stretching when switching between items that aren't adjacent to each other.

**Steps to reproduce the bug**
1. Open an app with a NavigationView on build 22000.51 - best example of this is **Settings** or the new **Microsoft Store**.
2. Try clicking on the navigation items in the left pane.
3. Observe the selection indicator animation.

**Expected behavior**
The animation should stretch and compress like it used to.

**Screen recordings**

Current behavior:

WinUI 2.6 behavior - custom app:
https://user-images.githubusercontent.com/8061077/124037534-009bd580-da00-11eb-84fd-a5804ede97b8.mp4

WinUI 2.6 behavior - Settings app on 22000.51:
https://user-images.githubusercontent.com/8061077/124037705-4193ea00-da00-11eb-9e46-69b859505185.mp4

**Expected behavior:**

Feedback Hub, pre-WinUI:
https://user-images.githubusercontent.com/8061077/124038025-c7b03080-da00-11eb-8231-aab693d9de9f.mp4

-----

**Version Info**

NuGet package version: [Microsoft.UI.Xaml 2.6.0]
OS version: 22000.51

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.51)              | Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Additional context**
Is there documentation/guidelines on how the animation is actually supposed to look like?

**Comment by zhuxb711** [comment] 2021-07-01 02:31
Same as I mention in #5275

**Comment by XeZrunner** [comment] 2021-07-01 08:47
> Same as I mention in #5275

I did see your issue as well, however, on your GIF, the animation does seem to properly stretch at least.  
Might be 22000.51 specific, but the stretching animation doesn't even occur on this build.

I do also see the jumpiness in the animation at the end, much like your issue.  
I'm not sure whether the two issues are the same.

**Comment by xezrunner** [comment] 2021-07-13 09:03
On a cold boot, the first selection change seems to not animate at all.

https://user-images.githubusercontent.com/8061077/125423836-2f3326b0-fd51-47cd-ad62-aba0f77ed61e.mp4

**Comment by xezrunner** [comment] 2022-04-19 23:16
After many months of using Windows 11, as well as seeing promotional videos showcasing this animation, it is possible that this was an intentional design change.

While I personally find the previous stretchy animation smoother and more fun, the new animation does feel more aligned with Windows 11's UI.

Keeping this open for now, in case somebody working on the design team could confirm whether this change was intentional.

**Comment by Elttob** [comment] 2023-04-30 04:48
It doesn't look intentional to my eyes. If you pixel peep while the animation is playing, it appears to be clipped by the button's background; the rounded corner of the button makes the bottom leftmost side of the indicator clip earlier, which just looks really weird. The characteristics of the animation's easing curve appear mostly unchanged from the behaviour observed in earlier WinUI versions, which leads me to believe the only thing that's changed here is that the buttons are clipping the indicator where previously they did not. This could very easily have been accidental.

Also, to sprinkle in a little bit of something more subjective; if it *were* intentional, then it isn't what I'd consider to be good taste as far as motion design goes. Because the underlying animation curve has a very large velocity around the midpoint, there is virtually no transition between the indicator exiting the clip boundary of the first button and the indicator entering the clip boundary of the second button, creating a visual discontinuity where the indicator appears to instantaneously 'teleport' to the new location after a small jitter and delay. I would not produce this kind of effect in my own work as it strikes me as rather unprofessional, though of course I am not an authority on what should or should not be considered 'good' motion design.

**Comment by Elttob** [comment] 2023-04-30 19:10
Another reason why I think this is a bug; it's not consistent with the animation style used between items of different indentation levels. When animating between indentation levels, a dedicated animation is used presumably because it can't animate straight up and down, and instead has to cross a horizontal gap. Notice that this is separate and different from the normal animation used between items of the same indentation level, which bears more similarity to the WinUI 2 animation, and which looks substantially worse:

![ApplicationFrameHost_EzEBThPh62](https://user-images.githubusercontent.com/11815374/235371799-287aa9f8-ef8f-4fb6-94e8-08daba073ef9.gif)

**Comment by xezrunner** [comment] 2023-07-12 22:57
Keeping this open in light of the [Cleanup of Stale Issues](https://github.com/microsoft/microsoft-ui-xaml/discussions/8638).

Currently, these animations seem inconsistent in intention.

**Comment by ojhad** [comment] 2023-10-16 23:12
Closing this issue since this is by design. This change was motivated by introducing hierarchy to NavigationView where having the original animation no longer made sense in all scenarios.

**Closed by ojhad** 2023-10-16 23:12 UTC
Labels: area-NavigationView, area-UIDesign, team-Controls

**Comment by dphfox** [comment] 2023-10-20 17:34
> Closing this issue since this is by design. This change was motivated by introducing hierarchy to NavigationView where having the original animation no longer made sense in all scenarios.

I didn't think that was what was being contended here. The animation works fine across hierarchy levels. It's the flat animation that was cropping incorrectly.
