### ISSUE TITLE
Layout cycle detected.  Layout could not complete.

### ISSUE THREAD

**Issue by bryfa** [microsoft/microsoft-ui-xaml#6721] opened 2022-02-15 08:41 UTC
### Describe the bug

I just added a slider control on my main window. When using it, sliding it to the right edge, I got this error.

Maybe some other parts interferre with the slider, but I dont know how. XAML code looks ok. ie. it builds and shows the main form properly

### Steps to reproduce the bug

Create a main windor put a slider on it. And just slide for a while to edges.

### Expected behavior

Should be stable

### Screenshots

![image](https://user-images.githubusercontent.com/8579202/154024577-e73bcc39-23e8-4d73-b0a9-65a2d241ae01.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by kmgallahan** [comment] 2022-02-15 20:34
Dupes:

#6003 
#6042
#477

but I have no idea if/when this problem was fixed and/or what releases it went into and/or if there has been a recent regression...

@StephenLPeters

**Comment by StephenLPeters** [comment] 2022-03-04 22:14
@RBrid FYI, this might be easier track down now.

**Comment by kmgallahan** [comment] 2023-07-29 16:45
Keep alive, unsure if this was ever fixed

**Comment by codendone** [comment] 2023-11-16 23:54
A fix for this issue has just been completed for 1.5.

**Closed by codendone** 2023-11-16 23:54 UTC
Labels: bug, area-Slider, team-Controls, product-winui3, fixed-internally
