### ISSUE TITLE
UIElement.ProtectedCursor property doesn't work

### ISSUE THREAD

**Issue by mikhailvendin** [microsoft/microsoft-ui-xaml#6047] opened 2021-10-06 12:55 UTC
### Describe the bug

ProtectedCursor property doesn't change cursor type for the UIElement. Bug was reproduced in the Windows APP SDK 0.1.0 preview 1.

### Steps to reproduce the bug

1. Open the attached project "Sample_SDK_0.1.0"
2. Run the project
3. Tap on the 'CursorTestButton' button
4. Cursor doesn't change

### Expected behavior

Cursor for the 'CursorTestButton' should change.
In the attached project 'Sample_0.8.0' ProtectedCursor property works as expected and cursor for the test button changes.
[CursorBugSamples.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7293832/CursorBugSamples.zip)

### NuGet package version

WinUI 3 - Windows App SDK 0.8: 0.8.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Bug was reproduced in the Windows APP SDK 0.1.0 preview 1.

**Comment by StephenLPeters** [comment] 2021-10-20 22:20
duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6058?

**Closed** 2021-11-16 19:15 UTC
Labels: duplicate, needs-triage, team-Framework, product-winui3
