### ISSUE TITLE
Xaml UI designer not showing up for WinUI 3 project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6430] opened 2021-12-02 22:57 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Xaml-UI-designer-not-showing-up-for-WinU/1586040)._

---
There is plenty of posts about the hot reload not working. But my problem is way more simpler : I have no UI Designer showing up in WinUI 3 Projects (I have downloaded the latest project reunion Extension).

I have visual studio Version 17.0.1

Thanks in advance !

---
#### Feedback Bot on 11/16/2021, 07:58 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by MEK3DK** [comment] 2021-12-03 08:06
Believe it or not, but that is because no designer exists for WinUI 3. :-(
There is plenty of posts about that too :-)

I don't think any work is being done on a designer, and I don't think Blend will work either.

**Comment by HydrogenC** [comment] 2021-12-26 01:35
Welcome to join in the discussion in #5917

**Comment by Einztein** [comment] 2022-01-11 09:42
The necessity of a Visual UI Designer for generating codes of UI Implementation is no need to discuss more. :lipstick:
Note that there are also professional artists in a UI group who don't know languages but power up the products no less than programmers. They need to collaborate with others. :technologist:

**Comment by StephenLPeters** [comment] 2022-02-24 22:16
This is correct, currently Winui3 does not support the Designer.

**Comment by soroshsabz** [comment] 2023-07-21 06:28
ITNOA

@StephenLPeters So implement this feature to response, many developer requests (see #5917)

and all below votes:

* [[Feature request] Visual designer for WinUI 3](https://developercommunity.visualstudio.com/t/Feature-request-Visual-designer-for-Wi/1608476?q=WinUI+Designer) - more than 47 votes
* [winui 3 xaml designer still missing](https://developercommunity.visualstudio.com/t/winui-3-xaml-designer-still-missing/10386589?q=WinUI+Designer)
* [Blend 2022 and WinUI3 when will designer be available?](https://developercommunity.visualstudio.com/t/Blend-2022-and-WinUI3-when-will-designer/1593656?q=WinUI+Designer)

**Comment by evelynwu-msft** [comment] 2023-12-19 00:49
https://github.com/microsoft/microsoft-ui-xaml/issues/5917

**Comment by evelynwu-msft** [comment] 2023-12-19 00:50
https://github.com/microsoft/microsoft-ui-xaml/issues/5917

**Comment by evelynwu-msft** [comment] 2023-12-19 00:50
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5917

**Closed by evelynwu-msft** 2023-12-19 00:50 UTC
Labels: area-Tooling, needs-triage, team-Markup, product-winui3, area-Designer
