### ISSUE TITLE
Bug report API [SetWindowCompositionAttribute] not work in 22557

### ISSUE THREAD

**Issue by Shomnipotence** [microsoft/microsoft-ui-xaml#6756] opened 2022-02-21 13:04 UTC
### Describe the bug

API [SetWindowCompositionAttribute] not work,the area draw by it become white in 22557

### Steps to reproduce the bug

Afer you update to the 22557, it will not work

### Expected behavior

![image](https://user-images.githubusercontent.com/6630660/154960724-6585d91f-9096-4bcf-bee3-9d90e92fc083.png)

### Screenshots

![R_PANDXN4TK$VXOE{JW8DC](https://user-images.githubusercontent.com/6630660/154960333-78580348-e0a2-465f-a5a8-ec8a0b779361.jpg)
https://github.com/QL-Win/QuickLook
https://github.com/QL-Win/QuickLook/issues/1088

### Windows app type

- [X] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Insider Build (xxxxx)

### Additional context

Windows Version Build 22557.ni_release.220210-1445

**Comment by kmgallahan** [comment] 2022-02-21 17:06
A Google search indicates that this is an undocumented API, which means there should be no expectation that it does anything as expected or even exists from one Windows build to the next.

Due to that this definitely isn't a bug. You could make a proposal it be turned into an official API that does a documented function.

**Comment by driver1998** [comment] 2022-02-22 02:57
You might want to use `DwmSetWindowAttribute` with `DWMWA_SYSTEMBACKDROP_TYPE` this is public API in the 22523 SDK but still **undocumented** as of now. So take it with a grain of salt.

**Comment by asklar** [comment] 2022-02-22 09:00
Closing as this is not a bug, as @kmgallahan mentioned.

**Closed by asklar** 2022-02-22 09:00 UTC
Labels: needs-triage
