### ISSUE TITLE
global::Microsoft.UI.Xaml.Application.Start -> Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#5280] opened 2021-06-25 14:43 UTC
**Describe the bug**

I updated the **NuGet packages from 0.8.0-preview to 0.8.0** and my application does not launch any more. 

![image](https://user-images.githubusercontent.com/43340959/123441165-d8f9d700-d5d3-11eb-9a11-6caf9ba37224.png)

![image](https://user-images.githubusercontent.com/43340959/123441370-0e9ec000-d5d4-11eb-82f6-dedadc63b0ba.png)

NuGet package version: 

```
	<ItemGroup>
		<PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0" />
		<PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0" />
		<PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0" />
		<Manifest Include="$(ApplicationManifest)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
		<PackageReference Include="Prism.DryIoc.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Prism.Uno.WinUI" Version="8.1.97" />
		<PackageReference Include="Uno.Core" Version="2.4.0" />
	</ItemGroup>
```

**Additional context**

![image](https://user-images.githubusercontent.com/43340959/123441555-44dc3f80-d5d4-11eb-901f-3c2eab521cb2.png)

**Comment by asklar** [comment] 2021-06-27 00:10
@sigmarsson which OS build are you on?

**Comment by sigmarsson** [comment] 2021-06-27 07:02
![image](https://user-images.githubusercontent.com/43340959/123534782-d60bfd00-d71f-11eb-9bc2-044558fd4230.png)

**Comment by asklar** [comment] 2021-06-27 07:10
@sigmarsson please make sure you are running the Package project (not the app project).
It looks like this might be a duplicate of #4537

**Comment by asklar** [comment] 2021-06-27 07:12
See also microsoft/WindowsAppSDK#583

**Comment by sigmarsson** [comment] 2021-06-27 07:16
Sure, 
1. that is set as start up project.
2. Deployed
3.  > Local Machine

The error keep persisting until **0.8.0** is downgraded to "**-preview**".

**Comment by sigmarsson** [comment] 2021-06-27 07:57
#4537 is occurring in `CreateInstanceDefaultCtorSlow`, this one is in `Application.Start`, or is it the same virtually ?

**Comment by StephenLPeters** [comment] 2021-06-29 23:25
@MikeHillberg FYI

**Comment by sigmarsson** [comment] 2021-07-16 11:45
Tried with 2019 Preview :

![image](https://user-images.githubusercontent.com/43340959/125942684-0407174b-8c88-4f71-b832-d4f43653d161.png)

**Comment by sigmarsson** [comment] 2021-07-20 07:57
#5497 contains an additional dump file as well.

**Comment by sigmarsson** [comment] 2021-07-30 21:58
@MikeHillberg ?

**Closed** 2021-07-31 19:15 UTC
Labels: area-NugetPackage, product-winui3, team-Markup, version-ProjectReunion 0.8
