### ISSUE TITLE
How to use the WinRT API SystemTray class

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#9204] opened 2024-01-04 14:27 UTC
### Describe the bug

How to use WinRT API SystemTray class? I found the official API document, but there are no version requirements and code examples of this API. May I ask how to use this API? In addition, when will the Windows app sdk provide a usable SystemTray API?

WinRT API SystemTray 类怎么使用，我找到了官方的API文档，但是没有该API的版本要求和代码示例，请问一下这个API该如何使用。除此之外，Windows app sdk什么时候能提供一个可用的SystemTray API呢？

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/49179966/a5500d59-170a-430a-946d-d0e0778134bd)
https://learn.microsoft.com/zh-cn/uwp/api/windows.ui.viewmanagement.systemtray

### Steps to reproduce the bug

See above

### Expected behavior

See above

### Screenshots

See above

### NuGet package version

WinUI 3 - Windows App SDK 1.4.3: 1.4.231115000

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

None

**Comment by asklar** [comment] 2024-01-09 18:06
Duplicate of microsoft/WindowsAppSDK#4063

**Comment by bpulliam** [comment] 2024-01-18 17:56
Closing the duplicate

**Closed by bpulliam** 2024-01-18 17:56 UTC
Labels: bug, needs-triage
