### ISSUE TITLE
Question: How can I interact with the UI elements inside the drag rectangle

### ISSUE THREAD

**Issue by dylech30th** [microsoft/microsoft-ui-xaml#6066] opened 2021-10-08 18:34 UTC
I am trying to migrate my app to be compatible with Windows 11 Style with Windows App SDK 1.0.0 preview2, and I found that if I set `AppWindowTitleBar.ExtendsContentIntoTitleBar ` property to `true`, the UI elements (a `CommandBar` for example) inside the title bar area (the area that is used to detect the drag operation) will not be interactive, call `SetDragRectangles(RectInt32[])` to set the drag rectangle size to zero can solve this problem but then you cannot drag the application anymore. Is there any way to extend the content while preserving the interactivity?

**Comment by krschau** [comment] 2022-06-22 17:05
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4233

Unfortunately, this is not possible in WinAppSDK right now. If you have more thoughts or questions on the subject, please post them in that issue.

**Closed by krschau** 2022-06-22 17:05 UTC
Labels: question, needs-triage, team-Reach, area-TitleBar, v1.0.0-preview2
