### ISSUE TITLE
IPrintManagerInterop::ShowPrintUIForWindowAsync throws System.Runtime.InteropServices.COMException

### ISSUE THREAD

**Issue by riverar** [microsoft/microsoft-ui-xaml#5831] opened 2021-09-03 06:09 UTC
Calling `IPrintManagerInterop::ShowPrintUIForWindowAsync` results in a `System.Runtime.InteropServices.COMException: 'Invalid window handle. (0x80070578)'`. These interop APIs typically exist to allow usage with HWND windowing, so I expect it to work in an unpackaged WinUI 3 scenario.

**Steps to reproduce**
1. `git clone https://github.com/riverar/mux-repros/`
2. `cd mux-repros/unpackaged/mux_issue_5831`
3. `mux_issue_5831.csproj`
4. Build/launch project
5. Observe exception / program terminates

**Version Info**

Windows App SDK 1.0-experimental1
Unpackaged desktop application
Windows 11 (22449.1000) and downlevel

**Comment by asklar** [comment] 2021-09-03 17:00
Duplicate of #4419
See also #5080
looks like the print APIs have not been updated to work on desktop.

**Comment by riverar** [comment] 2021-09-03 17:06
@asklar Thanks, good catch. Feel free to close.

**Closed** 2021-09-03 17:46 UTC
Labels: needs-triage

**Comment by FreddyD-GH** [comment] 2021-09-03 18:56
@riverar  FYI, I'm not sure if this is actually a C#-specific problem or not, but there is also an issue in the CsWinRT repo related to getting the printing APIs to work: https://github.com/microsoft/CsWinRT/issues/968.

**Comment by riverar** [comment] 2021-09-03 18:58
@FreddyD-GH Thanks will take a look. I actually ran into this issue with Rust and had to create a repro in C# to confirm.

**Comment by AdamBraden** [comment] 2021-09-03 19:58
@riverar  - can you confirm if you are only seeing the exception in unpackaged (non-MSIX) apps?

**Comment by riverar** [comment] 2021-09-03 21:01
@AdamBraden That particular API fails in the same way packaged. And I can reproduce the linked issue ( 0x80040155 : 'Interface not registered (0x80040155)') if I go directly to PrintManager (non-interop).

This is one hairy API!
