### ISSUE TITLE
ColorPicker tooltip for color name doesn't dismiss when scrolling away

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#5722] opened 2021-08-18 23:27 UTC
**Describe the bug**

WinUI 2.6 UWP on Desktop

Add a ScrollViewer and inside it, a ColorPicker
select a color, a tooltip with the closest color name shows up
scroll the scrollviewer

Observe that the tooltip does not scroll with the ColorPicker as we scroll, and in fact even after the ColorPicker is scrolled off the screen, the tooltip remains.

**Comment by robloo** [comment] 2021-08-19 01:36
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/3237

**Comment by StephenLPeters** [comment] 2021-08-19 23:21
yup, unfortunately still hasn't been fixed :/

**Comment by robloo** [comment] 2021-08-20 03:06
I thought a fix was proposed in the other issue but was waiting on the Microsoft team for feedback.

**Closed** 2021-08-20 03:10 UTC
Labels: duplicate, area-ColorPicker, team-Controls
