### ISSUE TITLE
Win32: Wrong field datatypes on Rect and Point

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#2474] opened 2020-05-19 15:41 UTC
**Describe the bug**
The Win32 projection of `Windows.Foundation.Point` and `Windows.Foundation.Rect` has the wrong datatype. They consist of floats instead of doubles.
The inconsistency makes it really hard to create code that works on both the same way, and historically UI as always been using double-precision values. These types are used throughout the WinUI controls.
I literally have 100s of build errors, and would have to make heavy use of `#if-def` between UWP and NET5.0 targets.

**Steps to reproduce the bug**
Create a Win32 and UWP project with WinUI and compare the definition of the two datatypes.

**Expected behavior**
Double fields should be used instead of float.

**Screenshots**

Win32 (left) vs UWP (right):
![image](https://user-images.githubusercontent.com/1378165/82340586-3e789e80-99a4-11ea-927b-27460c5d891e.png)

![image](https://user-images.githubusercontent.com/1378165/82340614-489a9d00-99a4-11ea-814d-7be87e9aa87d.png)

**Version Info**
```xml
    <PackageReference Include="Microsoft.WinUI">
      <Version>3.0.0-preview1.200515.3</Version>`
    </PackageReference>
```
NuGet package version:  3.0.0-preview1.200515.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by chingucoding** [comment] 2020-05-19 15:45
The problem is that the winrt types are actually only using floats, however those can't be passed through the ABI correctly, that's why they are exposed as doubles for language projection in UWP.

See this issue for more context: #2047

**Comment by dotMorten** [comment] 2020-05-19 15:48
@chingucoding I'm more against the difference between UWP and Win32, then I'm against floats instead of doubles. They shouldn't be different. I'd have to create literally 100s of if-defs to compile for both targets.

**Comment by chingucoding** [comment] 2020-05-19 15:55
The question is what data type is correct here, which platform behaves correctly here? If we are actually using floats under the hood, lifting the win32 apis up to `double` might not be the best solution. 

But yes, I agree that it's crucial that those type's behave the same regardless of win32 or UWP.

**Comment by dotMorten** [comment] 2020-05-19 16:04
Also you'd need to change all the other double values used in XAML that relates to positioning of UI

**Comment by stevenbrix** [comment] 2020-05-19 16:45
I'm going to explain my thoughts/rationale on why this discrepancy exists today. We're definitely open to having a conversation on this, and come to an agreement on what the right course of action is. 

> But yes, I agree that it's crucial that those type's behave the same regardless of win32 or UWP.

Absolutely agree, the difference between the two is a point-in-time issue. It's not really about UWP vs Desktop, it's more .NET Native vs .NET5. Once we are all on the same system, there won't be this discrepancy.

We are working on a tool (Roslyn analyzer+code fixer) that will make these changes to your code automatically, it just doesn't exist at the moment. We're hoping that the impact here will be minimal, but if there are corner cases that the tool won't be able to detect, then we want to understand this, because it will impact our decision here.

The main reason for us doing this for Preview1 is that this is just the way the new language projection worked by-design, because those types really are `float`. We would need to add a workaround to resort back to the old behavior, which we weren't really sure we wanted to do.

> It's also inconsistent throughout because there's lot of other places where UI is handled in doubles instead of floats, like ActualWidth/Height, Gridlength.Value, Thickness etc.

The inconsistency of `float` and `double` isn't strictly due to `Size/Rect/Point`, the XAML parser doesn't work with `float` properties, and those properties that are doubles (like `ActualWidth`) are actually stored as floats.

Let's continue discussion on this topic on #2047

**Comment by stevenbrix** [comment] 2020-05-19 19:17
Closing for #2047

**Closed by stevenbrix** 2020-05-19 19:17 UTC
Labels: needs-triage
