### ISSUE TITLE
Microsoft.Xaml.Interactivity bug in WinUI 3 Preview 4 making further development a non starter.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4350] opened 2021-02-25 16:10 UTC
**Describe the bug**
Microsoft.Xaml.Interactivity is not working as expected with WinUI 3 Preview 4.  

Given the following XAML:

```
            <Frame x:Name="ContentFrame" x:FieldModifier="Public" Padding="14 14" >
                <i:Interaction.Behaviors>
                    <ic:EventTriggerBehavior EventName="Loaded">
                        <ic:InvokeCommandAction Command="{x:Bind ViewModel.FrameLoadedCommand}" CommandParameter="{Binding ElementName=ContentFrame}"/>
                    </ic:EventTriggerBehavior>
                </i:Interaction.Behaviors>
                <Frame.ContentTransitions>
                    <TransitionCollection>
                        <NavigationThemeTransition>
                            <NavigationThemeTransition.DefaultNavigationTransitionInfo>
                                <DrillInNavigationTransitionInfo />
                            </NavigationThemeTransition.DefaultNavigationTransitionInfo>
                        </NavigationThemeTransition>
                    </TransitionCollection>
                </Frame.ContentTransitions>
            </Frame>
```

The CommandParameter is null when it should have the value of the Frame "ContentFrame" object.

**Steps to reproduce the bug**

You may use the following GitHub repository: https://github.com/Noemata/SimpleMVVM

1. Build SimpleMVVM
2. Set a breakpoint on the if () line as shown below within the SetupNavigationService method in ShellViewModel.cs which is part of the SimpleMVVM solution (note: UWP equivalent project is also provided).

```
        private void SetupNavigationService(Frame frame)
        {
            // MP! fixme: why is frame null??
            if (frame != null)
                NavigationService.Frame = frame;
        }
```

3.  Click the About "( ! ) " menu item when the app launches.

**Expected behavior**

CommandParameter should not be null.

**Screenshots**
![image](https://user-images.githubusercontent.com/6632315/109181827-5c0c3d00-775a-11eb-98a9-7ad469c466d8.png)

**Version Info**

NuGet package version: [Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**

This issue blocks any further development prospects with WinUI 3 Preview 4 as it cripples the ability to easily port working code over from UWP.  The provided sample has a fully functional UWP equivalent app using the exact same code constructs which should work in WinUI 3 Preview 4.

**Comment by duke7553** [comment] 2021-02-25 19:20
@Noemata There is a separate repo for Microsoft.Xaml.Interactivity here: https://github.com/microsoft/XamlBehaviors where you might have more luck reporting the problem you faced.

**Comment by Noemata** [comment] 2021-02-25 19:44
@duke7553 , I do not feel it is appropriate to start there, since this may turn out to be a WinUI 3p4 issue irrespective of the fact that it initially looks like a XamBehaviors problem.  I may post this there also.  Thanks for the suggestion.

I'm leaning toward blaming WinUI because this works in UWP.  So it suggests the framework XAML behaviors is sitting on may be broken.  Unless Xaml Behaviors is very different under the hood for WinUI (haven't looked myself).

**Comment by StephenLPeters** [comment] 2021-02-26 00:14
@MikeHillberg FYI @JesseCol looks to have temporarily removed behaviors from XCG and might know more about the current state of its support.

**Comment by JesseCol** [comment] 2021-02-26 01:37
Hi all, I removed XamlBehaviors from XCG a while back, I don't think it had been updated to work with WinUI 3 at that point.  But it looks like @azchohfi may be working on XamlBehaviors to keep up with the latest WinUI 3 previews -- maybe he knows if this is working well today?

**Comment by Noemata** [comment] 2021-02-26 17:45
@azchohfi, I tested a bunch of binding expressions with the Preview4 branch of XAML Behaviors.  Was any of this tested?  I see many things not working.  I can't tell what layer is at fault.

In future, please include release notes with XAML Behaviors so we know what to expect, if things are broken during your testing.  That said, this level of quality shouldn't get out the door.  Sorry to have to be so blunt.

**Comment by azchohfi** [comment] 2021-03-08 20:57
This is an issue with WinUI3, when using Binding with ElementName. Not a Xaml Behaviors issue.
I believe @alwu-msft fixed this already, but its not out. The next public version should have this fixed. Alan, can you confirm?
This might be a dupe of another issue, but I couldn't find anything.

**Comment by alwu-msft** [comment] 2021-03-08 22:07
Correct, an upcoming preview of WinUI 3 should have the fix for the bug affecting ElementName Bindings. It seems that the recent discussion is leaning toward the theory that this is a dupe of the aforementioned bug, so I'm keeping my fingers crossed.

**Comment by JanRajnoha** [comment] 2021-03-21 22:00
What's the status of this issue? Is any option to replace Microsoft.Xaml.Interactivity or we need to wait to another preview? @alwu-msft

**Comment by Noemata** [comment] 2021-03-22 02:12
@JanRajnoha , appears to be resolve with WinUI 0.5.  You can look for example usage here: https://github.com/Noemata/FakePOS

**Comment by JanRajnoha** [comment] 2021-03-22 10:23
@Noemata It looks it is working. Thanks for tip

**Comment by krschau** [comment] 2021-07-19 19:51
Closing this issue, since it is working in the Project Reunion 0.5 release as mentioned above.

**Closed by krschau** 2021-07-19 19:51 UTC
Labels: product-winui3, version-preview4
