### ISSUE TITLE
The Window.Activated event fires twice after maximizing a minimized window

### ISSUE THREAD

**Issue by PureWeen** [microsoft/microsoft-ui-xaml#7343] opened 2022-07-05 23:45 UTC
### Describe the bug

If you minimize a window and then maximize it you will get two symmetrical `Activated` events 

// Minimize window
```
OnActivated. WindowActivationState: Deactivated Handled: False Microsoft.UI.Xaml.WindowActivatedEventArgs
```

// Maximize Window
```
OnActivated. WindowActivationState: CodeActivated Handled: False Microsoft.UI.Xaml.WindowActivatedEventArgs
OnActivated. WindowActivationState: CodeActivated Handled: False Microsoft.UI.Xaml.WindowActivatedEventArgs
```

I tested this behavior on UWP and on UWP it only fires one event when maximizing the window. 

### Steps to reproduce the bug

[App86.zip](https://github.com/microsoft/WindowsAppSDK/files/9050274/App86.zip)

I've added an activated event to the window 
![image](https://user-images.githubusercontent.com/5375137/177434422-d9fbb777-8f50-4eb0-a095-f6a6e1479819.png)

1)  Minimize the window
2) Maximize the window

You'll see two messages logged during the Maximize phase.

### Expected behavior

Only one `CodeActivated` event should fire when maximizing the window. 

### NuGet package version

1.1.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

**Comment by pratikone** [comment] 2022-11-21 19:59
Thanks for reporting this. this is indeed an issue. I have debugged it and found the root cause. Will be working on fixing ti

**Comment by pratikone** [comment] 2023-03-30 18:34
@mattleibow  thanks. you can use [task.ms](https://task.ms/) to track internal issues on public repos.

**Comment by axa88** [comment] 2023-08-09 20:43
> ### Windows version
> 
> Windows 11 version 21H2 (22000)

fwiw I can affirm that this issue appears to affect Android as well.

**Comment by pratikone** [comment] 2024-03-11 22:44
Ok, finally was able to get this in. I think it will be part of 1.6. It took a while because it was a breaking change and we needed to time it.

**Closed by pratikone** 2024-03-11 22:44 UTC
Labels: bug, team-Reach, product-winui3, area-App activation
