### ISSUE TITLE
Freeze when app is resumed and a secondary application view was created and closed before

### ISSUE THREAD

**Issue by lhak** [microsoft/microsoft-ui-xaml#802] opened 2019-06-04 17:37 UTC
**Describe the bug**

I posted the same issue on stackoverflow but it was not resolved in more than a month so posting it here again. Basically using secondary application views in combination with registering certain lifecycle events (in this case by the appcenter library) will lead to complete freezes of any application on both recent Windows versions.

**Steps to reproduce the bug**

- A secondary ApplicationView is created from the main view.

- When it is closed by the user, the Consolidated event fires and the handler calls Window.Current.Close() at the end.

- The main view is minimized by the user causing the application EnteredBackground and Suspending event to fire.

- When the view is restored, its UI is frozen.

So far I have found that adding any event handler (even an empty one) to the LeavingBackground event of the application object causes this behavior if the secondary view has been opened and closed before. Using the old Resuming event however works fine (but does not help because appcenter uses the newer LeavingBackground event).

A repro project is here (a slightly modified version of one of the UWP samples):

https://github.com/lhak/Windows-universal-samples/tree/master/Samples/MultipleViews/cs

**Expected behavior**

The application should not freeze but resume correctly

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  X  |
| October 2018 Update (17763)        |  X  |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | X   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by lhak** [comment] 2019-08-20 09:02
Any updates on this? It is a serious bug (app is completely freezing) and there does not seem to be workaround.

**Comment by benstevens48** [comment] 2020-02-23 22:30
@jevansaks - I have new information that will help solve this absolutely critical bug. Please take a look at it. If this issue doesn't get any attention I will open a new one.

I have created an absolutely minimal project to demonstrate the issue - [TestMultipleViews.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4242513/TestMultipleViews.zip)

Steps to reproduce the issue are the same.

1.  Run the app
2.  Click 'Open view'
3.  Close the newly opened window.
4.  Minimise the original window
5.  Unminimize the original window
6.  The window should now be in a state where the content is simply a static image and if you resize the window to make it bigger the new area will have a blue background.

Key features which cause this issue (assuming steps 1-6 are followed):
-   Adding either an EnteredBackground or LeavingBackground event handler to the Application.
-   Including a ComboBox control somewhere on the MainPage.

If you omit either of these two conditions then the issue does not occur. (I don't know if there are other controls apart from the ComboBox that trigger it).

Other interesting points:
-   This issue occurs even when run using the debugger in Visual Studio - it appears that suspending does not need to occur for the issue to trigger.
-   If you add an EnteredBackground handler, then the app doesn't seem to ever be suspended after step 4 above (without the debugger attached, using the unscientific method of looking for a leaf symbol in the Task Manager).

Thanks so much to @lhak for posting the original issue and putting me onto the fact that it was to do with the LeavingBackground event handler being added. I have been struggling to pin down this issue for ages but I could never reproduce it when I wanted to - I've had reports from users and occasionally triggered it myself. I think the reason I never got anywhere was because of the requirement of a ComboBox to be involved, which is not initially present in my app's UI. I have now removed the LeavingBackground and EnteredBackground handlers from my app, and hopefully this will fix the issue for my users.

Please, please would the WinUI team try to fix this bug, ideally in the platform code base as soon as possible. It potentially prevents any app which uses multiple views from working reliably.

To anyone else reading this - if you have an app that uses multiple views, the message is **do not add LeavingBackground or EnteredBackground handlers** if you can possibly avoid it.

**Comment by benstevens48** [comment] 2020-03-02 17:54
@ranjeshj - did the comment I made above come to the team's attention? I'm not sure I mentioned the right team member. Just trying to make sure someone from the team has read it in case there's a chance to fix it in the platform codebase for the 2020 H1 update (although it's probably too late I guess).

**Comment by ranjeshj** [comment] 2020-03-02 17:57
@chrisglein did you get a chance to look at this issue ?

**Comment by chrisglein** [comment] 2020-03-04 01:20
Not yet. Thanks for the detailed (and minimal!) repro @benstevens48! We'll get this under the debugger.

**Comment by lhak** [comment] 2020-04-04 15:05
What is the status of this issue?

**Comment by lhak** [comment] 2020-06-15 08:59
I reported this bug over one year ago and it is still not fixed...

**Comment by HppZ** [comment] 2021-07-28 08:40
once again I need your HELP, PLEASE. @codendone

**Comment by HppZ** [comment] 2021-07-28 08:44
@codendone there is some additional information.
https://docs.microsoft.com/en-us/answers/questions/235494/uwp-after-closing-secondary-window-main-app-won39t.html

**Comment by HppZ** [comment] 2021-07-28 08:50
https://stackoverflow.com/questions/55894118/freeze-when-app-is-resumed-and-a-secondary-application-view-was-created-and-clos

**Comment by HppZ** [comment] 2021-07-28 09:05
have to say, so painful being a dev on Windows.

**Comment by codendone** [comment] 2021-07-30 04:39
Pretty weird bug for this to somehow be caused by a ComboBox plus EnteredBackground/LeavingBackground plus closing the window of a secondary view. I repro the issue with the provided app.

I don't yet see the cause of the bug. The app stops working because some code below XAML decided to not re-show the CoreWindow when restoring the window -- the window frame is re-shown, but not the CoreWindow. Why that happened isn't yet clear. I [logged a bug](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/34931291) to track this internally.

**Comment by codendone** [comment] 2021-07-31 02:39
Update: It looks like there is a timing issue here somewhere. Removing the ComboBox makes the problem no longer repro, but at that point adding a Sleep(300) in the LeavingBackground handler makes the problem likely to repro. I've handed the internal bug off to another team to investigate further.

**Comment by HppZ** [comment] 2021-08-07 03:42
any update here?

**Comment by HppZ** [comment] 2021-11-24 13:30
@chingucoding HELP.

**Comment by chingucoding** [comment] 2021-11-24 18:34
Sorry @HppZ there isn't anything I can do here.

**Comment by HppZ** [comment] 2021-11-25 04:39
> Sorry @HppZ there isn't anything I can do here.

can you fix it or send it to the proper team?

**Comment by DavidRufino** [comment] 2021-12-13 16:12
Hello, while the critical issue affecting user experience is not resolved.

I have been looking for a solution to this very problem mentioned by lhak and Benstevens48.

With many hours of testing, I was able to find a workaround to avoid screen freezing as follows:

Add the restricted functionality confirmAppClose to allow you to identify the event CloseRequested of the second window:
https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations
(It needs extra approval when submitting to the store.)

The code in the second window will look like this:

```
public SecondaryView()
{
    this.InitializeComponent();

    SystemNavigationManagerPreview.GetForCurrentView().CloseRequested -= SecondaryView_CloseRequested;
    SystemNavigationManagerPreview.GetForCurrentView().CloseRequested += SecondaryView_CloseRequested;
}

private async void SecondaryView_CloseRequested(object sender, SystemNavigationCloseRequestedPreviewEventArgs e)
{
    Debug.WriteLine("[SecondaryView] SecondaryView_CloseRequested"); 

    //  NOTE: The BeginExtendedExecution() method must be in front of ApplicationViewSwitcher.SwitchAsync()
    await BeginExtendedExecution();

    await ApplicationViewSwitcher.SwitchAsync(MainPageId);
}

/// <summary>
/// Codigo obtido no Windows-universal-samples/Samples/ExtendedExecution/
/// https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/ExtendedExecution
/// </summary>
private async Task BeginExtendedExecution()
{
    Debug.WriteLine("[SecondaryView] BeginExtendedExecution");

    // The previous Extended Execution must be closed before a new one can be requested.
    // This code is redundant here because the sample doesn't allow a new extended
    // execution to begin until the previous one ends, but we leave it here for illustration.
    ClearExtendedExecution();

    var newSession = new ExtendedExecutionSession();
    newSession.Reason = ExtendedExecutionReason.Unspecified;
    newSession.Description = "Raising periodic toasts";
    //newSession.Revoked += SessionRevoked;
    ExtendedExecutionResult result = await newSession.RequestExtensionAsync();

    switch (result)
    {
        case ExtendedExecutionResult.Allowed:
            Session = newSession;
            Debug.WriteLine("[SecondaryView] BeginExtendedExecution Allowed");
            break;

        default:
        case ExtendedExecutionResult.Denied:
            newSession.Dispose();
            Debug.WriteLine("[SecondaryView] BeginExtendedExecution Denied");
            break;
    }
}

/// <summary>
/// Limpar as Extended Session que estao executadas
/// </summary>
internal void ClearExtendedExecution()
{
    Debug.WriteLine("[SecondaryView] ClearExtendedExecution");

    if (Session != null)
    {
        Session.Dispose();
        Session = null;
    }
}
```

Using BeginExtendedExecution() the application no longer had the problem of freezing.

**Comment by Kumara-Krishnan** [comment] 2023-03-03 14:41
> Update: It looks like there is a timing issue here somewhere. Removing the ComboBox makes the problem no longer repro, but at that point adding a Sleep(300) in the LeavingBackground handler makes the problem likely to repro. I've handed the internal bug off to another team to investigate further.

@codendone Is there any update on this issue?

**Comment by FrayxRulez** [comment] 2023-11-15 19:42
Not sure if this can be useful, but this seems to happen because the secondary view thread hangs forever on `CoUninitialize`:
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/8152849/43a8ed3f-cf76-41ca-82a0-98977fe0dab3)

Terminating the secondary view thread from Process Explorer BEFORE minimizing the main view does indeed prevent the issue from occurring.

**Comment by FrayxRulez** [comment] 2023-11-16 09:04
Following up, there are two distinct issues:
- First of all, in some conditions the secondary view thread fails to exit and hangs forever on `CoUninitialize`, this happens regardless of `EnteredBackground`/`LeavingBackground`
- Second, if you hook one of the two events and there's a orphaned window thread, the main application thread will hang forever (likely because it internally uses the event deferral and never releases it because the orphaned thread will never respond?)

Now, after a bit more of investigation, this seems to happen in the provided repo because of the `Popup` contained within the `ComboBox`, or at least, removing the `Popup` prevents the issue from happening.

**Closed** 2024-02-24 06:58 UTC
Labels: bug, area-ComboBox, internal tracking, area-Navigation, team-CompInput, closed-Won'tFix
