### ISSUE TITLE
Self contained, WindowsPackageType none, Single file published winui3 app is not launching

### ISSUE THREAD

**Issue by Fefedu973** [microsoft/microsoft-ui-xaml#9758] opened 2024-06-26 17:42 UTC
### Describe the bug

I spend hours trying to make it work but basically Self-contained, WindowsPackageType none, Single file published winui3 exe file are crashing.

```
<WindowsPackageType>None</WindowsPackageType>
<WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
```
This is the error I get when i start the exe in visual studio in debug mode.
```Exception non gérée à 0x756A8984 (KernelBase.dll) dans App1.exe : 0xE0434352 (paramètres : 0x80131524, 0x00000000, 0x00000000, 0x00000000, 0x00540000).``` (you can see that at the end of the video)

### Steps to reproduce the bug

https://github.com/microsoft/microsoft-ui-xaml/assets/80718477/322429d6-0dd0-47a7-a9b8-e8e8ad2c3d0e

### Expected behavior

The app should launch

### NuGet package version

WinUI 3 - Windows App SDK 1.5.4: 1.5.240607001

### Windows version

Windows Insider Build (xxxxx)

**Comment by lhak** [comment] 2024-06-26 20:00
As it looks that you have trimming enabled, you might want to try setting <TrimMode> to "partial" in your .csproj file.

**Comment by Fefedu973** [comment] 2024-06-26 20:19
Where did you see trimming enabled, i don't see that in the csproj file ?
Should I add this ?
```
<PublishTrimmed>true</PublishTrimmed>
    <TrimmerDefaultAction>link</TrimmerDefaultAction>
    <TrimMode>partial</TrimMode>
```

**Comment by lhak** [comment] 2024-06-26 20:23
Check your publish profile and see if PublishTrimmed is enabled there (according to your video, it seems to be). You might also want to try setting it to false.

**Comment by Fefedu973** [comment] 2024-06-26 20:28
Ok I found the settings but unfortunately it didn't worked I still have this annoying error and the app doesn't start at all.
```
Exception non gérée à 0x756A8984 (KernelBase.dll) dans App1.exe : 0xE0434352 (paramètres : 0x80131524, 0x00000000, 0x00000000, 0x00000000, 0x00640000).
```

**Comment by lhak** [comment] 2024-06-26 21:25
I could reproduce this issue. It started working once I deleted the obj and bin folders once.

**Comment by Fefedu973** [comment] 2024-06-26 21:31
How did you do it because I just deleted bin and obj folders, re-run the publish process and my software still cannot start unfortunately );

**Comment by lhak** [comment] 2024-06-27 07:05
I did the following steps:

-Create the new project
-Add TrimMode=partial, WindowsPackageType=None and WindowsAppSdkSelfContained=true setting to the csproj. 
-Open the publish profile for the architecture and change PublishSingleFile to true. 
-I also had to change win10-platform to win-platform in the publish profile. Somehow the .net version detection does not seem to  work when publishing from visual studio which results in an error
-The app should now publish, but crashes during startup
-Delete the obj and bin folder
-Publish again
-App now starts

**Comment by Fefedu973** [comment] 2024-06-27 07:19
Wait it finally worked thank you !!!!! Tbh I don't know what I have done differently

**Comment by abdx79** [comment] 2024-06-28 08:58
> Wait it finally worked thank you !!!!! Tbh I don't know what I have done differently

can you share your project files. I'm having the same issue.

**Comment by Fefedu973** [comment] 2024-06-28 12:02
Yes of course it's on my GitHub

**Comment by Fefedu973** [comment] 2024-06-28 12:03
Don't look the code too closely it's bad 😅 (it's my first native windows app ever) but you can just wipe all the code and put your code instead and it should work 
https://github.com/Fefedu973/PowerToys-Run-Plugin-Updater

**Comment by abdx79** [comment] 2024-06-28 12:21
> Don't look the code too closely it's bad 😅 (it's my first native windows app ever) but you can just wipe all the code and put your code instead and it should work https://github.com/Fefedu973/PowerToys-Run-Plugin-Updater

man you are too generous, thank you. let see if it works.

**Comment by abdx79** [comment] 2024-06-28 14:11
It works!,

It works after adding these 
```
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <TrimMode>partial</TrimMode>
```

in `<PropertyGroup>` in   `.csproj` file and doing the following changes in `PublishProfiles`.

The majority of changes happens in publish profile where I only wanted to publish x64 version.

publish profile address: `YourProject\Properties\PublishProfiles`

### **Working**: `Project1.xml`
### Not **working**: `Project2.xml`

### File 1: `Project1.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- https://go.microsoft.com/fwlink/?LinkID=208121. -->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Platform>x64</Platform>
    <RuntimeIdentifier Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win-x64</RuntimeIdentifier>
    <PublishDir>bin\\\win10-x64\publish\</PublishDir>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">true</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">false</PublishTrimmed>
    <Configuration>Release</Configuration>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
</Project>
```

### File 2: `Project2.xml`
```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- https://go.microsoft.com/fwlink/?LinkID=208121. -->
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PublishProtocol>FileSystem</PublishProtocol>
    <Platform>x64</Platform>
    <RuntimeIdentifier Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x64</RuntimeIdentifier>
    <RuntimeIdentifier Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x64</RuntimeIdentifier>
    <PublishDir>bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\publish\</PublishDir>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>False</PublishSingleFile>
    <PublishReadyToRun Condition="'$(Configuration)' == 'Debug'">False</PublishReadyToRun>
    <PublishReadyToRun Condition="'$(Configuration)' != 'Debug'">True</PublishReadyToRun>
    <PublishTrimmed Condition="'$(Configuration)' == 'Debug'">False</PublishTrimmed>
    <PublishTrimmed Condition="'$(Configuration)' != 'Debug'">True</PublishTrimmed>
  </PropertyGroup>
</Project>
```

### Differences between Project1.xml and Project2.xml

1. **RuntimeIdentifier Property:**
   - **Project1.xml:** Uses `win-x64` regardless of the target framework version.
   - **Project2.xml:** Uses `win-x64` for target framework versions >= 8 and `win10-x64` for versions < 8.

2. **PublishDir Property:**
   - **Project1.xml:** Uses a hardcoded path `bin\\\win10-x64\publish\`.
   - **Project2.xml:** Uses a dynamic path `bin\$(Configuration)\$(TargetFramework)\$(RuntimeIdentifier)\publish\`.

3. **PublishSingleFile Property:**
   - **Project1.xml:** Set to `true`.
   - **Project2.xml:** Set to `False`.

4. **PublishTrimmed Property:**
   - **Project1.xml:** Set to `False` in both Debug and non-Debug configurations.
   - **Project2.xml:** Set to `False` in Debug and `True` in non-Debug configurations.

5. **Configuration Property:**
   - **Project1.xml:** Explicitly set to `Release`.
   - **Project2.xml:** Not explicitly set (it relies on the build configuration being used).


The generated exe file in `\bin\win10-x64\publish` works in my Computer but I'm not sure that it will work in other Computers, 
Will it work ?
Thanks!

**Comment by Scottj1s** [comment] 2024-07-29 21:59
Closing, as this issue appears to be resolved with a change to trimming policy, similar to:
https://github.com/microsoft/microsoft-ui-xaml/issues/9740

@Fefedu973 If the suggested fix is not effective, feel free to reopen.

**Closed by Scottj1s** 2024-07-29 21:59 UTC
Labels: bug, area-ProjectSystem, team-Markup

**Comment by Fefedu973** [comment] 2024-07-29 22:01
Okay thanks Scott !
