### ISSUE TITLE
Cannot find a Resource with the Name/Key TabViewItemHeaderBackground 

### ISSUE THREAD

**Issue by CarlSharp** [microsoft/microsoft-ui-xaml#1295] opened 2019-09-09 01:13 UTC
After recent updates, UWP Unit Test App fails at InitializeComponent() within page using Microsoft.UI.Xaml.Controls.NavigationView.

1. Create new Unit Test App (Universal Windows)
2. Add Microsoft.UI.Xaml NuGet package
3. Add MUXC to application resource
4. Have UITestMethod navigate to page containing a MUXC NavigationView control

**Expected behavior**
Test will not throw:

> **Windows.UI.Xaml.Markup.XamlParseException**:..
> 
> Cannot find a Resource with the Name/Key
> TabViewItemHeaderBackground [Line: 18 Position: 69]'

**Version Info**
Project Target Version: Win 10.0 18362
OS: Win 10.0 18362.329

NuGet package version: 
Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | No   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes  |
| Mobile                   |   |
| Xbox                      |   |
| Surface Hub          |    |
| IoT                         |   |

**Additional context**
- Analogous UWP App Project loads MUXC Navigation View Page without throwing exception. 
- No exception thrown prior to Microsoft.UI.Xaml 2.2.190830001 update.

**Comment by jevansaks** [comment] 2019-09-09 18:02
Dupe of #230 which has workaround instructions. It's an issue with the unit test project.

**Closed** 2019-09-09 18:02 UTC
Labels: duplicate

**Comment by FrancoisM** [comment] 2019-10-01 06:31
I have the same error in a [regular project](https://github.com/FrancoisM/ReproTreeView) (not unit test). I used that project to repro a [bug](https://github.com/microsoft/microsoft-ui-xaml/issues/809) which was supposed to be solved with WinUI2.2. But after upgrading from 2.1 I had the issue explained above.

**Comment by crutkas** [comment] 2020-03-11 07:01
I'm getting same issue on a brand new app.  Something isn't fixed here

**Comment by ranjeshj** [comment] 2020-03-11 13:05
@FrancoisM You need to add XamlControlsResources to your app.xaml file. See details [here](https://docs.microsoft.com/en-us/uwp/toolkits/winui/getting-started). 

@crutkas Can you check your App.xaml as well ?

**Comment by crutkas** [comment] 2020-03-11 18:48
Yup, that is, this really needs to be a better runtime check.  Super easy to miss.

**Comment by crutkas** [comment] 2020-03-11 18:48
The bug that this was dup'ed against also doesn't have a clear "this is how you fix it" too.

**Comment by ranjeshj** [comment] 2020-03-11 19:10
When you add the nuget package, it currently shows a readme with exactly the steps needed to avoid this. One thing to note that this will be a non-issue in WinUI3 where you will not have to do this extra step.
