### ISSUE TITLE
TextBlock.ActualWidth is sometimes incorrect - doesn't match ActualSize.X

### ISSUE THREAD

**Issue by benstevens48** [microsoft/microsoft-ui-xaml#1669] opened 2019-11-24 13:58 UTC
**Describe the bug**
I was just writing some code using the Composition API to create a shadow on a TextBlock. At some point the size of the shadow visual needs to be set to the size of the TextBlock. Therefore I am listening to the SizeChanged event for the TextBlock and updating the size of the shadow as necessary using TextBlock.ActualWidth (and height). However, the shadow was occasionally the wrong size as I resized the window. Eventually I discovered that TextBlock.ActualWidth was wrong. The NewSize.Width argument of the SizeChanged event reported something like 407, as did TextBlock.ActualSize.X, as did the ActualWidth for the parent element of the TextBlock (which was set so that it sized to its content), but TextBlock.ActualWidth reported 345. This wasn't a timing issue since I added a Task.Delay to inspect the value again and got the same result. It's possible this is intentional, but if it is then it's very unhelpful...

**Steps to reproduce the bug**
See the description - I don't have time to create a repro sample right now.

**Expected behavior**
TextBlock.ActualWidth should be the same as TextBlock.ActualSize.X

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            |   Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |    Yes   |

**Comment by shaheedmalik** [comment] 2019-11-24 17:33
That seems like a bug.

**Comment by codendone** [comment] 2020-01-30 22:06
The ActualWidth behavior is indeed intentional.  TextBlock and RichTextBlock override the default ActualWidth/ActualHeight property values to return the actual size of the text, rather than the full size the element was given by its parent layout panel, because some code wants to know just the actual text size.

I agree it is confusing to have these properties return a different value from what SizeChanged and ActualSize expose, though, and one could easily debate whether TextBlock overriding these properties was the right way to communicate the actual text size.  There have been other requests about improving the ability to measure text size, so we could potentially roll exposing the final actual text size in as part of a bigger text measurement feature.

**Comment by klara-zielinska** [comment] 2022-08-15 12:06
> The ActualWidth behavior is indeed intentional. TextBlock and RichTextBlock override the default ActualWidth/ActualHeight property values to return the actual size of the text, rather than the full size the element was given by its parent layout panel, because some code wants to know just the actual text size.
> 
> I agree it is confusing to have these properties return a different value from what SizeChanged and ActualSize expose, though, and one could easily debate whether TextBlock overriding these properties was the right way to communicate the actual text size. There have been other requests about improving the ability to measure text size, so we could potentially roll exposing the final actual text size in as part of a bigger text measurement feature.

If you left users with no way to get the actual size of a TextBox element, it is not about debating. This is a purely wrong design.

**Comment by benstevens48** [comment] 2023-07-17 15:47
Has this been addressed in WinUI 3? I still strongly believe the previous 'intentional' override of the behavior should be scrapped.

**Comment by JJBrychell** [comment] 2023-08-30 03:25
While we understand the confusion, this is currently functioning by design and as such we are closing this issue.

As a possible workaround you can add a border with zero thickness around the text block. The border will then be sized at the same size as actual text block and not the text content.

If you feel that this isn't sufficient you may reopen this issue as a feature proposal. There would be two ways to approach this.

We could add a new "TextWidth" and "TextHeight" properties to return the text size and report Actual Width/Height consistently with other elements. However, this would be a significant breaking change for a number of applications and certainly could not be addressed until at lease version 2.0.

Or we could a add new Width/Height properties to TextBlock to return the actual control width/height. However, it is hard to come up with a name for these that wouldn't contribute further to the confusion.

**Closed by JJBrychell** 2023-08-30 03:25 UTC
Labels: area-TextBlocks, needs-winui-3, team-Rendering
