### ISSUE TITLE
Proposal: Placement of a TabView

### ISSUE THREAD

**Issue by QuanticStorm** [microsoft/microsoft-ui-xaml#2838] opened 2020-07-05 13:50 UTC
# Proposal: Placement of a TabView

## Summary

It could be useful to be able to choose the placement of the TabView (Top, Bottom, Left or Right)

## Rationale

* To be able to act a TabView like a TabControl in WPF, we need to be able to choose the placement of the TabView like Top, Bottom, Left or Right

## Scope

| Capability | Priority |
| :---------- | :------- |
| TabViewPlacement.Left | Must |
| TabViewPlacement.Right | Must |
| TabViewPlacement.Top | Must |
| TabViewPlacement.Bottom | Must |

## Important Notes

`public enum TabViewPlacement
{
     Top,
     Bottom,
     Left,
     Right
}`

```
public static DependencyProperty TabViewPlacementProperty {get;} = DependencyProperty.Register(
nameof(TabViewPlacement),
typeof(TabViewPlacement),
typeof(TabView),
new PropertyMetadata(TabViewPlacement.Top));

public TabViewPlacement TabViewPlacement 
{
    get => (TabViewPlacement)GetValue(TabViewPlacementProperty);
    set=>SetValue(TabViewPlacementProperty, value);
}

```

**Comment by chingucoding** [comment] 2020-07-05 13:54
Is this in the same spirit as #2194 ? How would TabViewPlacement.Left work?

**Comment by QuanticStorm** [comment] 2020-07-05 14:06
@chingucoding : You're right... I haven't seen the #2194 ... But it is the same spirit. 

The TabControl in WPF render the Left or Right placement like this :

![image](https://user-images.githubusercontent.com/6189558/86534424-a8a7bd00-bed8-11ea-9cb9-b9b5e16c4e94.png)

But a render like this :

![image](https://user-images.githubusercontent.com/6189558/86534429-b52c1580-bed8-11ea-89f4-c6bf3784035e.png)

Could be really interesting too...

For me as a visual concept, there is no difference between TabView and TabControl because they share the same subject: render elements in a Tab way.

In fact, TabViewPlacement.Left (or Right) will work in the same way the WPF TabControl does.

**Comment by chingucoding** [comment] 2020-07-05 14:10
I see. @stmoy What do you think about rotating the control? I wonder how accessible that would be.
Maybe we should have two API's, one for "just rotating" and one for placing it at the side while maintaining text orientation.

**Comment by mdtauk** [comment] 2020-07-05 16:51
> I see. @stmoy What do you think about rotating the control? I wonder how accessible that would be.
> Maybe we should have two API's, one for "just rotating" and one for placing it at the side while maintaining text orientation.

Edge is getting a vertical side placement option, so perhaps that is how it should be handled

**Comment by shaheedmalik** [comment] 2020-07-06 01:58
Can this proposal be merged with the other one? #2194

**Comment by stmoy** [comment] 2020-07-06 16:58
Thanks for filing this @QuanticStorm! This looks to be mostly a dupe of #2194 so I'm closing this issue. 

I do have a couple of quick questions (for follow up on this issue, or over on that one):
- This issue also covers Placement = Bottom. Is Bottom placement included here for completeness or necessity? (ie. are there specific scenarios that require Bottom)?
- Are you working on a specific app that could use the TabView's alternate placement modes?

**Closed by stmoy** 2020-07-06 16:58 UTC
Labels: feature proposal, needs-triage

**Comment by mdtauk** [comment] 2020-07-06 17:09
Often times Tool Palettes will use bottom placed tabs.

Not including it when you also have Top, Left and Right placements, seems a bit silly though, just looking at it.

**Comment by stmoy** [comment] 2020-07-06 17:19
> Not including it when you also have Top, Left and Right placements, seems a bit silly though, just looking at it.

Agreed. From an implementation point of view, I also think Placement = Bottom would be the easiest to implement - I mostly asking to understand if there are specific scenarios that require Bottom or if it's included for completeness.
