### ISSUE TITLE
Textbox not displaying text input.

### ISSUE THREAD

**Issue by alainreynoso** [microsoft/microsoft-ui-xaml#1849] opened 2020-01-15 18:19 UTC
Having the following issue with textboxes and not displaying text

Setup:
1) Create a Blank UWP project
2) In MainPage.xaml add two TextBox elements such as:
<Grid>
<TextBox />
<TextBox />
</Grid>

Repro:
1) Run the app
1a) Notice focus is on the first TextBox
2) Interact with a Window that is NOT the running UWP app.
3) Click into the second TextBox
3a) Notice that focus is now in the second TextBox
4) Start typing standard letters on the keyboard

**Comment by ranjeshj** [comment] 2020-01-15 20:28
@alainreynoso This works fine for me. focus goes back to the first textbox and i can see more text as I type. Can you provide a repro app/more details ?

**Comment by alainreynoso** [comment] 2020-01-15 20:53
after step 3... dont click on the first textbox... focus should be on the second textbox and then type.  do they appear?

**Comment by ranjeshj** [comment] 2020-01-15 21:20
> after step 3... dont click on the first textbox... focus should be on the second textbox and then type. do they appear?

How to do you get focus back to the tab. I can click on the app or alt-tab. In both cases focus goes back to the first text box for me.

**Comment by alainreynoso** [comment] 2020-01-15 22:21
When you run the app, use the mouse to click on the first textbox.  Focus should be on the first textbox.  Then click on another application, chrome for example and copy the url.  the url is not important but the action of interacting with another application is the key.  Then click on the second text box , not on the page (parent of the text box) but this should give focus on the second text box.  At this point, start typing letters/numbers.  The expected result is that the letters/numbers you type will appear but what happens is that even though the second text box has focus - they do not appear.

**Comment by kmgallahan** [comment] 2020-01-16 01:11
@ranjeshj
I can repro this following the above steps in the XAML Controls Gallery TextBox samples page.

**Comment by ranjeshj** [comment] 2020-01-16 01:18
I am able to repro as well. @Austin-Lamb this looks like it could be a focus/input issue.

**Comment by Austin-Lamb** [comment] 2020-01-17 15:38
I can also repro this - my suspicion is that XAML is getting focus but failing to forward the focus to the text input stack in this case.  It looks like a race condition, since it only happens sometimes in my tests.

@alainreynoso - do you see this repro 100%, or is it inconsistent?

**Comment by alainreynoso** [comment] 2020-01-17 16:23
So using the sample project and doing the steps outlined, we can always reproduce it.  But there are times in our application (not the 2 textboxes sample) where it is inconsistent.  We have noticed that if you do the following on the sample project - Focus on first Textbox , focus on a different application, then click on first textbox - that you can type ok.  Hope this helps and thanks for looking into the issue

**Comment by kmgallahan** [comment] 2020-01-17 18:29
Mild possibility that this is related to #1555. Similar application switching / multitasking scenario impact.

**Comment by Austin-Lamb** [comment] 2020-01-23 18:37
Since TextBox and XAML's interaction with the text input stack is in the core framework, unfortunately there's nothing I can see that we can do here until WinUI 3.  So tagging with needs-winui-3, and putting on the backlog for the moment.

I'm not aware of any workaround in the app, but you might be able to listen to TextBox's GotFocus and if you know the window was just activated (via CoreWindow.Activated event) you could try briefly focusing another thing then going back to the TextBox.  It's a very ugly workaround, and I'm not even sure it'd work, but you could try it?

**Comment by Trolldemorted** [comment] 2020-05-13 17:22
@Austin-Lamb is fixing this issue in the core framework out of the question? Has this issue been around forever, or was it introduced recently? This bug is affecting every UWP app out there, isn't it?

**Comment by myokeeh** [comment] 2021-07-19 22:11
Wow this bug is still present in 2.6.1. Reproduced per the steps on the original post.

**Comment by Trolldemorted** [comment] 2022-01-08 10:55
WinUI 3 is out and this issue is extremely annoying, any chance for a fix or a workaround coming soonish?

**Comment by Trolldemorted** [comment] 2023-01-10 20:19
An entire year has passed without any updates. Are there any workarounds for this problem, or is nobody who uses WinUI caring about basic things like **working textboxes**?

@Austin-Lamb can you make any estimates when this bug will make it to a milestone? I really hate to be nagging, but if textboxes just don't work sometimes, users get upset quickly.

**Comment by kmgallahan** [comment] 2023-07-29 14:12
Keep alive

**Comment by ranjeshj** [comment] 2023-11-21 00:03
This has been fixed in WinUI3.

**Closed by ranjeshj** 2023-11-21 00:03 UTC
Labels: bug, area-TextBox, needs-winui-3, team-Controls
