### ISSUE TITLE
Proposal: Play indicator animation for NavigationViewItems in PaneFooter

### ISSUE THREAD

**Issue by ad1Dima** [microsoft/microsoft-ui-xaml#1458] opened 2019-10-17 13:36 UTC
# Proposal: Play indicator animation for NavigationViewItems in PaneFooter
When you add some NavigationViewItems in PaneFooter (Account for ex.) and you have reach page for this item, you expect it to be selected like any other item (settings for example)
![Account](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/images/navview-freeform-footer-left.png)

This will allow developers to add several menu items binded to the bottom

**UPD** Or even better, Add BottomMenuItems, so not only settings button can be pinned to bottom, but a few other

**Comment by jevansaks** [comment] 2019-10-21 17:21
Sounds like duplicate of #375.

**Closed by jevansaks** 2019-10-21 17:21 UTC
Labels: feature proposal
