### ISSUE TITLE
Unable to resize application from top edge when using `App.MainWindow.AppWindow.TitleBar.ExtendsContentIntoTitleBar = true`

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#8613] opened 2023-06-25 09:23 UTC
### Describe the bug

The issue emerges when we use `App.MainWindow.AppWindow.TitleBar.ExtendsContentIntoTitleBar = true; ` instead of `App.MainWindow.ExtendsContentIntoTitleBar = true; ` to extend the content into the title bar. 

However, using the latter option doesn't allow interaction elements in the titlebar, such as a button or a text box in the titlebar. @pratikone 

### Steps to reproduce the bug

1. Extend the content using `App.MainWindow.AppWindow.TitleBar.ExtendsContentIntoTitleBar = true; `
2. Try to resize the application using the top edge of the application window
3. The application is not resized, however, the application is moved. 

### Expected behavior

The application should be resized

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

### IDE

Visual Studio 2022

**Comment by bpulliam** [comment] 2023-07-06 21:24
Duplicate of #8414

**Closed by bpulliam** 2023-07-06 21:24 UTC
Labels: duplicate
