### ISSUE TITLE
Frame.Navigate throws when clicking unselected item in GridView

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#6350] opened 2021-11-19 06:00 UTC
### Describe the bug

If a frame navigation is triggered by clicking a button in unselected item in GridView, it will throw with 'Child collection must not be modified during measure or arrange'.

This is a regression from 1.0.0-preview3

### Steps to reproduce the bug

1. Create a page, with GridView inside it
2. In GridView items, put a button that triggers navigation to another page
3. When clicking the button without selecting the item first, Frame.Navigate throws
4. If select the item first then click the button inside it, it will not throw

### Expected behavior

Navigate successfully without exception.

### NuGet package version

WinUI 3 - Windows App SDK 1.0.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Minimal repro:
[GridViewNavigationRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7568084/GridViewNavigationRepro.zip)
 
Changing WindowsAppSDK to 1.0.0-preview3 and the problem disappears.

**Comment by dynsim** [comment] 2021-12-06 07:30
I experience the same issue. Did you find any workaround for this (apart from changing to 1.0.0-preview3)?

**Comment by MikeHillberg** [comment] 2021-12-06 23:43
Thanks for the repro. We've done some debugging and the issue is that the button on the page that's being navigating away from has captured the pointer (normal for pointer press on a button), then that capture is being canceled as part of navigating away, which is triggering an attempt to modify a tree that's in the process of being torn down.

As a workaround for now you can release the button's capture:

```cs
private void Button_Click(object sender, RoutedEventArgs e)
{
    (sender as Button).ReleasePointerCaptures();
    Messenger.Navigate();
}
```

**Comment by huoyaoyuan** [comment] 2021-12-08 09:05
Thank you for the workaround. Hopefully you can fix it soon.

**Comment by StephenLPeters** [comment] 2022-02-16 21:48
@JJBrychell FYI

**Comment by huoyaoyuan** [comment] 2022-04-07 08:18
The issue is not fixed in 1.0.1 or 1.1.0-preview.

**Comment by SteezCram** [comment] 2022-08-07 13:01
I have also the same problem in version 1.1.3.

**Comment by Scottj1s** [comment] 2022-08-29 18:14
@ranjeshj can the controls team look at a global fix for this, instead of the workaround?

**Comment by SamChaps** [comment] 2022-09-21 22:33
This can be repro'd on WinUI 2.

**Comment by mickaelfrancois** [comment] 2023-01-23 19:10
Do you have a date for a fix?
It is not possible to require users to first select a grid item before clicking on it.

Also, as I use a template for my grid, I haven't found a way to apply the workaround with the button clickl.

**Comment by huoyaoyuan** [comment] 2023-08-04 04:05
The bug is still present in WinAppSDK 1.3 and latest preview 1.4.230628000-preview1. Please reopen this.

**Comment by mattleibow** [comment] 2023-10-17 22:05
@evelynwu-msft could we add a maui label to this?

**Comment by Gueztt** [comment] 2023-11-26 12:43
> @evelynwu-msft could we add a maui label to this?


I am facing this issue with WinUI3 App also.

**Comment by hjohnson12** [comment] 2023-12-05 23:22
I can confirm I'm receiving the same error in a UWP application, WinUI v2.8.5. 

Having a command bound to my Button while the click event was doing this seemed to work for now (didn't need Messenger.Navigate() there though in my case, the command handles navigation):

> ```cs
> private void Button_Click(object sender, RoutedEventArgs e)
> {
>     (sender as Button).ReleasePointerCaptures();
>     Messenger.Navigate();
> }
> ```

**Closed** 2024-01-25 08:34 UTC
Labels: bug, area-Commanding, area-Navigation, team-Rendering, product-winui3, area-Pointer, closed-Fixed, MAUI-request ???

**Comment by huoyaoyuan** [comment] 2024-01-25 08:45
@llongley can you provide which version will include this fix? Thanks!

**Comment by codendone** [comment] 2024-01-26 06:20
@huoyaoyuan The fix will be in WinAppSDK 1.5. It did **not** make it into the 1.5-experimental2 release today.

**Comment by petervcim** [comment] 2024-06-30 10:31
`SelectionMode ="None"`
This works Fine!
I mean, for that scenario, you just want the item to stay unselected. Logically, this ain't a bug to fix.

**Comment by AgentSmith-Dev** [comment] 2024-10-31 17:03
I can still see the bug on a XamlIslands project with C++.
Microsoft.UI.Xaml 2.8.2.prerelease-220830001

The workaround from above works:

```
    if (!(sender.try_as<winrt::Windows::UI::Xaml::Controls::Button>(xBtnEdit))) {
    }
    else {
        //  \see    https://github.com/microsoft/microsoft-ui-xaml/issues/6350
        xBtnEdit.ReleasePointerCaptures();

```
