### ISSUE TITLE
NavigationView PaneDisplayMode="Top" throws exception "The parameter is incorrect" container

### ISSUE THREAD

**Issue by Going-Gone** [microsoft/microsoft-ui-xaml#767] opened 2019-05-29 13:59 UTC
**Describe the bug**
Currently have a menu system that consists of a Top level, and sub level. Navigation works fine in PaneDisplayMode="Left", but when using "Top", an error "The parameter is incorrect, container"  is thrown when selecting a sub level menu item in various scenarios explained below. 
It does not fire the ItemInvoked, or SelectionChanged event before the error is thrown. 

**Top level nav view**
```

<my:BaseControl
    x:Class=""
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:Controls="using:Microsoft.Toolkit.Uwp.UI.Controls"
    xmlns:UnderConstructionPage="using:LD75ClaimSystem.UI.View.Claimant"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local=""
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:models=""
    xmlns:my=""
    xmlns:vmc=""
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    Name="TopMenu"
    mc:Ignorable="d">

    <Grid>
        <Border BorderBrush="#477DAC" BorderThickness="1,1,1,1">
            <winui:NavigationView
                Name="NavTopLevel"
                AlwaysShowHeader="False"
                Background="AliceBlue"
                IsBackButtonVisible="Collapsed"
                IsBackEnabled="False"
                IsSettingsVisible="False"
                IsTabStop="False"
                ItemInvoked="NavTopLevel_ItemInvoked"
                Loaded="NavTopLevel_Loaded"
                PaneDisplayMode="Top"
                SelectionChanged="NavTopLevel_SelectionChanged"
                Tapped="NavTopLevel_Tapped">
                <winui:NavigationView.MenuItemTemplate>
                    <DataTemplate x:DataType="models:MenuItem">
                        <TextBlock Text="{x:Bind HeaderTitle, Mode=OneWay}" />
                    </DataTemplate>
                </winui:NavigationView.MenuItemTemplate>
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="auto" />
                        <RowDefinition Height="*" />
                    </Grid.RowDefinitions>
                    <Frame x:Name="badgeFrame" Grid.Row="0" />
                    <Frame x:Name="contentFrame" Grid.Row="1" />
                </Grid>
            </winui:NavigationView>
        </Border>
    </Grid>
</my:BaseControl>

```
**Sub level nav view**
```
<my:BaseControl
    x:Class=""
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local=""
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:models="l"
    xmlns:my=""
    xmlns:vm=""
    xmlns:vmc=""
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">

    <Control.Resources>
        <vmc:NullableIntToIntConverter x:Key="NullableIntToIntConverter" />
    </Control.Resources>
    <Grid>
        <Border BorderBrush="#477DAC" BorderThickness="1,1,1,1"> 
        <winui:NavigationView
            Name="NavSubLevel"
            IsTabStop="False"
            Background="#FFFFFF"
            IsBackButtonVisible="Collapsed"
            IsBackEnabled="False"
            IsSettingsVisible="False"
            ItemInvoked="NavTopLevel_ItemInvoked"
            Loaded="NavTopLevel_Loaded"
            PaneDisplayMode="Top"
            SelectionChanged="NavTopLevel_SelectionChanged">
            <winui:NavigationView.MenuItemTemplate>
                <DataTemplate x:DataType="models:MenuItem">
                    <TextBlock Text="{x:Bind HeaderTitle, Mode=OneWay}" />
                </DataTemplate>
            </winui:NavigationView.MenuItemTemplate>
            <Grid>
                <Frame x:Name="contentFrame"/>
            </Grid>
        </winui:NavigationView>
        </Border>
    </Grid>
</my:BaseControl>
```

**Steps to reproduce the bug**
1. Select a top level menu item, and sub level menu loads.
2. Select a sub level menu item, and page loads.
3. Select a different top level menu item, and different sub level menu items load.
4. Select initial top level menu item, and initial sub menu loads.
5. Prior sub level menu item page is loaded, but menu item is not selected. 
6. Select any sub level menu item, and error is thrown.

**Expected behavior**
In PaneDisplayMode="Left" I am able to select top level menu items, and sub level menu items in the same steps without the error being thrown. Only see the error in "Top" mode.

**Screenshots**
**Initial selection**
![loaded page sub level](https://user-images.githubusercontent.com/28640954/58561714-58e2c680-81ed-11e9-9eb7-afecac31234c.PNG)
**Next menu item**
![next menu over navigate](https://user-images.githubusercontent.com/28640954/58562227-72384280-81ee-11e9-8da4-05d1ca2a47e1.PNG)
**Back to initial selection**
![navigate back to claimant, navigation selected item animation gone](https://user-images.githubusercontent.com/28640954/58562269-88460300-81ee-11e9-9bc2-6d54d36afb51.PNG)
**Error thrown when selecting any sub menu item after navigating back**
![selecting sub level menu](https://user-images.githubusercontent.com/28640954/58562379-be838280-81ee-11e9-83d7-9fd16b01ed20.PNG)

**Version Info**

NuGet package version: 
 Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | yes target version  |
| April 2018 Update (17134)          | yes, minimum version  |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
Current version of windows is 17134. Target version 17763, minimum 17134.
 Again, this does not occur with PaneDisplayMode="Left"
Similar issue, but different steps to throw error.https://stackoverflow.com/questions/54196402/selecting-item-in-navigationview-overflow-list-programatically
After the error occurs, I am still able to select a menu item successfully.

**Comment by mrlacey** [comment] 2019-05-29 14:06
Do you have nested NavigationView controls? I don't believe that's supported.
If not, can you share a repro project or the XAML used to recreate this?  Showing obscured screenshots and reproduction steps that assume a specific app make investigating this much harder.

**Comment by Going-Gone** [comment] 2019-05-29 14:14
**Top level nav view**
```

<my:BaseControl
    x:Class=""
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:Controls="using:Microsoft.Toolkit.Uwp.UI.Controls"
    xmlns:UnderConstructionPage="using:LD75ClaimSystem.UI.View.Claimant"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local=""
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:models=""
    xmlns:my=""
    xmlns:vmc=""
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    Name="TopMenu"
    mc:Ignorable="d">

    <Grid>
        <Border BorderBrush="#477DAC" BorderThickness="1,1,1,1">
            <winui:NavigationView
                Name="NavTopLevel"
                AlwaysShowHeader="False"
                Background="AliceBlue"
                IsBackButtonVisible="Collapsed"
                IsBackEnabled="False"
                IsSettingsVisible="False"
                IsTabStop="False"
                ItemInvoked="NavTopLevel_ItemInvoked"
                Loaded="NavTopLevel_Loaded"
                PaneDisplayMode="Top"
                SelectionChanged="NavTopLevel_SelectionChanged"
                Tapped="NavTopLevel_Tapped">
                <winui:NavigationView.MenuItemTemplate>
                    <DataTemplate x:DataType="models:MenuItem">
                        <TextBlock Text="{x:Bind HeaderTitle, Mode=OneWay}" />
                    </DataTemplate>
                </winui:NavigationView.MenuItemTemplate>
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="auto" />
                        <RowDefinition Height="*" />
                    </Grid.RowDefinitions>
                    <Frame x:Name="badgeFrame" Grid.Row="0" />
                    <Frame x:Name="contentFrame" Grid.Row="1" />
                </Grid>
            </winui:NavigationView>
        </Border>
    </Grid>
</my:BaseControl>

```
**Sub level nav view**
```
<my:BaseControl
    x:Class=""
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local=""
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:models="l"
    xmlns:my=""
    xmlns:vm=""
    xmlns:vmc=""
    xmlns:winui="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">

    <Control.Resources>
        <vmc:NullableIntToIntConverter x:Key="NullableIntToIntConverter" />
    </Control.Resources>
    <Grid>
        <Border BorderBrush="#477DAC" BorderThickness="1,1,1,1"> 
        <winui:NavigationView
            Name="NavSubLevel"
            IsTabStop="False"
            Background="#FFFFFF"
            IsBackButtonVisible="Collapsed"
            IsBackEnabled="False"
            IsSettingsVisible="False"
            ItemInvoked="NavTopLevel_ItemInvoked"
            Loaded="NavTopLevel_Loaded"
            PaneDisplayMode="Top"
            SelectionChanged="NavTopLevel_SelectionChanged">
            <winui:NavigationView.MenuItemTemplate>
                <DataTemplate x:DataType="models:MenuItem">
                    <TextBlock Text="{x:Bind HeaderTitle, Mode=OneWay}" />
                </DataTemplate>
            </winui:NavigationView.MenuItemTemplate>
            <Grid>
                <Frame x:Name="contentFrame"/>
            </Grid>
        </winui:NavigationView>
        </Border>
    </Grid>
</my:BaseControl>
```

**Comment by Going-Gone** [comment] 2019-05-29 14:17
> Do you have nested NavigationView controls? I don't believe that's supported.
> If not, can you share a repro project or the XAML used to recreate this? Showing obscured screenshots and reproduction steps that assume a specific app make investigating this much harder.

Sorry about obfuscating stuff, but I'm doing my best to give you everything I can. Any other things that can help, just let me know.

**Comment by mrlacey** [comment] 2019-05-29 14:37
So, **Yes**, you're nesting `NavigationView` controls.
I don't believe that's an officially supported scenario as the control is meant to provide top-level navigation within an app.

I think that because it's meant for top-level navigation only the no nesting support is only implied or tested for and not called out explicitly.

It'd be good to get official confirmation of this and something appropriate added to the docs too.

**Comment by Going-Gone** [comment] 2019-05-29 15:12
> So, **Yes**, you're nesting `NavigationView` controls.
> I don't believe that's an officially supported scenario as the control is meant to provide top-level navigation within an app.
> 
> I think that because it's meant for top-level navigation only the no nesting support is only implied or tested for and not called out explicitly.
> 
> It'd be good to get official confirmation of this and something appropriate added to the docs too.

It works perfectly fine in PaneDisplayMode="Left" though. Only when it's in "Top"

**Comment by Going-Gone** [comment] 2019-05-29 15:31
I was storing pages in a collection for sublevel use, and that seems to have effect on this error occuring. When i grab a new instance of the sub menu, no error occurs. It looks like it's a logic issue on my end. 

How i set my frame on the top level. 
```
//contentFrame.Content = new SubMenus() { ParentClaimant = this.ParentClaimant, ParentMenuID = ItemContent.MenuID };
//contentFrame.Content = SubMenuInstance.Where(aa => aa.ParentMenuID == ItemContent.MenuID).FirstOrDefault();
```

Line 2 brings the error, using line 1 works fine.

**Comment by YuliKl** [comment] 2019-05-29 21:55
> I don't believe that's an officially supported scenario as the control is meant to provide top-level navigation within an app.

@mrlacey, you're absolutely correct.

@Going-Gone, your last comment suggests that you've found a workaround for this error. Is that right? If this is no longer blocking, can you close this issue?

I would also love to get your thoughts and up-votes on #79. I suspect, but would like confirmation, that hierarchy in a single NavigationView would eliminate the need for nesting multiple NavigationViews.

**Comment by Going-Gone** [comment] 2019-05-30 12:57
> > I don't believe that's an officially supported scenario as the control is meant to provide top-level navigation within an app.
> 
> @mrlacey, you're absolutely correct.
> 
> @Going-Gone, your last comment suggests that you've found a workaround for this error. Is that right? If this is no longer blocking, can you close this issue?
> 
> I would also love to get your thoughts and up-votes on #79. I suspect, but would like confirmation, that hierarchy in a single NavigationView would eliminate the need for nesting multiple NavigationViews.

I'm curious to what is happening though, since this only happens in PaneDisplayMode="Top". If i switch to left, it goes doesn't show up.

**Closed** 2019-05-30 19:29 UTC
Labels: area-NavigationView, needs: follow-up

**Comment by hjohnson12** [comment] 2019-08-18 13:39
> > > I don't believe that's an officially supported scenario as the control is meant to provide top-level navigation within an app.
> > 
> > 
> > @mrlacey, you're absolutely correct.
> > @Going-Gone, your last comment suggests that you've found a workaround for this error. Is that right? If this is no longer blocking, can you close this issue?
> > I would also love to get your thoughts and up-votes on #79. I suspect, but would like confirmation, that hierarchy in a single NavigationView would eliminate the need for nesting multiple NavigationViews.
> 
> I'm curious to what is happening though, since this only happens in PaneDisplayMode="Top". If i switch to left, it doesn't show up.

Did you ever find a solution? I'm actually running into this same issue with my Kanban Board application. Tried a workaround with MenuItems, and it was working up until I needed to update an item; sometimes it'd crash randomly with wrong index, though everything was as it should be. Wanting to check in about this!

**Comment by Going-Gone** [comment] 2019-10-23 14:05
> > > > I don't believe that's an officially supported scenario as the control is meant to provide top-level navigation within an app.
> > > 
> > > 
> > > @mrlacey, you're absolutely correct.
> > > @Going-Gone, your last comment suggests that you've found a workaround for this error. Is that right? If this is no longer blocking, can you close this issue?
> > > I would also love to get your thoughts and up-votes on #79. I suspect, but would like confirmation, that hierarchy in a single NavigationView would eliminate the need for nesting multiple NavigationViews.
> > 
> > 
> > I'm curious to what is happening though, since this only happens in PaneDisplayMode="Top". If i switch to left, it doesn't show up.
> 
> Did you ever find a solution? I'm actually running into this same issue with my Kanban Board application. Tried a workaround with MenuItems, and it was working up until I needed to update an item; sometimes it'd crash randomly with wrong index, though everything was as it should be. Wanting to check in about this!

I have not found a solution yet sadly. Nested navigation would be a great feature for the NavigationView.
