### ISSUE TITLE
WebView2: HTML Option element is broken

### ISSUE THREAD

**Issue by cdhawan** [microsoft/microsoft-ui-xaml#3230] opened 2020-09-02 04:51 UTC
**Describe the bug**
HTML Option element is doesn't work in WebView2. The list doesn't opens.

**Steps to reproduce the bug**
1. Create a UWP app with WebView2
2. Set WebView2 source uri to "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist"
3. Launch the app
4. Try to expand the list from right pane.

**Expected behavior**
The list should expand for the selection. But the list doesn't expand.

**Screenshots**
None

**Version Info**
WinUI 3.0 with WebView2 Preview 2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | < N/A   |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  Don't know |
| Surface Hub        | Don't know |
| IoT                | Don't know |

**Additional context**
None

**Comment by DmitriyKomin** [comment] 2020-09-10 17:33
Thanks for reporting this! This is a class issue affecting webpage-originated popup UI that's rendered via separate HWNDs, which are not owned by the Anaheim Browser HWND (as is the case for browser-originated popups like context menu) Xaml WV2 isn't being informed of these currently and they're not rolled into the page content  rendering so they currently don't show up.

This issue was recently also identified by the Anaheim/CoreWebView2 owner team and is now being investigated by our teams together. A fix will definitely require work in Anaheim/CoreWebView2, and possibly some work on WinUI3 as well.. I'll follow up here with an update when the investigation is finished.

So far, I've hit one other case of this (in addition to <option>): <input type=”date”…>@cdhawan do you know of any others?

**Comment by adambarlow** [comment] 2020-10-07 18:12
I spoke with @cdhawan and he isn't aware of any others. Do we know what would be needed in Edge to support this?

**Comment by anawishnoff** [comment] 2021-01-29 15:19
This was fixed in WinUI 3 Preview 3, so I'm going to go ahead and close this issue. Feel free to re-open and let us know if the issue still persists.

**Closed by anawishnoff** 2021-01-29 15:19 UTC
Labels: area-WebView, team-Rendering, winui3preview

**Comment by cdhawan** [comment] 2021-06-21 04:56
We are still able to repro in Preview 4.

**Comment by DmitriyKomin** [comment] 2021-08-14 03:10
This was an Edge bug, fixed in October ’20. At this point, updating to latest WebView2Runtime (https://aka.ms/winui3/webview2download/) should resolve the issue. I confirmed this locally just now (in a UWP sample) as well. (Note I am using newer WinUI3 bits and can't  vouch for Preview 4).

**Comment by ispysoftware** [comment] 2021-11-08 03:12
This is not fixed.

**Comment by krschau** [comment] 2022-03-02 20:17
I think there were two issues contributing to this. As said above, one was fixed in Edge, the other is #5570. I'm going to keep this closed as a dupe of that one.
