### ISSUE TITLE
ColorSpectrum thumb moves slowly

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#4053] opened 2021-01-29 06:08 UTC
**Describe the bug**

ColorSpectrum thumb moves slowly when I write a code on the `ColorChanged` event.

Code,

_XAML_

**\<ColorSpectrum ColorChanged="ColorSpectrum_ColorChanged"/>**

_CSharp_

**private void ColorSpectrum_ColorChanged(ColorSpectrum sender, ColorChangedEventArgs args)
{
             Debug.WriteLine("It takes time to move");
}**

**Steps to reproduce the bug**

1. Run the sample using the above code
2. Press the thumb on the color spectrum and move fast 
3. Now, you can see the thumb moves slowly on the color spectrum

**Expected behavior**

The thumb needs to be moved fastly on the color spectrum.

**Screenshots**

NA

**Version Info**

NuGet package version: [Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by ssaran046** [comment] 2021-02-01 09:10
Hi Team,

Any update on this issue?

**Comment by StephenLPeters** [comment] 2021-02-02 00:22
@ssaran046 do you know if this is unique to winui3 or if it is present in winui2 as well?

**Comment by ssaran046** [comment] 2021-02-02 07:26
@StephenLPeters Not sure about winui 2

**Comment by StephenLPeters** [comment] 2021-02-04 00:20
Does this also happen when you attach to the colorpicker's ColorChanged() event? ColorSpectrum is a primitive, its not really designed to be used by itself.

**Comment by ssaran046** [comment] 2021-02-04 06:00
@StephenLPeters This issue reproduced in ColorPicker control too.

**Comment by robloo** [comment] 2021-02-04 22:18
This is a duplicate https://github.com/microsoft/microsoft-ui-xaml/issues/2683
It also exists in WinUI 2

**Comment by StephenLPeters** [comment] 2021-02-06 00:27
Thanks rob, I agree, although the work around is unfortunate...

**Comment by robloo** [comment] 2021-02-06 04:50
@StephenLPeters The control takes the pointer or touch position on the spectrum and looks up the corresponding color in a 2D array and then raises the changed event. This means as the pointer moves its raising an event and internally reprocessing at each pixel. As the selected color on the spectrum needs to be pixel-perfect accurate, this is all unavoidable. The only solution to this is to implement some consideration of time.

**Comment by krschau** [comment] 2022-06-22 18:24
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/2683

**Closed by krschau** 2022-06-22 18:24 UTC
Labels: duplicate, area-ColorPicker, team-Controls, area-Performance
