### ISSUE TITLE
[uwp] crash XamlParseException: The text associated with this error code could not be found.

### ISSUE THREAD

**Issue by jtorjo** [microsoft/microsoft-ui-xaml#3219] opened 2020-08-31 14:15 UTC
Basically, this happens to about 5% of my users, and I simply don't understand why. This happens EXACTLY at startup, roughly 5-20 seconds in.

```
App crash: Windows.UI.Xaml.Markup.XamlParseException: The text associated with this error code could not be found.

Cannot create instance of type 'select_media.compact.preview_video_media_ctrl' [Line: 0 Position: 0]
   at Windows.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at select_media.compact.compact_browse_media_ctrl..ctor()
   at edit_ui.main.main_ui_ctrl..ctor(startup_info create_info)
   at edit_ui.main.main_ui_window.Main_ui_window_OnLoaded(Object sender, RoutedEventArgs e)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
   at Windows.ApplicationModel.Core.UnhandledError.Propagate()
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AppCenter.Utils.ApplicationLifecycleHelper.<.ctor>b__17_1(Object sender, UnhandledErrorDetectedEventArgs eventArgs)

```
This clearly works correctly on most machines, so I really don't know why this would happen. It might happen on slow machines, and/or related to something async. Anyone can shed any idea on this? Thanks!

**Comment by StephenLPeters** [comment] 2020-08-31 23:16
@jtorjo unfortunately we are going to need more info to get to the bottom of this. Is there anyway that you can provide a repro for us to debug or maybe a crash dump?

**Comment by jtorjo** [comment] 2020-09-01 03:54
@StephenLPeters Well, this is quite sad, because those customers have clearly uninstalled my app and are far gone now. Had it happened on my computer, I would have provided you with anything you want. But this is not the case.

I mean, if there's anything more I can do on my end, so that if this happens in the future, I can record more info, for sure I'll do it. Just please let me know how I can do that.

**Comment by JeanRoca** [comment] 2020-11-25 23:58
@jtorjo thanks for filing this issue. As Stephen mentioned, it is really hard for us to help here if there is no way for us to reproduce the bug or a crash dump to look into. If this happens in the future please let us know how it happens and we can investigate further.

**Comment by jtorjo** [comment] 2020-11-26 07:18
@JeanRoca I've investigated this to hell and beyond. The error itself is beyond unhelpful. Here are my findings after months of dealing this with.

This seems to have something to do with a UI-control's constructor taking too much time to initialize:
1. I used to initialize a cache in one of my classes, and that could sometimes take >1s. Moving the code inside OnLoaded fixed the issue. I fixed it around 2 months ago, and this error dissappeared since then.

2. This one was much harder to tackle - this happened in my main control. I would create some custom controls in my constructor, before `InitializeComponent`, they were member variables of my .xaml.cs class, initialized like this: `edit_properties_ctrl properties_ctrl_ = new edit_properties_ctrl();`

Once again, I moved the code in OnLoaded, and so far I haven't had this happen again. This is a very recent change, just a few days ago. But since my fix, I haven't had this issue happen again. I'll monitor another 1-2 weeks.

**Comment by jtorjo** [comment] 2020-12-02 08:35
> Once again, I moved the code in OnLoaded, and so far I haven't had this happen again. This is a very recent change, just a few days ago. But since my fix, I haven't had this issue happen again. I'll monitor another 1-2 weeks.

It did not fix the issue. This still occurs.

**Comment by stevenbrix** [comment] 2020-12-10 00:01
@jtorjo, is there anything consistent with the machines that this fails on? And I'm a bit unsure what the current problem is, it sounds like one went away, but a different one crept up?

**Comment by jtorjo** [comment] 2020-12-10 09:11
> @jtorjo, is there anything consistent with the machines that this fails on? And I'm a bit unsure what the current problem is, it sounds like one went away, but a different one crept up?

@stevenbrix I wish there was :( The only thing I did find rather consistent is that it appears on machines with 4GB or 8GB of RAM.

Also, I create the control programmatically, not from XML. And the only thing that would be a bit out of the ordinary is that it contains a `MediaPlayerElement`, which I assume may take a bit longer to initialize.

That's all I can think of.

Note that this happens during startup, when showing the UI. I have a huge control (`main_ui_ctrl`), that is also loaded programmatically, and is stretched horizontally and vertically to take all space of `Main_ui_window`.

On `main_ui_ctrl`'s `Loaded` event, I have another 8 controls I create programmatically. The control that fails is one of these controls, and basically stops my app in its tracks - I can't even start up.

**Comment by stevenbrix** [comment] 2021-01-06 23:19
@jtorjo, do you know if once a machine is in this state, does it always fail, or is it random?

@alwu-msft, does this look like the activation issue that carl russel is tracking?

**Comment by jtorjo** [comment] 2021-01-08 16:13
@stevenbrix @alwu-msft I can say I'm pretty sure that once a machine is in this state, it will always fail. I've never seen a machine to fail a few times and then work

Having said that, my current hypothesis is that this may be related to Windows Media Player being in a corrupt state. I have searched the internet, and it can happen, and my take is that most people won't even notice it because most other media players will use custom libraries and thus work.

My assumption is that if Windows Media Player is somehow corrupt, MediaPlayerElement will throw some error and the error will be caught during XAML parsing, eaten, and another error gets thrown.

1. Is this a viable possibility?
2. Could this happen on some trimmed down versions of Windows? Is it possible that Windows doesn't come with Media Player components preinstalled (maybe some Windows server versions)?

**Comment by alwu-msft** [comment] 2021-01-08 19:29
@jtorjo 
1. Yes, that is pretty likely. If you have a crash dump that you can share, we can check it for any inner exceptions that were masked.
2. My understanding is that the N editions don't include Windows Media Player (users need to download and install it separately) so you might be onto something. @Austin-Lamb do you know how MediaPlayerElement interacts with a Windows 10 N install that doesn't have the "media feature pack" installed?

**Comment by jtorjo** [comment] 2021-01-10 10:26
@alwu-msft 
1. I would happily provide one, but I don't really have any. No one is willing to give me one.
2. If you can provide me with a link to a windows 10 N ISO, I can try this myself on a virtual machine. Thanks!

**Comment by alwu-msft** [comment] 2021-01-11 21:05
Based on this [list](https://visualstudio.microsoft.com/vs/benefits/#software-and-downloads?cat=visual-studio-enterprise-subscription-with-github-enterprise) it looks like it's available as part of a Visual Studio Professional or Enterprise subscription. I don't know offhand of any non-subscription method of acquiring an ISO, but I'm also not an area expert.

**Comment by jtorjo** [comment] 2021-01-17 16:53
Thanks! Unfortunately I do not have a subscription. I will have to find another way.

**Comment by DmitriyKomin** [comment] 2023-10-19 22:39
Closing as there does not seem to be an actionable problem to fix.

**Closed** 2023-10-19 22:40 UTC
Labels: bug, area-MediaPlayerElement, team-Markup, product-winui2

**Comment by SeakyLuo** [comment] 2023-11-04 06:10
Getting the same crash here.
