### ISSUE TITLE
The XamlControlsResources break the reveal effect for context menu flyouts

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#559] opened 2019-04-14 16:05 UTC
**Describe the bug**

As soon as you reference the `Microsoft.UI.Xaml` library and include the required resource dictionary, the reveal highlight effect is lost on `MenuFlyout`s used in the `ContextFlyout` property of a `UIElement`. Using them in other places (eg. `Button.Flyout`) works as expected.

**Steps to reproduce the bug**

1. Create a new UWP app targeting `17763` (I'm also using `17763` as minimum)
2. Add this code to the `MainPage.xaml` file:
```xml
<Grid>
    <Button Content="BUTTON 1">
        <Button.Flyout>
            <MenuFlyout>
                <MenuFlyoutItem Text="ITEM 1"/>
                <MenuFlyoutItem Text="ITEM 2"/>
            </MenuFlyout>
        </Button.Flyout>
    </Button>

    <Button Content="BUTTON 1" Margin="120,0,0,0">
        <Button.ContextFlyout>
            <MenuFlyout>
                <MenuFlyoutItem Text="ITEM 1"/>
                <MenuFlyoutItem Text="ITEM 2"/>
            </MenuFlyout>
        </Button.ContextFlyout>
    </Button>
</Grid>
```
3. Run the app and open both the flyouts. Observe that the reveal effect is always present
4. Include the `Microsoft.UI.Xaml` package and the required resource dictionary
5. Run the app again: the reveal effect is gone from the context menu (the second `Button`)

> **NOTE:** as said before, the reveal highlight is _only_ gone when used from the `Button.ContextFlyout` property. It's still there in the `Flyout` property, or in the `ComboBox` flyout.

**Expected behavior**

The reveal highlight effect should always be visible, no matter how the menu flyout is displayed

**Screenshots**

Before: 
![image](https://user-images.githubusercontent.com/10199417/56095667-6c58fd00-5edf-11e9-981b-58d71e5bbc99.png)

After: 
![image](https://user-images.githubusercontent.com/10199417/56095663-5e0ae100-5edf-11e9-8363-8f2b5edf2c96.png)

Note how the reveal highlight effect is completely gone in the second screen.

**Version Info**

OS: Windows 10 `18362.30`
NuGet package version: 
`Microsoft.UI.Xaml 2.1.190405004`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   | Yes   |
| October 2018 Update (17763)   | Yes/No   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by jevansaks** [comment] 2019-04-16 17:24
Thanks for the report. @chrisglein can you take a look? Seems like we accidentally lost reveal.

**Comment by Sergio0694** [comment] 2019-06-11 19:17
Hey @jevansaks - sorry to bother, I just checked the changelog for the new update and didn't see anything related to this issue, and the user you pinged has never replied yet.
Just curious if there's an ETA on this 😊
Thanks!

**Comment by jevansaks** [comment] 2019-06-11 19:23
Thanks for the ping! No ETA at the moment, especially since a lot of our resources are focused on the WinUI 3.0 effort. If you want to try to debug it some, we'd certainly appreciate the help. :) Otherwise I'll also tag @kaiguo to take a look if he has time.

**Comment by Sergio0694** [comment] 2019-06-11 20:20
Hey, no worries, I can imagine you guys are super busy planning for WinUI 3.0 😄

Yeah I can look into it, my guess is just that the style that WinUI applies to the `Button` control is applying an out of date style in the template to the `FlyoutPresenter` that is used to host the `ContextFlyout`, which should instead be the same (or pretty close) to the one used to display the one from the `Flyout` property (which is instead displayed perfectly fine).
I mean, @kaiguo might very well end up being faster than me to fix this, but I hope at least this might help with the triaging/debugging part a bit.

Cheers!

**Comment by yaichenbaum** [comment] 2019-10-31 02:10
@SavoySchuler tagging you since I don't remember who it was on the Win UI call told me to tag here. Whats going on with this issue?

**Comment by kaiguo** [comment] 2019-11-02 03:40
@yaichenbaum there might be some lower level rendering issue associated with this, we probably won't be able to fix this until WinUI 3.

**Comment by kaiguo** [comment] 2019-11-09 00:44
Adding the 2 rendering bugs for tracking (MS internal links):

[Bug 23957752](https://microsoft.visualstudio.com/OS/_workitems/edit/23957752): 19H1 regression breaks MUX reveal border
[Bug 23932680](https://microsoft.visualstudio.com/OS/_workitems/edit/23932680): CornerRadius + BorderBrush with opacity breaks reveal background

**Comment by kaiguo** [comment] 2020-01-28 19:36
Moving to rendering...

**Closed** 2023-08-03 22:31 UTC
Labels: bug, area-Menus, area-Materials, needs-winui-3, team-Rendering, no-issue-activity
