### ISSUE TITLE
Why still designer view not working in WINUI reunion version 

### ISSUE THREAD

**Issue by santhoshkumarmk** [microsoft/microsoft-ui-xaml#5553] opened 2021-07-26 01:57 UTC
I installed vs2019 with WINUI 3.0 reunion version . I am not able to view the designer view in this setup please help on this

**Comment by marb2000** [comment] 2021-07-26 19:33
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4195.

**Closed by marb2000** 2021-07-26 19:33 UTC
Labels: needs-triage
