### ISSUE TITLE
WebView2 error when loading local app package file

### ISSUE THREAD

**Issue by georgsku** [microsoft/microsoft-ui-xaml#3763] opened 2020-12-04 11:15 UTC
**Describe the bug**

I cannot seem to get WebView2 to load a file from the app package. Setting the source to a file in app package results in error in console. 

**Steps to reproduce the bug**
Start a blank WinUI project.
Install necessary packages.

Add index.html to app package, containing random html code.

Add WebView2 in XAML 
WebView2 x:Name="MyWebView_3" Source="ms-appx-web:///help/index.html"/
Run app and open debug console

**Expected behavior**

Expect index.html to be located and loaded.

**Screenshots**

![image](https://user-images.githubusercontent.com/55386744/101156520-06c40200-3629-11eb-9c04-879af64c5d49.png)

**Version Info**

NuGet package version: 5.9.0

Microsoft.WinUI 3.0.0.-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment] 2020-12-05 00:20
@adambarlow Fyi

**Comment by Felix-Dev** [comment] 2020-12-30 14:47
Looks like a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/1967 (this issue has an additional error output description).

**Comment by codendone** [comment] 2021-02-03 03:48
Closing as a dup, as noted in the previous comment.

**Closed by codendone** 2021-02-03 03:48 UTC
Labels: area-WebView, needs-triage, team-Rendering, winui3preview
