### ISSUE TITLE
WinUI Design Toolkit Bug: Dark theme should have light shadows

### ISSUE THREAD

**Issue by kubaszostak** [microsoft/microsoft-ui-xaml#5591] opened 2021-07-30 09:04 UTC
## WinUI Toolkit Bug Report

---

**Name of component or part of Toolkit:**

Flyout, TeachingTip, DropDownButton, MenuFlyoutItem, ...

**Describe the bug:**

In dark theme shadows are invisible because they are also dark. The 3D effect is lost.

**Version Info:**
XAML Controls Gallery, Version: 1.2.20.0

**Additional context:**

![image](https://user-images.githubusercontent.com/4609437/127629072-674078f4-2c0a-4e61-8924-95a0625d4a22.png)

![image](https://user-images.githubusercontent.com/4609437/127629085-d1472df1-7b7a-499f-b194-0476a98d9ad7.png)

![image](https://user-images.githubusercontent.com/4609437/127629125-8de7fb7e-5b5a-4573-bfd4-5276f4754d5d.png)

![image](https://user-images.githubusercontent.com/4609437/127629138-5512bc9c-4a68-4c04-a35c-b46c149c4cbe.png)

**Comment by Poopooracoocoo** [comment] 2021-07-30 10:34
not a bug tho

@StephenLPeters look at the shadow bug above

**Comment by StephenLPeters** [comment] 2021-07-30 14:28
Thanks, I think we're making progress on this internally.

**Comment by fitojb** [comment] 2021-07-31 01:48
But then it wouldn't be a _shadow_, would it? It'd be a _glow_.

To me, this is not a bug.

**Comment by Poopooracoocoo** [comment] 2021-07-31 02:09
^
And I haven't seen other platforms do a glow. Namely iOS, macOS, Android and the various implementations of Material Design on the web. There are other ways to make it contrast better. Martin (mdtauk) opened an issue somewhere here

**Comment by alejo4000** [comment] 2021-08-04 18:38
Closing this as by design.

**Closed by alejo4000** 2021-08-04 18:38 UTC
Labels: area-DesignToolkit, team-Design
