### ISSUE TITLE
NavigationView throws exception.

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#6197] opened 2021-10-29 14:10 UTC
### Describe the bug

NavigationView throws exception  when set PaneDisplayMode in Page Loaded event handler.

### Steps to reproduce the bug

can't repro the bug in sample project. (no exception in new project).
my app is a UWP app using WinUI 2.7.0.

### Screenshots

![image](https://user-images.githubusercontent.com/12285582/139449828-c4a7386a-0d07-4f20-af8c-15fa9829b81c.png)
![image](https://user-images.githubusercontent.com/12285582/139449884-f3103fd2-604b-40bc-824c-73768a40422b.png)

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

**Comment by nickrandolph** [comment] 2021-11-02 05:21
I think this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5971

**Comment by HppZ** [comment] 2021-11-02 05:24
> I think this is a duplicate of #5971

how about this issue: https://github.com/microsoft/microsoft-ui-xaml/issues/5892

**Comment by HppZ** [comment] 2021-11-03 12:33
@karenbtlai adding for help.

**Comment by StephenLPeters** [comment] 2021-11-04 22:50
@karenbtlai is this a dupe of what you are looking into?

**Comment by HannsKanns** [comment] 2021-11-16 10:19
I rolled back to Microsoft.UI.Xaml" Version=2.6.2, and it works for me. Maybe other versions before 2.7.0 are also working, but I didn't test it. It costs me 2 days of work. Not so nice. ;-((

**Comment by karenbtlai** [comment] 2021-11-16 18:31
> @karenbtlai is this a dupe of what you are looking into?

This looks similar yes. @HppZ can you test and confirm?

**Closed** 2023-08-03 22:47 UTC
Labels: area-NavigationView, team-Controls, no-issue-activity
