### ISSUE TITLE
ItemsRepeater does not respect HorizontalAlignment.

### ISSUE THREAD

**Issue by grokys** [microsoft/microsoft-ui-xaml#3842] opened 2020-12-21 09:24 UTC
**Describe the bug**

`ItemsRepeater` does not respect the `HorizontalAlignment` property, always aligning with the `Stretch` strategy.

**Steps to reproduce the bug**

Example XAML comparing the behavior of `ItemsRepeater` and `ListView`:

```xml
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        <Border Background="Yellow" Grid.Row="0">
            <controls:ItemsRepeater ItemsSource="{Binding Items}" HorizontalAlignment="Left">
                <controls:ItemsRepeater.ItemTemplate>
                    <DataTemplate>
                        <Border Background="Blue">
                            <TextBlock Text="{Binding}"/>
                        </Border>
                    </DataTemplate>
                </controls:ItemsRepeater.ItemTemplate>
            </controls:ItemsRepeater>
        </Border>
        <ListView ItemsSource="{Binding Items}" Background="Green" Grid.Row="1" HorizontalAlignment="Left"/>
    </Grid>
```

(Note that I had to surround `ItemsRepeater` in a `Border` to get a background color because it also does not respect the `Background` property)

**Expected behavior**

The `ItemsRepeater` aligns itself correctly.

**Screenshots**

![image](https://user-images.githubusercontent.com/1775141/102760970-94685700-4376-11eb-9eb6-ade84b1d3d17.png)

**Version Info**

`master`

**Comment by michael-hawker** [comment] 2022-10-31 18:29
We've hit this as well trying to implement our `SettingsExpander` with an `ItemsRepeater` ([in this PR](https://github.com/CommunityToolkit/Labs-Windows/pull/290)) and having to go back and do a bunch of stuff with `ItemsControl` instead to work around this. 🙁

When the `ItemsRepeater` is in an `Expander` it's causing the `Expander` to enlarge when expanded because the `ItemsRepeater` is trying to take up all the available space, if we didn't have a `MaxWidth` constraint on our `Expander`, I'm not sure what would have happened. In either case, it makes a simpler implementation with `ItemsRepeater` a non-starter.

**Comment by michael-hawker** [comment] 2023-02-08 22:18
You can see that the ItemsRepeater (or StackLayout) is ignoring the child's `DesiredSize` in the inspector:

![image](https://user-images.githubusercontent.com/24302614/217658456-48101758-9026-4e2c-96d8-8466460432c6.png)

This problem occurs the same in both latest stable WinUI 2 and 3 (and the new 1.3 experimental).

Translated the repro code above to a project to share, and added the Expander case we see too:

![image](https://user-images.githubusercontent.com/24302614/217660168-30fde18f-890e-4ef9-8cba-bd81fcd7a2ce.png)

You can see how this effects the Expander usage:

![image](https://user-images.githubusercontent.com/24302614/217660260-02faf757-9f6a-4f96-bdbb-3670a2996eb2.png)

It even causes wonkiness with `StackPanel` layout when in an `Expander` (not shown in this example). (though wrapping in a `Grid` seems to mitigate...)

Repro project, just run in VS: [ItemsRepeaterAlignmentRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/10690224/ItemsRepeaterAlignmentRepro.zip)

_Code in **MainPage.xaml** in the **WinAppSDK** project._

----

Separately, I tried to switch to `UniformGridLayout` to abstract the issue to the Layout algorithm; however, whatever combination I tried caused both the UWP and WinAppSDK apps to **hang** on load (no exception in the managed debugger).

```xml
<muxc:ItemsRepeater.Layout>
  <muxc:UniformGridLayout Orientation="Vertical"/>
</muxc:ItemsRepeater.Layout>
```

Since I tried upgrading to 1.3-experimental though, I was surprised when it did not hang anymore on load, and even had the containers be properly sized:

![image](https://user-images.githubusercontent.com/24302614/217663862-256262eb-9a8a-4e1c-a8a3-b9147411a2ab.png)

However, the `ItemsRepeater` itself still didn't respect the `HorizontalAlignment` nor the child size (on the left), and therefore the issue remains (though now Expander behaves better). So at least that seems to indicate the issue is in `ItemsRepeater` itself vs. a particular `Layout` algorithm?

Will open a separate issue for the `UniformGridLayout` hang in WinUI 2, though seems resolved in latest WinAppSDK experimental, so just needs to be back-ported.

**Comment by michael-hawker** [comment] 2023-08-10 16:20
This is a well-defined issue that is still an issue.

**Closed** 2024-09-11 07:10 UTC
Labels: bug, help wanted, area-ItemsRepeater, team-Controls, wct, closed-Fixed
