### ISSUE TITLE
Build error when there is a property with an init accessor in the app

### ISSUE THREAD

**Issue by RVPE** [microsoft/microsoft-ui-xaml#3637] opened 2020-11-18 16:15 UTC
Error in XamlTypeInfo.g.cs when there is a property with an init accessor in the app

Steps to reproduce the bug
1- create a new desktop app in Visual Studio
2- add a property with an init accessor in MainWindow class. Example  :  public string String1 { get; init; }
3- build

Versions :
Visual studio : Version 16.9.0 Preview 1.0
[Microsoft.WinUI 3.0.0-preview3.201113.0]
[Microsoft.VCRTForwarders.140 1.0.7]

Windows app type:
| UWP                | Win32             |
| :--------------- | :--------------- |
|                        |    Yes                |

| Windows 10 version                  | Saw the problem?  |
| :--------------------------------- | :-------------------- |
| Insider Build (19042.630)          |          Yes                 |
 

 
| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop             |    Yes                |

**Comment by Grinch** [comment] 2021-03-05 06:14
Can confirm this is still an issue. It appears to generate a setter for the property in the `XamlTypeInfo.g.cs` class.

**Comment by jlinstrum** [comment] 2021-05-05 23:20
This is also an issue with UWP apps when using C# 9 (C# 9 isn't officially supported but you can get most of it if you change compiler settings).

**Comment by pellea** [comment] 2021-06-02 16:06
My sample is a Project Reunion 0.8 Desktop app with C# on .NET 6 preview and I have also the same issue using a `record` (which implicitly declares properties with `init`).

**Comment by artkat** [comment] 2022-08-10 14:34
What is the current status on this issue (I just ran into this issue with WindowsAppSDK 1.1.3)

**Comment by evelynwu-msft** [comment] 2023-07-10 23:53
Duplicate of #2519.

**Closed** 2023-07-10 23:53 UTC
Labels: team-Markup, product-winui3
