### ISSUE TITLE
RichEditBox crashes the app when typing fast

### ISSUE THREAD

**Issue by paulovila** [microsoft/microsoft-ui-xaml#2563] opened 2020-05-27 20:18 UTC
**Typing text relatively fast makes the app crash**
The debugger doesn't even catches the error, and a new instance of Visual Studio is proposed to start the debugging.
**Steps to reproduce the bug**
1. Start debugging the XamlControlsGallery solution
2. Click on RichTextbox control (two text boxes appear)
3. In the large one, start typing fast.

**Expected behavior**
1. not crash
2. be able to debug the exception

**Version Info**
Gallery version (found on Settings page): 
commit 99299819382f2e8cdefd59193ae17d43f4c5b060 (HEAD -> winui3alpha, origin/winui3alpha)

Windows 10 version:
- [x] November 2019 Update (18363)

**Comment by chrisglein** [comment] 2020-06-09 18:36
@paulovila We're assuming you mean RichEditBox. This bottom one, right?
![image](https://user-images.githubusercontent.com/26607885/84186167-fbf72e80-aa44-11ea-859e-0cae17adef22.png)

We've been unable to repro so far. Is there more about your configuration that might be relevant you can share? A crash dump here would be most useful.

**Comment by paulovila** [comment] 2020-06-09 19:15
Hi @chrisglein , it's very easy to reproduce, I can  send you a link to Visual Studio Live Share for you'd like to see it. 
![image](https://user-images.githubusercontent.com/888391/84189492-413f4e80-aa8d-11ea-858d-9d7b52db818c.png)
![image](https://user-images.githubusercontent.com/888391/84189878-e1957300-aa8d-11ea-8d53-39ce33bb1a37.png)

**Comment by chrisglein** [comment] 2020-06-16 18:27
Going to be hard to coordinate a live shared debugging session. A crash dump would be easiest (you should be able to save one from the Visual Studio UI), or our ability to reproduce locally. We've made a significant amount of changes between WinUI alpha and WinUI preview 1 and are continuing to not repro there. Have you tried on the latest?

**Comment by chrisglein** [comment] 2020-06-18 21:43
Looks like we have an internal repro now.
[Internal issue 1](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/25317297) [Internal issue 2](https://microsoft.visualstudio.com/DefaultCollection/OS/_workitems/edit/24878943)

**Comment by ranjeshj** [comment] 2020-07-15 17:12
@paulovila  This issue should be fixed in WinUI3 Preview2. Can you give it a try ? Thanks!

**Closed by ranjeshj** 2020-07-15 17:12 UTC
Labels: area-TextBox, team-Framework, winui3preview
