### ISSUE TITLE
FocusManager.TryMoveFocus() throws Catastrophic failure exception

### ISSUE THREAD

**Issue by bjorn-malmo** [microsoft/microsoft-ui-xaml#8292] opened 2023-03-15 14:28 UTC
### Describe the bug

Trying to move focus to next control in a textbox' KeyDown event handler on Enter key throws an unhandled Catastrophic exception.

### Steps to reproduce the bug

```
<Window
    x:Class="App2.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Vertical" HorizontalAlignment="Center" VerticalAlignment="Center" Spacing="8">
        <TextBox Text="First textbox" KeyDown="TextBox1_KeyDown"/>
        <TextBox Text="Second textbox" KeyDown="TextBox2_KeyDown"/>
    </StackPanel>
</Window>

```

```
    private void TextBox1_KeyDown(object sender, KeyRoutedEventArgs e)
    {
        // Move focus to next control on enter
        if (e.Key == Windows.System.VirtualKey.Enter)
        {
            FocusManager.TryMoveFocus(FocusNavigationDirection.Next);
            e.Handled = true;
        }
    }
```

### Expected behavior

Move focus to next control. Since it is a TryXXX method, it should never throw.

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment] 2023-03-16 16:26
Dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/5593

**Closed by gabbybilka** 2023-03-16 16:26 UTC
