### ISSUE TITLE
XAML parser not reading dependency property as expected

### ISSUE THREAD

**Issue by PetarMladenov** [microsoft/microsoft-ui-xaml#3273] opened 2020-09-10 13:09 UTC
[Definitions_WinUI_Isolation.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5201798/Definitions_WinUI_Isolation.zip)
[Definitions_WPF.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5201799/Definitions_WPF.zip)

**Describe the bug**
Difference between XAML Parser in WPF and WInUI

**Steps to reproduce the bug**
Put breakpoint in CollectionChanged in code behind.
Run the attached WinUI project.
Notice the event CollectionChanged fires, in the new Items there is a new Definition class read by the XAML parser, but its Template property is NULL. The same steps in WPF project lead to new Definition in CollectionChanged with non-NULL Template.

**Expected behavior**
Expected, in collection changed the new definition read in the XAML has all the properties set as expected, same as in WPF.

NuGet package version: 
<PackageReference Include="Microsoft.WinUI">
      <Version>3.0.0-preview2.200713.0</Version>
    </PackageReference>
-->

Windows app type:
| UWP        YES     | 

| Windows 10 version                  | Saw the problem? |
10.0.17763 build 17763

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by ranjeshj** [comment] 2020-09-10 17:17
The Index property seems to be set but not the template.

**Comment by stevenbrix** [comment] 2020-12-10 00:05
@PetarMladenov, we had some C#/WinRT issues that would prevent templates from being applied. It sounds like this could be a dupe of #3309?

**Closed** 2020-12-24 07:00 UTC
Labels: needs-author-feedback, no-recent-activity, team-Markup
