### ISSUE TITLE
NavigationViewItems created dynamically via MenuItemsSource crash under More dropdown

### ISSUE THREAD

**Issue by logikonline** [microsoft/microsoft-ui-xaml#138] opened 2018-12-28 16:03 UTC
**Describe the bug**
When creating items dynamically via a bound collection with MenuItemsSource using a MenuItemTemplate.  It will work as expected until the top menu is compressed enough to move items under the "More" dopdown menu.  When it does, expanding the menu will create the following error:

Failed to assign to property 'Windows.UI.Xaml.Controls.ContentPresenter.Content'. [Line: 6980 Position: 37]

and crash.  If done statically, they work as expected.

**Steps to reproduce the bug**
Bind the MenuItemsSource to a collection.

Use a DataTemplate

```
        <DataTemplate x:Key="NavigationItemTemplate">
            <mux:NavigationViewItem Content="{Binding linkTitle}" Icon="{Binding linkImage}" Tag="{Binding Id}"/>
        </DataTemplate>
```

**Expected behavior**
The menu shows correctly

**Version Info**

NuGet package version: 
2.1.181217001-prerelease

Windows 10 version:
- [x] October 2018 Update (17763)

Device form factor:
- [x] Desktop
- [x] Mobile

**Comment by logikonline** [comment] 2018-12-28 16:04
Not sure if this helps, but the following article appears to be the same issue https://sadev.co.za/content/my-toughest-bug-2014

**Comment by licanhua** [comment] 2019-01-02 17:13
Thank you for reporting this. It's a bug and I can reproduce it. Will let you know if we have update on this.

**Comment by logikonline** [comment] 2020-02-07 22:50
Heads up = I keep testing this on every release and pre-release and it is still crashing.
On 2.2.1908300001 - it crashes with this response:
Failed to assign to property 'Windows.UI.Xaml.Controls.ContentPresenter.Content'. [Line: 12611 Position: 49]

On 2.3.1912110002 - it crashes with this one:
Failed to assign to property 'Windows.UI.Xaml.Controls.ContentPresenter.Content'. [Line: 13237 Position: 49]

**Comment by ranjeshj** [comment] 2020-02-07 23:32
@licanhua can you provide the repro app you used ? Also, NavigationView has gone through a complete refactor, so I would be curious to see if this still repro's in latest preview pacakge.

**Comment by logikonline** [comment] 2020-02-07 23:44
I did try the latest pre-release and it is still failing.  I cannot provide my production app (although I would screenshare so you can see it) but I can provide the specific error number for that version.

**Comment by logikonline** [comment] 2020-02-07 23:51
Failed to assign to property 'Windows.UI.Xaml.Controls.ContentPresenter.Content'. [Line: 13428 Position: 49]

this is for : 2.4.0-prerelease.200203002

**Comment by logikonline** [comment] 2020-02-08 00:04
If you review the message thread, licanhua did reproduce it too.  I was delayed in testing this because of a bug with the IDE which prevented developers from compiling the apps with the new target of 1903 which this library requires.  Thus I got blocked from confirming if this was working - you can see that message thread [here ](https://developercommunity.visualstudio.com/content/problem/544057/uwp-visual-studio-2019-targetting-1903-18362.html?childToView=909720#comment-909720)

**Comment by chingucoding** [comment] 2020-08-19 23:38
@logikonline Can you share a repro project? I can't seem to repro this issue using the test app which has a test page which leverages a custom DataTemplate. Opening the overflow menu seems to work fine for me.

**Comment by licanhua** [comment] 2020-08-20 17:11
@chingucoding It's hard for you to debug it without the source code from Xaml. It's possible a bug from platform, and most likely Icon property trigged the problem. 
@ranjeshj I forwarded the email about my investigation before. 

Here is the code I used to repro the problem:
```
        <Grid.Resources>
            <local:Customers x:Key="customers"/>
            <DataTemplate x:Key="NavigationItemTemplate">
                <mux:NavigationViewItem Content="{Binding linkTitle}" Icon="{Binding linkImage}" Tag="{Binding Id}"/>
           </DataTemplate>
        </Grid.Resources>
        <mux:NavigationView MenuItemsSource="{StaticResource customers}" PaneDisplayMode="Top" MenuItemTemplate="{StaticResource NavigationItemTemplate}"></mux:NavigationView>
 
   public class Customer
    {
        public string linkTitle { get; set; }
        public IconElement linkImage { get; set; }
 
        public Customer(string title, SymbolIcon iconElement)
            {
            linkTitle = title;
            linkImage = iconElement;
            }
    }
 
    public class Customers : ObservableCollection<Customer>
    {
        public Customers()
        {
            Add(new Customer("1111111111111", new SymbolIcon(Symbol.Accept)));
            Add(new Customer("2222222222222", new SymbolIcon(Symbol.Accept)));
            Add(new Customer("1333333333333333333333", new SymbolIcon(Symbol.Accept)));
            Add(new Customer("44444444444444", new SymbolIcon(Symbol.Accept)));
        }
 
    }

```

**Comment by chingucoding** [comment] 2020-08-20 17:38
Thanks for the repro code @licanhua ! This still seems to repro, though in my case, the app just becomes totally unresponsive instead of crashing. Removing the binding from content seems to "fix" this issue. Also in the sample you posted, the binding of the Tag property is invalid as the Customer object doesn't have an Id property.

Switching out `Binding` with `x:Bind` does seem to work though, so this can be used as a workaround for now.

**Comment by ranjeshj** [comment] 2020-08-20 17:39
There have been many updates to NavigationView since 2.1 release, so it is possible that this does not repro anymore. @chingucoding could you try to see if this repros with licanhua's snippet above. Thanks!

**Comment by chingucoding** [comment] 2020-08-20 17:40
@ranjeshj The issue still repros, though with different "artifacts". Instead of throwing an exception, it seems that the app just doesn't respond anymore.

**Comment by logikonline** [comment] 2021-02-05 12:01
@licanhua @ranjeshj Everyone - this has been a crashing bug for us or unresponsive on the latest version for over 2 years.  I am trying to be patient but this is insane.  This is the only control unique to Microsoft and it is broken.  We need this functionality and I am constantly telling our clients Microsoft knows this is an issue (even high profile clients like the NFL which the Microsoft pays to be on the sideline)

I need an ETA after 2 years.

**Comment by ranjeshj** [comment] 2021-02-05 16:10
@alwu-msft can you please help investigate this issue ?

**Comment by alwu-msft** [comment] 2021-02-06 01:36
Hey @logikonline, I apologize for how long this issue has languished. Please rest assured that investigating it and determining the root cause is my current priority (and I will fight to keep it that way).

**Comment by Veldrina** [comment] 2021-02-11 17:50
This is an infinite loop in NavigationView's MeasureOverride as it's laying out the top navigation bar (specifically, moving item(s) out of the primary area and into the overflow). It's easiest to see if, after launching the app, one sets breakpoints on [`CUIElement::EnterImpl`](https://github.com/microsoft/microsoft-ui-xaml/files/5967402/enter_callstack.txt) and [`CUIElement::LeaveImpl`](https://github.com/microsoft/microsoft-ui-xaml/files/5967403/leave_callstack.txt) and then notes that the same SymbolIcon repeatedly Enters and Leaves. 

I believe that the cause of the loop lies in these lines in [FlowLayoutAlgorithm::Measure](https://github.com/microsoft/microsoft-ui-xaml/blob/dfbe38bfb2996dfaa2f09544c4e86aa69ccc906b/dev/Repeater/FlowLayoutAlgorithm.cpp#L61):
    m_elementManager.OnBeginMeasure(orientation);

    const int anchorIndex = GetAnchorIndex(availableSize, isWrapping, minItemSpacing, layoutId);
    Generate(GenerateDirection::Forward, anchorIndex, availableSize, minItemSpacing, lineSpacing, maxItemsPerLine, disableVirtualization, layoutId);

What seems to be happening is that the ElementManager::OnBeginMeasure() call is resulting in the penultimate NavigationViewItem (i.e. index 3, the right-most visible item remaining if layout were to successfully complete) being recycled; this is what causes the SymbolIcon to Leave as the container is disconnected from the tree. However, (almost) immediately after, FlowLayoutAlgorithm determines that 
index 3 is in fact visible and needs a container generated for it, so the just-recycled container is duly reconnected to a DataContext and Enters the tree. This constant discard/generate of the same container causes this portion of the tree to stay dirty and so layout never finishes. 

So why does this happen when the MenuItemTemplate's NavigationViewItem.Content/Icon properties are set by a Binding and not when they're fixed values? When a container is recycled, its DataContext is first cleared and then assigned the new appropriate value. The Bindings cause these DataContext changes to propagate down into the expanded template resulting in elements Leaving/Entering the tree, whereas without Bindings nothing exists that would cause the expanded template to notice the DataContext change. It's the reaction of the expanded template to the DataContext change that causes the constant re-dirtying of the tree.

**Comment by alwu-msft** [comment] 2021-02-11 17:53
This is an infinite loop in NavigationView's MeasureOverride as it's laying out the top navigation bar (specifically, moving item(s) out of the primary area and into the overflow). It's easiest to see if, after launching the app, one sets breakpoints on [`CUIElement::EnterImpl`](https://github.com/microsoft/microsoft-ui-xaml/files/5967426/enter_callstack.txt) and [`CUIElement::LeaveImpl`](https://github.com/microsoft/microsoft-ui-xaml/files/5967428/leave_callstack.txt) and then notes that the same SymbolIcon repeatedly Enters and Leaves. 

I believe that the cause of the loop lies in these lines in FlowLayoutAlgorithm::Measure:
    m_elementManager.OnBeginMeasure(orientation);

    const int anchorIndex = GetAnchorIndex(availableSize, isWrapping, minItemSpacing, layoutId);
    Generate(GenerateDirection::Forward, anchorIndex, availableSize, minItemSpacing, lineSpacing, maxItemsPerLine, disableVirtualization, layoutId);

What seems to be happening is that the ElementManager::OnBeginMeasure() call is resulting in the penultimate NavigationViewItem (i.e. index 3, the right-most visible item remaining if layout were to successfully complete) being recycled; this is what causes the SymbolIcon to Leave as the container is disconnected from the tree. However, (almost) immediately after, FlowLayoutAlgorithm determines that 
index 3 is in fact visible and needs a container generated for it, so the just-recycled container is duly reconnected to a DataContext and Enters the tree. This constant discard/generate of the same container causes this portion of the tree to stay dirty and so layout never finishes. 

So why does this happen when the MenuItemTemplate's NavigationViewItem.Content/Icon properties are set by a Binding and not when they're fixed values? When a container is recycled, its DataContext is first cleared and then assigned the new appropriate value. The Bindings cause these DataContext changes to propagate down into the expanded template resulting in elements Leaving/Entering the tree, whereas without Bindings nothing exists that would cause the expanded template to notice the DataContext change. It's the reaction of the expanded template to the DataContext change that causes the constant re-dirtying of the tree.

**Comment by StephenLPeters** [comment] 2021-03-05 00:27
@ojhad Can you give this a read through and let us know what you think?

**Comment by ojhad** [comment] 2021-03-16 23:09
@StephenLPeters  Based on the investigation above and what I am seeing, it looks like the removal/addition of items may be happening in `NavigationView::HandleTopNavigationMeasureOverrideOverflow`. More specifically [this part of the function](https://github.com/microsoft/microsoft-ui-xaml/blob/d20fcb84ea3cc5e21a82fd4f44547471e7259078/dev/NavigationView/NavigationView.cpp#L3418) does not look like its behaving as intended in order to avoid NavigationView determining that all the items can be re-added to the top nav. Seems like the item width state is not being saved properly for the line linked above to do its job.

**Comment by logikonline** [comment] 2021-07-21 01:42
Do we have an update on this guys?  Another 6 months have passed...

**Comment by Zuescho** [comment] 2023-07-19 21:51
UP. This issue should not be part of https://github.com/microsoft/microsoft-ui-xaml/discussions/8638.

**Closed** 2024-01-13 08:07 UTC
Labels: bug, area-NavigationView, needs-assignee-attention, team-Controls, closed-NotRepro
