### ISSUE TITLE
ItemsView produces Failed to assign to property 'Microsoft.UI.Xaml.Controls.ItemsRepeater.ItemTransitionProvider'. exception

### ISSUE THREAD

**Issue by adamfierek** [microsoft/microsoft-ui-xaml#8810] opened 2023-08-31 06:11 UTC
### Describe the bug

After try to display page with  ItemsView, XamlParsingFailed is thrown:

Failed to assign to property 'Microsoft.UI.Xaml.Controls.ItemsRepeater.ItemTransitionProvider'. 

### Steps to reproduce the bug

Place ItemsView in xaml

### Expected behavior

working control

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by ranjeshj** [comment] 2023-08-31 15:33
@adamfierek can you share a small repro project ?

**Comment by RobertK66** [comment] 2023-09-07 11:42
Run into exactly same problem. (same Windows/SDK and VS versions)
Here is a repo-branch (pls. ignore the reponame 😉 :  https://github.com/RobertK66/SettingsExpanderExample/tree/issue/sdk_8810

**Comment by nchape** [comment] 2023-09-08 09:07
Same problem here, seems to be caused when using/referencing: **CommunityToolkit.WinUI.UI.Controls**

**Comment by RobertK66** [comment] 2023-09-11 10:05
Yes, that's it.
Removing the dependency to **CommunityToolkit.WinUI.Controls.SettingsControls** from my repos solves/avoids this error.
Not sure what to do to make both controls work in one project yet.....

**Comment by RobertK66** [comment] 2023-09-11 10:49
if I want to make it work AND keep my SettingsControls, I have to manually add the 
C**ommunityToolkit.WinUI.Controls.Segmented** nuget package.
(Tested with released version 8.0.230907)

**Comment by michael-hawker** [comment] 2023-09-18 23:07
Calling out here that `CommunityToolkit.WinUI.UI.Controls` is the old package from 7.x built against WASDK 1.0
The `CommunityToolkit.WinUI.Controls.SettingsControls` is the latest 8.0 package built against WASDK 1.3.
It's weird adding another package would mystically solve this, as they're all built in the same pipeline against the same versions.

This seems like a NuGet or dll resolution issue or something when referencing an older WASDK built library against an app built with the latest (or newer) SDK?

@bpulliam FYI.

**Comment by adamfierek** [comment] 2023-09-19 04:11
I would migrate to 8.0 but there is a lack of features currently used by me comparing to 7.x.

**Comment by michael-hawker** [comment] 2023-09-20 16:16
The 7.x and 8.x packages of the Toolkit are built completely differently. I don't even think the 7,x DataGrid referenced WinUI 2.x.

The only common thread here is the Windows App SDK and the upgrade to 1.4?

**Comment by adamfierek** [comment] 2023-09-23 07:35
I think it can be closed since we know it's caused by 3rd party reference

**Comment by michael-hawker** [comment] 2023-09-26 16:43
> I think it can be closed since we know it's caused by 3rd party reference

There is nothing specific in the third-party reference causing this. It's not a problem in the third-party library. The stack itself isn't contained within the third-party reference. The fact a version of the package from 2-years ago referencing the WindowsAppSDK v1.0 should mean it's not an issue within the packages themselves. Something with ItemsView or the platforms dependency resolution is broken here. Even if it is, there's literally nothing we could change without the platform team root-causing what's happening here and saying that all packages now need to do X instead with 1.4+.

In either case, this is an issue that should remain open with the platform - there's something going on within the platform itself that is unknown when another NuGet dependency is being added (it could be beyond the scope of the just the Toolkit). It needs to be resolved and is something the platform team needs to investigate. There could be any number of other third-party libraries that are affected, there's no action for us to do right now in the Toolkit on here. Two different packages from us with completely different ways of being built and with completely different code highlight the problem _within_ ItemsView, there's nothing we can even start or go on to know to change to resolve this issue in _ItemsView_.

**Comment by RobertK66** [comment] 2023-09-29 09:09
See my new comment here: https://github.com/CommunityToolkit/Windows/issues/234#issuecomment-1740558688

**Comment by RobertK66** [comment] 2023-11-24 10:02
unchanged/still an issue in Version 1.4.3 (1.4.231115000).

**Comment by ranjeshj** [comment] 2023-12-15 03:02
Thanks @kmahone for digging into this.
This seems to be a bug with IXamlMetadataProvider implementation. 
Looks like an IXMP issue.

Here is what happens:
App references WinAppSDK 1.4
App references LibraryFoo that references WinAppSDK 1.3.

LibraryFoo uses ItemsRepeater.

 App loads xaml that includes ItemsRepeater. Xaml Parser looks up metadata for ItemsRepeater from App’s IXMP. The App does not include the definition of ItemsRepeater so it forwards it on to ‘OtherProviders’. OtherProviders references both LibraryFoo IXMP and XamlControlsMetadataProvider. It checks both. It happens to have them in alphabetical order, so it checks LibraryFoo first. Since LibraryFoo DOES know about ItemsRepeater it returns the IXMP for it. But this IXMP is for the 1.3 api surface, so it is missing stuff. When the xaml parser tries to set one of the newer apis, it fails since it does not have the metadata for that property.

If you rename LibraryFoo to ZLibraryFoo it happens to change the sort order in OtherProviders and so the scenario works.

**Comment by kmahone** [comment] 2023-12-15 18:51
We will need to fix this in the Xaml Compiler so that the generated IXMP works correctly in this scenario. It should ensure that the XamlControlsXamlMetaDataProvider is always first in the list of OtherProviders.

Until this issue is fixed, here is one way to work around the issue.

In your app's csproj file add this property to the first PropertyGroup:
```
<XamlCodeGenerationControlFlags>DoNotGenerateOtherProviders</XamlCodeGenerationControlFlags>
```

This will cause the Xaml Compiler to not populate the OtherProviders list. You now need to populate it manually. In your App's constructor, call AddOtherProvider to add each of the IXamlMetadataProviders that were previously being generated. Since you can now control the order you can make sure that XamlControlsXamlMetaDataProvider comes first:

```
    public App() 
    {
        this.InitializeComponent();
        this.AddOtherProvider(new Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider());
        this.AddOtherProvider(new AClassLibrary1.AClassLibrary1_XamlTypeInfo.XamlMetaDataProvider());
    }
```

The downside to this is you need to manually add any new IXMP implementations that your app needs if you add a new dependency to your app.

**Comment by efreykongcn** [comment] 2024-03-10 06:09
> We will need to fix this in the Xaml Compiler so that the generated IXMP works correctly in this scenario. It should ensure that the XamlControlsXamlMetaDataProvider is always first in the list of OtherProviders.
> 
> Until this issue is fixed, here is one way to work around the issue.
> 
> In your app's csproj file add this property to the first PropertyGroup:
> 
> ```
> <XamlCodeGenerationControlFlags>DoNotGenerateOtherProviders</XamlCodeGenerationControlFlags>
> ```
> 
> This will cause the Xaml Compiler to not populate the OtherProviders list. You now need to populate it manually. In your App's constructor, call AddOtherProvider to add each of the IXamlMetadataProviders that were previously being generated. Since you can now control the order you can make sure that XamlControlsXamlMetaDataProvider comes first:
> 
> ```
>     public App() 
>     {
>         this.InitializeComponent();
>         this.AddOtherProvider(new Microsoft.UI.Xaml.XamlTypeInfo.XamlControlsXamlMetaDataProvider());
>         this.AddOtherProvider(new AClassLibrary1.AClassLibrary1_XamlTypeInfo.XamlMetaDataProvider());
>     }
> ```
> 
> The downside to this is you need to manually add any new IXMP implementations that your app needs if you add a new dependency to your app.

This issue also reproduces on WindowsAppSDK 1.5 (SelectorBar) with CommunityToolkit controls (etc. SettingsControls) 8.0.2.

I changed to code to use manually add other provides for an temporary solution.

**Comment by OrangeDogSoftware** [comment] 2024-03-30 08:22
Hello, I have the same issue and I don't understand anything as workaround that was written here. Could you please provide a way to not have this error for a dummy ? thanks

**Comment by efreykongcn** [comment] 2024-04-01 05:09
@OrangeDogSoftware 

I've created a temporary solution sample project for this issue: [Issue8810TemporarySolution](https://github.com/efreykongcn/Issue8810TemporarySolution). 

Hope it will help.

**Comment by kmahone** [comment] 2024-05-10 17:08
I merged a fix for this issue into internal builds. I expect the fix to ship in WinAppSDK 1.6.

**Closed** 2024-05-11 07:06 UTC
Labels: bug, area-ItemsRepeater, team-Reach, fixed-internally, wct, closed-Fixed

**Comment by codendone** [comment] 2024-06-06 21:34
1.6-experimental1 has now been released, on June 4.

**Comment by catmanjan** [comment] 2026-07-07 12:59
this is happening again in a project using latest 2026 stack
