### ISSUE TITLE
Blank WinUI 3 App not working - wrong WinRT version

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5141] opened 2021-06-03 16:34 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Blank-WinUI-3-App-not-working---wrong-Wi/1413767)._

---
[severity:I'm unable to use this version]
I've just done a clean install, I believe I've got the latest 'everything'. But when I run a Blank WinUI app (Non-UWP) I get the following error:

This version of Project Reunion requires WinRT.Runtim.dll version 1.2 or greater.

---
#### Feedback Bot on 5/6/2021, 01:35 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
#### Gavin Williams solved on 5/5/2021, 11:08 PM, 0 votes: 

<p>Somebody on the UWP Community Discord helped me by suggesting…</p>
<p>update cswinrt</p>
<p>Which works, because it’s not even installed in the template even though it’s required.</p>

**Comment by asklar** [comment] 2021-06-04 04:30
Duplicate of #4894

**Closed** 2021-06-10 23:20 UTC
Labels: duplicate
