### ISSUE TITLE
Unable to drag scrollbar with touchscreen

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#7005] opened 2022-04-20 22:20 UTC
### Describe the bug

Occurs on both the collapsed and expanded scrollbars.

### Steps to reproduce the bug

1. Drag on scrollbar thumb with your finger downwards

### Expected behavior

Page scrolls down

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000, Windows 10 (21H2): Build 19044

### Additional context

Could be by design and just not implemented? Scrollbars in File Explorer and other non-WinUI apps, iOS and Chromium have this though, and I see that Edge is looking to be consistent with WinUI's scrollbars.

**Comment by ojhad** [comment] 2022-04-25 23:29
Closing this as by design.

**Closed by ojhad** 2022-04-25 23:29 UTC
Labels: question, needs-triage, team-Controls, area-ScrollBar
