### ISSUE TITLE
Xaml Islands Win32 MenuFlyoutSubItem crash

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#3529] opened 2020-10-30 17:43 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Xaml-Islands-Win32-MenuFlyoutSubItem-cra/1236135?preview=true)._

---
<p class="">Use any Xaml Islands Win32 sample as base, e.g. <a href="https://github.com/microsoft/Xaml-Islands-Samples/tree/master/Samples/Win32" target=_blank class=redactor-added-link tabindex=0>Xaml-Islands-Samples</a></p><p class="">Add a MenuBar with two MenuFlyoutSubItem elements. E.g:</p><pre class="">	&lt;MenuBar&gt;
		&lt;MenuBarItem Title=&quot;MenuBarItem&quot;&gt;
			&lt;MenuFlyoutSubItem Text=&quot;MenuFlyoutSubItem1&quot;&gt;
				&lt;MenuFlyoutItem Text=&quot;MenuFlyoutItem1&quot;/&gt;
			&lt;/MenuFlyoutSubItem&gt;
			&lt;MenuFlyoutSubItem Text=&quot;MenuFlyoutSubItem2&quot;&gt;
				&lt;MenuFlyoutItem Text=&quot;MenuFlyoutItem2&quot;/&gt;
			&lt;/MenuFlyoutSubItem&gt;
		&lt;/MenuBarItem&gt;
	&lt;/MenuBar&gt;</pre><p class="">Run the app, open the menu, hover over the first SubItem until the menu animation starts playing, then quickly move to the second SubItem (or just move quickly between the two subitems without giving enough time for the animation to complete). The app will crash with: &quot;Exception thrown at 0x030B450C (Windows.UI.Xaml.dll) in SampleCppApp.exe: 0xC0000005: Access violation reading location 0x00000000.&quot;</p><p class="">Tried in WinUI 2.4 and WinUI 3 prerelease. Windows version 10.0.18363, Visual Studio 16.7.6.</p>

---
#### Levente Tordai-Karczagi on 10/28/2020, 07:20 AM: 

<p>On further testing I have discovered, that it's not related to the animations. Windows settings "Show animations in Windows" will turn off sliding out the menu, but the problem still persists.</p>

#### Donna Deng [MSFT] on 10/29/2020, 00:56 AM: 

<p>Thank you for taking the time to log this issue!</p>
<p>In order for us to investigate further, please provide more information by recording your repro steps via the Visual Studio Feedback Tool (Help -&gt; Send Feedback -&gt; Report A Problem). The feedback tool will ensure that we collect the needed information for you without worrying about what to provide (recording, dump file or ETL trace). Since this issue is now marked as Need More Info, that workflow is enabled in the Feedback Tool – <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2019#when-further-information-is-needed">full instructions</a><br>
In our <a target='_blank' href="https://aka.ms/vsfeedbackguidelines/#writing-a-good-bug-report-or-feature-suggestion">guidelines</a> , you can get tips on how to provide clear and simple reproducible steps.</p>
<p>Get performance issues fixed quicker, please see <a target='_blank' href="https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019">https://docs.microsoft.com/en-us/visualstudio/ide/how-to-increase-chances-of-performance-issue-being-fixed?view=vs-2019</a>.</p>
<p>We look forward to hearing from you!</p>

#### Levente Tordai-Karczagi on 10/29/2020, 02:56 AM: 

<p>Thank you for looking into this.</p>
<p>I have entered a new report through the feedback tool. Also added a recording. Here is the link: <a target='_blank' href="https://developercommunity2.visualstudio.com/t/xaml-islands-win32-menuflyoutsubitem-crash-1/1237929">https://developercommunity2.visualstudio.com/t/xaml-islands-win32-menuflyoutsubitem-crash-1/1237929</a></p>

#### Feedback Bot on 10/29/2020, 10:45 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by lyahdav** [comment] 2021-04-26 23:49
I found a workaround for this:

1. Instead of using MenuBar/MenuFlyout, switch to a CommandBar/CommandBarFlyout.
2. Subclass AppBarButton:
```
struct CustomAppBarButton : winrt::AppBarButtonT<CustomAppBarButton> {
  CustomAppBarButton() {
    // Because we lose the default behavior of OnPointerExited which reverts the button's styling
    // when the pointer is no longer over the button, we change the button's resources so that the
    // hover color is the same as non-hover color.
    this->Resources().Insert(winrt::box_value(L"AppBarButtonBackgroundPointerOver"),
                             winrt::Application::Current().Resources().Lookup(
                                 winrt::box_value(L"AppBarButtonBackground")));
  }

  void OnPointerExited(winrt::Input::PointerRoutedEventArgs const& e) {
    // This method crashes in the superclass, so we override it to do nothing.
  }
};
```

3. Use that subclass instead of AppBarButton. You can create submenus by setting the [AppBarButton.Flyout](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.button.flyout?view=winrt-19041#Windows_UI_Xaml_Controls_Button_Flyout) property to a MenuFlyout.

This has a few limitations/issues:

1. You can't have more than 1 level of submenus, or you'll re-introduce the crash.
2. The hover styling on the submenu items isn't present. This isn't a big deal because the submenu items have styling when the submenu is open, which happens very shortly after hover.
3. If you're using CommandBarFlyout: it has some bugs with positioning, unrelated to this crash. I found the only options from [FlyoutBase.ShowAt](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.flyoutbase.showat?view=winrt-19041#Windows_UI_Xaml_Controls_Primitives_FlyoutBase_ShowAt_Windows_UI_Xaml_DependencyObject_Windows_UI_Xaml_Controls_Primitives_FlyoutShowOptions_) that work are ones where you specify a non-null placementTarget and showOptions.Placement of TopEdgeAlignedLeft or TopEdgeAlignedRight. Also you need to fix some offset issues with the code below (I'm not sure if this works for all cases, I needed this for a few I tested):
```
      if (options.Placement() == winrt::FlyoutPlacementMode::TopEdgeAlignedLeft) {
        winrt::Point offset = {0.0f, 42.0f};
        options.Position(offset);
      } else if (options.Placement() == winrt::FlyoutPlacementMode::TopEdgeAlignedRight) {
        winrt::Point offset = {static_cast<float>(placementTarget.ActualWidth()), 42.0f};
        options.Position(offset);
      }

```

**Comment by lyahdav** [comment] 2021-04-28 22:46
I forgot another step is required, below. We have to hook into the Closed event to hide any flyouts, likely due to the overriding of `OnPointerExited`. 
```
  auto closedRevoker = commandBarFlyout.Closed([=](winrt::IInspectable const& sender, auto&&) {
    if (auto commandBarFlyout = sender.try_as<winrt::CommandBarFlyout>()) {
      for (int i = 0; i < commandBarFlyout.SecondaryCommands().Size(); i++) {
        if (auto button =
                commandBarFlyout.SecondaryCommands().GetAt(i).try_as<winrt::AppBarButton>()) {
          if (auto flyout = button.Flyout()) {
            flyout.Hide();
          }
        }
      }
    }
  });
```

**Comment by lyahdav** [comment] 2021-05-10 17:17
I found a better implementation of `CustomAppBarButton` from above that fixes some issues with the previous one:
1. There were situations where a submenu could stay visible after the app loses focus.
2. Clicking on submenu items would dismiss the menu, which is not the behavior of MenuFlyoutSubItem.
3. The hover state wasn't working on these menu items.

```
struct CustomAppBarButton : winrt::AppBarButtonT<CustomAppBarButton> {
  void OnPointerExited(winrt::Input::PointerRoutedEventArgs const& e) {
    // This method crashes in the superclass, so we purposely don't call super. But the superclass
    // implementation likely cancels a timer that will show the submenu shortly after pointer enter.
    // Since we don't have access to that timer, instead we reset the Flyout property, which resets
    // the timer. This also fixes a crash where you can get a zombie submenu showing if the app
    // loses focus while this timer is scheduled to show the submenu.
    if (auto flyout = this->Flyout()) {
      this->Flyout(nullptr);
      this->Flyout(flyout);
    }

    // The superclass implementation resets the button to the normal state, so we do this ourselves.
    this->SetValue(winrt::ButtonBase::IsPointerOverProperty(), winrt::box_value(false));
    winrt::VisualStateManager::GoToState(*this, L"Normal", false);
  }

  void OnPointerPressed(winrt::Input::PointerRoutedEventArgs const& e) {
    // Clicking AppBarButton by default will dismiss the menu, but since we only use this class for
    // submenus we override it to be a no-op so it behaves like MenuFlyoutSubItem.
  }
};
```

**Comment by lyahdav** [comment] 2021-08-20 21:49
I confirmed at least in CommandBarFlyout this issue is not fixed in WinUI 2.6.1-prerelease.210709001. I realize the real fix requires WinUI 3, but it seems there should be a workaround in WinUI 2, possible based on my workaround above.

**Comment by aquinn39** [comment] 2021-11-06 07:53
I have experienced this issue as well. It's very annoying.
Hopefully it gets fixed in Windows 10 seeing as many users are unable to upgrade to 11 due to prerequisites.

**Comment by zadjii-msft** [comment] 2021-11-08 11:48
FWIW, this thread and #3953 are dupes, unsure which the team wants to use as the tracking thread. MSFT:36621660 internally seems to suggest that this OS fix should be out later this month, with KB5007253, though, that number doesn't mean anything to me ¯\\\_(ツ)_/¯

**Comment by sylveon** [comment] 2022-07-06 06:30
@zadjii-msft checking back on this: do you know in which exact KBs the issue was fixed, and if there is a way for me to detect the fix besides reading the OS build number?

**Comment by zadjii-msft** [comment] 2022-07-06 10:58
[KB5007253](https://support.microsoft.com/en-gb/topic/november-22-2021-kb5007253-os-builds-19041-1387-19042-1387-19043-1387-and-19044-1387-preview-d1847be9-46c1-49fc-bf56-1d469fc1b3af) definitely looks like the one. I honestly don't know if there's a way to check for the fix or not - we just bumped our min version to 19041, but not everyone's got that kind of liberty.

**Comment by sylveon** [comment] 2022-07-07 03:07
Do we know if the fix got backported to the 18362 and friends builds, and if yes which KB? That's my min target right now. I can keep using the legacy Win32 context menu for these builds, but it'd be interesting to see if I can enable the MenuFlyout-based menus for these users as well.

**Comment by zadjii-msft** [comment] 2022-07-07 11:07
I don't believe so. Unfortunately, the bar for servicing to that build is a lot higher, so we could only get it back to 19041 😕 

(note to self: that's noted in MSFT:36393125)

**Comment by sylveon** [comment] 2022-07-07 21:03
Thanks for letting me know! I have to keep the legacy Win32 implementation anyways for people who are on 19041+ but never update their machines, so it's not much trouble using that implementation on 18362 as well (I dynamically build a Win32 menu based on the Xaml MenuFlyout, so the maintenance cost is pretty low).

**Closed** 2023-08-04 12:01 UTC
Labels: area-Islands, needs-winui-3, team-Reach, no-issue-activity
