### ISSUE TITLE
webview2 flicking

### ISSUE THREAD

**Issue by vzhilong** [microsoft/microsoft-ui-xaml#10011] opened 2024-09-25 08:54 UTC
My microsoft edge webview2 runtime upgrade to 129.0.2792.52, and when create the webview2 instance there may be a white window flicking and close quickly.

The problem reproduction easily, just open the winui3 gallery app and switch to the webview2 demo page. 

Here are my reproduction captures bellow:

**Comment by vzhilong** [comment] 2024-09-25 08:55
![IMG_5899](https://github.com/user-attachments/assets/29a5349b-a2d1-498c-ae06-62a6bd1a692b)
![IMG_5898](https://github.com/user-attachments/assets/4566714c-c07d-4f5e-a151-f7c43cd75dd0)

**Comment by Zulu-Inuoe** [comment] 2024-09-25 14:57
We are seeing this same issue. There is a sample project https://github.com/stegru/webview-poc which demonstrates the issue

**Comment by stegru** [comment] 2024-09-25 15:07
![webview-flicker](https://github.com/user-attachments/assets/df54011d-b5cc-44ca-a46a-b33972bce293)

**Comment by michael-hawker** [comment] 2024-09-25 18:43
I can also verify that I saw this in the WinUI Gallery app 2.4.3 on 23H2 22631.4169 when switching to the WebView2 page, there's a briefest flash of a window.

**Comment by andresledo** [comment] 2024-09-26 10:52
I have the same issue, every time it starts it opens a window and closes in milliseconds.

**Comment by NikolaiKobzev** [comment] 2024-09-26 11:59
I've encountered this issue in my project as well, and I also saw it reproduced in the WinUI 3 Gallery

**Comment by stegru** [comment] 2024-09-26 12:15
Minimal code required:

```c#
WebView2 webView2 = new WebView2();
webView2.EnsureCoreWebView2Async();
```

`webView2.EnsureCoreWebView2Async().AsTask().Wait();` will let the phantom window remain (due to the expected deadlock).

**Comment by RuddyOne** [comment] 2024-09-27 09:19
Also having this issue while using MAUI, there is also an issue over there for this.

https://github.com/dotnet/maui/issues/24933

**Comment by ITaluone** [comment] 2024-09-27 09:38
Can verify too

**Comment by NicholasChrzan** [comment] 2024-09-27 16:48
Here is the issue on Webview2 GitHub:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4834

**Comment by vzhilong** [comment] 2024-09-29 07:29
> Here is the issue on Webview2 GitHub: [MicrosoftEdge/WebView2Feedback#4834](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4834)
> 
> Looks like it affects more than just WinUI and is at its root a WebView2 issue.

It seems to be a very obvious excepiton.
I wonder if there is no qa work in MS.

**Comment by NicholasChrzan** [comment] 2024-09-30 18:47
There was a workaround posted in the WebView2 issue:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4834#issuecomment-2381904393

Environment.SetEnvironmentVariable("WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS", "--window-size=0,0 --window-position=20000,20000");

**Comment by DmitriyKomin** [comment] 2024-10-01 03:12
Thanks for linking to the Edge issue and workaround, @NicholasChrzan! It certainly looks like the WebView2Runtime issue described in [MicrosoftEdge/WebView2Feedback#4834](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4834), so I'm closing this bug.

**Closed by DmitriyKomin** 2024-10-01 03:12 UTC
Labels: closed-Duplicate
