### ISSUE TITLE
Hope to expose SystemConfiguration of the default backdrop

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#8818] opened 2023-09-03 04:09 UTC
### Describe the bug

Hope to expose SystemConfiguration of the default backdrop

Currently, bringing Microsoft.UI.Xaml.Media namespace MicaBackdrop and DesktopAcrylicBackdrop not exposed outside the default SystemBackdropConfiguration object. If we want to use SystemBackdropConfiguration this object, the need to derive SystemBackdrop and implement a custom Backdrop, this is not a perfect solution. Hope that future versions will provide default in own MicaBackdrop and DesktopAcrylicBackdrop SystemBackdropConfiguration

### Steps to reproduce the bug

None

### Expected behavior

Expose SystemBackdropConfiguration of the default MicaBackdrop and DesktopAcrylicBackdrop

### Screenshots

None

### NuGet package version

WinUI 3 - Windows App SDK 1.4.0: 1.4.230822000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by bpulliam** [comment] 2023-09-07 18:28
Duplicate of #8845

**Closed by bpulliam** 2023-09-07 18:28 UTC
Labels: bug
