### ISSUE TITLE
C++/WinRt with XAML only works on flat-directory project structure

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#1551] opened 2019-11-06 00:41 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/content/problem/804459/cwinrt-with-xaml-only-works-on-flat-directory-proj.html)._

---
Steps:
1) In the PhotoEditor sample app, create subfolder PhotoEditor/MyViews
2) In Solution Explorer add a filter of the same name
3) In the PhotoEditor/MyViews folder add a blank user control named MyUserControl
4) Build the app

Error: InitializeComponent() and Button() are undefined in MyUserControl.

I traced the problem as follows:
```
PhotoEditor
    |____MyViews
    |    |____MyUserControl.idl
    |    |____MyUserControl.xaml
    |    |____MyUserControl.h
    |    |____MyUserControl.cpp
    |
    |____Generated Files
    |    |____MyViews
    |    |    |____MyUserControl.xaml.g.h
    |    |
    |    |____MyUserControl.g.h
    |    |____ ...
    |
    |____App.cpp
    |____...
```
Note that MyUserControl.xaml.g.h is (correctly) generated in the MyViews subfolder. However, MyUserControl.g.h assumes otherwise.

MyUserControl.g.h:
```
#if defined(WINRT_FORCE_INCLUDE_MYUSERCONTROL_XAML_G_H) || __has_include(&quot;MyUserControl.xaml.g.h&quot;)
#include &quot;MyUserControl.xaml.g.h&quot;
#else

namespace winrt::PhotoEditor::implementation
{
    template &lt;typename D, typename... I&gt;
    using MyUserControlT = MyUserControl_base&lt;D, I...&gt;;
}

#endif
```
Because __has_include(&quot;MyUserControl.xaml.g.h&quot;) yields 0, MyUserControlT derives from non-XAML base and hence the error.

Fix: The code generation tool should emit:
```
#if defined(WINRT_FORCE_INCLUDE_MYUSERCONTROL_XAML_G_H) || __has_include(&quot;MyViews/MyUserControl.xaml.g.h&quot;)
#include &quot;MyViews/MyUserControl.xaml.g.h&quot;
#else
...
#endif
```
Hope this helps.

---
#### Visual Studio Feedback System on 11/4/2019, 01:27 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by stevenbrix** [comment] 2019-11-06 17:34
Hmm, I wonder if this is a cppwrint or xaml compiler issue. @kennykerr do you know?

**Comment by kennykerr** [comment] 2019-11-06 17:43
The cppwinrt compiler provides a few different ways to structure includes, but I believe the combination of msbuild and xaml takes a narrower path. @danzil or @Scottj1s may have additional commentary but I don't think this is open to change at this point.

**Comment by danzil** [comment] 2019-11-06 17:48
cppwinrt.exe emits this file 'MyUserControl.g.h', so there is where the bug lies, I believe. Kenny's right, there are some limitations regarding project structure that impose a certain flatter project structure. @Scottj1s may know if this is fixable.

**Comment by Scottj1s** [comment] 2019-11-07 16:37
Yes, this is a known limitation of cppwinrt.exe, which does not have access to the project structure, as the xaml compiler does.  There is some support for nested folders, which must follow namespace hierarchy, but not generalized folder layout.

**Comment by danzil** [comment] 2019-11-07 23:54
Closing per Scott's comment

**Closed by danzil** 2019-11-07 23:54 UTC
Labels: area-ProjectSystem, needs-triage, team-Markup

**Comment by asklar** [comment] 2021-03-09 03:10
Duplicate of https://github.com/microsoft/cppwinrt/issues/731
