### ISSUE TITLE
Facing the Trojan virus threat when create a new WinUI app using VS 2022 preview 17.3 latest version

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#7120] opened 2022-05-18 19:10 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Facing-the-Trojan-virus-threat-when-crea/10043317)._

---
[severity:It bothers me. A fix would be nice] [regression] [worked-in:17.2 preview 4]
Hi team,

I am using the VS 2022 Preview 17.3 and you can find the same details in the attached image.
![image.png](https://aka.ms/dc/image?name=Bd5366b4b9a5943ca8f1c7910e38a1276637882880792587217_20220516-142438-image.png&tid=d5366b4b9a5943ca8f1c7910e38a1276637882880792587217)

When I created a new WinUI project with VS 2022 preview and started running it. Windows defender started showing it as Trojan virus as shown below.
![image.png](https://aka.ms/dc/image?name=B101cae61538741878539049243276b6d637882881663282024_20220516-142605-image.png&tid=101cae61538741878539049243276b6d637882881663282024)

In a instant I have deleted the project and rescaned once again and there was no threat. Please check the issue and let me know if you need any other information.
![image.png](https://aka.ms/dc/image?name=B8e76285f7c1e4f228984a6faf3ca9bc4637882882831976788_20220516-142802-image.png&tid=8e76285f7c1e4f228984a6faf3ca9bc4637882882831976788)

Regards,
Niranjan kumar

---
#### Feedback Bot on 5/16/2022, 08:19 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by Niranj-Ninja** [comment] 2022-05-19 02:55
Hi Team,

The above image files are not displaying properly since moving the ticket from the Developer Community. Please find the same images below.

VS 2022 detail:
<img width="582" alt="image" src="https://user-images.githubusercontent.com/93654184/169194411-1ebbd6cf-75ad-47ae-aeb1-942e76fb84ba.png">

Issue: 
<img width="428" alt="image" src="https://user-images.githubusercontent.com/93654184/169194498-0d3febb5-0e2b-4f64-b248-0da0d48ac52b.png">

System details:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/93654184/169194555-68439371-154e-4a8f-8acc-19ea2f75ffdd.png">

Regards,
Niranjan Kumar

**Comment by Niranj-Ninja** [comment] 2022-09-29 02:54
Hello @ojhad ,

The issue is resolved in the latest version of VS 2022 Preview.

**Closed** 2022-10-17 13:19 UTC
Labels: bug, area-External
