### ISSUE TITLE
Some StaticResource entries point to Color objects

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/microsoft-ui-xaml#7691] opened 2022-09-06 10:21 UTC
I noticed that some StaticResources defined in the library point to Color objects instead of their SolidColorBrush equivalent, but they're still used in place of actual brushes in the styles.
An example is
`<StaticResource x:Key="RadioButtonOuterEllipseStrokePointerOver" ResourceKey="ControlStrongStrokeColorDefault" />`
I was now wondering if this  on purpose and in case what's the actual reason.

Sorry, I know I didn't use the right ticket template but I couldn't find a better fitting one 😅

**Comment by marksfoster** [comment] 2022-09-13 22:49
Color animations cannot point to a SolidColorBrush, only a Color.

**Comment by FrayxRulez** [comment] 2022-09-25 16:14
> Color animations cannot point to a SolidColorBrush, only a Color.

I don't think that this is anyhow related.

**Comment by MikeHillberg** [comment] 2022-10-06 21:53
The Xaml markup parser does this as a convenience helper; automatically converting the Color into a SolidColorBrush.

So in this case ControlStrongStrokeColorDefault is a Color, consequently RadioButtonOuterEllipseStrokePointerOver is a Color, yet it can be set in markup to a (Brush-typed) Stroke property.

This implicit conversion is certainly useful, but kind of random on this one type, not part of a general feature. It would be useful to make it into a more generalized implicit conversion mechanism.

**Comment by marksfoster** [comment] 2022-10-07 18:05
@FrayxRulez asked: "I noticed that some StaticResources defined in the library point to Color objects instead of their SolidColorBrush equivalent"

RadioButtonOuterEllipseStrokePointerOver value points to a Color resource (ControlStrongStrokeColorDefault) and not a SolidColorBrush because if you look at the visual state using RadioButtonOuterEllipseStrokePointerOver:

`<LinearColorKeyFrame KeyTime="{StaticResource ControlFasterAnimationDuration}" Value="{ThemeResource RadioButtonOuterEllipseStrokePointerOver}" />`

`<StaticResource x:Key="RadioButtonOuterEllipseStrokePointerOver" ResourceKey="ControlStrongStrokeColorDefault" />`

`<Color x:Key="ControlStrongStrokeColorDefault">#8BFFFFFF</Color>`

You'll see it is a LinearColorKeyFrame which is part of a color animation (ColorAnimationUsingKeyFrames) that cannot use a SolidColorBrush, only a Color.

https://github.com/microsoft/microsoft-ui-xaml/blob/8ac2866a2b42165184a265181caa931f6638ccbd/dev/CommonStyles/RadioButton_themeresources.xaml#L270

**Comment by bpulliam** [comment] 2022-10-29 22:33
Closing this issue as By Design

**Closed by bpulliam** 2022-10-29 22:33 UTC
Labels: question
