### ISSUE TITLE
Extend TabView in title bar in WinUI 3

### ISSUE THREAD

**Issue by manfromarce** [microsoft/microsoft-ui-xaml#5730] opened 2021-08-20 10:14 UTC
I'm trying to to show TabView tabs in the title bar in WinUI 3. This could be done quite easily [in UWP](https://docs.microsoft.com/en-us/windows/apps/design/controls/tab-view#display-tabview-tabs-in-a-windows-titlebar), but obviously some of these APIs are not available in WinUI.
So I tried: 
`this.ExtendsContentIntoTitleBar = true;`
`tabViewFooter.MinWidth = 100;`
`this.SetTitleBar(tabViewFooter);`
where "this" refers to main Window, but it doesn't work properly. The window can be dragged and maximized / restored by double clicking but Minimize, Maximize and Close buttons don't appear and the area where they should be is unresponsive to mouse events. 
If it worked, it wouldn't be 100% correct anyway because, unlike the UWP sample, it uses a fixed width and doesn't consider RTL layouts.
Am I missing something?

**Comment by Sanlorng** [comment] 2021-08-21 10:41
You can try this code (please check your winui version >= 1.0.0 experimental

**create helper class**
```   
public static class AppWindowHandle
    {
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }

        [DllImport("Microsoft.UI.Windowing.Core.dll", CharSet = CharSet.Unicode)]
        private static extern int GetWindowHandleFromWindowId(WindowId windowId, out IntPtr result);

        [DllImport("Microsoft.UI.Windowing.Core.dll", CharSet = CharSet.Unicode)]
        private static extern int GetWindowIdFromWindowHandle(IntPtr hwnd, out WindowId result);

        public static AppWindow GetAppWindow(this Microsoft.UI.Xaml.Window window)
        {
            IntPtr windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(window);
            _ = GetWindowIdFromWindowHandle(windowHandle, out WindowId windowId);
            return AppWindow.GetFromWindowId(windowId);
        }
    }
```
**using AppWindow.TitleBar.ExtendsContentToTitleBar** 
```
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            Title = "ADB 连接助手";
            AppWindow appWindow = this.GetAppWindow();
            AppWindowTitleBar titleBar = appWindow.TitleBar;
            titleBar.ExtendsContentIntoTitleBar = true;
            titleBar.ButtonBackgroundColor = Colors.Transparent;
            SetTitleBar(CustomDragArea);
        }

    }

```

**Comment by Sanlorng** [comment] 2021-08-21 10:42
You can try this code (please check your winui version >= 1.0.0 experimental

**create helper class**
```   
public static class AppWindowHandle
    {
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }

        [DllImport("Microsoft.UI.Windowing.Core.dll", CharSet = CharSet.Unicode)]
        private static extern int GetWindowHandleFromWindowId(WindowId windowId, out IntPtr result);

        [DllImport("Microsoft.UI.Windowing.Core.dll", CharSet = CharSet.Unicode)]
        private static extern int GetWindowIdFromWindowHandle(IntPtr hwnd, out WindowId result);

        public static AppWindow GetAppWindow(this Microsoft.UI.Xaml.Window window)
        {
            IntPtr windowHandle = WinRT.Interop.WindowNative.GetWindowHandle(window);
            _ = GetWindowIdFromWindowHandle(windowHandle, out WindowId windowId);
            return AppWindow.GetFromWindowId(windowId);
        }
    }
```
**using AppWindow.TitleBar.ExtendsContentToTitleBar** 
```
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            this.InitializeComponent();
            AppWindow appWindow = this.GetAppWindow();
            AppWindowTitleBar titleBar = appWindow.TitleBar;
            titleBar.ExtendsContentIntoTitleBar = true;
            titleBar.ButtonBackgroundColor = Colors.Transparent;
            SetTitleBar(CustomDragArea);
        }

    }

```

**Comment by manfromarce** [comment] 2021-08-21 11:57
Thanks for your answer but unfortunately I get an exception on startup:
```
onecoreuap\windows\moderncore\windowing\TitleBar\TitleBar.cxx(132)\Microsoft.UI.Windowing.Core.dll!18E0D7D8: (caller: 18E0DB46) FailFast(1) tid(3ed0) 80004002 Interface not supported.
Unhandled exception at 0x18E0D7D8 (Microsoft.UI.Windowing.Core.dll) in TabberSample.exe: Fatal program exit requested.
```

**Comment by Sanlorng** [comment] 2021-08-21 16:46
> Thanks for your answer but unfortunately I get an exception on startup:
> 
> ```
> onecoreuap\windows\moderncore\windowing\TitleBar\TitleBar.cxx(132)\Microsoft.UI.Windowing.Core.dll!18E0D7D8: (caller: 18E0DB46) FailFast(1) tid(3ed0) 80004002 Interface not supported.
> Unhandled exception at 0x18E0D7D8 (Microsoft.UI.Windowing.Core.dll) in TabberSample.exe: Fatal program exit requested.
> ```

check your winui version, this method only avaliable in 1.0.0-experimental

**Comment by manfromarce** [comment] 2021-08-22 06:09
Yes, I'm sure I'm using 1.0.0-experimental1

**Comment by Sanlorng** [comment] 2021-08-22 08:29
> Yes, I'm sure I'm using 1.0.0-experimental1

```
Windowing (experimental feature)
This release includes updates to the windowing APIs. These are a set of high-level windowing APIs, centered around the AppWindow class, which allows for easy-to-use windowing scenarios that integrates well with the Windows user experience and other apps. This is similar to, but not the same as, the UWP AppWindow.

Important limitations:

This release of AppWindow is currently available only to Win32 apps (both packaged and unpackaged).
The Windows App SDK does not currently provide methods for attaching UI framework content to an AppWindow; you are limited to using the HWND interop access methods.
The Windowing API's will currently not work on Windows version 1809 and 1903 for AMD64.
For more information, see Manage app windows.
```

**Comment by manfromarce** [comment] 2021-08-23 06:51
The windowing APIs work, I can set the title or move the window programmatically. 
The exception occurs when I try to set any property on the TitleBar object (ButtonBackgroundColor, ExtendsContentIntoTitleBar, ButtonForegroundColor, ...). It's probably not fully implemented yet because almost all properties have a value of 0 or null even after the window has been shown

**Comment by Sanlorng** [comment] 2021-08-24 16:39
@manfromarce Everything work on my device……

**Comment by Sanlorng** [comment] 2021-08-24 16:39
@manfromarce Everything work on my device……

**Comment by StephenLPeters** [comment] 2021-09-14 23:49
duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4835?  @pratikone thoughts?

**Comment by wcavell** [comment] 2021-09-15 03:14
try set TitleBarMinMaxCloseContainer Top

`<Style TargetType="ContentControl" x:Key="WindowChromeStyle">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ContentControl">
                            <Grid x:Name="LayoutRoot">
                                <VisualStateManager.VisualStateGroups>
                                    <VisualStateGroup x:Name="CommonStates">
                                        <VisualState x:Name="Normal">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="{ThemeResource WindowCaptionBackground}" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                        <VisualState x:Name="WindowInactive">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="{ThemeResource WindowCaptionBackgroundDisabled}" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForegroundDisabled}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForegroundDisabled}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForegroundDisabled}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                    </VisualStateGroup>
                                </VisualStateManager.VisualStateGroups>
                                <ContentPresenter x:Name="ClientAreaPresenter"
                                    Content="{TemplateBinding Content}"
                                    ContentTemplate="{TemplateBinding ContentTemplate}"
                                    ContentTransitions="{TemplateBinding ContentTransitions}"
                                    Foreground="{TemplateBinding Foreground}"/> 
                                <Grid x:Name="TitleBarMinMaxCloseContainer"
                                    HorizontalAlignment="Right"
                                    VerticalAlignment="Top"
                                    Visibility="{Binding CaptionVisibility, RelativeSource={RelativeSource TemplatedParent}}">
                                    <Grid x:Name="MinMaxCloseContainer"
                                        HorizontalAlignment="Right"
                                        VerticalAlignment="Top"
                                        ColumnDefinitions="Auto,Auto,Auto">
                                        <Button x:Name="MinimizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Minimize"
                                        AutomationProperties.AutomationId="_MinimizeButton"
                                        Grid.Column="0"
                                        Content="M 0 0 H 10">
                                        </Button>

                                        <Button x:Name="MaximizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Maximize"
                                        AutomationProperties.AutomationId="_MaximizeButton"
                                        Grid.Column="1"
                                        Content="M 0 0 H 10 V 10 H 0 V 0">
                                        </Button>
                                        <Button x:Name="CloseButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Close"
                                        AutomationProperties.AutomationId="_CloseButton"
                                        Grid.Column="2"
                                        Content="M 0 0 L 10 10 M 10 0 L 0 10">
                                            <Button.Resources>
                                                <ResourceDictionary>
                                                    <ResourceDictionary.ThemeDictionaries>
                                                        <ResourceDictionary x:Key="Light">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="Dark">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="HighContrast">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                                        </ResourceDictionary>
                                                    </ResourceDictionary.ThemeDictionaries>
                                                </ResourceDictionary>
                                            </Button.Resources>
                                        </Button>
                                    </Grid>
                                </Grid>
                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>`

**Comment by manfromarce** [comment] 2021-09-20 12:33
The solution provided by @wcavell generally works, but if the title bar is inside TabViewFooter buttons still aren't clickable. Probably the title bar must be a root element.

The only workaround I've found is to hide the system title bar buttons and use custom buttons, following system style. However, there are still some issues and in this case you have to manage Minimize / Maximize yourself.
In App.xaml:
```
            <Style TargetType="ContentControl" x:Key="WindowChromeStyle">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ContentControl">
                            <Grid x:Name="LayoutRoot">
                                <Grid x:Name="TitleBarMinMaxCloseContainer" Visibility="Collapsed">
                                    <Grid x:Name="MinMaxCloseContainer"/>
                                </Grid>
                                <ContentPresenter x:Name="ClientAreaPresenter"
                            Content="{TemplateBinding Content}"
                            ContentTemplate="{TemplateBinding ContentTemplate}"
                            ContentTransitions="{TemplateBinding ContentTransitions}"
                            Foreground="{TemplateBinding Foreground}"/>
                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>
```
In TabStripFooter:
```
                <Grid ColumnDefinitions="*,Auto">
                <Grid x:Name="CustomDragArea" Grid.Column="0" MinWidth="45">
                </Grid>
                <Grid Grid.Column="1" HorizontalAlignment="Right" VerticalAlignment="Stretch" ColumnDefinitions="Auto,Auto,Auto">
                    <Button x:Name="MinimizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Minimize"
                                        AutomationProperties.AutomationId="_MinimizeButton"
                                        Grid.Column="0"
                                        Content="M 0 0 H 10"
                                        Click="MinimizeButton_Click">
                    </Button>
                    <Button x:Name="MaximizeButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Maximize"
                                        AutomationProperties.AutomationId="_MaximizeButton"
                                        Grid.Column="1"
                                        Content="M 0 0 H 10 V 10 H 0 V 0"
                                        Click="MaximizeButton_Click">
                    </Button>
                    <Button x:Name="CloseButton"
                                        Style="{StaticResource WindowCaptionButton}"
                                        AutomationProperties.Name="Close"
                                        AutomationProperties.AutomationId="_CloseButton"
                                        Grid.Column="2"
                                        Content="M 0 0 L 10 10 M 10 0 L 0 10"
                                        Click="CloseButton_Click">
                        <Button.Resources>
                            <ResourceDictionary>
                                <ResourceDictionary.ThemeDictionaries>
                                    <ResourceDictionary x:Key="Light">
                                        <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                        <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                        <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                        <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                    </ResourceDictionary>
                                    <ResourceDictionary x:Key="Dark">
                                        <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                        <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                        <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                        <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                    </ResourceDictionary>
                                    <ResourceDictionary x:Key="HighContrast">
                                        <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver"/>
                                        <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed"/>
                                        <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver"/>
                                        <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed"/>
                                    </ResourceDictionary>
                                </ResourceDictionary.ThemeDictionaries>
                            </ResourceDictionary>
                        </Button.Resources>
                    </Button>
                </Grid>
                </Grid>
```
In Window code-behind:
```
 public MainWindow()
        {
            this.InitializeComponent();
            ExtendsContentIntoTitleBar = true;
            SetTitleBar(CustomDragArea);
        }
```

**Comment by pratikone** [comment] 2021-09-23 02:11
If you refer to the docs on custom titlebar, we recommend using simple UI elements like stackpanel or grid for custom titlebar element. Complex elements create ui layout issues. Also, any uielement set as custom titlebar cannot receive input because all the input is taken for titlebar operations like drag. 

 https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window.settitlebar?view=winui-3.0

I am closing this issue. If you got follow up question, feel free to re-open it.

**Closed by pratikone** 2021-09-23 02:11 UTC
Labels: needs-triage, team-Reach, product-winui3, area-TitleBar
