### ISSUE TITLE
ListView does not maintain current selected item when its SelectionMode is changed.

### ISSUE THREAD

**Issue by hungnd1475** [microsoft/microsoft-ui-xaml#3865] opened 2020-12-28 00:12 UTC
**Describe the bug**

When changing `ListView.SelectionMode` from `Single` to `Multiple` and vice versa, the current selected item is lost in the transition.

**Steps to reproduce the bug**

One simple way to reproduce the bug is using the XAML Controls Gallery app:

1. Go to `ListView` page.
2. Scroll down to the section about selection support.
3. When in `Single` mode, select an item, then use the combo box to change the mode to `Multiple`. The current selection is now disappeared.
4. Now in the `Multiple` mode, select some items, then change the mode back to `Single`. All the selected items are now deselected.

**Expected behavior**

* When changing from `Single` to `Multiple`, the selected item should stay selected.
* When changing from `Multiple` to `Single`, the last selected item should stay selected. Or maybe provide a way for programmers to decide between the first or last item to stay selected.

The above expected behaviors can be seen in the Mail app.

**Screenshots**

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|   |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |   |
| May 2019 Update (18362)            |  Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

When I tried to replicate the behaviors seen in the Mail app, I found out that whenever the value of `ListView.SelectionMode` is changed, the `ListView` somehow tries to call the `IndexOf` method of its `ItemsSource` with a null parameter. This leads to the source (in this case a generic `IList`) returning -1. I'm not sure if this has anything to do with the `ListView` losing its selection but worth looking into imo.

**Comment by YuliKl** [comment] 2020-12-28 20:15
@hungnd1475 this behavior feels by design. While going from single to multi-selection and maintaining the currently selected item could make sense, this behavior definitely wouldn't work in reverse, when going from multi to single-selection. So for consistency, it feels best to have the same behavior regardless of current selection mode.

Closing this issue as by design.

**Closed by YuliKl** 2020-12-28 20:15 UTC
Labels: needs-triage
