### ISSUE TITLE
Publish not working in Reunion 0.8

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#5480] opened 2021-07-15 14:16 UTC
Visual Studio version: 16.10.3

Just invoke publish-create package in Visual Studio.

Error message:
```
Can't find asset file “....\obj\wappublish\win10-x86\project.assets.json”
```

There is a `win-x86` folder there, instead of `win10-x86`. The project uses `<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>` correctly.

**Comment by StephenLPeters** [comment] 2021-07-15 23:09
@alwu-msft FYI

**Comment by alwu-msft** [comment] 2021-07-15 23:20
Duplicate of #5248. This is expected to fixed by VS 16.10.4.

**Closed by alwu-msft** 2021-07-15 23:20 UTC
Labels: area-Tooling, needs-triage, product-winui3, team-Markup, version-ProjectReunion 0.8
