### ISSUE TITLE
App resources to control corner radii of controls can't be overridden at the app level

### ISSUE THREAD

**Issue by jess-rod** [microsoft/microsoft-ui-xaml#1834] opened 2020-01-13 13:25 UTC
**Describe the bug**

App resources to control corner radii of controls (i.e. ControlCornerRadius and OverlayCornerRadius) can't be overridden at the app level (i.e. at Application.Resources). If these resources are added to Application.Resources with new values, the new values aren't applied. The default values are still the applied ones.

**Steps to reproduce the bug**

1. Open Visual Studio 2019.
2. Create a new UWP project.
3. Add the Windows UI Library.
4. Write the following in Application.Resources inside App.xaml (following the instructions given on [Page or app-wide CornerRadius changes](https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner#page-or-app-wide-cornerradius-changes):
`<Application.Resources>`
`.    <ResourceDictionary>`
`.    .    <ResourceDictionary.MergedDictionaries>`
`.    .    .    <ResourceDictionary>`
`.    .    .    .    <CornerRadius x:Key="OverlayCornerRadius">10</CornerRadius>`
`.    .    .    .    <CornerRadius x:Key="ControlCornerRadius">12</CornerRadius>`
`.    .    .    </ResourceDictionary>`
`.    .    .    <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />`
`.    .    </ResourceDictionary.MergedDictionaries>`
`.    </ResourceDictionary>`
`</Application.Resources>`
5. In MainPage.xaml, write this code (or similar):
`<Page  ...>`
`.    <Grid>`
`.    .    <Button Content="Button" />`
`.    </Grid>`
`</Page>`

**Expected behavior**

If you override the value of these resources at the app level with the new CornerRadius values, all controls where roundness could be applied would show the new rounded corners accordingly. In this very example, the button should have appeared as if it had been defined like this:
`<Button Content="Button" CornerRadius="12" />`.

**Screenshots**

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.3.191211002.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            |  Yes   | 
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |  Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

There's a note on [Page or app-wide CornerRadius changes](https://docs.microsoft.com/en-us/windows/uwp/design/style/rounded-corner#page-or-app-wide-cornerradius-changes) that says: 

> The OverlayCornerRadius resource must be defined at the app level in order to take effect.

How can that be if the values cannot be overridden at the app level, at least not following the instructions given on the official documentation?

**Comment by Felix-Dev** [comment] 2020-01-13 14:36
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/1486.
Accroding to @chingucoding this has been fixed in the latest insider builds (at least build 19018).

@kaiguo Will this bug be fixed on non-insider versions of Windows 10?

**Comment by ranjeshj** [comment] 2020-01-13 15:31
Closing this bug since it seems to be a dup of  #1486. Can you please comment on the other bug that is still open ? Thanks !

**Closed by ranjeshj** 2020-01-13 15:31 UTC
Labels: needs-triage
