### ISSUE TITLE
Error while creating a WinUI 3, C# on Desktop project.

### ISSUE THREAD

**Issue by Fabi** [microsoft/microsoft-ui-xaml#2949] opened 2020-07-18 06:00 UTC
**Describe the bug**
Creating a new WinUI 3,0 project using the C# on Desktop (package) project results in an error:

`A problem was encountered creating the sub project 'Arctium Sandbox Studio'.  The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.18362.0)" cannot be evaluated. Parameter "targetPlatformIdentifier" cannot have zero length.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
`

**Steps to reproduce the bug**
1. Install the latest VS 2019 Preview+ .NET 5 (Preview 8/RC1)
2. Install the WinUI 3.0 Preview2 extension.
3. Create a WinUI C# on Desktop project.

**Expected behavior**
It should create the project without any errors instead of failing.

**Version Info**
WinUI 3 Preview 2

Windows 10 Pro Insider Preview Build 20170

Desktop

**Additional context**

**Comment by StephenLPeters** [comment] 2020-07-20 23:42
@Fabi have you installed both the x86 and x64 versions of the .net 5 sdk?

@alwu-msft and @stevenbrix FYI.

**Comment by john-h-k** [comment] 2020-07-21 17:43
Occurs to me, I have nightlies of x86 and 64 SDK installed

**Comment by john-h-k** [comment] 2020-07-21 19:03
Fixes if you regress to preview 5 @Fabi

**Comment by Fabi** [comment] 2020-07-22 15:38
Yes, sorry. Works with Preview 5.

**Comment by StephenLPeters** [comment] 2020-07-22 16:30
@alwu-msft or @stevenbrix is this a known requirement?

**Comment by alwu-msft** [comment] 2020-07-22 18:58
We've only tested with .NET 5 Preview 5 so far. It is not surprising that subsequent .NET 5 Previews might cause issues as there is no guarantee of compatibility between different previews.

**Comment by jasonvasquez** [comment] 2020-08-26 15:48
Just as an update, with VS 16.8.0 Preview 2, and .Net5 Preview 8 (x86 and x64 sdks installed), I am observing the same behavior on new project creation.

**Comment by stevenbrix** [comment] 2020-08-26 19:56
Sorry for not responding to this earlier - yeah we have incompatibilities with preview8 of net5 and 16.8 Preview2.

The only current recommendation I can give is to stay on VS16.7.2 and .NET5 Preview5 (not great, I know).  If you want to keep preview8 installed, I'd recommend installing .net5 preview5 using the dotnet install scripts and use global.json to make sure it's picked up.

**Comment by stevenbrix** [comment] 2020-08-26 19:59
Here is the install script I use [Install-DotNet.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5132546/Install-DotNet.zip)

If you run this in an admin powershell window: `Install-DotNet -version 5.0.100-preview.5.20279.10`. This will install both x86 and x64 to program files.

Then you can add a global.json that looks like this:

```json
{
  "sdk": {
    "version": "5.0.100-preview.5.20279.10"
  }
}
```

**Comment by jasonvasquez** [comment] 2020-08-28 15:41
@stevenbrix no problem! Thanks for the update and workaround.

**Comment by akunzz** [comment] 2020-08-29 01:33
I got the same error, pls helps....

**Comment by stevenbrix** [comment] 2020-08-29 21:55
@akunzz you can either uninstall preview8 and install preview5 of .net5, or keep preview8 installed and use the install scripts and global.json workaround I described above.

Either way, you need to use VS16.7.2.

**Comment by nickrandolph** [comment] 2020-08-30 07:03
A couple of extra comment for anyone trying to get this:
- Run the Install-Dotnet script from an elevated prompt
- If you're creating a new solution, create an empty solution, put the global.json file in the same folder as the .sln file and **then** you can add the WinUI for desktop project to the solution. If you don't do this, you'll see the error listed in the issue above, even if you've run the install script

**Comment by nickrandolph** [comment] 2020-08-30 07:33
Now getting the following error when attempting to build and run - any help would be appreciated:

 error NETSDK1005: Assets file 'c:\temp\App5\App1\App1\obj\project.assets.json' doesn't have a target for '.NETCoreApp,Version=v5.0'. Ensure that restore has run and that you have included 'net5.0' in the TargetFrameworks for your project.

**Comment by sbrian26** [comment] 2020-10-22 15:02
Is this issue expected to be fixed when using VS 16.8.0 Preview 5.0+ and .NET 5.0.100-rc.2?

**Comment by tonecool** [comment] 2020-10-26 12:18
The same here, VS 16.8 Preview 5.0 and .NET 5 rc2
![image](https://user-images.githubusercontent.com/12557893/97171290-81c60d00-178d-11eb-822f-4cde050643c3.png)

**Comment by alwu-msft** [comment] 2020-10-26 17:59
This will be fixed in WinUI 3 Preview 3. Unfortunately .NET 5 has had a lot of breaking changes since we released Preview 2; you will need to stick with VS 16.7 and .NET 5 Preview 5 (although I've seen some reports that .NET 5 Preview 7 is the most recent version that is still compatible).

**Comment by marcinsmialek** [comment] 2020-11-08 17:47
With .NET 5 just around the corner, when do you think this will be fixed?

**Comment by anawishnoff** [comment] 2021-01-29 15:18
This was fixed in WinUI 3 Preview 3, so I'm going to go ahead and close this issue. Feel free to re-open and let us know if the issue still persists.

**Closed by anawishnoff** 2021-01-29 15:18 UTC
Labels: area-Desktop, area-NugetPackage, winui3preview

**Comment by frozenprakash** [comment] 2021-05-14 11:49
Hi @anawishnoff,![image](https://user-images.githubusercontent.com/16418079/118266663-8909f980-b4d8-11eb-9bd1-ee7c9e99254c.png)I use latest Preview 3 and still facing the issue, see to the below screenshot for reference.

![image](https://user-images.githubusercontent.com/16418079/118266618-7abbdd80-b4d8-11eb-8e6a-5174b0f25b27.png)
![image](https://user-images.githubusercontent.com/16418079/118266631-7e4f6480-b4d8-11eb-8f46-38c94a1c629c.png)
![image](https://user-images.githubusercontent.com/16418079/118266636-80b1be80-b4d8-11eb-946b-dbb2fd8dc8b6.png)
![image](https://user-images.githubusercontent.com/16418079/118266642-83141880-b4d8-11eb-9c6e-ab9134c71d61.png)
![image](https://user-images.githubusercontent.com/16418079/118266646-84dddc00-b4d8-11eb-960d-84a4528d71c5.png)
![image](https://user-images.githubusercontent.com/16418079/118266654-87403600-b4d8-11eb-9f76-f01455cab673.png)
![image](https://user-images.githubusercontent.com/16418079/118266663-8909f980-b4d8-11eb-9bd1-ee7c9e99254c.png)
![image](https://user-images.githubusercontent.com/16418079/118266674-8c04ea00-b4d8-11eb-8217-696c27e23cce.png)

**Comment by StephenLPeters** [comment] 2021-05-14 23:46
@alwu-msft FYI

**Comment by StephenLPeters** [comment] 2021-05-14 23:46
@frozenprakash .net6 is not currently supported

**Comment by HeyITGuyFixIt** [comment] 2021-07-22 10:24
Is there a work around for encountering this issue again? I'm using GitHub's Actions, on the Windows Server runner (windows-latest). The .NET SDK version is 5.0.302.

**Comment by alwu-msft** [comment] 2021-07-22 17:01
@HeyITGuyFixIt Please open a new issue describing the problem that you're seeing and the steps that we might follow to reproduce it. Given the age of this issue it's likely that the root cause of your problem is different from that of this one. Thanks!
