### ISSUE TITLE
FlyoutMenus no longer produce ledgible text when RequestedTheme="Dark" at the page level

### ISSUE THREAD

**Issue by martgoodall** [microsoft/microsoft-ui-xaml#8842] opened 2023-09-05 17:24 UTC
### Describe the bug

FlyoutMenus no longer produce ledgible text when RequestedTheme="Dark" at the page level.

### Steps to reproduce the bug

use WinUI3 gallery samples, upgrade to WindowsAppSDK 1.4 and add RequestedTheme=Dark to MenuFlyoutPage.xaml and it no longer works. Works ok with 1.3

### Expected behavior

text should be ledgible but colors make it invisible (white foreground on white background).

### Screenshots

![Screenshot 2023-09-05 122245](https://github.com/microsoft/WindowsAppSDK/assets/7119754/76ccfa6c-8421-41b3-976d-e35c6ccdaef7)

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022-preview

### Additional context

actual problem happens in multiple apps but this is the easiest way to recreate it. Occurs in both CS and C++.

**Comment by bpulliam** [comment] 2023-09-07 16:10
Duplicate of #8756

**Closed by bpulliam** 2023-09-07 16:10 UTC
