### ISSUE TITLE
WinUI3 XAML generate wrongs parameter type declaration for C++/WinRT MIDL Array Type

### ISSUE THREAD

**Issue by seven-mile** [microsoft/microsoft-ui-xaml#7929] opened 2022-11-16 08:27 UTC
### Describe the bug

As described in [this article](https://learn.microsoft.com/en-us/uwp/midl-3/intro), single-dimensional array types are standard MIDL 3.0 types, which has the form `T[]`. C++/WinRT itself works well with them, using projected type `winrt::com_array<T>`. But XAML Compiler for C++ doesn't deal with these types correctly.

In detail, the generated code for `{x:Bind ViewModel.SomeArrayProp}` simply does not compile.

### Steps to reproduce the bug

For example
```midl
runtimeclass WmiNamespace
{
    WmiNamespace[] Subspaces{ get; };
}
```
```xaml
<TreeViewItem ItemsSource="{x:Bind Subspaces}" ... />
```
The combination should generate the update method mentioned in the "Screenshots" section below.

### Expected behavior

`::winrt::UFCase::WmiNamespace[] obj`

The projected type chosen by XAML Compiler is a C#-like array type, which is not a valid type declaration in C++. As far as I am concerned, the proper parameter should be `::winrt::com_array<T>`.

### Screenshots

![image](https://user-images.githubusercontent.com/56445491/202127651-3eaf5445-d492-45a2-98f3-1f414a9ff8e3.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.2.0

### Windows version

Windows 11 (22H2): Build 22621

**Comment by Jaiganeshkumaran** [comment] 2022-11-16 11:51
Duplicate of #4119.

**Closed** 2022-11-16 11:53 UTC
Labels: bug, needs-triage

**Comment by Jaiganeshkumaran** [comment] 2022-11-16 11:59
Another thing to be considered is that even if it used the correct syntax, probably it can't be bound to a XAML collection view. This table shows that only non-generic vectors can be bound. In C#, arrays work because the .NET runtime implicitly converts it to an IEnumerable<object> wrapper. I would recommend you use an IVector<T> or IVectorView<T> here. Remember that com_array only supports unique ownership, it's a move-only type, so exposing it as a property probably isn't what you want, unless you're allocating and returning an array every time and not storing it.
