### ISSUE TITLE
ProgressBar causes exception in WinUI App for UWP with Project Reunion SDK

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#4491] opened 2021-03-11 20:00 UTC
Hello!

We are migrating our app from WinUI 3 Preview 4 to the Project Reunion SDK (v. 0.5.0-prerelease). An application failed on ProgressBar initialization.

![image](https://user-images.githubusercontent.com/23479280/110845519-c3c69a00-82bb-11eb-81d8-0cfa3b74049d.png)

For the desktop platform all works as expected.

**Steps to reproduce the bug**

1. Create a blank WinUI 3 for UWP application with Project Reuninon SDK.
2. Put ProgressBar on the main page.
3. Run the app

**NuGet package version: **

WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

**Windows app type:**
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes  | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Version 20H2 (OS Build 19042.804)           |  Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by StephenLPeters** [comment] 2021-03-12 00:05
@BorzillaR is this issue unique to UWP?

**Comment by BorzillaR** [comment] 2021-03-12 05:51
@StephenLPeters, yes, I cannot reproduce it for a desktop application.

**Comment by Nukepayload2** [comment] 2021-08-10 11:58
I've encountered the same problem while porting an old Windows Forms app to WinUI 3. I'm using project reunion 0.8.1 .
```
Xaml parsing failed
Cannot find a Resource with the Name/Key TabViewButtonBackground [Line: 0 Position: 0]
```

![image](https://user-images.githubusercontent.com/10798596/128862790-c1452fe1-799f-4493-b48c-611201562788.png)

If I don't use `ProgressBar`, my app can start normally.

![image](https://user-images.githubusercontent.com/10798596/128862026-fb0b006b-7dce-49ca-a84d-b1b91a0ed5d2.png)

**Comment by mrlacey** [comment] 2021-08-10 12:52
@Nukepayload2 This looks like the kind of situation (that I've hit previously) where the reported error isn't the one that's actually causing the issue.
Can you recreate when you add the ProgressBar in XAML?
Do you have a minimal executable repro?
Does this happen with C# too? (AFAIK VB.Net isn't supported--or am I missing something?)

**Comment by Nukepayload2** [comment] 2021-08-10 14:12
Hi @mrlacey ,

> Can you recreate when you add the ProgressBar in XAML?

I can't use XAML directly at this time, because I haven't finish porting C# WinUI 3 XAML compiler to VB yet. 

But I can reproduce this problem with `XamlReader.Load`. 

Message: XAML parsing failed
Stack trace:
```
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Markup.IXamlReaderStatics.global::Microsoft.UI.Xaml.Markup.IXamlReaderStatics.Load(String xaml)
   at Microsoft.UI.Xaml.Markup.XamlReader.Load(String xaml)
```

![image](https://user-images.githubusercontent.com/10798596/128872819-530b1a37-36f2-49ef-9dc3-ced3be46fc8a.png)

> Do you have a minimal executable repro?

[VbWinUI3TestApp-winui3-4491.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6961947/VbWinUI3TestApp-winui3-4491.zip)

> Does this happen with C# too?

The default C# WinUI 3 template doesn't have this problem. This problem happens only if you don't use `App.xaml` in your project. Maybe this problem is related to `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />`  in `App.xaml`. I'll try to add it to my VB projects manually.

> VB.Net isn't supported

Correct. This sample was created from an empty VB template. I did a lot of research and wrote this project almost line by line. There're no templates, no XAML compilers, no designers and no documentations. Why is it so hard to update my existing Windows Desktop VB apps with WinUI controls?

**Comment by mrlacey** [comment] 2021-08-10 15:09
@Nukepayload2 When I run your repro project I get this:
```ascii
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at WinuiTestAppB2.Program.Main() in C:\Users\matt\Downloads\VbWinUI3TestApp-winui3-4491\WinuiTestAppB2\Program.vb:line 7

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
```

What you've done seems quite impressive but at the moment the issue looks to be something you're doing, rather than a bug in the framework. 
I can create a C# app that can, in code, successfully add a new ProgressBar to a Grid at runtime.

**Comment by Nukepayload2** [comment] 2021-08-10 15:20
@mrlacey 
> When I run your repro project I get this `Class not registered`

Please set startup project to "WinuiTestAppB2Pkg" and then run.

>  the issue looks to be something you're doing

If you remove `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />` in `App.xaml` in your C# project, then you will see the same error as I mentioned if your project is using `ProgressBar`. I don't know whether it's a bug.

**Comment by mrlacey** [comment] 2021-08-10 17:48
> If you remove `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />` in `App.xaml` in your C# project, then you will see the same error as I mentioned if your project is using `ProgressBar`. I don't know whether it's a bug.

Removing a required dependency and then getting an error doesn't sound like a bug. :/

**Comment by StephenLPeters** [comment] 2021-08-10 22:44
The TabViewButtonBackground is defined in the XamlControlsResources.  This is the issue you get when you have imported the Winui nuget package but your project doens't include XamlControlsResources.

**Comment by krschau** [comment] 2022-06-07 18:25
Sounds like this was fixed, and additional questions were resolved. Closing.

**Closed by krschau** 2022-06-07 18:25 UTC
Labels: area-Progress, team-Controls, product-winui3, appModel-UWP, fixed-in-Reunion0.5
