### ISSUE TITLE
DateTimeFormatter date conversion delay in WinUI Desktop

### ISSUE THREAD

**Issue by KarthikRajaAKR** [microsoft/microsoft-ui-xaml#5758] opened 2021-08-24 14:03 UTC
**Description**
I'm using [DateTimeFormatter](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.datetimeformatting.datetimeformatter?view=winrt-20348) to convert a datetime value to string based on [CalendarIdentifiers](https://docs.microsoft.com/en-us/uwp/api/windows.globalization.calendaridentifiers?view=winrt-19041). 

Here DateTimeFormatter takes more time to convert DateTime into a string value in **WinUI Desktop** project for calendar types other than GregorianCalendar. The same scenario working fine under WinUI.UWP projects.

In further, I've analyzed framework controls and I could replicate this issue in [CalendarDatePicker](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.calendardatepicker?view=winrt-20348) itself while using CalendarIdentifiers other than Gregorian calendar.

**Steps to reproduce the bug**
Sample: 
[CalIdentifierDesktop.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7039684/CalIdentifierDesktop.zip)

1. Run the attached sample.
2. Select any date. Now picker works fine. Note calendar type is gregorian
3. Change CalendarIdentifier by using combo box. Now, you will face a delay on date picker popup opening and dates are not showing properly.
4.  This delay occurs for all calendar types other than gregorian.
5. Change type to Gregorian and everything works fine. 

**Note:** I've replicated this issue using CalendarDatePicker, but the actual issue is with DateTimeFormatter conversion.

**Expected behavior**
DateTimeFormatter should work without delay for all types of calendars.

**Video**

https://user-images.githubusercontent.com/41435300/130629692-24619f7a-26d4-4837-9e4d-9e38c05bdb54.mp4

**Version Info**
NuGet package version: 
[WinUI 3 - Project Reunion 0.8 Preview: 0.8.0-preview] 
[WinUI 3 - Windows App SDK 0.8: 0.8.0] 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No| Yes |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | No |
| Surface Hub        | No |
| IoT                | No |

**Comment by StephenLPeters** [comment] 2021-09-16 23:07
@RBrid I think this is a dupe of internal fix: https://dev.azure.com/microsoft/OS/_git/os.2020/pullrequest/6344279 , do you agree?

**Comment by StephenLPeters** [comment] 2021-09-16 23:09
actually maybe not because this seems to only repro with winui desktop.

**Comment by KarthikRajaAKR** [comment] 2021-09-18 17:11
Hi @StephenLPeters,

We are using the below method to get DateTimeFormatter based on calendar identifier and date time format string, this makes our application slow. It takes too much time to get formatter, and memory also increase rapidly while creating new DateTimeFormatter.


`internal static DateTimeFormatter GetFormatter(string language, string calendarIdentifier, string timeFormat)
        {
            var userRegion = new Windows.Globalization.GeographicRegion();
            DateTimeFormatter datetimeformatter = new DateTimeFormatter(
                        timeFormat,
                        new[] { language },
                        userRegion.CodeTwoLetter,
                        calendarIdentifier,
                        Windows.Globalization.ClockIdentifiers.TwelveHour);
            return datetimeformatter;
        }`

**Comment by KarthikRajaAKR** [comment] 2021-09-18 17:16
As I stated before, we are facing issue in DateTimeFormatter for that, I demonstrated the issue using CalendarPicker, we expect performance improvement in DateTimeFormatter class.

**Comment by akilarajesh1313** [comment] 2021-09-23 17:35
Hello @KarthikRajaAKR this is in our backlog and we don't expect to get to it till sometime next year. Hope that helps!

**Closed** 2023-08-03 22:45 UTC
Labels: area-DateTimePickers, team-Controls, product-winui3, no-issue-activity
