### ISSUE TITLE
Microsoft.UI.Xaml.Markup.Compiler generates invalid code for init only properties (binding to records)

### ISSUE THREAD

**Issue by plonkaadam** [microsoft/microsoft-ui-xaml#6701] opened 2022-02-09 17:18 UTC
### Describe the bug

Tried to use a record as a one way view model but it seems impossible. Microsoft.UI.Xaml.Markup.Compiler generates code like:

```
        private void set_3_Item_Name(object instance, object Value)
        {
            var that = (global::App5.Item)instance;
            that.Name = (global::System.String)Value;
        }
```

which generates `error CS8852: Init-only property or indexer 'ISomething.Property' can only be assigned in an object initializer, or on 'this' or 'base' in an instance constructor or an 'init' accessor.`

### Steps to reproduce the bug

1. Create a record type like `public record ReadOnlyModel(string Name);`
2. Try to bind to it using `{x:Bind Name, Mode=OneTime}`
3. The project doesn't compile

### Expected behavior

Able to bind to properties with `init` accessor just like to "get only" properties.

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX), Unpackaged

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022-preview, Visual Studio 2022

**Comment by StephenLPeters** [comment] 2022-03-04 20:54
@RealTommyKlein I think this is a dupe but I can't find the issue.

**Comment by michael-hawker** [comment] 2022-04-28 23:25
🦙 Duplicate of #5315

**Closed by michael-hawker** 2022-04-28 23:25 UTC
Labels: area-XamlCompiler, needs-triage, team-Markup, product-winui3
