### ISSUE TITLE
Navigation View selection not always showing up when adding items in asynchronous thread.

### ISSUE THREAD

**Issue by eduardoaguacate** [microsoft/microsoft-ui-xaml#3206] opened 2020-08-27 21:43 UTC
I think this is related to:  https://github.com/microsoft/microsoft-ui-xaml/issues/3015 NavigationView selection change and child items 

When the selection is done in an async way, it never updates the UX with this. 

Github repo: https://github.com/ejserna/MenuExample-WinUI-2.4.3-C-CX

This code is in `MainPage.xaml.cpp`
**Steps to reproduce the bug**

![NoSelection_WinUI_NavView](https://user-images.githubusercontent.com/11062927/91497665-35d11780-e873-11ea-9ce0-a1bb5f564b56.png)

````c++
void MainPage::AddItemsToMenu()
{
    auto fi = ref new FontIcon();

    auto txtContent = ref new TextBlock();
    txtContent->TextWrapping = TextWrapping::WrapWholeWords;
    txtContent->Text = L"Home";

    auto nvi = ref new Microsoft::UI::Xaml::Controls::NavigationViewItem();
    nvi->Content = txtContent;
    nvi->Icon = fi;
    nvi->IsSelected = true;

    this->MenuCollection->Append(nvi);
    this->navView->SelectedItem = nvi;
}

MainPage::MainPage()
{
	InitializeComponent();
	m_menuCollection = ref new Platform::Collections::Vector<Microsoft::UI::Xaml::Controls::NavigationViewItem^>();
        auto waitTask = concurrency::create_task([](){
            return concurrency::create_async([]() {
                Sleep(1000);
            });
        });

    // This never shows the selected item in the nav menu
    waitTask.then([this]()
    {        
        this->AddItemsToMenu();
    });
}
````
**Expected behavior**
![SelectionExpected_WinUI_NavView](https://user-images.githubusercontent.com/11062927/91497703-484b5100-e873-11ea-8cb9-c81ea27cea11.png)

It should work like when it's not done in an async way:
````c++
MainPage::MainPage()
{
	InitializeComponent();
	m_menuCollection = ref new Platform::Collections::Vector<Microsoft::UI::Xaml::Controls::NavigationViewItem^>();
        this->AddItemsToMenu();
}
````
**Screenshots**

**Version Info**
Microsoft.UI.Xaml 2.4.3

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by YuliKl** [comment] 2020-08-27 23:05
I believe this is a dupe of #2845

**Comment by ejserna** [comment] 2020-08-27 23:29
I see how  they are related. However, in that bug it's about selecting an item in a hierarchical navigation view. This navigation view isn't hierarchical.

**Comment by StephenLPeters** [comment] 2020-08-31 23:24
I think you are right, this sounds different.

**Closed** 2023-08-03 22:38 UTC
Labels: help wanted, area-NavigationView, team-Controls, no-issue-activity
