### ISSUE TITLE
TabView header looks different in dark and light theme

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#2454] opened 2020-05-16 02:59 UTC
**Describe the bug**

The header looks different. It seems the light mode is the right one and dark mode is where it is off.

**Screenshots**

![image](https://user-images.githubusercontent.com/8557046/82108824-c5dfcb00-9774-11ea-9da5-c038e89d55b1.png)

**Version Info**

NuGet package version: 

2.4

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          | Yes   |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by shaheedmalik** [comment] 2020-05-16 03:07
I'm not sure what I am looking for, but I can say that Light Mode has an incorrect contrast ratio for the text / gyph.

**Comment by harvinders** [comment] 2020-05-17 23:18
Here is a closeup. The background behind the tabs and header open area is same in light mode, but different in dark mode

![image](https://user-images.githubusercontent.com/8557046/82162496-538ff780-98e8-11ea-84c8-d72897e9eb74.png)

**Comment by StephenLPeters** [comment] 2020-05-20 22:52
@stmoy is this by design? #1901 could be related here.

**Comment by stmoy** [comment] 2020-05-21 01:07
Not by design, but also no repro in the Xaml Controls Gallery. I see a settings button on the right side of the screenshots above - that might be related. 

@harvinders can you please post your Xaml to debug further?

Here is the Xaml Gallery sample that has Header and Footer set, no repro.

![image](https://user-images.githubusercontent.com/25991996/82512372-c48c0680-9ac4-11ea-8189-6d3504fd5ebf.png)

**Comment by harvinders** [comment] 2020-05-21 01:58
@stmoy My mistake, My TabStripFooter have a CommandBar. Setting the `Background ="Transparent"` fixed it. Ideally speaking it should have impacted both the light and dark mode equally.

**Comment by stmoy** [comment] 2020-05-28 23:30
Thank you for the update. Closing this issue since it was `CommandBar` related. 

I believe the difference in behavior is because the TabView uses different Theme brushes for light and dark theme; the dark theme brush is slightly lighter to help increase the contrast between the selected tab and the background.

**Closed by stmoy** 2020-05-28 23:30 UTC
Labels: area-TabView, team-Controls
