### ISSUE TITLE
Initializing XamlsControlsResources crashes the app when installed from the store

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#999] opened 2019-07-05 14:44 UTC
**Describe the bug**

I included the TeachingTip in my UWP app. Locally it works as expected, both in Debug and in Release mode. But as soon as the app is installed from the store, it crashes: XamlControlsResources cannot be initialized in App.xaml.
I suspect that the appxupload does not contain the Microsoft.Ui.Xaml dependencies; I'm using a Packaging Project to package the app. 

**Steps to reproduce the bug**

1. Right click on the Packaging Project
2. Create App Packages for the store
3. Upload *.appxupload to the store.
4. Submit the new package
5. Wait for the new version to appear in the store
6. Install from the store
7. Launch the app
8. Crash! 

**Expected behavior**
The app should just run without crashing on parsing App.xaml

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml v2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |
| April 2018 Update (17134)          |     |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by wbokkers** [comment] 2019-07-09 07:11
I should add that I don't expect TeachtingTip to be the problem. It is the only WinUI control I use at the moment. Likely, other controls would've given me the same issue.

**Comment by jevansaks** [comment] 2019-07-09 17:13
@wbokkers, I replied on Twitter -- were you able to try the workaround from #616 ? If that works, I'll mark this as duplicate and continue to poke VS folks.

**Comment by wbokkers** [comment] 2019-07-09 17:59
@jevansaks I don't think this is a duplicate issue:

- I can run the app locally using .NET Native in both debug and release mode without problems.
- The manifest contains a PackageDependency to Microsoft.UI.Xaml.2.1, so there's no workaround for me.
- I can install the app package generated for the store locally (from the generated *_Test folder)
- The exception occurs on launching the app after being installed from the store.

**Comment by jevansaks** [comment] 2019-07-09 18:03
Ah, thanks for the clarification. Can you point me to the .appx from the store? Or if you have the broken version installed can you go to the install directory and dump the contents of AppxManifest.xml and share the `<Dependencies>` section?

**Comment by wbokkers** [comment] 2019-07-09 18:04
It can be the case that PackageDependency is missing in the app that is installed from the store. But I put another version on the store without the WinUI control, so that our customers do not longer experience this issue. I don't know if you have access to older versions in the store?

**Comment by wbokkers** [comment] 2019-07-09 18:12
This is the dependencies section of AppxManfiest.xml in the *.bundle.appxupload:
```
<Dependencies>
<TargetDeviceFamily Name="Windows.Desktop" MaxVersionTested="10.0.18362.0" MinVersion="10.0.17134.0"/>
<PackageDependency Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Name="Microsoft.VCLibs.140.00.UWPDesktop" MinVersion="14.0.24217.0"/>
<PackageDependency Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Name="Microsoft.VCLibs.140.00" MinVersion="14.0.26706.0"/>
<PackageDependency Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Name="Microsoft.UI.Xaml.2.1" MinVersion="2.11906.6001.0"/>
<PackageDependency Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Name="Microsoft.NET.Native.Framework.2.2" MinVersion="2.2.27405.0"/>
<PackageDependency Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" Name="Microsoft.NET.Native.Runtime.2.2" MinVersion="2.2.27328.0"/>
</Dependencies>
```

**Comment by jevansaks** [comment] 2019-07-09 18:16
@wbokkers I don't believe I'm able to access older versions from the store.

> It can be the case that PackageDependency is missing in the app that is installed from the store.

Is there any way to confirm that? Would you be willing to publish the app to the store privately under a different app identity with the WinUI dependency re-added and install that to see if the PackageDependency is in fact stripped out on the store side? That would really help us narrow this down.

**Comment by wbokkers** [comment] 2019-07-09 18:19
@jevansaks Maybe I can publish the app with a dependency to WinUI, but without including the resources in App.xaml to see what will be installed?

**Comment by jevansaks** [comment] 2019-07-09 18:25
Yeah, that should give us the answer we need too. Great idea!

**Comment by wbokkers** [comment] 2019-07-09 19:57
I created a package flight that's only visible to me and just installed an update including the reference and the resource in App.xaml. 
After installing this version from the store, the app crashes again. So I can reproduce this issue.

However, the AppxManifest.xml (located in C:\Program Files\WindowsApps\....) DOES contain this dependency:

` <PackageDependency Name="Microsoft.UI.Xaml.2.1" MinVersion="2.11906.6001.0" Publisher="CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US" />
` 
I have no clue on what's going on here....

**Comment by jevansaks** [comment] 2019-07-09 19:59
The plot thickens! Is there a way to flight that package to me as well? (I can DM you my MSA)

You might be running into this other bug where the Microsoft.UI.Xaml framework package's installation is broken -- that one is finally fixed and the engineering team is working on getting it serviced now.

**Comment by wbokkers** [comment] 2019-07-09 20:00
No problem, waiting for your DM...

**Comment by jevansaks** [comment] 2019-08-30 23:12
Sorry for the delay closing this thread, but we believe the issues with framework package installation are fixed and pushed out to servicing. If you are already in this bad state then there's a separate remediation fix which we hope will go out soon.

**Comment by Naveen61097** [comment] 2020-01-07 13:53
The same issue reproducing for me when im using Teaching Tip. The app working fine in both dubug and release mode, but one i upload .appxupload to the store and download the app from store, it crashes. Help me by providing the solution.

**Comment by StephenLPeters** [comment] 2020-01-07 19:13
@ranjeshj I've put this on you, maybe @jevansaks has insights into how this was fixed in the past?

**Comment by Naveen61097** [comment] 2020-01-08 12:12
Hai @ranjeshj ... Any updates on solution ??

**Comment by ranjeshj** [comment] 2020-01-08 17:03
@jevansaks  - what was the fix made initially that resolved @wbokkers issue. I'm curious if @Naveen61097 is hitting the same issue or something different.

**Comment by jevansaks** [comment] 2020-01-08 17:13
I believe the problem was that compiling with VS2017 was not propagating the winmd into the .appx's WinMetadata folder. Then when the store recompiles with .NET Native (which it does because VS2017 has an older version of .NET Native, it wouldn't do this if you had the latest VS2019) then it fumbles the recompile and it starts crashing.

Compiling with VS2019 resolved this issue for the person I was working with. I don't recall if that was @wbokkers's issue, but the symptoms described above seem like the VS2017 issue.

**Comment by wbokkers** [comment] 2020-01-08 17:18
@jvansaks If I remember correctly, I had the tooling issue you described.

**Comment by Naveen61097** [comment] 2020-01-30 09:22
thanks... I builded my app with **VS2019**. It worked fine.

**Closed** 2020-02-19 00:55 UTC
Labels: bug, team-Controls
