### ISSUE TITLE
WebView2 types exist in both Microsoft.Web.WebView2.Core and Microsoft.WinUI

### ISSUE THREAD

**Issue by edoust** [microsoft/microsoft-ui-xaml#5689] opened 2021-08-14 11:16 UTC
I have a .NET 5 desktop app with WinUI 3 and these are some of the package references

<img width="210" alt="package-references" src="https://user-images.githubusercontent.com/6137595/129444435-af4defc7-2459-4079-a101-1b4ae51e7052.png">

I am getting this build error:

`error CS0433: The type 'CoreWebView2NavigationStartingEventArgs' exists in both 'Microsoft.Web.WebView2.Core, Version=1.0.864.35, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' and 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'`

The following code is causing the issue, since the type `CoreWebView2NavigationStartingEventArgs` exists in both `Microsoft.WinUI` and `Microsoft.Web.WebView2.Core`:

```c#
private void AuthWebView_NavigationStarting(WebView2 sender, Microsoft.Web.WebView2.Core.CoreWebView2NavigationStartingEventArgs args)
{
    var destination = args.Uri;

    if (destination.StartsWith(this.Callback, StringComparison.OrdinalIgnoreCase))
    {
        args.Cancel = true;
        this.Result = new WebAuthenticationResult(destination);
        this.Hide();
    }
}
```

Will this be fixed in future versions? Is there any workaround for this error?

Explicitly installing the `WebView2` package and specifying an alias for it does not work - any input would be appreciated. For now I will continue to use `Microsoft.Graph` in version `3.*`

**Comment by llongley** [comment] 2021-08-17 01:52
@Scottj1s Is this C#/WinRT related?  I'm curious whether this is a type getting added to the projection that shouldn't be, or whether this is mixing and matching packages that shouldn't go together.  Should Microsoft.Graph perhaps go into project that creates a projection binary instead of directly being referenced by a .NET 5 project?

**Comment by dahovey** [comment] 2021-11-27 15:29
I ran into this as well, referencing the Microsoft.Identity.Client package directly.

**Comment by dahovey** [comment] 2021-11-29 23:12
See issue in WebView2 repository:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/1921

**Comment by dahovey** [comment] 2021-11-29 23:30
I found a workaround for this! Based on this [stackoverflow question here](https://stackoverflow.com/questions/9194495/type-exists-in-2-assemblies).

1. Add a `PackageReference` to `Microsoft.Web.WebView2`. In my case I chose version `1.0.864.35` because other packages I needed to reference, depended on that version.
2. Select the `Microsoft.Web.WebView2` package in the `Dependencies` section of project.
3. Enter an alias, i.e. `webivew2`

After doing this the `Dependencies` and `Packages` nodes within project, show up with a yellow exclamation triangle, but the project builds without error and works. 

![image](https://user-images.githubusercontent.com/22330242/143958488-c67b7fdd-fc01-4fa8-8bfd-ad9525180e99.png)

**Comment by jameskiltscitrix** [comment] 2022-07-29 20:59
This is also an issue in Maui when adding platform specific browser event handlers, since Maui uses WinUI3+WebView2 on Windows under the hood.  While the solution from @dahovey is appropriate, the issue can also be sidestepped by using a lambda expression to define the handler without specifying the type.

```C#
private async void WebView_HandlerChanged(object sender, EventArgs e)
{
#if WINDOWS
    if (yourMauiBrowser.Handler?.PlatformView is Microsoft.Maui.Platform.MauiWebView webview)
    {
        await webview.EnsureCoreWebView2Async();
        webview.CoreWebView2.WebResourceRequested += (a,b) => CoreWebView2_WebResourceRequested(a,b);
...

**Comment by jameskiltscitrix** [comment] 2022-07-29 21:00
This is also an issue in Maui when adding platform specific browser event handlers, since Maui uses WinUI3+WebView2 on Windows under the hood.  While the solution from @dahovey is appropriate, the issue can also be sidestepped by using a lambda expression to define the handler without specifying the type.

```C#
private async void WebView_HandlerChanged(object sender, EventArgs e)
{
#if WINDOWS
    if (yourMauiBrowser.Handler?.PlatformView is Microsoft.Maui.Platform.MauiWebView webview)
    {
        await webview.EnsureCoreWebView2Async();
        webview.CoreWebView2.WebResourceRequested += (a,b) => CoreWebView2_WebResourceRequested(a,b);
...

**Comment by jameskilts** [comment] 2022-07-29 21:07
This is also an issue in Maui when adding platform specific browser event handlers, since Maui uses WinUI3+WebView2 on Windows under the hood.  While the solution from @dahovey is appropriate, the issue can also be sidestepped by using a lambda expression to define the handler without specifying the type.

```C#
private async void WebView_HandlerChanged(object sender, EventArgs e)
{
#if WINDOWS
    if (yourMauiBrowser.Handler?.PlatformView is Microsoft.Maui.Platform.MauiWebView webview)
    {
        await webview.EnsureCoreWebView2Async();
        webview.CoreWebView2.WebResourceRequested += (a,b) => CoreWebView2_WebResourceRequested(a,b);
...

**Comment by rossirpaulo** [comment] 2022-11-23 18:25
WindowsApp SDK then is not compatible with Microsoft.Identity?!?! Is there a fix coming along?

**Comment by rossirpaulo** [comment] 2022-12-14 03:10
Any ETA?

**Comment by baskren** [comment] 2023-02-09 13:55
@dahovey : posted work around does not work (I _really_, _really_ tried).

Here is a simple demo app showing that the work around does not work: https://github.com/baskren/WinUi3_MSAL_SelfContained_WorkAround_Fail

Here is a simple demo app illustrating the original failure:
https://github.com/baskren/WinUi3_MSAL_SelfContained_Fail

**Comment by baskren** [comment] 2023-02-13 16:01
Hi @asklar and @llongley :  just reaching out to see if there's anything else I can do to get this issue some more love?

**Comment by penndai** [comment] 2023-02-17 03:17
Same error here, we have the WinUI project, and when I add the package Microsoft.Identify.Client, it complains.
The version of Microsoft.WinUI is 3.0.0.0, 
The version of Microsoft.Identity.Client is 4.50.0

The type 'CoreWebView2' exists in both 'Microsoft.Web.WebView2.Core, Version=1.0.864.35, Culture=neutral' and 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral'

**Comment by asklar** [comment] 2023-02-22 08:33
I think you can work around it by not creating the WebView2 in markup, but instead creating it in code behind, e.g.
```csharp
var wv = new WebView2();
grid.Children.Add(wv);
// ...
```

**Comment by MatthewB05** [comment] 2023-05-05 06:25
I'm surprised this has been open for so long without a resolution.  It's still an issue as of today - if you try to publish a MAUI app that references Microsoft.Identity.Client, ,you get a conflict between the WebView2 included as standard with WinUI and the one referenced by the MSAL.

I've tried all kinds of techniques from dozens of StackOverflow posts and elsewhere to try and exclude one of the DLLs from the published build, or make MS Build understand that they're the same file so who even cares, but can't get anything to work :

C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): err
or NETSDK1152: plusieurs fichiers de sortie de publication ayant le même chemin relatif ont été trouvésD:\temp\MauiApp1
\obj\x64\Release\net7.0-windows10.0.19041.0\win10-x64\MsixContent\Microsoft.Web.WebView2.Core.dll, obj\x64\Release\net7
.0-windows10.0.19041.0\win10-x64\R2R\Microsoft.Web.WebView2.Core.dll: . [D:\temp\MauiApp1\MauiApp1.csproj::TargetFramew
ork=net7.0-windows10.0.19041.0]

**Comment by Panda-Sharp** [comment] 2023-05-05 07:10
> I'm surprised this has been open for so long without a resolution. It's still an issue as of today - if you try to publish a MAUI app that references Microsoft.Identity.Client, ,you get a conflict between the WebView2 included as standard with WinUI and the one referenced by the MSAL.
> 
> I've tried all kinds of techniques from dozens of StackOverflow posts and elsewhere to try and exclude one of the DLLs from the published build, or make MS Build understand that they're the same file so who even cares, but can't get anything to work :
> 
> C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets(112,5): err or NETSDK1152: plusieurs fichiers de sortie de publication ayant le même chemin relatif ont été trouvésD:\temp\MauiApp1 \obj\x64\Release\net7.0-windows10.0.19041.0\win10-x64\MsixContent\Microsoft.Web.WebView2.Core.dll, obj\x64\Release\net7 .0-windows10.0.19041.0\win10-x64\R2R\Microsoft.Web.WebView2.Core.dll: . [D:\temp\MauiApp1\MauiApp1.csproj::TargetFramew ork=net7.0-windows10.0.19041.0]
> 
> Edited to add ... the above is only a problem if publishing self-contained. While it might not be possible for everyone, deactivating the self-contained option does at least allow it to work. There may be other people using MAUI who first turned this on because a while back the installer was useless without this option (wasn't capable of actually installing the required dependencies) but that seems to be working at the time of writing.

Sadly I'm not even surprised anymore 😢

**Comment by Daniellled** [comment] 2023-07-15 12:05
This issue also exist if you have a WPF application that uses WebView2 and also attempt to use WindowsAppSDK for functionality such as notifications.

The instant you add any code that uses *CoreWebView2NavigationStartingEventArgs* you receive 

> CS0433	The type 'CoreWebView2NavigationStartingEventArgs' exists in both 'Microsoft.Web.WebView2.Core, Version=1.0.1823.32, Culture=neutral, PublicKeyToken=2a8ab48044d2601e' and 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'

To reproduce I followed these steps https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/wpf-plus-winappsdk#configure-your-wpf-project-for-windows-app-sdk-support followed by these https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/wpf (I omitted the .NET Framework stuff since the app is .NET 6)

The instant I add in this code things quit working

```
void EnsureHttps(object sender, CoreWebView2NavigationStartingEventArgs args)
{
   String uri = args.Uri;
   if (!uri.StartsWith("https://"))
   {
      webView.CoreWebView2.ExecuteScriptAsync($"alert('{uri} is not safe, try an https link')");
      args.Cancel = true;
   }
}
```

I have uploaded an example that reproduces the issue.

[TestAppSDKWebView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/12061354/TestAppSDKWebView.zip)

**Comment by amadeo-alex** [comment] 2023-07-21 19:21
The fact that this issue existed for so long without any traction is at best laughable.
All while UWP Toolkit users are advised to move to the App SDK when encountering a registry bug which was marked as "won't fix because use App SDK"...

**Comment by 27k1** [comment] 2023-07-23 09:14
When is a fix due for this please? Urgent requirement.

**Comment by esmondmissen** [comment] 2023-08-28 16:43
So I've tried all the work arounds and still can't publish an application. Any word from Microsoft or is MAUI abandoned already?

**Comment by MikeG96** [comment] 2023-10-04 02:58
Any update of this?

**Comment by IQTechSolutions** [comment] 2023-10-09 06:50
Maui is a flop. they do not support it. Bugs dont get fixed. microsoft does not even step in in any forum. This is rediculous, I am truly about to give up on maui.

**Comment by Dev-Taehui** [comment] 2023-10-12 08:53
FUCKING MICROSOFT. I FULLY REGRET DEVELOPING WINDOWS APPLICATION.

**Comment by 27k1** [comment] 2023-10-12 08:58
Bad language helps no-one. But we need a solution to this, is there anyone there to respond.

**Comment by Dev-Taehui** [comment] 2023-10-12 09:03
I'm very sorry to you all, but I'm not sorry to MS at all.

When I think about the stress I've been under due to MS's slowdown strike, I feel like my lifespan has been cut in half.

**Comment by 27k1** [comment] 2023-10-12 09:05
Yes, there dev teams need to get sorted out. Or, perhaps, routed out 😉


Peter Farrer
Co-Founder 27k1 Ltd

Mob: +44 (0) 794 678 4302

Peter is a Certified IBITGQ ISO27001:2013 Lead Auditor and Lead Implementer

https//27k1.com<https/27k1.com>

**Comment by baskren** [comment] 2023-10-12 12:28
> I think you can work around it by not creating the WebView2 in markup, but instead creating it in code behind, e.g.
> 
> ```cs
> var wv = new WebView2();
> grid.Children.Add(wv);
> // ...
> ```

@asklar : I am just seeing your response to my question about a work around.  Please note that, I am not directly using WebView2.  Rather, I'm using MSAL (Microsoft Identity Library).  The MSAL team has multiple times pointed me (and others) to this team as the root cause of this issue:

- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3941
- https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583

In fact, they state that your team is aware of this:  https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583#issuecomment-1424467868

Please note, my intent isn't to throw anyone under the bus.  Like everyone else here, we've been unable to ship product for over a year and a half because of this issue.  Resolution of the issue would be very welcome.

**Comment by DonaldAirey** [comment] 2023-11-06 23:25
> I think you can work around it by not creating the WebView2 in markup, but instead creating it in code behind, e.g.
> 
> ```cs
> var wv = new WebView2();
> grid.Children.Add(wv);
> // ...
> ```

I don't know why this was voted down, but it worked for me. The problem, as nearly as I can tell, is with the XAML. It scours the default namespaces for a control called WebView2, and when it finds it in both Microsoft.Identity and Microsoft.WindowsAppSDK package.

**Comment by Denreik** [comment] 2023-11-18 21:32
I got this issue with Uno.WinUI (v.5.0.48) and Microsoft.UI.Xaml on Win10. Gets resolved after I downgrade Microsoft.UI.Xaml to version 2.7.3. or below.

**Comment by AMArostegui** [comment] 2023-11-29 09:40
I'm hit by this issue too.

I'm able to compile by using _Microsoft.Web.WebView2_ NuGet package, but then, fails to publish a self-contained app.

While publishing, NuGet _Microsoft.Web.WebView2.Core.dll_ assembly clashes with _MsixContent\Microsoft.Web.WebView2.Core.dll_

**Comment by leinad13** [comment] 2023-12-15 12:10
I've been hit by this bug trying to build a WinUI3 app and use the Azure.Identity package (which uses Microsoft.Identity.Client). The workaround using ErrorOnDuplicatePublishOutputFiles set to false, doesnt work for me - and neither does adding the WebView2 package with an alias.

Has anyone found any other workarounds?

I guess we are stuck either using workarounds, or just not using Winui3 / MAUI at all as Microsoft aren't going to fix this critical bug - its over 2 years old now...

**Comment by DRAirey1** [comment] 2023-12-15 12:50
> Has anyone found any other workarounds?

Yes. Don't attempt to use XAML to create the control. The logic for finding the library where the control lives has a bug in it. You can reference the control just fine in the code-behind. The solution I posted above works just fine.

**Comment by leinad13** [comment] 2023-12-15 18:56
@DRAirey1 thanks for trying to help, unfortunately I'm not using a WebView2 control anywhere in my XAML. I get an error during build relating to two output files with the same relative path. As far as I can tell from the various issues logged here and in the other repositories relating to this, its because the Windows SDK has a WebView2 control built into the SDK instead of using a nuget package. In my case, I'm trying to use the nugest package Azure.Identity which depends on Microsoft.Identity.Client which depends on Microsoft.Web.WebView2

When the app trys to build it raises [NETSDK1152 ](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/6.0/duplicate-files-in-output). 

I have tried adding the build parameter [ErrorOnDuplicatePublishOutputFiles](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#erroronduplicatepublishoutputfiles) set to false, to my project but it doesn't seem to do anything.

I also tried adding Microsoft.Web.WebView2 as a nuget package and setting an alias, but this didnt work for me either.

`Severity	Code	Description	Project	File	Line	Suppression State
Error	NETSDK1152	Found multiple publish output files with the same relative path: source\repos\AzureToolkit\AzureToolkit\obj\x64\Debug\net7.0-windows10.0.19041.0\MsixContent\Microsoft.Web.WebView2.Core.dll, .nuget\packages\microsoft.web.webview2\1.0.864.35\lib\netcoreapp3.0\Microsoft.Web.WebView2.Core.dll.	AzureToolkit	C:\Program Files\dotnet\sdk\8.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ConflictResolution.targets	112	
`

**Comment by mseitz1** [comment] 2023-12-19 20:05
This issue was also referenced here in 2020: [PackageReference: Need control over the selection for individual .dlls
](https://github.com/NuGet/Home/issues/5986#issuecomment-731985624)

Since I've not seen this mentioned in this thread:
In my case the workarounds suggested here didn't work and the only viable solution was to split the functionality into sub-projects and set <PrivateAssets>all</PrivateAssets> to hide the reference from the main project.

```
<PackageReference Include="Microsoft.Identity.Client" Version="4.58.0">
 	<PrivateAssets>all</PrivateAssets>
</PackageReference>
```

**Comment by AMArostegui** [comment] 2023-12-22 13:30
I was able to solve compiling/publishing errors, but now I'm stuck as the WebView won't initialize in the published version. Regular debug and release versions both work.

I used _ErrorOnDuplicatePublishOutputFiles_ to bypass the conflict between these two webview assemblies

_<project_folder>\obj\x64\Release\net6.0-windows10.0.19041.0\win-x64\MsixContent\Microsoft.Web.WebView2.Core.dll_
![Msix](https://github.com/microsoft/microsoft-ui-xaml/assets/7090613/f97a8a6b-8466-47d7-8d73-e2abff1c7d52)

_<home_folder>\.nuget\packages\microsoft.web.webview2\1.0.864.35\lib\netcoreapp3.0\Microsoft.Web.WebView2.Core.dll._
![NuGet](https://github.com/microsoft/microsoft-ui-xaml/assets/7090613/b4f3dfa7-1cd4-4508-96b7-df6242a8d90c)

I guess the first assembly is the dependency for Microsoft.UI.Xaml.Controls in my self-contained app. The second, a transitive dependency from some other nuget. These two files are quite different. The nuget is much older and seems to be just a wrapper. The Msix... I don't know, is more recent but is too small to be the whole browser.

The thing is, my application fails when trying to initialize the browser using the Msix dll. I get **System.Runtime.InteropServices.COMException (0x8007007F): No se encontró el proceso especificado**. (Couldn't find specified process, if the spanish translation is accurate).

The regular debug & release versions are using the other version, and sucesfully initialize.

I'm now looking for a workaround, but **just by manually replacing the webview assemblies, my self-contained app works,** but I guess it's no longer self-contained, since it relies on the system WebView2.

**Comment by agat366** [comment] 2024-01-15 14:56
One more "great" example of how "out-of-the-box" Windows native development stuff mentioned on the [official Learn page](https://learn.microsoft.com/en-us/microsoft-edge/webview2/get-started/winui#step-4---add-a-webview2-control) just doesn't work!
From MS with "love" to its native devs!.. (as with a lot of other similar stuff)
#letsgoapple

**Comment by AMArostegui** [comment] 2024-01-20 18:19
Hi @llongley , can you link to the related issue?

**Comment by codendone** [comment] 2024-01-21 23:17
Reopening. The duplicate was an [internal issue](http://task.ms/43683926). I've relinked to that issue.

**Comment by WINMAN174** [comment] 2024-02-23 02:24
I can't believe this is still open.  Am I missing something? 

Found a way around it or at least for WINUI. 

Don't use the control directly in XAML. Use a ContentControl in XAML then instantiate the WebView2 control in code and set the ContentControl.Content to the WebView2 control. 

Cheers guys. Don't let the AI bite you.

**Comment by baskren** [comment] 2024-02-23 12:44
FWIW: The only way I've found to work around this was [this approach by @christianfo](https://github.com/unoplatform/uno/issues/14555#issuecomment-1876175425).  @asklar, @codendone, and @llongley: does [@christianfo](https://github.com/christianfo)'s work around help point to a root cause?

**Comment by Ccarmichael92** [comment] 2024-03-11 04:10
I have been using this method for almost 2 years. I figured it out after getting extremely frustrated none of the other methods would work for me for winui3 app. And I am using a webview2 instance as a pdf reader. 

Open up obj/project.assets.json and delete any reference to webview2 where it is the key in a key:value pair. For example if webview2. Is referenced within another package you can leave if. But delete all the top level webview2 instances in entire file. Or just delete all instances of it, it will still work. Just ensure you keep the json intact.  Then just build and run.

Have to redo this anytime major xaml changes are made. I was going to write a CL all to do automatically but hasn’t been enough of an annoyance yet.

**Comment by zadjii** [comment] 2024-04-21 12:29
@Scottj1s Should we x-ref or dedupe this with https://github.com/microsoft/WindowsAppSDK/issues/4249? or some other offshoot of https://github.com/microsoft/WindowsAppSDK/issues/1856#issuecomment-1996050794

**Comment by ancker1** [comment] 2024-04-30 10:52
> I have been using this method for almost 2 years. I figured it out after getting extremely frustrated none of the other methods would work for me for winui3 app. And I am using a webview2 instance as a pdf reader.
> 
> Open up obj/project.assets.json and delete any reference to webview2 where it is the key in a key:value pair. For example if webview2. Is referenced within another package you can leave if. But delete all the top level webview2 instances in entire file. Or just delete all instances of it, it will still work. Just ensure you keep the json intact. Then just build and run.
> 
> Have to redo this anytime major xaml changes are made. I was going to write a CL all to do automatically but hasn’t been enough of an annoyance yet.

This is the only working workaround I have encountered.

**Comment by ancker1** [comment] 2024-05-03 09:14
> > I have been using this method for almost 2 years. I figured it out after getting extremely frustrated none of the other methods would work for me for winui3 app. And I am using a webview2 instance as a pdf reader.
> > Open up obj/project.assets.json and delete any reference to webview2 where it is the key in a key:value pair. For example if webview2. Is referenced within another package you can leave if. But delete all the top level webview2 instances in entire file. Or just delete all instances of it, it will still work. Just ensure you keep the json intact. Then just build and run.
> > Have to redo this anytime major xaml changes are made. I was going to write a CL all to do automatically but hasn’t been enough of an annoyance yet.
> 
> This is the only working workaround I have encountered.

If you are using WebView2 in xaml you will still get an error. See here for a fix: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3583#issuecomment-2092606633

**Closed** 2024-07-02 07:06 UTC
Labels: area-WebView, team-Rendering, product-winui3, closed-Fixed

**Comment by codendone** [comment] 2024-07-03 17:30
This is fixed in [1.6.240701003-experimental2](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.6.240701003-experimental2).

**Comment by zpfzhang** [comment] 2024-10-15 01:20
I fixed this issue by install Microsoft.WindowsAppSDK 1.6.240923002(should work higher than  1.6.240701003-experimental2). hope helpful for others.

**Comment by WINMAN174** [comment] 2024-10-15 01:43
Thanks guys!. Check it out. TradingView lightweight charts integrated. Sick.

![Image](https://github.com/user-attachments/assets/a7689ebe-b304-4dcf-aa87-398581000cf8)
