### ISSUE TITLE
Grid RowDefinitions/ColumnDefinitions breaks hot reload in VS 2022

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6371] opened 2021-11-23 17:49 UTC
### Describe the bug

This might be related to #6370 but since this is another aspect of the break, filing separately

### Steps to reproduce the bug

```xml
<Grid RowDefinitions="123,*">
...
</Grid>
``` 

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Windows version

Insider Build (xxxxx)

**Comment by wbokkers** [comment] 2021-11-24 19:01
I reported this already here: https://github.com/microsoft/microsoft-ui-xaml/issues/5944

**Comment by HEIC-to-JPEG-Dev** [comment] 2022-05-20 04:46
This means that there is effectively no visual editor for WinUI if you use this XAML as VS doesn't have one, and hot reload doesn't work as it doesn't recognise the XAML if any part is modified.

**Comment by sbaeumlisberger** [comment] 2023-07-30 12:47
The problem still exists with Windows App SDK 1.3

**Comment by JesseCol** [comment] 2023-12-15 05:44
As wbokkers says, looks like a dupe of #5944 , closing.

**Closed by JesseCol** 2023-12-15 05:44 UTC
Labels: bug, area-Commanding, team-Markup, product-winui3
