### ISSUE TITLE
TreeView: Binding and Expanding

### ISSUE THREAD

**Issue by cubed-it** [microsoft/microsoft-ui-xaml#164] opened 2019-01-09 08:58 UTC
**Describe the bug**
If I use data binding to create a TreeView control I am not able to expand any of the items. It does crash immediately with an an access violation.

**Steps to reproduce the bug**
Just copy the given example and adjust namespace https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/tree-view#tree-view-using-data-binding

**Expected behavior**
Root item should expand its children.

**Screenshots**
-/-

**Version Info**
Microsoft.UI.Xaml 2.0.181018003.1

Windows 10 version:
- [x] April 2018 Update (17134)

Device form factor:
- [x] Desktop

**Additional context**
-/-

**Comment by YuliKl** [comment] 2019-01-09 18:19
@cubed-it - Can you share your project? I understand you're just copying sample code from the documentation, but we believe that sample works correctly. Your project would help us reproduce the issue.

**Comment by cubed-it** [comment] 2019-01-10 18:09
Hey @YuliKl,
thanks for the feedback. This is very interesting indeed and would be nice, because I would realy like to use the control with bindings. ;) However I don't have the project at hand right now, but I get back to you asap!

**Comment by chingucoding** [comment] 2019-09-18 09:39
With MUX version 2.2.190830001, the issue is not reproducable anymore, so my guess is that it was fixed some point. 
@jevansaks I think we can close this issue.

**Comment by kaiguo** [comment] 2019-09-30 18:37
Yeah I just verified with the latest stable 2.2.190917002, the sample project worked fine. @cubed-it if you are still seeing the issue, feel free to reopen.

**Closed by kaiguo** 2019-09-30 18:37 UTC
Labels: area-TreeView, bug
