### ISSUE TITLE
SetLayeredWindowAttributes with flag LWA_COLORKEY does not work with windows created in WinUI 3 application

### ISSUE THREAD

**Issue by ACGNnsj** [microsoft/microsoft-ui-xaml#8469] opened 2023-05-09 09:27 UTC
### Describe the bug

SetLayeredWindowAttributes with flag LWA_ALPHA works well, while SetLayeredWindowAttributes does not make any color transparent inside any window including the main one.

### Steps to reproduce the bug

Here is my demo project [WinUI3CppWinRTDemo](https://github.com/ACGNnsj/WinUI3CppWinRTDemo).
Most of the associated codes are in [MainWindow.xaml.cpp](https://github.com/ACGNnsj/WinUI3CppWinRTDemo/blob/master/OCR/MainWindow.xaml.cpp) and [WindowHelper.cpp](https://github.com/ACGNnsj/WinUI3CppWinRTDemo/blob/master/OCR/WindowHelper.cpp).

### NuGet package version

WinUI 3 - Windows App SDK 1.3.0: 1.3.230331000

### Windows version

Windows Insider Build (xxxxx)

**Comment by castorix** [comment] 2023-05-09 09:33
It is because of the background in DirectComposition window which had been added 
(you can see https://github.com/castorix/WinUI3_SwapChainPanel_Layered)

**Comment by ACGNnsj** [comment] 2023-05-09 10:18
> It is because of the background in DirectComposition window which had been added (you can see https://github.com/castorix/WinUI3_SwapChainPanel_Layered)
Thanks for your reply. According to your cue, I find this possibly related to the behaviors of redirection surfaces. Does that mean the only way to achieve my goal is to redraw the window with something like Direct2D and DirectComposition.

**Comment by ACGNnsj** [comment] 2023-05-09 10:19
> It is because of the background in DirectComposition window which had been added (you can see https://github.com/castorix/WinUI3_SwapChainPanel_Layered)

Thanks for your reply. According to your cue, I find this possibly related to the behaviors of redirection surfaces. Does that mean the only way to achieve my goal is to redraw the window with something like Direct2D and DirectComposition.

**Comment by castorix** [comment] 2023-05-09 13:06
> Thanks for your reply. According to your cue, I find this possibly related to the behaviors of redirection surfaces. Does that mean the only way to achieve my goal is to redraw the window with something like Direct2D and DirectComposition.

The purpose is just to hide the Background which covers the window
I used a SwapChainPanel which is simple to use but you can also hide the Microsoft.UI.Composition Visual. It can be done with Microsoft.UI.Content.ContentIsland (Microsoft.UI.winmd) but it is marked "Experimental" and it can crash on my OS (Windows 10 22H2, Windows App SDK 1.1.0)

**Comment by tibitoth** [comment] 2023-09-01 18:37
@castorix I've been very deep in the "WinUI 3 / WinAppSDK transparent click through Window" rabbit hole and I've just found your sample which is really great, only on thing not working right now which I cannot figure out why. 

If you set the presenter's `IsAlwaysOnTop` property to `true`. Click through will stop working.

**Comment by codendone** [comment] 2023-09-14 17:55
Closing this issue as by design. As noted above, WinUI renders through the Composition APIs which draw in a separate layer not impacted by the SetLayeredWindowAttributes API.

**Closed by codendone** 2023-09-14 17:55 UTC
Labels: bug, team-CompInput
