### ISSUE TITLE
VS22 - Unable to copy Microsoft.UI.Xaml.winmd

### ISSUE THREAD

**Issue by Swiftpaws** [microsoft/microsoft-ui-xaml#6195] opened 2021-10-29 10:50 UTC
### Describe the bug

When trying to start the application using the packaging project the build process failed saying that it cannot copy from .nuget to the target dir.

Seems to be specific to vs22

Error	MSB3021	Unable to copy file "C:\Users\Danie\.nuget\packages\microsoft.ui.xaml\2.7.0\buildTransitive\..\lib\uap10.0\Microsoft.UI.Xaml.winmd" to "bin\x64\Debug\\Microsoft.UI.Xaml.winmd". The process cannot access the file 'bin\x64\Debug\\Microsoft.UI.Xaml.winmd' because it is being used by another process.	WapProjTemplate1	

### Steps to reproduce the bug

I have created a sample project:
https://github.com/Swiftpaws/microsoft-ui-xaml-vs22-cannotcopyfile

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [X] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Microsoft Visual Studio Community 2022 Preview (64-bit)
Version 17.0.0 Preview 7.0

**Comment by Swiftpaws** [comment] 2021-10-29 20:26
@lhak That seems to be a related issue to https://developercommunity.visualstudio.com/t/visual-studio-2019-version-1610uwpxamarin-runtime/1437211

The workarounds mentioned there will ensure that the app does not crash on launch - <b>but the issue outlined above prevents building the app altogether</b>

**Comment by andersthorsen** [comment] 2021-10-30 16:22
I have the same problem. As a workaround (which has to be reapplied when nuget downloads the file again) I edited
C:\Users\<username>\.nuget\packages\microsoft.ui.xaml\2.8.0-prerelease.210927001\buildTransitive\Microsoft.UI.Xaml.targets and added SkipUnchangedFiles="true"

`<Copy SourceFiles="@(XamlWinmd)" DestinationFiles="@(XamlWinmd -> '$(OutDir)\%(Filename)%(Extension)')" />`

to
`<Copy SourceFiles="@(XamlWinmd)" DestinationFiles="@(XamlWinmd -> '$(OutDir)\%(Filename)%(Extension)')" SkipUnchangedFiles="true" />`

**Comment by StephenLPeters** [comment] 2021-11-04 22:33
potential duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6190?

**Comment by lhak** [comment] 2021-11-05 08:23
@Swiftpaws At least in my case the linked issue did lead to compile errors (.net native compilation failed due to nuget cache corruption). Adding the ```<AppxUseHardlinksIfPossible>false</AppxUseHardlinksIfPossible>``` property to the wap project file fixed this issue (for VS22) and apparently also avoids the issue discussed here.

**Closed** 2023-08-03 22:46 UTC
Labels: team-Markup, product-winui2, no-issue-activity
