### ISSUE TITLE
Immediate crash on launch

### ISSUE THREAD

**Issue by wjk** [microsoft/microsoft-ui-xaml#4023] opened 2021-01-26 17:26 UTC
### Describe the bug
Any WinUI 3/Win32 app I run on my system crashes immediately on launch. In fact, it crashes so quickly that it causes the debugger process (msvsmon) to crash as well! I had to extract the stack trace from the dump file using WinDbg; it is included below.

### Steps to reproduce the bug
1. Install Windows build 21296. (I believe the problems started at about the time that this build was installed, so it may be Windows that’s at fault.)
2. Build [this solution](https://github.com/microsoft/WinUI-3-Demos/tree/master/src/Build2020Demo/DemoBuildCs).
3. Deploy and run the application.
4. Observe the crash.

### Expected behavior

No crash!

### Version Info

* Windows 10 Insider Preview build 21296
* Desktop form factor
* WinUI package version 3.0.0-preview3.201113.0
* `dotnet --info` included below.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21296)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |   |
| May 2019 Update (18362)            | |
| October 2018 Update (17763)        | |
| April 2018 Update (17134)          | |
| Fall Creators Update (16299)       | |
| Creators Update (15063)            | |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | |
| Surface Hub        | |
| IoT                | |

### Stack trace

```
 # Child-SP          RetAddr               Call Site
00 00000065`3a97d760 00007ffa`985ceed9     KERNELBASE!RaiseFailFastException+0x15c
01 00000065`3a97dd40 00007ffa`32b0b078     combase!RoFailFastWithErrorContextInternal2+0x559 [onecore\com\combase\winrt\error\error.cpp @ 1468] 
02 00000065`3a97df70 00007ffa`32b0ae74     Microsoft_Internal_FrameworkUdk!<lambda_d4a7b0d89668b5ef671d72f8766fe68b>::operator()+0x1b8
03 00000065`3a97e010 00007ffa`32b15088     Microsoft_Internal_FrameworkUdk!GetPlatformFunctions+0x64
04 00000065`3a97e050 00007ffa`32b15c88     Microsoft_Internal_FrameworkUdk!Microsoft::Internal::FrameworkUdk::CoreMessagingProxy::Register+0x38
05 00000065`3a97e160 00007ffa`32b189f6     Microsoft_Internal_FrameworkUdk!VisualDiagnosticsPort_Register_Impl+0x58
06 00000065`3a97e1c0 00007ffa`2e13ce27     Microsoft_Internal_FrameworkUdk!VisualDiagnosticsPort_Register+0x86
07 00000065`3a97e210 00007ffa`2e13cd7c     Microsoft_UI_Xaml!DirectUI::DXamlCore::RegisterVisualDiagnosticsPort+0x67 [C:\a\1\s\dxaml\xcp\dxaml\lib\DXamlCore.cpp @ 2702] 
08 00000065`3a97e250 00007ffa`2e13bec8     Microsoft_UI_Xaml!DirectUI::DXamlCore::InitializeInstance+0x260 [C:\a\1\s\dxaml\xcp\dxaml\lib\DXamlCore.cpp @ 436] 
09 00000065`3a97e2a0 00007ffa`2e50beb0     Microsoft_UI_Xaml!DirectUI::DXamlCore::InitializeImpl+0xb0 [C:\a\1\s\dxaml\xcp\dxaml\lib\DXamlCore.cpp @ 2654] 
0a (Inline Function) --------`--------     Microsoft_UI_Xaml!DirectUI::DXamlCore::Initialize+0x22 [C:\a\1\s\dxaml\xcp\dxaml\lib\DXamlCore.cpp @ 2739] 
0b 00000065`3a97e2f0 00007ffa`2e35dda9     Microsoft_UI_Xaml!DirectUI::FrameworkApplication::StartDesktop+0x54 [C:\a\1\s\dxaml\xcp\dxaml\lib\FrameworkApplication_Partial.cpp @ 183] 
0c (Inline Function) --------`--------     Microsoft_UI_Xaml!DirectUI::FrameworkApplicationFactory::StartImpl+0x131aef [C:\a\1\s\dxaml\xcp\dxaml\lib\FrameworkApplication_Partial.cpp @ 163] 
0d 00000065`3a97e400 00007ff9`d0c0b17d     Microsoft_UI_Xaml!DirectUI::FrameworkApplicationFactory::Start+0x131b09 [C:\a\1\s\dxaml\xcp\dxaml\lib\winrtgeneratedclasses\FrameworkApplication.g.cpp @ 713] 
0e 00000065`3a97e430 00007ff9`d03995cb     0x00007ff9`d0c0b17d
0f 00000065`3a97e4f0 00007ff9`d0388ad5     0x00007ff9`d03995cb
10 00000065`3a97e570 00007ff9`d03873e2     0x00007ff9`d0388ad5
11 00000065`3a97e5b0 00007ffa`2feea683     0x00007ff9`d03873e2
12 00000065`3a97e600 00007ffa`2fe22fcc     coreclr!CallDescrWorkerInternal+0x83 [F:\workspace\_work\1\s\src\coreclr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 100] 
13 00000065`3a97e640 00007ffa`2fe422b3     coreclr!MethodDescCallSite::CallTargetWorker+0x268 [F:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.cpp @ 552] 
14 (Inline Function) --------`--------     coreclr!MethodDescCallSite::Call+0xb [F:\workspace\_work\1\s\src\coreclr\src\vm\callhelpers.h @ 458] 
15 00000065`3a97e780 00007ffa`2fe4207e     coreclr!RunMainInternal+0x11f [F:\workspace\_work\1\s\src\coreclr\src\vm\assembly.cpp @ 1465] 
16 00000065`3a97e8b0 00007ffa`2fe41be1     coreclr!RunMain+0xd2 [F:\workspace\_work\1\s\src\coreclr\src\vm\assembly.cpp @ 1536] 
17 00000065`3a97e960 00007ffa`2fe41908     coreclr!Assembly::ExecuteMainMethod+0x1cd [F:\workspace\_work\1\s\src\coreclr\src\vm\assembly.cpp @ 1648] 
18 00000065`3a97ecf0 00007ffa`2fe09ad2     coreclr!CorHost2::ExecuteAssembly+0x1c8 [F:\workspace\_work\1\s\src\coreclr\src\vm\corhost.cpp @ 384] 
19 00000065`3a97ee60 00007ffa`32be2c72     coreclr!coreclr_execute_assembly+0xe2 [F:\workspace\_work\1\s\src\coreclr\src\dlls\mscoree\unixinterface.cpp @ 431] 
1a (Inline Function) --------`--------     hostpolicy!coreclr_t::execute_assembly+0x2b [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\coreclr.cpp @ 89] 
1b 00000065`3a97ef00 00007ffa`32be2ed7     hostpolicy!run_app_for_context+0x3be [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\hostpolicy.cpp @ 246] 
1c 00000065`3a97f090 00007ffa`32be3b6b     hostpolicy!run_app+0x37 [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\hostpolicy.cpp @ 275] 
1d 00000065`3a97f0d0 00007ffa`32c639ea     hostpolicy!corehost_main+0xfb [F:\workspace\_work\1\s\src\installer\corehost\cli\hostpolicy\hostpolicy.cpp @ 408] 
1e 00000065`3a97f290 00007ffa`32c67358     hostfxr!execute_app+0x206 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 146] 
1f (Inline Function) --------`--------     hostfxr!?A0x542acd91::read_config_and_execute+0x10a [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 520] 
20 00000065`3a97f380 00007ffa`32c65b5f     hostfxr!fx_muxer_t::handle_exec_host_command+0x214 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 1001] 
21 00000065`3a97f470 00007ffa`32c62029     hostfxr!fx_muxer_t::execute+0x39b [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\fx_muxer.cpp @ 566] 
22 00000065`3a97f5b0 00007ff6`7f0de090     hostfxr!hostfxr_main_startupinfo+0x89 [F:\workspace\_work\1\s\src\installer\corehost\cli\fxr\hostfxr.cpp @ 50] 
23 00000065`3a97f6b0 00007ff6`7f0de3f8     OpenDeployKit_Shell_exe!exe_start+0x620 [F:\workspace\_work\1\s\src\installer\corehost\corehost.cpp @ 236] 
24 00000065`3a97f890 00007ff6`7f0dfee8     OpenDeployKit_Shell_exe!wmain+0x124 [F:\workspace\_work\1\s\src\installer\corehost\corehost.cpp @ 302] 
25 (Inline Function) --------`--------     OpenDeployKit_Shell_exe!invoke_main+0x22 [D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
26 00000065`3a97fa00 00007ffa`97b653fe     OpenDeployKit_Shell_exe!__scrt_common_main_seh+0x10c [D:\agent\_work\9\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
27 00000065`3a97fa40 00007ffa`98d75a7b     kernel32!BaseThreadInitThunk+0x1e
28 00000065`3a97fa70 00000000`00000000     ntdll!RtlUserThreadStart+0x2b
```

### `dotnet --info`

```
.NET SDK (reflecting any global.json):
 Version:   5.0.200-preview.20614.14
 Commit:    863605c8c3

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.21296
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.200-preview.20614.14\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.0.100 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.200-preview.20614.14 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by huoyaoyuan** [comment] 2021-01-26 17:48
Duplicate of #3954

**Comment by ranjeshj** [comment] 2021-01-27 00:33
@wjk closing this issue since this is a dup.

**Closed by ranjeshj** 2021-01-27 00:33 UTC
Labels: needs-triage
