### ISSUE TITLE
nullptr exception in ListView with grouped view when DragOver

### ISSUE THREAD

**Issue by sarosigy** [microsoft/microsoft-ui-xaml#6484] opened 2021-12-16 13:42 UTC
### Describe the bug

When dragging an item onto a ListView which is grouped, and the mouse movement would cause a scroll, exception raises:

Exception thrown: read access violation.
**pDirectManipulationService** was nullptr.

Windows.UI.Xaml.dll!CInputServices::InitializeDirectManipulationViewportValues(CDMViewport * pViewport, IPALDirectManipulationService * pDirectManipulationService, float initialTranslationX, float initialTranslationY, float initialZoomFactor) Line 6852
	at onecoreuap\windows\dxaml\xcp\core\input\inputservices.cpp(6852)
Windows.UI.Xaml.dll!CInputServices::SetConstantVelocities(CUIElement * pDMContainer, CUIElement * pManipulatedElement, float panXVelocity, float panYVelocity) Line 9560
	at onecoreuap\windows\dxaml\xcp\core\input\inputservices.cpp(9560)
Windows.UI.Xaml.dll!CUIDMContainerHandler::SetConstantVelocities(CUIElement * pManipulatedElement, float panXVelocity, float panYVelocity) Line 466
	at onecoreuap\windows\dxaml\xcp\core\optional\elements\touch\uidmcontainerhandler.cpp(466)
Windows.UI.Xaml.dll!ManipulationHandler_SetConstantVelocities(void * hManipulationHandler, CUIElement * pManipulatedElement, float panXVelocity, float panYVelocity) Line 4499
	at onecoreuap\windows\dxaml\xcp\core\dll\pinvokes.cpp(4499)
Windows.UI.Xaml.dll!DirectUI::ScrollViewer::SetConstantVelocities(float dx, float dy) Line 9100
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\scrollviewer_partial.cpp(9100)
Windows.UI.Xaml.dll!DirectUI::ListViewBase::ScrollWithVelocity(DirectUI::ListViewBase::PanVelocity velocity) Line 2133
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\listviewbase_partial_reorder.cpp(2133)
Windows.UI.Xaml.dll!DirectUI::ListViewBase::StartEdgeScrollTimerTick(IInspectable * pUnused1, IInspectable * pUnused2) Line 2197
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\listviewbase_partial_reorder.cpp(2197)
Windows.UI.Xaml.dll!DirectUI::ClassMemberEventHandler<DirectUI::ListViewBase,Windows::UI::Xaml::Controls::IListViewBase,Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::Invoke(IInspectable * pSender, IInspectable * pArgs) Line 663
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\JoltClasses.h(663)
Windows.UI.Xaml.dll!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::Raise(IInspectable * pSource, IInspectable * pArgs) Line 275
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\JoltClasses.h(275)
Windows.UI.Xaml.dll!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,Windows::Foundation::IEventHandler<IInspectable *>,IInspectable,IInspectable>::UntypedRaise(IInspectable * pSource, IInspectable * pArgs) Line 248
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\JoltClasses.h(248)
Windows.UI.Xaml.dll!DirectUI::DependencyObject::FireEvent(KnownEventIndex nEventId, IInspectable * pSender, IInspectable * pArgs) Line 3502
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\dependencyobject.cpp(3502)
[Inline Frame] Windows.UI.Xaml.dll!DirectUI::DXamlCore::FireEvent(CDependencyObject *) Line 1978
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp(1978)
[Inline Frame] Windows.UI.Xaml.dll!AgCoreCallbacks::FireEvent(CDependencyObject *) Line 92
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\fxcallbacks.cpp(92)
[Inline Frame] Windows.UI.Xaml.dll!CFxCallbacks::JoltHelper_FireEvent(CDependencyObject *) Line 1015
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\fxcallbacks.cpp(1015)
Windows.UI.Xaml.dll!CCoreServices::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 3229
	at onecoreuap\windows\dxaml\xcp\core\dll\xcpcore.cpp(3229)
Windows.UI.Xaml.dll!CommonBrowserHost::CLR_FireEvent(CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, unsigned int flags) Line 771
	at onecoreuap\windows\dxaml\xcp\control\common\shared\CommonBrowserHost.hpp(771)
Windows.UI.Xaml.dll!CControlBase::ScriptCallback(void * pControl, CDependencyObject * pListener, EventHandle hEvent, CDependencyObject * pSender, CEventArgs * pArgs, int flags, IScriptObject * pScriptObject, HRESULT(*)(CDependencyObject *, CEventArgs *) pInternalHandler) Line 267
	at onecoreuap\windows\dxaml\xcp\control\common\shared\controlbase.cpp(267)
Windows.UI.Xaml.dll!CXcpDispatcher::OnScriptCallback(CEventInfo * pEventInfo) Line 1347
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(1347)
Windows.UI.Xaml.dll!CXcpDispatcher::OnWindowMessage(HWND__ * msg, unsigned int wParam, unsigned __int64 lParam, __int64) Line 1189
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(1189)
Windows.UI.Xaml.dll!CXcpDispatcher::ProcessMessage(HWND__ * msg, unsigned int wParam, unsigned __int64 lParam, __int64 plRet, __int64 * pbDoDefault, unsigned int *) Line 925
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(925)
Windows.UI.Xaml.dll!CXcpDispatcher::WindowProc(HWND__ * hwnd, unsigned int msg, unsigned __int64 wParam, __int64 lParam) Line 839
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(839)
Windows.UI.Xaml.dll!CDeferredInvoke::DispatchQueuedMessage(bool * dispatchedWork, bool * hasMoreWork) Line 301
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(301)
[Inline Frame] Windows.UI.Xaml.dll!CXcpDispatcher::MessageTimerCallback() Line 1534
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(1534)
Windows.UI.Xaml.dll!CXcpDispatcher::MessageTimerCallbackStatic(void * myUserData) Line 1526
	at onecoreuap\windows\dxaml\xcp\win\shared\xcpwindow.cpp(1526)
CoreMessaging.dll!00007ff920de8d50()
CoreMessaging.dll!00007ff920de8ca1()
CoreMessaging.dll!00007ff920de05dc()
CoreMessaging.dll!00007ff920dd9647()
CoreMessaging.dll!00007ff920dd6190()
CoreMessaging.dll!00007ff920dd5e4c()
CoreMessaging.dll!00007ff920dd5bb0()
user32.dll!UserCallWinProcCheckWow()
user32.dll!DispatchClientMessage()
user32.dll!__fnDWORD()
ntdll.dll!KiUserCallbackDispatcherContinue()
win32u.dll!NtUserPeekMessage()
user32.dll!_PeekMessage()
user32.dll!PeekMessageW()
Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessMessage()
Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessagesInternal()
Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents()
Windows.UI.Xaml.dll!CJupiterWindow::RunCoreWindowMessageLoop() Line 1258
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\jupiterwindow.cpp(1258)
[Inline Frame] Windows.UI.Xaml.dll!CJupiterControl::RunMessageLoop() Line 1065
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\jupitercontrol.cpp(1065)
Windows.UI.Xaml.dll!DirectUI::DXamlCore::RunMessageLoop() Line 2532
	at onecoreuap\windows\dxaml\xcp\dxaml\lib\dxamlcore.cpp(2532)
twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run()
twinapi.appcore.dll!<lambda>(void)()
SHCore.dll!_WrapperThreadProc()
kernel32.dll!BaseThreadInitThunk()
ntdll.dll!RtlUserThreadStart()

### Steps to reproduce the bug

1. Clone the repository at https://github.com/sarosigy/ListViewRepro
2. Build and run
3. Drag and Drop a contact to the left side list
4. Drag the contact from the right side list back to left side, but force scrolling the left side grouped ListView by moving the item around the bottom (or top of you previously scrolled down)
5. Optionally observe that the non-grouped ListView behaves as expected, scrolling with no exception

### Expected behavior

Won't throw an ecxeption

### NuGet package version

Microsoft.UI.Xaml 2.7.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Additional context

Windows version not in list.

Source code based on XAML Controls Gallery, which is Copyright (c) Microsoft Corporation. All rights reserved.

**Comment by StephenLPeters** [comment] 2022-03-01 22:13
I think this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6404

**Closed by StephenLPeters** 2022-03-01 22:13 UTC
Labels: area-Lists, team-Controls
