### ISSUE TITLE
Proposal: Add a project template for WinUI 3 class library targeting .NET UWP and .Net Desktop

### ISSUE THREAD

**Issue by mveril** [microsoft/microsoft-ui-xaml#2903] opened 2020-07-14 16:02 UTC
# Proposal: Add a project template for WinUI 3 class library targeting .NET UWP and .NET Desktop 

## Summary

Following a discussion in the last community call #2867 when I ask a question about the process to create a multitarget (targeting .NET UWP and .NET Desktop) WinUI 3 class library .

I think It's may be interesting to make a project template for that.

## Rationale

* WInUI 3 targeting .NET 5 Desktop and .NET Native (and also C++ but it's not the subject here) so .NET class library based on WinUI should do the same thing.

## Scope

| Capability                                                   | Priority |
| :----------------------------------------------------------- | :------- |
| This proposal will allow developers to easily create a UWP/Desktop independent WinUI 3 class library for .NET | Must     |

## Important Notes

- I think this template should use the https://github.com/novotnyllc/MSBuildSdkExtras like @michael-hawker and @stevenbrix suggest to me. Thanks a lot to them.

## Open Questions

I don't know if the .NET 5 Preview 3 SDK already support this multitarget scenario or if https://github.com/novotnyllc/MSBuildSdkExtras  Is still necessary.

**Comment by stevenbrix** [comment] 2020-07-14 16:12
@mveril thanks for filing this issue! This is indeed something I think we should do, especially since it looks like we won't be bringing .NET5 to UWP apps right now.
 
This seems like a dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/1952, so I'm going to close this one out, please go upvote that one! 👍

**Closed by stevenbrix** 2020-07-14 16:12 UTC
Labels: feature proposal, needs-triage
