### ISSUE TITLE
DragUI.SetContentFromSoftwareBitmap() does not show the bitmap

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#4528] opened 2021-03-12 14:55 UTC
When setting the drag bitmap in the DragStarting event handler, the bitmap is not displayed.
To set the bitmap, I use args.DragUI.SetContentFromSoftwareBitmap(...)

**Steps to reproduce the bug**
1. Add an event handler to a DragStarting event
2. Create a software bitmap
3. Set the bitmap using DragUI.SetContentFromSoftwareBitmap()
4. The bitmap does not show up.

**Expected behavior**
The bitmap should be visible

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion 0.5.0-prerelease

 Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            |  Yes   |

**Comment by jschwizer99** [comment] 2021-03-17 07:53
I observe the same problem with `args.DragUI().SetContentFromBitmapImage(bitmap)`. I also do not see the image. When just calling `args.DragUI()` a paper sheet is shown.

**Comment by jschwizer99** [comment] 2021-03-17 08:51
This issue could be related to #4545 as I indeed see the bitmap icon if #4545 works on a platform reliable.

**Comment by codendone** [comment] 2021-03-18 03:09
I believe @jschwizer99 is correct that this is the same as #4545. The comment I just added to that one:

> We just debugged this issue last week. This is unfortunately a bug in Windows specific to non-UWP apps. It isn't clear right now if we can fix this in WinUI3. On the plus side, this has been fixed in Windows, and is available in current Dev Channel builds from the Windows Insider Program.

In theory it is possible to avoid the issue if you can avoid any awaits (and taking a deferral) in your DragStarting handler. But that likely isn't reasonable for most uses to already have the bitmap ready.

**Comment by wbokkers** [comment] 2021-03-18 09:00
@codendone Will the window fix also be applied to older Windows versions? WinUI Desktop is supposed to work on older Windows versions as well.

**Comment by codendone** [comment] 2021-03-19 05:40
Backporting will be considered, but I can't guess whether it will be considered, or how far it might be backported.

**Comment by wbokkers** [comment] 2021-05-28 09:57
ProjectReunion 0.8.0-preview regresses even more. Even the default drag UI bitmap never shows up. This was working 1 out of 5 times in Reunion 0.5.7.  Overriding the bitmap still does not work.

And I still get random crashes while dragging: 0xC000027B: An application-internal exception has occurred

**Comment by codendone** [comment] 2021-09-02 16:57
The OS fix for this issue went live on Windows Update over the last month, so fully updated machines should no longer experience this issue.

**Closed by codendone** 2021-09-02 16:57 UTC
Labels: area-Images, needs-triage, team-Rendering, product-winui3, appModel-win32

**Comment by sudongg** [comment] 2022-06-25 09:47
The problem is easily triggered when I use StartDragAsync .
I'm confused by "This is unfortunately a bug in Windows specific to non-UWP apps" because I don't have this problem on other UI frameworks (like Google Chrome)
I would like to know if there is any workaround for this issue currently in older versions?

**Comment by stevenbrix** [comment] 2024-07-22 21:15
@codendone this seems to still be happening on windows 11 so it seems that the OS fix from a few years ago wasn't enough?
