### ISSUE TITLE
ItemsRepeater template crashes when using x:Phase, and set x:Phase > 0

### ISSUE THREAD

**Issue by hupo376787** [microsoft/microsoft-ui-xaml#1600] opened 2019-11-12 02:33 UTC
**Describe the bug**
I used x:Phase in ItemsRepeater data template. When set x:Phase = 0, app runs well.
But when set x:Phase = 1, then the app crashes every time staring, and throws exception `Access violation`.

**Steps to reproduce the bug**

Go to MovieTemplate, change Image's phase to 1
`<Image x:Phase = "1"/>`
Run app.

**Expected behavior**
App runs well and show the normal home page.

**Version Info**

Win: 18362.418

**NuGet package version:**

Microsoft.UI.Xaml: 2.2.190917002

**Additional context**
Here is a small [repo](https://github.com/hupo376787/ItemsRepeater-throws-System.InvalidCastException-when-using-converter), and special thanks to @XamlBrewer's repo.

**Comment by ranjeshj** [comment] 2019-11-12 18:29
If you have both phase 0 and phase 1 in the template does it work ?

**Comment by ranjeshj** [comment] 2019-11-12 20:35
This seems to be the same issue as 
https://github.com/dotnet/coreclr/issues/22324

A possible workaround is to enable compilation for .net native. In project properties, go to Build section and check the "Compile with .Net Native tool chain"

**Comment by hupo376787** [comment] 2019-11-13 06:33
If set phase both 0 and 1, it also crashes.

And thanks for the workaround, it works : )

**Comment by ranjeshj** [comment] 2019-11-13 18:32
I've created a new .net core bug to follow up https://github.com/dotnet/coreclr/issues/27860 since the old one was closed. Resolving this bug as closed since this is not a bug in Microsoft.ui.xaml.

**Closed by ranjeshj** 2019-11-13 18:32 UTC
Labels: area-ItemsRepeater, bug, needs-assignee-attention, team-Controls
