### ISSUE TITLE
Nested ObservableCollection crashes when removing item

### ISSUE THREAD

**Issue by WillyWoe** [microsoft/microsoft-ui-xaml#9868] opened 2024-08-01 19:38 UTC
### Describe the bug

When removing an item in a nested ObservableCollection, tha app crashes with System.ArgumentOutOfRangeException: 'This collection cannot work with indices larger than Int32.MaxValue - 1 (0x7FFFFFFF - 1). (Parameter 'index')'

I attached a small example that reproduces the bug
[Example.zip](https://github.com/user-attachments/files/16461060/Example.zip)

the example consists of 2 ItemsView, one represents the headers and the second represents the details of the selected header.

### Steps to reproduce the bug

1. Click on Add Header
2. Select Header 0
3. Click on Add Detail
4. Click on Add Detail again
5. Select Detail 1
6. Click on Remove Detail
7. Select Detail 0
8. Click on Remove Detail
9. App crashes

https://github.com/user-attachments/assets/e4df17e2-9260-4336-bfb6-1a04c1cd54e8

### Expected behavior

App does not crash when an item is removed

### NuGet package version

WinUI 3 - Windows App SDK 1.5.5: 1.5.240627000

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (20H2): Build 19042

**Comment by codendone** [comment] 2024-08-29 03:52
This was closed as duplicate of an internal bug. Reactivating and connecting to that bug.

**Closed** 2024-09-11 07:11 UTC
Labels: bug, area-Lists, team-Controls, closed-Fixed

**Comment by bluelaze** [comment] 2025-02-13 16:40
it also in 1.7-preview1，reproduce: click button1 add item1, click button2 to add item2 and remove item1 in code, will crash.

![Image](https://github.com/user-attachments/assets/27e739d7-5b6b-47d8-b92f-ea3585e2b310)
