### ISSUE TITLE
ListView with Single selection mode can have two selected items.

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#9692] opened 2024-06-04 10:58 UTC
### Describe the bug

When reordering the items of a `ListView` with `SelectionMode=Single` we can end with two selected items

### Steps to reproduce the bug

1. In a blank WinAppSDK+WinUI3 app add the following code:

 ```xaml
<ListView
      AllowDrop="True"
      CanDragItems="True"
      CanReorderItems="True"
      IsItemClickEnabled="True"
      IsSwipeEnabled="True"
      DragEnter="OnDragEnter"
      DragLeave="OnDragLeave"
      ItemClick="OnItemClick"
      ItemsSource="{x:Bind Items, Mode=OneWay}"
      ReorderMode="Enabled"
      SelectionMode="Single"
      SingleSelectionFollowsFocus="False">
      <ListView.Footer>
          <Border BorderBrush="{ThemeResource TextBoxBorderThemeBrush}" BorderThickness="0,1,0,0">
              <TextBlock x:Name="output" />
          </Border>
      </ListView.Footer>
</ListView>
```
2. Run the application
3. Drag one item from the bottom of the list to the middle
4. Drag another item from the bottom of the list above the selected item

### Current behavior
We now have two selected items in the list

### Expected behavior

The list should always have a single selected item

### Screenshots

![WinUI3 - listview reorder bug](https://github.com/microsoft/microsoft-ui-xaml/assets/20152272/a4fc3c40-88d8-4d99-ad29-24be5afc42e3)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.3: 1.5.240428000

**Comment by codendone** [comment] 2024-06-07 18:33
This looks like a duplicate of #8271.

**Closed by codendone** 2024-06-07 18:33 UTC
Labels: bug, needs-triage
