### ISSUE TITLE
Cannot use ScrollViewer in UWP project

### ISSUE THREAD

**Issue by Berrysoft** [Microsoft/microsoft-ui-xaml#594] opened 2019-04-20 04:07 UTC
**Describe the bug**
Failed to assign to property 'Microsoft.UI.Xaml.Controls.Primitives.Scroller.IgnoredInputKind'. [Line: 1710 Position: 777]

**Steps to reproduce the bug**
Add Microsoft.UI.Xaml NuGet package 2.2 preview, and simply add a ScrollViewer to the page. Run the project, and it crashes with the exception above.

**Expected behavior**
Nothing wrong happens.

**Version Info**
Windows version: 10.0.18362.53
NuGet package version: 
Microsoft.NETCore.UniversalWindowsPlatform 6.2.8
Microsoft.UI.Xaml 2.2.190416008-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362)                   | Yes   |
| October 2018 Update (17763)   |    |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Comment by micahl** [comment] 2019-04-20 06:00
@Berrysoft, we ran into this internally as well and determined that 1) it happens in Debug builds and 2) is caused by a bug in the markup compiler that was fixed and should be available in the [latest Win 10 SDK](https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk).  I don't believe you have to retarget your project and that you just need to have the latest SDK.  Can you confirm that you're only hitting this on Debug builds?  And do you have the latest SDK installed?

**Comment by Berrysoft** [comment] 2019-04-20 06:55
@micahl Yes, you're right. I was somehow too impatient. Now I have installed the latest SDK and it works very well.😄

**Comment by micahl** [comment] 2019-04-20 06:59
@Berrysoft thanks for confirming!  Closing this issue.

**Closed by micahl** 2019-04-20 06:59 UTC
Labels: area-Scrolling, bug
