### ISSUE TITLE
There is no upper border accent color at the window on Windows 10

### ISSUE THREAD

**Issue by 4OTbIPE** [microsoft/microsoft-ui-xaml#9923] opened 2024-08-25 08:50 UTC
### Describe the bug

If you enable the display of accent color on window borders in Windows settings, then there is no upper border in Winapi 3 applications. 

### Steps to reproduce the bug

1. Enable the display of accent color on window borders in Windows settings
2. Open any WinUI3 app

### Expected behavior

The accent color on the upper border of the window is displayed correctly

### Screenshots

![image](https://github.com/user-attachments/assets/03b5a75a-b0b7-474e-802a-91d5efae4478)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.6: 1.5.240802000

### Windows version

Windows 10 (21H2): Build 19044, Windows 10 (21H1): Build 19043, Windows 10 (20H2): Build 19042, Windows 10 (1809): Build 17763

### Additional context

Only on Windows 10

**Comment by HO-COOH** [comment] 2024-08-27 03:07
Duplicate of #8948

**Comment by codendone** [comment] 2024-08-29 16:37
Closing as duplicate.

**Closed by codendone** 2024-08-29 16:37 UTC
Labels: bug, needs-triage
