### ISSUE TITLE
Double taskbar button showing for a single Window

### ISSUE THREAD

**Issue by chanallenk** [microsoft/microsoft-ui-xaml#4099] opened 2021-02-04 04:15 UTC
**Describe the bug**
When launching any WinUI 3.0 project, there is an extra taskbar button that shows. 

**Steps to reproduce the bug**
1. In Windows 10 settings > Taskbar Settings > Change to never combine taskbar buttons
2. Create a WinUI 3.0 project (Or run the one from the [build 2020 demo](https://github.com/microsoft/WinUI-3-Demos))
3. Run and when window is opened will be two buttons for one window 

**Expected behavior**
Only a single button per window. When window is hidden, no buttons should be visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/47792989/106844021-51c7b900-665c-11eb-8c03-7bfd3c52096f.png)

**Version Info**
Microsoft Win UI 3.0.0-preview3.201113.0
Microsoft Visual Studio Professional 2019 v16.9.0 Preview 2

NuGet package version: 
Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
Only tried on Win32 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            |   Yes    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
I believe what's happening is one button is created for when the App is launched, and another button is created for the MainWindow. When I removed all code for opening a MainWindow, there is still a phantom taskbar button that is created when the project is launched

**Comment by huoyaoyuan** [comment] 2021-02-04 09:44
Duplicate of #3698

**Comment by marb2000** [comment] 2021-02-05 23:45
Thanks @huoyaoyuan Closing for dupe. Also, this is solved in the next Preview 4.

**Closed by marb2000** 2021-02-05 23:45 UTC
Labels: duplicate
