### ISSUE TITLE
Calendar control lacks tooltips

### ISSUE THREAD

**Issue by paulcam206** [microsoft/microsoft-ui-xaml#2870] opened 2020-07-08 19:42 UTC
**Describe the bug**
Per accessibility guidelines (MAS 1.3.3), controls like the next/previous buttons in the `CalendarDatePicker` control should have accessible tooltips (see OS bug #23713353)

**Steps to reproduce the bug**
1. Invoke calendar date picker 
2. Hover mouse over previous/next buttons

**Expected behavior**
Tooltip should appear saying something along the lines of "Previous/Next month"

**Screenshots**
![image](https://user-images.githubusercontent.com/16614499/86962521-ea727680-c117-11ea-98eb-7b9a90dc9a9d.png)

**Version Info**

Windows 10 20.04

**Additional context**
This showed up in an accessibility review of microsoft/AdaptiveCards

**Comment by YuliKl** [comment] 2020-10-30 05:19
This issue was opened first, but resolving as a duplicate of #3525

**Closed by YuliKl** 2020-10-30 05:19 UTC
Labels: accessibility, area-DateTimePickers, duplicate, needs-winui-3, team-Controls
