### ISSUE TITLE
[16.11][WinUI] Single-project MSIX projects don't have Package and Publish option in Context menu

### ISSUE THREAD

**Issue by XamlTest** [microsoft/microsoft-ui-xaml#7999] opened 2022-12-08 10:36 UTC
### Describe the bug

In VS 16.11.21, there is no Package and Publish option on WinUI 3 project.

### Steps to reproduce the bug

1. Open VS 16.11.21
2. Create a Blank App, Packaged (WinUI 3 in Desktop) project
3. Right click theproject node to show the context menu
4. Check if there is Package and Publish option

**Actual Result:** No Package and Publish option, even if reopen VS or reopen project.

### Expected behavior

There should show Package and Publish option.

### Screenshots

![image](https://user-images.githubusercontent.com/97647558/206424833-f9621c9c-a542-4461-8a41-53741bed1319.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.5

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

TargetFramework: net5.0-windows10.0.19041.0
Nuget package version: WinUI3 - Windows App SDK 1.1.4 or 1.1.5

**Comment by bpulliam** [comment] 2022-12-08 17:21
Related/duplicate of #7928

**Closed by bpulliam** 2022-12-08 17:21 UTC
Labels: bug, needs-triage
