### ISSUE TITLE
NavView and Alt + Left KeyBoardAccelerators

### ISSUE THREAD

**Issue by sibille** [microsoft/microsoft-ui-xaml#8] opened 2018-10-17 08:57 UTC
We're having an issue with WinUI NavView and the Alt + Left KeyboardAccelerator. 
Initially we added the KeyboardAccelerator in the page constructor (following guidance from 
https://docs.microsoft.com/en-us/windows/uwp/design/basics/navigation-history-and-backwards-navigation), but doing this the "Alt + Left" Tooltip is showing all over the app. 

We saw in your samples (https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview#code-example) that you are adding the accelerator in the NavView Loaded event handler. Moving the code here results in not showing the tooltip. 

Is NavView_Loaded or Page_Loaded the correct place to add KeyboardAccelerators? 

Working on this we also noticed that the NavView BackButton does not have a tooltip. Should this tooltip de provided out of the box (like the Hamburger Button does) or are we missing something?

I'll attach a generated app so you can see what we are generating. 
[NavViewTooltip.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2486550/NavViewTooltip.zip)

Tracking issue on our side is https://github.com/Microsoft/WindowsTemplateStudio/issues/2650

**Comment by jevansaks** [comment] 2018-11-06 18:32
Filed on engineering team ([Internal tracking link](https://microsoft.visualstudio.com/OS/_workitems/edit/19329887))

**Comment by jevansaks** [comment] 2018-11-06 18:37
Leaving as open until we have closure on the internal side of things.

**Comment by chingucoding** [comment] 2020-08-20 16:36
@ranjeshj @jevansaks Can we close this issue now? The corresponding issue over at WindowsTemplateStudio has been closed and it sounds like the fix for this was already added back then.

**Comment by jevansaks** [comment] 2020-08-20 18:15
No objections from me.

**Comment by mvegaca** [comment] 2021-02-17 11:51
Hi

Adding keyboardAccelerators to WinUI 3 Preview 4 Templates in WindowsTemplateStudio I've verified that this tooltip issue still happens.

**Comment by StephenLPeters** [comment] 2021-02-19 01:05
@jevansaks or @chingucoding do you remember this one?

**Comment by chingucoding** [comment] 2021-02-19 18:42
Could it be that there is a regression in WindowsTemplateStudio for the preview4 version? Or is the Preview 4 NavView different from the WinUI 2 one?

**Comment by StephenLPeters** [comment] 2021-02-20 00:30
@sibille FYI

**Comment by jevansaks** [comment] 2021-02-22 06:38
> @jevansaks Jevan Saks FTE or @chingucoding do you remember this one?

Looks like the internal bug I linked earlier is still active.

**Comment by sibille** [comment] 2021-02-23 08:22
I just double checked and can confirm that this issue is still happening, both on WinUI 2.5 and WinUI3 Preview 4. 
We currently add the keyBoardAccelerators in the OnLoaded Event, but if I move them back to the ViewModel initialization I can see the Alt+ Left Tooltip pop up again.

![image](https://user-images.githubusercontent.com/24698018/108817446-35ae9c00-75b8-11eb-9c31-7d294df9ccc1.png)
Repro app (using WinUI 2.5): [App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6027509/App1.zip) 

Can we reopen this? Will also create a tracking issue on our side.

**Closed** 2023-08-03 22:31 UTC
Labels: area-NavigationView, team-Controls, no-issue-activity
