### ISSUE TITLE
"Up" arrow in TimePicker dialog not visible when window is fullscreen and timepicker near top of windowBug title

### ISSUE THREAD

**Issue by aloh86** [microsoft/microsoft-ui-xaml#9532] opened 2024-04-02 23:42 UTC
### Describe the bug

If a TimePicker is placed near the top of a window and the window itself is fullscreen, the up arrow may not be visible. See screenshot. Calculation of top of picker popup should be placed right below title bar.

### Steps to reproduce the bug

1. Add timepicker near top of a window.
2. Make window full screen.
3. Hover over hour or minute.
4. Observe that bottom arrow to scroll down is visible, but not the up arrow.

### Screenshots

![timepicker bug](https://github.com/microsoft/WindowsAppSDK/assets/1497463/e0bc1086-efcd-4193-a1ba-0d7db70b785c)

### NuGet package version

Windows App SDK 1.5.1: 1.5.240311000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

**Comment by kmahone** [comment] 2024-04-25 22:20
I am not able to reproduce this issue. Are you hitting it consistently or only in certain cases/on certain machines? Is there anything special in your app other than a TimePicker?

**Comment by kmahone** [comment] 2024-04-25 23:03
Also, what is the screen resolution of the device that you are hitting this on?

**Comment by kmahone** [comment] 2024-05-07 22:37
Closing this since I am unable to reproduce it.

**Closed by kmahone** 2024-05-07 22:37 UTC
Labels: area-Flyouts, area-DateTimePickers, team-Controls
