### ISSUE TITLE
Calling FindNextElement with Direction as Next or Previous on FocusManager with FindNextElementOptions throws exception

### ISSUE THREAD

**Issue by totallymonkey** [microsoft/microsoft-ui-xaml#1516] opened 2019-10-30 21:25 UTC
**Describe the bug**
When trying to find the next focusable element using FindNextElement on FocusManager, you can't provide FindNextElementOptions with a SearchRoot if using Next or Previous as the Direction.

**Steps to reproduce the bug**
1. Populate a FindNextElementOptions structure with a SearchRoot
2. Call FindNextElement on FocusManager, provide the options and specify Next or Previous as the Direction

**Expected behavior**
It should return the next element that can receive focus in that direction

**Version Info**
Windows 10, version vb_release.191004-1432

**Additional context**
Throws an unexpected exception:
Platform::InvalidArgumentException ^ at memory location 0x000000AECB0FCF20. HRESULT:0x80070057 The parameter is incorrect.
WinRT information: Focus navigation directions Next and Previous are not supported when using FindNextElementOptions.

**Comment by kmgallahan** [comment] 2019-10-30 21:46
As [the `FindNextElement` docs state](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.focusmanager.findnextelement):

> Tab navigation (FocusNavigationDirection.Previous and FocusNavigationDirection.Next ) cannot be used with FindNextElementOptions. Only directional navigation (FocusNavigationDirection.Up, FocusNavigationDirection.Down, FocusNavigationDirection.Left, or FocusNavigationDirection.Right ) is valid.

So not a bug.

**Comment by Austin-Lamb** [comment] 2019-10-30 22:39
My team added this API and it's a bug that we don't support these two directions, moving this to my team.  We'll look at addressing this in WinUI 3+.

**Closed** 2023-08-03 22:33 UTC
Labels: area-FocusManager, needs-winui-3, team-Reach, no-issue-activity
