### ISSUE TITLE
Get different MenuFlyoutItem ActualHeight in first Opened event by diffrent UIthread

### ISSUE THREAD

**Issue by l619534951** [microsoft/microsoft-ui-xaml#7381] opened 2022-07-15 04:05 UTC
### Describe the bug

get different MenuFlyoutItem ActualHeight in first Opened event by diffrent UIthread. 
render height is correct (32), but the height in proterty RenderSize is 40.
[MenuFlyoutActualHeightIssue.zip](https://github.com/microsoft/microsoft-ui-xaml/files/9117675/MenuFlyoutActualHeightIssue.zip)

### Steps to reproduce the bug

1.run demo.
2.click button twice.
3.check out Visual Studio's output.

### Expected behavior

return the same ActualHeight and RenderSize in first Opened event.

### Screenshots

![image](https://user-images.githubusercontent.com/17621099/179147723-f3ccac12-508e-4c96-b839-9ba54d4a3f43.png)
![image](https://user-images.githubusercontent.com/17621099/179147799-e48a4a23-4f23-4ae2-ae21-0796111d3f86.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by l619534951** [comment] 2022-07-15 04:07
the same issue https://github.com/microsoft/microsoft-ui-xaml/issues/6396
maybe the same reason cause that https://github.com/microsoft/microsoft-ui-xaml/issues/7374

**Comment by krschau** [comment] 2022-07-15 16:49
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6396

**Closed** 2022-07-15 16:49 UTC
Labels: bug, duplicate
