### ISSUE TITLE
WinUI3 Button XAML Template does not respect Foreground property after mouse passes over

### ISSUE THREAD

**Issue by RossCoeH** [microsoft/microsoft-ui-xaml#7208] opened 2022-06-08 06:48 UTC
### Describe the bug

In WInUI 3, create a Button with:

` <Button Name="Undo1" Content="Undo." 
              Background ="DarkSlateBlue" 
              Foreground ="White"/>`
On starting the app, the colors are correct, but after moving the mouse over the button, the text color will remain black rather that white as specified with Foreground property.
![ice_video_20220608-182052_edit_0](https://user-images.githubusercontent.com/30205634/172547370-fa0570f4-93d7-439c-aedb-3616cc07c517.gif)

### Steps to reproduce the bug

as above.

Note that the key issue is that the default template  for Button (inside generic.xaml) does not have a templatebinding for Foreground, but includes Background.
My reference for the template is:
C:\Users\....\.nuget\packages\microsoft.windowsappsdk\1.0.3\lib\net5.0-windows10.0.18362.0\Microsoft.WinUI\Themes

The template contains:
```   <Style TargetType="Button" >
      <Setter Property="Background" Value="{ThemeResource ButtonBackground}" />
  ```

It should contain:
```    <Style TargetType="Button">
      <Setter Property="Background" Value="{ThemeResource ButtonBackground}" />
      <Setter Property="Foreground" Value="{ThemeResource ButtonForeground}" />
```

### Expected behavior

Foreground color  property should be reset to original color after the mouse has left the button zone.  It will do that if the generic template is updated as suggested

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by ojhad** [comment] 2022-06-10 23:09
@RossCoeH I am unable to repro this in Windows App SDK 1.1. Can you try it out and see if it's still an issue?

**Comment by RossCoeH** [comment] 2022-06-12 01:29
Definitely still a problem in Windows App SDK 1.1. and in SDK 1.0.3
You are probably not watching the text color -   Create a new WinUI 3 App and edit MainWIndow.xaml to add FontWeight, Foreground and Background colors into the Button as below:

`Window
    x:Class="DemoBugButtonForeground.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:DemoBugButtonForeground"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="myButton_Click"
                FontWeight="Bold"
                Foreground="White"
                Background="DarkSlateBlue"
                >Click Me</Button>
    </StackPanel>
</Window>`

1. Start the app and the button text is white and bold.  
![image](https://user-images.githubusercontent.com/30205634/173210337-9ceb1100-8ac1-4f19-b64d-e831f0e234a8.png)

2. Now move mouse over button - the text goes black on a white background (as expected due to Visual State triggers in Generic.xaml)

3. Now move the mouse away from the button and the text remains black and is not reset to the original white.  
![image](https://user-images.githubusercontent.com/30205634/173210318-e694fc82-3a2d-4f71-a3a7-9143accc09bc.png)

This is the error causes by a missing template binding for Foreground in generic.xaml  as stated earlier.   

You can view a demonstration application at https://github.com/RossCoeH/DemoBugButtonForeground.
It is currently built with  Windows App SDK 1.0.3  but an upgrade to Windows App SDK 1.1. will not fix the problem either

**Comment by castorix** [comment] 2022-06-12 08:38
As EddieLotter said, it is a theming problem, as the bug is not reproducible in Dark mode on my OS (Windows 10 21H1)

**Comment by RossCoeH** [comment] 2022-06-13 06:40
Unlikely to be a theming issue because the default Dark theme color will be white which is the same color as I have chosen - therefore after mouseover you would still be left with white, and you might conclude there is no error.

But if you change the test to use another foreground color like "orange"  as below then you should see the error in both light and dark modes - use a button like:
`<Button x:Name="myButton" Click="myButton_Click"
            FontWeight="Bold"
            Foreground="Orange"
            Background="DarkSlateBlue"
            >Click Me</Button>`
The button text will start orange, but not return to orange after the mouse has passed over.

**Comment by ojhad** [comment] 2022-06-13 23:36
My mistake, I can repro the bug. Thanks for the follow up! I've routed the issue.

**Comment by nickrandolph** [comment] 2022-09-29 03:08
Did the routing cause this issue to get lost?

**Comment by michael-hawker** [comment] 2022-09-29 20:30
Related to https://github.com/microsoft/microsoft-ui-xaml/issues/6945

**Comment by ranjeshj** [comment] 2022-09-30 15:40
In this particular case, there is a template bind to the foreground property for the control. The foreground property is inherited by the ContentPresenter in the template. The PointerOver visual state is writing the foreground property and when going back to normal, the inhertited property is not going back to its original value. A workaround would be to explicitly set the foreground property on the ContentPresenter to a template binding instead of it getting inherited. That unfortunately needs a re-template. Testing a fix to WinUI3's button template.

@michael-hawker There are other cases where the properties really need to be template bound instead of pointing to theme resources like you mention in your linked bug.

**Comment by Jimbo99** [comment] 2022-10-20 10:50
Hi! Any progress on this please? And sorry but I am confused as to the workaround suggest - could you please clarify what the simplest way to solve this is at the moment, thank you.

**Comment by nickrandolph** [comment] 2022-11-02 06:38
@Jimbo99 does this post not provide enough guidance on how to fix this issue in your app: https://nicksnettravels.builttoroam.com/fixing-broken-defaultbuttonstyle/

**Comment by nickrandolph** [comment] 2022-11-02 06:39
@krschau @michael-hawker any idea whether this is going to be fixed in the 1.2 release (it wasn't in the preview releases).

**Comment by Jimbo99** [comment] 2022-11-02 07:33
> @Jimbo99 does this post not provide enough guidance on how to fix this issue in your app: https://nicksnettravels.builttoroam.com/fixing-broken-defaultbuttonstyle/

Many thanks Nick! I will give that a try when I get back to this issue.

**Comment by michael-hawker** [comment] 2022-11-02 16:53
FYI @gabbybilka

**Comment by gabbybilka** [comment] 2022-11-02 16:59
> @krschau @michael-hawker any idea whether this is going to be fixed in the 1.2 release (it wasn't in the preview releases).

@ranjeshj @kmahone @llongley who were the latest to work on this and can provide a status update.

**Comment by nickrandolph** [comment] 2022-11-14 11:37
So, looks like v1.2 without this bug being fixed? seriously??? How bad does a bug need to be in order to get it fixed?

**Comment by gabbybilka** [comment] 2022-12-15 00:23
:tada:`Microsoft.WindowsAppSDK.1.2.221209.1` has been released which fixes this issue.

Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1)

**Closed by gabbybilka** 2022-12-15 00:23 UTC
Labels: bug, team-Controls, product-winui3, area-Button

**Comment by Steffens-Bridgemate** [comment] 2023-03-26 21:33
I am sorry to report that I still have the problem with release 1.2.230313.1

**Comment by OmarGGil** [comment] 2023-04-03 17:15
I'am getting the same error using the last version 1.2.230313.1

**Comment by OmarGGil** [comment] 2023-04-03 18:16
After a few days looking for a workaround i found that i was overriding the DefaultButtonStyle and i just needed to use BasedOn="DefaultButtonStyle" at all my button styles, so that there's no property missing anymore.

Changed this:
`    <Style TargetType="Button" x:Key="btnCoppelSecondary" >
        <Setter Property="Background" Value="White"/>
        <Setter Property="Foreground" Value="{StaticResource Highlight}"/>
        <Setter Property="BorderBrush" Value="{StaticResource Highlight}"/>
        <Setter Property="Margin" Value="10,0,10,0"/>
        <Setter Property="CornerRadius" Value="16"/>
        <Setter Property="FontSize" Value="16"/>
        <Setter Property="FontWeight" Value="SemiBold"/>
        <Setter Property="HorizontalAlignment" Value="Stretch"/>
        <Setter Property="MinWidth" Value="200"/>
    </Style>`
    
  For this:
      ```
<Style TargetType="Button" x:Key="btnCoppelSecondary"  BasedOn="{StaticResource DefaultButtonStyle}">
        <Setter Property="Background" Value="White"/>
        <Setter Property="Foreground" Value="{StaticResource Highlight}"/>
        <Setter Property="BorderBrush" Value="{StaticResource Highlight}"/>
        <Setter Property="Margin" Value="10,0,10,0"/>
        <Setter Property="CornerRadius" Value="16"/>
        <Setter Property="FontSize" Value="16"/>
        <Setter Property="FontWeight" Value="SemiBold"/>
        <Setter Property="HorizontalAlignment" Value="Stretch"/>
        <Setter Property="MinWidth" Value="200"/>
    </Style>
```

**Comment by Jimbo99** [comment] 2023-04-04 07:54
> After a few days looking for a workaround i found that i was overriding the DefaultButtonStyle and i just needed to use BasedOn="DefaultButtonStyle" at all my button styles, so that there's no property missing anymore.

Thank you very much for posting that, @OmarGGil! I am using 1.2.230313.1 and was still having the problem. Your mod fixed it for me.
