### ISSUE TITLE
ToggleSplitButton does not work with Touch Input

### ISSUE THREAD

**Issue by techjogger** [microsoft/microsoft-ui-xaml#8035] opened 2022-12-22 16:00 UTC
### Describe the bug

Unable to control the IsChecked property with ToggleSplitButtons with touch input

### Steps to reproduce the bug

1. Launch WinUI3 Gallery App
2. Navigate to ToggleSplitButton page
3. Use mouse to toggle the control On/Off.... works as intended
4. Use Touch to toggle the control On/Off... it launches the flyout

### Expected behavior

Both mouse and TOUCH input toggle the control On/Off

https://user-images.githubusercontent.com/13125455/209173175-26131740-9046-4d30-9a6c-a0b3d8679e82.mp4

### NuGet package version

WinUI 3 - Windows App SDK 1.2.2: 1.2.221209.1

### Windows version

Windows 11 (22H2): Build 22621

**Comment by gabbybilka** [comment] 2023-01-06 17:43
Closing as dupe of #8061

**Closed by gabbybilka** 2023-01-06 17:43 UTC
Labels: bug, needs-triage
