### ISSUE TITLE
Using `AnimatedIcon`s inside `ListView` causes crashes 

### ISSUE THREAD

**Issue by yuyoyuppe** [microsoft/microsoft-ui-xaml#8604] opened 2023-07-04 11:15 UTC
### Describe the bug

While investigating [PowerRename performance issue](https://github.com/microsoft/PowerToys/pull/26761), we've discovered that using standard `CheckBox` as part of a `ListView`'s item causes app to crash.

### Steps to reproduce the bug

1. Checkout https://github.com/microsoft/PowerToys/commit/8ccbb694dd3c00b5d28132620a47b0e9a3a975c7.
2. [Build the installer](https://github.com/microsoft/PowerToys/tree/main/doc/devdocs), install PowerToys, use PowerRename to rename a folder with more than ~1000 items.
3. Scroll up and down really fast, observe the crash.

The relevant crash's callstack and more details are in the linked issue above.

### NuGet package version

None

**Comment by kmahone** [comment] 2023-08-09 23:17
Likely a dupe of: AnimatedIcon exception when initializing a large amount of CheckBoxes #8110

**Closed by kmahone** 2023-08-09 23:17 UTC
Labels: bug, team-Controls
