### ISSUE TITLE
Bug: NumberBox spin buttons aren't visible if the NumberBox starts off collapsed.

### ISSUE THREAD

**Issue by kmgallahan** [microsoft/microsoft-ui-xaml#6341] opened 2021-11-18 20:59 UTC
### Describe the bug

If a NumberBox starts out with Visibility=Collapsed, then when it is shown the spinner buttons are never displayed.

### Steps to reproduce the bug

[See this repo](https://github.com/kmgallahan/NumberBoxBugs) to repro. Click the "Show Collapsed NumberBoxes" button.

### Expected behavior

Spinner buttons should be visible.

### Screenshots

![Screenshot 2021-11-18 155403](https://user-images.githubusercontent.com/5379488/142495426-3d5b7b91-6b2f-4ce9-adb7-2c680b66f0f3.jpg)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

Present in WASDK 1.0. 

That version isn't currently available under the bug template's "NuGet package version" combobox.

**Comment by chingucoding** [comment] 2021-11-21 18:19
FWIW, this is also present in the WinUI 2 version. I would like to look into this.

**Comment by chingucoding** [comment] 2021-11-21 19:37
Turns out this, issue, to a degree, is a duplicate of #6052 and was already fixed in WinUI 2 (so awaiting fix being ported into WinUI 3).

**Closed** 2022-02-16 22:00 UTC
Labels: area-NumberBox, team-Controls, product-winui3
