### ISSUE TITLE
ProgressRing causes Windows.UI.Xaml.XamlParseException running under UWP in Project Reunion

### ISSUE THREAD

**Issue by gcaughey** [microsoft/microsoft-ui-xaml#4520] opened 2021-03-15 15:54 UTC
**Describe the bug**

Inclusion of a Progress Ring in a Project Reunion 0.5 UWP app causes exception in InitializeComponent(): Cannot create instance of type Microsoft.UI.XamlControls.ProgressRing

**Steps to reproduce the bug**

Include code like this in a Grid

                                    <ProgressRing Name="Progress"
                                                  VerticalAlignment="Center"
                                                  HorizontalAlignment="Center"
                                                  Width="40"
                                                  Height="40" />

**Expected behavior**

ProgressRing control is usable. (It is usable in desktop Project Reunion app, but not in Project Reunion running in UWP runtime.

**Screenshots**

**Version Info**

NuGet package version: 

WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21332)              |  Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This is only an issue with the UWP runtime for Project Reunion. With the Win32 runtime it is not a problem.

**Comment by codendone** [comment] 2021-03-16 05:13
Thanks for reporting this! The cause is the same as the problem with ProgressBar reported in #4491. Closing this as a dup of that issue.

**Closed by codendone** 2021-03-16 05:13 UTC
Labels: needs-triage
