### ISSUE TITLE
Windows.Storage.ApplicationData: ArgumentException when Inkscape is open

### ISSUE THREAD

**Issue by Meloman19** [microsoft/microsoft-ui-xaml#4725] opened 2021-04-02 18:53 UTC
**Describe the bug**
ApplicationData throw ArgumentException ("Value does not fall within the expected range.") on any property while Inkscape is open...

**Steps to reproduce the bug**
1. Add `var folder = ApplicationData.Current.LocalCacheFolder;` on app or window code-behind (no difference).
2. Open Inkscape (reproduced on v1.0.1 and v1.0.2)
3. Run App.

**Expected behavior**
No exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/23280622/113444440-97a2c280-93fc-11eb-82e4-7ce890391ac8.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5: 0.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
On UWP (not WinUI) no exception.

**Comment by StephenLPeters** [comment] 2021-04-02 23:14
@Meloman19 to be clear, this repro requires opening inkscape, an entirely different application?

**Comment by Meloman19** [comment] 2021-04-03 09:05
@StephenLPeters That's right. I was surprised myself.
I opened Inkscape for edit some svg and my running WinUI app crashed with this exception. I tried to launch the application and it crashed again on ApplicationData. But as soon as I closed Inkscape, the application worked fine.
This is reproduced on two completely different computers (my office and my home).

**Comment by StephenLPeters** [comment] 2021-04-06 00:07
how strange.. @MikeHillberg I'm not sure where to start with routing this one.

**Comment by sylveon** [comment] 2021-04-08 13:19
This is an old issue and I've opened a bug about it in Project Reunion. It also reproduces when you have GIMP open, or any program that holds a lock on the entire AppData folder.

https://github.com/microsoft/ProjectReunion/issues/101

**Comment by krschau** [comment] 2021-07-29 18:12
Since the Project Reunion instance of this issue has been closed as resolved, I'm going to resolve this one as well. If it turns out that there's something WinUI specific still broken, let me know and I'll reopen.

**Closed by krschau** 2021-07-29 18:12 UTC
Labels: appModel-win32, product-winui3, version-ProjectReunion 0.5
