### ISSUE TITLE
Proposal: Add FlyoutPlacementMode.Center to the FlyoutPlacementMode enum.

### ISSUE THREAD

**Issue by AlexanderBlackman** [microsoft/microsoft-ui-xaml#10211] opened 2024-12-02 21:46 UTC
## Desired Behaviour  
When  FlyoutPlacementMode.Center is selected, the Flyout should centre itself at the centre of the xaml root of the target element.

## Rationale

- It is troublesome to use margins to centre the flyout.
- TeachingTipPlacementMode already has "Center",  so adding it will improve consistency.

**Comment by Lightczx** [comment] 2024-12-10 03:51
Maybe that's why they didn't Add FlyoutPlacementMode.Center at first place
https://github.com/microsoft/microsoft-ui-xaml/blob/14364e6c301e881c5e2b6b9c39503343c66e53eb/src/dxaml/xcp/dxaml/lib/ContentDialog_Partial.cpp#L1250-L1272

**Comment by karkarl** [comment] 2024-12-26 16:40
Closing as by design.

**Closed by karkarl** 2024-12-26 16:40 UTC
Labels: feature proposal, needs-triage
