### ISSUE TITLE
Navigation View Scrollbar beside Settings button.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#3798] opened 2020-12-10 22:29 UTC
When the NavigationView flag IsSettingsVisible="True" is set to activate the Settings button in the footer the following is observed:

![image](https://user-images.githubusercontent.com/6632315/101836986-59f7f200-3b0c-11eb-8bb7-bc3d9405b066.png)

This is with the 2.5 version of ui-xaml.

**Steps to reproduce the bug**
1. Install version 2.5 of WinUI
2. Set IsSettingsVisible="True"
3. Hover over right edge of Settings button (scroll bar should appear)

**Expected behavior**
No scroll bars.

**Version Info**
2.5

NuGet package version: 
[Microsoft.UI.Xaml 2.5.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |

**Additional context**

Previously it was possible to have this markup:

```
            <ui:NavigationView.PaneFooter>
                <StackPanel Margin="0,0,0,-30" >
                    <Rectangle Height="1" HorizontalAlignment="Stretch" Fill="Gray" Margin="0,0,1,0" />

                    <StackPanel Orientation="Horizontal" Margin="0,0,0,0">
                        <ToggleButton Style="{StaticResource ToggleButtonStyle}" cm:Message.Attach="[Event Click] = [Action ShowSetup()]" >
                            <FontIcon Glyph="&#xE115;"/>
                        </ToggleButton>
                        <TextBlock Text="Setup" VerticalAlignment="Center" Margin="8,0,0,0" />
                    </StackPanel>
                </StackPanel>
            </ui:NavigationView.PaneFooter>
```

This no longer works.  This worked for a number of WinUI releases.  Such breaking changes should never happen.  There needs to be a mechanism for having custom markup for the Settings button.

**Comment by chingucoding** [comment] 2020-12-10 22:34
Since the settings item will be added to the PaneFooterItems, this is a duplicate of #3771 .

**Comment by StephenLPeters** [comment] 2020-12-12 00:11
I agree with this assessment: here is a link to the work around proposed in that issue: https://github.com/microsoft/microsoft-ui-xaml/issues/3771#issuecomment-739041735.

**Closed** 2020-12-12 00:11 UTC
Labels: area-NavigationView, duplicate, team-Controls
