### ISSUE TITLE
RichEditBox dont match Theme

### ISSUE THREAD

**Issue by CesGan** [microsoft/microsoft-ui-xaml#3061] opened 2020-08-06 12:10 UTC
**Describe the bug**
If you load a text to a RichEditBox when the Theme is in Dark mode the text will be black.

**Steps to reproduce the bug**
1. Just use the App XAML Controls Gallery version 1.2.16.0 and go to the RichEditBox control.
2. Go to the third example where you can upload a text file.
![image](https://user-images.githubusercontent.com/43221114/89530180-f9ffe080-d7e5-11ea-9ba9-bf348419b336.png)
3. Make sure you are on dark mode and upload the text.

**Expected behavior**
The text should be white.

**Comment by chingucoding** [comment] 2020-08-06 19:04
I am not sure if this is actually a bug. Per default text is black, so on black background you don't see anything. Similarly, if you load a file with white text into a RichEditBox in light theme, you can't read the text either.

**Comment by StephenLPeters** [comment] 2020-08-06 23:16
Yeah, I think this is by design.  With RichEdit, the text color is associated with the text itself so when you copy black text into a text box its supposed to be black. The background is also black though so you get this behavior.  We could have xaml controls gallery be responsive to this scenario but I'm not sure that is worth it. @stmoy

**Comment by stmoy** [comment] 2020-08-06 23:19
The bug reported here doesn't repro on other RichEditBoxes - just this specific one that attempts to emulate a text editor (and specifically sets the text color to black). I think it'd be reasonable to move this over to the XCG repo. @chingucoding did you add this sample? Maybe instead of setting the color to black, it could be set to a ThemeBrush instead?

**Comment by chingucoding** [comment] 2020-08-07 13:24
There are two things here:

1. When loading a RTF file, the RichEditBox not only copies the text, but also the font colors, resulting in a rtf file with black text not being readable on dark theme.
2. There were a few changes made to the samples to deal with the lighttheme on focus, which are not up to date anymore. I am working on reverting those changes and will create a PR for this soon.

Regarding 1, I don't think there is much to do beside overriding the font color delivered to us through the rtf file, @stmoy do you think we should do that kind of changes when loading an rtf file?

**Comment by stmoy** [comment] 2020-08-07 17:38
For #1, I don't think we should do any sort of shenanigans to the copied text in the sample. I think the absolute easiest thing would be to change the background color back to white just for this sample.

**Comment by StephenLPeters** [comment] 2020-08-07 17:41
> For #1, I don't think we should do any sort of shenanigans to the copied text in the sample. I think the absolute easiest thing would be to change the background color back to white just for this sample.

I think you would still hit this issue when loading an rtf file with white text. Maybe that is a little less common though?

**Comment by stmoy** [comment] 2020-08-07 17:53
> I think you would still hit this issue when loading an rtf file with white text. Maybe that is a little less common though?

True, and probably. This isn't mean to be a proper editor, just a simulacrum of one. It's ok if the edge cases don't work.

**Comment by chingucoding** [comment] 2020-08-07 17:55
If we change the background, we also need to adjust the foreground, foregroundhover, foregroundfocused ... values. I am not sure if we want to go down that road, especially as it suggest that you should use the RichEditBox with changed background and foreground values.

**Comment by stmoy** [comment] 2020-08-07 18:26
With this change, can we close this issue? https://github.com/microsoft/Xaml-Controls-Gallery/pull/524

**Comment by stmoy** [comment] 2020-08-07 20:28
Closing per the above PR

**Closed by stmoy** 2020-08-07 20:28 UTC
Labels: area-TextBox, needs-triage, team-Framework
