### ISSUE TITLE
Question: Spacing standard followed in WinUI controls

### ISSUE THREAD

**Issue by jeganrajm** [microsoft/microsoft-ui-xaml#2984] opened 2020-07-24 06:48 UTC
**Spacing standard - Margin, Padding, Border thickness followed in WinUI controls**

As guidelines is there for UWP App creation, is there specific document which discuss about spacing standard followed in WinUI controls.
It would help for creating custom controls with same standard.

Reference: https://docs.microsoft.com/en-us/windows/uwp/design/style/spacing
https://docs.microsoft.com/en-us/windows/uwp/design/layout/alignment-margin-padding
https://docs.microsoft.com/en-us/windows/uwp/design/basics/design-and-ui-intro#multiples-of-four

**Comment by mdtauk** [comment] 2020-07-24 10:24
Once upon a time, there was some PowerPoint utilities from Microsoft about creating Settings screen layouts.
![image](https://user-images.githubusercontent.com/7389110/88381904-489d8b80-cd9f-11ea-8954-1d68a7c28f22.png)

This is one of the reasons a **Form Control** has been proposed, to make creating these layouts easier. #82

**Comment by hansmbakker** [comment] 2020-07-24 11:55
Is this a duplicate of https://github.com/MicrosoftDocs/windows-uwp/issues/2374 ?

**Comment by ranjeshj** [comment] 2020-07-24 23:09
@kikisaints and @chigy as FYI

**Closed** 2023-08-03 22:37 UTC
Labels: question, no-issue-activity
