### ISSUE TITLE
Announcing: WinUI 2.6! 🎨💻🎉

### ISSUE THREAD

**Issue by anawishnoff** [microsoft/microsoft-ui-xaml#5262] opened 2021-06-24 16:16 UTC
The team has just released WinUI 2.6! This release contains visual updates to most of our controls, a few new controls, bug fixes, and new functionality for use in UWP apps.

### New controls
- [Expander](https://docs.microsoft.com/windows/apps/design/controls/expander)
- [BreadcrumbBar](https://docs.microsoft.com/windows/apps/design/controls/breadcrumbbar)
- [AnimatedIcon](https://docs.microsoft.com/windows/apps/design/controls/animated-icon)
- [PipsPager](https://docs.microsoft.com/windows/apps/design/controls/pipspager)
- [ImageIcon](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.imageicon)

### Control visual updates
Most WinUI controls now support the latest Windows styles. These new styles align with the current design direction of Windows, and will provide your app with the most modern, up-to-date visual experience. 

### New materials
WinUI 2.6 is the first release to introduce **Mica**, which is a new material that incorporates theme and desktop wallpaper to paint the background of long-lived windows such as apps and settings. You can apply Mica to your application backdrop to delight users and create visual hierarchy, aiding productivity, by increasing clarity on which window is in focus.

Mica is specifically designed for app performance as it only samples the desktop wallpaper once to create its visualization.

### New features
- **SplitButton in CommandBar**: You can now easily integrate a SplitButton into CommandBar using the `SplitButtonCommandBarStyle` and [AppBarElementContainer](https://docs.microsoft.com/uwp/api/windows.ui.xaml.controls.appbarelementcontainer) wrapper class. 
- **Popup location**: Several new APIs were added to the [Popup class](https://docs.microsoft.com/windows/winui/api/microsoft.ui.xaml.controls.primitives.popup) to allow developers to specify the direction how CommandBarFlyout opens up to ensure it is placed in a desired location relative to the item it is being involved from. 

### Bug fixes
To see the full list of bugs fixed in this release, see the official [GitHub release](https://github.com/microsoft/microsoft-ui-xaml/releases/tag/v2.6.0).

## Get started
If you're new to WinUI, get started by following the steps in this doc: [Getting started with the WinUI 2.x library](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/getting-started)

If you've used WinUI in the past, get started with 2.6 by downloading the latest NuGet package: [NuGet Download](https://www.nuget.org/packages/Microsoft.UI.Xaml)

## Thank you!
Your contributions as a developer community have been incredibly valuable in shipping WinUI. We'd like to extend a big thank you to everyone who contributed to this release by filing or fixing bugs, requesting features, implementing features, and generally being a significant part of the development process!

**Comment by Tropix126** [comment] 2021-06-24 16:24
This looks great! Is there an estimate of when these styles will arrive on WinUI 3?

**Comment by chingucoding** [comment] 2021-06-24 17:09
How can I as a developer use Mica? How does Mica manifest in the WinUI 2.6 source code?

**Comment by jevansaks** [comment] 2021-06-24 17:22
> How can I as a developer use Mica? How does Mica manifest in the WinUI 2.6 source code?

Docs are now live! https://docs.microsoft.com/en-us/windows/apps/design/style/mica

The code for it is here: https://github.com/microsoft/microsoft-ui-xaml/pull/5261 and will be in main soon.

**Comment by chingucoding** [comment] 2021-06-24 17:24
Awesome, thank you Jevan!

**Comment by lhak** [comment] 2021-06-24 17:51
All menus look very dark (e.g. the search box in the xaml controls gallery)

![image](https://user-images.githubusercontent.com/38145893/123309596-69c5a980-d525-11eb-9971-4eeba56b6702.png)

is this intended?

**Comment by ranjeshj** [comment] 2021-06-24 17:54
@lhak no, can you please file an issue ?

**Comment by LancerComet** [comment] 2021-06-24 18:11
After upgrade to 2.6 I've found that I have to make lots of minor fixing to fix the style 😢 It's too much to a 2.5-to-2.6 upgrade

Windows 10 21H1

![2 6](https://user-images.githubusercontent.com/10321350/123312223-9fd15080-d55a-11eb-8a19-d06d8a8009ca.jpg)

**Comment by roxk** [comment] 2021-06-24 18:43
I'm not sure, but it looks like the issue is related to #5133 . This is how date picker looks on light mode:
![image](https://user-images.githubusercontent.com/16918354/123315604-7b777300-d55e-11eb-83b2-08927ed97047.png)

**Note**: Screenshot cannot capture the more subtle shadow behind the flyout, but both the search box in the screenshot above and this flyout have shadow.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| 21H1 | Yes |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

**Comment by mdtauk** [comment] 2021-06-24 18:55
I remember a few of us mentioning the issue with dim Acrylic flyouts, as if the shadow layer renders on top - so not entirely sure if this is the same issue, or something new.  As I understand it, WinUI is using DropDownShadows instead of the older Elevation based ThemeShadows

**Comment by nlogozzo** [comment] 2021-06-25 02:22
I thought WinUI 3 was the future. When can we see these controls in WinUI 3?

**Comment by jevansaks** [comment] 2021-06-25 02:45
> I thought WinUI 3 was the future. When can we see these controls in WinUI 3?

It's harder because WinUI2 and WinUI3 are different codebases right now and it takes us a fair bit of time to merge the changes over from WinUI2 into WinUI3. We wanted to do it but we just didn't have the time to get that done by today's releases.

**Comment by nlogozzo** [comment] 2021-06-25 02:57
@jevansaks Ah, I see. Any idea when this would be coming for WinUI 3? With Windows 11 pushing WinUI 3 and Windows App SDK, I feel like these new controls, features, and designs should be worked on WinUI 3 first, then backported to WinUI 2.

**Comment by zhuxb711** [comment] 2021-06-25 08:24
> I'm not sure, but it looks like the issue is related to #5133 . This is how date picker looks on light mode:
> ![image](https://user-images.githubusercontent.com/16918354/123315604-7b777300-d55e-11eb-83b2-08927ed97047.png)
> 
> **Note**: Screenshot cannot capture the more subtle shadow behind the flyout, but both the search box in the screenshot above and this flyout have shadow.
> 
> _Update_: Added video below
> https://user-images.githubusercontent.com/16918354/123316663-af06cd00-d55f-11eb-91a7-3ecdcd3b7e94.mp4
> 
> Windows 10 version	Saw the problem?
> Insider Build (xxxxx)	
> 21H1	Yes
> October 2020 Update (19042)	
> May 2020 Update (19041)	
> November 2019 Update (18363)	
> May 2019 Update (18362)	
> October 2018 Update (17763)	
> April 2018 Update (17134)	
> Fall Creators Update (16299)	
> Creators Update (15063)

#3373 I mention dim color before but nobody try to fix it

**Comment by FrayxRulez** [comment] 2021-06-25 11:37
> I remember a few of us mentioning the issue with dim Acrylic flyouts, as if the shadow layer renders on top - so not entirely sure if this is the same issue, or something new. As I understand it, WinUI is using DropDownShadows instead of the older Elevation based ThemeShadows

It's a new one, and it's a complete deal breaker for me, must be fixed asap: https://github.com/microsoft/microsoft-ui-xaml/issues/5277

**Comment by akpapa** [comment] 2021-06-25 16:31
I have a basic question:
Will the Store automatically update 2.6 runtime for current 2.5 UWP apps in the Store?
Or the developers need to rebuild their apps on 2.6 and republish them?

**Comment by mdtauk** [comment] 2021-06-25 17:29
> I have a basic question:
> Will the Store automatically update 2.6 runtime for current 2.5 UWP apps in the Store?
> Or the developers need to rebuild their apps on 2.6 and republish them?

Re-build I believe, versioning means apps can continue using older versions without their apps breaking potentially.

**Comment by akpapa** [comment] 2021-06-26 08:25
> Re-build I believe, versioning means apps can continue using older versions without their apps breaking potentially.

Thanks, that makes sense.
Why I'm asking this is because I read a doc about deployment of Project Reunion which now can be read only through web cache.

> Deploy apps that use Project Reunion
> 19/03/2021

> When a new version of the Project Reunion framework package is released, all apps are updated to the new version without themselves having to redistribute a copy. Windows updates to the newest version of frameworks as they are released, and apps will automatically reference the latest framework package version during relaunch. Older framework package versions will not be removed from the system until they are no longer running or being actively used by apps on the system.

I thought UWP apps work the same way.

**Comment by gabrielconl** [comment] 2021-06-26 12:44
![image](https://user-images.githubusercontent.com/84711285/123513305-3ace4580-d695-11eb-8acf-45e027ab0bfc.png)
Shouldn't tooltips use OverlayCornerRadius? All other floating controls have it.

**Comment by jevansaks** [comment] 2021-06-27 03:31
> ![image](https://user-images.githubusercontent.com/84711285/123513305-3ace4580-d695-11eb-8acf-45e027ab0bfc.png)
> Shouldn't tooltips use OverlayCornerRadius? All other floating controls have it.

They do, but only uplevel. The problem is that the dropshadow drawn pre-Windows 11 (that's implemented in the OS) doesn't look good with higher rounding value so we had to change the dropshadow implementation in Windows 11. But that means we can only use the larger rounding value on Windows 11 and higher. 😢

The good news is that in WinUI3 we'll be able to do the new rounding and shadows everywhere.

**Comment by under3415** [comment] 2021-07-03 22:48
Next time, can RTM release be the same as the final pre-release? Makes no sense to have pre-releases and then deploy something else to production that looks different and breaks.

**Comment by zhuxb711** [comment] 2021-08-19 04:30
It seems that the 2.6.2 pre-release and 2.7.0 pre-release will cause the failure when submit to MStore. Error code is 1201. Is there anyone encountered the same problem?
![image](https://user-images.githubusercontent.com/42038175/130007864-554c7934-122d-40b7-9a51-4aca925d8173.png)

**Comment by crramirez** [comment] 2021-08-24 21:36
Same here: 
![image](https://user-images.githubusercontent.com/8397379/130693231-331702cc-54cc-4a95-af1a-250d07850a98.png)

With the 2.6.2 release. My app UWP with desktop extensions, x64 and ARM64. The desktop part is in .NET 5

**Comment by zhuxb711** [comment] 2021-08-25 00:37
@chingucoding @StephenLPeters @ranjeshj 
Any ideas?

**Comment by zhuxb711** [comment] 2021-08-25 01:50
> Same here:
> ![image](https://user-images.githubusercontent.com/8397379/130693231-331702cc-54cc-4a95-af1a-250d07850a98.png)
> 
> With the 2.6.2 release. My app UWP with desktop extensions, x64 and ARM64. The desktop part is in .NET 5. In fact since 2.6 I cannot publish in store. I must stay in 2.5

My App also have desktop extensions and it's in .Net Framework 4.8. I suspect that only apps with desktop extensions are affected. After all, I haven't seen anyone mention this in other issues.

**Comment by zhuxb711** [comment] 2021-08-25 16:35
@crramirez How could I upgrade the desktop extensions to .Net 5 ?  I got the error: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsFormsavailable for the specified RuntimeId "win10-arm" "win10-arm64"

**Comment by crramirez** [comment] 2021-08-25 16:47
Pssf, I don't remember but it wasn't easy. The best way is to create a new .net 5 project and migrate the code. I can later today paste my project. My project is a console application to avoid WPF and Forms incompatibilities with ARM

**Comment by zhuxb711** [comment] 2021-08-25 16:53
> Pssf, I don't remember but it wasn't easy. The best way is to create a new .net 5 project and migrate the code. I can later today paste my project. My project is a console application to avoid WPF and Forms incompatibilities with ARM

Same as your project. My project is a console too but I don't know why it will reference that package
![image](https://user-images.githubusercontent.com/42038175/130832659-f466fef9-a8f9-4a4c-bf0e-2956b681ca02.png)

**Comment by crramirez** [comment] 2021-09-23 16:31
> @crramirez How could I upgrade the desktop extensions to .Net 5 ? I got the error: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsFormsavailable for the specified RuntimeId "win10-arm" "win10-arm64"

Hello, @zhuxb711 I completely forgot your question until today I checked your project and noticed that it is .Net Framework based. This is the project file of my Full Trust Project in .net 5: https://gist.github.com/crramirez/1e0bcbd5e590f54ffb26385343a1bd92

**Comment by zhuxb711** [comment] 2021-09-23 17:03
> > @crramirez How could I upgrade the desktop extensions to .Net 5 ? I got the error: There was no runtime pack for Microsoft.WindowsDesktop.App.WindowsFormsavailable for the specified RuntimeId "win10-arm" "win10-arm64"
> 
> 
> 
> Hello, @zhuxb711 I completely forgot your question until today I checked your project and noticed that it is .Net Framework based. This is the project file of my Full Trust Project in .net 5: https://gist.github.com/crramirez/1e0bcbd5e590f54ffb26385343a1bd92

Never mind. I found something that might block my project to use .Net 5.

1. In .Net Framework, I could call every UWP API without considering Win10 version. But .Net 5 was limited.

2. My project rely on some API in System.Windows.Form (like Clipboard etc.). Since WinForm is not supposed on Arm currently. It means I have to give ARM for now.

So .Net 5 is not an option for me currently. Thanks for help. Very appreciate!

**Comment by crramirez** [comment] 2021-09-23 17:10
Remember that for .Net Framework when you put Any CPU for ARM it will generate x86 code and it will run in emulation mode. So, your application will run in ARM.
For me worked quite well for a while even though I had to make a workaround to call x64 processes from x86.

I wonder if you target Windows 11 as a minimum if it will generate x64 for ARM64 based on the emulation

**Comment by crramirez** [comment] 2021-09-23 17:15
@zhuxb711 did you read this? https://devblogs.microsoft.com/dotnet/net-july-2021/

**Comment by zhuxb711** [comment] 2021-09-23 17:15
Sorry I haven't test it on Win11 because Win11 is still in preview.

**Comment by zhuxb711** [comment] 2021-09-23 17:22
> @zhuxb711 did you read this? https://devblogs.microsoft.com/dotnet/net-july-2021/

Thanks for providing that article. I will try it again with .Net 5.0.8 SDK and let's see if that works for me.

**Comment by crramirez** [comment] 2021-09-23 17:22
> Sorry I haven't tested it on Win11 because Win11 is still in preview.

I use Virtual Machines for that, having our apps ready is important, also you can do this: https://boxofcables.dev/dual-boot-windows-and-windows-insiders-without-re-partitioning/ it works pretty well

**Comment by zhuxb711** [comment] 2021-09-24 06:51
@crramirez I could use .Net 5 on ARM64 but ARM now. Microsoft.WindowsDesktop.App.WindowsForms on ARM is still not supported by .Net 5 currently

**Comment by zhuxb711** [comment] 2021-09-24 11:08
@crramirez
I always got this error on publish the package (Debug is fine): NETSDK1083: The specified RuntimeIdentifier 'win-ARM64' is not recognized.
It seems that 
```
<RuntimeIdentifiers></RuntimeIdentifiers> 
```
not work and VS always read the configuration from 
```
<RuntimeIdentifier><RuntimeIdentifier>
```

**Comment by Panda-Sharp** [comment] 2021-09-24 13:00
> ```
> <RuntimeIdentifiers></RuntimeIdentifiers> 
> ```

did you try to totally remove <RuntimeIdentifiers></RuntimeIdentifiers>  ?

**Comment by zhuxb711** [comment] 2021-09-24 13:20
> > ```
> 
> > <RuntimeIdentifiers></RuntimeIdentifiers> 
> 
> > ```
> 
> 
> 
> did you try to totally remove `<RuntimeIdentifiers></RuntimeIdentifiers> ` ?

Remove it totally just the same as 
<RuntimeIdentifier> exists with "win-ARM64" in it. It looks like the default value

**Comment by crramirez** [comment] 2021-09-24 17:55
@zhuxb711 I have `<RuntimeIdentifiers>win10-x64;win10-arm64;win-x64;win-arm64</RuntimeIdentifiers>` check the project file that I shared above

**Comment by gabbybilka** [comment] 2021-11-23 19:17
Check out #5889 for the latest WinUI 2.x update!

**Closed by gabbybilka** 2021-11-23 19:17 UTC
Labels: discussion
