### ISSUE TITLE
WinAppSDK 1.0 (WinUI 3) ComboBox theme and Toolbox

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#6697] opened 2022-02-09 18:39 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinAppSDK-10-WinUI-3-ComboBox-theme-a/1617587)._

---
I started working with Windows App SDK 1.0 in Visual Studio 2022 (17.0.4) and found 3 problems:

1. When I change RequestedTheme of a Grid, it works but when I click a  combobox inside the Grid, its drop down items panel remains in the original theme.

![WinUIApp1_03.png](https://aka.ms/dc/image?name=Be12e0a7c2ede48518f34fbc2ab3c8395637755757012384667_WinUIApp1_03.png&tid=e12e0a7c2ede48518f34fbc2ab3c8395637755757012384667)

2. When we open xaml view of the page, the Toolbox is empty.

![WinUIApp1_02.png](https://aka.ms/dc/image?name=B1479e04fcd9345e7a8d8cc1e22677236637755758494949266_WinUIApp1_02.png&tid=1479e04fcd9345e7a8d8cc1e22677236637755758494949266)

---
#### Feedback Bot on 12/19/2021, 10:54 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by WelterDevelopment** [comment] 2022-02-16 11:48
Duplicate of #6622. This problem has been around for ages... For me this clearly is a bug with seemingly no simple workaround but design-wise it apparently is 'by design' that Popups get their theme (as far as I understand) from the app's ApplicationTheme and not from the ElementTheme of the superordinate UIElement. Highly frustrating...
Please also give #4474 a thumbs-up because beeing able to set the ApplicationTheme at runtime would (as far as I understand) also solve the popup theme issue.

**Comment by AndrewFromJapan** [comment] 2022-02-19 05:26
This is a workaround I'm using for the moment. It's not perfect but at least the DropDownButton works with theme changes. 

**XAML**
```
<DropDownButton x:Name="ThemeSelector" Content="Theme">
    <DropDownButton.Flyout>
        <MenuFlyout Placement="Bottom">
            <MenuFlyoutItem Text="Default" Click="ThemeSelector_Click"/>
            <MenuFlyoutItem Text="Light" Click="ThemeSelector_Click"/>
            <MenuFlyoutItem Text="Dark" Click="ThemeSelector_Click"/>
        </MenuFlyout>
    </DropDownButton.Flyout>
</DropDownButton>
```

***.cs**
```
private void ThemeSelector_Click(object sender, RoutedEventArgs e)
{
    if (sender is MenuFlyoutItem menuItem)
    {
        ThemeSelector.Content = menuItem.Text;
    }
}
```

**Comment by StephenLPeters** [comment] 2022-03-03 23:47
This is definitely considered a bug by the team and we recognize that it is frustrating.  The by design part of our explination is simply how the system works today, not how we want it to work. Unfortunately this is a challenging issue to fix, but it is definitely on our radar.

**Closed** 2022-03-03 23:47 UTC
Labels: duplicate, area-Flyouts, area-Resources, team-Controls, product-winui3
