### ISSUE TITLE
TextBox unaligned text

### ISSUE THREAD

**Issue by OnlyOnePro** [microsoft/microsoft-ui-xaml#5386] opened 2021-07-07 07:30 UTC
**Describe the bug**

The TextBox's placeholder and content text do not center-align vertically when indicated. Changing it to bottom doesn't appears to work either.

**Steps to reproduce the bug**

Create a TextBox as provided by the below snippet on a Blank Page

```
            <TextBox x:Name="SearchBar" 
                     HorizontalAlignment="Stretch" 
                     Grid.Row="0" 
                     Grid.Column="0" 
                     Grid.ColumnSpan="4"
                     VerticalAlignment="Stretch"
                     HorizontalContentAlignment="Left"
                     VerticalContentAlignment="Center"
                     PlaceholderText="Text that should be centered"/>
```

**Expected behavior**

The text should modify its centering relative to the control itself.

**Screenshots**

![image](https://user-images.githubusercontent.com/27441273/124717434-66f38d00-df05-11eb-907a-b473e4baee3c.png)

**Version Info**

NuGet package version: 

[Microsoft.UI.Xaml 2.6.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |  Yes  |
| May 2020 Update (19041)            |  Yes  |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This is a similar issue to #3284.

**Comment by ranjeshj** [comment] 2021-07-07 23:11
@chingucoding @StephenLPeters This looks like an issue we have looked at before. Was this never fixed ?

**Comment by StephenLPeters** [comment] 2021-07-07 23:38
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5369

**Comment by chingucoding** [comment] 2021-07-08 07:56
The trail leads down to #3383, however I am not sure why we reverted that. @beervoley might remember more.

**Comment by nor0x** [comment] 2022-03-15 19:12
any updates on this? I tried `VerticalContentAlignment` but it doesn't change the placeholder position
![image](https://user-images.githubusercontent.com/3210391/158453542-2c5351e5-acd4-464b-970a-a8d7d7b57d3d.png)

**Comment by nor0x** [comment] 2023-07-29 20:43
> This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 5 days.

still open!

**Comment by DmitriyKomin** [comment] 2023-10-19 22:53
Duplicate of #6324

**Closed by DmitriyKomin** 2023-10-19 22:53 UTC
Labels: feature proposal, help wanted, area-TextBlocks, area-Styling, team-Controls
