### ISSUE TITLE
FontIcon displays garbled characters

### ISSUE THREAD

**Issue by sudongg** [microsoft/microsoft-ui-xaml#6390] opened 2021-11-27 08:27 UTC
### Describe the bug

Without setting `FontFamily="Segoe MDL2 Assets" `, some icons will be displayed as Garbled.
Garbled will not appear on versions prior to app sdk 1.0.

### Steps to reproduce the bug

1. New App SDK 1.0 project
2. Copy the code below to MainWindow.xaml
```
  <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
         <Button x:Name="myButton" >
             <FontIcon x:Name="testIcon" FontSize="12" Glyph="&#xE102;" Margin="5,0,5,0" Foreground="Gray"></FontIcon>
         </Button>
     </StackPanel>

```
3. Run.
4. You can see that the icon on the button is Garbled.

### Expected behavior

The icon is displayed normally

### NuGet package version

WinUI 3 - Windows App SDK 1.0 (If you're seeing your issue in older previews of WinUI 3, please try this release)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

### Additional context

 SymbolIcon will also appear garbled, the code is as follows
`  <SymbolIcon  Symbol="Save" Margin="5,0,-5,0"></SymbolIcon>
`

**Comment by StephenLPeters** [comment] 2022-02-17 17:50
probably a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6392, @MarissaMatt @licanhua @codendone FYI

**Comment by Jay-o-Way** [comment] 2023-04-10 10:00
> "It's not you, it's Microsoft"

https://github.com/microsoft/microsoft-ui-xaml/issues/8375

**Comment by JJBrychell** [comment] 2023-08-29 22:15
The poster's PR has been pulled in WinUI2 and WinUI3.

**Closed by JJBrychell** 2023-08-29 22:15 UTC
Labels: team-Rendering, product-winui3, area-Icon
