### ISSUE TITLE
FileOpenPicker throw Invalid Window handle  exception in Project Reunion 0.5 desktop app 

### ISSUE THREAD

**Issue by gcaughey** [microsoft/microsoft-ui-xaml#4519] opened 2021-03-15 15:43 UTC
**Describe the bug**

FileOpenPicker throws Invalid Window handle exception on PickSingleFileAsync()

**Steps to reproduce the bug**

1. Step through the following code:
 
var picker = new FileOpenPicker();
var file = await picker.PickSingleFileAsync();

**Expected behavior**

picker.PickerSingleFileAsync() should show FileOpenPicker

**Screenshots**

**Version Info**

NuGet package version: 

WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

This fails running on Win32 but does not fail running in UWP app model.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21332)              | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

This app runs without error when running under UWP.

**Comment by Marv51** [comment] 2021-03-15 15:50
I had the same issue and this worked for me: https://github.com/microsoft/microsoft-ui-xaml/issues/4167

```csharp
        [ComImport, System.Runtime.InteropServices.Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        public interface IInitializeWithWindow
        {
            void Initialize([In] IntPtr hwnd);
        }

        [DllImport("user32.dll", ExactSpelling = true, CharSet = CharSet.Auto, PreserveSig = true, SetLastError = false)]
        public static extern IntPtr GetActiveWindow();

        var picker = new FileOpenPicker();
        var initializeWithWindowWrapper = picker.As<IInitializeWithWindow>();
        initializeWithWindowWrapper.Initialize(GetActiveWindow());
        var file = await picker.PickSingleFileAsync();
```

**Comment by gcaughey** [comment] 2021-03-15 16:08
I'm getting a compiler error on this line of code:
`var initializeWithWindowWrapper = picker.As<IInitializeWithWindow>();
`
Member 'FileOpenPicker.As<IInitializeWithWindow>()' cannot be accessed with an instance reference.

Interestingly the ContentDialog issue that was mentioned in your issue appears to work now.

**Comment by FreddyD-GH** [comment] 2021-03-15 16:56
@gcaughey add `using WinRT;` to use the `As<T>()` extension method.

**Comment by gcaughey** [comment] 2021-03-15 17:05
Thanks - that does indeed solve the compiler error. But now I'm getting a new exception on PickSingleFileAsync: Error HRESULT E_FAIL has been returned from a call to a COM component.

**Comment by FreddyD-GH** [comment] 2021-03-15 18:06
@gcaughey I just tried it out and unfortunately, it doesn't look like the FileTypeFilter gets set automatically either.  So, you'll need to add yet another line to your current monstrosity: `picker.FileTypeFilter.Add("*");`

**Comment by gcaughey** [comment] 2021-03-15 18:45
Excellent! This makes a very usable workaround. Thanks!

**Comment by StephenLPeters** [comment] 2021-03-16 23:33
Closing as a duplicate of #4167

**Closed by StephenLPeters** 2021-03-16 23:33 UTC
Labels: area-Desktop, duplicate, winui3preview

**Comment by YareYareO** [comment] 2023-05-14 10:03
I have a WinUi3 project and this worked for me just now. FYI. Thanks alot to everyone!
