### ISSUE TITLE
MenuFlyoutSubItem can be laggy when opening on mouse over

### ISSUE THREAD

**Issue by jeremy-visionaid** [microsoft/microsoft-ui-xaml#9371] opened 2024-02-29 02:58 UTC
### Describe the bug

There can sometimes be a significant/noticeable delay when displaying a MenuFlyoutSubItem's MenuFlyoutItems

### Steps to reproduce the bug

This is reprodicible in WinUI 3 Gallery:
"Menu & toolbars" -> "MenuFlyout"
Then click "File Options" and hover over "Send to"

Occassionaly this takes a few seconds to display the sub items (not every time, but maybe 1 in every 5)

Originally noticed it in a MAUI app, but it appears to affect all Win UI 3 applications

### Expected behavior

Sub items should start animating into view immediately on mouse over

### NuGet package version

WinUI 3 - Windows App SDK 1.4.5: 1.4.240411001

### Windows version

Windows 11 (22H2): Build 22621

**Comment by kmgallahan** [comment] 2024-02-29 03:57
Possibly same issue as #939 with diagnosis found here: https://github.com/microsoft/microsoft-ui-xaml/issues/939#issuecomment-1837149717

**Comment by jeremy-visionaid** [comment] 2024-02-29 04:18
@kmgallahan Oh yup, that's the one! I am running a high refresh rate screen... If I set it back down to 60 Hz then the problem goes away... Not the first time I've seen something like this with WinUI 3. I couldn't even target an app against it previously at all because of refresh rate related perf issues like #7290 that made it unsuitable for displaying video etc.

Anyways, #939 is a proposal to change the behaviour on clicking the menu items, and this is explitly calling out the display refresh rate performance issue as a bug... Up to you if you want to close this as a dupe.

**Comment by kmgallahan** [comment] 2024-02-29 04:28
@DmitriyKomin There are multiple issues related to this: #939 #8921 #9371, plus other elsewhere like https://github.com/microsoft/terminal/issues/14756, & https://github.com/microsoft/terminal/issues/15545

**Comment by bpulliam** [comment] 2024-02-29 17:16
Resolving as a duplicate of #8921

**Comment by gegao18** [comment] 2024-03-22 22:29
Update - we have two separate issues here. #939 and #8921 deal with a slight delay when expanding cascading menus with a click. This delay exists regardless of the device.

There is also a problem in the way that WinUI 3 handles its clock that causes major delays on variable refresh rate devices, which can cause multi-second delays in DispatcherTimers firing, which then affects things like menus which wait for those timers. I believe that's what this thread is hitting. We have a fix for this variable refresh rate problem coming in 1.5.2.

**Closed by gegao18** 2024-03-22 22:29 UTC
Labels: bug, needs-triage

**Comment by fredemmott** [comment] 2024-03-22 22:37
@gegao18 that’s great! Any chance of a backport to 1.4? I’m using v1.5 in my master branch, but 1.4 -> 1.5 is a too big of a change for me to put in the existing stable branch of my app
