### ISSUE TITLE
NavigationView: overflow button, settings button and pane footer displayed outside of the app window

### ISSUE THREAD

**Issue by vgromfeld** [microsoft/microsoft-ui-xaml#943] opened 2019-06-25 12:51 UTC
**Describe the bug**
If the selected item of `NavigationView` has a name too long for the currently available window width, the overflow button, the pane footer and the settings button are displayed outside of the window bounds and not reachable.

**Steps to reproduce the bug**
1. Create an application using the following snippet:
```xml
<mux:NavigationView IsBackEnabled="True" PaneDisplayMode="Top">
    <mux:NavigationView.MenuItems>
        <mux:NavigationViewItem Content="Item with a very very very very long name that doesn't fit in the window width..." />
        <mux:NavigationViewItem Content="Item B" />
    </mux:NavigationView.MenuItems>
    <mux:NavigationView.PaneFooter>
        <mux:NavigationViewItem Icon="People" />
    </mux:NavigationView.PaneFooter>
</mux:NavigationView>
```
2. Run the application
3. By default, there is no selected item. 
4. Resize the application; the overflow button is well displayed based on the window width
5. Select the first item
6. The first item is not selected (it has the accent color line under it)
7. Reduce the window width if needed and notice that the overflow and settings button as well as the footer are now outside of the window bounds.

**Expected behavior**
If one item is too long for the available width, it should be restricted in a way that will allow all the left controls to be displayed.

**Screenshots**
*Nothing selected - window with a big enough width* -> OK
![image](https://user-images.githubusercontent.com/20152272/60098915-dea75280-9756-11e9-96f8-157163dad5d6.png)

*Nothing selected - smallest window width* -> OK
![image](https://user-images.githubusercontent.com/20152272/60098954-faaaf400-9756-11e9-8671-82dba1d5a8b4.png)

*Item B selected - smallest window width* -> OK
![image](https://user-images.githubusercontent.com/20152272/60098982-0a2a3d00-9757-11e9-9bed-7e44da26e082.png)

*Long item selected - smalled window width* -> KO
![image](https://user-images.githubusercontent.com/20152272/60099017-17472c00-9757-11e9-8317-01260de0aa0e.png)

*Long item selected - medium window width* -> KO
![image](https://user-images.githubusercontent.com/20152272/60099069-33e36400-9757-11e9-933f-abe4d43b12b8.png)

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.1.190606001
Microsoft.UI.Xaml 2.2.190611001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |    |
| Anniversary Update (14393)         |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |    |

**Additional context**
Retemplating the control and changing the `TopNavGrid` columns layout to use a 1star width for the navigation items list is helping to workaround the issue but it has it own drawback (the overflow button is sticked to the left pane) and needs to be refined.
```xml
<Grid.ColumnDefinitions>
    <ColumnDefinition x:Name="BackButtonPlaceholderOnTopNav" Width="{ThemeResource NavigationBackButtonWidth}" />
    <ColumnDefinition Width="Auto" />
    <ColumnDefinition Width="Auto" />
    <!-- nav items column -->
    **<ColumnDefinition Width="*" />**
    **<ColumnDefinition Width="Auto" />**
    <!-- custom content column -->
    <ColumnDefinition Width="Auto" />
    <ColumnDefinition Width="Auto" />
    <ColumnDefinition Width="Auto" />
    <ColumnDefinition Width="Auto" />
</Grid.ColumnDefinitions>
```

**Comment by jevansaks** [comment] 2019-06-25 17:05
Sounds like a dupe of #769. Re-open if you disagree.

**Closed by jevansaks** 2019-06-25 17:05 UTC
