### ISSUE TITLE
TwoPaneView: Pane1 doesn't span across available space

### ISSUE THREAD

**Issue by ikarago** [microsoft/microsoft-ui-xaml#1950] opened 2020-02-06 19:57 UTC
**Describe the bug**
Pane1 doesn't use the available space in the TwoPaneView when only the width of Pane2 has been set.

**Steps to reproduce the bug**
Use the following XAML code to reproduce behavior. Change the the Property of Pane1Length to Pane2Length to see the control filling properly.

WinUI needs to be referenced in the XAML (in sample code set as `winuic`)

```XAML
                    <winuic:TwoPaneView Background="Yellow"
                                        WideModeConfiguration="RightLeft"
                                        PanePriority="Pane1"
                                        Pane2Length="320"
                                        HorizontalAlignment="Stretch"
                                        HorizontalContentAlignment="Stretch">
                        <!-- Pane 1 - GridView -->
                        <winuic:TwoPaneView.Pane1>
                            <Grid Background="Blue">
                                <TextBlock Text="Hello!" />
                            </Grid>
                        </winuic:TwoPaneView.Pane1>
                        <!-- Pane 2 - Details -->
                        <winuic:TwoPaneView.Pane2>
                                <Grid Background="Lime">
                                    <TextBlock Text="Hello!" />
                                </Grid>
                        </winuic:TwoPaneView.Pane2>
                    </winuic:TwoPaneView>`
```
**Expected behavior**
I expected Pane1 to use up the available width and dynamically change width depending on the available space with Pane2 keeping it's set width. Just like it does with dynamically changing the width of Pane2 when only the Width of Pane1 has been set.

**Workaround**
As noted by @rudyhuyn on Twitter this can be remedied by setting property Pane1Lenght to 1* and Pane2Lenght to a set width. This fixes the issue, but the developer needs to be aware of this, so this being automatically done by the control would have the preference

Twitter message with the workaround and explanation what causes the issue: https://twitter.com/RudyHuyn/status/1225502492718518273?s=20

**Screenshots**
![image](https://user-images.githubusercontent.com/19528662/73973561-16988a00-4923-11ea-9ff3-13f2da4c4899.png)
![image](https://user-images.githubusercontent.com/19528662/73973574-1d270180-4923-11ea-98ec-d5af05682b2e.png)

I've removed the DropShadowPanel (of the Community Toolkit) from the sample code included for less dependencies while debugging.

**Version Info**
NuGet package version: 
Microsoft.UI.Xaml 2.3.191211002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | -  |
| November 2019 Update (18363)  | Yes  |
| May 2019 Update (18362)            | -   |
| October 2018 Update (17763)        | -   |
| April 2018 Update (17134)          | -  |
| Fall Creators Update (16299)       | -   |
| Creators Update (15063)            | -   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   | -  |
| Xbox                      | -  |
| Surface Hub          | -  |
| IoT                         | -  |

**Additional context**
Thread with screenshots and XAML code on Twitter: https://twitter.com/IkaragoDev/status/1225498840121344002?s=20

**Comment by chingucoding** [comment] 2020-02-06 20:29
It seems like this behavior is kind of by design. If you look at the source code, you can see that the left column (aka Pane1 in LeftToRight) is set to auto:

https://github.com/microsoft/microsoft-ui-xaml/blob/5747ce10d6ec58865e1e669492ab6bd04953c042/dev/TwoPaneView/TwoPaneView.xaml#L84-L108

However I agree that this is a bit counterintuitive. I think it would be better to mention this in the docs.

**Comment by StephenLPeters** [comment] 2020-02-06 21:14
The design of TwoPaneView specifies that pane1's width is set to auto and that pane two's width is set to * by default. This means that by default pane one will take the minimum space required to display its content and pane two will fill the remaining space. In your example you have changed pane two's behavior by setting its width to a new value but have not changed Pane 1's behavior. In order to acheive what you are looking for our design requires the work around you suggested (although just * would work fine). I'm going to close this issue because I think it is by design.

**Closed by StephenLPeters** 2020-02-06 21:14 UTC
Labels: needs-triage
