### ISSUE TITLE
Horizontal and Vertical Content Alignment is not works for TextBox

### ISSUE THREAD

**Issue by FarjanaParveen** [microsoft/microsoft-ui-xaml#5369] opened 2021-07-06 08:06 UTC
**Describe the bug**
We have use the TextBox in our application, set the HorizaontalContentAlignment and VerticalContentAlignment as Center. But the text is aligned at Top, left of the control.

**Steps to reproduce the bug**
1. Run the sample.
2. Note the "Hi" text in TextBox, its in Top, left corner

**Expected behavior**
Text should be in center of the control

**Screenshots**
![image](https://user-images.githubusercontent.com/56529945/124565614-dca51d80-de5f-11eb-8d99-098d1a0d5cda.png)![image](https://user-images.githubusercontent.com/56529945/124564388-a2874c00-de5e-11eb-988f-569e2ab72d01.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

Sample Link : [App9.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6768383/App9.zip)

**Comment by StephenLPeters** [comment] 2021-07-06 23:25
I beleive this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5163  which was originally fixed by https://github.com/microsoft/microsoft-ui-xaml/pull/3383 but reverted because we didn't have the right default values... We should add this back in.

@beervoley FYI

**Closed** 2023-08-03 22:44 UTC
Labels: duplicate, area-TextBox, team-Controls, no-issue-activity
