### ISSUE TITLE
FontSize of RichEditBox is limited to 130

### ISSUE THREAD

**Issue by KennethVScom** [microsoft/microsoft-ui-xaml#8835] opened 2023-09-06 07:14 UTC
### Describe the bug

In the RichEditBox control, when pasting a huge font size context copied from Microsoft Word or some other application, the font size will be limited to 130 (fs260).

### Steps to reproduce the bug

1. Copy text from Microsoft Word with font size 150 (or larger)
2. Paste the text into a RichEditBox control of an application in the WinUI3 project
3. Copy the text from the RichEditBox and paste it back into Microsoft Word
4. Observe that the font size of the pasted text will be reduced to 130 (fs260).

### Expected behavior

In this case, the font size of the pasted text should remain as it is (FontSize = 150).

### Screenshots

Step 1: Copy text from Microsoft Word with font size 150
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/132980123/c838dd83-df4f-4900-bd7e-a33053200af9)

Step 2: Paste the text into a RichEditBox control of an application in the WinUI3 project
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/132980123/52931bc4-714d-424d-846a-a0bfb26690eb)

Step 3: Copy the text from the RichEditBox and paste it back into Microsoft Word
Results: The font size of the pasted text will be reduced to 130 (fs260).
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/132980123/9f91e17c-9aee-493a-ba8e-87538e7ba741)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/132980123/5424a4c7-2415-4271-a375-299b4eb628f3)

### NuGet package version

None

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

Related issue:
https://github.com/microsoft/microsoft-ui-xaml/issues/9045

**Comment by codendone** [comment] 2023-11-03 01:42
Resolving as duplicate of #9045, which has some responses.

**Closed by codendone** 2023-11-03 01:42 UTC
Labels: feature proposal, area-TextBox, team-Controls
