### ISSUE TITLE
pressed state is stuck when you click, drag and release on items in the navigation pane

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#3582] opened 2020-11-09 06:57 UTC
**Describe the bug**

Pressed state is stuck when you click, drag and release on items in the navigation pane

**Steps to reproduce the bug**

1. Open Gallery
2. Click and hold on a NavigationView item in the left pane
3. While clicking, drag outside of the window

**Expected behavior**

Pressed state is cancelled

**Actual behavior**

Pressed state persists

**Screenshots**

It's possible to "lock" the press state on any number of items.

![image](https://user-images.githubusercontent.com/25991996/98578490-47bb3780-2272-11eb-868e-435d3e8b1e77.png)

**Version Info**

Gallery version (found on Settings page): 

1.2.16.0

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [x] 20H2
- [ ] May 2020 Update (19041)
- [ ] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**

**Comment by kmgallahan** [comment] 2020-11-09 18:55
Dupe of #2860 & already resolved in one of the WinUI 2.5 Pre-releases.

**Comment by YuliKl** [comment] 2020-11-09 19:05
I was going to call this a dupe of #2966 :)

**Comment by ranjeshj** [comment] 2020-11-10 00:17
@Poopooracoocoo can you please reopen this if you see this issue with the latest WinUI 2.5 prerelease ?

**Closed by ranjeshj** 2020-11-10 00:17 UTC
Labels: needs-triage

**Comment by Poopooracoocoo** [comment] 2020-11-10 02:31
@stmoy xaml controls gallery really needs an update
