### ISSUE TITLE
Cannot create WinUI project in Visual Studio 2019 16.8.1

### ISSUE THREAD

**Issue by prcdpr** [microsoft/microsoft-ui-xaml#3607] opened 2020-11-13 13:13 UTC
**Describe the bug**

When trying to create a blank app WinUI project, it shows an error and the solution doesn't compile.

```
---------------------------
Microsoft Visual Studio
---------------------------
A problem was encountered creating the sub project 'MyApp1'.  The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPlatformSDKLocation('', 10.0.18362.0)" cannot be evaluated.
Parameter "targetPlatformIdentifier" cannot have zero length.  C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets
---------------------------
OK   
---------------------------
```

**Steps to reproduce the bug**

1. Selecte "Create a new project". Choose C#/Windows/WinUI
2. Create a new Blank App, Packaged (WinUI in Desktop).

**Expected behavior**
It should create a new project and it should compile and run out of the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/43776797/99075926-93dfe200-25ba-11eb-8e24-fa9a286bf926.png)
![image](https://user-images.githubusercontent.com/43776797/99075492-de149380-25b9-11eb-91bb-8112cb73d11d.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by stevenbrix** [comment] 2020-11-13 16:55
@prcdpr thanks for filing this issue! This is a known issue that will be fixed when we release preview3 in a week

**Closed by stevenbrix** 2020-11-13 16:55 UTC
Labels: needs-triage

**Comment by stevenbrix** [comment] 2020-11-13 16:59
Also, this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/3282
