### ISSUE TITLE
Custom style is not applied

### ISSUE THREAD

**Issue by Vinothini-V** [microsoft/microsoft-ui-xaml#3499] opened 2020-10-27 11:43 UTC
**Describe the bug**
I have a custom control derived from DropdownButton and have style for this control. But custom style is not applied. 

**Steps to reproduce the bug**
  public sealed class CustomControl1 : DropDownButton
    {
        public CustomControl1()
        {
            this.DefaultStyleKey = typeof(CustomControl1);
        }

        protected override void OnApplyTemplate()
        {
            base.OnApplyTemplate();
        }
    }

 <Style x:Key="CCStyle" TargetType="local:CustomControl1">
        <Setter Property="Background" Value="Red" />
        <Setter Property="Foreground" Value="White"/>
        <Setter Property="BorderBrush" Value="{ThemeResource ButtonBorderThemeBrush}" />
        <Setter Property="BorderThickness" Value="{ThemeResource ButtonBorderThemeThickness}" />
        <Setter Property="Padding" Value="12,4,12,4" />
        <Setter Property="HorizontalAlignment" Value="Left" />
        <Setter Property="VerticalAlignment" Value="Center" />
        <Setter Property="FontFamily" Value="{ThemeResource ContentControlThemeFontFamily}" />
        <Setter Property="FontSize" Value="{ThemeResource ControlContentThemeFontSize}" />
        <Setter Property="Template">
            <Setter.Value>
                <ControlTemplate TargetType="local:CustomControl1">
                    <Grid>
                        <Border x:Name="LargeBorder" Visibility="Collapsed"
                            Background="{TemplateBinding Background}"
                            BorderBrush="{TemplateBinding BorderBrush}"
                            BorderThickness="{TemplateBinding BorderThickness}"
                            Margin="3">
                            <StackPanel Orientation="Horizontal">
                                <ContentPresenter x:Name="ContentPresenter3"
                                          Content="{TemplateBinding Content}"
                                          ContentTransitions="{TemplateBinding ContentTransitions}"
                                          ContentTemplate="{ThemeResource LargeMode}" Margin="{TemplateBinding Padding}"
                                          HorizontalAlignment="{TemplateBinding HorizontalContentAlignment}"
                                          VerticalAlignment="{TemplateBinding VerticalContentAlignment}" 
                                         />
                                <Path Name="Arrow3" 
                                                HorizontalAlignment="Center" 
                                                VerticalAlignment="Center" 
                                                Fill="{TemplateBinding Foreground}"
                                                Data="M 0 0 L 4 4 L 8 0 Z" 
                                                Margin="2,0,2,0"/>
                            </StackPanel>
                        </Border>
                    </Grid>
                </ControlTemplate>
            </Setter.Value>
        </Setter>
    </Style>
    <Style TargetType="local:CustomControl1" BasedOn="{StaticResource CCStyle}"/>

**Expected behavior**
This custom style should be applied. 

**Version Info**
NuGet package version: 3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |
OS version : 1909 Build : 18363.1139

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
But for me when custom style is used OnApplyTemplate itself is not called. And it works well for controls derived from Button, ListView but not fro DropdownButton, SplitButton, TabView and NavigationView.

**Comment by robloo** [comment] 2020-10-27 20:38
Since I can see my Bug report #3502 getting closed as duplicate :) I'm duplicating my report for a similar issue below:

----------------------------------------------

**Describe the bug**

Unable to create new controls inheriting from a MUX WinUI 2.x base control. The control template will never be applied.

**Steps to reproduce the bug**

Using the attached repro project below:

[InheritTest.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5447846/InheritTest.zip)

 1. Using the WUX namespace set a breakpoint on `base.OnApplyTemplate()`. When code is run the breakpoint should be hit:
     ![image](https://user-images.githubusercontent.com/17993847/97355529-69c5ba80-186d-11eb-9367-c36f4507b023.png)
 2. Change to the MUX namespace for the base control and run again with the same breakpoint:
     ![image](https://user-images.githubusercontent.com/17993847/97355791-caed8e00-186d-11eb-8c3a-6952cad28978.png)
 3. The breakpoint in OnApplyTemplate() is never hit and the control template is never applied.

Note that if you change the `DefaultStyleKey = typeof(ColorPicker)` (the base type) that will work.

**Expected behavior**

It should be possible to inherit from a MUX WinUI 2.x base control and have the new control template applied.

**Screenshots**

Using WUX the template is correctly applied:
![image](https://user-images.githubusercontent.com/17993847/97355648-8feb5a80-186d-11eb-9c87-c438a0c7a7d2.png)

Using MUX no template is applied:
![image](https://user-images.githubusercontent.com/17993847/97355762-bf01cc00-186d-11eb-94d7-127b3c2c8439.png)

Also see above.

**Version Info**


NuGet package version: 

Microsoft.UI.Xaml 2.4.3

**Comment by ranjeshj** [comment] 2020-10-27 23:12
This looks like WinUI3 vs the other issue is in WinUI2.x

**Comment by stevenbrix** [comment] 2020-10-28 00:27
While these are similar, I agree with @ranjeshj that they are most likely different. 

This particular issue, which is a WinUI3 one, seems like a dupe of https://github.com/microsoft/CsWinRT/issues/345

**Closed** 2020-10-28 23:30 UTC
Labels: duplicate, winui3preview

**Comment by jeganrajm** [comment] 2020-10-29 06:26
@StephenLPeters  @stevenbrix  I can't see solution for this issue in [microsoft/CsWinRT#345](https://github.com/microsoft/CsWinRT/issues/345) (Closed) or am i missing?

**Comment by StephenLPeters** [comment] 2020-10-29 06:34
It should be Fixed with CsWinRT1.0.1 which is included in Winui3 preview 3. so the issue should be resolved by upgrading to that when it becomes available.
