### ISSUE TITLE
WinUI HyperlinkButton is not displayed underlined

### ISSUE THREAD

**Issue by yangxiaopo** [microsoft/microsoft-ui-xaml#7000] opened 2022-04-20 03:11 UTC
### Describe the bug

The _HyperlinkButton_ default behavior is not consistent with that [HyperlinkButton ](https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.hyperlinkbutton?view=winui-3.0#remarks)documentation notes.
Original post: [https://stackoverflow.com/questions/71694089/winui-hyperlinkbutton-is-not-displayed-underlined](https://stackoverflow.com/questions/71694089/winui-hyperlinkbutton-is-not-displayed-underlined)

### Steps to reproduce the bug

A blank WinUI3 project with \<HyperlinkButton Content="www.microsoft.com" NavigateUri="http://microsoft.com"/>

### Expected behavior

Consistent Behavior.

### Screenshots

![image](https://user-images.githubusercontent.com/16287565/164142756-56779bfb-049f-4c45-9e22-9b05e91d09ae.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (21H2): Build 22000

**Comment by gabbybilka** [comment] 2022-04-20 03:47
The documentation needs updating to reflect the updated design for HyperlinkButton first introduced in WinUI 2.6, see the WinUI [Figma toolkit](https://www.figma.com/community/file/989931624019688277) for more info.

**Comment by ojhad** [comment] 2022-04-25 23:20
Closing as by design.

**Closed by ojhad** 2022-04-25 23:20 UTC
Labels: needs-triage, team-Controls, area-HyperlinkButton
