### ISSUE TITLE
[SDK] XAML Compiler emits duplicate definitions

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6413] opened 2021-11-30 03:37 UTC
XAML Compiler emits code in xamltypeinfo.g.cpp that has duplicate definitions, if e.g. two Pages define an element with the same name (this seems fixed in WinAppSDK).

Repro is: Have two runtimeclasses in IDL, that have a property with the same name, and are used from `x:Bind` in XAML.

**Comment by RealTommyKlein** [comment] 2021-12-13 22:05
Is this a dupe of #5395?

**Comment by asklar** [comment] 2021-12-13 23:22
Yeah this looks like the same issue. Is this something we can fix in the inbox SDK, it push into the build tools nuget?



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bpulliam** [comment] 2023-06-30 21:33
Closing since #5395 was fixed.

**Closed by bpulliam** 2023-06-30 21:33 UTC
Labels: duplicate, area-XamlCompiler, team-Markup, product-winui3
