### ISSUE TITLE
Bug: CornerRadius Inconsistency/Missing in ContentDialog/MessageDialog

### ISSUE THREAD

**Issue by robloo** [microsoft/microsoft-ui-xaml#1345] opened 2019-09-17 15:19 UTC
**Describe the bug**
There is some inconsistency with the added corner radius in WinUI 2.2 styling (#659). The buttons in ContentDialog did not get a corner radius in all cases. Other dialog types probably have the same issue (MessageDialog).

**Screenshots**

(1) As you can see the button on the right has the radius, the button on the left does not. 

<img width="390" alt="Capture1" src="https://user-images.githubusercontent.com/17993847/65054390-77ef9a80-d93b-11e9-9cde-47300381a047.PNG">

<img width="1162" alt="Capture3" src="https://user-images.githubusercontent.com/17993847/65067694-176d5700-d955-11e9-8909-196ef9302b4c.PNG">

Additonal Questions:
 (2) When an item has keyboard focus like the buttons in the above image, should the added context border have a corner radius as well?
Edit: As answered below this is by design...

 (3) AppBarButton doesn't have a CornerRadius. I actually think this looks better and should stay that way. However, was this and related AppBar controls missed in the discussion?
Edit: As answered below this is by design.

<img width="143" alt="Capture2" src="https://user-images.githubusercontent.com/17993847/65054378-72925000-d93b-11e9-9a95-e15ca32d87d0.PNG">

**Version Info**

Microsoft.UI.Xaml 2.2.190830001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes |
| October 2018 Update (17763)        | N/A |
| April 2018 Update (17134)          | N/A |
| Fall Creators Update (16299)       | N/A |
| Creators Update (15063)            | N/A |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes |
| Mobile                   | N/A |
| Xbox                      | N/A |
| Surface Hub          | N/A  |
| IoT                         | N/A |

**Comment by jevansaks** [comment] 2019-09-17 16:23
Buttons in ContentDialog is probably an oversight. Buttons in MessageDialog is owned by Windows and would be part of a future OS update. 

AppBarButton ... i'm not sure. @chigy?

**Comment by chigy** [comment] 2019-09-17 16:31
@robloo , @jevansaks 
#1 - A bug. All buttons are supposed to get rounded.
#2 - Don't understand the question. If the question is if the keyboard focus should be rounded, then the answer is no. Not part of today's design.
#3 - It is by design per "T-rule" when multiple items are next to each other and forms a T, it should not be rounded. Thus, we don't round list items nor grid items.

**Comment by robloo** [comment] 2019-09-17 18:01
@chigy

> 2 - Don't understand the question. If the question is if the keyboard focus should be rounded, then the answer is no. Not part of today's design.

Yes, that is my question (should have said 'Focus'). Further annotated below:

<img width="1162" alt="Capture3" src="https://user-images.githubusercontent.com/17993847/65067027-96619000-d953-11e9-9f4b-d4d329717604.PNG">

> 3 - It is by design per "T-rule" when multiple items are next to each other and forms a T, it should not be rounded. Thus, we don't round list items nor grid items.

Makes a lot of sense and definitely visually it's the right call. Can this be added to docs some place so developers like myself are aware. We are going to have to know the design conventions with CornerRadius.

Probably here: https://docs.microsoft.com/en-us/windows/uwp/design/style/

I can add feedback to the document on GitHub if it will help.

**Comment by chigy** [comment] 2019-09-17 18:08
@robloo , Yes, it is by design that we don't round and yes we plan on adding some note to that since as a developer you can round the corner as much as you like but they might not look good. Detail is still being worked out as to what to say and where, but early draft is here. https://github.com/microsoft/microsoft-ui-xaml-specs/blob/user/chigy/roundedcorner/active/RoundedCorner/roundedcorner.md

**Comment by chigy** [comment] 2019-09-17 18:09
@robloo , can you please open a bug against #1 so I can close this issue as resolved since the other two issues are actually by current design?

**Comment by robloo** [comment] 2019-09-17 18:09
@Chigy I will re-title this one. No need to make a new bug report.

**Comment by chigy** [comment] 2019-09-17 18:12
Removing myself so it will appear at triage. Please consider fixing # 1 issue. FYI @jevansaks

**Comment by jevansaks** [comment] 2019-09-17 18:13
Thanks @robloo! @kaiguo, FYI.

**Comment by ismaelestalayo** [comment] 2019-09-20 20:55
Apart from the buttons that are not in the Selected state not having the CornerRadius set, the ContentDialog itself doesn't have it either:

![ContentDialog](https://user-images.githubusercontent.com/17100634/65358347-a1d5e500-dbf9-11e9-8d17-35f5be52cff3.png)

**Comment by chigy** [comment] 2019-09-23 17:08
@kaiguo , ContentDialog not having corner working was something to do with a bug that you were working through? Though I thought we shipped with corner rounded but the bug was about customizaiton?

**Closed** 2019-10-04 19:35 UTC
Labels: area-UIDesign, bug, working on it

**Comment by robloo** [comment] 2019-12-15 19:41
Are the buttons in the ContentDialog supposed to have a border brush? This doesn't match with the default button style.

![pic1](https://user-images.githubusercontent.com/17993847/70867915-dcc18d80-1f48-11ea-959b-6612c5c7d215.png)

This came up investigating another bug which I'll open shortly.

**Comment by chigy** [comment] 2019-12-16 17:13
@robloo , which version are you using because I am seeing the right behavior on my older Controls gallery (this one doesn't have rounded corner fixed) so did something get reverted when others got fixed?

![image](https://user-images.githubusercontent.com/22958680/70927682-4a6ec780-1fe4-11ea-9743-0c4428601357.png)

**Comment by chingucoding** [comment] 2019-12-16 19:11
I am also seeing the right behavior on the latest commit on master of this repository. Following screenshot was taken inside the MUXControlsTestApp:

![image](https://user-images.githubusercontent.com/16122379/70935324-3a84d100-2040-11ea-87f6-34b1de8c983e.png)

**Comment by robloo** [comment] 2019-12-17 22:44
@chigy @chinguacoding Ok, thanks for taking a look. This is a strange state my app is getting into then and it looks like it's tied with #1764. Since the style is correct for you, I won't worry about it here.

**Comment by robloo** [comment] 2019-12-23 21:36
Update: The border on the buttons in the content dialog was a bug on my part. Sorry for that!

**Comment by kaiguo** [comment] 2019-12-23 22:42
> Update: The border on the buttons in the content dialog was a bug on my part. Sorry for that!

Thanks for letting us know.
