### ISSUE TITLE
WinUI 3 in desktop: XAML parsing failed

### ISSUE THREAD

**Issue by yv73** [microsoft/microsoft-ui-xaml#5714] opened 2021-08-18 00:55 UTC
Windows 10 Pro 10.0.19043
Microsoft Visual Studio Community 2019 Version 16.11.1

Steps to reproduce:

File, New, App (WinUI 3 in desktop)
WTS.ProjectConfig.xml:

```
<xml
    xmlns:genTemplate="http://schemas.microsoft.com/appx/developer/windowsTemplateStudio">

    <genTemplate:Metadata>
        <genTemplate:Item Name="generator" Value="Windows Template Studio"/>
        <genTemplate:Item Name="wizardVersion" Version="v4.1.21179.1" />
        <genTemplate:Item Name="templatesVersion" Version="v4.1.21179.1" />
        <genTemplate:Item Name="projectType" Value="BlankAdvanced" />
        <genTemplate:Item Name="framework" Value="MVVMToolkit" />
        <genTemplate:Item Name="platform" Value="WinUI" />
        <genTemplate:Item Name="appmodel" Value="Desktop" />
    </genTemplate:Metadata>
</xml>
```
Add, New Item ... Resource Dictionary (WinUI 3) TextBox.xaml
Make the modifications to TextBox.xaml:

```
   <Style x:Key="TextBoxBaseStyle" TargetType="TextBox">
        <Setter Property="FontSize" Value="{StaticResource LargeFontSize}"/>
    </Style>

```
LargeFontSize is from /Styles/_FontSizes.xaml:

`<x:Double x:Key="LargeFontSize">24</x:Double>
`

Make the modifications to App.xaml:

```
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
                <ResourceDictionary Source="/Styles/_FontSizes.xaml" />
                <ResourceDictionary Source="/Styles/_Thickness.xaml" />
                <ResourceDictionary Source="/Styles/Page.xaml" />
                <ResourceDictionary Source="/Styles/TextBlock.xaml" />
                **<ResourceDictionary Source="/Styles/TextBox.xaml" />**
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

```
Build / execute
Observe exception at runtime: 'XAML parsing failed.'
"Cannot find a Resource with the Name/Key LargeFontSize [Line: 13 Position: 37]"

Is there something wrong?

**Comment by StephenLPeters** [comment] 2021-08-20 00:08
@yv73 does the _FontSizes.xaml file contain only one resource, LargeFontSize?  If so can you try adding a second resource to that dictionary and see if the issue still occurs? there is an optimization for resource dictionaries with only one entry which has bitten us in the past, I wonder if that is causing this.

**Comment by yv73** [comment] 2021-08-20 02:17
_FontSizes.xaml is generated with Windows Template Studio (App (WinUI 3 in Desktop)):

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <x:Double x:Key="LargeFontSize">24</x:Double>

    <x:Double x:Key="MediumFontSize">16</x:Double>

</ResourceDictionary>

```

To set TextBox.xaml:

```
    <Style x:Key="TextBoxBaseStyle" TargetType="TextBox">
        <Setter Property="FontSize" Value="{StaticResource MediumFontSize}"/>
    </Style>

```
Observe exception at runtime: 'XAML parsing failed.'
"Cannot find a Resource with the Name/Key MediumFontSize [Line: 13 Position: 37]"

No problem if I use 

```
    <Style x:Key="TextBoxBaseStyle" TargetType="TextBox">
        <Setter Property="FontSize" Value="{StaticResource TextStyleLargeFontSize}"/>
    </Style>

```

TextStyleLargeFontSize is from .nuget\packages\microsoft.projectreunion.winui\0.8.2\lib\net5.0-windows10.0.18362.0\Microsoft.WinUI\Themes\generic.xaml

`            <x:Double x:Key="TextStyleLargeFontSize">18.14</x:Double>
`

And LargeFontSize is used in TextBlock.xaml (generated with WTS) without problem:

```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">

    <!--Common texts-->
    <Style x:Key="PageTitleStyle" TargetType="TextBlock">
        <Setter Property="VerticalAlignment" Value="Center" />
        <Setter Property="FontWeight" Value="SemiLight" />
        <Setter Property="FontSize" Value="{StaticResource LargeFontSize}" />
        <Setter Property="TextTrimming" Value="CharacterEllipsis" />
        <Setter Property="TextWrapping" Value="NoWrap" />
    </Style>

    <Style x:Key="BodyTextStyle" TargetType="TextBlock">
        <Setter Property="FontWeight" Value="Normal" />
        <Setter Property="FontSize" Value="{StaticResource MediumFontSize}" />
        <Setter Property="TextTrimming" Value="CharacterEllipsis" />
        <Setter Property="TextWrapping" Value="Wrap" />
    </Style>

</ResourceDictionary>

```

Using LargeFontSize directly in MainPage.xaml:

`            <TextBox Text="TextBox" FontSize="{StaticResource LargeFontSize}"/>
`

is no problem too.

**Comment by mrlacey** [comment] 2021-08-20 19:23
@yv73 I can't reproduce the issue based on the step you've provided. Following them everything works fine for me.

Based on other information above, I suspect there may be more going on than is documented. Because:
- The error message reports the error at line 13, but unless you've got a lot of empty lines, there's no need for TextBlox.xaml to have that many lines so I wonder if there's something else there that may be contributing to the problem. 
- WTS generates an app that references Project Reunion package version 0.8.0 but your error message references 0.8.2

If you have a minimal project that shows this, can you zip it up and share it?

**Comment by yv73** [comment] 2021-08-21 02:22
I updated Project Reunion package to version 0.8.2. With 0.8.0 same behavior.

[App1.zip](https://github.com/microsoft/microsoft-ui-xaml/files/7024712/App1.zip)

**Comment by StephenLPeters** [comment] 2021-09-14 23:44
@RealTommyKlein and @fabiant3 FYI

**Comment by RealTommyKlein** [comment] 2021-09-30 00:43
I believe the `TextBox.xaml` and `TextBlock.xaml` dictionaries need to explicitly include `_FontSize.xaml` in their `MergedDictionaries` in order to resolve `LargeFontSize` and `MediumFontSize`.  `TextBox.xaml` and `TextBlock.xaml` are being inserted into `Application.Resources` at the same time as `_FontSize.xaml`, so they wouldn't be able to resolve from `_FontSize.xaml` even though the `Application.Resources.MergedDictionaries` would suggest so.  Making these changes worked for me:

TextBlock.xaml:
```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/Styles/_FontSizes.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <!--Common texts-->
    <Style x:Key="PageTitleStyle" TargetType="TextBlock">
        <Setter Property="VerticalAlignment" Value="Center" />
        <Setter Property="FontWeight" Value="SemiLight" />
        <Setter Property="FontSize" Value="{StaticResource LargeFontSize}" />
        <Setter Property="TextTrimming" Value="CharacterEllipsis" />
        <Setter Property="TextWrapping" Value="NoWrap" />
    </Style>

    <Style x:Key="BodyTextStyle" TargetType="TextBlock">
        <Setter Property="FontWeight" Value="Normal" />
        <Setter Property="FontSize" Value="{StaticResource MediumFontSize}" />
        <Setter Property="TextTrimming" Value="CharacterEllipsis" />
        <Setter Property="TextWrapping" Value="Wrap" />
    </Style>

</ResourceDictionary>
```

TextBox.xaml:
```
<ResourceDictionary
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1.Styles">
    <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="/Styles/_FontSizes.xaml" />
    </ResourceDictionary.MergedDictionaries>

    <Style x:Key="TextBoxBaseStyle" TargetType="TextBox">
        <Setter Property="FontSize" Value="{StaticResource LargeFontSize}"/>
    </Style>

</ResourceDictionary>
```

**Comment by yv73** [comment] 2021-09-30 01:47
Yes, it works for me too. However, `TextBlock.xaml` works without explicitly including `_FontSize.xaml`.

**Closed** 2023-08-04 12:03 UTC
Labels: area-XamlCompiler, question, team-Markup, product-winui3, no-issue-activity
