### ISSUE TITLE
Update v1.3 to v1.4 crash on start-up

### ISSUE THREAD

**Issue by Slion** [microsoft/microsoft-ui-xaml#8848] opened 2023-09-01 15:10 UTC
### Describe the bug

After updating from SDK v1.3 to v1.4 the app crashes during start-up.
Does not seem to have anything to do with the core features of the app.
Is it caused by the Mica changes?

### Steps to reproduce the bug

Update to v1.4 launch the app.

### NuGet package version

Windows App SDK 1.4.0: 1.4.230822000

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

Exception:

```
Exception thrown at 0x00007FFDB6B4DE84 (Microsoft.UI.Windowing.Core.dll) in Taskbar.App.exe: 0xC0000005: Access violation reading location 0x0000000000000030.
```

Callstack:

```
 	Microsoft.UI.Windowing.Core.dll!Api::ReunionApi32::GetWindowFeatureImpl(enum Core::WindowHandle,unsigned int)	Unknown
 	Microsoft.UI.Windowing.Core.dll!GetWindowFeature()	Unknown
 	Microsoft.UI.Input.dll!InputNonClientPointerSourceWinRTStatics::GetForWindowIdHelper(struct Microsoft::UI::WindowId,struct Microsoft::UI::Input::IInputNonClientPointerSource * *,bool)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!winrt::impl::factory_cache_entry<struct winrt::Microsoft::UI::Input::InputNonClientPointerSource,struct winrt::Microsoft::UI::Input::IInputNonClientPointerSourceStatics>::call<class `winrt::Microsoft::UI::Input::InputNonClientPointerSource::GetForWindowId(struct winrt::Microsoft::UI::WindowId const &)'::`2'::<lambda_1> &>(class `winrt::Microsoft::UI::Input::InputNonClientPointerSource::GetForWindowId(struct winrt::Microsoft::UI::WindowId const &)'::`2'::<lambda_1> &)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!winrt::Microsoft::UI::Input::InputNonClientPointerSource::GetForWindowId(struct winrt::Microsoft::UI::WindowId const &)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::InAppMenu::InAppMenu(class Microsoft::VisualStudio::DesignTools::UwpTap::ActivationFactoryProviderBase &,class std::shared_ptr<class Microsoft::VisualStudio::DesignTools::UwpTap::OM::ObjectIdentityService>,struct Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::InAppMenuModel &,struct winrt::Microsoft::UI::Xaml::Controls::Panel,struct winrt::Microsoft::UI::Xaml::XamlRoot,struct HWND__ *)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::UILayerManager::OnInAppMenuStateChanged(void)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::WinrtRunOnUIThread<class std::function<void > >(class Microsoft::VisualStudio::DesignTools::UwpTap::DispatcherHelper const &,enum Microsoft::VisualStudio::DesignTools::UwpTap::DispatcherPriority,class std::function<void >)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!std::_Func_impl_no_alloc<class `Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::DispatcherBindingBase<bool>::Initialize(class std::function<void >,bool)'::`5'::<lambda_1>,void>::_Do_call(void)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::SimpleBinding<bool>::Initialize(class std::function<void >,bool)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::DispatcherBindingBase<bool>::Initialize(class std::function<void >,bool)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::UILayerManager::SetBinding(class Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::NotifyingValue<bool> &,void )	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::UILayerManager::Initialize(void)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::UILayerManager::RunOnUIThread(class std::function<void > const &)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::InAppUI::UILayerManager::Initialize(struct winrt::Microsoft::UI::Xaml::Controls::Panel,struct HWND__ *)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!std::_Func_impl_no_alloc<`Microsoft::VisualStudio::DesignTools::UwpTap::WindowsXamlDiagnosticsTap::AddRoot'::`2'::<lambda_1>,void>::_Do_call()	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!Microsoft::VisualStudio::DesignTools::UwpTap::PackagedTask<void>::operator()(void)	Unknown
 	Microsoft.VisualStudio.DesignTools.WinUITap.dll!winrt::impl::delegate<winrt::Microsoft::UI::Dispatching::DispatcherQueueHandler,`Microsoft::VisualStudio::DesignTools::UwpTap::WinrtRunOnUIThreadAsync<`Microsoft::VisualStudio::DesignTools::UwpTap::WindowsXamlDiagnosticsTap::AddRoot'::`2'::<lambda_1>>'::`2'::<lambda_1>>::Invoke()	Unknown
 	CoreMessagingXP.dll!Microsoft::UI::Dispatching::DispatcherQueue::DeferInvokeCallback(void *)	Unknown
 	CoreMessagingXP.dll!CFlat::SehSafe::Execute<<lambda_a81ff790741c2a62f2197c2561f5fe49>>()	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::ActionCallback::ImportAdapter$(class CFlat::Box$1<struct CFlat::FunctionPointerAndUserData$1<long > > *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Messaging::MessageSession::Callback_InvokeDeferInvoke(class Microsoft::CoreUI::ActionCallback *,struct System::UIntPtr)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::DeferredCall::Callback_Dispatch(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::DeferredCallDispatcher::Callback_OnDispatch(void)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchNextItem(class Microsoft::CoreUI::Dispatch::DispatchItem *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::Dispatcher::Callback_DispatchLoop(enum Microsoft::CoreUI::Dispatch::RunnablePriorityMask)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::EventLoop::Callback_RunCoreLoop(enum Microsoft::CoreUI::Dispatch::RunMode)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::DrainCoreMessagingQueue(enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,void * *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatch(bool,enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,void * *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::OnUserDispatchRaw(enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,bool,void * *)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::DoWork(struct HWND__ *,enum Microsoft::CoreUI::Dispatch::UserAdapter$UserPriority,bool)	Unknown
 	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::HandleDispatchNotifyMessage(struct HWND__ *,unsigned __int64,__int64)	Unknown
>	CoreMessagingXP.dll!Microsoft::CoreUI::Dispatch::UserAdapter::WindowProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchClientMessage()	Unknown
 	user32.dll!__fnDWORD()	Unknown
 	ntdll.dll!KiUserCallbackDispatcherContinue()	Unknown
 	win32u.dll!NtUserGetMessage()	Unknown
 	user32.dll!GetMessageW()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::RunDesktopWindowMessageLoop()	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplication::StartDesktop(void)	Unknown
 	Microsoft.ui.xaml.dll!DirectUI::FrameworkApplicationFactory::Start()	Unknown
 	[External Code]	
 	[Inline Frame] hostpolicy.dll!coreclr_t::execute_assembly(int) Line 109	C++
 	hostpolicy.dll!run_app_for_context(const hostpolicy_context_t & context, int argc, const wchar_t * * argv) Line 255	C++
 	hostpolicy.dll!run_app(const int argc, const wchar_t * * argv) Line 284	C++
 	hostpolicy.dll!corehost_main(const int argc, const wchar_t * * argv) Line 430	C++
 	hostfxr.dll!execute_app(const std::wstring & impl_dll_dir, corehost_init_t * init, const int argc, const wchar_t * * argv) Line 146	C++
 	hostfxr.dll!`anonymous namespace'::read_config_and_execute(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int new_argc, const wchar_t * * new_argv, host_mode_t mode, const bool is_sdk_command, wchar_t * out_buffer, int buffer_size, int * required_buffer_size) Line 533	C++
 	hostfxr.dll!fx_muxer_t::handle_exec_host_command(const std::wstring & host_command, const host_startup_info_t & host_info, const std::wstring & app_candidate, const std::unordered_map<enum known_options,std::vector<std::wstring,std::allocator<std::wstring>>,known_options_hash,std::equal_to<enum known_options>,std::allocator<std::pair<enum known_options const ,std::vector<std::wstring,std::allocator<std::wstring>>>>> & opts, int argc, const wchar_t * * argv, int argoff, host_mode_t mode, const bool is_sdk_command, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 1018	C++
 	hostfxr.dll!fx_muxer_t::execute(const std::wstring host_command, const int argc, const wchar_t * * argv, const host_startup_info_t & host_info, wchar_t * result_buffer, int buffer_size, int * required_buffer_size) Line 579	C++
 	hostfxr.dll!hostfxr_main_startupinfo(const int argc, const wchar_t * * argv, const wchar_t * host_path, const wchar_t * dotnet_root, const wchar_t * app_path) Line 61	C++
 	Taskbar.App.exe!exe_start(const int argc, const wchar_t * * argv) Line 251	C++
 	Taskbar.App.exe!wmain(const int argc, const wchar_t * * argv) Line 322	C++
 	[External Code]	

```

**Comment by bpulliam** [comment] 2023-09-07 20:57
Duplicate of #8806

**Closed by bpulliam** 2023-09-07 20:57 UTC
Labels: team-Markup

**Comment by NicholasChrzan** [comment] 2023-09-07 23:21
Just to put the workaround here as well. You can get past this issue by turning off the "Enable in-app toolbar" from the XAML Hot Reload under debug settings.
