### ISSUE TITLE
Page Resource with name generate wrong code in c++ winrt desktop

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4649] opened 2021-03-25 07:14 UTC
Define CollectionViewSource .
```
 <Page.Resources>
        <CollectionViewSource x:Name="cvsGroups3" 
                              Source="{x:Bind SourceModel2.Groups}"
                              IsSourceGrouped="True" ItemsPath="Items"/>
</Page.Resources>
```
ref `cvsGroups3` .
```
<SemanticZoom.ZoomedInView>
                <GridView x:Name="x123" ItemsSource="{x:Bind cvsGroups3.View}" SelectionMode="None"
                          ScrollViewer.IsHorizontalScrollChainingEnabled="False"
                          ItemTemplate="{StaticResource ZoomedInTemplate}">
  
            </SemanticZoom.ZoomedInView>
````
compile error:
![image](https://user-images.githubusercontent.com/16729017/112432962-92020880-8d7c-11eb-9167-ce89a41ed61e.png)

**Comment by StephenLPeters** [comment] 2021-03-25 23:17
Can you give us more information about the app configuration you are using. Is this Winui3 from project reunion 0.5 in a desktop application written in cppwinrt?

**Comment by shelllet** [comment] 2021-03-26 03:38
yes, this is winui3 from project reunion 05 in desktop app.
this is packages.config
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Microsoft.ProjectReunion" version="0.5.0-prerelease" targetFramework="native" />
  <package id="Microsoft.ProjectReunion.Foundation" version="0.5.0-prerelease" targetFramework="native" />
  <package id="Microsoft.ProjectReunion.WinUI" version="0.5.0-prerelease" targetFramework="native" />
  <package id="Microsoft.Toolkit.Uwp.UI.Controls" version="8.0.0-preview5" targetFramework="native" />
  <package id="Microsoft.Windows.CppWinRT" version="2.0.210211.2" targetFramework="native" />
</packages>
```

this is .xaml.g.hpp
```
  void Update_(::winrt::Velkhana::ControlList obj, int32_t phase)
        {
            if (obj)
            {
                if ((phase & (NOT_PHASED | (1 << 0))) != 0)
                {
                    Update_SourceModel2(obj.SourceModel2(), phase);
                    Update_SourceModel(obj.SourceModel(), phase);
                    Update_cvsGroups3(obj.cvsGroups3(), phase);
                }
            }
        }
```
this is idl file.
```
namespace Velkhana
{
    [default_interface]
    runtimeclass ControlList : Microsoft.UI.Xaml.Controls.Page
    {
        ControlList();
        Int32 MyProperty;
        DataSource SourceModel{ get; };
        ControlInfoDataSource SourceModel2{ get; };

        Microsoft.UI.Xaml.Data.CollectionViewSource cvsGroups2{ get; };
    }
}

```
this is error info.
```
1>C:\Users\admin\source\repos\Velkhana\Velkhana\Velkhana\Generated Files\ControlList.xaml.g.hpp(732,43): error C2039: 'cvsGroups3': is not a member of 'winrt::Velkhana::ControlList'
```

**Comment by StephenLPeters** [comment] 2021-03-30 00:02
I'm guessing this is a xaml compiler bug.. @alwu-msft or @RealTommyKlein 

@jevansaks or @kennykerr for the cppwinrt perspective.

**Comment by RealTommyKlein** [comment] 2021-03-30 00:13
For C++/WinRT, x:Bind'ing to a named element also requires the element to be declared in your .idl file.  See the [documentation here](https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property#element-to-element-binding).  Though we should add a compiler error if a C++/WinRT app has bound to a named element without the named element being present in the project's winmd.

**Comment by marb2000** [comment] 2021-05-04 06:27
I do think this is the right thing to do: **_"add a compiler error if a C++/WinRT app has bound to a named element without the named element being present in the project's winmd"_**

**Comment by evelynwu-msft** [comment] 2023-07-11 00:21
Duplicate of #2721.

**Closed by evelynwu-msft** 2023-07-11 00:21 UTC
Labels: bug, area-XamlCompiler, team-Markup, product-winui3, appModel-win32, area-C++/WinRT, v0.5
