### ISSUE TITLE
WebView inside NavigationView in WinUI 2.6.1 is not interactable for Windows 10 in Left and LeftCompact modes.

### ISSUE THREAD

**Issue by bkaankose** [microsoft/microsoft-ui-xaml#5627] opened 2021-08-04 19:56 UTC
**Describe the bug**
WebView content placed inside muxc:NavigationView is not interactable for UWP apps running on Windows 10 when the control is in LeftCompact or Left modes (in Minimal mode it works fine), but fully works fine in Windows 11 (for all modes).

Events like Tapped and RightTapped seem to fire since they are coming from FrameworkElement. However, the content loaded in WebView is not interactable at all. Can't click on hyperlinks or scroll the page.

It works fine in Top and LeftMinimal modes but doesn't work for LeftCompact and Left modes. You can also set PaneDisplayMode to Auto and snap the window to make it minimal and it will work.

**Steps to reproduce the bug**
1. Create a blank UWP app and install WinUI 2.6.1
2. Place muxc:NavigationView in the page and put WebView control inside as a content.
3. Give WebView a source to display some scrollable web page.

Bug Sample Project: [https://github.com/bkaankose/NavigationViewBug](https://github.com/bkaankose/NavigationViewBug)

**Expected behavior**
WebView content should be interactable (tapping on hyperlinks, scrolling etc.)

**Version Info**
WinUI 2.6.1 on Windows 10 running build 19042 (v20H2). Bug is not reproducible in Windows 11 with the same WinUI package.

NuGet package version: 
Microsoft.UI.Xaml 2.6.1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by michael-hawker** [comment] 2021-08-04 22:27
Duplicate of #5299

**Closed** 2021-08-04 22:28 UTC
Labels: area-NavigationView, area-WebView, duplicate
