### ISSUE TITLE
WebView 2 can't be displayed in a frame

### ISSUE THREAD

**Issue by Chips1234** [microsoft/microsoft-ui-xaml#3337] opened 2020-09-27 00:30 UTC
**Describe the bug**
Hello, I'm trying to create a tabbed web browser with WebView 2. Inside a tab is a frame, and the frame is navigated to the page containing the textbox, buttons and WebView. Everything works fine, but the WebView does not display a page at all.

**Steps to reproduce the bug**
Steps to reproduce the behaviour:
1. Make a tab view
2. Place a frame as the content
3. Create a new page with a WebView 2.
4. Make the page the content of the frame
5. See error - you can't look at the WebView.

**Expected behaviour**
The WebView displays perfectly fine in a frame

**Version Info**
NuGet package version: Microsoft.WinUI 3.0.0-preview2.200713.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20215)              | Yes |
| May 2020 Update (19041)            | Yes |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
WebView does work in a frame constructed in XAML code itself, but it does not when I set the frame as a content of a tab page.

**Comment by anawishnoff** [comment] 2021-01-28 21:17
Hi, it looks like we couldn't reproduce this bug, so I'm going to close this issue. If this bug still persists in Preview 4 (which will be released in early February), please re-open the issue and let us know. Thanks!

**Closed by anawishnoff** 2021-01-28 21:17 UTC
Labels: area-WebView, team-Rendering, winui3preview

**Comment by codendone** [comment] 2021-01-29 03:04
Slight correction: we were able to repro this, but then the problem stopped reproing recently and we aren't sure exactly which change fixed it. But we believe this is fixed for Preview 4.
