### ISSUE TITLE
OverlappedPresenter `SetBorderAndTitleBar` not hide titlebar

### ISSUE THREAD

**Issue by ourfor** [microsoft/microsoft-ui-xaml#10137] opened 2024-11-03 07:09 UTC
### Describe the bug

I want the window to be resizable and hide system control button

```cpp
    MainWindow::MainWindow()
    {
        InitializeComponent();

        auto presenter = AppWindow().Presenter().as<Microsoft::UI::Windowing::OverlappedPresenter>();
        presenter.IsMaximizable(false);
        presenter.IsMinimizable(false);
        presenter.SetBorderAndTitleBar(true, false);
    }
```
![Image](https://github.com/user-attachments/assets/2dfa68f8-512c-4851-b43c-0ec872783faf)

There is a small region at the top of the window which looks like Windows is drawing part of the title bar. 

if I set resizable equals to `false`

```cpp
    MainWindow::MainWindow()
    {
        InitializeComponent();

        auto wn = try_as<IWindowNative>();

        HWND window_handle{};
        wn->get_WindowHandle(&window_handle);

        auto presenter = AppWindow().Presenter().as<Microsoft::UI::Windowing::OverlappedPresenter>();
        presenter.IsMaximizable(false);
        presenter.IsMinimizable(false);
        presenter.IsResizable(false);
        presenter.SetBorderAndTitleBar(true, false);
    }
```

![Image](https://github.com/user-attachments/assets/2c600445-6656-4f9f-bcf0-452d2f9cdc8a)

### Steps to reproduce the bug

1.  `AppWindow().Presenter().as<Microsoft::UI::Windowing::OverlappedPresenter>()`
2. `SetBorderAndTitleBar(true, false)`
3. `IsResizable(true)`

There is a small region at the top of the window which looks like Windows is drawing part of the title bar. 

### Expected behavior

There shouldn't be a small area at the top of the window

### NuGet package version

None

**Comment by karkarl** [comment] 2024-11-07 19:37
Resolving as dupe of #9978

**Closed by karkarl** 2024-11-07 19:37 UTC
Labels: needs-triage
