### ISSUE TITLE
Expander Control visuals seems incorrect 

### ISSUE THREAD

**Issue by harvinders** [microsoft/microsoft-ui-xaml#6846] opened 2022-03-17 11:42 UTC
### Describe the bug

1. The expander header area has shadow. Pay attention to bottom right of the header

![image](https://user-images.githubusercontent.com/8557046/158799887-0d899e8f-4e9f-4f57-ad69-acb6db99fd0c.png)
![image](https://user-images.githubusercontent.com/8557046/158799964-1b66a789-aa21-43aa-bfcb-106f6b2a39da.png)

2. The Expanded region doesn't stand out in light mode, dark mode it works fine. The page background is set as    `{ThemeResource ApplicationPageBackgroundThemeBrush}`

![image](https://user-images.githubusercontent.com/8557046/158800308-0c57ea97-8ab0-4fdd-83e4-ca1df1905d5e.png)
![image](https://user-images.githubusercontent.com/8557046/158800351-08940a4a-f09c-4f18-a548-29d3e61e5718.png)

### Steps to reproduce the bug

1. Create a `Expander` Control with the Page `Background ="{ThemeResource ApplicationPageBackgroundThemeBrush}"`

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by kmgallahan** [comment] 2022-03-17 13:21
Probably another dupe of #6194 @StephenLPeters ?

**Comment by ojhad** [comment] 2022-03-17 22:44
@codendone FYI another instance of gradient bug

**Closed by ojhad** 2022-03-17 22:44 UTC
Labels: duplicate, team-Rendering, product-winui3

**Comment by harvinders** [comment] 2022-03-17 23:34
@ojhad What about point 2? In light mode the expanded area background is barely distinguishable from the page background. 

![image](https://user-images.githubusercontent.com/8557046/158800308-0c57ea97-8ab0-4fdd-83e4-ca1df1905d5e.png)

However, dark mode it is easy to differentiate. 

![image](https://user-images.githubusercontent.com/8557046/158800351-08940a4a-f09c-4f18-a548-29d3e61e5718.png)
