### ISSUE TITLE
Graphical Artifacting With Border When Non-1 Scale, Non-Uniform Corner-Radius

### ISSUE THREAD

**Issue by AlgoRythm-Dylan** [microsoft/microsoft-ui-xaml#6475] opened 2021-12-13 19:11 UTC
### Describe the bug

I'm using the built-in XAML canvas and some Border elements and unfortunately I seem to have noticed a specific graphical bug that will impact my application.

The simplest thing to explain this bug is a combination of steps to reproduce and the screenshot, but in essence, if your corner-radius on a Border element is not the same on all 4 corners (for example, the value `0, 0, 6, 0`), and the scale of the Canvas that it is placed on is non-1, there will be this somewhat transparent strip leading up to that corner.

I have not completely isolated everything that directly contributes to this bug (maybe background doesn't need to be transparent, I don't know if it only applies to Canvas, etc), but I have some very short code that you can run to reproduce it.

### Steps to reproduce the bug

Create a new project
In MainWindow, add this code:
```xaml
    <Grid>
        <Canvas Background="White" x:Name="Can">
            <Border CornerRadius="0 0 10 0"
                    BorderThickness="3" 
                    BorderBrush="#000000"
                    Width="1000"
                    Height="500"
                    Canvas.Top="100"
                    Canvas.Left="100"
                    Background="#00FFFFFF"></Border>
        </Canvas>
    </Grid>
```

In MainWindow codebehind, add this code:

```c#
        public MainWindow()
        {
            this.InitializeComponent();
            Can.Scale = new System.Numerics.Vector3(0.9f, 0.9f, 1);
        }
```

### Expected behavior

A normal border with no visual artifacting/ graphical strangeness.

### Screenshots

Please take specific notice to the upper-right and lower-left corners where a strange black-ish strip can be seen, which both converge on the one rounded corner

![xamlbug](https://user-images.githubusercontent.com/8422111/145872815-a0880988-a942-48e5-a328-59a996bc530b.png)

### NuGet package version

1.0.0

### Packaging type

Packaged (MSIX)

### Windows version

Windows 11 version 21H2 (22000)

### IDE

Visual Studio 2022

**Comment by kmgallahan** [comment] 2021-12-13 23:16
Probably dupe of:

#6194 
#6207 
#6419

**Comment by AlgoRythm-Dylan** [comment] 2021-12-13 23:26
> Probably dupe of:
> 
> #6194 #6207 #6419

Yep, looks the same. I guess I was looking for just borders. At least this thread shows the behavior with a transparent background

**Comment by StephenLPeters** [comment] 2022-03-01 19:54
@gegao18 and @codendone FYI, a little more info about this issue.

**Closed** 2023-08-04 12:04 UTC
Labels: duplicate, team-Rendering, product-winui3, no-issue-activity
