### ISSUE TITLE
DWM titlebar is rendered behind WinUI3 titlebar

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/microsoft-ui-xaml#5747] opened 2021-08-22 21:23 UTC
**Describe the bug**

When using a custom titlebar in a WinUI3 desktop program (C# or C++), the DWM native titlebar is still being rendered behind WinUI3's content. (`DwmExtendFrameIntoClientArea` is still being called).

<img width="878" alt="47" src="https://user-images.githubusercontent.com/42058942/130370254-68b14f29-d051-4091-882b-92cd0510e2a8.png">

**Steps to reproduce the bug**

1) Create a new desktop project
2) Add either just a call to `ExtendsContentIntoTitleBar(true);` in the constructor of the main window or add that and a `this->SetTitleBar(TitleBar());` call.
3) Build, run, and resize the window to see

**Expected behavior**
The native window frame should not be extended at all, or WinUI should use only the native window frame instead of drawing its own. Personally, I prefer to use the DWM frame, as WinUI controls can overlap everything except the caption buttons. If the caption buttons should have their colors changed, it seems like upcoming Windows 11 DWM apis can achieve that goal: https://github.com/microsoft/WindowsAppSDK/issues/41#issuecomment-892637002

On the other hand, the jittering when resize needs to really be fixed; platform api's and UWP Core/AppWindows don't have the same problem.

**Version Info**

NuGet package version: 
[WinUI 3 - Windows App SDK 0.8: 0.8.2]

Windows app type:
| Win32            |
| :--------------- |
| YES |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.160)              | YES   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | YES |

**Comment by StephenLPeters** [comment] 2021-09-16 22:45
@pratikone FYI

**Comment by pratikone** [comment] 2021-09-23 02:07
it is a resize bug it seems. is it consistent ? can you share your project with me ? The Win32 titlebar is hidden so  that is the custom titlebar's min/max/close buttons. what you are seeing a stackpanel failing to resize properly.

**Comment by pratikone** [comment] 2021-09-29 01:03
I checked with a sample user control and it is able to work as a custom titlebar. With the points mentioned above in my last comment, can you also check the layout and width of your custom titlebar control. The draggable region is only over the real width of your custom titlebar. So if you custom titlebar 's located at center of the app with 5 unit of width, that would be the draggable region too.


I am closing this bug for now. If above mentioned techniques don't work or you have any followup questions, feel free to re-open it.

**Comment by pratikone** [comment] 2021-09-29 01:06
had accidently closed it

**Comment by pratikone** [comment] 2021-10-20 21:21
no problem. let me have a look at your project

**Comment by AzAgarampur** [comment] 2021-12-14 05:23
Any updates to this issue, now that version 1.0 stable is out? Issue still persist btw, and so does the XAML compilation error.

**Comment by pratikone** [comment] 2022-02-04 19:42
@AzAgarampur   yes actually. thanks for the patience. I have found the issue and the fix and it will be released in a future release.

**Comment by pratikone** [comment] 2022-02-04 19:43
@evelynwu-msft  that is by design. we decided not to have it in markup.

**Comment by pratikone** [comment] 2022-02-04 19:43
closing it. feel free to re-open it something changes

**Closed by pratikone** 2022-02-04 19:43 UTC
Labels: needs-triage, team-Reach, product-winui3, area-TitleBar
