### ISSUE TITLE
StackPanel applies Spacing to Collapsed items

### ISSUE THREAD

**Issue by bschoepke** [microsoft/microsoft-ui-xaml#916] opened 2019-06-21 21:19 UTC
**Describe the bug**
StackPanel applies Spacing to Collapsed child items, which means a Collapsed item causes whitespace of 2x the spacing value.

**Steps to reproduce the bug**
```xml
    <StackPanel Spacing="24" BorderThickness="2" BorderBrush="Navy" Padding="24">
        <StackPanel.Resources>
            <Style TargetType="Border">
                <Setter Property="BorderThickness" Value="1"/>
                <Setter Property="BorderBrush" Value="{ThemeResource SystemControlBackgroundBaseHighBrush}"/>
            </Style>
        </StackPanel.Resources>
        <Border>
            <TextBlock Text="..."/>
        </Border>

        <Border>
            <TextBlock Text="Hello"/>
        </Border>

        <!-- Expected: 24px whitespace between Hello and World. Observed: 48px. -->
        <Border Visibility="Collapsed">
            <TextBlock Text="..." />
        </Border>

        <Border>
            <TextBlock Text="World"/>
        </Border>

        <Border>
            <TextBlock Text="..."/>
        </Border>
    </StackPanel>
```

**Expected behavior**
Collapsed elements should not be considered in Spacing calculations.

**Screenshots**
![image](https://user-images.githubusercontent.com/6391254/59951936-590e6480-942f-11e9-923c-fd1cf8436744.png)

**Version Info**
C# UWP app targeting 1903 SDK

NuGet package version: 
n/a

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18913)              | Yes  |
| May 2019 Update (18362)            |  ? |
| October 2018 Update (17763)        | ?   |
| April 2018 Update (17134)          | ?   |
| Fall Creators Update (16299)       |  ?   |
| Creators Update (15063)            | ?   |
| Anniversary Update (14393)         | ?  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   | ?   |
| Xbox                      | ?   |
| Surface Hub          | ?    |
| IoT                         | ?    |

**Comment by robloo** [comment] 2020-06-11 02:55
I just ran across this one myself. Definitely would be a big help to fix this for cases where items are dynamically shown/hidden in a StackPanel.

**Comment by MartinZikmund** [comment] 2020-12-28 20:28
I would definitely love to see this behavior adjusted. Maybe it could be controlled by a separate property like `SkipCollapsedSpacing`. Similarly it would be useful for `Grid` where it could be used to skip spacing for empty columns/rows.

**Comment by robloo** [comment] 2020-12-29 17:53
This is more of a bug. I wouldn't advocate adding a new property to control this. Concerns about changing existing apps would be trivial. The change is non-breaking and would only slightly affect the look of some (an extremely small number) of apps.

**Comment by MartinZikmund** [comment] 2020-12-29 19:56
@robloo I am afraid people who come across this have actually employed some "hacks" to work around this (like negative margins), so it would be a breaking change. But it is probably an acceptable one. For `Grid` on the other hand, it could be a new (and useful) behavior.

**Comment by robloo** [comment] 2020-12-29 20:03
Non-breaking to me means the app will still compile, build and run without errors or crash. Of course visually these are differences but there are also differences when styling is updated from time to time. I agree that it is acceptable reguardless.

**Comment by duraz0rz** [comment] 2021-03-26 18:16
Just ran across this when trying out the `Spacing` property. We have a `TextBlock` inside a `StackPanel` that we dynamically show/hide, and it would be nice to use this property vs setting `Margin` on every child element in the `StackPanel`. Any updates?

**Comment by ZodmanPerth** [comment] 2021-07-01 06:36
I'm adding my `+1` to this.

**Comment by tomtom-m** [comment] 2021-12-03 11:20
Since there doesn't seem to be an official fix for the problem, I created a new implementation which inherits from StackPanel. My version uses margins to create spacing between items in the StackPanel, but only for those items which are visible.

Full implemenation: [StackPanelWithSpacing ](https://gist.github.com/tomtom-m/4df733e1fdb68291ed4a5100629c11c4)

```C#
private void SetSpacingForChildren(int spacing)
        {
            for (int i = 0; i < this.Children.Count; i++)
            {
                if (this.Children[i] is FrameworkElement element
                    && element.Visibility == Visibility.Visible)
                {
                    var halfSpacing = spacing / 2;
                    var topSpacing = i == 0 ? 0 : halfSpacing;
                    element.Margin = new Thickness(element.Margin.Left, element.Margin.Top + topSpacing, element.Margin.Right, element.Margin.Bottom + halfSpacing);
                }
            }
        }
```

**Comment by dansmor7** [comment] 2022-04-24 16:46
This issue makes the spacing property useless for a lot of scenarios where it's most needed.

**Comment by l619534951** [comment] 2022-07-22 04:01
two years have passed, issue should be closed if not planned.

**Comment by MartinRichards23** [comment] 2022-10-17 10:58
I'd like to see this change, I've never been able to use the Spacing property due to this, and I would use it often otherwise.

**Comment by LucaCris** [comment] 2022-11-11 14:38
This is a "one minute fix" (replicating @tomtom-m code). Please...

**Comment by Odinodin** [comment] 2022-12-05 09:02
I wasted some time on this today, is there any chance this bug will be fixed after 3.5 years?

**Comment by trungnt2910** [comment] 2022-12-12 10:02
This is the `n`th WinUI bug that I've encountered today, all of which has been opened for a few years and labeled with `needs-winui-3`.

With WinUI3 out for a while now, when will this issue (and many others with `needs-winui-3`) be finally fixed?

**Comment by robloo** [comment] 2022-12-13 02:22
@trungnt2910 Begin transition to other UI frameworks. Microsoft is killing this off for anyone but the OS team and C++ apps. I would even go as far as to say it will never be open sourced (contrary to what they will publicly state) so the community will never be able to fix issues like these. If you are using C# Avalonia will be dominant in a few years, it is already dominant in most scenarios.

Microsoft is repeating the same failures here with WinUI3 we've seen many times before. https://github.com/microsoft/microsoft-ui-xaml/issues/3639

**Comment by bogdan-patraucean** [comment] 2023-03-12 14:04
This is a basic feature that should work by default. We deserve an update on this. I encountered the same issue and it's just annoying to see it doesn't work as expected.

**Comment by bogdan-patraucean** [comment] 2023-03-12 18:45
@tomtom-m I've allowed myself to improve your solution as it doesn't take 2 aspects into consideration:

- applying the spacing when the orientation is Horizontal
- not adding extra spacing after the last element as it's not needed (only element in between should have spacing)

```
for (int i = 0; i < Children.Count - 1; i++)
        {
            if (Children[i] is FrameworkElement child && child.Visibility == Visibility.Visible)
            {
                child.Margin = new Thickness(child.Margin.Left, child.Margin.Top, Orientation is Orientation.Horizontal ? gap : child.Margin.Right, Orientation is Orientation.Vertical ? gap: child.Margin.Bottom);
            }
        }
```

**Comment by LucaCris** [comment] 2023-03-23 14:54
Correction, @bogdan-patraucean :

`Orientation is Orientation.Horizontal ? child.Margin.Right + gap : child.Margin.Right`

and the same for the other side...

**Comment by bogdan-patraucean** [comment] 2023-03-25 19:09
@LucaCris the idea is to place the spacing only when the orientation is set to that particular one, otherwise the default Margin can be applied, not viceversa.

**Comment by LucaCris** [comment] 2023-04-01 16:18
> @LucaCris the idea is to place the spacing only when the orientation is set to that particular one, otherwise the default Margin can be applied, not viceversa. Just test it, it works.

The implicit item margin **must be present every time**. Plus the gap when needed...

**Comment by fabianoriccardi** [comment] 2023-06-06 16:33
Any updates? Almost 4 years since this issue was opened... I'm testing WinUI3, but this kind of *unexpected behavior* are annoying and descouraging for the adoption of this library.

**Comment by LucaCris** [comment] 2023-06-08 12:34
> Any updates? Almost 4 years since this issue was opened... I'm testing WinUI3, but this kind of _unexpected behavior_ are annoying and discouraging for the adoption of this library.

Do not exagerate... The library is very good. There are some minor problems only.

**Comment by robloo** [comment] 2023-06-08 12:42
That wasn't an exaggeration by any means. It is an example of pain point that has never been fixed (but should have been easy to resolve). It's why, among many other things, many companies (including mine) dropped UWP/WinUI. Even MAUI is adding a WPF backend because WinUI 3 future is in question.

**Comment by trungnt2910** [comment] 2023-06-08 13:11
@robloo 

> Even MAUI is adding a WPF backend because WinUI 3 future is in question.

A bit off-topic, but where did you get this information?

**Comment by fabianoriccardi** [comment] 2023-06-08 17:10
> A bit off-topic, but where did you get this information?

I'm curious too, it is not the first time I read similar comment un WinUI team.

> You can't event set a Min or Max width and height for a Window. 

Moreover, you cannot either set the width/height of the Window, you have to get AppWindow to do it. Nothing near to an issue, but it seems I'm not using a "native" framework.

> It is an example of pain point that has never been fixed.

Exactly, there are many bugs also on TreeView (I have performed a query and there are 73 open issues, I have personally hit few of them), and this is a quite basic component, TreeView exists since WinForms and even before.

Now, I'm not really blaming the developers, I know that if man-power and budget is not enough the result cannot be satisfying, but I would understand if investing in this framework will pay in the future. 

Currently I'm not giving up, just questioning :)

**Comment by robloo** [comment] 2023-06-08 17:49
> A bit off-topic, but where did you get this information?

At this point let's just say rumors from the BUILD conference.

**Comment by Basnederveen** [comment] 2023-08-28 17:31
This is still the case?

**Comment by JJBrychell** [comment] 2024-01-26 21:14
Fix is in to not add spacing for collased items.  It is scheduled for 1.5.

**Closed by JJBrychell** 2024-01-26 21:14 UTC
Labels: bug, area-Layouts, needs-winui-3, team-Controls, fixed-internally

**Comment by bogdan-patraucean** [comment] 2024-01-26 21:26
@JJBrychell awesome news, I can finally ditch my custom Stackpanel.

**Comment by legistek** [comment] 2024-05-04 17:29
`Grid` has this issue too.

**Comment by codendone** [comment] 2024-05-06 05:16
See #9491 for `Grid`.
