### ISSUE TITLE
UWP XAML Rotation property does not work from markup/creation

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#2302] opened 2020-04-17 01:44 UTC
(migrated from ADO 23848007)

The [Rotation](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.rotation?view=winrt-18362) property does not work from markup. It however works when updating it in code behind (e.g. in a button click handler) but it _should_ just work. An alternative is to use a rendertransform.

```xml
<Page
    x:Class="Centerpoint.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Centerpoint"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid>
        <Border Background="Red" Width="400" Height="400">
            <TextBlock Rotation="45">Hello</TextBlock>
        </Border>
    </Grid>
</Page>
```

**Comment by JeanRoca** [comment] 2020-11-17 20:40
Closing as duplicate of #2048

**Closed** 2020-11-17 20:40 UTC
Labels: area-Parser, bug, team-Markup

**Comment by asklar** [comment] 2020-11-17 20:49
@JeanRoca that's a different problem... this doesn't result in a compile time error, this just doesn't do anything

**Comment by JeanRoca** [comment] 2020-11-18 04:27
This has been fixed for WinUI 3.
