### ISSUE TITLE
TextBox cursor is positioned at the beginning when using a Converter that changes the text length

### ISSUE THREAD

**Issue by MichalMucek** [microsoft/microsoft-ui-xaml#7946] opened 2022-11-21 17:07 UTC
### Describe the bug

When using the TextBox control with a Converter that changes text length, the text cursor is positioned at the beginning (i.e. SelectionStart is set to zero). An example of such a Converter can be applying a dot-decimal notation. In that case, the cursor "jumps" after a separation character is added.

### Steps to reproduce the bug

```csharp
public class TextToSeparatedCharsConverter : IValueConverter
{
    public object Convert(object value, Type targetType, object parameter, string language)
    {
        if (value is not string text || parameter is not string separator) throw new ArgumentException();
        if (text.IsNullOrEmpty()) return string.Empty;

        var formattedChars = text.Trim().Select(c => c + separator).ToArray();
        var joinedFormattedChars = string.Join(string.Empty, formattedChars);
        var readyText = joinedFormattedChars.Remove(joinedFormattedChars.Length - (separator.Length), separator.Length);

        return readyText;
    }

    public object ConvertBack(object value, Type targetType, object parameter, string language)
    {
        if (value is not string text || parameter is not string separator) throw new ArgumentException();
        if (text.IsNullOrEmpty()) return string.Empty;

        return text.Replace(separator, string.Empty, StringComparison.InvariantCulture);
    }
}
```
```xaml
<TextBox Text="{x:Bind ViewModel.ExampleText, 
                       Mode=TwoWay, 
                       UpdateSourceTrigger=PropertyChanged, 
                       Converter={StaticResource TextToSeparatedCharsConverter}, 
                       ConverterParameter=.}"/>
```

### Expected behavior

It is expected to leave the cursor where it went after a character was typed and separation added. Preferably, keep the cursor at the end if it was at the end before a text was converted.

### NuGet package version

WinUI 3 - Windows App SDK 1.2.1: 1.2.221116.1

### Windows version

Windows 11 (21H2): Build 22000

### Additional context

The issue also occurs for a Converter that doesn't change the text length. An example is a converter that replaces all characters with the password-like dot symbol (U+2022).

**Comment by MichalMucek** [comment] 2022-12-12 09:21
The issue isn't triaged yet. Is more information needed on it?

**Comment by JJBrychell** [comment] 2024-02-28 00:08
This behavior is by design.  If the text in a text box is replaced then we reset the  selection to the beginning of the line because we have no idea where the selection should be placed.  I suppose there could be some advanced logic written that compares the before and after strings and makes some kind of the judgements, but we don't do that currently and I doubt that we ever would.

Let's take your example.  It appears that you want to be able to type a string such as "abc" and have it show up as "a.b.c".  Seems like a valid scenario, but let's look at it in practice and what happens if the TextBox maintains the current position after the converter replaces the text.

User starts with an empty text box.  Caret at position 0 and type an 'a' putting the cursor at position 1 with text string of "a".  The converter does nothing (because there is only one character).  Textbox keeps a position of 1 and all looks good.

User types a "b".  The caret is moved to position 2 and the text becomes "ab".  This goes into the converter and comes back out as "a.b".  If the text box maintains the previous position of 2, the caret will be between the "." and the "b".  This is probably not what you want and certainly not what the user would expect. 

One might argue that if the caret is at the end of the string, we might special case that and keep it there after the text is replaced.  Except, what if the converter is one that always ensures a decimal point in the number (e.g. "123" should be "123.".  In this case when the user types a "1" the converter would change it to "1." and if we followed the "leave at the end" semantic, then the next character typed by the user would be after the decimal point.  Again, probably not what is expected.

There is simply no way for the text box to know where the caret should be after the text is replaced.  So the design is, if the text is replaced (which is what a converter does), selection is reset and the caret is moved to the beginning of the string.

So how could we achieve the desired effect?

Typically, this kind of is done in the LostFocus event and not with a converter.  During the LostFocus event, the string is updated to the correct format (e.g. "abc" would be changed to "a.b.c").  Sometimes this is paired with the GotFocus event and the string is "unformatted" when the textbox receives focus.  So "a.b" would be converted to "ab" in GotFocus, and when the user is done editing it (say by changing it to "abc") then LostFocus would format it back (to "a.b.c").

If you are really looking for a dynamic interaction, rather than using a converter, you can "roll your own" semantics for how to position the caret by handling the TextChanging and SelectionChanging events.

DISCLAIMER: This code is for demonstration purposes only and is not intended to be real world code.  It most certainly needs to be tested and hardened to defects and may have performance impacts (e.g. if it were me, I would throttle the formatting updates).  This is not a recommended approach, but simple a possibility.

By creating a derived control from TextBox we can extend the functionality to provide the formatting suggested in the original post.
```
    public sealed class FancyTextBox : TextBox
    {
        // String to use as separator - make a dependency property if desired.
        public String Separator { get; set; }

        // Copy of the conveter used in the example to convert he strings.
        private static TextToSeparatedCharsConverter Converter = new TextToSeparatedCharsConverter();

        // Variable indicating where we want the caret to end up.  A negative value indicates
        // just leave it in its natural position.
        int forceCaretPosition = -1;
    }
```
Define a dependency property for the RawText (which we can use for binding):

```
        public static readonly DependencyProperty RawTextProperty = DependencyProperty.Register(
            "RawText", typeof(String), typeof(FancyTextBox), new PropertyMetadata(null, OnRawTextChanged));
        public String RawText
        {
            get { return (String)GetValue(RawTextProperty); }
            set { SetValue(RawTextProperty, value); }
        }
        private static void OnRawTextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e)
        {
            // When the RawText changes we want to format it and push it into our Text property.
            ((FancyTextBox)d).FormatRawText();
        }
```
In the constructor, register for the events we want and do anything else we need to do:
```
        public FancyTextBox()
        {
            this.DefaultStyleKey = typeof(TextBox);
            TextChanging += OnTextChanging;
            SelectionChanging += OnSelectionChanging;
            Separator = ".";
        }
```
In the TextChanging event we to determine how (or if) it will affect our raw text and then ensure that our text is still in the property format.
```
        private void OnTextChanging(TextBox sender, TextBoxTextChangingEventArgs args)
        {
            // Start by assuming that we will not change the caret position
            forceCaretPosition = -1;

            // If it is only a format change, we don't need to do anything.
            if (!args.IsContentChanging) return;

            // What will the change do to our raw text?
            var rawText = (String)Converter.ConvertBack(Text, typeof(String), Separator, null);
            if (rawText == RawText)
            {
                // The raw text hasn't changed, but we want to reformat it (since the user could have,
                // for example, deleted a separator and we want to add it back).
                FormatRawText();
            }
            else
            {
                // Update the raw text and let it request that it be reformatted.
                RawText = rawText;

            }
        }
```
We then want to intercept the selection change back to the front of the string and insert our own if necessary:

```
        private void OnSelectionChanging(TextBox sender, TextBoxSelectionChangingEventArgs args)
        {
            // If we are forcing the caret position, do it here
            if (forceCaretPosition >= 0)
            {
                SelectionStart = forceCaretPosition;
                SelectionLength = 0;
                forceCaretPosition = -1;
            }
        }
```
And this is the workhorse function that will take our raw data, reformat it, determine where the next caret position should be and request that it be put there.
```
        private void FormatRawText()
        {
            int caretPosition = SelectionStart;  
            int characterAfterCaret = Text.Length - caretPosition;  
            string newText = (String)Converter.Convert(RawText, typeof(String), Separator, null);

            if (newText != Text) 
            {
                if (characterAfterCaret > newText.Length)
                {
                    // If our text has gotten smaller then we will have truncated from the end of the string, so just put the 
                    // caret there.
                    forceCaretPosition = newText.Length;
                }
                else if (newText.Substring(newText.Length - characterAfterCaret) == Text.Substring(Text.Length - characterAfterCaret))
                {
                    //  If all the characters following the insertion point are the same, then we will just move to the
                    //  equivalent insertion point.
                    forceCaretPosition = newText.Length - characterAfterCaret;

                    // But, if we also inserted a separator at that spot, then make sure we are before that.
                    if (forceCaretPosition >= Separator.Length && 
                       newText.Substring(forceCaretPosition - Separator.Length, Separator.Length) == Separator)
                    {
                        forceCaretPosition -= Separator.Length;
                    }
                }
                Text = newText;
            }
         }
```
Then hook it up:
```
<local:FancyTextBox RawText="{x:Bind ViewModel.ExampleText, Mode=TwoWay}"/>
```
This gives you a working version of what it seem like you were attempting to do.  Note though that when getting this fancy, it is going to be hard to get right and performant.  It was mentioned above that some throttling might be needed if the user is rapidly updating the text (e.g. holding down a key to get it to repeat).  In addition, there will be corner cases or additional customizations that might be needed.  For example, do you really want the deletion of a separator character in the text box to appear to do nothing?  Do you want a different caret position depending on the direction the user is moving (e.g. if they use a delete key as opposed the backspace key).  These are all the kinds of things that need to be considered.  And that is before we even get to globalization and IMEs and multi keystroke characters.

With all that, and given there are also a lot of assumptions in the code above as to what the converter will do to the text, this is not a feature that would be able to be implemented in a generic, robust and performant manner.  Hence, we are going to close this issue as by design.

**Closed by JJBrychell** 2024-02-28 00:08 UTC
Labels: bug, area-TextBox, team-Controls
