### ISSUE TITLE
Unable to reorder tabitems in tabview winui 3

### ISSUE THREAD

**Issue by roonius** [microsoft/microsoft-ui-xaml#3106] opened 2020-08-12 10:03 UTC
**Describe the bug**
We were able to reorder tabitems in tabview in winui 2.4
Same application in winui 3 preview 2 displays "negative" sign
**Steps to reproduce the bug**
Create a tabview with 'CanReorderItems" property set to true
Add few tabitems
Try to reorder them

**Expected behavior**
TabItems reordered as in WinUI 2.4

**Version Info**
WinUI 3 Preview 2 Windows 10

**Comment by StephenLPeters** [comment] 2020-08-13 23:26
Drag and drop is not supported with the Winui 3 preview 2.  #2715 is the same issue.

**Comment by StephenLPeters** [comment] 2020-08-13 23:27
#2783 also, I'm going to close this as a duplicate of that issue

**Closed by StephenLPeters** 2020-08-13 23:27 UTC
Labels: area-TabView, winui3preview
