### ISSUE TITLE
CommandBarFlyout Failed to Follow System Theme Change

### ISSUE THREAD

**Issue by Jack251970** [microsoft/microsoft-ui-xaml#9820] opened 2024-07-16 15:43 UTC
### Describe the bug

The colour of the text in some menus of CommandBarFlyout does not adjust automatically when the Windows system theme switches between dark and light.
Same to the closed issue [#4970](https://github.com/microsoft/microsoft-ui-xaml/issues/4970).

### Steps to reproduce the bug

1. Under light mode, set App theme to 'Use system setting', and then open one CommandBarFlyout.
2. Don't close app, and change to dark mode. (Take WinUI Gallery for example, details are in [here](https://github.com/microsoft/WinUI-Gallery/issues/1583))
![image](https://github.com/user-attachments/assets/822e1c43-ccf1-4b70-8c04-0c39d4731b3b)
3. Don't close app, and change to dark mode.
![image](https://github.com/user-attachments/assets/bebe2f40-a978-4f86-970b-6ba36bc3079e)

### Expected behavior

The text color should change so that the text remains easily visible.

### NuGet package version

WinUI 3 - Windows App SDK 1.5.5: 1.5.240627000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by codendone** [comment] 2024-07-16 20:35
This should be a duplicate of #8077. You can try a 1.6-experimental build to test the fix.

**Closed by codendone** 2024-07-16 20:35 UTC
Labels: bug, needs-triage
