### ISSUE TITLE
Setting app icon and title is unreasonably complicated in WinAppSDK

### ISSUE THREAD

**Issue by asklar** [microsoft/microsoft-ui-xaml#6406] opened 2021-11-30 03:00 UTC
There are a number of reports of this sprinkled across this and the appsdk repo but filing this to track getting a resolution.
Today if you want to set the app icon and title, there are a few problems:
1) Window.Title doesn't work from markup (you get a build failure that is not useful). This should be fixed.
2) Setting the icon requires using the under-documented `IWindowNative` API and then dipping down to window messages

Instead, Window should have an Icon property; maybe multiple ones:
- TaskbarIcon
- StartIcon
- TitleBarIcon

**Comment by asklar** [comment] 2021-12-02 06:36
In the meantime, the docs for IWindowNative have been updated with C++ and C# samples.

**Comment by sylveon** [comment] 2021-12-02 06:43
Start icon is something you set in the app package (if packaged) or start menu shortcut file (typically via an installer framework), not XAML

**Comment by bpulliam** [comment] 2022-10-18 21:10
Duplicate of #5773

**Closed by bpulliam** 2022-10-18 21:10 UTC
Labels: area-AppWindow, needs-triage, team-Reach, product-winui3
