### ISSUE TITLE
Imagebrush display issue in pivot control?

### ISSUE THREAD

**Issue by Linjie123** [microsoft/microsoft-ui-xaml#7718] opened 2022-09-13 09:42 UTC
### Describe the bug

I use a pivot control in my application, add the same unit template, and use an absolute path for the imagebrush in the border, but the deployed application only displays the background on the first page, and the rest are not displayed, and the development tools are also No error, I can't figure out how to solve the problem

### Steps to reproduce the bug

1.
2.
3.

### Expected behavior

<Page x:Class="Project_Tools.Views.OfficePage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:animations="using:CommunityToolkit.WinUI.UI.Animations"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:offices="using:Project_Tools.Models.OfficeModel"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
      mc:Ignorable="d">

    <Page.Resources>
        
        <DataTemplate x:Key="ContentTemplate" x:DataType="offices:Office">
            <Border Width="220"
                    Height="100"
                    HorizontalAlignment="Stretch"
                    VerticalAlignment="Stretch"
                    BorderBrush="Transparent"
                    BorderThickness="1"
                    CornerRadius="5">
                <Border.Background>
                    <ImageBrush ImageSource="{Binding Image}"
                                Opacity="0.6"
                                Stretch="UniformToFill" />
                </Border.Background>
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition Height="Auto" />
                        <RowDefinition />
                    </Grid.RowDefinitions>
                    <TextBlock Grid.Row="0"
                               Margin="10,10,0,0"
                               HorizontalAlignment="Left"
                               VerticalAlignment="Top"
                               FontSize="15"
                               Text="{Binding Title}"
                               TextWrapping="WrapWholeWords" />
                    <StackPanel Grid.Row="1"
                                Margin="10,10,0,0"
                                Orientation="Vertical">
                        <StackPanel Orientation="Horizontal">
                            <TextBlock FontSize="15"
                                       Text="{Binding Views}"
                                       TextWrapping="Wrap" />
                            <TextBlock Margin="5,0,0,0"
                                       FontSize="15"
                                       Text="查看"
                                       TextWrapping="Wrap" />
                        </StackPanel>
                        <StackPanel Orientation="Horizontal">
                            <TextBlock FontSize="15"
                                       Text="{Binding Likes}"
                                       TextWrapping="Wrap" />
                            <TextBlock Margin="5,0,0,0"
                                       FontSize="15"
                                       Text="喜欢"
                                       TextWrapping="Wrap" />
                        </StackPanel>
                        <TextBlock FontSize="1"
                                   Text="{Binding Link}"
                                   TextWrapping="Wrap"
                                   Visibility="Collapsed" />
                    </StackPanel>
                </Grid>
            </Border>
        </DataTemplate>
        <Style x:Key="ItemContainerStyle" TargetType="GridViewItem">
            <Setter Property="Margin" Value="5" />
        </Style>
    </Page.Resources>

    <Pivot>
        <PivotItem>
            <PivotItem.Header>
                <TextBlock FontSize="15" Text="WORD教程" />
            </PivotItem.Header>
            <GridView x:Name="Gv_1"
                      animations:ItemsReorderAnimation.Duration="00:00:00.8000000"
                      IsItemClickEnabled="True"
                      ItemClick="Gv_1_ItemClick"
                      ItemContainerStyle="{StaticResource ItemContainerStyle}"
                      ItemTemplate="{StaticResource ContentTemplate}"
                      ItemsSource="{Binding Office_Word, Mode=OneWay}" />
        </PivotItem>
        <PivotItem>
            <PivotItem.Header>
                <TextBlock FontSize="15" Text="EXCEL教程" />
            </PivotItem.Header>
            <GridView x:Name="Gv_2"
                      animations:ItemsReorderAnimation.Duration="00:00:00.8000000"
                      IsItemClickEnabled="True"
                      ItemClick="Gv_2_ItemClick"
                      ItemContainerStyle="{StaticResource ItemContainerStyle}"
                      ItemTemplate="{StaticResource ContentTemplate}"
                      ItemsSource="{Binding Office_Excel, Mode=OneWay}" />
        </PivotItem>
        <PivotItem>
            <PivotItem.Header>
                <TextBlock FontSize="15" Text="PPT教程" />
            </PivotItem.Header>
            <GridView x:Name="Gv_3"
                      animations:ItemsReorderAnimation.Duration="00:00:00.8000000"
                      IsItemClickEnabled="True"
                      ItemClick="Gv_3_ItemClick"
                      ItemContainerStyle="{StaticResource ItemContainerStyle}"
                      ItemTemplate="{StaticResource ContentTemplate}"
                      ItemsSource="{Binding Office_PPt, Mode=OneWay}" />
        </PivotItem>
        <PivotItem>
            <PivotItem.Header>
                <TextBlock FontSize="15" Text="WPS教程" />
            </PivotItem.Header>
            <GridView x:Name="Gv_4"
                      animations:ItemsReorderAnimation.Duration="00:00:00.8000000"
                      IsItemClickEnabled="True"
                      ItemClick="Gv_4_ItemClick"
                      ItemContainerStyle="{StaticResource ItemContainerStyle}"
                      ItemTemplate="{StaticResource ContentTemplate}"
                      ItemsSource="{Binding Office_Wps, Mode=OneWay}" />
        </PivotItem>
    </Pivot>
</Page>

This is ViewModel: 
public ObservableCollection<Office> Office_Word { get; set; } = new ObservableCollection<Office>
        {
            new Office { Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "WORD教程全部", Description = "", Link = new Uri("http://www.wordlm.com/word/") },
            new Office {Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "WORD技巧大全", Description = "", Link = new Uri("http://www.wordlm.com/word/wjqdq/") },
            new Office { Image="ms-appx:///Assets/OfficeImages/office.jpg",Title = "WORD制作表格不求人", Description = "", Link = new Uri("http://www.wordlm.com/word/zzbg/") },
            new Office {Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "全民学WORD", Description = "", Link = new Uri("http://www.wordlm.com/word/qmx/") },
            new Office { Image="ms-appx:///Assets/OfficeImages/office.jpg",Title = "WORD分分钟排版", Description = "", Link = new Uri("http://www.wordlm.com/word/ffzpb/") },
            new Office {Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "WORD模板下载", Description = "", Link = new Uri("http://www.wordlm.com/word/wjpmbxz/") },
            new Office { Image="ms-appx:///Assets/OfficeImages/office.jpg",Title = "WORD宏案例", Description = "", Link = new Uri("http://www.wordlm.com/word/hong/") },
            new Office {Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "WORD2010教程", Description = "", Link = new Uri("http://www.wordlm.com/word/list_39_1.html") },
            new Office {Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "WORD2013教程", Description = "", Link = new Uri("http://www.wordlm.com/word/list_83_1.html") },
            new Office {Image="ms-appx:///Assets/OfficeImages/office.jpg", Title = "WORD2016从入门到精通课程", Description = "", Link = new Uri("http://www.wordlm.com/shipin/word2016.html") },
        };

### Screenshots

![image](https://user-images.githubusercontent.com/26216203/189867650-45b7718e-7e1f-4358-880d-96fe031b5380.png)
![image](https://user-images.githubusercontent.com/26216203/189867712-bf3a7237-1539-42a5-baa4-60eaf71024a2.png)
![image](https://user-images.githubusercontent.com/26216203/189867751-104a077f-7146-47c7-831b-91c4477233c8.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.1.4

### Windows app type

- [ ] UWP
- [ ] Win32

### Device form factor

Desktop

### Windows version

Windows 11 (22H2): Build 22621

**Comment by michael-hawker** [comment] 2023-01-12 19:37
Pretty sure this is a duplicate of #7809 (it has a simpler example, and I have a detailed repro of the scenario, so going to add my details to that issue)

**Closed** 2023-08-03 22:53 UTC
Labels: bug, area-Pivot, team-Controls, product-winui3, no-issue-activity
