### ISSUE TITLE
Unable to click, drag and release in menus

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/microsoft-ui-xaml#815] opened 2019-06-06 09:33 UTC
**Describe the bug**

In various non-UWP apps (easiest examples being Chrome, Firefox and Control Panel), I'm able to click on a MenuBar item and then the menu would show up automatically and then I can keep holding and drag on an item to select it.

**Steps to reproduce the bug**

1. Go to 3D Viewer
2. Click on Help and don't let go
3. Drag mouse down to Settings (easiest on mouse or touchpad)
4. Release

**Expected behavior**

You would see 3D Viewer settings.

**Version Info**

NuGet package version: 
Unsure

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            |Yes |
| October 2018 Update (17763)        |Yes |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 |Yes|

**Additional information**
These are a little similar to this if you don't understand what I'm saying: https://github.com/flutter/flutter/issues/5064
https://github.com/mozilla-mobile/reference-browser/issues/420
In 2013 Android got this: https://www.androidpolice.com/2013/11/01/kitkat-feature-spotlight-chrome-apps-drag-and-release-style-overflow-menu-button-is-now-used-system-wide/
macOS, GNOME and KDE users are very familiar with this behaviour but so are many Windows users. Most users know that they can find this behaviour in apps like Chrome and Office, but users don't use enough WinUI apps to know that WinUI doesn't have this. But I can say B2B apps get reports like this all the time.

**Comment by kikisaints** [comment] 2019-06-06 17:16
Interesting! I never knew I could do this on Chrome 😄. I think this is more a feature request than a bug? You mentioned that this can be done in Control Panel too, could you describe where you can do this?

**Comment by jevansaks** [comment] 2019-06-06 17:20
This is how win32 menus have worked for a long time and WPF did work to match that behavior. We should do this in XAML too.

**Comment by DragoCubed** [comment] 2019-06-07 02:26
I think poopooracoocoo is talking about programs and features in control panel. Love the name lmao

**Comment by jevansaks** [comment] 2019-06-07 03:43
You can see this pretty much anywhere: e.g. notepad (Win32), Visual Studio (WPF).

**Comment by DragoCubed** [comment] 2019-06-07 07:02
It even works in VS Code which uses Chromium/Electron

**Comment by Poopooracoocoo** [comment] 2019-06-08 13:42
Does this have anything to do with accessibility? Would this also work with touch like the two issues I linked to above?

**Comment by jevansaks** [comment] 2019-06-10 17:44
Yes, it should work with touch. I don't believe this breaks any accessibility guidelines but it does make our menus feel unfamiliar to users who are used to this behavior, so it's something we should fix.

**Comment by Poopooracoocoo** [comment] 2019-07-10 13:54
so i noticed that this happens in the ribbon of file explorer too. probs happens in many other places

**Comment by shaheedmalik** [comment] 2019-10-16 00:53
This is how all Win32 apps were designed. Windows as had this as long as I remember (and I've been using Windows since 3.1) It should be treated as a bug if UWP doesn't have it. UWP should have it as well.

It would greatly benefit touch users as well as they could tap and hold and let go on the menu item of their choice.

**Comment by Poopooracoocoo** [comment] 2021-03-20 10:03
@leonMSFT hi. you were the last person afaik to have worked on the menubar control... so uh. could you look at this? 🥺

**Comment by Poopooracoocoo** [comment] 2021-07-14 19:08
@StephenLPeters hey uh apparently this is an issue with Windows 11? i've never used it but i've heard about this issue being there.

**Comment by Poopooracoocoo** [comment] 2021-08-10 01:45
@kikisaints @chigy @jevansaks literally tagging everyone at this point. i don't even think kiki works on winui anymore. been that long...

**Comment by chigy** [comment] 2021-08-10 18:59
@Poopooracoocoo , I agree that this is something we should consider, however I believe this work will require OS level change that we are currently not taking. So it is not on our roadmap to act on right away especially given it is not causing critical errors to user experience either.

**Comment by StephenLPeters** [comment] 2021-08-10 22:32
Yes, we won't be able to address this in Winui2, it needs winui3

**Comment by shaheedmalik** [comment] 2021-08-10 22:49
> Yes, we won't be able to address this in Winui2, it needs winui3

But when is WinUI 3 coming to UWP?

**Comment by DragoCubed** [comment] 2021-09-30 14:22
@gabbybilka now that WinUI 3.0 is heading towards release and that Windows 11 (which uses WinUI controls in more areas) has nearly been released, are there any updates on the priority of this feature?

**Comment by Poopooracoocoo** [comment] 2023-01-06 13:58
WinUI 3 and the WinAppSDK have released "stable" versions since creating this issue. I hope that this will be addressed.

**Comment by Poopooracoocoo** [comment] 2023-07-29 07:17
Don't close this

**Comment by bkudiess** [comment] 2024-07-11 22:28
I will be closing this issue as it is not a bug, but a feature proposal. You can track the ask here:
#5600.

**Closed by bkudiess** 2024-07-11 22:28 UTC
Labels: bug, area-Menus, needs-winui-3, team-Controls
