### ISSUE TITLE
WinUI in VS 2019 Preview gives error "... requires WinRT.Runtime.dll version 1.2 or greater" and more

### ISSUE THREAD

**Issue by tedekeroth** [microsoft/microsoft-ui-xaml#4894] opened 2021-04-25 15:00 UTC
**Describe the bug**
Unable to build "Blank App, Packaged (WinUI 3 in Desktop)". The error list contains:

> This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater. 
> Please update to .NET 5.0.6 SDK or later.  Or add a temporary Microsoft.Windows.SDK.NET.Ref FrameworkReference of version > 10.0.*.16 or later.

I also note that I have yellow triangles in the Dependencies regarding the WinUI, see below.

**Steps to reproduce the bug**
1. I installed the VS 2019 Preview from microsofts webpage, version is Version 16.10.0 Preview 2.1
2. I followed the instructions here: https://docs.microsoft.com/en-us/windows/apps/project-reunion/get-started-with-project-reunion#set-up-your-development-environment and here https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop to setup Reunion
3. Open VS2019 Preview, create new Project ""Blank App, Packaged (WinUI 3 in Desktop)"
4. Build

**Expected behavior**
I expected the app to build and run, with no apparent errors.

**What happened instead**
In step 5 here: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop, after clicking OK, I get this error message:
![image](https://user-images.githubusercontent.com/10088477/115998258-b56fdb80-a5e6-11eb-962c-ad0ff013a6d1.png)

After clicking OK in that error popup, the project loads, and I can see errors in the dependencies:
![image](https://user-images.githubusercontent.com/10088477/115998370-2d3e0600-a5e7-11eb-9c81-1131b740b802.png)

I also note that the "Windows Application Packaging Project" that is supposed to be created (according to the URL above), is not created.

**Version Info**
WinUI packages version: 0.5.5
Windows app type: desktop
OS: Win 10 20H2 build 19042.928

NuGet package version: 
See above.

Windows app type:
Ehm, I am not sure. It says "Output type: Window Application", so I guess Win32?

| UWP              | Win32            |
| :--------------- | :--------------- |
| ? | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
I have used the `maui-check` tool, and that says that everything is OK:

![image](https://user-images.githubusercontent.com/10088477/115998460-9d4c8c00-a5e7-11eb-9fc5-dd3b3c13b48a.png)

**Comment by tedekeroth** [comment] 2021-04-25 16:38
I just noticed this thread, which reports the same problem:

https://github.com/microsoft/ProjectReunion/issues/740

I didnt see it at first, as I was directed to https://github.com/microsoft/microsoft-ui-xaml for any WinUI bugs found. This bug report is in https://github.com/microsoft/ProjectReunion.

Thanks.

**Comment by asklar** [comment] 2021-04-26 17:45
Duplicate of microsoft/ProjectReunion#740

**Comment by asklar** [comment] 2021-04-26 17:46
Workaround is to add a global.json in the solution folder:
```json
{
"sdk": {
"version": "5.0.202"
}
}

```

**Comment by tedekeroth** [comment] 2021-04-27 05:28
Hello, I tried that, and yes, the errors did disappear, but it wont start anyways. Perhaps a new ticket is required, but the error when running it in debug is:

> System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
> Inner Exception:
> COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

**Comment by asklar** [comment] 2021-04-27 06:14
@tedekeroth you have to create the global.json file first, then create the project (which should create 2 projects). If you create the global.json file after you get that error, only the app project will have been created, not the packaging project which is the one you want to run, which is probably why you're hitting the error.

**Comment by asklar** [comment] 2021-04-27 06:14
in other words: delete the projects that were created, ensure you have an empty folder, add the global.json, then create the solution in that folder which should create 2 projects in that solution.

**Comment by tedekeroth** [comment] 2021-04-27 06:19
You suggest that add the global.json to a folder, then create a solution (.sln) inside that same folder, and then on top of that add the projects? I will try that and report back!

**Comment by asklar** [comment] 2021-04-27 06:20
yes, those are the steps that worked for me

**Comment by tedekeroth** [comment] 2021-04-27 07:23
Alright, that worked in the sense that the Package project was created correctly. I then added the ItemGroup in csproj. It then builds, and looks ok, even though it does not start, it fails in runtime as stated above.

**Comment by asklar** [comment] 2021-04-27 07:27
yes, the package project is the one to start, can you try that?

**Comment by tedekeroth** [comment] 2021-04-27 07:30
Yes, that worked. I was very confused from this thread [here](https://github.com/microsoft/microsoft-ui-xaml/issues/4537#issuecomment-800721624), where I thought they said that it is _not_ the package project that should be started:

> As a sanity check, the app being debugged doesn't have "Package" in the name, which is the default for packaging projects (e.g. "ETIHub.TDHub.Demo.UI (Package)" instead of "ETIHub.TDHub.Demo.UI"). @s3nt1n3l-hub can you confirm the wapproj/packaging project is being run instead of the unpackaged application?

That sounded to me that Packaging shouldn't be run. Apparently, I misread of they said the wrong thing.

Thanks for your input asklar =)

**Comment by StephenLPeters** [comment] 2021-04-28 23:27
@alwu-msft FYI

**Comment by AghaKhan** [comment] 2021-04-29 12:55
Today I tried to build simple application with WinUI, but it failed. 
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>Agha</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.6" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.6" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.6" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
</Project>

I tried everything as suggested, but it didn't work. Maybe due to change version 0.5.5 to 0.5.6

**Comment by codendone** [comment] 2021-04-30 03:25
@AghaKhan Did you try the option of adding this block in your .csproj file?
```
<ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />
</ItemGroup>
```

**Comment by AghaKhan** [comment] 2021-04-30 03:53
Hi
I was confused and put that code in App1 (Package) project.
Now I placed provided code in main App1 project and it worked.

Thanks for update.
Best regards
Agha Khan
(206) 619-2097

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Closed** 2021-04-30 04:28 UTC
Labels: ProjectReunion 0.5, area-Tooling, needs-triage, team-Markup, winui3preview

**Comment by bluephoton** [comment] 2021-06-06 03:47
@codendone solution worked for me, shame this WinUI3 desktop template is still broken out of the box as of today 6/5/21, not sure why this is closed!

**Comment by rafalkubiak** [comment] 2022-04-10 10:49
I didn't code WinUI for some time (I tried it some time ago and worked perfectly fine) and now I wanted to take a tour and surprisingly have the same error but in other version of WinRT.Runtime.dll (this time is 1.6). Can somebody tell me what to do?

**Comment by AghaKhan** [comment] 2022-04-11 01:41
Today in response to message today I tried to build Microsoft provided code (DemoBuildCpp) which compiled ok but got run time  exception 
![image](https://user-images.githubusercontent.com/5318363/162651229-8ab6919a-42c9-4136-a64b-cf21c78213e7.png)
