### ISSUE TITLE
When dragging a tab to the top of another tab and dropping it, the shadow is displayed incorrectly

### ISSUE THREAD

**Issue by zhuxb711** [microsoft/microsoft-ui-xaml#3191] opened 2020-08-25 03:50 UTC
**Describe the bug**
When dragging a tab to the top of another tab and dropping it, the shadow is displayed incorrectly.

If you drag to the edge of the TabItem, the problem disappears.

In addition, when dragging Tab to the TabStrip area, the corresponding TabStripDragOver event will not be triggered (the triggerable area is too small)

**Steps to reproduce the bug**

1. Drag tab from another process/Drag and drop tabs in the same TabView 
2. Make sure the two tabs overlap

**Expected behavior**

There should not be a situation where both tabs have shadows

**Screenshots**

![bug](https://user-images.githubusercontent.com/42038175/91120783-0b435b00-e6c9-11ea-95d4-9cd6eb19f151.gif)

**Version Info**

NuGet package version: 
[Microsoft.UI.Xaml 2.4.3]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by YuliKl** [comment] 2020-08-25 23:11
@stmoy and @teaP FYI

**Comment by zhuxb711** [comment] 2020-08-28 01:59
Any solution about this?

**Comment by chingucoding** [comment] 2020-10-20 18:41
I am unable to reproduce this issue. Can you try out the latest WinUI prerelease or provide a repro app? @StephenLPeters FYI

**Comment by zhuxb711** [comment] 2020-10-21 02:46
@chingucoding 
Here is a repro: 
[TabDragBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5412950/TabDragBug.zip)

It is worth noting that you should open two instances and drag tabs between the windows. Make sure the tab you drag is released above the selected tab in another window

**Comment by chingucoding** [comment] 2020-10-21 11:57
Thank you for the repro app, I am able to repro this now. I'll take a look what is causing this behavior.

**Comment by chingucoding** [comment] 2020-10-21 15:21
Unfortunately, this is not an issue with TabView but rather an issue with the underlying ListView which takes care of the visual states (also the issue is not about shadows but the pointerover behavior). See #3458 for more context. 

There are multiple ways TabView can deal with this:
1. Switch to ItemsRepeater, this however is not a small task and will take quite some time
2. Handle the PointerOver state manually by using a different VisualState and handle PointerOver state manually. This is not ideal, however is an easier mitigation to the issue 
3. Wait for the bugfix in ListView, this would need to wait until WinUI 3 to arrive which will be the slowest way to resolve this

@StephenLPeters @ranjeshj What are your thoughts on the way to handle this?

**Comment by zhuxb711** [comment] 2020-10-21 15:50
@chingucoding  I don't know VisualState very well, could you provide some code to alleviate this problem? Thanks a lot~

**Comment by chingucoding** [comment] 2020-10-21 16:26
I'm afraid, there is no simple way to mitigate this for you. One thing you could do is handle the pointer over logic yourself, that would mean:

- Listen to PointerExited
- Listen to PointerEntered
- Listen to Drop
- Listen to DragEnter
- Listen to DragLeave

and respond accordingly.

In addition to that, you would also need to retemplate TabView and remove the "PointeOver" visual state while introducing a new visual state that you will use to indicate pointer over.

**Comment by zhuxb711** [comment] 2020-10-21 16:36
This is a fairly low-level BUG. ListView is the most basic control. It should not have such or other problems and cannot be fixed in time.

Please set this problem as an urgent problem in WinUI3，and I hope that WinUI3 can be released as scheduled and not delayed like WinUI2.5.

**Comment by DmitriyKomin** [comment] 2024-03-05 01:23
Per comment of @marcelwgn, marking this as duplicate of #3458.

**Closed** 2024-03-05 01:23 UTC
Labels: bug, duplicate, area-TabView, needs-winui-3, team-Controls
