### ISSUE TITLE
UWP ShareUI: Thumbail image not displayed

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/microsoft-ui-xaml#145] opened 2019-01-04 14:56 UTC
**Describe the bug**
When sharing an image via the UWP [Windows.ApplicationModel.DataTransfer.DataTransferManager](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/share-data) class, a thumbnail image is not shown, even if set.

See the [Thumbnail Property](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackagepropertyset.thumbnail#Windows_ApplicationModel_DataTransfer_DataPackagePropertySet_Thumbnail) of the [DataPackage](https://docs.microsoft.com/en-us/uwp/api/windows.applicationmodel.datatransfer.datapackage) specifying the data to share.

**Steps to reproduce the bug**
1. Build/Start the [UWP ShareSource app sample](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/ShareSource)
2. Click on "4) Share image"
3. On the 'Share image' pane: Click 'Select image' and select an image
4. Scroll down under you see the 'Share' button. Click it.

The Share UI opens without showing a thumbnail of the selected image, even though it is set in code.

Code snippet (of the UWP sample app) below:
     
> ```
> DataPackage requestData = request.Data;
>
> RandomAccessStreamReference imageStreamRef = RandomAccessStreamReference.CreateFromFile(this.imageFile);
> requestData.Properties.Thumbnail = imageStreamRef;
> ```

The full method can be found [here](https://github.com/Microsoft/Windows-universal-samples/blob/master/Samples/ShareSource/cs/ShareImage.xaml.cs#L32).

**Expected behavior**
Show the set thumbnail, in this case a thumbnail of the selected image.

**Screenshots**
![uwp share image](https://user-images.githubusercontent.com/1398851/50693806-5ca45f80-1038-11e9-87e2-d3eb43d8ef4c.jpg)

**Version Info**
- Windows 10 17763
- Latest Windows 10 SDK (17763)

NuGet package version: 
-

Windows 10 version:
- [ ] October 2018 Update (17763)

Device form factor:
- Desktop

**Additional context**
Not sure if the same case, but sharing an image file via the windows explorer also doesn't display a thumbnail image.

**Comment by YuliKl** [comment] 2019-01-10 19:53
Thanks for reporting this problem! This is occuring lower down in the stack than the controls available in this repo, so I've filed an [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/20148643) for tracking.

**Comment by Felix-Dev** [comment] 2019-01-10 20:52
@YuliKl 

thank you for your comment. Yes, I was expecting it to be an issue for a team other than the WinUI team. However, I chose to report it here because so far you guys have been extremely responsive to user-reported problems! On other platforms, like user voice, there have been reports that bug reports were left unanswered.

If possible, I'd love to be updated about any progress/fixes for this particular issue. 

Thanks again!

**Comment by YuliKl** [comment] 2019-08-14 22:42
@Felix-Dev, the internal issue I had created was resolved as By Design with this comment

> The thumbnail property is not for displaying the shared image in the Share target picker UI. The thumbnail property is to be used by the target app to display a thumbnail before the target app downloads the image.

Closing this issue but please let me know if you have other questions.

**Closed by YuliKl** 2019-08-14 22:42 UTC

**Comment by Felix-Dev** [comment] 2019-08-15 07:42
@YuliKl Ah, I see! I checked the documentationto see if it needed an update to reflect this behavior and indeed this piece of information is included there:

> We recommend that any time you create a DataPackage that contains images, you also assign a thumbnail image. Doing so gives target apps the opportunity to display a visual representation of the images being shared to the user while the share operation completes.

I guess we can leave the documentation as it is right now. Thanks!
