### ISSUE TITLE
ScrollViewer Jumps to Top-most TextBox (UWP app)

### ISSUE THREAD

**Issue by myokeeh** [microsoft/microsoft-ui-xaml#597] opened 2019-04-22 06:56 UTC
**Describe the bug**
The `ScrollViewer` control seems "jumpy." I have several controls arranged top to bottom. One of the top-most controls is a `TextBox` and several controls down is a `ToggleSwitch`. When I scroll down, and click on empty space just to the right, nothing happens (expected behavior). When I toggle the switch on/off, and click on empty space again, the `ScrollViewer` jumps to the top-most `TextBox` waiting for text entry(?) (unwanted behavior)--caret is blinking in the text box. Hitting empty space is basically the inevitability that users can miss hitting controls (tapping with a finger) or purposefully trying to remove focus on some control.

**Steps to reproduce the bug**
Setup a page with several controls (`TextBox`, `ToggleSwitch`) in a `<StackPanel Orientation="Horizontal">` enough to require scrolling down to the `ToggleSwitch`
1. Debug the app.
2. Scroll to the toggle switch.
3. Toggle the switch on/off.
4. Click on empty area (not the control or toggle switch text).

**Expected behavior**
The `ScrollViewer` should NOT scroll to the top--should stay put.

**Actual behavior**
The `ScrollViewer` scrolls to the top-most `TextBox` with the text cursor blinking.

**Version Info**
Windows 10 19H1 (all versions I can remember), All form factors

NuGet package version: 
2.1.190405004.1

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18362)                   | Yes   |
| October 2018 Update (17763)   | Yes      |
| April 2018 Update (17134)        | Yes      |
| Fall Creators Update (16299)     | Yes      |
| Creators Update (15063)           | Yes      |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes      |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I've used the same XAML on the Template 10 version, and even (Windows Template Studio/Prism) and the unwanted behavior has always been there.

I thought `BringIntoViewOnFocusChange = "false"` would do the trick, but it doesn't.

**Comment by jevansaks** [comment] 2019-04-22 17:07
Thanks for reporting! I see this too in the Xaml Controls Gallery app on the RichEditBox page. If I scroll down and then click on the right gutter it scrolls to the top.

Something is setting focus to the ScrollViewer or the page and that's causing focus to go to the first focusable thing in the ScrollViewer which causes the view to jump.

**Comment by myokeeh** [comment] 2019-05-29 07:10
I don't know how everything works... I see this got put into Approved in Controls Triage, but I don't understand what that means as far as when it might show up in a release. Can anyone fill me in?

**Comment by mrlacey** [comment] 2019-05-29 09:38
>  I see this got put into Approved in Controls Triage, but I don't understand what that means as far as when it might show up in a release. Can anyone fill me in?

Full descriptions of all projects, and the boards within them, would help share understanding and promote transparency.

**Comment by DuncWatts** [comment] 2019-07-12 14:22
Is there a workaround for this issue? I'm seeing this from a Xamarin.Forms UWP application but can also replicate it on a standard UWP app.  Is there a way to make the ScrollViewer accept focus itself so it doesn't auto-focus the first focusable control within its children?

**Comment by jevansaks** [comment] 2019-07-12 15:54
I know that I talked to @Rbrid about this but I can't remember where we landed. We recognize it's a problem but I don't know if there's a good workaround. You could try putting a panel behind your whole ScrollViewer content that handles the mouse clicks so ScrollViewer doesn't get a chance to see them and try to set focus to itself.

**Comment by DuncWatts** [comment] 2019-07-12 16:11
On a simple UWP repro app - ScrollViewer containing a StackPanel containing multiple TextBox control - I can workaround this by setting IsTabStop="True" on the ScrollViewer.  

This doesn't work on the Xamarin.Forms application as it isn't the same issue but I've got a workaround there as well.

**Comment by myokeeh** [comment] 2019-07-12 16:38
@DuncWatts thanks! I think that works for me.

**Comment by JKennedy24** [comment] 2019-07-22 13:56
@duncWatts

Experiencing this in Xamarin.Forms UWP application. Whats the workaround you mention?

**Comment by DuncWatts** [comment] 2019-07-22 14:02
> @DuncWatts
> 
> Experiencing this in Xamarin.Forms UWP application. Whats the workaround you mention?

I duplicated the ScrollViewRenderer and stripped off the IDontGetFocus interface.  See the linked issue Xamarin.Forms issue above and related commits.  Once that issue has been fixed in a released build I can just remove my custom renderer.

**Comment by JKennedy24** [comment] 2019-07-22 14:21
Might be a bit cheeky but any chance you can share the renderer? I duplicated the renderer and stripped off the interface but I'm still getting the behavior

**Comment by DuncWatts** [comment] 2019-07-22 14:23
This is the code I'm using in my UWP project.

https://gist.github.com/DuncWatts/2c9dd44e13d29a0e6fdc72c659532bb6

**Comment by JKennedy24** [comment] 2019-07-22 14:29
@DuncWatts brilliant thanks!

I'll also mention that you also need to have `IsTabStop="true"` as well as the renderer, I was setting it to false which is why I still saw the behavior

**Comment by premiaware** [comment] 2019-08-07 22:28
I have the same issue, has anyone found a solution?

**Comment by jevansaks** [comment] 2019-08-07 23:04
@premiaware someone recommended a workaround above, can you try this:

> I can workaround this by setting IsTabStop="True" on the ScrollViewer.

**Comment by premiaware** [comment] 2019-08-08 07:26
Thank's for answer, in my sample UWP IsTabStop=True not working. if you have time to try my sample i have attached it.
click in the first textBox, scroll the view to the botton, click in the checkbox in left botton corner.
result, the view autoscroll to the top :-(
[Ricorsivo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3480376/Ricorsivo.zip)

**Comment by DuncWatts** [comment] 2019-08-08 07:55
> Thank's for answer, in my sample UWP IsTabStop=True not working. if you have time to try my sample i have attached it.
> click in the first textBox, scroll the view to the botton, click in the checkbox in left botton corner.
> result, the view autoscroll to the top :-(
> [Ricorsivo.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3480376/Ricorsivo.zip)

I can't replicate this with your code, however I notice you don't have "Build" or "Deploy" checked against the AnyCPU in the Configuration Manager, so you may not have been testing the change.

**Comment by premiaware** [comment] 2019-08-08 08:10
sorry, maybe it was removed by deleting the configuration files before running the zip. but were you able to compile and start the app? following the procedure described, in your pc work? from me in 3 different PCs does not work

**Comment by premiaware** [comment] 2019-08-08 16:50
After 1 day of investigation i have found the problem, if the UWP App have Light theme all working OK using IsTabStop = true, if the App have Dark Theme the Scrollviewer not working also if i set IsTabStop = true, the sample is attached. 
It is an absurd situation, If you open the App.xaml and remove RequestedTheme="Dark" the app working.

[Ricorsivo2.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3482801/Ricorsivo2.zip)

**Comment by jevansaks** [comment] 2019-08-08 16:58
> Light theme all working OK using IsTabStop = true, if the App have Dark Theme the Scrollviewer not working

It's possible that in dark theme the background is Null, which will cause the mouse clicks to not "hit" the ScrollViewer background. Try setting the ScrollViewer's background to Transparent and see if that helps make it hit-testable.

**Comment by premiaware** [comment] 2019-08-08 17:05
i have set: 
 <ScrollViewer
            Background="Transparent"
            Padding="50"
            VerticalScrollBarVisibility="Auto"
            VerticalScrollMode="Auto"
            IsTabStop="True">

but the problem is the same.

**Comment by jevansaks** [comment] 2019-08-08 17:09
Did you set the background on the ScrollViewer? Either way I tried your project on latest Windows 10 (1903) and it worked fine. Here was I did to try to repro:
1) Scroll down
2) Put focus in a TextBox
3) Click on blank space to the right side of the TextBoxes

Result: TextBox loses focus but ScrollViewer scroll position doesn't change.

Are your repro steps different? Or are you seeing different behavior with these steps?

**Comment by premiaware** [comment] 2019-08-08 17:21
you must build and run my new sample "ricorsivo2.zip"  start the APP.
- SET THE FOCUS in the FIRST TEXTBOX
- SCROLL DOWN to the botton
- Click on blank space or click the checkbox in the left, botton corner.

result: the scroll auto return to the top.

**Comment by premiaware** [comment] 2019-08-08 17:29
the problem is the TextBox Theme, if in the textBox i set the Light theme
<TextBox Width="200" RequestedTheme="Light"/>
All working ok!
This is not solution because my app use Dark theme.

**Comment by premiaware** [comment] 2019-08-08 19:43
Finally i have fix the problem, changing Template now working ok!. Thank's for support.

**Comment by Balasubramanian93** [comment] 2019-08-23 10:07
@premiaware Can you please let me know how you have resolved this issue?

**Comment by premiaware** [comment] 2019-08-23 10:30
naturally,
you have to edit the TextBox template, you can take it from generic.xaml or use blend, and create a custom textBox template.
then you need to replace the theme line:

    <ObjectAnimationUsingKeyFrames Storyboard.TargetName="ContentElement" Storyboard.TargetProperty="RequestedTheme">
        **<DiscreteObjectKeyFrame KeyTime="0" Value="Light" />**

replace 
        **<DiscreteObjectKeyFrame KeyTime="0" Value="Light" />**
with
        **<DiscreteObjectKeyFrame KeyTime="0" Value="Dark" />**

Now set the new template to All textBox and for me work.

**Comment by myokeeh** [comment] 2019-08-30 05:20
Like @premiaware I'm also discovering the workaround doesn't work for an app that can switch theme (Light, Dark). I hope this gets fixed soon.

@premiaware, can you share more of the XAML code for your workaround. I'm not sure I follow. Does yours work for both Light and Dark if changed by the user?

**Comment by premiaware** [comment] 2019-08-30 07:53
My App working with Fixed Dark Theme.
you could try to do this but it's a bit complex to do it in all TextBox

<TextBox RequestedTheme="{Binding currentTheme}"     />                                         

I don't know if it works

**Comment by JonasMuliolis** [comment] 2019-09-04 22:38
Thanks for all of the above. I found a solution that worked for me without having to set the entire App Theme to Light - just set RequestedTheme of the ScrollView to Light. In conjunction with the new ScrollViewRenderer above this fixed the problem in my app. I had to tweak a few styles of the controls in the ScrollView, but all seems to work now. 
HTH.

**Comment by myokeeh** [comment] 2019-11-22 05:45
Is it possible to get this prioritized higher?

**Comment by jevansaks** [comment] 2019-11-22 18:19
Unfortunately this isn't something we can fix any sooner. It is tagged with "needs-winui-3" which means we'll review it as soon as we're able to start thinking about bug fixes on top of Winui 3.

**Comment by Rothanan** [comment] 2020-11-05 11:16
Any news on this?

**Comment by myokeeh** [comment] 2020-12-04 15:42
🤔 Was this inadvertently fixed somehow? I can't seem to reproduce the problem anymore. I just checked with 2.5.0 that was just released. 2.4.3 doesn't seem to have the problem, either.

I'm on Windows 10 19042.662.

**Comment by shuice** [comment] 2021-03-09 07:29
I found a solution on stackoverflow that worked for me. Add a ContentView below the scrollview hierarchy. The overall hierarchy is as follows: ScrollView->ContentView->GridView->TextBox


https://stackoverflow.com/questions/49713033/uwp-scrollviewer-unexpected-behavior

**Comment by huco95** [comment] 2021-09-16 11:44
> > @DuncWatts
> > Experiencing this in Xamarin.Forms UWP application. Whats the workaround you mention?
> 
> I duplicated the ScrollViewRenderer and stripped off the IDontGetFocus interface. See the linked Xamarin.Forms issue above and related commits. Once that issue has been fixed in a released build I can just remove my custom renderer.

I am trying to implement this solution but I am having problems with the `_currentView.Cleanup();` method call, I have the following error:

`'VisualElement' does not contain a definition for 'Cleanup' and no accessible extension method 'Cleanup' accepting a first argument of type 'VisualElement' could be found (are you missing a using directive or an assembly reference?).`

What I am missing? I have changed to `_currentView = null;` just to test it and it's working but I don't think this is the best way...

**Comment by Qws** [comment] 2022-04-29 22:58
Lol, this is not fixed? 

🤦

**Comment by holecekp** [comment] 2022-04-30 08:22
I think it is still not fixed but at least a workaround can be used. I created a custom ScrollViewRenderer without IDontGetFocus for the issue #5652, which is probably the same bug. You can download a zip file with this renderer there:  https://github.com/xamarin/Xamarin.Forms/issues/5652#issuecomment-763886698.

**Comment by mattleibow** [comment] 2022-12-09 18:42
@evelynwu-msft this may need that maui label too

**Comment by tipa** [comment] 2023-07-29 02:27
.

**Comment by Felicity-R** [comment] 2023-09-19 18:40
We were using DuncWatt's solution in Xamarin Forms, but after converting to Maui this is what I did to fix it with a handler rather than having to use a compatibility renderer: https://github.com/dotnet/maui/issues/11472#issuecomment-1726284964

**Closed** 2024-02-24 06:58 UTC
Labels: bug, area-Scrolling, needs-winui-3, team-Controls, maui-7.x, closed-Fixed

**Comment by marcelwgn** [comment] 2024-04-04 20:32
@llongley Is the fix for this included any of the currently released WinUI 3 versions? I wasn't able to find any reference to it and the issue was closed with "closed-fixed" 😅

**Comment by codendone** [comment] 2024-04-05 05:04
@marcelwgn Looking at the internal bug, the fix is currently only in 1.6.

**Comment by marcelwgn** [comment] 2024-04-05 05:46
Awesome thanks for the clarification @codendone

**Comment by codendone** [comment] 2024-04-05 16:51
@MartyIX The code owners say there is considerable risk associated with the fix, which requires the 1.6 timeframe to bake the fix.
