### ISSUE TITLE
ColorPicker display incorrect on Win11

### ISSUE THREAD

**Issue by manupstairs** [microsoft/microsoft-ui-xaml#6474] opened 2021-12-10 03:42 UTC
**Describe the bug**
In a UWP APP, if I apply Microsoft.UI.XAML 2.7. ColorPicker display incorrect on Win11, it only can be replicate in release version.

**Steps to reproduce the bug**
1. Create an empty UWP project in VS 2019. 
2. Add a ContentDialog which content is ColorPicker. 
3. Add Microsoft.UI.XAML 2.7 from Nuget.
4. Change "Debug" to "Release", press F5. It work fine.
5. Add `<XamlContrlsResource xmlns="using: Microsoft.UI.Xaml.Controls"/>` in App.xaml
6. Press F5, issue happen.

**Expected behavior**
ColorPicker should display correct on Win11 and Win10.

**Actual behavior**
ColorPicker can't works on Win11. User can't pick color.

**Screenshots**
<img width="602" alt="Screenshot 2021-12-10 113657" src="https://user-images.githubusercontent.com/1835049/145513204-2af42fb6-e3aa-4428-8fc5-ed670acb3436.png">

**Version Info**
- [ ] Xaml Controls Gallery - Downloaded from Store
    - 2.7 version from Nuget.

**Additional context**
https://github.com/manupstairs/IssueAboutXAMLGallery
I create a sample to replicate this issue here. Just click the only one button to show the dialog with colorpicker.

Windows version:
- [*] Windows 11 (21H2 22000.348)

Device form factor:
- [*] Desktop

**Comment by StephenLPeters** [comment] 2022-03-01 19:28
duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/6440  @llongley and @gegao18 thoughts on what might be the root cause?

**Closed** 2023-08-04 12:04 UTC
Labels: duplicate, area-ColorPicker, team-Controls, team-Rendering, no-issue-activity
