### ISSUE TITLE
Rearranging GridView items causes appcrash with exception 8000ffff only when running as administrator

### ISSUE THREAD

**Issue by yagdev** [microsoft/microsoft-ui-xaml#9751] opened 2024-06-22 17:04 UTC
### Describe the bug

https://github.com/microsoft/microsoft-ui-xaml/assets/53407061/2cba86bb-e1a2-4760-848c-443d7063dbc6
Basically rearranging a GridView works as expected when ran without administrator privileges but crashes when ran as an admin. 

### Steps to reproduce the bug

1. Create WinUI 3 project
2. Add GridView that allows for items to be rearranged
3. Add items to GridView (in my case frames with a page as content)
4. Build
5. Run normally (works)
6. Run as Admin (crashes)

### Expected behavior

Reordering a GridView should behave as the first build in the attached video (allows reordering)

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/53407061/f1d65208-497d-408f-b128-281d28c8b1db)

### NuGet package version

WinUI 3 - Windows App SDK 1.6 Experimental 1: 1.6.240531000-experimental1

### Windows version

Windows 11 (22H2): Build 22621

### Additional context

While Windows App SDK 1.6 Experimental 1 is selected, this issue also happens in the stable branch.

**Comment by kmgallahan** [comment] 2024-06-23 00:32
https://github.com/microsoft/microsoft-ui-xaml/issues/7690

**Comment by codendone** [comment] 2024-07-02 22:31
Closing as duplicate of #7690.

**Closed by codendone** 2024-07-02 22:31 UTC
Labels: bug, needs-triage
