### ISSUE TITLE
WinUI 3 NavigationView does not apply correct styles

### ISSUE THREAD

**Issue by sibille** [microsoft/microsoft-ui-xaml#4608] opened 2021-03-22 13:52 UTC
**Describe the bug**
After updating WinUI 3 Nuget package to Project Reunion "0.5.0-prerelease" NavigationView does not apply correct styles when use small window size.

**Steps to reproduce the bug**
Repro project: [NavView.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6182630/NavView.zip)

1. Make app small
2. Open NavView Menu

**Expected behavior**
![image](https://user-images.githubusercontent.com/25466105/111995439-36841080-8b19-11eb-8d2a-19dc409f82f1.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/24698018/111999931-c1ffa080-8b1d-11eb-8ba6-4140968b259a.png)

**Version Info**

NuGet package version: 
[WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease] If you're seeing your issue in older previews, please try this release.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |Yes|

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
VS Version: 16.9.0
Windows Build: 19042.868
Dotnet SDK: 5.0.200

**Comment by StephenLPeters** [comment] 2021-03-22 23:35
duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4579

**Closed by StephenLPeters** 2021-03-22 23:35 UTC
Labels: needs-triage
