### ISSUE TITLE
NavigationView display issue while debugging in Win 10 with remote desktop connection

### ISSUE THREAD

**Issue by hanzhang54** [microsoft/microsoft-ui-xaml#5801] opened 2021-08-31 06:52 UTC
**Describe the bug**

The NavigationView menu will expand without open the pane and get abnormally displayed with semitransparent effect while debugging in Win 10 with remote desktop connection.

**Steps to reproduce the bug**

1. Remote desktop connection to Win 10.
2. Debug project in Win 10.
3. Set the window size to be small.
4. Close the window and reopen it.
5. The NavigationView menu will expand without open the pane and get abnormally displayed with semitransparent effect.

**Expected behavior**

The menu shouldn't be expanded by default without clicking the menu button and shouldn't have the semitransparent effect.

**Screenshots**

![image](https://user-images.githubusercontent.com/78525595/131455449-2640396c-9eb5-4d67-ac58-f13361a990d1.png)

**Version Info**

NuGet package version: Microsoft.UI.Xaml 2.6.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            |  Yes  |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

More information can be found in https://github.com/microsoft/calculator/issues/1640.

**Comment by StephenLPeters** [comment] 2021-09-14 00:18
I think that this is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5342 which should have been fixed by https://github.com/microsoft/microsoft-ui-xaml/pull/5531  However that fix was included in 2.6.2

@hanzhang54 are you confident you are seeing this issue with 2.6.2

@karenbtlai do you know whats going on here?

**Comment by hanzhang54** [comment] 2021-09-14 05:08
Hi @StephenLPeters , I reproduced this in 2.6.2 only when debugging in Win10 with remote desktop connect. I didn't see such issue in general cases, so I guess the fix works for general cases but this corner case is not included.

**Comment by StephenLPeters** [comment] 2021-09-17 01:03
hmm, that is really surprising... @codendone any idea what could be causing that or how to go about looking into it?

**Comment by codendone** [comment] 2021-09-17 02:30
@StephenLPeters It sounds like there are two potential issues here:
1. Is the NavView menu actually open here, and is that behavior different when not over Remote Desktop? If it is, is it open in a different way than when it is opened manually? Does toggling it closed and open change how it draws?
2. If it open in the normal way and draws with the same issue even after toggling closed/open, then why is it not drawing correctly? It looks like the AcrylicBrush background isn't working, if the background is properly set to an AcrylicBrush (or whatever not-fully-transparent background it should be).

**Comment by karenbtlai** [comment] 2021-09-17 20:40
This looks like an issue similar the previous ones linked, where NavView pane and SplitView pane VisuatStates are out of sync. In this case, NavView is open, but SplitView is not (background is in SplitView). I will have to investigate more to see why the previous fix does not fix these scenarios specifically.

**Closed** 2023-08-03 22:45 UTC
Labels: area-NavigationView, team-Controls, no-issue-activity
