### ISSUE TITLE
Short, incomplete swipe gestures on the SwipeControl sometimes cause it to break down and stop swiping

### ISSUE THREAD

**Issue by Sergio0694** [microsoft/microsoft-ui-xaml#1082] opened 2019-07-19 20:29 UTC
**Describe the bug**

This bug is probably related to #890.
Basically, if you perform some incomplete swipe actions on a `SwipeControl`, and then make a full gesture, the control will just break down and stop responding to new swipe gestures.

**Steps to reproduce the bug**

1. Get the repro: [SwipeGlitchRepro.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3412608/SwipeGlitchRepro.zip).
2. Perform a series of partial swipes on either side of any of the items, then a full swipe (see video below for more details on how to reproduce this).
3. The template should then break down and stop responding.

**Expected behavior**

The control should just keep working as usual.

**Screenshots**

[VideoCapture.zip](https://github.com/microsoft/microsoft-ui-xaml/files/3412629/VideoCapture.zip) (it's a zipped .mp4 video).

**Version Info**

**NuGet package version** 
`Microsoft.UI.Xaml` 2.1.190606001

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

Pinging @kikisaints as she owns the `SwipeControl` control (I know this is the 4th issue I open on it, I'm sorry 🙈), and @RBrid as he was investigating the related issue #890.

**Comment by jevansaks** [comment] 2019-07-22 18:32
Sounds like a dupe. @RBrid is on vacation but I think @KMahone might have some time to take a look at these two together.

**Comment by kmahone** [comment] 2019-08-06 20:21
I cannot reproduce this issue (or the crash #890) on my desktop machine (with a Dell touch monitor) or on my Surface Pro 4. 

I CAN reproduce this issue (but not the crash) in the Simulator using the mouse simulated as touch input. But using real touch input in the Simulator does NOT reproduce this issue.

@Sergio0694 did you ever hit this issue on a real device? Or has this only been seen in the Simulator?

**Comment by Sergio0694** [comment] 2019-08-06 20:31
Hi @kmahone - thank you for the follow up!
So, I haven't been able to personally repro this on a real device, as I don't actually have a Windows 10 device with a touch screen to test this on, but I do see hundreds of occurrences for this crash on AppCenter, plus additional reports from individual users, so I can definitely confirm that this is a real issue happening on real devices.

Here's a screen with some of the common devices and OS builds this happens more often on:
![image](https://user-images.githubusercontent.com/10199417/62574875-c10ef200-b899-11e9-8950-9793a1f70a02.png)

I could try pinging the users that reported this issue to see if they have found some ways to repro the issue more reliably, I'm not sure how else I could do on my end about this 😟

It's unfortunate that this isn't easily reproducible on a real device, and I understand that this won't make it easier to investigate either of these issues.
Please let me know if there's anything else I can do to help on my end, and thank you again for looking into this!

**Comment by kmahone** [comment] 2019-08-06 22:26
@Sergio0694 thanks for the info with regards to the crash.

For the problem in this issue (where the SwipeControl becomes non-responsive but does not crash), it sounds like this has only ever been seen in the Simulator? Is that correct? Or have you gotten reports from users about this problem also?

**Comment by Sergio0694** [comment] 2019-08-06 23:26
Yes, that is correct. I've mainly opened this issue as I thougth it could provide additional info, but this one in particular I've only managed to reproduce through the simulator, and I haven't received reports about it. Users only mentioned straight up crashes, so what's detailed in #890.

**Comment by kmahone** [comment] 2019-11-09 00:12
@Sergio0694 since #890 is now closed, I am going to close this issue also. If this particular issue remains a problem for you, please let me know and I can reactivate.

**Closed by kmahone** 2019-11-09 00:12 UTC
Labels: area-SwipeControl, bug, team-Controls
