### ISSUE TITLE
XAML designer will not render any forms

### ISSUE THREAD

**Issue by GuildOfCalamity** [microsoft/microsoft-ui-xaml#5521] opened 2021-07-20 22:33 UTC
**Describe the bug**
I have installed the WinUI/ProjectReunion/WindowsAppSDK extensions in VS2019 and followed all the steps in the tutorials but I cannot get the form to paint in the IDE. I have checked all of the settings in the options menus and my other XAML projects render the form just fine. NOTE: The app will run and compile without issue, but will not render in the IDE.

I'm using VS2019 Version 16.10.3 on Windows 10 Pro, build 19042.1110

**Steps to reproduce the bug**

1. Create blank app WinUI project.

![error1](https://user-images.githubusercontent.com/81915293/126403845-94911d96-5569-4c0e-9da6-96968f22baa0.png)
![error4](https://user-images.githubusercontent.com/81915293/126403853-1f29bea8-0759-43ad-bd77-d5ff58030e73.png)
![error2](https://user-images.githubusercontent.com/81915293/126403862-5cf6c959-3001-4834-9b8b-648ba3fba1bb.png)
![error3](https://user-images.githubusercontent.com/81915293/126403869-f685d822-7438-4538-bff3-7faa2cab5a45.png)

Using NuGet just makes the problem worse...
![UAP_error](https://user-images.githubusercontent.com/81915293/126404120-91cbdce0-e979-4184-a818-1fffb6d7ab9c.png)

**Comment by StephenLPeters** [comment] 2021-07-20 23:13
@fabiant3 FYI.

@GuildOfCalamity Xaml designer is not yet supported by WinUI3.

**Comment by GuildOfCalamity** [comment] 2021-07-20 23:35
> 
> 
> @fabiant3 FYI.
> 
> @GuildOfCalamity Xaml designer is not yet supported by WinUI3.

So how are we supposed to do the visual design??

**Comment by marb2000** [comment] 2021-07-21 18:41
Hi @GuildOfCalamity,

The XAML Designer for WinUI 3 is not in the plan for 2021.  I agree VS should aware of users that WinUI doesn't support XAML Designer, although I thought the designer is disabled by default in the WinUI project templates to avoid these misunderstandings. 
Also, I believe that Alvin was using a preview version of WinUI 3 in UWP in his book. A lot of things happening since Alvin released the book. For example:  
1. WinUI 3 is now part of the Windows App SDK.
2. Windows App SDK has different releases: Experimental, Preview, and Stable. 
3. The Experimental release contains WinUI 3 running in UWP, in addition to WinUI 3 in Desktop (Win32). 
4. WinUI 3  the Preview and Stable releases contain only WinUI 3 in Desktop
5. XAML Designer only worked for WinUI 3 in UWP in the past, given we were reusing the UWP XAML designer (actually, we adjusted several things to make it work). The UWP XAML designer is not compatible with WinUI 3 in Desktop given WinUI 3 in Desktop has substantial changes that require a rearchitected of the XAML Designer. 

Without XAML designer, the recommended development inner loop is to use XAML Hot-Reload, Live Visual Tree, and in-app command bar to design the app while the app is running so you can apply changes and see the result immediately.

Closing this bug given it's a dupe of https://github.com/microsoft/microsoft-ui-xaml/issues/4195

**Closed by marb2000** 2021-07-21 18:41 UTC
Labels: area-Tooling, needs-triage, product-winui3, team-Markup

**Comment by mrlacey** [comment] 2021-07-21 19:08
> Also, I've seen screenshots of people working with the designer using WinUI 3.0. Alvin Ashcraft's new book proves that it worked at some point.

If you're referring to figures 11.1 and 11.2 (from chapter 11) these show a WinUI2/UWP app running. I believe the intent was to show how it will eventually be (& was hoped for at the time of writing.)

This also hints at a possible workaround.
As WinUI3 XAML is **very** similar to that used in UWP apps you can write your XAML in a UWP app (including seeing it visualized in Visual Studio) and then copy it into a WinUI3 app. Or set up a solution with both projects that share the XAML.

If you're new to building with XAML, you might also want to try out [XAML Studio (Microsoft Store link)](https://www.microsoft.com/p/xaml-studio/9ntls214tkmq) as that will also allow you to visualize the entered XAML with a version of XAML that is very similar to that available in WinUI3. 


As a further alternative, you can often get a better experience than with the Visual Designer by using [XAML Hot Reload](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2019) (also covered in Chapter 11 of Alvin's book.)

Another option we can look forward to in the future is [XAML Live Preview](https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-preview#XAMLLivePreview-170P2) which will hopefully be available for more than just WPF in a future Visual Studio preview.

Not an excuse for the current situation but some possible workarounds and a suggestion that things will get better in the future.

**Comment by GuildOfCalamity** [comment] 2021-07-21 20:19
Thanks for the info!

**Comment by GuildOfCalamity** [comment] 2021-07-22 00:36
I did just try VS2022 starting with a blank UWP project, but my god is it buggy... seems to have no idea what a grid is???

![UWP_Errors](https://user-images.githubusercontent.com/81915293/126576351-ae56f5c5-6b49-4b29-a904-41ca07bf2c31.png)

**Comment by mgoertz-msft** [comment] 2021-07-22 17:10
@GuildOfCalamity This would happen if there were some kind of problem with the References in the project. For a normal working blank project it should look like this:

![image](https://user-images.githubusercontent.com/14282894/126680159-8df6456b-d838-42e4-8a28-8b2f57ff3b8a.png)

**Comment by asklar** [comment] 2021-07-23 04:58
Duplicate of #4195
