### ISSUE TITLE
Drag and drop: setting DragUIOverride.Caption after async code triggers a COM exception

### ISSUE THREAD

**Issue by Arko109** [microsoft/microsoft-ui-xaml#9296] opened 2024-01-29 14:32 UTC
### Describe the bug

Drag and drop: setting `DragUIOverride.Caption` after async code triggers a COM exception that has no message.

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in WinRT.Runtime.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in WinRT.Runtime.dll but was not handled in user code
```

Without the async call it works fine. Actually, if I catch the exception, the caption is set, however the drag and drop becomes broken and works only once. The subsequent times I try to drop a file, the `DragOver` is called, but setting values does nothing and the file is not accepted.

Tried with release and prerelease Nuget package.

Maybe I misunderstand how to filter the file type that can be dropped and there is a way of doing it without an async call?

### Steps to reproduce the bug

1. Create a new blank WinUI app
2. In `MainWindow` add any element (`StackPanel`, `RelativePanel`...) with `AllowDrop="True"` and `DragOver="DragOver"`
3. In the `DragOver` event handler paste the following code:
```csharp
if (e.DataView.Contains(StandardDataFormats.StorageItems)
    && (await e.DataView.GetStorageItemsAsync()).FirstOrDefault() is StorageFile file 
    && (file.FileType == ".xlsx" || file.FileType == ".xls"))
{
    e.AcceptedOperation = DataPackageOperation.Copy;
    e.DragUIOverride.Caption = "TEST";
}
```
4. Try dragging over an Excel file, the `e.DragUIOverride.Caption = "TEST"` statement will throw a COM exception

### Expected behavior

The drag and drop should work without exceptions and multiple times.

### NuGet package version

WinUI 3 - Windows App SDK 1.4.4: 1.4.231219000

### Windows version

Windows 10 (21H2): Build 19044

### Additional context

Actual OS build: 19045.3930

**Comment by kmgallahan** [comment] 2024-01-29 23:50
Use `DragEnter` instead of `DragOver`.

The `DragOver` event gets dispatched many times per second until the drag stops. You are starting many instances of the handler that are all awaiting e.DataView.GetStorageItemsAsync and setting the drag properties at the same time, which is resulting in a problem *somewhere*.

**Comment by Arko109** [comment] 2024-01-30 10:17
I tried with `DragEnter` and setting the `AcceptedOperation` is not reliable, most of the time it doesn't work and the file drop isn't accepted. Also the COM exception still happens sometimes if you enter - exit - enter.

I also tried using `DragOver` with a semaphore to limit the number of instances of the handler to one and it didn't fix anything, the exception is still occurring.

**Comment by kmgallahan** [comment] 2024-01-30 13:30
This was interesting to play with. 

After testing I came to the same conclusions as found here #8108, which describes the issue and what is happening at a lower level.

The final reply states this is "by design". I don't think that is a great way to word it, but rather this is just what happens due to how the event processing system interacts with the DataExchangeHost.

Using a synchronous handler synchronous with `e.DataView.GetStorageItemsAsync().GetAwaiter().GetResult()` makes the problem go away, and also results in `DragEnter` working reliably so you aren't processing extra events.

**Comment by Arko109** [comment] 2024-01-30 14:31
`.GetAwaiter().GetResult()` fixes the exception for me. You can close this issue if you don't need it for following up.

**Comment by bpulliam** [comment] 2024-02-06 15:50
Closing as dup of #8108

**Closed by bpulliam** 2024-02-06 15:50 UTC
Labels: bug, needs-triage
