### ISSUE TITLE
The keyboard accelerator will cause webview2 to fail to respond to the English "." And the "delete" key

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#4773] opened 2021-04-09 06:58 UTC
1. can't input english '.' in editbox.
    load a url  with input control can reproduce。

2.  don't respond forward delete.
    load a url  with input control can reproduce。
3. conflict KeyboardAccelerator with key ='T'

```
<AppBarButton Icon="Play" Label="Run" Click="Run_Clicked">
    <AppBarButton.KeyboardAccelerators>
          <KeyboardAccelerator Key="F5" />
    </AppBarButton.KeyboardAccelerators>
</AppBarButton>
```
If i press `t` and will trigger `f5` handler.
![image](https://user-images.githubusercontent.com/16729017/114141256-f2c83e00-9943-11eb-96e3-f243bca16d81.png)

**Comment by StephenLPeters** [comment] 2021-04-09 23:20
@shelllet can you provide more information about your scenario? what is the editbox you are referring to? What do you mean by foreword delete, the delete key? what type of input control is being used.  Thank you!

**Comment by shelllet** [comment] 2021-04-10 01:42
> @shelllet can you provide more information about your scenario? what is the editbox you are referring to? What do you mean by foreword delete, the delete key? what type of input control is being used. Thank you!

i use webview2 to load monaco-editor .
yeah, it's delete key , i'm sorry for  my spell error.

I found it why,  i defined `MenuFlyout` in projectpanel.  simple project to reproduce: https://github.com/shelllet/simple

**Comment by DmitriyKomin** [comment] 2021-04-20 23:01
@shelllet - to confirm, are you using ENG / US Keyboard or some other? With that configuration at least, I don't repro (1) or (2) in simple test app with WV2 navigated to webpage with <input> element such as https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder.

Also, can  you elaborate on how MenuFlyout in projectpanel.simple is related to the WebView2 input issue? Is this relevant to just (1) & (2) or (3) also?

(3) - ['T' input to WV2 triggering 'F5' accelerator key handler] has also been filed separately as https://github.com/microsoft/microsoft-ui-xaml/issues/4858. Seems separate from (1) & (2), so keeping 4858 to track this.

**Comment by shelllet** [comment] 2021-04-21 02:51
> @shelllet - to confirm, are you using ENG / US Keyboard or some other? With that configuration at least, I don't repro (1) or (2) in simple test app with WV2 navigated to webpage with element such as https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_placeholder.
> 
> Also, can you elaborate on how MenuFlyout in projectpanel.simple is related to the WebView2 input issue? Is this relevant to just (1) & (2) or (3) also?
> 
> (3) - ['T' input to WV2 triggering 'F5' accelerator key handler] has also been filed separately as #4858. Seems separate from (1) & (2), so keeping 4858 to track this.

I recorded a video to show this problem. This video shows the complete process and includes how to comment the code to get webview2 back to work.

youtube link: https://youtu.be/fTEBiSCSbsw

**Comment by krschau** [comment] 2022-01-27 17:14
Hi @shelllet, could you check if you're still seeing this issue? I believe it might have been fixed (maybe it was the same as #4858) since I am unable to reproduce it now. Thanks!

**Comment by shelllet** [comment] 2022-01-28 02:03
ok, i will check it today.

**Comment by shelllet** [comment] 2022-01-28 09:41
![image](https://user-images.githubusercontent.com/16729017/151523666-4c78e08e-d463-4dcc-a212-8c936619f43b.png)

i update appsdk to 1.0 , and everything works fine.

i'm sure it's fixed.

**Comment by krschau** [comment] 2022-02-01 18:16
@shelllet Great! I will close this issue.

**Closed by krschau** 2022-02-01 18:16 UTC
Labels: area-WebView, team-Rendering, product-winui3, appModel-win32
