### ISSUE TITLE
WinUI3: Content dialog buttons don't respond to relay command enabling and disabling

### ISSUE THREAD

**Issue by ArchieHill** [microsoft/microsoft-ui-xaml#8563] opened 2023-06-17 19:36 UTC
### Describe the bug

On using Relay Commands you can control if a button is disabled or enabled based on the relay command's can execute property however this does not apply to the buttons of the content dialog itself (primary, close, secondary)

### Steps to reproduce the bug

1. Create commands and set the primary or other content dialog button to the command
2. Have the condition of the command to execute fail 
3. Observe the content dialog button set with the command is not disabled

### Expected behavior

On the condition of the command execution failing the content dialog buttons should be disabled like a normal button component does.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/94839295/772cb28b-c389-43e1-849b-dbfc0e4bf0ea)

The primary button and test button are set to use the same command.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/94839295/944dae6e-42b6-4016-b6e4-ca43f2a46233)

On loading the dialog the test button is disabled as the condition to execute the command is not met but the primary button is still enabled.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/94839295/cfa9e4f8-2a3d-4be8-a083-696587cae631)

On succeeding the condition the test button becomes enabled demoing the normal button works as expected.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/94839295/638b1e10-a826-42d3-9e29-9a9021e32b82)

Code for reference utilising the MVVM Community Toolkit

### NuGet package version

WinUI 3 - Windows App SDK 1.3.2: 1.3.230602002

### Windows version

Windows 10 (21H2): Build 19044

**Comment by IstvanKor** [comment] 2023-06-18 04:40
It's not the most perfect solution, but try setting the ContentDialog's IsPrimaryButtonEnabled and IsSecondaryButtonEnabled properties:

IsPrimaryButtonEnabled="{x:Bind YourViewModel.IsValid, Mode=OneWay}"

**Comment by ArchieHill** [comment] 2023-06-18 17:01
@IstvanKor Thanks, that's a good workaround. It would still be nice to have for consistency.

**Comment by leoshusar** [comment] 2023-06-18 22:41
I don't see this problem in my app.
Is the `gameDirectory` really null? I would say it's rather an empty string.

Also I don't know if you are using null reference types, but if you do, you should have `string? gameDirectory`.

And one more thing, you might look at MVVMToolkit validations, you can then build something like this:

```cs
public partial class AddGameViewModel : ObservableValidator
{
    [Required]
    [MinLength(5)]
    [ObservableProperty]
    [NotifyDataErrorInfo]
    private string? _gameDirectory;

    private bool IsValid => !HasErrors;

    [RelayCommand(CanExecute = nameof(IsValid))]
    private void AddGame()
    {
        // ...
    }
}
```

**Comment by ArchieHill** [comment] 2023-06-19 17:05
@leoshusar Thanks, for the suggestion. 

I've made the changes in a branch here: https://github.com/ArchieHill/BattleAssistant/tree/RelayCommandTesting
The primary button of the dialog still doesn't disable itself when the IsValid is false, maybe you could link your app so I can have a look at your implementation?

In the branch I have changed the IsValid a bit so it displays in the UI showing when its false or true. If you would like to have a mess around you're more than welcome to.

**Comment by leoshusar** [comment] 2023-06-19 19:51
I was wrong! I'm sorry! Your issue is valid.

I forgot I implemented it like this, actually using IsEnabled too:
```xaml
<ContentDialog
    ...
    PrimaryButtonClick="HostAssignmentDialog_PrimaryButtonClick"
    IsPrimaryButtonEnabled="{x:Bind ViewModel.HasErrors.Equals(x:False), Mode=OneWay}">

    <StackPanel>
        <StackPanel Spacing="28">
            <TextBox Header="Host" Text="{x:Bind ViewModel.Host, Mode=TwoWay}" />
        </StackPanel>
        <ProgressBar
            IsIndeterminate="True"
            Margin="0,28,0,0"
            Visibility="{x:Bind ViewModel.SaveCommand.IsRunning, Mode=OneWay}" />
    </StackPanel>
</ContentDialog>
```
```cs
private async void HostAssignmentDialog_PrimaryButtonClick(ContentDialog sender, ContentDialogButtonClickEventArgs args)
{
    var deferral = args.GetDeferral();
    
    await ViewModel.SaveCommand.ExecuteAsync(null);

    deferral.Complete();
}
```

because I have async command with progressbar while saving, the `PrimaryButtonCommand` would kill the dialog immediately without waiting for the async action to finish.

**Comment by kmahone** [comment] 2023-08-09 23:12
Dupe of: ContentDialog ignores ICommand.CanExecute #8215

**Closed by kmahone** 2023-08-09 23:12 UTC
Labels: bug, team-Controls
