### ISSUE TITLE
Possible memory leak in WinUI 3 Preview 3 when using ContentDialogs and UserControls

### ISSUE THREAD

**Issue by vadd98** [microsoft/microsoft-ui-xaml#4005] opened 2021-01-22 11:42 UTC
**Describe the bug**
I'm developing a Win32 Net5 app using the WinUI 3 Preview 3 and I'm getting some problems with possible memory leaks. I have a complex app which uses a lot of UserControl and ContentDialogs but, after they are out of scope, their memory is never released.

I'm trying to do some memory analyses using DotMemory and in the screenshot below it is possible to see one of the UserControl (named SongControl) that is never released. In particular, it is possible to see that the only thing that is retaining the UserControl is the so called "Regular Handle", which I think is a GCHandle from the internal WinUI code.

This SongControl is used in a ListView and is generated using an ObservableCollection as ItemSource. When I navigate away from the page with the ListView, I remove all the items present in the ObservableCollection (removing also all the event handlers linked to each item and setting all of them to null) and then set the collection to null.

As there is nothing in particular retaining the control, I believe that in a standard situation the internal WinUI code would have to remove that Regular Handle and allow the object to be collected, but it doesn't happen. Because of this, the memory footprint of my app keeps growing forever and so, soon or later, the user will get an OutOfMemoryException.

The same behaviour happens for every ContentDialogs I use. When they are closed, they are never released from memory, even setting them to null and removing all event handlers to which they are linked.

I already tried to set each UserControl and each ContentDialogs I use to null, set each control they contain to null, remove all event handlers, but nothing changed.

Any ideas on how to solve the problem?

**Steps to reproduce the bug**
1. Create a UserControl
2. Load it in a ListView using an ObservableCollection
3. Navigate away from the page
4. Destroy all the contents of the ObservableCollection
5. See that the memory is never released

**Expected behavior**
Memory has to be released

**Screenshots**
![Immagine 2021-01-21 230238](https://user-images.githubusercontent.com/71467711/105486476-d60a5b80-5cae-11eb-9dc6-a07e7c6564e7.png)

**Version Info**
WinUI 3 Preview 3. Windows 10 20H2. Net 5.

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No |  Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by StephenLPeters** [comment] 2021-01-23 00:09
@Scottj1s and @stevenbrix is this the same memory as this? https://github.com/microsoft/CsWinRT/issues/413

**Comment by stevenbrix** [comment] 2021-01-26 15:43
@StephenLPeters, yeah this does look like the same C#/WinRT issue.

**Comment by Scottj1s** [comment] 2021-01-26 16:14
Yes, this looks like a duplicate of microsoft/CsWinRT#413

**Comment by krschau** [comment] 2022-06-23 17:39
Closing this, as seems to be a dupe of https://github.com/microsoft/CsWinRT/issues/413, which was fixed. If you still see this problem in the latest WindowsAppSDK release, comment here and I'll reopen the issue, or open a new issue.

**Closed by krschau** 2022-06-23 17:39 UTC
Labels: duplicate, area-Dialogs, team-Controls, product-winui3

**Comment by KWodarczyk** [comment] 2022-10-24 16:39
I see the same problem 
wappsdk 1.2.220930.4-preview2
winui 3
windows sdk build tools 10.0.25227-preview
