### ISSUE TITLE
Exception thrown in .exe Microsoft C++ exception: winrt::hresult_error at memory location

### ISSUE THREAD

**Issue by sigmarsson** [microsoft/microsoft-ui-xaml#3741] opened 2020-12-02 11:03 UTC
![image](https://user-images.githubusercontent.com/43340959/100864348-2b3ba500-3496-11eb-8a5c-d5931c761ebe.png)

This exception was thrown after the process had started and already appeared on the taskbar.

**Comment by ranjeshj** [comment] 2020-12-03 00:10
@sigmarsson The screenshot does not provide much information to debug the issue you are seeing. Could you try debugging the issue based on the documentation [here](https://github.com/microsoft/microsoft-ui-xaml/blob/dfbe38bfb2996dfaa2f09544c4e86aa69ccc906b/docs/debugging_crashes.md).

**Comment by sigmarsson** [comment] 2020-12-03 08:38
@ranjeshj , please git the source from this rep; https://github.com/sigmarsson/NewRepo
1. Deploy the pkg
2. Hit F5
3. You ought to witness the C++ exception. 

![Uploading image.png…]()

**Comment by stevenbrix** [comment] 2020-12-03 22:15
@alwu-msft this looks like it is most likely another manifestation of the issue with CoreMRT.

@sigmarsson, these exceptions are usually harmless (and annoying), and you can just continue past them.

If you switch the packaging project from "Mixed" mode debugging to "Managed" you should no longer see these issues. Can you try that and let me know if that works?

**Comment by sigmarsson** [comment] 2020-12-04 09:54
Hi,

Now I am facing a different error in Managed mode;


![image](https://user-images.githubusercontent.com/43340959/101149066-b47de380-361e-11eb-91cc-d10603af9212.png)


F5


![image](https://user-images.githubusercontent.com/43340959/101149276-fe66c980-361e-11eb-900e-22e23eeaaddd.png)

**Comment by stevenbrix** [comment] 2020-12-04 19:04
@Ocalvo do you know what this error message means?

**Comment by sigmarsson** [comment] 2020-12-14 14:50
Howdy @ocalvo 

I am furnishing you the artifacts, please hit F5 & tell if you face the same fact as I do. Many thanks. 

[Repo](https://github.com/sigmarsson/3741)

**Comment by sigmarsson** [comment] 2020-12-18 16:33
- 1. This is yet persisting on my end in Mixed debug mode :

![image](https://user-images.githubusercontent.com/43340959/102637709-b1264400-4156-11eb-88d9-00818d141198.png)

- This exception is being thrown in Managed only :

`Opening a popup failed because the XAML runtime is running to support DesktopWindowXamlSource, and in this mode a popup must be a child of a live XAML element.`


Please advise something.

**Comment by sigmarsson** [comment] 2020-12-20 21:12
` <muxc:TabView x:Name="MainTabView">
            <muxc:TabView.TabItems>
                <muxc:TabViewItem Header="Welcome">
                    <muxc:TabViewItem.IconSource>
                        <muxc:SymbolIconSource Symbol="Placeholder" />
                    </muxc:TabViewItem.IconSource>
                    
                </muxc:TabViewItem>`


Problem is vanishing if this line is kept uncommented. 

This is the welcome page : 


`<Page
    x:Class="Weather.History.WinUI.Pages.WelcomePage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:local="using:Weather.History.WinUI.Pages"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
    mc:Ignorable="d">


    <Page.BottomAppBar>
        <CommandBar>
            <AppBarButton
                x:Name="back"
                HorizontalAlignment="Left"
                VerticalAlignment="Top"
                Icon="Back"
                Label="back" />
            <AppBarButton
                x:Name="next"
                HorizontalAlignment="Left"
                VerticalAlignment="Top"
                Icon="Forward"
                Label="forward" />
        </CommandBar>
    </Page.BottomAppBar>


    <Frame
        x:Name="WelcomeFrame"
        MinHeight="600"
        HorizontalAlignment="Stretch">
        <Frame.ContentTransitions>
            <TransitionCollection>
                <NavigationThemeTransition />
            </TransitionCollection>
        </Frame.ContentTransitions>
    </Frame>
</Page>
`

**Comment by BorzillaR** [comment] 2020-12-21 06:59
Hello!

I  have reproduced this issue in a simple scenario

![image](https://user-images.githubusercontent.com/23479280/102744945-0c7d4f80-436c-11eb-9e43-359350f4b7b3.png)

It seems the bottom app bar in UWP is opened in popup and that popup needs to be placed in the visual tree.

**Comment by sigmarsson** [comment] 2020-12-22 19:04
Thank you @BorzillaR !

**Comment by saurabh-mhaisekar** [comment] 2021-05-15 05:20
Facing same issue while creating simple Navigation view 
```c#
<Window
    x:Class="WinX.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:WinX"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:muxc="using:Microsoft.UI.Xaml.Controls"
    mc:Ignorable="d">
    <muxc:NavigationView x:Name="navigation">
        <muxc:NavigationView.MenuItems>
            <muxc:NavigationViewItem Icon="View" Tag="Apperance" />
        </muxc:NavigationView.MenuItems>
    </muxc:NavigationView>

</Window>
```

**Comment by evelynwu-msft** [comment] 2023-06-15 23:45
Closing as this does not repro with WinAppSDK 1.3.

**Closed by evelynwu-msft** 2023-06-15 23:45 UTC
Labels: team-Markup, team-Rendering, product-winui3
