### ISSUE TITLE
Xaml Islands Win32 MenuFlyoutSubItem crash

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#3530] opened 2020-10-30 17:44 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity2.visualstudio.com/t/Xaml-Islands-Win32-MenuFlyoutSubItem-cra/1237929?preview=true)._

---
[severity:It's more difficult to complete my work]
Use any Xaml Islands Win32 sample as base, e.g. Xaml-Islands-Samples

Add a MenuBar with two MenuFlyoutSubItem elements. E.g:

	<MenuBar>
		<MenuBarItem Title="MenuBarItem">
			<MenuFlyoutSubItem Text="MenuFlyoutSubItem1">
				<MenuFlyoutItem Text="MenuFlyoutItem1"/>
			</MenuFlyoutSubItem>
			<MenuFlyoutSubItem Text="MenuFlyoutSubItem2">
				<MenuFlyoutItem Text="MenuFlyoutItem2"/>
			</MenuFlyoutSubItem>
		</MenuBarItem>
	</MenuBar>
Run the app, open the menu, hover over the first SubItem until the menu animation starts playing, then quickly move to the second SubItem (or just move quickly between the two subitems without giving enough time for the animation to complete). The app will crash with: "Exception thrown at 0x030B450C (Windows.UI.Xaml.dll) in SampleCppApp.exe: 0xC0000005: Access violation reading location 0x00000000."

---
#### Feedback Bot on 10/29/2020, 07:16 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by aquinn39** [comment] 2020-12-25 13:04
I have this issue too.
It is very annoying and is very easy for users to trigger.

**Comment by lyahdav** [comment] 2021-04-26 23:50
I found a workaround: https://github.com/microsoft/microsoft-ui-xaml/issues/3529#issuecomment-827211418

**Comment by chrisglein** [comment] 2021-09-01 18:12
Duplicate of #3529

**Closed as completed** 2021-10-08 16:12 UTC
Labels: duplicate, area-Islands, needs-winui-3, team-Reach
