### ISSUE TITLE
Unable to drop items from ListView onto Grid in WinUI3 Desktop

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/microsoft-ui-xaml#2782] opened 2020-06-29 19:10 UTC
**Describe the bug**

We are able to drag and drop items from a ListView onto a Grid in our UWP application. 

However, once we switched over to WinUI3 Desktop, we are no longer able to drag and drop into the Grid.

**Steps to reproduce the bug**
1. Clone the [WinUI3 Problems DragDropListView repository](https://github.com/eleanorleffler/WinUI3_Problems_DragDropListView).
2. Go to the DragDropListViewWinUI folder.
3. Open the DragDropViewWinUI solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Attempt to drag one item from the ListView on the left to the right side
6. You should see the red "not permitted" symbol (circle with slash) as you are dragging over. See Screenshot#1.
7. Select two items and attempt to drag them onto the Grid on the right side.
8. You should see the red "not permitted" symbol (circle with slash) as you are dragging over.

**Expected behavior**

We expect to see the drag indicator change to "Open" and be able to drop items onto the Grid. 

For multiple items, we expect to see the checkbox with the number of dragged items while dragging.

We expect to see the same behavior we saw in UWP. See Screenshot#2 and Screenshot#3.

Build and run the DragDropListViewUWP solution inside the DragDropListViewUWP folder to see expected behavior.

**Screenshots**

![DragDropListViewCurrentBehavior](https://user-images.githubusercontent.com/9272634/86045924-efe20980-ba11-11ea-851a-6d72168f4dc3.PNG)

Screenshot#1 - Current Behavior

![DragDropListViewExpectedBehavior](https://user-images.githubusercontent.com/9272634/86045947-fbcdcb80-ba11-11ea-92b1-fb952c709d01.PNG)

Screenshot#2 - Expected Behavior - Single item dragged

![DragDropListViewExpectedBehaviorMultiple](https://user-images.githubusercontent.com/9272634/86045968-038d7000-ba12-11ea-89e8-21030a7d565a.PNG)

Screenshot#3 - Expected Behavior - Multiple items dragged

**Version Info**

NuGet package version:

[Microsoft.VCRTForwarders.140 1.0.6]
[Microsoft.WinUI 3.0.0-preview1.200515.3]

Targeting:

Target: Universal Windows
Target version: Windows 10, version 1809 (10.0; Build 17763)
Min version: Windows 10, version 1809 (10.0; Build 17763)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |                       |
| November 2019 Update (18363)  	 |                       |
| May 2019 Update (18362)            |                       |
| October 2018 Update (17763)        | Yes                   |
| April 2018 Update (17134)          |                       |
| Fall Creators Update (16299)       |                       |
| Creators Update (15063)            |                       |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop               | Yes                  |
| Mobile                |                      |
| Xbox                  |                      |
| Surface Hub           |                      |
| IoT                   |                      |

**Additional context**

When we debugged the solution, we noticed that the listView_DragItemsStarting (MainPage.xaml.cs Line 42) is called and identifies the items dragged.

However, the dropGrid_DragOver (MainPage.xaml.cs Line 51) and dropGrid_Drop (MainPage.xaml.cs Line 57) do not get called during the drag and drop.

**Comment by StephenLPeters** [comment] 2020-06-29 23:08
Almost certainly the same root cause as #2783

**Comment by jevansaks** [comment] 2020-09-13 03:08
I verified that the same fix that address #2783 fixed this. Will be in the next WinUI3 preview. Thanks for the report!

**Closed by jevansaks** 2020-09-13 03:08 UTC
Labels: Area-Desktop, area-Lists, duplicate, winui3preview
