### ISSUE TITLE
Proposal: Allow to select the whole paragraph with triple click

### ISSUE THREAD

**Issue by MarcAnt01** [microsoft/microsoft-ui-xaml#2619] opened 2020-06-07 10:03 UTC
In a TextBlock or in a RichTextBlock allow to select the whole paragraph with triple mouse/touchpad click

# Proposal: [Allow paragraph selection with triple click] 

## Summary
In a TextBlock or in a RichTextBlock allow to select the whole paragraph with triple mouse/touchpad click

## Rationale
* Match textboxes behaviour

**Comment by Felix-Dev** [comment] 2020-06-07 10:57
Related #2128

**Comment by chrisglein** [comment] 2020-06-16 18:14
Added the mention of triple-click to #2619. Good catch.

Duplicate of #2619.

**Closed by chrisglein** 2020-06-16 18:14 UTC
Labels: area-TextBlocks, feature proposal, needs-triage, team-Framework
