### ISSUE TITLE
Xaml Internal Error error WMC9999: Operation is not supported on this platform.

### ISSUE THREAD

**Issue by kant2002** [microsoft/microsoft-ui-xaml#5325] opened 2021-06-30 11:35 UTC
Create WinUI desktop application (non-UWP)
When attempt to run using `dotnet run`

```
       Using "CompileXaml" task from assembly "....packages\microsoft.projectreunion.winui\0.8.0\buildTransitive\..\tools\Microsoft.UI.Xaml.Markup.Compiler.dll".
       Task "CompileXaml"
         Xaml Compiler Marker: 5:30:18 PM: 378 perfXC_StartPass1, App1
         Xaml Compiler Marker: 5:30:18 PM: 396 perfXC_FingerprintCheck, Reference Assemblies Fingerprint Changed
         Xaml Compiler Marker: 5:30:18 PM: 397 perfXC_CreatingTypeUniverse
         Xaml Compiler Marker: 5:30:18 PM: 399 perfXC_CreatedTypeUniverse
         Xaml Compiler Marker: 5:30:18 PM: 401 perfXC_CreatingSchemaContext
   1:7>...\packages\microsoft.projectreunion.winui\0.8.0\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(465,9): Xaml Internal Error error WMC9999: Operation is not supported on this platform. [App1\App1\App1\App1.csproj]
            at System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeInterfaceAsObject(Guid clsid, Guid riid) in System.Runtime.InteropServices.dll:token 0x6000048+0x5
            at System.Reflection.Adds.MetadataDispenser.GetDispenserShim() in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60012e9+0x1f
            at System.Reflection.Adds.MetadataDispenser.OpenFileAsFileMapping(String fileName) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60012eb+0x8
            at Microsoft.UI.Xaml.Markup.Compiler.Lmr.Loader.OpenMetadataFile(String filename) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x6001c73+0x1
            at Microsoft.UI.Xaml.Markup.Compiler.Lmr.Loader.ReadAssemblyFromFile(String file) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x6001c75+0x1
            at Microsoft.UI.Xaml.Markup.Compiler.Lmr.XamlTypeUniverse.LoadAssemblyFromFile(String path) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x6001ffd+0xe
            at Microsoft.UI.Xaml.Markup.Compiler.CompileXamlInternal.TryLoadAssembly(String reference) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60013df+0x1b
            at Microsoft.UI.Xaml.Markup.Compiler.CompileXamlInternal.LoadAssembly(String reference) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60013de+0x1
            at Microsoft.UI.Xaml.Markup.Compiler.CompileXamlInternal.LoadAssemblyItem(String item, Boolean isSystemAssembly) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60013dd+0x9
            at Microsoft.UI.Xaml.Markup.Compiler.CompileXamlInternal.LoadAssemblyItems(List`1 referenceAssemblies, Boolean isSystemAssembly) in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60013dc+0x1a
            at Microsoft.UI.Xaml.Markup.Compiler.CompileXamlInternal.LoadSchemaContext() in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60013e7+0x17
            at Microsoft.UI.Xaml.Markup.Compiler.CompileXamlInternal.DoExecute() in Microsoft.UI.Xaml.Markup.Compiler.dll:token 0x60013d9+0x243
         Xaml Compiler Marker: 5:30:18 PM: 440 perfXC_EndPass1, App1
```

**Comment by StephenLPeters** [comment] 2021-06-30 23:18
@kant2002 duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5327?

**Comment by kant2002** [comment] 2021-07-01 00:08
Technically this is different error. But based on answer on sibling issue you will probably close as not supported. Any chance that I can hack around somehow myself? I look for source code of MSBuild task, but cannot find it. If this task open sourced I can hack around and find real problem. Please advice.

**Comment by StephenLPeters** [comment] 2021-07-01 23:30
Unfortunately I don't think so.

**Closed** 2021-07-12 15:07 UTC
Labels: duplicate
