### ISSUE TITLE
WebView2.NavigateToString throws InvalidOperationException

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#3714] opened 2020-11-27 13:51 UTC
**Describe the bug**

`WebView2.NavigateToString` does not work in WinUI3 Preview3.

**Steps to reproduce the bug**

1. Create a new Blank App (Windows in Desktop)
2. Add the following below the `Button` on `MainWindow.xaml`
 `<WebView2 x:Name="MyWebView" Width="600" Height="400" />`

3. Add this to `myButton_Click` in `MainWindow.xaml.cs`

```cs
MyWebView.NavigateToString("<html><body><h2>This is an HTML fragment</h2></body></html>");
```

4. Run the app and click the button. See exception:

```ascii
System.InvalidOperationException
  HResult = 0x80131509
  Message=A method was called at an unexpected time.

  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.Controls.IWebView2.global::Microsoft.UI.Xaml.Controls.IWebView2.NavigateToString(String htmlContent)
   at Microsoft.UI.Xaml.Controls.WebView2.NavigateToString(String htmlContent)
   at App75.MainWindow.myButton_Click(Object sender, RoutedEventArgs e) in C: \Users\matt\source\repos\App75\App75\App75\MainWindow.xaml.cs:line 35
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.<>c__DisplayClass10_0.<Do_Abi_Invoke>b__0(RoutedEventHandler invoke)
   at WinRT.ComWrappersSupport.MarshalDelegateInvoke[T](IntPtr thisPtr, Action`1 invoke)
   at ABI.Microsoft.UI.Xaml.RoutedEventHandler.Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr e)
```

**Expected behavior**

The HTML content should be loaded in the WebView2 control.

**Screenshots**

**Version Info**

NuGet package version:  Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

The same code works with a `WebView` (not 2) in a UWP (WinUI2) app.

As `MediaElement` will not be supported in the GA release of WinUI3, being able to use an embedded browser control was going to be a workaround. With this error, there is no workaround for needing to include embedded media content in an app. 😞

**Comment by codendone** [comment] 2020-12-01 03:30
The issue is that the CoreWebView2 hasn't yet been created. This is a detail which needs to be added to the documentation for WebView2 element. Creation of the CoreWebView2 is triggered by only two actions: (1) setting WebView2.Source, or (2) calling WebView2.EnsureCoreWebView2Async().

For NavigateToString(), you should first call EnsureCoreWebView2Async() and either await for that to finish or listen for the CoreWebView2Ready event before calling NavigateToString().

**Comment by dotMorten** [comment] 2021-01-30 00:08
> For NavigateToString(), you should first call EnsureCoreWebView2Async() 

This is a terrible developer experience. The SDK should be doing that for us.

**Comment by sigmarsson** [comment] 2021-05-15 23:27
![image](https://user-images.githubusercontent.com/43340959/118380902-ef307280-b5e5-11eb-8a28-e4d93f6e874c.png)

**Comment by sigmarsson** [comment] 2021-05-16 21:26
this is indeed murky, never witness the event handler being invoked;

![image](https://user-images.githubusercontent.com/43340959/118413127-fc109d00-b69d-11eb-8008-9e97da6e0ed8.png)

![image](https://user-images.githubusercontent.com/43340959/118413149-1ba7c580-b69e-11eb-8b83-feced0463df0.png)

**Comment by sigmarsson** [comment] 2021-05-16 21:41
can i enforce anyhow it be initialized without specifying the `Source` ?

**Comment by codendone** [comment] 2021-05-18 23:34
@sigmarsson The CoreWebView2 won't be created without either setting `Source` or calling `EnsureCoreWebView2Async()`. Creating the CoreWebView2 is expensive, especially if there aren't already live CoreWebView2's in the app, since this will result in the core webview processes spinning up; because of this, we delay the creation until one of these APIs says it is needed.

We need to get clear documentation posted for these APIs and the behaviors around CoreWebView2 lifetime.

**Comment by sigmarsson** [comment] 2021-05-20 14:16
True @codendone. CoreWebView2 takes a significant chunk of time. I will try to invoke that ensure method in a startup task. Or could you recommend a different control, a kind of lite version of WebView2?

**Comment by codendone** [comment] 2021-05-28 03:58
@sigmarsson If you need web content, then WebView2 is the right control to use. I expect there will be additional performance improvements to WebView2 over time when performance opportunities are identified, but instantiating an HTML framework will always be expensive enough to merit being intentional about when your app needs to start paying that cost.

**Comment by sigmarsson** [comment] 2021-05-31 13:54
@codendone , how can i await an `IAsyncAction` in C# please ? 

`public IAsyncAction EnsureCoreWebView2Async()`

**Comment by codendone** [comment] 2021-06-01 02:25
@sigmarsson I recommend just a regular await:
```
    await myWebView2.EnsureCoreWebView2Async();
    myWebView2.NavigateToString("<html><body><h2>This is an HTML fragment</h2></body></html>");
```

(Or you could just do the EnsureCoreWebView2Async call once earlier, of course, if you don't want to call this or check if CoreWebView2 is null before each place which will use it.)

Note: I assume the "new WebView2()" part of your example was simply for brevity, but for documentation purposes I'd like to note here that `EnsureCoreWebView2Async()` needs to be called on the WebView2 instance you want to ensure has a CoreWebView2. This is why my example above calls uses an instance for this call and the following use.

**Comment by sigmarsson** [comment] 2021-06-02 19:20
@codendone splendid you stressed. 

I expected it would have been sufficient per process as 

![image](https://user-images.githubusercontent.com/43340959/120539710-24133680-c3e8-11eb-9e6e-f989fececbc2.png)

I must call this in the View-Model ctor after all.

**Comment by mbranscomb** [comment] 2021-06-29 01:02
It would be great if there was a convenient API to check if WebView2 is installed/available/valid e.g. `WebView2.IsAvailable()`

[This sample ](https://github.com/MicrosoftEdge/WebView2Samples/blob/9a076c4cbf7eee17f66ae3d373a859a5665e94d8/SampleApps/WebView2WpfBrowser/MainWindow.xaml.cs#L94) appears to show an approach that would enable you to call your own `IsWebViewValid` method.

But as far as I can tell, `WebView2.CoreWebView2` will always be null unless you have previously called `WebView2.EnsureCoreWebView2Async()` which results in a C++ exception if WebView2 is not installed?

```
Exception thrown at 0x00007FFE18D64B89 in ArcGISRuntime.WinUI.Viewer.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000FA9A579580.
```

**Comment by sigmarsson** [comment] 2021-06-29 07:32
@mbranscomb yeah, the WebView2 kit you currently install on your own, will be a part of the OS. However the target version not yet decided. Perhaps Microsoft intends to roll this out in Windows 11, which you can upgrade in October.

**Comment by taooceros** [comment] 2021-07-30 03:39
Hi, I have experienced this issue when using Maui with WinUI. How can I cast Maui WebView to WebView2 and ensure it is created?

**Comment by andrewleader** [comment] 2021-11-10 21:44
If this won't be fixed, the exception that's thrown should at least be informative and say that `EnsureCoreWebView2Async` needs to be called, rather than having devs result to a Google search to find this GitHub issue.

**Comment by sigmarsson** [comment] 2022-05-07 22:37
I invoke like this just to see how long it takes the init but I witness here an infinite waiting time ... 

![image](https://user-images.githubusercontent.com/43340959/167274026-70d5ac1e-a0da-42aa-9493-c9d90887703b.png)

How can I diagnose why this async method never finishes ?

**Comment by sigmarsson** [comment] 2022-05-30 09:52
@codendone does the following require elevated mode or is there a particular Windows policy setting must be considered ? I don't recall it was the case earlier. 

![image](https://user-images.githubusercontent.com/43340959/170966569-5cae52f7-99f5-436d-b1fc-7d2850788adf.png)

**Comment by sigmarsson** [comment] 2022-05-31 20:36
@dotMorten thanks for intending to engage here. ```.wait()```ed there only for the purpose to see the exception and see how long it takes while it is standing up. The "Access Denied" has taken me aback but of course no inner exception, no idea what the problem is .

**Comment by jamers99** [comment] 2022-07-19 19:37
This really needs to be fixed. Requiring calling another method before you call this one? Pathetic.

**Comment by mrlacey** [comment] 2023-07-29 14:51
If this isn't going to be fixed in the framework, would an analyzer to highlight the need for the additional call be a useful addition?  (perhaps as part of the community toolkit-- @michael-hawker ?? )

**Comment by dotMorten** [comment] 2023-07-29 14:54
I don’t think it’s much to ask to at least throw a helpful error message here. These are the kinds of razor cuts that are killing the developer experience

**Comment by bkudiess** [comment] 2024-08-23 17:56
Closing this as the error message is updated on latest releases. ![image](https://github.com/user-attachments/assets/8a18fd7e-69e2-4298-8632-aa5353b47cb7)

**Closed by bkudiess** 2024-08-23 17:56 UTC
Labels: bug, area-WebView, team-Rendering, product-winui3, Crash

**Comment by riverar** [comment] 2024-08-23 20:41
Looks good. I hope the practice of surfacing more informative errors is applied across all APIs where possible.
