### ISSUE TITLE
MenuFlyout requires 'slow moving cursor' (so my Terminal Tabs are finicky)

### ISSUE THREAD

**Issue by ekoschik** [microsoft/microsoft-ui-xaml#8921] opened 2023-09-26 21:12 UTC
### Describe the bug

In latest version of Terminal, right click a tab and move down to the 'Close...' option (note: NOT the close tab option).

Clicking on 'close...' will open a sub menu. But if you click on 'close...' and move to the right 'too quickly', the flyout doesn't open. It seems like XAML is slow to create this flyout, and it is responding to the cursor position at the time it finishes (requiring the cursor still be over the original menu item).

This is BAD. It means that anyone that wants to expand this menu item needs to do so verrrryyyyyyyyy slllllooooooowwwwwwwwwlllly. This requires waiting a full second or so, which is AGES.

Menus aren't easy, but they're also built on long standing muscle memory. If XAML wants to be the implementation of menus for REAL apps they should get the submenus opened instantly and even if the cursor moves away from the menu item that was clicked.

(Side note, you should also be able to click+drag to the side of an expandable menu to open it.)

### Steps to reproduce the bug

Terminal (I've got Windows Terminal Canary Version: 1.19.2511.0).
Open two tabs.
Right click one tab, expands the menu.

Move just above the 'close...' menu item (dont move over it yet).

Move over the 'close...' item, click, and move to outside the menu (must do fairly quickly). Menu does not respond to click.

Click again on 'close...', wait a seconds for the menu item to open. (Menu opens because cursor is still inside the original menu item.)

### Expected behavior

Obviously XAML menus should work like any other menu (without requiring the cursor stay over a menu item before the submenu is able to show itself).

### NuGet package version

None

**Comment by Permik** [comment] 2023-10-12 01:39
Can't reproduce this on Windows Terminal Canary Version: 1.19.2682.0, the dropdown shows instantly if the registry key "MenuShowDelay" set to 0 in "HKEY_CURRENT_USER\Control Panel\Desktop". The application needed to be fully terminated, before the changes came into effect.

This dropdown delay is typically handled via the registry key "MenuShowDelay" set to 400 by default in "HKEY_CURRENT_USER\Control Panel\Desktop".

**Comment by jeremy-visionaid** [comment] 2024-02-29 03:05
Oh yup, I'm seeing something pretty similar with #9371, though I'm not sure if it's the same issue/root cause...
Sometimes the sub menu flyouts are so slow to open it feels like somethings broken, sometimes for than a second, sometimes more like 2 or 3. Certainly a lot more than what `MenuShowDelay` is set to.

**Comment by jeremy-visionaid** [comment] 2024-02-29 03:09
I can repro the problem here with the terminal sub menu not opening immediately on click, but otherwise appears to be OK.

In the WinUI 3 Gallery though the MenuFlyout subitems take can take what feels like an age to open..

**Comment by kmgallahan** [comment] 2024-02-29 03:57
Possibly same issue as #939 with diagnosis found here: https://github.com/microsoft/microsoft-ui-xaml/issues/939#issuecomment-1837149717

**Comment by jeremy-visionaid** [comment] 2024-02-29 20:11
Hmm, #9371 was closed as a duplicate of this one, but there's no mention here that it's related to/caused by the screen refresh rate, which was what #9371 turned out to be, and what was identified in #939

**Comment by jeremy-visionaid** [comment] 2024-03-01 00:45
Still present in 1.5.240227000

**Comment by jeremy-visionaid** [comment] 2024-04-10 00:04
I'm no longer seeing this in 1.5.240404000 🎉

**Comment by bkudiess** [comment] 2024-08-20 18:49
This was fixed internally and will be available in the next release!

**Closed by bkudiess** 2024-08-20 18:49 UTC
Labels: bug, area-Flyouts, team-Controls
