### ISSUE TITLE
RichEditBox throws Microsoft C++ exception: error at memory location 0x0077DC10.

### ISSUE THREAD

**Issue by ssaran046** [microsoft/microsoft-ui-xaml#4688] opened 2021-03-29 05:01 UTC
**Describe the bug**

RichEditBox throws Microsoft C++ exception when select the RichEditBox text using mouse.

**Sample**

[Desktop_App.zip](https://github.com/microsoft/ProjectReunion/files/6219273/Desktop_App.zip)

**Steps to reproduce the bug**

1. Run the provided sample
2. Select rich edit box text using the mouse, it throws an exception when release the mouse left button

**Expected behavior**
It should not throw an exception.

**Screenshots**

![image](https://user-images.githubusercontent.com/24865096/112789063-db52a080-9079-11eb-8a15-df81c8a2ef42.png)

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-03-29 23:09
Closing as duplicate of #4686

**Closed by StephenLPeters** 2021-03-29 23:09 UTC
Labels: duplicate
