### ISSUE TITLE
Crash on creating multiple Window instances (WinUI3)

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#6208] opened 2021-11-01 12:24 UTC
**Describe the bug**
Creating more windows results in internal Exception.

![image](https://user-images.githubusercontent.com/4835617/139670580-c69c5328-6c48-4dc2-aa45-97699fa2fee0.png)

**Steps to reproduce the bug**

1. Use WinUI 3 with Windows App SDK 1.0 Preview 3
2. Follow these steps to create a new window:  https://docs.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.window?view=winui-3.0-preview#create-a-new-window
3. An internal exception is thrown

**Expected behavior**
It should be possible to create multiple Windows.

**Version Info**
NuGet package version: 
WindowsAppSDK 1.0 Preview 3

**Comment by asklar** [comment] 2021-11-03 16:15
Duplicate of #5918 
See comment here: https://github.com/microsoft/microsoft-ui-xaml/issues/5918#issuecomment-924584693
> Unfortunately the support for multiple Windows was not finished in time to be included in 1.0. The Experimental build had the block for this and other incomplete features disabled, and those blocks are re-enabled for Preview and Stable releases.

**Closed by asklar** 2021-11-03 16:15 UTC
Labels: needs-triage
