### ISSUE TITLE
NavigationView concurrency glitch

### ISSUE THREAD

**Issue by matheus-inacio** [microsoft/microsoft-ui-xaml#5474] opened 2021-07-15 03:37 UTC
**Describe the bug**

After upgrading to WinUI 2.6, i've noticed that sometimes the NavigationView gets in a corrupted state, with the menu opened but with a transparent background.

It seems to be happening randomly at times, but i've found a consistent way to reproduce the issue.

**Steps to reproduce the bug**
1. With the NavigationView in compact mode, press the toggle button in order to expand the menu.
2. While the menu is expanding quickly double click in the title bar twice in order to make the window maximize and minimize back to the compact mode.
3. The menu should now be open but without the background. (It may take a couple of tries)
4. Now if you maximize the window and press the toggle button again the menu items will not have their width updated.

**Screenshots**

### With the controls test app:
![ConcurrencyIssue1](https://user-images.githubusercontent.com/29243277/125724838-20b87f02-7d57-40a7-97a6-a4c191d1c541.gif)

### With the XAML Controls Gallery
![ConcurrencyIssue2](https://user-images.githubusercontent.com/29243277/125724854-44d822fd-7adb-42be-9460-c19862d5c2e5.gif)

**Version Info**
[Microsoft.UI.Xaml 2.6.1]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2021-07-15 23:22
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/5342 fixed by https://github.com/microsoft/microsoft-ui-xaml/pull/5431.  @karenbtlai FYI

**Closed** 2021-07-15 23:22 UTC
Labels: area-NavigationView, team-Controls
