### ISSUE TITLE
Drag-and-drop using TreeView with multi-select always drags the selected items

### ISSUE THREAD

**Issue by llongley** [microsoft/microsoft-ui-xaml#4093] opened 2021-02-04 00:28 UTC
Open up the XAML Controls Gallery app, navigate to the TreeView page, and scroll down to "A TreeView with Multi-selection enabled".  Click on the checkboxes next to "XYZ Functional Spec" and "Feature Schedule".  Click and drag "Feature Resources Allocation" to put it under "Home Remodel".

**Expected:** The item clicked on and dragged should be moved.

**Actual:** The selected items are dragged instead.

It'd make sense for clicking and dragging one selected item to drag all selected items, but it does not make sense for click-and-drag to still drag the selected items when the click was not one any of them.

**Comment by chingucoding** [comment] 2021-02-04 00:30
I think this is a dupe of #3097 looking at the description.

**Closed** 2021-02-06 00:23 UTC
Labels: duplicate, needs-triage
