### ISSUE TITLE
x:Bind does not update when a bool? is set to null

### ISSUE THREAD

**Issue by jbe2277** [microsoft/microsoft-ui-xaml#8241] opened 2023-02-25 19:46 UTC
### Describe the bug

I have a `x:Bind` that binds to a nullable boolean (`bool?`) property. It updates when it is set to `true` or `false`. But it does not update when it is set to `null`.

### Steps to reproduce the bug

1. Extract and open: [WinUIApp1.zip](https://github.com/microsoft/WindowsAppSDK/files/10832132/WinUIApp1.zip)
2. App contains a ThreeState CheckBox which allows to click between the states `true`, `false` and `null`. The state is bound to the property `IsChecked` in the `MainWindow.xaml.cs` class.
3. Two TextBlock show the actual state. The first one use `x:Bind` to show the state. The second one use code to update the state.
4. Run the app and click through the states. Both TextBlocks show the state. Only when the `Null` state is selected the first TextBlock will not update the shown state.

### Screencast
![WinUI-Issue](https://user-images.githubusercontent.com/10452896/221376787-3b9d9f20-9eca-48a5-bbf2-f138c257ed96.gif)

### NuGet package version

Windows App SDK 1.2.4: 1.2.230217.4

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### IDE

Visual Studio 2022

**Comment by gabbybilka** [comment] 2023-03-02 17:15
Thanks @michael-hawker, closing as dupe of #1904

**Closed by gabbybilka** 2023-03-02 17:15 UTC
