### ISSUE TITLE
CommandBar appears above NavigationView

### ISSUE THREAD

**Issue by yoshiask** [microsoft/microsoft-ui-xaml#2970] opened 2020-07-22 02:54 UTC
**Describe the bug**
My app has a MainPage with a NavigationView containing a Frame. When a CommandBar is in a page being displayed by the frame, it displays over the NavigationView (when it's in LeftCompact mode).

**Steps to reproduce the bug**
1. Create a blank UWP project targeting 2004 and install WinUI 2.4.2
2. In MainPage.xaml, replace the default Grid with a WinUI NavigationView, and set the NavigationView content to a Frame. Make sure that `PaneDisplayMode` is set to `LeftCompact`.
3. Create a new page and set BottomAppBar/TopAppBar to a new CommandBar.
4. In MainPage.xaml.cs, override the OnNavigatedTo event and navigate the frame to the new page.
5. Observe that the CommandBar covers the bottom/top of the NavigationView.

**Expected behavior**
The CommandBar should display underneath the NavigationView pane, just like the rest of the frame's contents.

**Screenshots**
Expected:
![image](https://user-images.githubusercontent.com/7549325/88128977-d1dc7480-cb8b-11ea-836c-0b8d6a392974.png)
Observed:
![image](https://user-images.githubusercontent.com/7549325/88128997-dacd4600-cb8b-11ea-9393-e0c51660ff5a.png)

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.4.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |
| Mobile                |  |

**Additional context**

**Comment by eugenegff** [comment] 2020-07-22 11:37
Seems that this is by design since Win8 times for appbars assigned to Page.BottomAppBar and Page.TopAppBar properties. You can instead place AppBar inline inside your Page.Content to achieve effect desired by you.

**Comment by yoshiask** [comment] 2020-07-22 15:02
Why is this by design though? I could understand if the NavigationView and CommandBar were directly in the same page, but they're not. The page in the frame should be displayed as if it was any other content, no?

**Comment by StephenLPeters** [comment] 2020-07-22 23:27
This is, unfortunately, by design. When these page properties were made it was assumed that they would be the root of the window and that drawing the appbar on top of the whole window would be appropriate. In this case it is not and looks broken, but it is how this api works.  Id suggest placing the commandbar in the root of the page instead.

**Closed** 2020-07-22 23:27 UTC
Labels: needs-triage
