### ISSUE TITLE
This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater.

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5092] opened 2021-05-26 15:59 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/This-version-of-Project-Reunion-requires/1430196)._

---
1. VS 2019 Preview installed
2. The steps here done: https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop
3. The error get: "This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater."

---
#### Feedback Bot on 5/24/2021, 01:41 AM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by asklar** [comment] 2021-05-26 19:09
Duplicate of 4894

**Closed** 2021-05-26 20:47 UTC
Labels: duplicate
