### ISSUE TITLE
WPF like designer for WinUI 3

### ISSUE THREAD

**Issue by ward-horsfall** [microsoft/microsoft-ui-xaml#6670] opened 2022-02-03 08:37 UTC
Hi,

Can we please have a designer like there is for WPF in WinUI 3. It would make development a lot easier.

Unless I am mistaken and there is one comming

Thanks,
Ward

**Comment by WelterDevelopment** [comment] 2022-02-03 18:22
Duplicate of #5917. Please just go there and leave a thumbs-up. There is nothing more we can do about it. 
If you have a simple app with a flat XAML tree, no attached properties and no ItemTemplateSelectors, XAML Hot Reload is actually quite usable!

**Comment by gabbybilka** [comment] 2022-02-08 08:00
Thanks for your feedback, I agree with @WelterDevelopment, let's centralize the discussion in the existing issue: #5917

**Closed by gabbybilka** 2022-02-08 08:00 UTC
Labels: needs-triage

**Comment by sasakrsmanovic** [comment] 2024-11-20 04:21
It will be of interest to anyone searching for a Designer.... Hot Design from Uno Platform achieves this goal of being a WPF like designer for WinUI 3(and other targets)

https://github.com/unoplatform/uno/discussions/18833
.NET Conf 2024 Session on Hot design:
 https://www.youtube.com/watch?v=sJPyieyt1Rc&list=PLdo4fOcmZ0oXeSG8BgCVru3zQtw_K4ANY&index=93
