### ISSUE TITLE
WinUI for Desktop Can't create the project

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#4617] opened 2021-03-22 18:02 UTC
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/WinUI-for-Desktop-Cant-create-the-proje/1359682)._

---
[regression] [worked-in:16.9]
Unable to create a WinUI project. The dialog for creating a new project takes a long long time and an error pops up.

---
#### Feedback Bot on 3/7/2021, 09:48 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment] 2021-03-22 23:09
If this worked in 16.9 and not in 16.10 this sounds like a VS issue. Not a Winui issue.

**Comment by StephenLPeters** [comment] 2021-03-22 23:10
@svetbonev do you agree? can you help us route this appropriately?

**Comment by SvetBonev** [comment] 2021-05-06 23:41
> @SvetBonev do you agree? can you help us route this appropriately?

I will reactivate the Developer Community issue. At the moment, there is not enough information to root cause the problem.

**Comment by chingucoding** [comment] 2021-05-24 18:45
@StephenLPeters Is this worth keeping open? Regardless of this, should we label this issue?

**Comment by evelynwu-msft** [comment] 2022-11-29 11:49
Closing as there is insufficient information at this time to diagnose the problem, and the accompanying Developer Community issue was already closed for the same reason.

**Closed** 2022-11-29 11:49 UTC
Labels: team-Markup
