### ISSUE TITLE
Question: Is any way to launch WinUI application from command line?

### ISSUE THREAD

**Issue by BorzillaR** [microsoft/microsoft-ui-xaml#3367] opened 2020-10-03 16:20 UTC
Hello!

I tried to use AppExecutionAlias as described [here](https://www.c-sharpcorner.com/article/launch-uwp-app-via-commandline/) in app manifest. Application starts and exists without any reasonable message. 

Should this approach works in WinUI for Desktop applications?

**Comment by StephenLPeters** [comment] 2020-10-05 23:22
@Austin-Lamb This sounds like something we should investigate.

**Comment by BorzillaR** [comment] 2020-11-18 12:19
Any news about it?

**Comment by BorzillaR** [comment] 2021-01-12 07:42
@Austin-Lamb, the main goal to launch the packaged WinUI app from command line as like as Win32 app.

**Comment by marb2000** [comment] 2021-02-20 07:22
@BorzillaR you can find a example of the AppExecutionAlias in Desktop [here](https://github.com/microsoft/WinUI-3-Demos/blob/master/src/WinUI3_Visual_Sorting_Items_Demo/SortingItemsWinUI3Demo/SortingItemsWinUI3Demo%20(Package)/Package.appxmanifest#L45).

Feel free to close the issue if this works for you.

**Comment by BorzillaR** [comment] 2021-02-24 13:12
AppExecutionAlias works fine in Desktop. 
Thank you, @marb2000, for pointing me to the solution.

Btw, is there a working sample for WinUI(Uwp) app?

**Comment by ziaulhasanhamim** [comment] 2022-01-17 04:26
Is it possible to support running winui 3 apps from command line like WPF with something like `dotnet run`?

**Comment by alexdi220** [comment] 2022-07-07 05:24
@marb2000 the AppExecutionAlias doesn't work for me on Windows 11. Is there any way to run the WinUI by command `dotnet run or exec` ?

**Comment by marb2000** [comment] 2022-07-11 22:32
I have updated the sample [Visual Sorting](https://github.com/microsoft/WinUI-3-Demos/tree/master/src/VisualSortingItems), and **I couldn't reproduce it**. It works well on Windows 11. Here are two things that come into my mind:
1. The name of the execution [alias](https://github.com/microsoft/WinUI-3-Demos/blob/6d273dfda7cc0651f8ef30fa9ad73ae6689c19e7/src/VisualSortingItems/Package.appxmanifest#L53) should be different to the .exe, because it will fail if you try to execute it from .exe folder.
2. If your app is unpackaged, it can be executed from the command line just by invoking the .exe. Take a look at this [comment](https://github.com/microsoft/WinUI-3-Demos/blob/6d273dfda7cc0651f8ef30fa9ad73ae6689c19e7/src/VisualSortingItems/VisualSortingItems.csproj#L16) that I have added. 

I hope that helps.

**Closed by marb2000** 2022-07-11 22:32 UTC
Labels: question, team-Reach, product-winui3, appModel-win32

**Comment by DierkDroth** [comment] 2023-02-08 07:28
@marb2000 I tried to follow your instructions above but ran into those problems
- my app does not start but throws a Window event (screenshot below). Do you have any idea what might be going on?
- next I tried your Visual Sorting sample but failed to start (2nd screenshot below) it. Installing the presumably 'missing' package did not resolve the issue. Updating to latest NuGet packages didn't help neither.

Do you have any idea what might be going on? Thanks in advance

<img width="911" alt="image" src="https://user-images.githubusercontent.com/26179242/217462273-36ace5ef-7d23-4bc8-8e9c-6c28b1065543.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/217462572-1d961e6d-c37e-4e21-a8c8-47dc0d8d3800.png">

**Comment by steam3d** [comment] 2023-02-09 10:45
I tested `ExecutionAlias`. It works, but I could not pass args when run from command line.  I always get empty args strings.

**Comment by Thomas-Lecuppre** [comment] 2023-03-21 21:50
> @BorzillaR you can find a example of the AppExecutionAlias in Desktop [here](https://github.com/microsoft/WinUI-3-Demos/blob/master/src/WinUI3_Visual_Sorting_Items_Demo/SortingItemsWinUI3Demo/SortingItemsWinUI3Demo%20(Package)/Package.appxmanifest#L45).
> 
> Feel free to close the issue if this works for you.

File as been removed

**Comment by KWodarczyk** [comment] 2023-08-23 12:48
Please provide an example to to pass arguments, If i run using ExecutionAlias the Kind i get is still "Launch" event though i run from command line
