### ISSUE TITLE
Folder picker not working

### ISSUE THREAD

**Issue by dynamiquel** [microsoft/microsoft-ui-xaml#2973] opened 2020-07-22 17:21 UTC
**Describe the bug**
When using the PickSingleFolderAsync() method from  Windows.Storage.Pickers.FolderPicker. The following exception is given: System.Runtime.InteropServices.COMException: 'Invalid window handle. (0x80070578)'

**Steps to reproduce the bug**
Use the following code:
```cs
var picker = new Windows.Storage.Pickers.FolderPicker();
picker.SuggestedStartLocation = Windows.Storage.Pickers.PickerLocationId.Desktop;
picker.FileTypeFilter.Add("*");

var folder = await picker.PickSingleFolderAsync();
```

**Expected behavior**
The folder picker opens.

**Screenshots**
![image](https://user-images.githubusercontent.com/50085636/88207435-b20a8680-cc47-11ea-831d-28e26599b4dd.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview2.200713.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by eleanorleffler** [comment] 2020-07-22 18:48
I had a similar issue #2716.

**Comment by jevansaks** [comment] 2020-09-10 05:16
Duplicate of #2716 (use [IInitializeWithWindow](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-iinitializewithwindow#when-to-use) to give the owner window).

**Closed by jevansaks** 2020-09-10 05:16 UTC
Labels: Area-Desktop, area-Tooling, team-Markup, winui3preview

**Comment by manurode** [comment] 2021-02-25 15:16
@jevansaks I'm using IInitializeWithWindow but I'm getting this:

System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))

**Comment by Osaxely** [comment] 2022-07-08 10:59
Same here. On a UWP (Windows.UI.Xaml) app.

**Comment by krschau** [comment] 2022-07-15 18:20
@manurode  @Osaxely  Are you using a WinUI 2 UWP app? The solution jevansaks gave is specific to WinUI 3, where there is no core window. In WinUI 2 the old solutions should work.
