### ISSUE TITLE
Add ability to copy the content of a MessageDialog

### ISSUE THREAD

**Issue by Aurumaker72** [microsoft/microsoft-ui-xaml#8474] opened 2023-05-11 14:58 UTC
# Copying the content of a MessageDialog
`MessageBox`es, which are the loose WinAPI equivalent of `MessageDialog`s, copy both the caption and content upon focusing them and pressing `Ctrl+C`.
The WinUI3 `MessageDialog` should allow copying the content in the same manner.

## Rationale

* Consistency with the equivalent legacy feature
* Enhances UX (e.g.: submitting error messages)

## Additional info
This feature could also be implemented for `ContentDialogs` which don't have complex content.

**Comment by JaiganeshKumaran** [comment] 2023-05-12 03:58
MessageDialog is an old Windows 8 API and shouldn't be used in WinUI 3 apps. With ContentDialog, you can implement this manually.

**Comment by Aurumaker72** [comment] 2023-05-12 15:43
> MessageDialog is an old Windows 8 API and shouldn't be used in WinUI 3 apps.

Indeed. However, this feature would yield an improvement to UX for all apps still relying on this old (but still non-deprecated) API.

> With ContentDialog, you can implement this manually.

This is possible, but introduces additional complexity on the user side. 
If the `ContentDialog` consists of only a `TextBlock` (default correlated control for when the `ContentDialog`'s `Content` is set to a `string`), it would be convenient to get copying out-of-the-box, as there's no non-text content.

**Comment by zadjii-msft** [comment] 2023-05-18 20:33
Looks like a dupe of #5573 to me.

**Comment by asklar** [comment] 2023-05-26 02:37
MessageDialog is not a XAML/WinUI API, so while this request makes sense it is out of scope for this repo.

**Closed by asklar** 2023-05-26 02:37 UTC
Labels: feature proposal, area-External
