### ISSUE TITLE
WinUI 3 Preview 4 ContentDialog exception.

### ISSUE THREAD

**Issue by Noemata** [microsoft/microsoft-ui-xaml#4353] opened 2021-02-25 22:18 UTC
**Describe the bug**
The following code works in UWP, but generates an exception in WinUI 3 Preview 4:

```
                    var dialog = new ContentDialog
                    {
                        Title = "Notice",
                        Content = "Navigate to a page before selecting settings.",
                        CloseButtonText = "Ok",
                    };

                    // MP! why: System.ArgumentException : Value does not fall within the expected range."
                    ContentDialogResult result = await dialog.ShowAsync();
```

**Steps to reproduce the bug**
1. Create a solution with the above snippet of code.

**Expected behavior**
The code should work (not generate a System.ArgumentException)

**Screenshots**
n/a

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview4.210210.4]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| October 2020 Update (19042)        | Yes  |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Additional context**
n/a

**Comment by Noemata** [comment] 2021-02-26 00:01
Digging through the docs, I noticed that for WinUI's ContentDialog, you have to set the XamlRoot property before displaying the dialog.  This constitutes a breaking change compared to UWP's ContentDialog as it has no such requirement when instantiated through code.

This requirement complicates MVVM usage and will make porting certain UWP code more tedious.

If I'm hoisting up a Dialog from an MVVM ViewModel, how do I make sure it's attached to a right window in the right state?  A critical system message dialog may need to be app modal and topmost so I can be sure the user sees it.  It can't depend on a window that might have gone away or may be minimized.

**Comment by StephenLPeters** [comment] 2021-02-26 00:07
ContentDialog will get the xaml root set automatically if you parent it to a page, like would be the case if you include it in your xaml file. So the simplest solution would be to put the content dialog in the same xaml file as the stuff you want it to display over. This is only an issue for content dialogs you make from code. It isn't an issue for UWP apps because there can only be one xaml root for UWP apps, but fore desktop apps you can have multiple.

Duplicate of: https://github.com/microsoft/microsoft-ui-xaml/issues/4251

**Closed** 2021-02-26 00:08 UTC
Labels: area-Desktop, area-Dialogs, duplicate, team-Controls, winui3preview

**Comment by Noemata** [comment] 2021-02-26 00:47
@StephenLPeters , agreed, except that parenting isn't necessary in UWP.  I'm not sure how UWP handles this, presumably through the AppModel's core window?

The behavior should be the same in both UWP and WinUI.  It would be unfortunate to require lots of compile time checks to select different code paths.  The goal should be to minimize friction from UWP to WinUI.  Some things are looking very good that way.  Would be nice to have a mostly seamless transition.  Little details add up.

**Comment by Noemata** [comment] 2021-02-26 18:32
I disagree with the closure of this issue, since this is a breaking change that complicates porting UWP code to WinUI.

**Comment by StephenLPeters** [comment] 2021-03-03 01:31
In UWP there is alway only one xaml root, so the system is able to infer that the singleton is the one it should use.  You can set the XamlRoot in UWP it wont hurt, so you don't need a compile time check, you could just always set it.

I closed this issue because it is a dupe of #4251 and we like to have only one open issue per actual issue.

**Comment by Noemata** [comment] 2021-03-04 13:08
As this sample demonstrates: https://github.com/Noemata/SimpleMVVM

It's quite easy to "port" a UWP app over to WinUI.  It's also relatively easy to have common code between the two.  Unfortunately, the little differences will add up.  Why add to the friction?

@StephenLPeters , using your logic, I could make an equally valid argument for the WinUI framework setting XamlRoot so that it defaults to the handle of the launching window.

So my real point is about eliminating the friction between UWP and WinUI.

If there were a compile time switch for namspaces so I could do something similar to "using x=y" but without changing code, I could then easily move lots of code over to WinUI.  Yes, it is fairly easy to have common code.  Why not make it even easier?

**Comment by StephenLPeters** [comment] 2021-03-05 00:19
In winui desktop a single launching window can have as many xaml roots as you want. So in Winui desktop we can't divine the proper xaml root from the launching window.

I don't really understand the compile time switch recommendation. the types being used in UWP and Desktop are the same, there are just slightly different behaviors because of fundamental app model differences.

**Comment by Noemata** [comment] 2021-03-05 01:50
@StephenLPeters , I surrender.  You guys win as per usual, though the losers will also be the corporate customers I support when I tell them porting their large UWP projects won't be so easy.

Here's what I want to avoid, among the many other details:

```
#if WINDOWS_UWP
using Windows.UI.Xaml;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Controls;
#else
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Data;
using Microsoft.UI.Xaml.Controls;
#endif
```

I suggest you try and seamlessly port this: https://github.com/Alvaromah/eShopOnUWP to WinUI, and see how that works out for you.  It's Microsoft's own creation, and it's full of bits that require lots of tweaking.

**Comment by StephenLPeters** [comment] 2021-03-06 00:40
It seems like my answers to your questions are frustrating you.  I'm sorry if my tone has come across as dismissive, that was not my intention.  The differences between the desktop and uwp application models are complicated and lead to complicated issues, this being one of them.  We do strive for the experience of upgrading or porting an app to Winui 3 to be as seamless as possible, feedback about the pain points in this space is extremely valuable and we really do appreciate your help identifying the issues we have with the product. My responses are simply trying to explain why things are the way they are today, I was not trying to justify them as good or correct. Recognize that winui3 is still very much in a preview state, we have a number of issues like this and definitely need to figure out the best way to resolve them.  One idea for this particular scenario would be that if they system detect that there is only one xaml root in your app, to default the xaml root property of all elements to that.  I don't think that is something that has been considered.

**Comment by Noemata** [comment] 2021-03-06 01:53
@StephenLPeters , your suggestion "if the system detects that there is only one xaml root in your app, to default the xaml root property of all elements to that", is the sort of compromise that would work in many cases.

I do appreciate that it's not possible to have a one size fits all approach with WinUI.  I'm just looking to minimize the grief involved in transitioning from UWP to WinUI, since this will be the path of least resistance toward WinUI adoption.

I do recommend that you try to port this code over to WinUI to get a feel for what's involved: https://github.com/dotnet-architecture/eShopOnUWP

I picked this particular example since it is representative of typical corporate apps, warts and all.  It took me 4 days to get it working with WinUI (trying to work as quickly as possible).  The XamlRoot issue was minor.  My approach there would normally be to adjust the original source as you had suggested.  That said, the pain points accumulate.  This one seemed to have a reasonable "default" solution as you've suggested.

The namespace change makes maintaining two sets of mostly similar code a drag and error prone.  Getting rid of this one pain point would go a long way toward easing the transition to WinUI.  Given WinUI is so very close to UWP and quite accessible to anyone familiar with UWP, shortening the gap will only accelerate adoption of WinUI.

One other key point I'd like to make ... I'm baffled that WinUI on UWP isn't getting more priority.  I would have gotten that over the finish line first since it would accelerate the prospect of getting a large number of UWP apps onto WinUI because the first part of the transition work could be done with less friction.  UWP devs could keep there WinUI store app as is, and look forward to extending capabilities for a desktop deployment.  Microsoft would gain valuable input on the initial migration process while ensuring the creation of a healthy eco system of apps for WinUI desktop when it was finished.

The current desktop centric approach for WinUI will tend alienate both UWP devs and WPF devs, the two most likely early adopters.  My two cents worth.

As for first impressions; Preview 4 did surprise me.  Most things just work!  Much better than Preview 3.  With some strategic choices made to facilitate ease of transition from UWP and the addition of missing LOB capabilities, WinUI could start to get some serious attention.

**Comment by Noemata** [comment] 2021-03-08 13:34
One cool way to sort out the namespace problem would be to add a mechanism that is available at the project level.  So within my WinUI version of the project, I draw from the same sources, thus at the source code level there are zero changes, but within the build parameters of the project, I set a namespace mapping that acts as an override for what is in the source code.  This facility would be useful beyond just supporting WinUI migration for C# work.  Something along the lines of:

```
...
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
...
    <NameSpaceOverrides>
	Windows.UI.Composition = Microsoft.UI.Composition
	Windows.UI.Xaml.Navigation = Microsoft.UI.Xaml.Navigation
    </NameSpaceOverrides>
```
