### ISSUE TITLE
NavigationView causes crash in Reunion-0.5 pre UWP

### ISSUE THREAD

**Issue by kalin-todorov** [microsoft/microsoft-ui-xaml#4499] opened 2021-03-12 10:16 UTC
**Describe the bug**
Defining NavigationView on the MainPage throws exception with Reunion-0.5pre

**Steps to reproduce the bug**

1. Create a blank WinUI 3 for UWP application with Project Reuninon SDK.
2. Put NaviagionView on the MainPage.
3. Run the app

**Expected behavior**
The app to run correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/8479530/110925523-f9a36700-832b-11eb-8443-ddbd4b1dec0b.png)

**Stack Trace**
onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!152944D2: (caller: 15294327) ReturnHr(1) tid(6e24) 80070490 Element not found.
onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!152944D2: (caller: 15293FE7) ReturnHr(2) tid(6e24) 80070490 Element not found.
onecore\internal\sdk\inc\wil\opensource/wil/com.h(1256)\Microsoft.UI.Input.dll!7BA3EDAB: (caller: 7BA3F8FD) ReturnHr(1) tid(6e24) 80004002 No such interface supported
onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!152944D2: (caller: 15293FE7) ReturnHr(3) tid(6e24) 80070490 Element not found.
'App14.exe' (Win32): Loaded 'C:\Program Files\WindowsApps\Microsoft.ProjectReunion.0.5-Prerelease_0.52103.9000.0_x86__8wekyb3d8bbwe\Microsoft.DirectManipulation.dll'. 
'App14.exe' (Win32): Loaded 'C:\Windows\SysWOW64\Windows.Energy.dll'. 
onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!152944D2: (caller: 15294327) ReturnHr(4) tid(6e24) 80070490 Element not found.
onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!152944D2: (caller: 152941D6) ReturnHr(5) tid(6e24) 80070490 Element not found.
onecoreuap\windows\wgi\winrt\display\displaycommon.cpp(411)\Windows.Graphics.dll!152944D2: (caller: 15294327) ReturnHr(6) tid(6e24) 80070490 Element not found.
onecoreuap\base\mrt\runtime\src\cresourcemanagerinternal.cpp(682)\mrmcorer.dll!14485348: (caller: 1448D98A) ReturnHr(1) tid(6e24) 80073B1F ResourceMap Not Found.
onecoreuap\base\mrt\runtime\src\cresourcemanagerinternal.cpp(575)\mrmcorer.dll!1448DA5B: (caller: 14484957) ReturnHr(2) tid(6e24) 80073B1F ResourceMap Not Found.
onecoreuap\base\mrt\runtime\src\cresourcemanagerinternal.cpp(1672)\mrmcorer.dll!1448497D: (caller: 14484E65) LogHr(1) tid(6e24) 80073B1F ResourceMap Not Found.
App14.exe has triggered a breakpoint.

Exception thrown at 0x764C46D2 (KernelBase.dll) in App14.exe: 0x00000004: The system cannot open the file (parameters: 0x80073B1F, 0x00000003).
Unhandled exception at 0x764C46D2 (KernelBase.dll) in App14.exe: 0x00000004: The system cannot open the file (parameters: 0x80073B1F, 0x00000003).

onecoreuap\base\mrt\runtime\com\winrt\core\lib\winrtresourcemap.cpp(444)\mrmcorer.dll!144DA8BB: (caller: 14087AA9) ReturnHr(3) tid(6e24) 80073B1F ResourceMap Not Found.
Exception thrown at 0x764C46D2 (KernelBase.dll) in App14.exe: WinRT originate error - 0x80073B1F : 'ResourceMap Not Found.'.

NuGet package version: 
WinUI 3 - Project Reunion 0.5 Preview: 0.5.0-prerelease

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |

**Comment by huoyaoyuan** [comment] 2021-03-12 14:07
Duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/4496

**Comment by kalintodorov** [comment] 2021-03-12 15:40
> Duplicate of #4496

Saw the other one, however the root cause of this issue seems different to me. This one is in UWP and it doesn't seem to be related to brushes.

**Comment by StephenLPeters** [comment] 2021-03-13 00:06
@ojhad FYI.  If this is a different issue from 4496 and this is unique to UWP we should tag it with Winui3-UWP tag as well.

**Comment by StephenLPeters** [comment] 2021-03-13 00:07
@kalintodorov does the work around huoyaoyuan suggests in #4496 work for your UWP application?

**Comment by Noemata** [comment] 2021-03-13 20:35
Disable C++ exceptions as shown here: https://github.com/microsoft/microsoft-ui-xaml/issues/4510

**Comment by kalintodorov** [comment] 2021-03-15 08:53
> @kalintodorov does the work around huoyaoyuan suggests in #4496 work for your UWP application?

No - it doesn't work.

**Comment by kalintodorov** [comment] 2021-03-15 08:55
> Disable C++ exceptions as shown here: #4510

Already did that - continues to crash :)

**Comment by Noemata** [comment] 2021-03-15 20:28
@kalin-todorov , I'm using NavigationView here: https://github.com/Noemata/FakePOS/blob/master/FakePOS/FakePOSuwp/Views/ShellView.xaml

After disabling c++ exceptions, it's working in this app.  So there may be more in the mix than just the NavigationView in your case.

**Comment by kalin-todorov** [comment] 2021-03-16 09:01
@Noemata attaching sample project here:
[App15.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6147368/App15.zip)

**Comment by Noemata** [comment] 2021-03-16 11:41
@kalin-todorov , sorry to report this, but your sample is working for me:

![image](https://user-images.githubusercontent.com/6632315/111303541-04f7da80-862b-11eb-8086-46e2b86121a6.png)

**Comment by kalin-todorov** [comment] 2021-03-16 14:01
Hm interesting - my Win 10 is 18362.1256 and running the project with the latest preview 16.10 preview 1.

**Comment by Noemata** [comment] 2021-03-16 14:33
@kalin-todorov , obviously VS unlikely to be the issue, I just wanted to give you the full picture of what my side looks like.  The OS could be, or something else on your system that has gummed things up.  I have run into other problems with WinUI over UWP, but not what you're seeing.  I'm going to wait for the next release before I seriously start looking at WinUI over UWP.  It doesn't bring anything new to the table yet other than making it easy to author across UWP and desktop.  I'm hoping perf isn't degraded for the UWP side of things as that will void the prospect of considering WinUI over UWP for most of my customers (high perf TV Broadcasting apps).  Fingers crossed Microsoft keeps the UWP side of things as is or improves things even more.

**Comment by kalin-todorov** [comment] 2021-03-17 07:33
FYI: upgraded the OS to 19041 and the project started to work.

**Comment by Noemata** [comment] 2021-03-17 11:40
@kalin-todorov , cool that you got it resolved!

**Comment by anawishnoff** [comment] 2021-04-27 18:17
Hi @kalin-todorov, you should see a fix for this bug in the upcoming WinUI 3/Project Reunion 0.8 Preview, which you can expect soon. Thanks for filing this!

**Closed** 2021-06-29 14:54 UTC
Labels: ProjectReunion 0.5, area-NavigationView, fixed-in-Reunion0.8, fixed-internally, team-Rendering, winui3preview
