### ISSUE TITLE
MapControl: StyleSheet doesnt't work

### ISSUE THREAD

**Issue by anurkalem** [microsoft/microsoft-ui-xaml#2163] opened 2020-03-25 13:14 UTC
I create a WPF application and add Microsoft.Toolkit.Wpf.UI.Controls NuGet packages to my project. After that, I add to map my MainWindow.xaml. Then, I enter MapServiceToken and run the program. Everything is okay but when I try to change StyleSheet as an JSON or other styles like MapStyleSheet.RoadDark(), there are no change in the theme. Map will not be customized. I try to change stylesheet before and after Loaded event, there is no change. What should I do?

Note: I try this in .NET Framework 4.6.2, 4.7.2 and 4.8

**Comment by ranjeshj** [comment] 2020-03-25 13:37
@anurkalem Microsoft.Toolkit.Wpf.UI.Controls nuget is not from this repo. @michael-hawker Is this in the community toolkit ? If  so, we should file this issue in the tookit repo.

**Comment by michael-hawker** [comment] 2020-04-29 16:46
@anurkalem this sounds like [this issue](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/205) we have on the toolkit repo. That repo would be the right place to file an issue if it's not a duplicate of the one I just linked to. Let us know.

@ranjeshj we can close this here. FYI @marb2000

**Closed** 2020-04-29 16:52 UTC
Labels: area-External
