### ISSUE TITLE
Question: why there is shadow in ExpanderHeader when Expander is Expanded?

### ISSUE THREAD

**Issue by RekiDunois** [microsoft/microsoft-ui-xaml#6248] opened 2021-11-06 09:16 UTC
When the Expander is not Expanded

![image](https://user-images.githubusercontent.com/23435534/140604346-09e64425-ed87-4d86-9e11-e50c2a2372a8.png)

When it Expanded, shadow is appeared, but the `Shadow` property is null both in `ExpanderHeader` and `ExpanderContent`

![image](https://user-images.githubusercontent.com/23435534/140604355-7b2f5ff5-867d-4386-9a7c-9142c7a23428.png)

Where can I configure or disable this shadow?

The version of WinUI I am using is:

```xml
<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.0.0-preview3" />
```

**Comment by RekiDunois** [comment] 2021-11-10 08:45
I found that the shadow is come from button, since the header of `Expander` is a `ToggleButton`. And the button control seems to have those shadow effect too. To trigger the shadow, you need to change the `CornerRadius` of the `Button`:

```xaml
<Button CornerRadius="5,0,0,5" Content="TestButtonShadow" Background="Green"/>
<Button CornerRadius="0,5,5,0" Content="TestButtonShadow" Background="Green"/>
<Button CornerRadius="0,5,0,5" Content="TestButtonShadow" Background="Green"/>
<Button CornerRadius="5,0,5,0" Content="TestButtonShadow" Background="Green"/>
<Button CornerRadius="0,0,5,5" Content="TestButtonShadow" Background="Green"/>
<Button CornerRadius="5,5,0,0" Content="TestButtonShadow" Background="Green"/>
```

and the button would looks like:

![image](https://user-images.githubusercontent.com/23435534/141079935-d3a633c5-0ac6-42b6-a381-c203fdb2c879.png)

**Comment by kmgallahan** [comment] 2021-11-10 12:28
Probably related / dupe of #6194

**Comment by StephenLPeters** [comment] 2022-02-10 23:05
agreed, @codendone and @gegao18 fyi

**Comment by codendone** [comment] 2022-02-11 03:51
Thanks for the investigation, @RekiDunois! Given that, I agree this is the same as #6194,  and we believe we just identified the cause of that issue.

**Closed by codendone** 2022-02-11 03:51 UTC
Labels: area-Shadows, question, needs-triage, team-Rendering
