### ISSUE TITLE
Why ThemeShadow looks not right?

### ISSUE THREAD

**Issue by HppZ** [microsoft/microsoft-ui-xaml#1084] opened 2019-07-20 14:00 UTC
https://github.com/HppZ/ThemeShaowApp

![image](https://user-images.githubusercontent.com/12285582/61579551-18daf880-ab39-11e9-804e-fbbf3a4ddf3a.png)

**Comment by mdtauk** [comment] 2019-07-20 14:03
How ThemeShadow works is explained in this duplicate issue #1037

**Comment by HppZ** [comment] 2019-07-20 14:08
is there any solution available?

**Comment by mdtauk** [comment] 2019-07-20 14:15
> is there any solution available?

For shadows in general?  I'd say not right now,  I don't think shadow rendering is something that will be fixed before WinUI 3.0 is out at the end of the year or early next year.

Have you considered using the [**Teaching Tip**](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/dialogs-and-flyouts/teaching-tip) control - you seem to be building the same kind of thing.

![image](https://user-images.githubusercontent.com/7389110/61579755-31c7b780-ab01-11e9-841f-084ce4393e0c.png)

**Comment by HppZ** [comment] 2019-07-20 14:26
1, so it will be fixed in WinUI 3.0?

2, the TeachingTip control is great, but I don't like the border line, if I remove  the border, the shadow behind the triangle(that Polygon) is almost invisible, and that looks bad.

3, if I set the shadow on the border itself, it looks like this, the shadow on the top is almost invisible.
![image](https://user-images.githubusercontent.com/12285582/61579861-4e81e080-ab3d-11e9-976c-f4b8a09ccdc3.png)

**Comment by mdtauk** [comment] 2019-07-20 14:34
> 1, so it will be fixed in WinUI 3.0?
> 
Nothing has been confirmed, but there is another issue about this, but someone from the team @jevansaks has commented.

> 2, the TeachingTip control is great, but I don't like the border line, if I remove the border, the shadow behind the triangle(that Polygon) is almost invisible, and that looks bad.
> 
> 3, if I set the shadow on the border itself, it looks like this, the shadow on the top is almost invisible.
>
I imagine the border around the control was to deal with the issue of the tail arrow being lost because of the box shadowing.

**Comment by HppZ** [comment] 2019-07-20 14:41
> I imagine the border around the control was to deal with the issue of the tail arrow being lost because of the box shadowing.

the border looks really bad, what do you think? @mdtauk @jevansaks

**Comment by mdtauk** [comment] 2019-07-20 14:53
> > I imagine the border around the control was to deal with the issue of the tail arrow being lost because of the box shadowing.
> 
> the border looks really bad, what do you think? @mdtauk @jevansaks

I personally like the border on the TeachingTip, but I have an issue (#895) which is calling for borders on all elevated Acrylic surfaces and controls.

**Comment by chigy** [comment] 2019-07-22 20:52
@HppZ , @mdtauk is right about the border. We indeed added it to make sure the tip is visible. We experimented with a lot of options and we settled with the current design.

We also have the border around the control because the control would be invisible (you cannot tell against the background) when the page's color and flyout's color are the same. As common control creators, we have to anticipate what developer can end up doing and we cannot guarantee that color the page support would always accommodate the necessary contrast.

If you can come up with a cleaver idea that solves the issue, we would be happy to look at that option to see if it works for the common control!

**Closed** 2019-08-16 00:14 UTC
Labels: area-Shadows, question
