### ISSUE TITLE
Unable to set Window Title in XAML

### ISSUE THREAD

**Issue by mrlacey** [microsoft/microsoft-ui-xaml#3689] opened 2020-11-24 16:56 UTC
**Describe the bug**

In WinUI3preview3, unable to build a project if set the Window Title in XAML.

**Steps to reproduce the bug**

1. Create a new `Blank App, Packaged (WinUI in Desktop)`
2. Change the content of `MainWindow.xaml` to add the following on line 8

```xml
<Window
    x:Class="App68.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App68"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    Title="my app"
    mc:Ignorable="d">
```

3. Build the solution
4. See an  exception:

`MainWindow.xaml(8,5): XamlCompiler error WMC0612: The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found`

5. Remove the change in the XAML file and set the window Title in the constructor. e.g.:

```cs
    public MainWindow()
    {
        this.InitializeComponent();
        this.Title = "my app";
    }
```

6. Run the app and see the title displayed correctly.

**Expected behavior**

It should be possible to set the Window Title in XAML.

**Screenshots**

**Version Info**

NuGet package version:  Microsoft.WinUI 3.0.0-preview3.201113.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes  |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by StephenLPeters** [comment] 2020-11-24 22:20
@ocalvo FYI, who was it that finished up the title bar work in winui3?

**Comment by riverar** [comment] 2021-02-16 21:21
⚠ Still a bug in Preview 4. @StephenLPeters

**Comment by riverar** [comment] 2021-05-14 20:36
Still broken in WinUI 3 production, Project Reunion 0.5.7.

**Comment by antoprd** [comment] 2021-06-02 20:41
Still Broken.

**Comment by Darkatek7** [comment] 2021-06-30 12:33
still not fixed

**Comment by klauszou** [comment] 2021-07-05 09:31
Still not fix in Reunion 0.8

**Comment by riverar** [comment] 2021-08-15 21:30
Still broken in 1.0-experimental1. @marb2000 We're not going to ship 1.0 with the inability to set the window title right? RIGHT? 😂

**Comment by dotMorten** [comment] 2021-08-15 22:01
@riverar "inability' might be a little much. I mean it is technically possible:
```cs
        [DllImport("Microsoft.UI.Windowing.Core.dll", CharSet = CharSet.Unicode)]
        private static extern IntPtr GetWindowIdFromWindowHandle(IntPtr hwnd, out Microsoft.UI.WindowId result);

        private static void SetTitle(string title, Window window)
        {
            var handle = WinRT.Interop.WindowNative.GetWindowHandle(window);
            IntPtr whatIsThisReturnValueEvenFor = GetWindowIdFromWindowHandle(handle, out var windowId);
            var appWindow = Microsoft.UI.Windowing.AppWindow.GetFromWindowId(windowId);
            appWindow.Title = "New window title";
        }
```

However is this an acceptable amount of code to manage your window, in a v1.0 release? (hint: The answer isn't `yes`).

I'm worried people will take one look at WinUI and see that basic window management APIs are more or less non-existent (or as shown above overly complicated to use), and write off WinUI before it even had a chance.

**Comment by riverar** [comment] 2021-08-15 22:03
@dotMorten 🤠 Thankfully we can `this.Title = "Floop";` but it's pretty ridiculous that this still blows up XAML with an obscure error.

**Comment by dotMorten** [comment] 2021-08-15 22:24
There is an (ugly) workaround though. In your Window sub class add this:
```cs
        /// <summary>
        /// Gets or sets the window title.
        /// </summary>
        public new string Title
        {
            get => base.Title;
            set => base.Title = value;
        }
```

However I'm worried that the lack of window management APIs and `Title` can't even be set from XAML as we're used to is going to be extremely off-putting to users. Is the amount of code you need to write acceptable, just to do basic management of your window, in a v1.0 release? (hint: I don't think the answer isn't yes).

I'm worried people will take one look at WinUI and see that basic window management APIs are more or less non-existent (or as shown above overly complicated to use), and write off WinUI before it even had a chance.

**Comment by riverar** [comment] 2021-08-15 22:25
@dotMorten 🤠 It's pretty ridiculous that this still blows up XAML with an obscure error. But agreed. 👍

**Comment by dotMorten** [comment] 2021-08-15 22:35
I had started writing [WinUIEx](https://github.com/dotMorten/WinUIEx) as a temporary stop-gap to the lack of Windowing APIs, but hadn't bothered completely finishing it up or publishing a nuget, because I naturally assumed basic Windowing APIs would be in 1.0, and I was also reluctant because the entire implementation just feels like one giant band-aid. It seems like I need to do bring this all the way to at least close some of these obvious gaps for 1.0.

**Comment by fourdragons** [comment] 2021-09-20 00:23
Still... present in Preview 1. They got less than two months to fix this.

**Comment by riverar** [comment] 2021-09-20 00:45
Don't think this is getting fixed any time soon, now that there's a _workaround_. 😞

**Comment by jorcus** [comment] 2021-10-10 06:01
It's still broken. I'm currently using the constructor method for temporary fix.
`this.Title = "App Title";`

**Comment by marb2000** [comment] 2021-10-11 17:20
Unfortunately, per the latest engineering plan, the bug fix won't make the v1.0 Stable release (GA) and was moved to v1.1

**Comment by pjmlp** [comment] 2021-10-16 08:14
It is really off putting to still invest into WinUI stack instead of WPF, when such basic features don't make it to  1.0.

One more hurdle since Windows 8 rewrites roller coaster started.

**Comment by younky-yang** [comment] 2021-11-18 13:38
This is ridiculous as a so basic function doesn't work on the official version 1.0.

**Comment by alexmro** [comment] 2021-11-28 00:13
Yep, just decided to try UWP and WinUI but this thing is just horrible to work with. Back to good ole win32 it is

**Comment by olabacker** [comment] 2021-12-07 12:55
Not sure if directly related but when using MAUI blazor app template targeting Windows, title doesnt seem to work either from setting in xaml or ctor of mainpage.

**Comment by esaMark** [comment] 2021-12-19 17:56
Similar to what olabacker found, when using a .NET MAUI App template targeted on Windows the title won't appear when defined either in MainPage.xaml or in MainPage.xaml.cs.
I tried adding dotMorten's snippet to MainPage.xaml.cs and setting the property in the constructor, but still no title appeared.  As this template produces a WinUI app, presumably it's the same problem.  
Apps for scientific data processing can use upwards of 50 forms and dialogs in old Windows Forms app speak, having a form or window title is essential otherwise the user won't know where they are or how what they are seeing relates to documentation..

**Comment by mstasak** [comment] 2022-03-08 18:32
The bug which could not die.  <hopeful> Maybe in 1.1? </hopeful>

**Comment by bugproof** [comment] 2022-03-28 10:25
Are you serious? You can't even set title in WinUI3 app?

**Comment by Symbai** [comment] 2022-03-28 11:12
> I have set it programatically in App.xaml.cpp and it worked. Seems like a XAML only issue.

Which is exactly what the first post says. But yeah, that's just one of the wonderful experience developers get when they try out WinUI.

**Comment by dotMorten** [comment] 2022-03-30 23:48
Just tried with the latest `v1.1.0-preview1` and still doesn't work. And to make matters worse, the error message is extremely unhelpful with no indication about what property or where:
> 1>MainWindow.xaml(8,22): XamlCompiler error WMC0612: The XAML Binary Format (XBF) generator reported syntax error '0x09C4' : Property Not Found

**Comment by CompCodeNet** [comment] 2022-04-27 18:03
Perhaps MainWindow Title was purposefully left for a while out so engineers would have practice implementing WinUI3 properties. Is it a coincidence that the main bind sample is the Title property?  :-) 
https://docs.microsoft.com/en-us/windows/uwp/cpp-and-winrt-apis/binding-property

I use C++ coming from C# XAML, so I'm finding this to be a great exercise. :-)

**Comment by younesaassila** [comment] 2022-05-16 12:08
Still broken a year and a half later...

**Comment by soobakjonmat** [comment] 2022-06-18 10:36
Welp still not fixed. I think we'll have to wait about at least 5 more years for this issue to be fixed cause apparently there are other 2.7k current open issues.

**Comment by dotMorten** [comment] 2022-06-18 16:04
@soobakjonmat I agree this is annoying. But it is by no means a showstopper like many other issues. You can still set it in code behind or use something like WinUIEx’s WindowEx to do it.

**Comment by CompCodeNet** [comment] 2022-06-18 16:47
A (better) alternative is to use Win32 directly and have full control.

**Comment by soobakjonmat** [comment] 2022-06-19 00:34
> @soobakjonmat I agree this is annoying. But it is by no means a showstopper like many other issues. You can still set it in code behind or use something like WinUIEx’s WindowEx to do it.

Yeah I'm just saying that it's probably gonna take a while to get it fixed. I'm using `this.Title = ` so no problem there.
And while reading my own comment again, it does sound sarcastic and apologies for that. I guess I was a bit grumpy while I was writing that comment cause I haven't slept all night.

**Comment by oold** [comment] 2022-09-01 14:01
Maybe it's worth mentioning that the workaround for C++ looks like this:
```c++
MainWindow::MainWindow()
{
    InitializeComponent();
    this->Title(L"Your Window Title");
}
```

**Comment by breenbob** [comment] 2022-11-17 16:43
Still not working without workaround...

**Comment by CompCodeNet** [comment] 2022-12-24 03:41
I think we have been making a XAML title assumption for WinUI based on WPF experience. Code samples here imply that Title in XAML is not intended and by leaving it out of XAML, we are led to discover the Title Bar capabilities:
https://learn.microsoft.com/en-us/windows/apps/develop/title-bar?tabs=wasdk

I.e.: I think that we have a "Works as intended" status here.

**Comment by dotMorten** [comment] 2022-12-24 03:52
I think it’s a reasonable assumption. What I think went wrong here is the window is a non-WinUI window without the WinUI stuff in it (like inheriting from Dependency Object, understand styling etc). WinUI should make its own Window type that wraps the underlying Windows App SDK window and provide a proper developer experience that’s expected in 2022. I don’t buy the argument that it is as designed and existing expectations aren’t valid - if you want people to move over you need to provide an experience at least on par. The entire Window class is a mess to work with and needs something designed properly for the xaml developer.

**Comment by CompCodeNet** [comment] 2022-12-24 04:16
I see your point. Perhaps the idea is to abstract the concept of "app look and feel" and provide a somewhat lower-level app UI shell while providing more power and control to the engineers/designers. Thus, a company can create a product app brand UI shell (outer framework) XAML template. I do like the idea of more control. Easy enough to make a template with a Title property and Title Bar is example. Perhaps one of us here could make a basic template with Title property and offer it as the standard wrapper that you mention. I can keep it mind and if I offer one, I'll mention here. Open source has its advantages but also might require a bit of a shift in mindset. :-)

**Comment by MarkBrainfire** [comment] 2023-02-01 04:43
WinUI is the future of Windows desktop development.  And this is STILL broken.  
Microsoft needs to double the size of its WinUI development team.
WinUI desktop applications are the future of software development as I point out in my website:

https://WinUI3.org

**Comment by AMArostegui** [comment] 2023-03-27 11:52
Agreed, this is only a small annoyance, but such a simple feature to be reported and still broken after almost two years is scary.

Makes one think about Microsoft commitment to WinUI3.

So far I haven't hit a roadblock. Yes many minor bugs, a workaround here and there, but nothing remarkable. But it looms large the possibility of finding a major bug in the future that Microsoft won't address.

**Comment by bpulliam** [comment] 2023-05-09 22:55
The ability to set the Title was added in WinAppSDK 1.3, but there was an issue with it.  That issue has been fixed in 1.3.1 that is now available.

**Comment by dotMorten** [comment] 2023-05-09 22:57
@bpulliam Don't you mean `v1.3.230502000` ? Congrats on 171000 builds in a month :-D

**Comment by bpulliam** [comment] 2023-05-09 22:59
Well played :)

**Comment by riverar** [comment] 2023-05-10 00:28
For those reading this and are confused like I was, Windows App SDK 1.3 Preview 1 (referred here as 1.3.1) shows up on NuGet as `1.3.230228005-preview1` for whatever silly reason. You'll want to add that to your project to pick up this change.

**Comment by riverar** [comment] 2023-05-10 00:32
So, I tried this and it doesn't seem to work. Did either of you try it?

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/475132/11f0c422-b0f3-4c9d-815d-eb2b5284b5c8)

**Comment by bpulliam** [comment] 2023-05-10 00:44
@riverar 1.3.1 = 1.3.230502000 (built May 2, 2023), not preview1 (1.3.230228005-preview1 built Feb 28, 2023).  Its about 2 months newer :).

**Comment by riverar** [comment] 2023-05-10 01:04
Ah, was going off the documentation which has no mention of 1.3.1, sigh. ![image](https://github.com/microsoft/microsoft-ui-xaml/assets/475132/b76fe89f-9708-4bb9-a744-2aa0d81a1640)

**Comment by riverar** [comment] 2023-05-10 01:08
Wow it works. The end of an era!

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/475132/3076e4b4-08f5-43d2-ab20-ed9f31a8dcbf)

**Comment by bpulliam** [comment] 2023-05-10 16:39
> Ah, was going off the documentation which has no mention of 1.3.1, sigh. ![image](https://user-images.githubusercontent.com/475132/237251958-b76fe89f-9708-4bb9-a744-2aa0d81a1640.png)

The docs have been updated (https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-131-13230502000).  Thanks for the heads-up

**Closed** 2023-05-10 21:25 UTC
Labels: team-Reach, product-winui3, area-TitleBar, fixed-in-WinAppSDK1.3

**Comment by jozefizso** [comment] 2023-06-09 15:39
How is one supposed to teach developers to use WinUI 3 when the first steps with application requires searching for weird C++ code hacks?

Window sizes were solved in .NET Framework 1.0

**Comment by MartinFraAtGitHub** [comment] 2023-06-15 09:17
> > Ah, was going off the documentation which has no mention of 1.3.1, sigh. ![image](https://user-images.githubusercontent.com/475132/237251958-b76fe89f-9708-4bb9-a744-2aa0d81a1640.png)
> 
> The docs have been updated (https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/stable-channel#version-131-13230502000). Thanks for the heads-up

They say there: "Fixed issue causing apps to crash when setting the Window Title in XAML, a new capability added in 1.3.0. For more information, see GitHub issue [#3689](https://github.com/microsoft/microsoft-ui-xaml/issues/3689)."

**Comment by Qiu233** [comment] 2023-10-01 09:36
But setting `ExtendsContentIntoTitleBar` still gives the same error.

**Comment by ynkdir** [comment] 2024-06-05 14:56
WindowsAppSDK 1.5.3, unpackaged c#/c++

This doesn't work when setting DisableXbfGeneration=true or using XamlReader::Load().

MainWindow.xaml

```xml
<?xml version="1.0" encoding="utf-8"?>
<Window
    x:Class="App1.MainWindow"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d"
    Title="hello">

    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
    </StackPanel>
</Window>
```

error

```
Failed to assign to property 'Microsoft.UI.Xaml.Window.Title'. [Line: 10 Position: 5]
```

Program fails at https://github.com/microsoft/microsoft-ui-xaml/blob/2a60e27c591846556fa9ec4d8f305afdf0f96dc1/dxaml/xcp/core/core/elements/CWindow.cpp#L73

**Comment by ynkdir** [comment] 2024-06-07 14:40
At this line https://github.com/microsoft/microsoft-ui-xaml/blob/2a60e27c591846556fa9ec4d8f305afdf0f96dc1/dxaml/xcp/core/core/elements/CWindow.cpp#L70

When DisableXbfGeneration=false, type of args.m_value is valueString.
When DisableXbfGeneration=true, type of args.m_value is valueObject.
