### ISSUE TITLE
Proposal: ColorPicker horizontal mode

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#1637] opened 2019-11-18 22:40 UTC
## API spec proposal: https://github.com/microsoft/microsoft-ui-xaml-specs/pull/53

# Proposal: ColorPicker horizontal mode

## Summary

The current layout of the ColorPicker is mainly designed to grow in height. However in some cases, it may be better to have the ColorPicker to be wide, not high.
## Rationale
* In cases were height is limited, the ColorPicker is problematic to use
* Retemplating the whole control would not be that simple, since we need to completely reorganize the layout
* A horizontal ColorPicker may be easier to integrate due to the fact, that most content and screens are wide

## Scope
| Capability | Priority |
| :---------- | :------- |
| Developers have the possibilities to use ColorPickers where height is very limited, but width is not | Must |
| The ColorPicker has a display mode, similiar to NavigationView where the developer can specify wether it should layout vertically or horizontally | Should |

## Open Questions

# Examples

### A standard ColorPicker using Orientation "Vertical"
```xaml
<muxc:ColorPicker IsAlphaEnabled="True" Orientation="Vertical"/>
```

![ColorPicker_VerticalMode](https://user-images.githubusercontent.com/16122379/77758835-f4bea800-7033-11ea-9d9a-98b1589876f9.png)

### Standard ColorPicker using Orientation "Horizontal"
```xaml
<muxc:ColorPicker IsAlphaEnabled="True" Orientation="Horizontal"/>
```
![ColorPicker_HorizontalMode](https://user-images.githubusercontent.com/16122379/77758831-f38d7b00-7033-11ea-9f01-0b1b63b65c94.png)

# Remarks

# API Notes

Orientation: The orientation determining wether to display horizontally or vertically.
# API Details

```c#
[webhosthidden]
unsealed runtimeclass ColorPicker
{
    /// Gets or sets the DisplayMode of the ColorPicker
    Windows.UI.Xaml.Controls.Orientation Orientation = Windows.UI.Xaml.Controls.Orientation.Vertical;
}
```

**Comment by mdtauk** [comment] 2019-11-18 23:23
Maybe the control should be made responsive, so it can re-arrange to fit the space available to it?
![image](https://user-images.githubusercontent.com/7389110/69102444-62414300-0a5a-11ea-8ae6-b3ffeb9f9eb7.png)



Win32:
![image](https://user-images.githubusercontent.com/7389110/69101556-cf070e00-0a57-11ea-8208-2d51e026c97c.png)

UWP:
![image](https://user-images.githubusercontent.com/7389110/69101574-dc23fd00-0a57-11ea-8547-b35bdb29face.png)

Adobe:
![image](https://user-images.githubusercontent.com/7389110/69101653-1b524e00-0a58-11ea-8b05-44a27f38ac06.png)

**Comment by chingucoding** [comment] 2019-11-19 09:19
Yes that would definitely be an improvement. Maybe this could also be a setting, just like the NavigationView handles it.

**Comment by robloo** [comment] 2019-11-19 18:43
It would also be great if we could re-arrange the RGB entry text boxes themselves into a horizontal layout. A layout like what is shown below would be ideal to reduce space. That said, I'm pretty sure this was done due to localized text taking up a lot more space -- would be great to have it as an option though.

![image](https://user-images.githubusercontent.com/17993847/69175785-6dd05080-0ad2-11ea-88e0-c7ec9adeb833.png)

**Comment by jevansaks** [comment] 2019-11-20 19:11
@chingucoding (or anyone else) this seems reasonable to us. The next step would be to propose an API for it and go through the API spec process. In this case it should be as simple as making a markdown file from [this template](https://github.com/microsoft/microsoft-ui-xaml-specs/blob/master/spec_template.md) and putting out a PR. Once that's approved then we can greenlight this for implementation.

**Comment by mdtauk** [comment] 2019-11-20 19:47
**Does something like this make any sense @chingucoding ?**

NavigationView.Arrangement = Arrangement.Vertical

- Arrangement.Vertical
- Arrangement.VerticalCompact
- Arrangement.Horizontal
- Arrangement.HorizontalCompact

**Comment by chingucoding** [comment] 2019-11-20 20:23
> **Does something like this make any sense @chingucoding ?**
> 
> NavigationView.Arrangement = Arrangement.Vertical
> 
> * Arrangement.Vertical
> * Arrangement.VerticalCompact
> * Arrangement.Horizontal
> * Arrangement.HorizontalCompact

Something like this would make sense. However what is "Compact" in this case? There is already a way to achieve compact sizing. Also there should be an "Auto" mode shouldn't it?

**Comment by mdtauk** [comment] 2019-11-20 20:29
I would say @robloo 's layout could be compact, maybe "inline" may be better to avoid confusion with the Compact Density.

**Comment by chingucoding** [comment] 2019-11-20 20:49
I think this "inline" mode won't work as some color translations can get lengthy and might overflow. For example: "Xanh dương" is blue in vietnamese. How should this be handled? Should the ColorPicker get wider even though our intent is to save space?

**Comment by mdtauk** [comment] 2019-11-20 21:08
> I think this "inline" mode won't work as some color translations can get lengthy and might overflow. For example: "Xanh dương" is blue in vietnamese. How should this be handled? Should the ColorPicker get wider even though our intent is to save space?

*Inline* does not necessarily equate to less space.  It is more a declaration of how the constituent parts of the control arrange themselves.

**Comment by chingucoding** [comment] 2019-11-20 22:10
> Inline does not necessarily equate to less space. It is more a declaration of how the constituent parts of the control arrange themselves.

Maybe having this as separate option, such as "UseInlineLabels" would be better than having that built into the DisplayMode. If this would be something that you would think that would be a useful addition, I will be happy to add that to the API spec :)

I have also created an API spec PR over at [microsoft/microsoft-ui-xaml-specs](https://github.com/microsoft/microsoft-ui-xaml-specs), FYI @jevansaks

**Comment by mdtauk** [comment] 2019-11-21 16:30
![image](https://user-images.githubusercontent.com/7389110/69356907-1f5eb580-0c7c-11ea-83cc-83558c4e0678.png)

Here is my thinking for both the Orientation and the Mode of the colour picker

**Comment by shaheedmalik** [comment] 2019-11-22 00:45
> ![image](https://user-images.githubusercontent.com/7389110/69356907-1f5eb580-0c7c-11ea-83cc-83558c4e0678.png)
> 
> Here is my thinking for both the Orientation and the Mode of the colour picker

Maybe instead of having different ones just have one that you can resize. 

If you have the size at 240x500 for instance would be horizontal and if you have one at 500x240 would be vertical for example.

That way there would be some consistency.

**Comment by chingucoding** [comment] 2019-11-22 08:26
> > ![image](https://user-images.githubusercontent.com/7389110/69356907-1f5eb580-0c7c-11ea-83cc-83558c4e0678.png)
> > Here is my thinking for both the Orientation and the Mode of the colour picker
> 
> Maybe instead of having different ones just have one that you can resize and is fluid.
> A horizontal one might be better in landscape mode and a vertical might be better in portrait mode.
> Maybe you can set the initial orientation and then it can fluidly adapt to the screen positioning.
> 
> That way there would be some consistency.

I can see why that may be useful however this "Auto" may a quite complicated: Which orientation is preferred? What if there is not enough space in either orientation?

In addition to this, the easiest way would be to let developers choose which orientation is appropriate for their use case.

**Comment by Felix-Dev** [comment] 2019-11-22 10:18
I would leave that up to the developer. With adaptive triggers, the developer can easily change the Orientation whenever they want to.

**Comment by shaheedmalik** [comment] 2019-11-22 13:33
> I can see why that may be useful however this "Auto" may a quite complicated: Which orientation is preferred? What if there is not enough space in either orientation?
> 
> In addition to this, the easiest way would be to let developers choose which orientation is appropriate for their use case.

I was thinking the developer sets the size and have the control wrap around based on the dimensions.
500x240 might be horizontal while 240x500 would be vertical for example. Then the user can freely resize it based on preference.

Maybe have an initial orientation set like horizontal or vertical but then have it still fluid?

**Comment by robloo** [comment] 2019-11-23 17:21
Concerning putting all components on the same horizontal line:

![image](https://user-images.githubusercontent.com/17993847/69482618-b1d19700-0deb-11ea-959b-68273bf02000.png)

I thought of three possibilities to fix the potential localized text length issue:

 1. The text could have trimming...
 2. The control could resize itself (I realize that's not ideal at all)
 3. Just use color component abbreviations like Photoshop(r) has: just 'R', 'G', 'B' 

I like #3 the best and would argue if the user is editing the components directly they already know what they are doing.

**Comment by chingucoding** [comment] 2019-11-25 19:11
> I thought of three possibilities to fix the potential localized text length issue:
> 
> 1. The text could have trimming...
> 2. The control could resize itself (I realize that's not ideal at all)
> 3. Just use color component abbreviations like Photoshop(r) has: just 'R', 'G', 'B'
> 
> I like #3 the best and would argue if the user is editing the components directly they already know what they are doing.

I agree, that the second option is not optimal. Maybe #3 is the best solution. I think this should be an option for the developer to choose, what is suitable for them.

**Comment by mdtauk** [comment] 2019-11-25 19:16
> > I thought of three possibilities to fix the potential localized text length issue:
> > 
> > 1. The text could have trimming...
> > 2. The control could resize itself (I realize that's not ideal at all)
> > 3. Just use color component abbreviations like Photoshop(r) has: just 'R', 'G', 'B'
> > 
> > I like #3 the best and would argue if the user is editing the components directly they already know what they are doing.
> 
> I agree, that the second option is not optimal. Maybe #3 is the best solution. I think this should be an option for the developer to choose, what is suitable for them.

Things like HSV or HSB, and even CMYK - could use the Initials, but if this is the case, could the full word still appear with a Tooltip when hovering over the TextBox or the Header?

And is there any thought about using NumberBoxes for these controls?

**Comment by chingucoding** [comment] 2019-11-25 19:24
> And is there any thought about using NumberBoxes for these controls?

Yes, that is a brilliant idea! The R,G,B and Opacity textbox should be replaced with NumberBoxes.

**Comment by robloo** [comment] 2019-11-26 15:27
@mdtauk, @chingucoding Using the NumberBox in the ColorPicker was one of the original design goals. 

https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-500140203

> one example is WinUI's own ColorPicker control. It includes a hexadecimal input box. It also includes a number of other number entry TextBoxes. It might be worth looking into the possibility of updating ColorPicker to use the new NumberBox control as a way of validating the new control. If NumberBox can simplify the current implementation of ColorPicker, that would be a win.

I know @SavoySchuler discussed this at Microsoft internally:

https://github.com/microsoft/microsoft-ui-xaml/issues/483#issuecomment-500618794

> As you mentioned at the water cooler this morning, being able to removed a lot of code behind from ColorPicker by replacing its instances of TextBox + local validation logic with NumberBox could be a win in its own right.

**Comment by mdtauk** [comment] 2019-11-26 17:40
Good memory recall @robloo 

If the Suffix/Prefix feature for the TextBox is accepted #784  They could be used to further minify the ColorPicker

![image](https://user-images.githubusercontent.com/7389110/69658301-d63fa480-1073-11ea-85c2-667942e6ca0d.png)

**Comment by robloo** [comment] 2019-11-26 23:58
@mdtauk I really, really like that design. I was also thinking of putting the abbreviations next to the text boxes but adding at a prefix like (especially if TextBox gets that implemented) that would take it to a whole new level!

As you stated earlier, that could be the VerticalCompact display mode as well. We could theoretically keep the standard Vertical option if people wanted it.

**Comment by chingucoding** [comment] 2020-03-09 21:35
@kikisaints @ranjeshj What would be the next steps for this proposal? 😅
Is this good to go and can be implemented? If so I would be happy to do that.

**Comment by ranjeshj** [comment] 2020-03-27 12:58
Thanks for the great discussion. @chingucoding can you update the proposal text at the top with the proposed API (and some mock screenshots)? @kikisaints @chigy If this design is good with you, we can start a spec PR.

**Comment by chingucoding** [comment] 2020-03-27 13:06
I've updated the proposal and also added a link the currently running API review PR which you can find here: https://github.com/microsoft/microsoft-ui-xaml-specs/pull/53

**Comment by chigy** [comment] 2020-03-27 16:44
@chingucoding , to be clear, you are only proposing the horizontal layout not the swatches that was mentioned in the middle of the discussion? In other words, what I see in the proposal up top is what you are proposing, right?

**Comment by mdtauk** [comment] 2020-03-27 16:49
> @chingucoding , to be clear, you are only proposing the horizontal layout not the swatches that was mentioned in the middle of the discussion? In other words, what I see in the proposal up top is what you are proposing, right?

I think it was decided to separate the swatches as a separate proposal.  So only an option to layout the ColorPicker control in the current Vertical layout, or a new Horizontal layout.

**Comment by chingucoding** [comment] 2020-03-27 17:09
@chigy Yes exactly, only the horizontal mode is in this proposal. The swatches live in another proposal: https://github.com/microsoft/microsoft-ui-xaml/issues/1659

**Comment by niels9001** [comment] 2020-05-25 10:25
Not sure if this is the right issue since there are a couple around the ColorPicker control.

In the PowerToys settings application the use is able to set 3 different colors. We now have 3 colorpickers, which take a LOT of space and it's actually not really glanceable to see what color is selected.

We came up with the following solution, using a dropdown button with a colorpicker in the flyout:

https://user-images.githubusercontent.com/9866362/82731988-a6174c80-9d0a-11ea-824a-247a30b96f0d.gif

Works really well! Saves space and the selected colors are very easy to identify.

My proposal would be for this issue: can we have a minimized/compact/selected color state that will open up the colorpicker?

**Comment by chingucoding** [comment] 2020-05-25 13:30
I am not sure if I understand your request correctly @niels9001 .

So you want a compact state which shows a color or a very small layout that upon invoking opens the full color picker?

In that case I think someone already asked about this (or even create a proposal for this), but the WinUI team decided that it currently is not really "worth" it, since it is fairly easy to integrate a colorpicker with a DropDownButton or SplitButton.

**Comment by robloo** [comment] 2020-05-25 13:51
@niels9001 This is a duplicate of https://github.com/microsoft/microsoft-ui-xaml/issues/2309 "Add a ColorSwatchPicker" control. Could you please duplicate your comment on that issue? I also think this is an important control to add to WinUI.

**Comment by niels9001** [comment] 2020-05-25 13:57
@chingucoding Exactly. I can imagine this might beyond the control.

@robloo Ah yes, I see now that there was already a concept that does the exact same thing. Duplicate :)

**Comment by niels9001** [comment] 2020-06-23 08:40
With iOS 14, Apple released a new inline ColorPicker flyout:

![image](https://user-images.githubusercontent.com/9866362/85380988-d3d7f700-b53d-11ea-9684-1451aab16407.png)

More info here: https://developer.apple.com/videos/play/wwdc2020/10205/
I like how everyone is laid out: spectrum, grid view, sliders and the swatches.

**Comment by mdtauk** [comment] 2020-06-24 11:47
> 
> 
> With iOS 14, Apple released a new inline ColorPicker flyout:
> 
> ![image](https://user-images.githubusercontent.com/9866362/85380988-d3d7f700-b53d-11ea-9684-1451aab16407.png)
> 
> More info here: https://developer.apple.com/videos/play/wwdc2020/10205/
> I like how everyone is laid out: spectrum, grid view, sliders and the swatches.

It is good to look at how others approach the same design problem - the inline/flyout ColorPicker is a different proposal though #2309 , and this seems more like a rethink of how to design the entire ColorPicker, rather than adding Horizontal arrangements for the control.

**Comment by niels9001** [comment] 2020-06-24 12:13
Is it though? The iOS colorpicker shows how they are handling different modes and stuff like swatches.

To me it's confusing how we are tracking UX/layout improvements in two separate topics. Adding swatches will have (major) impact on decisions made on the layout and this issue. And vice versa.

In my opinion it would be good to come up with 1 proposal/spec where we tackle both horizontal mode and the swatches (basically redesigning the entire thing). Discuss and design the layout/UX first (taking into consideration stuff like color swatches) and then break out into issues to add the actions. If we'd list all the things we think should be added or improved to the ColorPicker control, we can design a proposal to validate against that.

**Comment by mdtauk** [comment] 2020-06-24 12:20
> 
> 
> Is it though? The iOS colorpicker shows how they are handling different modes and stuff like swatches.
> 
> To me it's confusing how we are tracking UX/layout improvements in two separate topics. Adding swatches will have (major) impact on decisions made on the layout and this issue. And vice versa.
> 
> In my opinion it would be good to come up with 1 proposal/spec where we tackle both horizontal mode and the swatches (basically redesigning the entire thing). Discuss and design the layout/UX first (taking into consideration stuff like color swatches) and then break out into issues to add the actions. If we'd list all the things we think should be added or improved to the ColorPicker control, we can design a proposal to validate against that.
>
Well it did start as a more all encompassing topic, but it was suggested that the asks be broken out into separate issues.

I am impatient, and I would like to see the whole control re-thought, with support for adaptive layouts to fit the panel its placed in, as well as flyout modes, and the additional swatches, and colour lists.  The PowerToys color picker could benefit from this, and there is still a disparity with the "better" layouts used by Fluent UI.

But Microsoft moves at its own pace it seems, especially with UI changes.

**Comment by robloo** [comment] 2020-06-24 14:10
First, there is another good idea in the Apple control. We could separate numerical input entirely into a 3rd tab and add sliders. The tabs would be:

 1. Spectrum to visually select a color
 2. Swatches to select a pre-defined color
 3. Components to create a color using numerical component values

This design would also make the control relatively 'square-shaped' so there may be little need for adaptive layouts like horizontal/vertical -- it wold also be perfect to place in a flyout.

@mdtauk, I have an idea that has been used for other controls such as the TabView. How about we implement all of these changes in the Windows Community Toolkit? We could conceivably make a brand new control there very quickly. Once everything has been worked out it would allow Microsoft to accept these changes in WinUI more quickly.

I would be willing to write the control in C# for the Community Toolkit. I need something like this for my existing apps. Long term I would like to bring this to Avalonia as well and that would be a great first step.

Main improvements:
 1. Adding the 3 tabs including swatches (With any adaptive layout still needed (horizontal, vertical))
 2. Changing numerical component values can be done with a slider as well as NumberBox
 3. Implement the control as a flyout button

Strategy:
 1. Get the go-ahead from michael-hawker, I'll file an issue over there shortly
 2. Work on changes in the Windows Community Toolkip repo (robloo develops, mdtauk supports designs)
 3. A few rounds of community feedback and bugfixes to stabilize the new control
 4. Create a very clear WinUI proposal based on everything learned in the toolkit -- get it accepted
 5. Port the control over to WinUI (chingucoding could probably do that although I don't want to volunteer him)
 6. Done! (I will probably port to Avalonia as well)

**Comment by robloo** [comment] 2020-06-24 14:33
I created the issue on the Community Toolkit tracker: https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3363. Would like everyone's comments.

**Comment by gabbybilka** [comment] 2021-07-28 22:02
Hey folks,

As you may have seen with the opening of this [spec](https://github.com/microsoft/microsoft-ui-xaml/pull/5453) we have re-invested into this feature to add an additional Orientation property to ColorPicker to support a horizontal layout. We are aiming to include this in WinUI 2.7. Thank you to @chingucoding for hopping in to help spec and develop this feature! 🎉

**Comment by gabbybilka** [comment] 2021-08-10 22:46
Hello! As an update we have our new design comps for this feature and a theme resource addition to support them:

Horizontal ColorPicker with input boxes:
![Design comp of Horizontal ColorPicker with input boxes](https://user-images.githubusercontent.com/20007011/128943807-04665a9d-81b6-4189-9a90-f255ccc97eac.png)

Horizontal ColorPicker with input boxes (with redlines):
![Redline design comp of Horizontal ColorPicker with input boxes](https://user-images.githubusercontent.com/20007011/128943993-40333114-c7d0-44c1-9738-09cb7ada16ea.png)

Horizontal ColorPicker without input boxes:
![Design comp of Horizontal ColorPicker without input boxes](https://user-images.githubusercontent.com/20007011/128943851-d9cb5d95-310f-4d97-ba46-a34cee4849fd.png)

Horizontal ColorPicker without input boxes (with redlines):
![Redline design comp of Horizontal ColorPicker without input boxes](https://user-images.githubusercontent.com/20007011/128944031-94629d70-6be6-40a3-8a15-956159417f32.png)

A few notes:

- Horizontal ColorPicker will **not** react to and support the IsMoreButtonVisible boolean. We explored a few options for this functionality (let us know if you want to see some comps 😄) and determined that to properly support we would need to introduce a new design pattern. Since the More/Less button was intended to truncate the control to save on vertical space, similar functionality for horizontal mode would involve left to right expansion which we don't currently have support for. If IsMoreButtonVisible is set to true, the control will act as if it were false. If the lack of this functionality is impactful for your app, please let us know and share your usecase.
- We are introducing a new theme resource to allow apps to reduce the right margin of the control when input boxes are enabled. We included the extra white space here to support localization of the different label strings to prevent unintended control truncation. We believed that allowing the control to dynamically resize would create a lack of consistency in different languages. If you would like to remove this space (with the danger that the control may not show the input labels/spacing properly in a different language) the option is available to do so.

**Comment by gabbybilka** [comment] 2021-09-15 22:32
Feature in WinUI 2.7, thanks all!

**Closed by gabbybilka** 2021-09-15 22:32 UTC
Labels: feature proposal, working on it, area-ColorPicker, team-Controls
