### ISSUE TITLE
ComboBox items not scaled properly when inside a Viewbox

### ISSUE THREAD

**Issue by RexfelisLOC** [microsoft/microsoft-ui-xaml#1187] opened 2019-08-21 23:25 UTC
**Describe the bug**

If a ComboBox is placed inside a Viewbox, the ComboBox items are scaled too large.

**Steps to reproduce the bug**
1) Add a Viewbox to XAML
2) Create a ComboBox as a child of the Viewbox
3) Add some items to the ComboBox
4) Notice items are too large when the popup dialog is opened

**Expected behavior**

ComboBox items should be scaled properly when inside a Viewbox as they have before the recent Windows update.

**Screenshots**

Notice how the selected item is off and the ComboBox items do not fit within the popup dialog

<img width="960" alt="screenshot_08212019_182237" src="https://user-images.githubusercontent.com/16925431/63474969-b11e1300-c440-11e9-92fc-38ed7afcada9.png">

**Version Info**
UWP Min 16299
UWP Max 18362

NuGet package version: 
N/A

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes   |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Xbox                      | Yes   |

**Additional context**

**Comment by YuliKl** [comment] 2019-08-22 17:39
@RexfelisLOC, can you explain why you need to put a ComboBox inside a Viewbox?

The items are added into a popup, which is its own distinct layer in terms of z-order. So I'm guessing that while the ComboBox entry point is inside the Viewbox, the popup with items is completely unaware of the Viewbox's existence. 

I think we'll need to come up with an alternate solution for your scenario, so it would be great to understand what you need to accomplish.

**Comment by RexfelisLOC** [comment] 2019-08-22 17:44
The thing is this was working fine till a recent Windows or Visual Studio update.  Not sure which is responsible for the change.  I use a Viewbox to keep my UI sized properly for all resolutions.

**Comment by YuliKl** [comment] 2019-08-22 17:55
>  I use a Viewbox to keep my UI sized properly for all resolutions.

That's not necessarily the mechanism I would recommend. Have you read through any of our documentation, like [Screen sizes and breakpoints](https://docs.microsoft.com/en-us/windows/uwp/design/layout/screen-sizes-and-breakpoints-for-responsive-design) or [Responsive design techniques](https://docs.microsoft.com/en-us/windows/uwp/design/layout/responsive-design) for alternative ideas?

**Comment by RexfelisLOC** [comment] 2019-08-22 17:57
Yes, but the app was designed years ago before all of that documentation was available and not something I want to refactor unless I absolutely have to.  It's been working fine for the past few years until the recent update and it is occurring on both Desktop and Xbox One.

**Comment by RexfelisLOC** [comment] 2019-08-22 18:03
Surely all standard controls contained inside a Viewbox should scale appropriately?

**Comment by jevansaks** [comment] 2019-08-22 18:07
I'm guessing the change was that in the Windows 1903 update we changed many flyouts to be windowed by default (so that they could escape window bounds and work properly in XAML islands scenarios) -- but that makes things like inheriting scale not work as well.

**Comment by RexfelisLOC** [comment] 2019-10-24 13:12
Is this something that will be fixed?  It makes some controls in a Viewbox unusable if the user doesn't have scale set to 100%.

**Comment by kmelmon** [comment] 2019-10-27 01:34
Confirmed this is a bug that was introduced in 1903.  There is a work-around, which is to set a very small rotation transform on your ViewBox.  The rotation will be so small that it won't have any visisble effect on screen, but this will disable windowed popups for its children, including the ComboBox popup.  Thus the bug will be masked.

Here's an example of how to do the workaround:

        <Viewbox Width="100" Height="100">
            <Viewbox.RenderTransform>
                <RotateTransform Angle="0.001"></RotateTransform>
            </Viewbox.RenderTransform>
            <StackPanel>
                <ComboBox>
                    <ComboBoxItem>item</ComboBoxItem>
                    <ComboBoxItem>item</ComboBoxItem>
                    <ComboBoxItem>item</ComboBoxItem>
                    <ComboBoxItem>item</ComboBoxItem>
                    <ComboBoxItem>item</ComboBoxItem>
                    <ComboBoxItem>item</ComboBoxItem>
                </ComboBox>
            </StackPanel>
        </Viewbox>

**Comment by Zofware** [comment] 2020-03-02 00:32
@kmelmon OMG what a lifesaver. Thanks for posting this workaround. I wish I had seen it a few months ago but it's still a big help. Thank you!

**Comment by chingucoding** [comment] 2020-08-23 17:57
@StephenLPeters I think this is something that can only be fixed with WinUI 3, since most of ComboBox and ViewBox are not in WinUI 2.

**Comment by Zofware** [comment] 2021-10-01 14:57
FWIW, the rotation workaround doesn't work anymore. I'm not sure when it stopped working, but it might have been with the release of Microsoft.UI.Xaml 2.6.x or 2.7.0.

**Comment by StephenLPeters** [comment] 2021-10-04 21:07
@kmelmon thoughts on how this work around could have regressed?

**Comment by Zofware** [comment] 2021-10-05 18:40
The Xaml that I'm scaling with a Viewbox uses DropDownButtons rather than ComboBoxes. At least for those I was able to scale the MenuFlyoutItem text by applying a style with a FontSize that is controlled by the same factor I use to scale the Viewbox. A similar technique might work for ComboBoxes too but I haven't tried it. Also, this only works for MenuFlyoutItems containing simple text. More complicated content (e.g. images, etc.) would require a more involved solution of course.

**Closed** 2023-08-04 11:59 UTC
Labels: needs-winui-3, team-Rendering, no-issue-activity
