### ISSUE TITLE
CoreTextServicesManager.GetForCurrentView() throws exceotion in WinUI3 for Desktop preview 4

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4239] opened 2021-02-18 14:28 UTC
When running the following code

` var manager = CoreTextServicesManager.GetForCurrentView();`

The following exception is thrown

> System.Runtime.InteropServices.COMException: 'The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))'

The calling thread is the ui thread. Looks like a bug.

**Comment by StephenLPeters** [comment] 2021-02-19 00:29
As of preview 4 api's which require a core window now throw, these are largely the API's that have CurrentView in their title likeGetForCurrentView() @anawishnoff Do we have documentation for this issue?  It is strange that we are throwing a wrong thread exception.. @Austin-Lamb Should we look at the exception we throw for this?

**Comment by anawishnoff** [comment] 2021-02-19 15:08
As @StephenLPeters said, this is an expected issue of Preview 4 - most GetForCurrentView() methods are no longer supported in Desktop apps. You can see more info in [this doc](https://github.com/microsoft/microsoft-ui-xaml/blob/master/docs/winrt-apis-for-desktop.md) (which is getting regularly updated as we identify more APIs and their workarounds).

**Comment by arivoir** [comment] 2021-02-19 15:31
I found that doc helpful, for other issues, but I don't find any replacement for CoreTextServicesManager. Did I miss something?

**Comment by JesseCol** [comment] 2021-02-19 17:04
Hi @arivoir , I actually expect CoreTextServicesManager.GetForCurrentView() to work fine in this context.  I've tried it in a simple WinUI 3 Preview 4 Desktop app and it doesn't throw.  Would you be willing to share a larger sample of your repro so I could have a look?

**Comment by arivoir** [comment] 2021-02-19 17:24
The issue can be easily reproduced by executing that code in a custom control constructor

```
public sealed class CustomControl1 : Control
{
    public CustomControl1()
    {
        this.DefaultStyleKey = typeof(CustomControl1);
        var manager = CoreTextServicesManager.GetForCurrentView();
        var editContext = manager.CreateEditContext();
    }
}
```

And then in xaml

`        <local:CustomControl1 />
`

**Comment by arivoir** [comment] 2021-02-19 17:25
There it is the repro sample
[App4.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6011775/App4.zip)

**Comment by JesseCol** [comment] 2021-02-19 18:58
Ah, thanks @arivoir  -- turns out this is only working in insider Windows builds, unfortunately all the shipping versions of Windows are failing in the way you've mentioned.  We'll add this to the list.  Sorry for the oversight and thanks for letting us know.

**Comment by arivoir** [comment] 2021-05-20 19:22
@Austin-Lamb why was this closed. Is there any way to use text services now?

**Comment by arivoir** [comment] 2021-07-01 18:25
This bug is still happening in WinUI3 version 0.8

I updated the repro sample
[App4.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6750095/App4.zip)

**Comment by anawishnoff** [comment] 2021-07-06 13:10
@JesseCol any update on the support for CoreTextServicesManager? Last we looked, it was only working on Insider builds.

**Comment by AdamBraden** [comment] 2021-09-21 17:59
Confirmed this is fixed in Win11.
@arivoir - Since this is an OS fix, do you have need to service this back to Win10?

**Comment by arivoir** [comment] 2021-09-21 19:48
I need it everywhere WinUi3 runs, so yes, I need it in Win10 too

**Comment by curia-damiano** [comment] 2021-09-24 13:15
Hi @andrewleader and @AdamBraden , I would need it for Windows 10 1809 IoT Enterprise LTSC

**Comment by curia-damiano** [comment] 2022-01-17 14:26
Hi @andrewleader and @AdamBraden , are there any updates about this issue?
Can the fix be backported to Windows 10 1809 IoT Enterprise LTSC please?

**Comment by arivoir** [comment] 2022-12-06 14:57
The exception is no longer thrown, but the TextUpdating event is not raised for English keyboard. is this expected?

**Closed** 2023-08-03 22:41 UTC
Labels: bug, team-Reach, product-winui3, no-issue-activity
