### ISSUE TITLE
WinUI 3 Alpha Theading problem with ObservableCollection<T> databinding

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/microsoft-ui-xaml#1557] opened 2019-11-06 14:34 UTC
Hi,

I get this **'System.Runtime.InteropServices.COMException: 'The application called an interface that was marshalled for a different thread. (Exception from HRESULT: 0x8001010E (RPC_E_WRONG_THREAD))''** exception when I add an item to an ObservableCollectionOfT which is databound to the ItemsSource of a ListView.

```xml
<Page x:Class="App3.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:App3"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d"
      Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

    <Grid Padding="8" RowSpacing="8">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="1*" />
        </Grid.RowDefinitions>
        <Button Content="{x:Bind MyCollection.Count, Mode=OneWay}"
                Click="Button_Click" />
        <ListView ItemsSource="{x:Bind MyCollection}"
                  Grid.Row="1" />
    </Grid>
</Page>
```

```
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Controls;
using System.Collections.ObjectModel;

namespace App3 {
    public sealed partial class MainPage : Page {

        private ObservableCollection<int> MyCollection { get; } = new ObservableCollection<int>() { 1, 2, 3 };

        public MainPage() {
            this.InitializeComponent();
        }

        private void Button_Click(object sender, RoutedEventArgs e) {
            MyCollection.Add(MyCollection.Count + 1);
        }
    }
}
```

**Steps to reproduce the bug**
Take the code and click on the button.

**Expected behavior**
No Exception

**Screenshots**
![image](https://user-images.githubusercontent.com/9335559/68307049-df5bd800-00aa-11ea-80ed-1a047ae634fa.png)

![image](https://user-images.githubusercontent.com/9335559/68306449-dfa7a380-00a9-11ea-8290-7a4842ef146d.png)

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19002)              | Yes  |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

**Comment by kmahone** [comment] 2019-11-06 17:46
This is a known limitation of the WinUI 3 Alpha release. The issue is with how certain special WinRT interfaces (such as Windows.UI.Xaml.INotifyPropertyChanged) get projected into .net (as System.ComponentModel.INotifyPropertyChanged). This same mapping does not currently work for the WinUI types (under Microsoft.UI.Xaml.*). The workaround for the Alpha is to not implement the .net interface (System.*) and instead explicitly implement the WinRT interface (Microsoft.*).

You can see an example of this in Xaml Controls Gallery:
https://github.com/microsoft/Xaml-Controls-Gallery/blob/winui3alpha/XamlControlsGallery/CollectionsInterop.cs

If you replace your ObservableCollection with this custom collection, the scenario should start to work.

**Comment by harvinders** [comment] 2019-11-06 23:19
@kmahone, @jevansaks 
It would be nice to collect these limitations at one place. The page https://docs.microsoft.com/en-us/uwp/toolkits/winui3/ already lists some.

**Comment by kmahone** [comment] 2019-11-06 23:24
@harvinders, I agree. This limitation actually is called out on that page, under the **Controls and features** list, but it is not very clear and the work-around is not really elaborated on.

@jesbis @MikeHillberg can we get that page updated with a clearer description of this limitation? I expect this is an issue that will be hit a lot, and it is not obvious what the problem is when it is hit.

**Comment by jevansaks** [comment] 2019-11-07 04:17
Anyone can make a PR to edit the docs page. :) But I think it's a good idea to have some more specific guidance. @ranjeshj you did the workarounds for the test apps, right? Could you write up a blurb to add as a new section in there, like "If you see an exception like this then ..."

**Comment by sonnemaf** [comment] 2019-11-07 08:57
> This is a known limitation of the WinUI 3 Alpha release. The issue is with how certain special WinRT interfaces (such as Windows.UI.Xaml.INotifyPropertyChanged) get projected into .net (as System.ComponentModel.INotifyPropertyChanged). This same mapping does not currently work for the WinUI types (under Microsoft.UI.Xaml.*). The workaround for the Alpha is to not implement the .net interface (System.*) and instead explicitly implement the WinRT interface (Microsoft.*).
> You can see an example of this in Xaml Controls Gallery:
> https://github.com/microsoft/Xaml-Controls-Gallery/blob/winui3alpha/XamlControlsGallery/CollectionsInterop.cs
> If you replace your ObservableCollection with this custom collection, the scenario should start to work.

The TestObservableCollection solved my problem. It is a great workaround. Thanks!

**Comment by kmahone** [comment] 2019-11-07 17:15
> Anyone can make a PR to edit the docs page. :) But I think it's a good idea to have some more specific guidance. @ranjeshj Ranjesh Jaganathan FTE you did the workarounds for the test apps, right? Could you write up a blurb to add as a new section in there, like "If you see an exception like this then ..."

I've created a PR that updates the docs:
https://github.com/MicrosoftDocs/winrt-related/pull/154

**Comment by Karl-Bridge-Microsoft** [comment] 2019-11-07 17:48
PR revised slightly and merged. Should be live soon.

**Comment by jevansaks** [comment] 2019-11-08 03:44
Thanks @kmahone and @Karl-Bridge-Microsoft !!

**Comment by chrisglein** [comment] 2020-01-31 00:59
@kmahone With the workaround in progress for this and the docs updated... is this bug intended to capture fixing those projections? Or can we consider this issue closed with your doc update?

**Comment by kmahone** [comment] 2020-01-31 01:01
@chrisglein this needs a real fix in WinUI3. I believe @MikeHillberg is investigating.

**Comment by ranjeshj** [comment] 2020-01-31 04:47
I believe the fix needs for this needs to be in the csharp projection (cswinrt)

**Comment by ranjeshj** [comment] 2020-03-19 11:58
@Austin-Lamb @stevenbrix as FYI.

**Comment by stevenbrix** [comment] 2020-04-15 16:55
I'm going to close this is duplicate of #1981

**Closed by stevenbrix** 2020-04-15 16:55 UTC
Labels: needs-triage, team-Markup, winui3α
