### ISSUE TITLE
TitleBar cannot be accessed in TabWindowing sample.

### ISSUE THREAD

**Issue by Vinothini-V** [microsoft/microsoft-ui-xaml#3611] opened 2020-10-20 08:18 UTC
**Describe the bug**
TitleBar cannot be accessed in TabWindowing sample in WinUI 3

**Steps to reproduce the bug**

1. Go to 'TabViewWindowingSamplePage'
2. Click on 'Launch window'
3. Now hover the TabItems in the window. But it cannot be accessed.

**Expected behavior**
We should able to access this. 

**Actual behavior**
Now we unable to click on the TabItems.

**Screenshots**

**Version Info**

Gallery version (found on Settings page): 
1.2.22.0

OS version : 1909 Build : 18363.1139

Windows 10 version:
- [ ] Insider Build (xxxxx)
- [ ] May 2020 Update (19041)
- [x] November 2019 Update (18363)
- [ ] May 2019 Update (18362)
- [ ] October 2018 Update (17763)
- [ ] April 2018 Update (17134)
- [ ] Fall Creators Update (16299)
- [ ] Creators Update (15063)
- [ ] Anniversary Update (14393)

Device form factor:
- [x] Desktop
- [ ] Mobile
- [ ] Xbox
- [ ] Surface Hub
- [ ] IoT

**Additional context**
In master branch we have this line to get access of the Titlebar content, 

Window.Current.SetTitleBar(CustomDragRegion); but now in winuipreview3 branch this method is not available.

**Comment by codendone** [comment] 2020-11-19 05:01
Duplicate of #3450.

**Closed by codendone** 2020-11-19 05:01 UTC
Labels: area-AppWindow, winui3preview
