### ISSUE TITLE
Low frame rate

### ISSUE THREAD

**Issue by heckerpowered** [microsoft/microsoft-ui-xaml#7373] opened 2022-07-14 14:29 UTC
### Describe the bug

This problem is extremely obvious on high frame rate monitors, not only my project, but also the WinUi3 project example (WinUI 3 Gallery) has this problem, the animation is not smooth and lagging, while WinUi2 does not have this problem, so I think it is a bug.

### Steps to reproduce the bug

No steps，any animation is lagging and the frame rate is very low.

### NuGet package version

WinUI 3 - Windows App SDK 1.1.2

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by marb2000** [comment] 2022-07-14 21:38
Thanks, @heckerpowered. We're working to fix this scenario in WInAppSDK 1.2 timeframe. Although we can't commit it yet.

(@krschau, this is our internal AzDevOps feature request #39831498)

**Comment by YorkFieldX** [comment] 2022-07-16 01:06
Can confirm the issue is very noticeable by comparing identical UWP Template and WinUI3 Template apps side by side on 120hz touchscreen display. While UWP is very smooth as expected, WinUI 3 app appears to be dropping frames on scrolling and any other animations. Hopefully there's a fix soon

**Comment by gabbybilka** [comment] 2022-12-02 01:02
:tada:`Microsoft.WindowsAppSDK.1.2.221109.1` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.0/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221109.1)

cc: @bpulliam

**Comment by lhak** [comment] 2022-12-02 12:33
This issue is still present in 1.2 even at 60Hz frame rate. Just compare the WinUI2 / WinUI3 gallery when scrolling in the "All controls" section.

**Comment by ygorcortes** [comment] 2022-12-27 01:58
It isn't fixed on my end either... If I put both the WinUI 2 Gallery and the WinUI 3 Gallery side by side on my 144 hz display and start scrolling on each of them I can clearly see that the frame rate on the WinUI 3 Gallery is severely limited.

**Comment by Void48** [comment] 2023-01-12 05:10
This still hasn't been fixed? @gabbybilka 
https://user-images.githubusercontent.com/85196642/211982479-27ab317e-121b-4c24-8b15-e87b52782535.mp4

**Comment by Nevodev** [comment] 2023-04-02 15:46
This bug is still not fixed.

**Comment by EugenM88** [comment] 2023-04-15 21:55
Hello, i would like to know a status update for this issue, my WinUI3 App also is lower fps than normal on my 144hz monitor. If i set it to 60hz its as smooth as 60fps, if i set my monitor to 144hz then the app instead of refreshing at 144fps its doesnt even reach 60fps anymore making any animation ugly and jittery.

When do you have plans to fix this specific issue? Thank you very much in advance!

**Comment by EugenM88** [comment] 2023-04-17 13:32
UPDATE: I have found where the bug problem is, this happens in applications wherever i use the mainwindow.dispatcherqueue, example:
DispatcherQueue.TryEnqueue(() =>
                    {
//some UI binding changes and other movements and animations updated right here
                    });

**Comment by bpulliam** [comment] 2023-04-20 21:08
There is a fix for frame rate issues on high refresh monitors in 1.3.  Please give that build a try.

**Comment by EugenM88** [comment] 2023-04-28 22:41
> There is a fix for frame rate issues on high refresh monitors in 1.3. Please give that build a try.

I was testing with 1.3 latest preview build, problem still remains, at 144hz the app responsiveness semms jittery while at 60hz it's silky smooth

**Comment by beeradmoore** [comment] 2023-07-20 08:13
@gabbybilka , can we get this issue re-opened as it still appears to be broken.

**Comment by gabbybilka** [comment] 2023-07-20 15:55
@bpulliam can you take a look?

**Comment by ghostidentity** [comment] 2023-07-24 19:38
Seems like webview has no problem. https://mtagab-my.sharepoint.com/:v:/g/personal/admin_mtagab_app/EaPff7mNldNLpuJ35lvLTU4BzwyOdPryyoDB8WrK5yWGjw?e=eWaxKG

**Comment by SnowSquire** [comment] 2023-09-30 18:24
This issue still exists

https://github.com/microsoft/microsoft-ui-xaml/assets/40239844/bab84963-3894-4f28-9624-c05dfd1f09b6

the source video is at 180fps i don't know if github will recompress it

**Comment by ChewWorker** [comment] 2023-10-16 22:59
@SnowSquire / @Void48 can you confirm the version of WinAppSDK you are using, or see if it reproes on 1.4? Thanks!

**Comment by Fefedu973** [comment] 2023-11-07 20:50
same issue

**Comment by Fefedu973** [comment] 2023-11-07 21:01
NEED REOPEN

**Comment by yaira2** [comment] 2023-11-10 14:24
@bpulliam this appears to still be an issue.

**Comment by pritster5** [comment] 2023-11-10 20:32
Definitely still an issue

**Comment by ChewWorker** [comment] 2023-12-13 00:42
@pritster5  @yaira2  @Fefedu973 can you confirm what version of WinAppSDK you are using?

Thanks!

**Comment by yaira2** [comment] 2023-12-13 02:21
1.4

**Comment by EugenM88** [comment] 2023-12-19 10:15
The very low fps issue has been fixed for me after upgrading my project to .net 6, .net 8 also works just fine.

However, there is still a fatal flaw with timers, i cannot for the life of me understand why a timer cannot go below 8ms... even if you set said timer lower, it will still take alot of time for it to start and stop than 8ms, dispatcher.tryenqueue might also have this issue. For performance applications this is unacceptable behavior.

**Comment by bpulliam** [comment] 2024-02-29 15:05
Looking at the history, there are multiple issues on multiple controls all pulled into this one issue.  Many fixes have gone in already.  If you have an issue with low frame rate, please open a new issue with your exact scenario, including control and WinAppSDK version. Thanks!

**Closed by bpulliam** 2024-02-29 15:05 UTC
Labels: bug, team-CompInput, area-Performance, product-winui3
